- README.md
> README.md: remove double hr

- cmd/client/main.go
- server/runtime.go
Add support for container status. 
@runcom PTAL.
> Support for container status

- oci/oci.go
- server/runtime.go
> Add started time and state to container status

- conmon/conmon.c
> Separate tty/non-tty and add opt parsing

- oci/oci.go
> Add lock around container state access

- server/runtime.go
> Update state after creating container

- conmon/conmon.c
- oci/oci.go
- server/runtime.go
This PR adds support for basic integration wtih conmon. Next, we can get container exit code and finish time.
@runcom PTAL.
> Conmon integration

- oci/oci.go
- server/runtime.go
> Report exit code and finish time on container status

- testdata/README.md
> testdata/README.md: fix examples

- server/runtime.go
- server/server.go
@mrunalp PTAL - I hope I got everything right here and seems it's not deadlocking anywhere here
> server: locking around server components

- HACKING.md
> *: add HACKING.md

- cmd/server/main.go
@mrunalp PTAL
```sh
$ sudo ./ocid --debug
$ sudo ./ocid --debug --log server.log
$ sudo ./ocid --debug --log-format json --log server.log
```
> server: add debug to ocid

- cmd/client/main.go
- server/utils.go
> *: Failed -> failed in errors

- Makefile
`--update` is ignored in gometalinter now.
> Fixes to the Makefile

- oci/oci.go
- utils/utils.go
> Convert status to exit code

- .tool/lint
- server/utils.go
> Increase the deadline to 30 seconds in lint

- server/sandbox.go
> Check if container in a pod is already stopped before stopping it

- cmd/client/main.go
> Better output formatting for container status

- testdata/container_exit_test.json
> Add an example config to demonstrate container exit code

- server/sandbox.go
> Automate the creation of the pod sandbox rootfs

- README.md
Because soon we'll have tests and we love them :smile: (https://github.com/kubernetes-incubator/ocid/pull/43)
> README.md: add Travis status image

- README.md
@sarahnovotny PTAL
cc: @runcom to address some concerns raised in #12 
> Remove "compliant" from README

- cmd/server/main.go
> cmd/server: fix cmd name and usage

- server/sandbox.go
> Include pod namespace in the pod name

- Makefile
- test/README.md
> test: add README.md and add TESTFLAGS to Makefile

- cmd/client/sandbox.go
- server/sandbox.go
> Populate state in pod status

- .gitignore
- Dockerfile
- Makefile
- cmd/server/main.go
- hack/.vendor-helpers.sh
- oci/oci.go
- server/container.go
- server/image.go
- server/sandbox.go
- server/server.go
- server/utils.go
- test/helpers.bash
> Fix the build for ocid to cri-o rename

- server/container.go
- server/sandbox.go
Allow specifying pod IDs by unique prefixes 
> Pod short ID

- README.md
> README.md: fix Travis badge

- README.md
> Rename OCID to cri-o in the README

- cmd/client/container.go
- server/container.go
> List containers

- Makefile
> [make] Add install and uninstall targets

- test/helpers.bash
> Remove unnecessary sleep from tests

- server/container.go
- test/ctr.bats
> Stop container first if it is running on RemoveContainer

- server/sandbox.go
- test/pod.bats
@runcom Similar treatment for pod removal. PTAL.
> Pod remove stop

- README.md
This also changes the badges to be flat, and moves them down to
allow more room for future badges.
> Add badge for Go Report Card

- Makefile
- cmd/server/main.go
- docs/ocid.8.md
- oci/oci.go
- server/server.go
- test/helpers.bash
This pull request includes the man page pull, will rebase when that gets merged.
> Conmon should not be installed in /usr/bin.

- test/ctr.bats
> Add container lifecycle test

- server/sandbox.go
- test/ctr.bats
> Remove containers from in-memory state on pod remove

- server/sandbox.go
> Add annotations for pods

- server/sandbox.go
> Include attempt in the pod name

- .gitignore
- Makefile
- cmd/server/main.go
- conmon/Makefile
- pause/.gitignore
- pause/Makefile
- pause/pause.c
- server/sandbox.go
- server/server.go
- test/helpers.bash
- utils/utils.go
This is working on improving the situation described in #91.
> Dockerless pause rootfs

- README.md
@ipbabble PTAL. Also, you need #66 to install/uninstall
> [readme] Add intructions for getting started

- server/container.go
> Add support for short IDs for containers

- README.md
Nit.. mentioning the make install.tools target.
> mention the need to add install tools

- Makefile
> remove install dependencies so they don't build

- server/container.go
> Cleanup container directory and state on creation failure

- server/sandbox.go
@runcom PTAL
Same treatment as we did with containers.
> Refactor to use helper method to get sandbox from request

- conmon/conmon.c
conmon uses getopt() even if it's a glib based application,
and therefore could use the much more modern and flexible
GOptionContext mechanism. Fixes #89
Signed-off-by: Alvaro Lopez Ortega <alvaro@gnu.org>
> Ports conmon from getopt() to glib's parsing mechanism

- cmd/client/sandbox.go
- server/sandbox.go
Close #107 
@mikebrow PTAL
(This could use some additional tests in a follow up).
> Return pod metadata in pod list and status APIs

- cmd/client/container.go
> Allow overriding the container name in the config

- docs/ocid.8.md
Also sort options in alphabetic order.
> Fix up man page with missing options

- cmd/server/main.go
- docs/ocid.8.md
Missing options from man page, and sort options alphabetically, as best
we can.
> Cleanup help and add options to man page

- cmd/server/main.go
So that @rhatdan doesn't spend time sorting flags :) (joking)
I've opened https://github.com/urfave/cli/pull/544 upstream also.
> cmd/server: sort flags

- server/sandbox.go
- test/ctr.bats
- test/restore.bats
Fix #127
@mrunalp @mikebrow PTAL
> server/sandbox: fix add/release pod/ctr ids and names

- cmd/client/container.go
- server/container.go
- test/ctr.bats
This adds container filtering support. Label filtering will come in a follow on.
> Add container filtering support

- hack/vendor.sh
- vendor/src/github.com/opencontainers/runc/libcontainer/label/label_selinux.go
- vendor/src/github.com/opencontainers/runc/libcontainer/system/syscall_linux_386.go
- vendor/src/github.com/opencontainers/runc/libcontainer/system/sysconfig.go
Vendor opencontainers/runc#1109 in order to fix running tests with selinux enabled
@mrunalp PTAL
> vendor opencontainers/runc 3abefdff18bc201199c5dfd0e91e941cb4c61376

- cmd/client/container.go
- oci/oci.go
- server/container.go
- test/ctr.bats
- vendor/src/k8s.io/kubernetes/pkg/fields/doc.go
- vendor/src/k8s.io/kubernetes/pkg/fields/fields.go
- vendor/src/k8s.io/kubernetes/pkg/fields/requirements.go
- vendor/src/k8s.io/kubernetes/pkg/fields/selector.go
- vendor/src/k8s.io/kubernetes/pkg/selection/operator.go
With this we can filter containers by labels
ocic ctr list --label tier=backend
I'll add a test.
@runcom @mikebrow PTAL
> Add support for label filtering

- cmd/client/container.go
- test/ctr.bats
> Allow adding labels at container create time

- Makefile
> Fix up Makefile, to only build when needed

- cmd/client/sandbox.go
- server/sandbox.go
- test/pod.bats
Same treatment as what we have for containers.
@runcom PTAL
> Pod filtering support

- Makefile
let the package builders of the distros do it
Signed-off-by: Lai Jiangshan <jiangshanlai@gmail.com>
> don't gzip the manpages

- Makefile
Signed-off-by: Lai Jiangshan <jiangshanlai@gmail.com>
> unistall or cleanup uncompressed manpages when requested

- cmd/client/main.go
Signed-off-by: Yao Zengzeng <yaozengzeng@zju.edu.cn>
> add timeout for ocic connect to server

- server/version.go
> Set the version to what kubelet expects

- oci/oci.go
> Revert "oci: cast timestamp to int64"

- server/container.go
- server/sandbox.go
- utils/utils.go
These are very useful to figure out what calls kubelet is making. 
> Add more debugs

- cmd/server/config.go
- oci/oci.go
- server/config.go
- server/server.go
Signed-off-by: HaoZhang <crazykev@zju.edu.cn>
> make conmon process's env configurable

- README.md
- docs/ocid.conf.5.md
1. update build step in README.md
2. update missing docs for #153 , sorry for that
Signed-off-by: HaoZhang <crazykev@zju.edu.cn>
> update README.md and ocid.conf.5.md

- cmd/server/main.go
> Add timestamps to logs

- Makefile
> Fix installation of ocid.systemd

- Makefile
This simplifies installation and building on various architectures and distributions. For example, openSUSE doesn't have a separate `%{_libexecdir}` so we need to keep that in mind.
Signed-off-by: Aleksa Sarai asarai@suse.de
> makefile: add make arguments

- server/container.go
- server/sandbox.go
Signed-off-by: Mrunal Patel mpatel@redhat.com
> Add logging for all container/sandbox responses

- Makefile
> Fix install of unit file and configuration file

- server/server.go
fix https://github.com/kubernetes-incubator/cri-o/pull/179#issuecomment-257492326
Signed-off-by: Crazykev <crazykev@zju.edu.cn>
> restore pod annotations when restart ocid

- utils/utils.go
This logs more information, when available, about how the child processes that we reap terminated.
> Log more information about exited children

- cmd/server/config.go
- server/config.go
- server/image.go
- server/sandbox.go
- server/server.go
This PR just cleans up some of the hardcoding we had lying around inside ocid.
Signed-off-by: Aleksa Sarai asarai@suse.de
> server: make more things configurable

- conmon/conmon.c
> Add syslog support

- cmd/client/container.go
- cmd/client/sandbox.go
make time display in ocic correctly, since we have already change it to nanosecond in #192
Signed-off-by: Crazykev <crazykev@zju.edu.cn>
> fix ocic time display

- server/container_create.go
- server/sandbox_run.go
- vendor/src/github.com/opencontainers/runtime-tools/generate/generate.go
- vendor/src/github.com/opencontainers/runtime-tools/generate/seccomp/consts.go
- vendor/src/github.com/opencontainers/runtime-tools/generate/seccomp/parse_action.go
- vendor/src/github.com/opencontainers/runtime-tools/generate/seccomp/parse_architecture.go
- vendor/src/github.com/opencontainers/runtime-tools/generate/seccomp/parse_arguments.go
- vendor/src/github.com/opencontainers/runtime-tools/generate/seccomp/parse_remove.go
- vendor/src/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default.go
- vendor/src/github.com/opencontainers/runtime-tools/generate/seccomp/syscall_compare.go
- vendor/src/github.com/opencontainers/runtime-tools/generate/spec.go
> *: bump opencontainers/runtime-tools

- .tool/lint
> Skip lint on vendored code

- Makefile
- contrib/rpm/Makefile
- contrib/rpm/ocid.spec
Signed-off-by: Dan Walsh dwalsh@redhat.com
> Add ocid.spec to build rpms

- Makefile
- README.md
- server/seccomp/seccomp.go
- server/seccomp/seccomp_unsupported.go
Fix #218 
@mrunalp @Crazykev PTAL
> *: add seccomp buildtag

- .gitignore
- Makefile
- completions/bash/kpod
- docs/kpod-launch.1.md
- docs/kpod.1.md
We need to start off with man pages and bash completion
support for kpod.
Also fix Makefile to install kpod by default
> Add missing man pages and bash completions for kpod

- server/container_list.go
- server/sandbox_list.go
- test/apparmor.bats
- test/ctr.bats
- test/helpers.bash
- test/pod.bats
> fix filter by truncated ids (+ apparmor tests)

- server/container_stop.go
- server/sandbox_stop.go
- test/ctr.bats
- test/pod.bats
> server: sync ctr state before checking it

- server/sandbox_stop.go
Fix #232 
(tested locally with @sameo's config https://github.com/kubernetes-incubator/cri-o/issues/232#issuecomment-265130836 and cni plugins under `/opt/cni/bin/`)
@mrunalp PTAL
> server: check netns path on pod stop

- Makefile
> Makefile: fix the creation of man5

- test/testdata/sandbox_config_seccomp.json
> testdata: Add missing closed curly

- server/container_execsync.go
- server/server.go
> Fix couple of lint issues

- .tool/lint
- server/container_create.go
- server/sandbox.go
- server/sandbox_remove.go
- server/sandbox_run.go
- server/server.go
Closes #242 
@runcom PTAL
note: We need to break runpodsandbox further but I will make separate PRs for that.
> Add support for pod /dev/shm that is shared by the pod ctrs

- test/helpers.bash
- test/pod.bats
@mrunalp PTAL
This scenario was a question by @sameo on IRC yesterday cause his PR was breaking this scenario. Adding a test to make sure anyone won't regress on this.
> test: add restart ocid with pod stopped test

- oci/oci.go
From http://pastebin.com/6qWez2aM you can see the old behavior on line 19, and the new behavior on line 23
> oci: pass through error output from runc

- server/sandbox_run.go
> Remove unnecessary check for mount label for /dev/shm

- server/container_create.go
> server: fix call to logrus.Warnf

- server/container_create.go
> container: Store annotations under ocid/annotations

- server/apparmor/apparmor.go
- server/apparmor/apparmor_common.go
- server/apparmor/apparmor_supported.go
- server/apparmor/apparmor_unsupported.go
- server/container_create.go
- server/server.go
- test/apparmor.bats
- test/helpers.bash
- test/seccomp.bats
- test/testdata/fake_ocid_default
Since we will come across the same issue like [this](https://github.com/docker/docker/issues/29097), so open this pr to avoid that issue.
cc @feiskyer @runcom @mrunalp 
Signed-off-by: Xianglin Gao <xlgao@zju.edu.cn>
> reload default apparmor profile if it is unloaded

- README.md
> README.md: add CNI setup

- server/container_create.go
Should fix #260 if I understood @jjlakis correctly
@mrunalp PTAL
> Read command from ContainerCreateRequest

- README.md
- cmd/client/sandbox.go
- test/apparmor.bats
- test/ctr.bats
- test/pod.bats
- test/restore.bats
- test/seccomp.bats
- test/testdata/README.md
> cmd/client: move pod create to pod run

- oci/oci.go
@runcom @sameo PTAL. See if this helps with races during tests.
> Add operation lock for containers

- server/sandbox.go
ns.Close() will not remove and unmount the networking namespace
if it's not currently marked as mounted.
When we restore a sandbox, we generate the sandbox netns from
ns.GetNS() which does not mark the sandbox as mounted.
Fix https://github.com/kubernetes-incubator/cri-o/issues/273
There currently is a PR open to fix that in the ns package:
https://github.com/containernetworking/cni/pull/342
but meanwhile this patch fixes a netns leak when restoring a pod.
> sandbox: Force netns unmount and removal when restoring

- test/testdata/sandbox_config.json
> Fixup cgroup in test sandbox config

- Dockerfile
Signed-off-by: Michal Rostecki <michal@kinvolk.io>
> Clean apt archives and source directories in Dockerfile

- cmd/server/config.go
- cmd/server/main.go
- conmon/conmon.c
- oci/oci.go
- server/config.go
- server/container_create.go
- server/sandbox_run.go
- server/server.go
> Add support cgroup config and systemd cgroups

- server/sandbox_remove.go
When removing a pod sandbox or one of its containers, don't forget to remove the ID of the item from the corresponding ID index.
> Clear index entries when removing pods or ctrs

- oci/memory_store.go
Find this typo in go report, so fix it to make go report more happy.
Signed-off-by: Xianglin Gao <xlgao@zju.edu.cn>
> Fix misspell to make go report more happy

- Makefile
Closes: #300
Signed-off-by: Jonathan Yu <jawnsy@cpan.org>
> Install to /usr/local to avoid conflicts with vendor binaries

- server/sandbox_run.go
For host network pod there's no need to prepare interfaces to let namespaces communicate - so there's no need to execute plugins. 
Found it while working on kubernetes. Kubelet spawns 2 pods with host networking (kube-proxy, flannel) and networking plugin tried to create 2 veth pairs (1 for each pod) with the same `eth0` name in the host namespace that causes a crash.
@lukasredynk Could you provide some additional information? 
cc @mrunalp @runcom @sameo 
BTW. Right now, kubelet starts with all services, and my kubernetes cluster works fine, I am still debugging problem with image pulling that seems to be the last one before running CRI e2e.
> sandbox_run: Do not run net plugin in host namespace

- Makefile
> Move GOPATH check to a phony target

- README.md
> Fix README to tell user to pull the image for container

- README.md
- tutorial.md
Get rid of our examples in favor of @kelseyhightower's tutorial
> README.md: replace examples with kelsey's tutorial

- lock.json
- manifest.json
- vendor/github.com/containers/image/docker/docker_client.go
- vendor/github.com/containers/image/storage/storage_image.go
> dep: Update containers/image to 1c202c5d85d2ee531acb1e91740144410066d19e

- README.md
Fixes #357 
Signed-off-by: Lorenzo Fontana <fontanalorenz@gmail.com>
> Specify glibc-static as build requirement

- .travis.yml
> Travis CI notifications to Freenode #ocid

- .travis.yml
> .travis.yml: add go1.8

- README.md
Signed-off-by: Malhar Vora  <mlvora.2010@gmail.com>
> Correct package name for pkg-config

- README.md
> Use png for logo as github doesn't display the svg

- oci/oci.go
- server/container_create.go
- server/sandbox_run.go
> Run conmon under cgroups (systemd)

- oci/oci.go
Signed-off-by: Yao Zengzeng yaozengzeng@zju.edu.cn
> add timeout when wait to get container pid from conmon

- cmd/ocic/main.go
- cmd/ocid/main.go
@runcom @sameo @rhatdan @cyphar PTAL
We will tag this as 0.1 on the repo. 
> Bump up version to 0.1

- oci/oci.go
If I create a sandbox pod and then restart the ocid service, the
pod ends up in a stopped state without an exit file.  Whether this is
a bug in ocid or not we should handle this case where a container exits
so that we can clean up the container.
This change just defaults to exit code to -1 if the container is not
running and does not have an exit file.
> If the container exit file is missing default exit code to -1

- oci/oci.go
Travis is hitting the 3 seconds intermittently.
@runcom @sameo @rhatdan PTAL
> Increase the timeout value for create container

- server/container_create.go
We need to support a 2x2 matrix of use cases with both
kubelet giving us (command, args) slices and the OCI
image config file giving us (ENTRYPOINT, CMD) slices.
Here we always prioritize the kubelet information over
the OCI image one, and use the latter when the former
is incomplete.
Not that this routine will be slightly simpler when
issue #395 is fixed.
> server: Fix the OCI process arguments build routine

- Makefile
- README.md
Make it easier to copy/paste and run.
> Cleanup prerequisites section in README.md

- oci/oci.go
- server/container_list.go
- server/container_status.go
- server/sandbox.go
- server/sandbox_list.go
- server/sandbox_run.go
- server/sandbox_status.go
- server/server.go
- test/copyimg/copyimg.go
> Fix lint issues

- server/container_create.go
> Apply working dir and env from image config

- server/container_create.go
- server/sandbox.go
- server/sandbox_run.go
> Set the container hostname same as pod hostname

- server/container_create.go
> Check for case when image config isn't present

- server/container_status.go
Fix 5 more tests from k8s's conformance tests
```
Ran 5 of 213 Specs in 76.068 seconds
SUCCESS! -- 5 Passed | 0 Failed | 0 Pending | 208 Skipped PASS
```
> server: expose mounts in container status

- cmd/ocic/main.go
- cmd/ocid/main.go
@runcom @sameo @cyphar @rhatdan PTAL
> Release version 0.2

- pkg/storage/runtime.go
- server/container_create.go
- server/container_remove.go
- server/container_status.go
- server/image_list.go
- server/image_pull.go
- server/image_remove.go
- server/image_status.go
- server/sandbox_remove.go
- server/sandbox_run.go
- server/server.go
`git grep -w images` or `git grep -w storage` needs to be more useful.
> server: readable fields

- Makefile
- contrib/systemd/ocid-shutdown.service
- server/sandbox_remove.go
- server/server.go
> Add kpod image and kpod rmi for the handling of container images.

- pause/pause.c
psignal needs a feature check macro
> pause: Fix compilation warning

- server/container_create.go
> container: Bind mount hosts file for host networking containers

- conmon/conmon.c
> Add nanoseconds to timestamp to make it RFC3339Nano

- server/container_create.go
- server/container_list.go
- server/container_remove.go
- server/container_start.go
- server/container_status.go
- server/container_stop.go
- server/sandbox_list.go
- server/sandbox_remove.go
- server/sandbox_status.go
- server/sandbox_stop.go
Fixes from the 1.6.1 branch.
@sameo @mrunalp @cyphar PTAL
> small fixes

- cmd/ocic/main.go
- cmd/ocid/main.go
> Bump up to version 0.3

- tutorial.md
Trying the pull request again with a signed-off commit.
Signed-off-by: Gianni Salinetti <gbsalinetti@extraordy.com>
> Updated paths on tutorial.md to reflect the Makefile install configuration.

- contrib/systemd/ocid.service
> contrib: systemd: fix ocid path

- server/sandbox_run.go
- server/server.go
Fix https://github.com/kubernetes-incubator/cri-o/issues/498
> server: store kubeName in annotations

- server/container_create.go
- test/ctr.bats
- test/testdata/container_redis_device.json
Fixes #487 
Add devices to OCI config.
> Device support

- Makefile
- lock.json
- test/ctr.bats
- vendor/github.com/opencontainers/runtime-tools/cmd/oci-runtime-tool/generate.go
- vendor/github.com/opencontainers/runtime-tools/completions/bash/oci-runtime-tool
- vendor/github.com/opencontainers/runtime-tools/generate/generate.go
- vendor/github.com/opencontainers/runtime-tools/man/oci-runtime-tool-generate.1.md
- vendor/github.com/opencontainers/runtime-tools/validate/validate.go
Fix #493
@mrunalp @sameo @rhatdan PTAL
> vendor: bump oci/runtime-tools to fix caps drop

- .gitignore
- test/ctr.bats
Matches the rename that just got merged
> Update gitignore to replace ocic with crioctl

- Dockerfile
- conmon/Makefile
- conmon/conmon.c
- oci/oci.go
Fixes #492 
@runcom @sameo @cyphar PTAL
> Capture errors from runtime create failures

- Makefile
- cmd/crio/config.go
- cmd/crio/main.go
- contrib/systemd/crio-shutdown.service
- contrib/systemd/crio.service
- docs/crio.8.md
- docs/crio.conf.5.md
- test/README.md
- test/apparmor.bats
- test/helpers.bash
- test/seccomp.bats
> Fix remnants of ocid -> crio rename

- cmd/crioctl/container.go
- oci/oci.go
- server/container_remove.go
- server/container_stop.go
- server/sandbox_remove.go
- server/sandbox_stop.go
> server: honor container stop timeout from CRI

- Makefile
> Makefile: enable git-validation dangling whitespace

- contrib/test/crio-integration-playbook.yaml
- test/testdata/container_config.json
- test/testdata/container_config_by_imageid.json
- test/testdata/container_config_logging.json
- test/testdata/container_config_seccomp.json
- test/testdata/container_redis.json
- test/testdata/container_redis_device.json
Cause the one shipped in CentOS is way too old at this point
> contrib: test: fix CentOS CI

- contrib/test/crio-integration-playbook.yaml
> contrib: test: enable k8s Conformance tests for Fedora

- contrib/test/crio-integration-playbook.yaml
- test/helpers.bash
- test/pod.bats
- test/seccomp.bats
- test/testdata/sandbox_config.json
- test/testdata/sandbox_config_hostnet.json
- test/testdata/sandbox_config_seccomp.json
Tests for https://github.com/kubernetes-incubator/cri-o/pull/524
@mrunalp PTAL
> Test systemd cgroup manager

- Dockerfile
- oci/container.go
- oci/oci.go
- server/container_create.go
- server/container_start.go
- server/container_status.go
- server/container_stop.go
- server/sandbox.go
- server/sandbox_list.go
- server/sandbox_remove.go
- server/sandbox_run.go
- server/sandbox_status.go
- server/sandbox_stop.go
- server/server.go
- test/restore.bats
- utils/utils.go
> Fix restore

- cmd/crioctl/container.go
- server/container_status.go
- server/image_status.go
- server/sandbox_remove.go
- server/sandbox_stop.go
- test/helpers.bash
- test/image.bats
- test/pod.bats
First batch of fixes needed for k8s e2e tests. Most importantly this came out https://github.com/kubernetes-incubator/cri-o/issues/531
See individual commits messages for rationales behind these patches.
> e2e fixes - part 0

- server/container_create.go
- test/ctr.bats
Workaround for some tests in the e2e suite.
> server: workaround images with Config.Volumes

- Dockerfile
- contrib/test/crio-integration-playbook.yaml
@mrunalp PTAL this should go in asap for other PRs to trigger correct CI (you need to rebase your PRs after this is merged)
> Fix CI because of CNI repo move

- conmon/conmon.c
- oci/oci.go
- test/ctr.bats
- test/helpers.bash
conmon has many flags that are parsed when it's executed, one of them
is "-c". During PR #510 where we vendor latest kube master code,
upstream has changed a test to call a "ctr execsync" with a command of
"sh -c commmand ...".
Turns out:
a) conmon has a "-c" flag which refers to the container name/id
b) the exec command has a "-c" flags but it's for "sh"
That leads to conmon parsing the second "-c" flags from the exec
command causing an error. The executed command looks like:
conmon -c [..other flags..] CONTAINERID -e sh -c echo hello world
This patch rewrites the exec sync code to not pass down to conmon the
exec command via command line. Rather, we're now creating an OCI runtime
process spec in a temp file, pass _the path_ down to conmon, and have
runc exec the command using "runc exec …
> execsync: rewrite to fix a bug in conmon

- server/container_exec.go
- server/container_portforward.go
- server/server.go
> [e2e fix] server: add nil checks to not panic

- oci/oci.go
- pkg/storage/runtime.go
- server/container_create.go
- server/sandbox_remove.go
- server/sandbox_run.go
these are patches taken from the kube-1.6.x branch - these patches are the result of many testing to make CRI-O works with kubeadm.
I also opened this to make sure kube tests are ok.
@sameo @mrunalp PTAL
> Stability fixes

- Dockerfile
- README.md
- conmon/Makefile
- conmon/conmon.c
- contrib/test/crio-integration-playbook.yaml
I've been reviewing the conmon code, and here is a bunch of fixes for issues that I found.
The comments on each commit describes the issues pretty well, and I don't think any of these are controversial, so I made it a single pull request.
> Various fixes for conmon

- conmon/conmon.c
> Add missing include for writev

- server/server.go
The bug is silly if you have a master/node cluster where node is on a
different machine than the master.
The current behavior is to give our addresses like "0.0.0.0:10101". If
you run "kubectl exec ..." from another host, that's not going to work
since on a different host 0.0.0.0 resolves to localhost and kubectl
exec fails with:
error: unable to upgrade connection: 404 page not found
This patch fixes the above by giving our correct addresses for reaching
from outside.
> server: do not use localhost for streaming service

- tutorial.md
> tutorial: pull the redis image first

- contrib/systemd/crio.service
> contrib: systemd: change After to network-online.target

- pkg/storage/image.go
- server/image_pull.go
This is an optimization of our image pull code path. It's basically
how docker handles pulls as well. Let's be smart and check the image in
pull code path as well.
> image_pull: check image already pulled

- conmon/conmon.c
This drops the custom epoll code from conmon, and used a glib mainloop instead.
This is the first step in cleaning this code up. Once this is in I think we can fix the FIXME in the code that does the terminal accept.
Note, i have not really tested this in a full kubernetes instance. Having issues getting kube to run atm. Lets see what the CI says about this :)
> conmon: Use glib mainloop instead of epoll

- cmd/crio/config.go
- cmd/crio/main.go
- pkg/storage/image.go
- server/config.go
- server/image_pull.go
- server/server.go
> *: support insecure registries

- README.md
> README.md: add communication paragraph

- oci/container.go
- oci/oci.go
- server/container_attach.go
- server/container_exec.go
- server/container_portforward.go
- server/container_start.go
- server/container_status.go
- vendor/github.com/docker/docker/pkg/pools/pools.go
@mrunalp @sameo @Random-Liu PTAL
> adjust status on container start failure

- README.md
> readme: Update the roadmap to reflect current status

- tutorial.md
> tutorial: Fix CNI plugins URL

- README.md
> readme: Fix the required version of runc

- server/container_create.go
Fix #595 
Together with https://github.com/kubernetes-incubator/cri-o/pull/598 this should fix calico
ref: https://github.com/projectcalico/calico/issues/852
> Fix calico

- oci/oci.go
> oci: remove busy loop

- .travis.yml
> travis: Fix the IRC channel

- cmd/crio/main.go
- server/container_create.go
> Add missing error checks and simplify bool check

- cmd/crio/main.go
- server/sandbox_run.go
> Fixies profiling + conflict run pod sandbox

- README.md
- cmd/crio/main.go
- cmd/crioctl/main.go
> version: Bump up version to 1.0.0-alpha.0

- test/ctr.bats
> test: Ensure we get error messages back on creation failure

- conmon/conmon.c
- oci/oci.go
This moves the timeout handling from the go code to conmon, whic
removes some of the complexity from criod, and additionally it will
makes it possible to do the double-fork in the exec case too.
> conmon: Clean up execsync

- conmon/conmon.c
This is a bunch of code cleanups to conmon. They should not affect the behaviour at all, but makes the code easier to read.
The first commit is from https://github.com/kubernetes-incubator/cri-o/pull/620, and i will rebase this when that lands, so ignore that.
> Conmon cleanup

- vendor.conf
- vendor/github.com/opencontainers/runtime-tools/generate/generate.go
- vendor/github.com/opencontainers/runtime-tools/generate/spec.go
- vendor/github.com/opencontainers/runtime-tools/validate/validate.go
> Vendor in latest opencontainers/runtime-tools

- server/container_create.go
> container: Add containerID to annotations for the container

- oci/oci.go
- server/container_exec.go
> oci: Use container ID as ID instead of container name

- Makefile
- cmd/kpod/main.go
- cmd/kpod/version.go
- completions/bash/kpod
- docs/kpod-version.1.md
- test/helpers.bash
- test/kpod.bats
Added the "kpod version" functionality using the same format as "docker version."
> Add version command to kpod

- contrib/test/crio-integration-playbook.yaml
- test/ctr.bats
We want to see if this fixes the issues on CI.
> test: Use cgroupfs for tests

- cmd/kpod/common.go
- cmd/kpod/common_test.go
- cmd/kpod/main.go
- cmd/kpod/tag.go
- completions/bash/kpod
- docs/kpod-tag.1.md
- docs/kpod.1.md
Tag adds one or more tags to an image and is necessary for `kpod push`
> Add `kpod tag` command

- cmd/crio/config.go
- cmd/crio/main.go
- docs/crio.8.md
- docs/crio.conf.5.md
- server/config.go
- server/container_create.go
- test/helpers.bash
- test/image_volume.bats
We add support for mkdir and ignore to begin with.
> Image volumes

- cmd/kpod/common.go
- cmd/kpod/main.go
- cmd/kpod/pull.go
- completions/bash/kpod
- docs/kpod-pull.1.md
- test/kpod.bats
Add "kpod pull" command. The --all-tags and --disable-content-trust flags are commented out since containers/image doesn't support it yet.
> Add 'kpod pull' command

- server/config.go
- server/server.go
> Rename remnants of ocid to crio

- cmd/crio/config.go
- cmd/crio/main.go
- docs/crio.8.md
- docs/crio.conf.5.md
- server/config.go
- server/container_create.go
- test/cgroups.bats
- test/helpers.bash
This adds a crio daemon level setting for container pids limit. We will add container level support once CRI supports it.
> Pids limit

- cmd/crio/main.go
- server/config.go
- server/container_create.go
- test/image_volume.bats
This adds supported for bind mounted image volumes.
> Add ImagesVolumesBind option

- server/container_create.go
- server/sandbox.go
- server/sandbox_list.go
- server/sandbox_run.go
- server/sandbox_stop.go
- server/server.go
Make sandbox struct and it methods public, and add accessor methods for the struct fields
> Refactor server sandbox

- README.md
- cmd/kpod/history.go
- cmd/kpod/main.go
- completions/bash/kpod
- docs/kpod-history.1.md
- test/kpod.bats
"kpod history" prints out information about the layers of an image.
> Add 'kpod history' command

- README.md
- cmd/kpod/common.go
- cmd/kpod/common_test.go
- cmd/kpod/containerImageRef.go
- cmd/kpod/docker/types.go
- cmd/kpod/imagePushData.go
- cmd/kpod/imagePushData_test.go
- cmd/kpod/main.go
- cmd/kpod/pull.go
- cmd/kpod/push.go
- cmd/kpod/push_test.go
- completions/bash/kpod
- docs/kpod-push.1.md
- kpod-push.1.md
- server/server.go
- test/kpod.bats
Push an image to a specified location, such as to an atomic registry or a local directory
Signed-off-by: Ryan Cole <rcyoalne@gmail.com>
> Add `kpod push` command

- libkpod/sandbox/sandbox.go
- server/container_create.go
- server/container_list.go
- server/sandbox_list.go
- server/sandbox_remove.go
- server/sandbox_run.go
- server/sandbox_status.go
- server/sandbox_stop.go
- server/server.go
If sandbox is in the same package as server, there will be a circular dependency when
kpod create is implemented
> Move sandbox into its own package

- libkpod/containerserver.go
- server/container_create.go
- server/container_remove.go
- server/container_start.go
- server/container_status.go
- server/container_stop.go
- server/naming.go
- server/sandbox_remove.go
- server/sandbox_run.go
- server/sandbox_status.go
- server/sandbox_stop.go
- server/server.go
Move the last of the non-kube-dependent server functions in the server package into libkpod
> Libkpod serverfunctions

- cmd/kpod/info.go
- cmd/kpod/rmi.go
- libkpod/container.go
- libkpod/image/image.go
- libkpod/image/imageData.go
- libkpod/image/rmi.go
* Switch to using storage APIs that don't bypass locking and synchronization.
* Properly close `Image` objects in a couple of places that we weren't.
> Fix a couple of bugs in our use of containers/storage and containers/image

- cmd/crio/main.go
> Make the profile port configurable

- README.md
- cmd/kpod/load.go
- cmd/kpod/main.go
- cmd/kpod/pull.go
- cmd/kpod/save.go
- completions/bash/kpod
- docs/kpod-load.1.md
- docs/kpod-pull.1.md
- libkpod/image/copy.go
- test/kpod_load.bats
Add kpod load. Add fixes to kpod pull. Add changes to containers/image/docker to get manifest for image:tag.
> Add kpod load

- docs/kpod-history.1.md
- docs/kpod-images.1.md
- docs/kpod-info.1.md
- docs/kpod-inspect.1.md
- docs/kpod-push.1.md
- docs/kpod-rmi.1.md
- docs/kpod-save.1.md
- docs/kpod-tag.1.md
- docs/kpod-version.1.md
Makes the headings of the kpod manpages more uniform.  My ocd was kicking up this weekend apparently.
> Make the kpod manpages a bit more uniform

- libkpod/container_server.go
- server/container_create.go
- server/container_remove.go
- server/container_stop.go
- server/sandbox_remove.go
- server/sandbox_run.go
- server/sandbox_stop.go
- server/server.go
Add Update() function to ContainerServer (based on server function of same name) and call the function when a new container server is created
> Make container server update it's list of containers upon creation

- cmd/kpod/diff.go
- cmd/kpod/main.go
- docs/kpod-diff.1.md
- libkpod/diff.go
- libkpod/layer/layer.go
- test/kpod_diff.bats
`kpod diff` reports on the changes in the filesystem between a container, layer, or image and its parent
Signed-off-by: Ryan Cole <rcyoalne@gmail.com>
> Add kpod diff command

- docs/kpod-cp.1.md
> Add man page for kpod-cp.1

- transfer.md
Facilitating the "how do i do X?" knowledge transfer process.
> tranfer: document ops and dev transfer

- contrib/cni/README.md
Signed-off-by: asifdxtreme <mohammad.asif.siddiqui1@huawei.com>
> Fix Typo in Readme

- libkpod/diff.go
- server/container_create.go
- server/image_pull.go
Signed-off-by: asifdxtreme <mohammad.asif.siddiqui1@huawei.com>
> Fix Typo to improve GoReport

- README.md
- docs/kpod-info.1.md
- docs/kpod-load.1.md
- docs/kpod-mount.1.md
- docs/kpod-umount.1.md
- docs/kpod.1.md
- transfer.md
Also added new commands to transfer.md
> More cleanups of main man page kpod-1.md and README.md

- libkpod/image/copy.go
When an image is saved using the digest, the repotag saved is null causing load to break
Using the hex form of the image digest to save the image when the repotag is null
This saves the image in containers-storage without a name or tag
> Fix 'kpod load' nil issue raised by QE

- cmd/kpod/common.go
- cmd/kpod/main.go
- cmd/kpod/rename.go
- completions/bash/kpod
- docs/kpod-rename.1.md
- docs/kpod.1.md
- libkpod/rename.go
- oci/container.go
- test/kpod_rename.bats
> implement kpod rename

- libpod/ctr/container.go
- libpod/options.go
- libpod/pod/pod.go
- libpod/runtime.go
Whiteboarded by myself, @rhatdan and @mrunalp this morning. Comments welcome.
> Add skeleton of new libpod API

- cmd/kpod/common.go
- cmd/kpod/main.go
The --debug flag is a global CLI flag, so parse it like one.
> kpod: make --debug work

- cmd/kpod/images.go
> kpod-images: don't nil pointer on empty list

- cmd/kpod/formats/formats.go
- cmd/kpod/history.go
- cmd/kpod/images.go
- cmd/kpod/main.go
- cmd/kpod/mount.go
- cmd/kpod/ps.go
- completions/bash/kpod
- docs/kpod-history.1.md
- docs/kpod-ps.1.md
- test/kpod_ps.bats
kpod ps lists the containers currently stored
Displays the list of containers
> Add 'kpod ps' command

- server/server.go
SetMaxThreads from runtime/debug in Golang is called to set max threads
value to 90% of /proc/sys/kernel/threads-max
Should really help performance. Same setting as in Docker.
> server: set golang runtime max threads

- Dockerfile
- contrib/test/crio-integration-playbook.yaml
- test/helpers.bash
Close https://github.com/kubernetes-incubator/cri-o/pull/793
Fixes CI found in https://github.com/kubernetes-incubator/cri-o/pull/789
@mrunalp PTAL
> *: fix crictl vendor

- cmd/kpod/ps.go
Changed the JSON output to hold the actual type of the data.
For example the creation time of a container will be of form time.Time.
The human readable output modifies all the fields to type string, which
is not helpful when the JSON output wants to be used for further processing.
> Modify the JSON output of kpod ps

- cmd/kpod/push.go
- test/kpod.bats
Picking up @14rcole patches, since he has gone back to school.
Added fix for @mtrmac comment on compression variable.
Replaces https://github.com/kubernetes-incubator/cri-o/pull/739
> Disable compression by default.

- libpod/options.go
- libpod/runtime.go
- vendor/github.com/ulule/deepcopier/LICENSE
- vendor/github.com/ulule/deepcopier/README.md
- vendor/github.com/ulule/deepcopier/deepcopier.go
Still WIP, but required to get work on #803 moving.
> Add basic skeleton of libpod runtime

- cmd/crio/main.go
- server/inspect.go
- vendor.conf
- vendor/github.com/go-zoo/bone/LICENSE
- vendor/github.com/go-zoo/bone/README.md
- vendor/github.com/go-zoo/bone/bone.go
- vendor/github.com/go-zoo/bone/helper.go
- vendor/github.com/go-zoo/bone/helper_15.go
- vendor/github.com/go-zoo/bone/helper_17.go
- vendor/github.com/go-zoo/bone/mux.go
- vendor/github.com/go-zoo/bone/route.go
We can add IP once #814 is merged. 
This could be used by our cadvisor handler.
> server: Add an inspect endpoint for containers

- cmd/crio/main.go
- server/inspect.go
> server: Add a /info endpoint

- libkpod/container_server.go
- oci/container.go
- pkg/annotations/annotations.go
- pkg/storage/image.go
- server/container_create.go
- server/image_list.go
- server/inspect.go
- server/sandbox_run.go
@mrunalp PTAL this is needed by cadvisor
> server: inspect: add log path and mount point for cadvisor

- vendor.conf
- vendor/k8s.io/kubernetes/README.md
- vendor/k8s.io/kubernetes/pkg/api/v1/generated.proto
- vendor/k8s.io/kubernetes/pkg/apis/admissionregistration/v1alpha1/generated.proto
- vendor/k8s.io/kubernetes/pkg/apis/networking/v1/generated.proto
- vendor/k8s.io/kubernetes/pkg/cloudprovider/README.md
- vendor/k8s.io/kubernetes/pkg/kubelet/apis/cri/v1alpha1/runtime/api.proto
> vendor: bump to kube v1.7.5

- cmd/crio/main.go
- server/inspect.go
> server: Use crio socket for info/inspect endpoints

- Dockerfile
> Dockerfile: bump runc commit

- libkpod/container_server.go
- server/inspect.go
- server/naming.go
- server/sandbox_remove.go
- server/sandbox_run.go
- server/server.go
- vendor/k8s.io/kubernetes/pkg/kubelet/leaky/leaky.go
- vendor/k8s.io/kubernetes/pkg/kubelet/types/constants.go
- vendor/k8s.io/kubernetes/pkg/kubelet/types/doc.go
- vendor/k8s.io/kubernetes/pkg/kubelet/types/labels.go
- vendor/k8s.io/kubernetes/pkg/kubelet/types/pod_update.go
- vendor/k8s.io/kubernetes/pkg/kubelet/types/types.go
This is required so cadvisor can recognize this container.
> sandbox: Add special label to infra container

- server/inspect.go
> server: Add sandbox to container info

- vendor.conf
- vendor/github.com/containers/image/README.md
- vendor/github.com/containers/image/docker/docker_client.go
- vendor/github.com/containers/image/image/oci.go
- vendor/github.com/containers/image/ostree/ostree_dest.go
- vendor/github.com/containers/image/ostree/ostree_transport.go
- vendor/github.com/containers/image/types/types.go
- vendor/github.com/containers/image/vendor.conf
- vendor/github.com/docker/docker-credential-helpers/LICENSE
- vendor/github.com/docker/docker-credential-helpers/README.md
- vendor/github.com/docker/docker-credential-helpers/client/client.go
- vendor/github.com/docker/docker-credential-helpers/client/command.go
- vendor/github.com/docker/docker-credential-helpers/credentials/credentials.go
- vendor/github.com/docker/docker-credential-helpers/credentials/error.go
- vendor/github.com/docker/docker-credential-helpers/credentials/helper.go
- vendor/github.com/docker/docker-credential-helpers/credentials/version.go
- vendor/github.com/docker/docker-credential-helpers/osxkeychain/osxkeychain_darwin.c
- vendor/github.com/docker/docker-credential-helpers/osxkeychain/osxkeychain_darwin.go
- vendor/github.com/docker/docker-credential-helpers/osxkeychain/osxkeychain_darwin.h
- vendor/github.com/docker/docker-credential-helpers/osxkeychain/url_go18.go
- vendor/github.com/docker/docker-credential-helpers/osxkeychain/url_non_go18.go
- vendor/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.c
- vendor/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.go
- vendor/github.com/docker/docker-credential-helpers/secretservice/secretservice_linux.h
Adds support for credential helpers
Need it to work on fix for https://github.com/containers/image/pull/333
> Vendor in latest containers/image

- server/inspect.go
> inspect: Add cgroup driver to info output

- README.md
- cmd/kpod/main.go
- cmd/kpod/rm.go
- completions/bash/kpod
- docs/kpod-rm.1.md
- docs/kpod.1.md
- libkpod/remove.go
- libkpod/stop.go
- server/container_remove.go
- server/container_stop.go
- test/kpod_diff.bats
- test/kpod_load.bats
- test/kpod_rm.bats
- test/kpod_save.bats
Kpod rm removes a container from the system
Signed-off-by: Ryan Cole <rcyoalne@gmail.com>
> Implement kpod rm

- pkg/storage/image.go
Fix https://github.com/kubernetes-incubator/cri-o/issues/847
@derekwaynecarr @mrunalp PTAL
> pkg: storage: fix panic when no image names

- contrib/test/crio-integration-playbook.yaml
- pkg/storage/image.go
> pkg: storage: fix additional registries

- README.md
- cmd/crio/config.go
- cmd/crio/main.go
- contrib/test/crio-integration-playbook.yaml
- hooks.md
- libkpod/config.go
- libkpod/container_server.go
- libkpod/hooks.go
- server/container_create.go
- test/helpers.bash
- test/hooks.bats
- test/hooks/checkhook.json
- test/hooks/checkhook.sh
> Add support for running oci-hooks

- README.md
> README: more copy-pastable code sample

- pkg/storage/image.go
> pkg: storage: image: get size from image ID

- Makefile
> version: Add -dirty if compiled binary includes uncommited changes

- cmd/kpod/load.go
- cmd/kpod/save.go
- completions/bash/kpod
- docs/kpod-load.1.md
- docs/kpod-save.1.md
- libpod/images/copy.go
- test/kpod_load.bats
- test/kpod_save.bats
https://github.com/kubernetes-incubator/cri-o/pull/829 needs to be merged in first.
> Update kpod load and save for oci-archive

- contrib/test/crio-integration-playbook.yaml
> contrib: test: redirect stderr to stdout

- README.md
- transfer.md
Add a couple of new ascicinema also
> Cleanup README.md and transfer.md with latest kpod

- libpod/images/copy_ref.go
- pkg/storage/image.go
- vendor.conf
- vendor/github.com/containers/image/copy/copy.go
- vendor/github.com/containers/image/directory/directory_transport.go
- vendor/github.com/containers/image/docker/archive/transport.go
- vendor/github.com/containers/image/docker/daemon/daemon_transport.go
- vendor/github.com/containers/image/docker/docker_image.go
- vendor/github.com/containers/image/docker/docker_image_dest.go
- vendor/github.com/containers/image/docker/docker_image_src.go
- vendor/github.com/containers/image/docker/docker_transport.go
- vendor/github.com/containers/image/manifest/manifest.go
- vendor/github.com/containers/image/oci/archive/oci_src.go
- vendor/github.com/containers/image/oci/archive/oci_transport.go
- vendor/github.com/containers/image/oci/layout/oci_transport.go
- vendor/github.com/containers/image/openshift/openshift.go
- vendor/github.com/containers/image/openshift/openshift_transport.go
- vendor/github.com/containers/image/ostree/ostree_dest.go
- vendor/github.com/containers/image/ostree/ostree_transport.go
- vendor/github.com/containers/image/storage/storage_reference.go
- vendor/github.com/containers/image/types/types.go
> fix issue with official images and manifest lits

- cmd/kpod/ps.go
- test/kpod_ps.bats
The namespace field was not being omitted when empty in the json
> Modified namespace field in json struct

- cmd/crio/main.go
- docs/crio.8.md
- docs/crio.conf.5.md
> docs: Add missing bind option in docs and command help

- .travis.yml
- Dockerfile
- Makefile
- cmd/kpod/common_test.go
- contrib/test/crio-integration-playbook.yaml
- libkpod/container_server.go
- libkpod/sandbox/sandbox.go
- oci/container.go
- pkg/annotations/annotations.go
- server/container_create.go
- server/inspect.go
- server/inspect_test.go
- server/sandbox_run.go
- test/inspect.bats
- test/network.bats
- test/selinux.bats
- test/testdata/container_config.json
- test/testdata/container_config_by_imageid.json
- test/testdata/container_config_hostport.json
- test/testdata/container_config_logging.json
- test/testdata/container_config_resolvconf.json
- test/testdata/container_config_resolvconf_ro.json
- test/testdata/container_config_seccomp.json
- test/testdata/sandbox_config_seccomp.json
- test/testdata/sandbox_config_selinux.json
Close #892 
Close #903 
Fix https://github.com/kubernetes-incubator/cri-o/issues/911
Fix https://github.com/kubernetes-incubator/cri-o/issues/898
Tested this the whole morning, run integration and e2e tests. Integrations are fine, on my local machine I got the usual network failures in e2e but nothing broken afaict so this seems good actually...
@mrunalp @rhatdan @sameo et all, PTAL
> V1.0.0 rc2 patches

- libkpod/config_test.go
- libkpod/testdata/config.toml
- ``config_test.go`` for testing ``libkpod/config.go``
- ``testdata/config.toml`` as a fixture for ``config_test.go``
> test: Add libkpod config tests

- README.md
> Describe in readme `kpod cp` man page

- client/client.go
- cmd/crioctl/container.go
- cmd/crioctl/info.go
- cmd/crioctl/main.go
- libkpod/container_server.go
- oci/container.go
- server/container_create.go
- server/inspect.go
- server/inspect_test.go
- server/sandbox_run.go
- test/inspect.bats
- types/types.go
This PR adds a client package for accessing the crio info and container endpoints. We also expose all the crio annotations in the container endpoint.
> client: Add crio client package

- README.md
> README: Update status

- cmd/crio/config.go
- cmd/crio/main.go
- conmon/conmon.c
- docs/crio.8.md
- docs/crio.conf.5.md
- libkpod/config.go
- libkpod/container_server.go
- oci/oci.go
- test/ctr.bats
- test/helpers.bash
This PR adds configuration for max log size.
> Max log size config

- .travis.yml
- Dockerfile
- README.md
- cmd/kpod/main.go
- cmd/kpod/wait.go
- completions/bash/kpod
- docs/kpod-wait.1.md
- libkpod/wait.go
- test/kpod_wait.bats
- test/testdata/template_container_config.json
- test/testdata/template_sandbox_config.json
- transfer.md
Waits on one or more containers to stop and prints the container's
return code
> Add kpod wait

- cmd/kpod/load.go
- cmd/kpod/pull.go
- cmd/kpod/push.go
- cmd/kpod/save.go
- cmd/kpod/tag.go
- libpod/image.go
Taking over https://github.com/kubernetes-incubator/cri-o/pull/862
> Continue switching commands from libkpod to libpod

- contrib/test/integration/ansible.cfg
- contrib/test/integration/build/bats.yml
- contrib/test/integration/build/cri-o.yml
- contrib/test/integration/build/cri-tools.yml
- contrib/test/integration/build/kubernetes.yml
- contrib/test/integration/build/plugins.yml
- contrib/test/integration/build/runc.yml
- contrib/test/integration/callback_plugins/default.py
- contrib/test/integration/e2e.yml
- contrib/test/integration/golang.yml
- contrib/test/integration/main.yml
- contrib/test/integration/results.yml
- contrib/test/integration/system.yml
- contrib/test/integration/test.yml
- contrib/test/integration/vars.yml
- contrib/test/venv-ansible-playbook.sh
Centralize results output.  Collect results.  Organize vars.
> Write playbook to collect results from subjects

- contrib/test/integration/system.yml
> test: Add task to enable xfs pquota support

- Makefile
- contrib/test/integration/e2e.yml
- hack/btrfs_installed_tag.sh
Alternative to #968 
cc: @stevekuznetsov @rhatdan @nalind
> Btrfs build

- README.md
- docs/kpod.1.md
- transfer.md
Alphabatize correctly and add missing content.  Also add video.
> Cleanup READMEs and Man pages

- test/network.bats
Signed-off-by: Dan Williams <dcbw@redhat.com>
> test: add test for network teardown on sandbox error

- README.md
> readme: Fix rc version and specify cgroup driver for k8s

- README.md
Added links to the video blog for kpod pause and kpod unpause.
> Add video for pause/unpause to README.md

- libpod/images/rmi.go
Rebase of https://github.com/kubernetes-incubator/cri-o/pull/895
> kpod rmi by ID untagged: %name incorrect

- README.md
- docs/kpod.1.md
- transfer.md
> Add information on kpod login/logout

- server/inspect_test.go
> test: Fix format specifier

- server/inspect_test.go
> test: Modify Fatal to Fatalf as we have a specifier

- cmd/crio/config.go
- cmd/crio/main.go
- docs/crio.conf.5.md
- libkpod/config.go
- server/container_create.go
- server/secrets.go
- test/crio_secrets.bats
- test/helpers.bash
Deleted mounts.conf file and moved the secrets mount paths
to a list (default-mounts) in crio.conf
> Follow up changes on secrets patch

- libpod/container.go
- libpod/errors.go
- libpod/in_memory_state.go
- libpod/options.go
- libpod/pod.go
- libpod/runtime.go
- libpod/runtime_ctr.go
- libpod/runtime_pod.go
- libpod/state.go
Should be enough to unblock @baude 
I removed the disk interactions, which weren't finished or reliable yet, especially for adding/removing containers.
> Working state implementation for libpod

- Makefile
- cmd/crio/main.go
- server/server.go
- server/version.go
- version/version.go
Same as #1021 but for the `release-1.0` branch
> version: fix version handling and kube info

- cmd/kpod/rm.go
- cmd/kpod/stop.go
- libkpod/remove.go
- libkpod/stop.go
- oci/oci.go
- server/container_remove.go
- server/container_stop.go
- server/sandbox_remove.go
- server/sandbox_stop.go
@mrunalp PTAL follow-up of #1010 
> oci: fixes to properly handle container stop action

- seccomp.json
> Update to latest seccomp filters in moby

- README.md
- cmd/crio/main.go
- cmd/crioctl/main.go
- contrib/test/integration/build/kubernetes.yml
- docs/crio.8.md
- docs/crio.conf.5.md
- kubernetes.md
- server/config.go
> Move crio default sock to /var/run/crio/crio.sock

- contrib/test/integration/e2e.yml
> contrib: test: fix e2e cmdline

- server/container_create.go
- server/sandbox_run.go
> fix host pid handling for containers and share uts ns

- contrib/test/integration/e2e.yml
> [release-1.0] Fix e2e v1

- test/ctr.bats
@rhatdan @runcom PTAL
This should take care of the integration_rhel failures.
> test: Test for OOM condition in a loop

- server/container_create.go
- server/sandbox_run.go
> [release-1.0] fix host pid handling for containers and share uts ns

- cmd/kpod/load.go
- cmd/kpod/logout.go
- cmd/kpod/pull.go
- cmd/kpod/push.go
- cmd/kpod/save.go
- completions/bash/kpod
- docs/kpod-pull.1.md
- docs/kpod-push.1.md
- libpod/common/common.go
- libpod/common/docker_registry_options.go
- libpod/runtime_img.go
- test/kpod_pull.bats
- test/kpod_push.bats
Push and pull can now access any cached registry credentials from the auth file
> Add authfile flag to pull and push

- README.md
> Add ascii cinema to README for login/logout/diff

- CONTRIBUTING.md
We need to tell people about contributing to the CRI-O project
> Copy CONTRIBUTING.md from skopeo

- version/version.go
> Release 1.0.1

- cmd/kpod/load.go
- cmd/kpod/pull.go
- completions/bash/kpod
- docs/kpod-pull.1.md
- libpod/runtime_img.go
> Add --tls-verify, --cert-dir, and --quiet flags to kpod pull

- libpod/container.go
- libpod/errors.go
- libpod/oci.go
- libpod/options.go
- libpod/pod.go
- libpod/runtime.go
- libpod/runtime_ctr.go
- libpod/storage.go
The core logic for container creation. @baude will be integrating this with CLI work to produce a working version of 'kpod create'.
> Libpod container creation logic

- contrib/systemd/crio.service
Borrowed from:
https://github.com/projectatomic/atomic-system-containers/pull/136
From: Antonio Murdaca <runcom@redhat.com>
@runcom @mrunalp PTAL
> expand limits for tests

- libpod/container.go
- libpod/options.go
- libpod/runtime.go
Also clean up properly if NewRuntime fails.
I think this may be required for the create frontend PR.
> Update libpod to support labels

- server/sandbox_run.go
- server/server.go
> lint fixes

- version/version.go
> Release 1.0.2

- cmd/crio/main.go
- test/command.bats
> Report error when arguments given to crio command

- contrib/test/integration/system.yml
> test: Add networking settings for critest

- README.md
- cmd/kpod/common.go
- cmd/kpod/create.go
- cmd/kpod/create_cli.go
- cmd/kpod/main.go
- cmd/kpod/parse.go
- cmd/kpod/run.go
- cmd/kpod/spec.go
- cmd/kpod/user.go
- completions/bash/kpod
- docs/kpod-create.1.md
- docs/kpod-run.1.md
- docs/kpod.1.md
- libpod/container.go
- libpod/container_attach.go
- libpod/runtime_ctr.go
- libpod/runtime_img.go
- libpod/storage.go
- libpod/util.go
- test/helpers.bash
- test/kpod_create.bats
- test/kpod_run.bats
- transfer.md
kpod create and run
Add the ability to run create a container with kpod.  Also, be able to run
(create and start) a container.  If the user asks for -it, be able to
attach a terminal to the container.
> Kpod create.pr

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
> *: add .github

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
> [release-1.0] *: add .github

- cmd/crio/main.go
- test/command.bats
Carry of #1100 for `release-1.0`.
@rhatdan PTAL
> [release-1.0] Report error when arguments given to crio command

- README.md
> README.md: add go-md2man to build dep in Ubuntu

- .travis.yml
- server/container_create.go
- test/ctr.bats
Added HOSTNAME to container env variables.
Start a pod and env | grep HOSTNAME
Add HOSTNAME environment variable to containers in the pod.
> Add HOSTNAME env var to container

- contrib/test/integration/build/kubernetes.yml
Carry https://github.com/kubernetes-incubator/cri-o/pull/1120 for `release-1.0` branch
> [release-1.0] test: Fix partial log line parsing

- Makefile
- contrib/test/integration/build/kubernetes.yml
- contrib/test/integration/e2e.yml
- contrib/test/integration/main.yml
closes #1119 
Moved a task, added a variable
In ``vi``
Running slash-test ami a bunch of times will never break on cloning kubernetes
> Fix Local modifications exist in repository

- pkg/storage/image.go
- server/image_pull.go
Better fix than https://github.com/kubernetes-incubator/cri-o/pull/1136 to fix image policy always from kube
vim
tricky, push images with same tags (but different images) and notice CRI-O re-pull the image if it has changed (same as docker).
Close #1136
> image_pull: repull when image ID (config digest) changed

- pkg/storage/image.go
> pkg: storage: image: close image after using it

- pkg/storage/image.go
- server/container_attach.go
- server/container_create.go
- server/container_exec.go
- server/container_execsync.go
- server/container_list.go
- server/container_portforward.go
- server/container_remove.go
- server/container_start.go
- server/container_stats.go
- server/container_stats_list.go
- server/container_status.go
- server/container_stop.go
- server/container_updateruntimeconfig.go
- server/image_fs_info.go
- server/image_list.go
- server/image_pull.go
- server/image_remove.go
- server/image_status.go
- server/metrics/metrics.go
- server/runtime_status.go
- server/sandbox_list.go
- server/sandbox_remove.go
- server/sandbox_run.go
- server/sandbox_status.go
- server/sandbox_stop.go
- server/server.go
- server/utils.go
- server/version.go
@mrunalp @rhatdan @sameo PTAL
This PR back ports:
- https://github.com/kubernetes-incubator/cri-o/pull/1138
- https://github.com/kubernetes-incubator/cri-o/pull/1133
> [release-1.0] Backports image pull fix and metrics

- server/container_update_resources.go
allow update running/created container.
Signed-off-by: CuiHaozhi <cuihaozhi@chinacloud.com.cn>
> allow update running/created container.

- test/README.md
fix syntax format error for test/README.md
Signed-off-by: DeShuai Ma dma@redhat.com
> fix syntax for test/README.md

- README.md
> README.md: add compatibility matrix

- test/pod.bats
- test/testdata/sandbox1_config.json
- test/testdata/sandbox2_config.json
- test/testdata/sandbox3_config.json
Signed-off-by: Wei Wei <weiwei.inf@gmail.com>
replace crioctl with crictl in e2e
vim
make verify
make integration
replace crioctl with crictl in e2e
> replace crioctl with crictl in e2e

- test/README.md
- test/apparmor.bats
- test/cgroups.bats
- test/ctr.bats
- test/ctr_seccomp.bats
- test/default_mounts.bats
- test/helpers.bash
- test/hooks.bats
- test/image.bats
- test/image_volume.bats
- test/inspect.bats
- test/network.bats
- test/restore.bats
- test/runtimeversion.bats
- test/selinux.bats
- test/testdata/README.md
- test/testdata/container_config_resolvconf.json
- test/testdata/container_config_resolvconf_ro.json
- test/testdata/sandbox1_config.json
- test/testdata/sandbox2_config.json
- test/testdata/sandbox3_config.json
- test/testdata/sandbox_config.json
- test/testdata/sandbox_config_hostnet.json
- test/testdata/sandbox_config_hostport.json
- test/testdata/sandbox_config_seccomp.json
- test/testdata/sandbox_config_selinux.json
- test/testdata/sandbox_config_sysctl.json
- test/testdata/template_sandbox_config.json
replace crioctl with crictl in e2e
vim
make verify
make integration
replace crioctl with crictl in e2e
> Replace crioctl with crictl

- tutorial.md
Signed-off-by: z00280905 <zhangwei555@huawei.com>
> Cleanup: remove redundant lines in tutorial

- docs/crio.8.md
- **What I did**
Hello, I edited the `crio.8.md` again and want to improve readability using better format.
- **How I did it**
Vim
- **How to verify it**
Markdown preview
- **Description for the changelog**
Improve the readability of crio.8.md
> Improve the readability of crio.8.md

- server/fixtures/resolv.conf
- server/utils_test.go
Hello, I write a unit test for `server/utils.go`.
Vim
```
go test -v github.com/kubernetes-incubator/cri-o/server
```
Adding unit tests for server/utils.go
> Adding unit tests for server/utils.go

- README.md
> README.md: add all runtime dependencies

- oci/oci.go
- server/container_create.go
- server/container_exec.go
- server/utils.go
- server/utils_test.go
- test/ctr.bats
- test/testdata/container_redis_env_custom.json
Mainly, do not append conmon env vars to the container process or conmon's PATH could override container PATH as happened in https://bugzilla.redhat.com/show_bug.cgi?id=1517652
vim
check https://bugzilla.redhat.com/show_bug.cgi?id=1517652
> Fix env handling on exec

- oci/oci.go
- server/container_create.go
- server/container_exec.go
- test/ctr.bats
- test/testdata/container_redis_env_custom.json
same as https://github.com/kubernetes-incubator/cri-o/pull/1186 but for `release-1.0`
> [release-1.0] Fix env handling on exec

- oci/oci.go
- server/container_create.go
- server/container_exec.go
- test/ctr.bats
- test/testdata/container_redis_env_custom.json
same as https://github.com/kubernetes-incubator/cri-o/pull/1186 but for `release-1.8`
> [release-1.8] Fix env handling on exec

- server/apparmor/apparmor_common.go
- server/apparmor/apparmor_supported.go
- server/apparmor/apparmor_unsupported.go
- server/container_create.go
same as https://github.com/kubernetes-incubator/cri-o/pull/1189 but for `release-1.8`
> [release-1.8] container_create: fix apparmor from container config

- server/apparmor/apparmor_common.go
- server/apparmor/apparmor_supported.go
- server/apparmor/apparmor_unsupported.go
- server/container_create.go
Fix https://github.com/kubernetes-incubator/cri-o/issues/1145
> container_create: fix apparmor from container config

- server/fixtures/secret/testDataA
- server/fixtures/secret/testDataB
- server/secrets_test.go
Hello, I write a unit test for `server/secrets.go`.
Vim
```
go test -v github.com/kubernetes-incubator/cri-o/server
```
Adding unit tests for server/secrets.go
> Adding unit tests for server/secrets.go

- lib/container_server.go
- lib/sandbox/history.go
- lib/sandbox/memory_store.go
- lib/sandbox/sandbox.go
- lib/sandbox/store.go
Moved the sandboxes state from a raw map to a Sandbox storer, which is the same as we use in for container objects.
> lib: sandbox: refactor to memory store

- libkpod/container_server.go
- libkpod/sandbox/history.go
- libkpod/sandbox/memory_store.go
- libkpod/sandbox/sandbox.go
- libkpod/sandbox/store.go
same as #1198 but for `release-1.8`
> [release-1.8] libkpod: sandbox: refactor to memory store

- oci/oci.go
- server/container_exec.go
same as https://github.com/kubernetes-incubator/cri-o/pull/1207 but for 1.8.x
@mrunalp ptal
> [release-1.8] container_exec: fix terminal true process json

- oci/oci.go
- server/container_exec.go
same as https://github.com/kubernetes-incubator/cri-o/pull/1207 but for 1.0.x
@mrunalp PTAL
> [release-1.7] container_exec: fix terminal true process json

- contrib/system_containers/centos/Dockerfile
- contrib/system_containers/centos/README.md
- contrib/system_containers/centos/cccp.yml
- contrib/system_containers/centos/config.json.template
- contrib/system_containers/centos/manifest.json
- contrib/system_containers/centos/run.sh
- contrib/system_containers/centos/service.template
- contrib/system_containers/centos/set_mounts.sh
- contrib/system_containers/centos/tmpfiles.template
- contrib/system_containers/fedora/Dockerfile
- contrib/system_containers/fedora/README.md
- contrib/system_containers/fedora/config.json.template
- contrib/system_containers/fedora/manifest.json
- contrib/system_containers/fedora/run.sh
- contrib/system_containers/fedora/service.template
- contrib/system_containers/fedora/set_mounts.sh
- contrib/system_containers/fedora/tmpfiles.template
- contrib/system_containers/rhel/Dockerfile
- contrib/system_containers/rhel/config.json.template
- contrib/system_containers/rhel/help.md
- contrib/system_containers/rhel/manifest.json
- contrib/system_containers/rhel/run.sh
- contrib/system_containers/rhel/service.template
- contrib/system_containers/rhel/set_mounts.sh
- contrib/system_containers/rhel/tmpfiles.template
> contrib: import system containers

- contrib/test/integration/main.yml
@mrunalp PTAL, we'll need this for https://github.com/openshift/aos-cd-jobs/pull/945
> CI: split critest from e2e

- version/version.go
> Bump 1.9.0

- contrib/system_containers/centos/Dockerfile
- contrib/system_containers/centos/README.md
- contrib/system_containers/centos/cccp.yml
- contrib/system_containers/centos/config.json.template
- contrib/system_containers/centos/manifest.json
- contrib/system_containers/centos/run.sh
- contrib/system_containers/centos/service.template
- contrib/system_containers/centos/set_mounts.sh
- contrib/system_containers/centos/tmpfiles.template
- contrib/system_containers/fedora/Dockerfile
- contrib/system_containers/fedora/README.md
- contrib/system_containers/fedora/config.json.template
- contrib/system_containers/fedora/manifest.json
- contrib/system_containers/fedora/run.sh
- contrib/system_containers/fedora/service.template
- contrib/system_containers/fedora/set_mounts.sh
- contrib/system_containers/fedora/tmpfiles.template
- contrib/system_containers/rhel/Dockerfile
- contrib/system_containers/rhel/config.json.template
- contrib/system_containers/rhel/help.md
- contrib/system_containers/rhel/manifest.json
- contrib/system_containers/rhel/run.sh
- contrib/system_containers/rhel/service.template
- contrib/system_containers/rhel/set_mounts.sh
- contrib/system_containers/rhel/tmpfiles.template
> [release-1.7] contrib: import system containers

- contrib/system_containers/centos/Dockerfile
- contrib/system_containers/centos/README.md
- contrib/system_containers/centos/cccp.yml
- contrib/system_containers/centos/config.json.template
- contrib/system_containers/centos/manifest.json
- contrib/system_containers/centos/run.sh
- contrib/system_containers/centos/service.template
- contrib/system_containers/centos/set_mounts.sh
- contrib/system_containers/centos/tmpfiles.template
- contrib/system_containers/fedora/Dockerfile
- contrib/system_containers/fedora/README.md
- contrib/system_containers/fedora/config.json.template
- contrib/system_containers/fedora/manifest.json
- contrib/system_containers/fedora/run.sh
- contrib/system_containers/fedora/service.template
- contrib/system_containers/fedora/set_mounts.sh
- contrib/system_containers/fedora/tmpfiles.template
- contrib/system_containers/rhel/Dockerfile
- contrib/system_containers/rhel/config.json.template
- contrib/system_containers/rhel/help.md
- contrib/system_containers/rhel/manifest.json
- contrib/system_containers/rhel/run.sh
- contrib/system_containers/rhel/service.template
- contrib/system_containers/rhel/set_mounts.sh
- contrib/system_containers/rhel/tmpfiles.template
> [release-1.9] contrib: import system containers

- contrib/system_containers/centos/Dockerfile
- contrib/system_containers/centos/README.md
- contrib/system_containers/centos/cccp.yml
- contrib/system_containers/centos/config.json.template
- contrib/system_containers/centos/manifest.json
- contrib/system_containers/centos/run.sh
- contrib/system_containers/centos/service.template
- contrib/system_containers/centos/set_mounts.sh
- contrib/system_containers/centos/tmpfiles.template
- contrib/system_containers/fedora/Dockerfile
- contrib/system_containers/fedora/README.md
- contrib/system_containers/fedora/config.json.template
- contrib/system_containers/fedora/manifest.json
- contrib/system_containers/fedora/run.sh
- contrib/system_containers/fedora/service.template
- contrib/system_containers/fedora/set_mounts.sh
- contrib/system_containers/fedora/tmpfiles.template
- contrib/system_containers/rhel/Dockerfile
- contrib/system_containers/rhel/config.json.template
- contrib/system_containers/rhel/help.md
- contrib/system_containers/rhel/manifest.json
- contrib/system_containers/rhel/run.sh
- contrib/system_containers/rhel/service.template
- contrib/system_containers/rhel/set_mounts.sh
- contrib/system_containers/rhel/tmpfiles.template
> [release-1.8] contrib: import system containers

- contrib/test/integration/build/kubernetes.yml
- contrib/test/integration/e2e.yml
- contrib/test/integration/main.yml
- lib/container_server.go
- lib/sandbox/memory_store.go
- oci/memory_store.go
> contrib: test: integration: enable more e2e kube tests

- server/container_create.go
- test/ctr.bats
- test/testdata/container_redis.json
set cpuset cpus|mems at container_create
> container_create: set cpuset cpus|mems

- contrib/test/integration/main.yml
- contrib/test/integration/node-e2e.yml
add a node-e2e job to run as postsubmits for kube testgrid
> [DO NOT MERGE] contrib: test: add node-e2e job

- README.md
> Add 1.9 release to compatibility table

- version/version.go
Bump up versions for releasing 1.9.1
> Release 1.9.1

- server/container_create.go
Having a separate function holding the details of this makes reading `createSandboxContainer` easier.
While I was moving the code, I've also cleaned up two things:
* The `nil` capabilities check is now earlier, where before it had been between the `ALL` handling and the non-`ALL` handling.
* I've added a `capPrefixed` variable to avoid having multiple `toCAPPrefixed` calls per capability.
> server/container_create: Factor out setupCapabilities helper

- server/container_attach.go
> container_attach: Ensure ctl file is closed

- server/container_attach.go
> 1.9: Ensure ctl file is closed

- Makefile
- releases/README.md
- releases/v1.9.1.toml
Added a way to generate release notes along with a README.md with commands to use and an example of a release file.
> releases: add releases

- Dockerfile
- contrib/test/integration/main.yml
- test/apparmor.bats
- test/cgroups.bats
- test/ctr.bats
- test/ctr_seccomp.bats
- test/default_mounts.bats
- test/helpers.bash
- test/hooks.bats
- test/image.bats
- test/image_volume.bats
- test/inspect.bats
- test/namespaces.bats
- test/network.bats
- test/pod.bats
- test/restore.bats
- test/selinux.bats
- tutorial.md
We need this to pick up a fix for attach test.
> Bump up cri-tools to f1a58d681c056f259802f5cae2fe1fbcc6b28667

- contrib/test/system-container/Dockerfile
- contrib/test/system-container/README.md
- contrib/test/system-container/config.json.template
- contrib/test/system-container/manifest.json
- contrib/test/system-container/run.sh
- contrib/test/system-container/service.template
- contrib/test/system-container/set_mounts.sh
- contrib/test/system-container/tmpfiles.template
same as #1201 but for `release-1.8`
@mrunalp PTAL
> [release-1.8] contrib: test: add CI system container

- contrib/test/system-container/Dockerfile
- contrib/test/system-container/README.md
- contrib/test/system-container/config.json.template
- contrib/test/system-container/manifest.json
- contrib/test/system-container/run.sh
- contrib/test/system-container/service.template
- contrib/test/system-container/set_mounts.sh
- contrib/test/system-container/tmpfiles.template
same as #1201 but for `release-1.7`
@mrunalp PTAL
> [release-1.7] contrib: test: add CI system container

- contrib/test/system-container/Dockerfile
- contrib/test/system-container/README.md
- contrib/test/system-container/config.json.template
- contrib/test/system-container/manifest.json
- contrib/test/system-container/run.sh
- contrib/test/system-container/service.template
- contrib/test/system-container/set_mounts.sh
- contrib/test/system-container/tmpfiles.template
same as #1201 but for `release-1.9`
@mrunalp PTAL
> [release-1.9] contrib: test: add CI system container

- vendor.conf
- vendor/github.com/soheilhy/cmux/cmux.go
- vendor/github.com/soheilhy/cmux/matchers.go
> Update cmux to 0.1.4

- contrib/system_containers/centos/config.json.template
- contrib/system_containers/centos/manifest.json
- contrib/system_containers/fedora/config.json.template
- contrib/system_containers/fedora/manifest.json
- contrib/system_containers/rhel/config.json.template
- contrib/system_containers/rhel/manifest.json
- lib/container_server.go
- pkg/annotations/annotations.go
- server/container_create.go
- server/sandbox_run.go
- version/version.go
Bump version to 1.9.2 to release the fix from #1297 
> Bump 1.9.2

- Makefile
- cmd/crio/main.go
- contrib/test/integration/main.yml
same as #1308 but for release-1.8 branch. @mrunalp PTAL this is needed by the Origin CI
> cmd/crio: fix listen address dir creation

- version/version.go
bump to v1.8.5 to take care of the socket listen flag in 1.8.
> Bump 1.8.5

- releases/v1.0.9.toml
- releases/v1.8.5.toml
- releases/v1.9.2.toml
added toml for v1.9.2,v1.8.5,v1.0.9 that we just released. No need for CI on this.
> releases: add v1.9.2,v1.8.5,v1.0.9 toml

- version/version.go
> version 1.9.3

- releases/v1.9.3.toml
added v1.9.3 toml for release, @mrunalp @rhatdan PTAL, no need for the CI
> releases: add v1.9.3

- contrib/system_containers/centos/config.json.template
- contrib/system_containers/fedora/config.json.template
- contrib/system_containers/rhel/config.json.template
same as #1322 but for `release-1.9`
@mrunalp PTAL
> [release-1.9] system container: add /var/tmp as RW

- contrib/system_containers/centos/config.json.template
- contrib/system_containers/fedora/config.json.template
- contrib/system_containers/rhel/config.json.template
Fix Origin tests :) @mrunalp PTAL
> system container: add /var/tmp as RW

- vendor.conf
- vendor/github.com/opencontainers/runtime-tools/README.md
- vendor/github.com/opencontainers/runtime-tools/generate/generate.go
- vendor/github.com/opencontainers/runtime-tools/specerror/runtime.go
- vendor/github.com/opencontainers/runtime-tools/validate/validate.go
Bump opencontainers/runtime-tools to fix https://github.com/kubernetes-incubator/cri-o/issues/1312
This basically pulls in https://github.com/opencontainers/runtime-tools/pull/581
Fix https://github.com/kubernetes-incubator/cri-o/issues/1312
> vendor: bump runtime-tools to fix caps drop handling

- lib/container_server.go
- pkg/annotations/annotations.go
- server/container_create.go
- server/container_status.go
- server/sandbox_run.go
Fix https://github.com/kubernetes-incubator/cri-o/issues/1319 @RenaudWasTaken PTAL, we now read container's annotations as well
The other commits are fixups
@mrunalp PTAL
> Hooks from ctr annotations

- version/version.go
> Release 1.9.4

- pkg/storage/image.go
> image: Add lock around image cache access

- version/version.go
> Release v1.9.5

- releases/v1.9.5.toml
> release: Add v1.9.5

- oci/oci.go
> Add container id to exit file missing warning

- releases/v1.9.6.toml
> releases: add v1.9.6.toml

- Makefile
- vendor.conf
- vendor/github.com/containers/image/copy/manifest.go
- vendor/github.com/containers/image/directory/directory_dest.go
- vendor/github.com/containers/image/docker/docker_client.go
- vendor/github.com/containers/image/docker/docker_image_dest.go
- vendor/github.com/containers/image/image/docker_schema1.go
- vendor/github.com/containers/image/image/oci.go
- vendor/github.com/containers/image/ostree/ostree_dest.go
- vendor/github.com/containers/image/storage/storage_reference.go
- vendor/github.com/containers/image/tarball/tarball_reference.go
> vendor: update c/image to handle text/plain from registries

- oci/oci.go
> 1.9: Add container id to exit file missing warning

- lib/sandbox/sandbox.go
- server/sandbox_stop.go
see individual commits, @mrunalp @sameo PTAL
> [release-1.9] netns fixes

- version/version.go
Release v1.9.7
@runcom @rhatdan We need new rpm builds.
> Release 1.9.7

- Makefile
> Fix SELINUXOPT handling

- lib/sandbox/sandbox.go
> Add context to net ns symlink removal errors

- lib/config.go
- lib/container_server.go
- lib/sandbox/sandbox.go
- pkg/annotations/annotations.go
- server/container_create.go
- server/sandbox_network.go
- server/sandbox_run.go
- server/sandbox_stop.go
- server/server.go
This allows one to optionally disable the network namespace pinning.
> Make network namespace pinning optional

- tutorial.md
- version/version.go
> version: Bump to 1.10 dev

- cmd/crio/main.go
- cmd/crio/selinux_linux.go
- cmd/crio/selinux_unsupported.go
> crio: abstract the selinux call

- lib/logs.go
- lib/testdata/config.toml
- test/helpers.bash
- transfer.md
> Change all references from kpod to podman

- contrib/system_containers/centos/config.json.template
- contrib/system_containers/centos/manifest.json
- contrib/system_containers/fedora/config.json.template
- contrib/system_containers/fedora/manifest.json
- contrib/system_containers/rhel/config.json.template
- contrib/system_containers/rhel/manifest.json
Make /var/lib rslave, add /var, add /opt and update mount propagations on other mounts.
@rhatdan @runcom @giuseppe PTAL
> system_containers: Update mounts

- version/version.go
Release v1.9.8
@runcom @rhatdan PTAL
We will need new rpms after this merged.
> Release v1.9.8

- cmd/crio/main.go
- lib/container_server.go
- lib/hooks.go
- server/server.go
implement hooks refresh with fsnotify
fix #1331 
> Fsnotify hooks

- lib/container_server.go
- lib/container_server_linux.go
- lib/container_server_unsupported.go
> lib: abstract out sandbox for platforms

- conmon/conmon.c
change the way the log file is replaced once it reaches the maximum size
I first create a new file, then rename it to the old one; instead of deleting the old one then creating a new one.
tail -F $LOG_FILE will not warn with "$LOG_FILE has become inaccessible" when the log file is recreated.
conmon will never leave the log file inaccessible.
> conmon: open+rename the log file instead of unlink+open

- Makefile
> Have make file create the oci/hooks.d directory

- Dockerfile
- contrib/test/integration/build/runc.yml
- vendor.conf
- vendor/github.com/opencontainers/runc/README.md
- vendor/github.com/opencontainers/runc/libcontainer/capabilities_linux.go
- vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go
- vendor/github.com/opencontainers/runc/libcontainer/container_linux.go
- vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
- vendor/github.com/opencontainers/runc/libcontainer/rootfs_linux.go
- vendor/github.com/opencontainers/runc/libcontainer/standard_init_linux.go
- vendor/github.com/opencontainers/runc/libcontainer/user/lookup.go
- vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unix.go
- vendor/github.com/opencontainers/runc/libcontainer/user/lookup_windows.go
- vendor/github.com/opencontainers/runc/libcontainer/user/user.go
- vendor/github.com/opencontainers/runc/vendor.conf
> vendor: update runc to HEAD

- lib/config.go
- lib/config_linux.go
- lib/config_unsupported.go
> lib: abstract out selinux call

- Vagrantfile
Signed-off-by: Aaron Weitekamp <aweiteka@redhat.com>
> add dev vagrantfile

- vendor.conf
- vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default.go
- vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default_linux.go
- vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default_unsupported.go
- vendor/github.com/opencontainers/runtime-tools/specerror/config.go
- vendor/github.com/opencontainers/runtime-tools/validate/validate.go
- vendor/github.com/opencontainers/runtime-tools/validate/validate_linux.go
- vendor/github.com/opencontainers/runtime-tools/validate/validate_unsupported.go
A couple of cross-platform PRs merged.
> vendor: update runtime-tools to HEAD

- conmon/conmon.c
so we can correctly invoke the exit command if conmon receives them.
> conmon: catch SIGTERM, SIGINT and SIGQUIT

- conmon/conmon.c
In order to get systemd socket passing to work properly
the listen PID needs to match the process ID of the OCI runtime.
This match modifies the LISTEN_PID if it is set to the new runtime.
conmon will check that the LISTEN_PID the pid that conmon is running as and
will ignore it if they are different.  But, if the caller specifies the
--replace-listen-pid flag, then the LISTEN_PID/LISTEN_FDS will always be used.
> Setup LISTEN_PID to point to new child process

- server/sandbox_stop.go
The CNI hook expects to be able to access the network namespace of
the pod infra container.
@rajatchopra @runcom PTAL
Moved stop pod infra container after network stop
e2e pass
> sandbox_stop: Call CNI stop before stopping pod infra container

- lib/container_server.go
- lib/container_server_linux.go
- lib/container_server_unsupported.go
- lib/stats.go
- lib/stats_linux.go
> lib: libcontainer references are linux only

- version/version.go
> Bump 1.9.9

- lib/sandbox/sandbox.go
> lib/sandbox: clarify variable names

- pkg/storage/image.go
Refactor some code around imageCache handling. Primarily fixes missing locking, but also simplifies logic a little
> Image cache lock

- cmd/crio/main.go
- conmon/conmon.c
- server/container_attach.go
Apply https://github.com/kubernetes-incubator/cri-o/pull/1436
to master
> conmon: Remove info logs

- oci/oci.go
The function waitContainerStop() in oci/oci.go was designed to check
on a container process and wait for it until it returns, or returns
an error if a timeout was reached.
Now, looking at the way this function is used, it is called twice
from the same function StopContainer() with the idea of trying to
wait the process properly first. Then, if the process is not
terminating as expected, another signal is sent to the container
process, and another call to waitContainerStop() is issued.
This second call should be the only one calling into SIGKILL because
this is the last chance to stop the container process. But from the
first call into this function, we should only retrieve sort of a
boolean value telling if the process is still around, instead of
trying to kill it with a SIGKILL already. …
> oci: Force kill the container process only if nothing else worked

- vendor.conf
- vendor/github.com/containers/image/copy/copy.go
- vendor/github.com/containers/image/directory/directory_dest.go
- vendor/github.com/containers/image/directory/directory_src.go
- vendor/github.com/containers/image/directory/directory_transport.go
- vendor/github.com/containers/image/docker/archive/src.go
- vendor/github.com/containers/image/docker/daemon/daemon_src.go
- vendor/github.com/containers/image/docker/docker_image_src.go
- vendor/github.com/containers/image/image/memory.go
- vendor/github.com/containers/image/image/sourced.go
- vendor/github.com/containers/image/image/unparsed.go
- vendor/github.com/containers/image/oci/archive/oci_src.go
- vendor/github.com/containers/image/oci/layout/oci_src.go
- vendor/github.com/containers/image/openshift/openshift.go
- vendor/github.com/containers/image/ostree/ostree_dest.go
- vendor/github.com/containers/image/ostree/ostree_src.go
- vendor/github.com/containers/image/storage/storage_image.go
- vendor/github.com/containers/image/tarball/tarball_src.go
- vendor/github.com/containers/image/transports/alltransports/ostree.go
- vendor/github.com/containers/image/transports/alltransports/ostree_stub.go
- vendor/github.com/containers/image/types/types.go
fixes needed for cross-platform are now in containers/image HEAD
> vendor: update containers/image to HEAD

- lib/config.go
- lib/container_server.go
- lib/sandbox/sandbox.go
- server/sandbox_network.go
- server/sandbox_run.go
- server/sandbox_stop.go
- server/server.go
> Make network namespace lifecycle management optional

- version/version.go
> Release 1.9.10

- lib/container.go
- server/container_attach.go
- server/container_exec.go
- server/container_execsync.go
- server/container_start.go
- server/container_status.go
- server/container_update_resources.go
> Add support for partial IDs for exec and attach

- version/version.go
Release v1.10.0-beta.1
@runcom @rhatdan PTAL
> v1.10 beta 1

- .travis.yml
> travis: bump up go versions

- .clang-format
- Makefile
- conmon/cmsg.c
- conmon/conmon.c
- pause/pause.c
Added clang format support.
Added a .clang-format style file
Look at the beautifully formatted code ;)
> Use formatter for C code

- lib/stats.go
- server/container_list.go
- server/container_stats.go
- server/container_stats_list.go
- server/image_fs_info.go
- utils/filesystem.go
Pull in commits needed to fix #1248 on release-1.9 branch.
Signed-off-by: Yann Ramin <atrus@stackworks.net>
Signed-off-by: Bo Zhao <bzhao@lyft.com>
Signed-off-by: Paul Fisher <pfisher@lyft.com>
Add CRI API support for container and imagefs stats
> Backport container and imageFs stats to release-1.9 branch

- Dockerfile
- contrib/test/integration/build/cri-tools.yml
- contrib/test/integration/critest.yml
- contrib/test/integration/main.yml
Picks up new pid namespace tests.
Also picks up the changes made to critest so it doesn't depend on the source code.
> Update cri-tools commit to pick up latest tests and changes

- Dockerfile
- contrib/test/integration/main.yml
Added new exec tests to cri-tools. Pull in updated cri-tools master
to run tests with cri-o.
> Update cri-tools version

- conmon/conmon.c
> conmon: Add container id to syslog

- docs/crio.8.md
> Add documentation of files used by cri-o

- oci/oci.go
Fix https://github.com/kubernetes-incubator/cri-o/issues/1477
Log the error from sending the stop signal to the container instead of erroring out. There could be a race as highlighted in https://github.com/kubernetes-incubator/cri-o/issues/1477 so we just log and leave logic to `waitContainerStop`.
@phemmer @mrunalp  PTAL
I'll back port this patch to 1.9.x once this is merged.
> oci: avoid race on container stop

- pkg/findprocess/findprocess_windows.go
> findprocess: no new variables for :=

- oci/oci.go
- pkg/findprocess/findprocess.go
- pkg/findprocess/findprocess_test.go
- pkg/findprocess/findprocess_unix.go
- pkg/findprocess/findprocess_windows.go
> [release-1.9] oci: avoid race on container stop

- oci/oci.go
- pkg/findprocess/findprocess.go
- pkg/findprocess/findprocess_test.go
- pkg/findprocess/findprocess_unix.go
- pkg/findprocess/findprocess_windows.go
> [release-1.10] oci: avoid race on container stop

- cmd/crio/main.go
- server/sandbox_status_test.go
- server/sandbox_stop.go
- server/server.go
Backported from #1494 with no conflicts.
> [release 1.10] server/sandbox_stop: Pass context through StopAllPodSandboxes

- cmd/crio/daemon_unsupported.go
- cmd/crio/main.go
- pkg/signals/signal.go
- pkg/signals/signal_unix.go
- pkg/signals/signal_windows.go
> main: a couple of platform depedent calls

- contrib/test/integration/build/cri-o.yml
- contrib/test/integration/build/kubernetes.yml
- contrib/test/integration/e2e.yml
- contrib/test/integration/golang.yml
- contrib/test/integration/system.yml
- contrib/test/integration/test.yml
Update all ``lineinfile`` and similar tasks to also add a comment indicating the change came from Ansible, and from which specific YAML file.
Use YAML line-folding syntax.
The CI tests won't puke if I did it right :smile:
> Add mark comments near all lines added by Ansible

- conmon/conmon.c
WEXITSTATUS(x) can be used only if WIFEXITED(x).  We were using it
also in the case the process exited because it was signaled.
Since we check for the exit_status both for the container and the
runtime, move the common code to a new function get_exit_status that
is used in both cases.
Fix the exit status reported by conmon
I added a check if the process was exited because of a signal
conmon returns exit status 137 on "kill -9 $CONTAINER_PID"
conmon returns the corrrect exit status when the process is signaled
> conmon: return the correct exit status

- version/version.go
@rhatdan @runcom @umohnani8 PTAL
> Release v1.9.11

- oci/finished.go
- oci/finished_32.go
- oci/finished_unsupported.go
- oci/oci.go
- oci/oci_linux.go
- oci/oci_unix.go
- oci/oci_unsupported.go
- oci/oci_windows.go
ensured that other `GOOS=` can build for the `oci` package
ensure it doesn't break the `GOOS=linux` defaults
> oci: changes for cross-platform

- server/sandbox_run.go
@umohnani8 @rhatdan PTAL. I will add this commit to the 1.10 PR.
> sandbox_run: Drop ambient capabilities for infra pod

- test/image.bats
- test/shm.bats
- test/testdata/container_sleep.json
> Add test to see if /dev/shm is working correctly

- test/ctr.bats
This depends on #1539 which should be merged first.
> Test for non root user capabilities

- version/version.go
> Release 1.9.12

- version/version.go
> Release 1.10.1

- tutorial.md
Followed the tutorial. Had some issues. Modified the doc adding the steps I've taken to progress.
"crictl create" was not working with the image path in container_redis.json so I changed it to the path that made it work for me.
Followed the tutorial, googled.
Follow the tutorial on a fresh VM.
Added clearer instructions to the tutorial.
> Updated tutorial.md

- version/version.go
Replaces #1563 
This changes the master version to 1.11.0-dev as that's what master is tracking right now.
@rhatdan @lsm5 @umohnani8 PTAL
> version: v1.11.0-dev

- server/container_exec.go
- server/container_exec_unix.go
- server/container_exec_windows.go
> server: platform specific tty handling

- .travis.yml
> .travis.yml: install gpgme on osx

- .travis.yml
> .travis.yml: allow failures for go tip

- .travis.yml
- Makefile
- server/container_create.go
- server/sandbox_run.go
- test/ctr.bats
- test/default_mounts.bats
- test/image_volume.bats
- test/pod.bats
- test/test_runner.sh
> tests: enable integration tests with user namespaces

- version/version.go
Release 1.9.13
@rhatdan @runcom PTAL
> Release 1.9.13

- lib/config.go
> lib: config: use official kube pause image from gcr

- server/container_create.go
> container_create: support CRI RunAsGroup

- .travis.yml
- Dockerfile
- contrib/test/integration/main.yml
- server/container_create.go
- test/ctr.bats
- test/helpers.bash
- test/pod.bats
- test/restore.bats
> [release-1.10] container_create: support CRI RunAsGroup

- Dockerfile
- contrib/test/integration/main.yml
- test/ctr.bats
- test/helpers.bash
- test/pod.bats
- test/restore.bats
bump cri-tools and adapt our code to it
vim
CI
> contrib,test: bump cri-tools

- version/version.go
> Release 1.10.2

- server/container_create.go
- server/container_portforward.go
> container_create: fixes

- server/container_create.go
- server/container_portforward.go
> Create fixes 1.10

- cmd/crio/main.go
> [release-1.10] cmd: crio: suppress logging before flag.Parse

- version/version.go
I'll tag the new version once all other PR for 1.10.x are merged and I rebase this one.
> release 1.10.3

- README.md
> README.md: add 1.10 to version matrix

- server/container_create.go
- server/sandbox_run.go
> [release-1.10] Selinux relabel fixes for 1.10

- client/client.go
- lib/container_server.go
- lib/logs.go
- lib/remove.go
- lib/rename.go
- lib/sandbox/sandbox.go
- lib/sandbox/sandbox_linux.go
- lib/sandbox/sandbox_unsupported.go
- lib/stop.go
- lib/wait.go
- oci/container.go
- oci/oci_windows.go
- pkg/storage/image.go
- server/container_create.go
- server/inspect_test.go
- server/sandbox_list.go
- server/sandbox_run.go
- server/sandbox_status_test.go
- server/server.go
> *: abstract out netns for multiple platforms

- vendor.conf
- vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
- vendor/github.com/opencontainers/selinux/go-selinux/selinux.go
> Vendor in latest go-selinux bindings

- server/container_attach.go
- server/container_exec.go
- server/container_portforward.go
- server/sandbox_network.go
- server/sandbox_stop.go
- server/server.go
deleted or unexposed public functions that were not used outside of `server.Server`
> server.Server: cleanup of public functions

- contrib/system_containers/centos/Dockerfile
- contrib/system_containers/fedora/Dockerfile
update to reflect the current status
> system-containers: update maintainer for Fedora and CentOS to myself

- .travis.yml
- Makefile
makefile target and basic compile check in travis.
For now this does not fail travis validation, but will show the red X
> cross platform compiles

- version/version.go
> release v1.10.4

- lib/config.go
- lib/config_unix.go
- lib/config_windows.go
- oci/oci.go
- oci/oci_unix.go
- oci/oci_windows.go
- server/config.go
- server/config_unix.go
- server/config_windows.go
- server/server.go
Isolate platform specific paths into variables
> platform specific default paths

- version/version.go
Release 1.11.0 for k8s.
@runcom @rhatdan PTAL
> Release 1.11.0

- vendor.conf
- vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
- vendor/github.com/cri-o/ocicni/pkg/ocicni/util.go
- vendor/github.com/cri-o/ocicni/pkg/ocicni/util_linux.go
- vendor/github.com/cri-o/ocicni/pkg/ocicni/util_unsupported.go
> vendor: update github.com/cri-o/ocicni

- Dockerfile
- contrib/test/integration/main.yml
> [1.11] cri-tools: Use release-1.11 branch

- lib/container_server.go
- server/container_create.go
- server/container_list.go
- server/container_stats_list.go
- server/sandbox_list.go
- server/server.go
- vendor.conf
- vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
- vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
- vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
- vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go
> Vendor in latest go-selinux so that it supports non linux builds

- README.md
> readme: Add 1.11 to compatibility matrix

- version/version.go
> version: v1.12.0-dev

- server/container_create.go
> [release-1.10] server/container_create: mask /proc/{acpi,keys}

- version/version.go
> Bump 1.10.6

- version/version.go
> Bump 1.11.1

- version/version.go
> Release v1.9.14

- conmon/conmon.c
Podman will inject fd's into conmon so that open TCP/UDP ports will be
kept busy while the container is running.  This introduces a race
condition as conmon could notify the container exited but these fd's
are still kept busy.  Close them before notifying the container
exited.
Required by: https://github.com/projectatomic/libpod/pull/1100
close extra fd's before conmon terminates
cycle through the fds 3-... until we find an unused fd
strace conmon and verify there are a bunch of close(..) before it exits
conmon closes extra files before it exits
> conmon: close extra files before exit

- cmd/crio/main.go
- server/config.go
- server/server.go
ref: https://github.com/kubernetes/kubernetes/pull/64006
ref: https://github.com/containerd/cri/pull/858
ref: https://github.com/containerd/cri/issues/777
@mrunalp PTAL
> server: serve streaming on localhost on a random port

- server/sandbox_network.go
Close https://github.com/kubernetes-incubator/cri-o/issues/1713
> sandbox_network: allow ipv6 addresses

- test/ctr.bats
> [1.11] test: Add a test for low memory configured

- test/ctr.bats
Low mem test for master branch.
> test: Add a test for low memory configured

- .travis.yml
- Makefile
> Begin shifting to use podman rather then docker

- lib/container_server.go
- server/container_create.go
- server/sandbox_run.go
This reverts commit eb1e0babd0f2405142b8075a485388f40849fb89.
#1744 for 1.11 branch.
> [1.11] Revert "server: Don't make additional copy of config.json"

- version/version.go
> Release v1.11.2

- Dockerfile
- contrib/test/integration/build/runc.yml
- vendor.conf
- vendor/github.com/opencontainers/runc/README.md
- vendor/github.com/opencontainers/runc/libcontainer/cgroups/fs/apply_raw.go
- vendor/github.com/opencontainers/runc/libcontainer/cgroups/systemd/apply_systemd.go
- vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
- vendor/github.com/opencontainers/runc/libcontainer/configs/validate/rootless.go
- vendor/github.com/opencontainers/runc/libcontainer/configs/validate/validator.go
- vendor/github.com/opencontainers/runc/libcontainer/container_linux.go
- vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go
- vendor/github.com/opencontainers/runc/libcontainer/factory_linux.go
- vendor/github.com/opencontainers/runc/libcontainer/init_linux.go
- vendor/github.com/opencontainers/runc/libcontainer/message_linux.go
- vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
- vendor/github.com/opencontainers/runc/libcontainer/process.go
- vendor/github.com/opencontainers/runc/libcontainer/rootfs_linux.go
- vendor/github.com/opencontainers/runc/libcontainer/standard_init_linux.go
- vendor/github.com/opencontainers/runc/libcontainer/system/linux.go
- vendor/github.com/opencontainers/runc/libcontainer/system/unsupported.go
- vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unix.go
- vendor/github.com/opencontainers/runc/libcontainer/user/user.go
> Update runc to latest

- contrib/test/integration/main.yml
> test: Switch to go 1.11

- .travis.yml
- Dockerfile
- lib/container_server.go
> travis: Switch to go 1.11

- pkg/storage/image.go
- server/image_pull.go
What's in CanPull is already done by PrepareImage so remove this
redunant check which can hit the network as well.
> [release-1.11] image_pull: remove redunant CanPull check

- pkg/storage/image.go
- server/image_pull.go
What's in CanPull is already done by PrepareImage so remove this
redunant check which can hit the network as well.
> image_pull: remove redunant CanPull check

- pkg/storage/image.go
- server/image_pull.go
fixes the various failures we've seen in the CI in #1772 and #1768 
> [release-1.11] image_pull: fix variable shadowing

- server/sandbox_run.go
same as #1781 but for `release-1.11`
When running a pod with privileged we just need to set the process
label to the empty string. We don't need to wipe out the mount labels
as those are stil applied to mounts and rootfs even if in privileged
mode.
Fix https://bugzilla.redhat.com/show_bug.cgi?id=1624326
We need this to also match the behavior with docker:
```
docker run -ti -v $(mktemp -d):/testselinux:Z --security-opt
label=level:s0:c25,c968 fedora ls -ldZ /testselinux
drwx------. 2 27212 27212 system_u:object_r:container_file_t:s0:c25,c968
40 Sep  6 17:13 /testselinux
docker run --privileged -ti -v $(mktemp -d):/testselinux:Z
--security-opt label=level:s0:c25,c968 fedora ls -ldZ /testselinux
drwx------. 2 27212 27212 system_u:object_r:container_file_t:s0:c25,c968
40 Sep  6 17:14 …
```
> [release-1.11] server: don't wipe out the selinux mount label if privileged

- version/version.go
I'll tag 4fbb0226dd4114aabc5ed13e292179f00e0f8690 as `v1.11.3`
> Bump 1.11.3

- Dockerfile
- contrib/test/integration/build/cri-tools.yml
- contrib/test/integration/main.yml
- server/sandbox_status.go
- server/sandbox_status_test.go
> test: Fixup kubernetes-incubator to kubernetes-sigs

- Dockerfile
- contrib/test/integration/build/cri-tools.yml
- server/container_list.go
- server/container_status.go
- server/sandbox_list.go
> [release-1.11] use in memory created time

- version/version.go
> Release 1.11.4

- Dockerfile
- contrib/test/integration/main.yml
Change git version of cri-tools to pick up new test added
for process and mount labels.
> Pick up new tests for critest

- lib/container_server.go
- lib/sandbox/history.go
- lib/sandbox/sandbox.go
- oci/container.go
- server/container_create.go
- server/container_list.go
- server/sandbox_list.go
- server/sandbox_run.go
@runcom @umohnani8 @rhatdan PTAL
Fixed a race between create/list for containers and sandboxes.
Added a created bool for container and sandbox and use that to filter them in list APIs.
Test pass
Fix race between create and list.
> [release-1.11] Fix create/list race

- lib/config.go
> [release-1.11] config: default file_locking to false

- test/ctr.bats
> [release-1.11] test: Use crictl logs for parsing log file in tty test

- lib/container_server.go
- lib/sandbox/history.go
- lib/sandbox/sandbox.go
- oci/container.go
- server/container_create.go
- server/container_list.go
- server/sandbox_list.go
- server/sandbox_run_linux.go
> Fix list/create race

- test/ctr.bats
> test: Use crictl logs for parsing log file in tty test

- version/version.go
I'll tag https://github.com/kubernetes-sigs/cri-o/commit/1c8a4b1eec7925285db4ba96ae0a9c97a6a17782 as `v1.11.5`
> Bump 1.11.5

- contrib/test/integration/e2e.yml
@runcom Let's see a few runs on 1.11
> [release-1.11] test: Run e2e in parallel

- server/container_status.go
Add pid and sandboxId for container
Fixes #1752.
> container_status: Add debug info for container

- server/sandbox_run_linux.go
If the CNI setup fails in runPodSandbox, the infra container started is
not stopped/removed and leaks.
Ensure the necessary clean-up steps are executed on error
path.
Fixes: #1816
> runPodSandbox: clean up containers on error path

- version/version.go
> Release 1.11.6

- oci/container.go
Addresses part of #1824.
@runcom PTAL
> Use RWLock for containers

- contrib/test/integration/main.yml
> test: Update to go 1.11.1

- cmd/crio/config.go
- oci/container.go
- server/sandbox_remove.go
- server/sandbox_stop_linux.go
Fix typos issues in below files:
1. cmd/crio/config.go
2. oci/container.go
3. server/sandbox_remove.go
4. server/sandbox_stop_linux.go
Remove the duplications in files.
> Fix typos issues

- cmd/crio/config.go
- cmd/crio/main.go
- lib/config.go
- server/container_create_linux.go
- server/sandbox_run_linux.go
- server/utils.go
- test/command.bats
- test/ctr.bats
- test/helpers.bash
Provide flag and configuration options to set default ulimits for containers
vi
tests
> *: implement default ulimits for containers

- contrib/test/integration/main.yml
> [1.12] Use fsync instead of sync for stateful set tests

- cmd/crio/main.go
- utils/utils.go
includes:
- https://github.com/kubernetes-sigs/cri-o/pull/1835
- https://github.com/kubernetes-sigs/cri-o/pull/1813
> [release-1.12] SIGPIPE and SIGUSR1 handling

- cmd/crio/main.go
- utils/utils.go
> cmd: crio: catch and ignore SIGPIPE

- cmd/crio/main.go
> [release-1.11] cmd: crio: catch and ignore SIGPIPE

- conmon/conmon.c
@giuseppe @runcom @umohnani8 PTAL
> conmon: fsync the log file

- README.md
> Update support table to include 1.12

- contrib/test/integration/main.yml
> Move e2e back to master

- conmon/conmon.c
> [1.12] conmon: fsync the log file

- Makefile
> [1.11] Fix release-tool

- Makefile
> [1.12] Fix release-tool

- oci/oci.go
- server/container_list.go
- server/sandbox_list.go
> [1.11] Use current status for list calls

- oci/oci.go
- server/container_list.go
- server/sandbox_list.go
> [1.12] Use current status for list calls

- version/version.go
> Release 1.11.8

- oci/oci.go
- server/container_list.go
- server/sandbox_list.go
> Use current status for list calls

- docs/crio.conf.5.md
- test/README.md
Cleanup duplications in documents:
1. docs/crio.conf.5.md
2. test/README.md
> Fix documents issues

- server/container_create.go
> [release-1.11] container_create: fix dev mounts and remove nodev from /dev mounts

- server/container_create.go
- server/container_create_linux.go
> [release-1.12] container_create: fix dev mounts and remove nodev from /dev mounts

- README.md
Fixed broken links in docs.
docs: fix links to policy.json, registries.conf
> docs: fix links to policy.json, registries.conf

- OWNERS
I am not actively working on the project, so removing myself from the file.
/assign @mrunalp
> Update OWNER file

- contrib/test/integration/e2e.yml
> test: Networking setup for DNS tests

- pkg/storage/runtime.go
- vendor.conf
- vendor/github.com/containers/storage/drivers/aufs/aufs.go
- vendor/github.com/containers/storage/drivers/overlay/overlay.go
- vendor/github.com/containers/storage/layers.go
- vendor/github.com/containers/storage/pkg/idtools/parser.go
- vendor/github.com/containers/storage/store.go
> [release-1.12] vendor: revendor c/storage to fix a devicemapper bug

- conmon/conmon.c
> [1.12] Do not overflow local buffer

- server/sandbox_network.go
- server/server.go
Don't use stream server address as it default to 127.0.0.1 now.
> Return the correct host IP

- server/sandbox_network.go
- server/server.go
Fixes #1895 
Don't use stream server address as it default to 127.0.0.1 now.
> [1.12] Return the correct host IP

- docs/crio.8.md
`s/CRI-I/CRI-O/`
Signed-off-by: Radostin Stoyanov <rstoyanov1@gmail.com>
> man: Fix typo

- version/version.go
@runcom @giuseppe @umohnani8 ptal
> Release 1.12.3

- README.md
Also add a link to Kubernetes versioning which is the one we follow.
> README.md: remove unsupported releases

- contrib/test/integration/build/kubernetes.yml
- contrib/test/integration/e2e-base.yml
- contrib/test/integration/e2e-features.yml
- contrib/test/integration/main.yml
- server/container_create.go
same as #1849 + a new test job for features :)
~~need to address @mrunalp comment here https://github.com/kubernetes-sigs/cri-o/pull/1849#issuecomment-430832689 as well but waiting on CI first~~
This PR also needs:
- ~~https://github.com/openshift/aos-cd-jobs/pull/1644~~
- ~~https://github.com/openshift/release/pull/2101~~
- ~~https://github.com/openshift/test-infra/pull/178~~
~~After the above are merged, we need to run the new `/test e2e_features` jobs~~
this is needed for 1.11 and 1.12 as well
> RunAsGroup fixes and tests

- version/version.go
> version: bump to v1.14.0-dev

- contrib/test/integration/main.yml
> test: Update to golang 1.10.6 and 1.11.3

- cmd/crio/config.go
> [1.13] config: Add missing comma after each hooks_dir item

- lib/sandbox/sandbox.go
- server/container_create.go
- server/sandbox_network.go
- server/sandbox_stop_linux.go
solves a couple of race conditions that are seen with short lived pods.
More details in each of the commits
> fix some race conditions with short lived pods

- server/container_create_linux.go
When running crio with id-mappings,it fails to create container
due to permission errors.
Fixes: #1939
Signed-off-by: vikaschoudhary16 <vichoudh@redhat.com>
> Usernamespaces: Fix permissions on runDirPath and BundlePath

- pkg/seccomp/seccomp.go
The function `setupSeccomp()` function missed some nil pointer checks, which are now added via this PR.
> Add seccomp nil checks

- version/version.go
> Release 1.12.4

- README.md
> readme: Add link to Weekly Meeting wiki page

- version/version.go
> Release v1.11.11

- conmon/conmon.c
> Cleanup coverity scan issues

- contrib/systemd/crio.service
> contrib/systemd: add metrics env

- server/container_stats.go
included a patch from Mrunal Patel
PR#1869#issuecomment-459530581
See https://github.com/kubernetes-sigs/cri-o/pull/1869 and https://github.com/kubernetes-sigs/cri-o/pull/1869#issuecomment-459530581 . I basically just cherry-picked the original patch and applied mrunal's changes to release-1.12 branch
@mrunalp @vrothberg @rhatdan PTAL
> Add disk usage for ListContainerStats

- utils/filesystem_test.go
- utils/suite_test.go
- utils/utils_test.go
This PR adds unit tests to the `utils` package.
> Add utils unit tests

- version/version.go
> Release 1.12.5

- cmd/crio/config.go
- cmd/crio/main.go
- docs/crio.8.md
- docs/crio.conf.5.md
- lib/config.go
- lib/container_server.go
- lib/testdata/config.toml
- pkg/config/config.go
- server/sandbox_status_test.go
- test/helpers.bash
Signed-off-by: W. Trevor King <wking@tremily.us>
Add same changes in #1943 to release-1.12
> Backport hooks fix to release-1.12

- pkg/storage/image.go
Backport-of: https://github.com/kubernetes-sigs/cri-o/pull/2059
> pkg/storage/image: wire in blocking registries feature

- contrib/test/integration/e2e.yml
- version/version.go
@rhatdan @giuseppe @umohnani8 ptal.
> Release v1.12.6

- version/version.go
> Release 1.13.1

- server/container_create.go
Backport of #1898 and #2090 to release-1.12.
@giuseppe @rhatdan @umohnani8 ptal.
> [1.12] Backport of user related fixes

- server/server.go
- test/restore.bats
If a pod or a container could not be restored, then delete them
from the storage.
Since the container was present in the storage and CRI-O didn't report
it to the the Kubelet, we would have failed the request from the
Kubelet to re-create it over and over again.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1677509
(cherry picked from commit 67639b573b059fa55635794bcacb557b4909b327)
> server: delete the container if it cannot be restored

- cmd/crio/main.go
- contrib/test/integration/golang.yml
> Increase max grpc message size

- contrib/test/integration/e2e.yml
@rhatdan @haircommander @umohnani8 ptal.
> test: Retry flakes one more time
