- cmd/client/main.go
Currently it was hard coded to /var/run/ocid.sock, makes it configurable with a --sock flag.  Still defaults to original location
> make socket location configurable on cmd line

- .gitignore
- Makefile
- conmon/conmon.c
- oci/oci.go
- server/runtime.go
@mrunalp PTAL - see individual commits, the various format fixes in `conmon.c` have been done with vim following the linux guidelines with https://github.com/crosbymichael/vim-cfmt
I got a pod sandbox to run but first I had to do the following:
```
```
> Various fixes

- oci/history.go
- oci/memory_store.go
- oci/store.go
- server/runtime.go
- server/server.go
Instead of that locking everywhere... also with a nice read/write lock. This is how docker/docker daemon holds a list of containers in memory - we aren't lucky though since the implementation doesn't live under `docker/docker/pkg` and I couldn't import it from `docker/docker/daemon/container`.
> use an in memory store for containers

- .gitignore
- cmd/server/main.go
@mrunalp PTAL - required also for https://github.com/kubernetes-incubator/ocid/pull/43 so we don't rely on the same socket for every test.
> cmd/server: add socket flag

- cmd/client/sandbox.go
This makes it easier to test creation of multiple pods
from the same config.json file.
> Allow overriding name in a pod sandbox config file

- server/sandbox.go
- server/server.go
Allow re-using a pod name after the pod has been removed.
> Pod create bug

- .tool/lint
- Makefile
Close #68 
@rhatdan we can't install automatically because it will pollute the project's GOPATH - I'm providing an hint to run `make install.tools` instead
> Makefile: suggests install.tools

- .travis.yml
`make install.tools` already installs `gometalinter` (as can be seen in
the logs), so the subsequent `go get` steps are unnecessary.
This change also reorders the build directives according to execution
order: https://docs.travis-ci.com/user/customizing-the-build#The-Build-Lifecycle
and replaces the "before_install" step with an override of the default
"install" procedure (which we were suppressing anyway with install: true)
> (WIP) Remove redundant build steps

- .travis.yml
This will give us early warning of changes in upstream Golang that
may affect us.
> (WIP) Build with "tip" version of Golang

- conmon/Makefile
It should be possible to run make with compilation CFLAGS / LIBS
paramaters. For instance, 'make CFLAGS="-g3 -O0"'. Fixes #87
Signed-off-by: Alvaro Lopez Ortega <alvaro@gnu.org>
> Fixes Makefile so CFLAGS/LIBS are accepted as a make parameter

- test/ctr.bats
- test/pod.bats
- test/runtimeversion.bats
In several places, we previously didn't output the $output of the
failing command, leading to confusion when debugging. A proper fix is to
alias oci{c,d} in helpers.sh like runC does, but that can come later.
> test: add more debugging output

- .tool/lint
- oci/oci.go
- server/container.go
- server/sandbox.go
- server/server.go
This PR introduces IDs for containers separating them from container names similar to what we have for pods. I will add support for short IDs in a follow on PR.
@runcom PTAL
> Refactor to separate container IDs from container names

- server/container.go
@runcom Bug from the refactor. Remove already uses the container ID.
> Use container ID as the directory name

- Makefile
When doing make install on ubuntu I'm getting the following error..
mike@mike-VirtualBox:~/go/src/github.com/kubernetes-incubator/cri-o$ sudo make docs
make: command: Command not found
/bin/sh: 1: Syntax error: "in" unexpected
Makefile:80: recipe for target 'docs/ocid.8' failed
make: [docs/ocid.8] Error 2 (ignored)
So I'd like to change from using `command -v` to `which` to identify the path to go-md2man.
> fixes issue with ubuntu build

- README.md
- cmd/server/main.go
Checking for whether we have a runtime path that exists.  And a small amount of read me text for resolution when the path is not the default.
> small amount of error checking and help for path to the runtime

- oci/oci.go
- server/container.go
- server/sandbox.go
Move Container State constants to oci package
and fixup where strings were used instead of
the state constants
> Container state fixes

- server/sandbox.go
SELinux will cause breakage when sharing these namespaces.  For example it
will block processes inside of the container from looking at the hosts /proc
in hosts Pid Namespace.  It will also block all access to semaphores and
shared memory defined outside of the pod.
> Can't use SELinux separation when sharing the host pid or ipc namespace

- README.md
- test/testdata/container_redis.json
Container will fail to load correctly if you don't have the directory specified by the mount in the config.
> removing mount from container_redis

- cmd/client/container.go
- cmd/client/sandbox.go
- server/container.go
- server/sandbox.go
- server/server.go
- test/ctr.bats
- test/helpers.bash
- test/pod.bats
- test/restore.bats
Close https://github.com/kubernetes-incubator/cri-o/issues/17
Close #111
Keep in mind this comment https://github.com/kubernetes-incubator/cri-o/issues/17#issuecomment-252249629 meaning we don't have any way right now to fully restore if someone plays with runc directly (we'll address that ofc).
@rhatdan this is also fixing https://github.com/kubernetes-incubator/cri-o/issues/102#issuecomment-252259251 by storing the process label in the sandbox's config.json.
@mrunalp PTAL - I'm writing some tests but won't likely finish soon (this weekend at least), I'll open another PR shortly.
> server: containers restore

- README.md
After we changed the dependencies for make install, if you don't make docs make install will show an error.
Added some temporary text in the readme explaining how to recover from out of sync sandbox data.
> mention make docs

- server/server.go
@mrunalp PTAL fixing the panic you have into https://github.com/kubernetes-incubator/cri-o/pull/115
> server/server: skip f no sandbox when restoring containers

- README.md
The 'make binaries' command requires the existence of ibc.a.  On Fedora this file is included in the glibc-static package.  If this is not installed the user will get the error '/usr/bin/ld: cannot find -lc'.  On Ubuntu this is not an issue.  The README was updated to reflect this dependency.
> README.md: Update build instructions

- Makefile
Previously, the markdown versions of the man pages were copied to their respective locations, but these cannot be parsed by the man command.  The Makefile was updated to gzip the man pages generated by go-md2man and install the gzipped files into their respective man directories.
> Fix installation of manpages

- test/helpers.bash
The rootfs that gets created needs to have an SELinux label that containers
can write to.  Until they get native storage support, this patch will
force the entire storage pool to be labeled in such a way that confined
containers can read/write/execute the content.
> Setup proper labeling for runnin test with selinux

- Makefile
On Ubuntu, /bin/sh is used in Makefile by default, so
a.{1,2,3} isn't evaluated to a.1 a.2 a.3, another solution
is to use `SHELL=/bin/bash` in Makefile, but I don't think
we should bind to bash this early, at least not for this
case.
This also remove the removal of docs/*.1 which doesn't
exist for now.
Signed-off-by: Qiang Huang <h.huangqiang@huawei.com>
> Makefile: fix remove docs in make clean

- test/helpers.bash
> Make sure selinuxenabled exists before executing it

- server/container.go
kubernetes doesn't share the UTS namespace
> Don't share container UTS namespace with pod

- server/image.go
ocid crashes under kubelet immediately as it can't marshal nil. This PR fixes that by returning empty structs instead of nil and also adds debugs.
> Make image APIs return empty struct instead of nil

- oci/oci.go
Found while trying to package ocid for openSUSE.
This fixes building on i586.
> oci: cast timestamp to int64

- server/container.go
- server/sandbox.go
- server/server.go
infra container is used to implement the pod
sandbox, it should not be exported to user.
this patch stores infra container in sandbox
immediately, only the containers created by user
are stored into container store, this prevents user
from removing/stopping infra container incorrectly.
Signed-off-by: Gao feng <omarapazanadi@gmail.com>
> store infra container in sandbox

- cmd/client/image.go
This patch adds "image list", "image status", and "image remove" subcommands to the client, most of it boilerplate stuff.
> Add "image list/remove/status" to the client

- server/sandbox.go
- server/utils.go
DNSConfig can pass "options" settings in now, so we should add them to the resolv.conf that we're generating.
> Handle PodSandboxConfig.DNSConfig.Options

- cmd/client/container.go
- cmd/client/sandbox.go
- oci/oci.go
- server/container.go
- server/sandbox.go
- server/server.go
- test/ctr.bats
- test/pod.bats
- test/restore.bats
- test/testdata/container_config.json
- test/testdata/sandbox_config.json
Currently, 
1. we didn't store container/pod metadata.
2. metadata in container is not returned to kubelet in list and status APIs
Fix that.
Added test case:
1. add test for pod/ctr metadata in list/status.
2. enhance restore test to check list/status consistency before/after restore.
> Return pod metadata in container list and status APIs 

- README.md
The guideline in README doesn't work, one important step `#make` is
missing, so fix it.
Signed-off-by: Zhang Wei <zhangwei555@huawei.com>
> Add missing steps in README

- server/container.go
- server/sandbox.go
CRI requires all timestamps in nanoseconds instead of seconds.
Signed-off-by: Pengfei Ni <feiskyer@gmail.com>
cc @mrunalp
> Set timestamps to nanoseconds

- server/utils.go
- server/version.go
gRPC version is not needed in Version() endpoint.
PTAL @runcom
> version: remove checking gRPC version

- conmon/conmon.c
- oci/oci.go
When testing ocid against the clear containers runtime we found 2 issues:
1. The bundle path is missing from the create command passed to the container runtime.
2. The pid file passed through `--pid-file` is not an absolute path and could lead to potential issues if the runtime chdir before getting called.
This PR aims at fixing those 2 issues by explicitly building and passing the bundle path and an absolute pid file path to conmon.
> Conmon fixes

- OWNERS
@feiskyer and other engineers from hyper have already been helping with cri-o. @feiskyer is one of the primary contributors to CRI in kubernetes upstream. His inputs and contributions will be invaluable to the project. 
> Add feiskyer as an OWNER

- oci/oci.go
- server/container.go
[Status](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/v1alpha1/runtime/api.pb.go#L3562) is one of the first queries sent to cri-o from kubelet on recent kubernetes master => cri-o crashes on unmarshaling `<nil>`. Added empty functions to provide this functionality. 
Motivation: [StatusResponse](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/v1alpha1/runtime/api.pb.go#L2854) --> [RuntimeStatus](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/v1alpha1/runtime/api.pb.go#L2827) --> [RuntimeCondition](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/v1alpha1/runtime/api.pb.go#L2768)
> Add runtime status compliant with CRI

- Dockerfile
> Dockerfile: bump to golang 1.7.3

- server/sandbox_run.go
- server/utils.go
- test/pod.bats
- test/testdata/sandbox_config.json
close #198 
1. extract sysctls config from annotations and set to oci spec config, treat safe/unsafe sysctls in the same way here.
2. add test case for sysctls, mainly test whether sysctls have been pass to spec config, and whether pod can  start with some specified sysctls. 
Note: the valid of sysctls may be concerned with kernel version( see opencontainers/runc#1193), I picked three I think it's general here. But if someone failed to pass the case, pls let me know that. Or any advice?
> Add support for sysctls

- oci/oci.go
- server/container_execsync.go
- test/ctr.bats
The gprc execsync client call doesn't populate `ExecSyncResponse` on
error at all. You just get an error https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/api/v1alpha1/runtime/api.pb.go#L3144.
This patch modifies the code to include command's streams, exit code
and error direcly into the error. `ocic` will then print useful
infomation in the cli, otherwise it won't.
found while working on https://github.com/kubernetes-incubator/cri-o/pull/211
@mrunalp PTAL
> execsync: return proper error description

- server/container.go
- server/container_create.go
- server/sandbox_run.go
VM base container runtimes (e.g. Clear Containers) will run each pod
in a VM and will create containers within that pod VM. Unfortunately
those runtimes will get called by ocid with the same commands
(create and start) for both the pause containers and subsequent
containers to be added to the pod namespace. Unless they work around
that by e.g. infering that a container which rootfs is under
"/pause" would represent a pod, they have no way to decide if they
need to create/start a VM or if they need to add a container to an
already running VM pod.
This patch tries to formalize this difference through pod
annotations. When starting a container or a sandbox, we now add 2
annotations for the container type (Infrastructure or not) and the
sandbox name. This will allow VM based container …
> server: Export more container metadata for VM containers

- cmd/kpod/README.md
We have gotten feedback from discussions with kubernetes developers that we need a utility to debug pods and images when the daemons are wedged. This PR proposes kpod to fulfill the role.
> Add README for kpod

- .gitignore
- Makefile
- cmd/kpod/launch.go
- cmd/kpod/main.go
Add a basic framework for kpod, a debugging tool for Kubernetes and cri-o. The goals of kpod are described in the recently-merged readme (#220). Actual code will follow, as there's a bit of refactoring needed to allow code to be used by both the cri-o server and kpod.
> Add basic skeleton of kpod executable

- Dockerfile
- Makefile
- README.md
- cmd/server/config.go
- cmd/server/main.go
- docs/ocid.8.md
- docs/ocid.conf.5.md
- server/apparmor/aaparser.go
- server/apparmor/apparmor.go
- server/apparmor/apparmor_unsupported.go
- server/apparmor/template.go
- server/config.go
- server/container_create.go
- server/server.go
- server/utils.go
- test/apparmor.bats
- test/helpers.bash
- test/seccomp.bats
- test/testdata/apparmor_test_deny_write
- vendor/src/github.com/docker/docker/utils/templates/templates.go
- vendor/src/github.com/opencontainers/runc/libcontainer/apparmor/apparmor.go
- vendor/src/github.com/opencontainers/runc/libcontainer/apparmor/apparmor_disabled.go
close #201
cc @feiskyer @mrunalp @runcom 
Signed-off-by: Xianglin Gao <xlgao@zju.edu.cn>
> support apparmor

- server/sandbox.go
- server/sandbox_remove.go
And in particular make it not fail when removing an already removed
sandbox pod. According to the CRI spec:
[RemovePodSandbox] is idempotent, and must not return an error if
the sandbox has already been removed.
We now only print a warning instead of returning an error.
Fixes #240
> Make RemovePodSandbox idempotent

- test/testdata/sandbox_config.json
- test/testdata/sandbox_config_seccomp.json
And not directly under linux.
Fixes #243
> testdata: sandbox ns options should be under security_context

- test/testdata/sandbox_config.json
The json doc referenced by the README was missing a closed curly.
> testdata: fix invalid json doc

- test/pod.bats
- test/testdata/sandbox_config.json
Test if we can remove a pod several times without
generating an error.
> test: Add a pod remove idempotent test

- server/server.go
These debug calls were sometime wrong (formatting `id` where it was clearly `""`) or not really good at all. Fixing this. (I'm running into an issue with k8s integration also)
@mrunalp PTAL
> server: fix calls to logrus again

- cmd/client/container.go
- oci/oci.go
- server/container_create.go
- server/container_list.go
- server/sandbox_run.go
- server/server.go
First of all - thanks to @jjlakis for the patience he went through this issue with me on Slack. All credits for this PR goes to him.
Long story: while testing k8s integration (with #189), pods with `RestartPolicy: Always` failed to run and were always restarted by the kubelet, eventually failing with a conflict about containers names.
This patch makes sure we return annotations and image in contaienrs listing so that the kubelet isn't fooled by the container computed hash used to check if a container has changed (and other stuff). Basically the kubelet didn't understand if a container was already running by looking at the containers list and kept re-running the container (note, this wasn't happening with `--restart=Never`).
/cc @mrunalp @jjlakis  
Signed-off-by: Antonio Murdaca …
> store annotations and image for a container

- oci/oci.go
- server/container_create.go
- server/sandbox.go
- server/sandbox_remove.go
- server/sandbox_run.go
- server/sandbox_stop.go
- server/server.go
- vendor/src/github.com/containernetworking/cni/pkg/ns/README.md
- vendor/src/github.com/containernetworking/cni/pkg/ns/ns.go
This pull request adds networking support for hypervisor based OCI compatible container runtimes.
This has been tested with Clear Containers, and together with the [cri-o](https://github.com/01org/cc-oci-runtime/tree/sameo/topic/cri-o) branch this PR allows us to fully run CRI-O with KVM based containers.
Hypervisor based container runtimes prepare their virtual machine (kernel arguments, QEMU process, monitoring process) for a pod when receiving the sandbox container creation command.
Part of the VM preparation typically involves bridging the networking namespace existing interfaces with hypervisor supported interfaces (e.g. TAP). There typically is one bridge per networking namespace veth pair where the QEMU TAP interface and the veth peer are bridged together.
This means we need to the …
> Enable networking for hypervisor based container runtimes

- oci/oci.go
- server/server.go
- utils/utils.go
This is likely fixing tests and `wait: no child processes` error when running `cri-o`.
Fix https://github.com/kubernetes-incubator/cri-o/issues/268
@mrunalp @jjlakis @feiskyer @Crazykev please test this out (as I cannot reproduce `ECHILD` error anymore with this patch) 
runc does already take care of reaping childs (as I read the code) - I believe we're late here in to reap and killing/stopping/removing/state causes ECHILD so frequently when ops are really fast.
> server: remove reaper, let runc take care of reaping

- OWNERS
@kubernetes-incubator/maintainers-cri-o PTAL
@sameo has been helping a lot on the networking side of `cri-o` and we can now fully run cri-o fully backed by CNI. Would be great to have him on board.
> OWNERS: add @sameo

- server/container_updateruntimeconfig.go
k8s's e2e node tests does a call to updateruntimeconfig to set the network CIDR - unfortunately playing with CNI conf file to update `IPAM.Subnet` is infeasible and awful to me (maybe we should try to find a way to `SetCIDR` for a network in CNI (or `ocicni`) /cc @sameo). So, I just mocked the call so that cri-o doesn't crash when returning `nil` to the grpc API.
@mrunalp PTAL (@sameo PTAL at the network stuff)
> server: mock UpdateRuntimeConfig

- server/container_create.go
- server/sandbox.go
- server/sandbox_run.go
This PR makes cri-o support pod level qos model introduced recently by kubernetes.
This feature is required by new resource qos tiers model, and VM based containers like runv and cc can also read pod level qos value to decide the resource boundary for the sandbox.
NOTE: systemd cgroup support is discussed in #270.
Signed-off-by: Harry Zhang <harryz@hyper.sh>
> Support pod level qos in cri-o

- cmd/client/image.go
The client size field that we get back when we inspect an image is a pointer to a number, not just a number, so we need to dereference it for display.
> Fix client size reporting

- cmd/server/config.go
- cmd/server/main.go
- docs/ocid.8.md
- docs/ocid.conf.5.md
- server/config.go
- server/server.go
- test/helpers.bash
- test/network.bats
This PR includes 2 changes:
1. Add `--cni-config-dir` and `--config-plugin-dir` options to ocid, in order to specify where the CNI configuration and plugin binaries live. This is needed so that we can run BATs with temporarily created CNI configuration files.
2. Add 2 initial networking BATs where we test that the netns interface is using a valid CIDR and can be pinged from the host netns.
Next step is to add host networking tests, so that we can close #266.
> Add Initial networking BATs

- test/helpers.bash
- test/network.bats
- test/testdata/sandbox_config_hostnet.json
This PR introduces 2 new networking BATs:
- Inter pod networking check: We create 2 separate pods in 2 permanent networking namespaces and try to have them ping each others.
- Basic host networking check: This is a marginal use case, but we create a pod on the host netns and try to ping it from the host as well. This checks that host pods gets their networking interface up and running at least.
> Additional networking tests

- oci/oci.go
In later versions of runC, `runc kill` *requires* the signal parameter
to know what signal needs to be sent.
Signed-off-by: Aleksa Sarai <asarai@suse.com>
> oci: fix runc kill usage

- cmd/server/main.go
- hack/vendor.sh
- vendor/src/github.com/urfave/cli/.travis.yml
- vendor/src/github.com/urfave/cli/CHANGELOG.md
- vendor/src/github.com/urfave/cli/README.md
- vendor/src/github.com/urfave/cli/app.go
- vendor/src/github.com/urfave/cli/appveyor.yml
- vendor/src/github.com/urfave/cli/cli.go
- vendor/src/github.com/urfave/cli/command.go
- vendor/src/github.com/urfave/cli/context.go
- vendor/src/github.com/urfave/cli/errors.go
- vendor/src/github.com/urfave/cli/flag-types.json
- vendor/src/github.com/urfave/cli/flag.go
- vendor/src/github.com/urfave/cli/flag_generated.go
- vendor/src/github.com/urfave/cli/generate-flag-types
- vendor/src/github.com/urfave/cli/help.go
- vendor/src/github.com/urfave/cli/runtests
Remove `byName` in cmd/server/main.go, since [urfave/cli#544 ](https://github.com/urfave/cli/pull/544) has been in.
cc @runcom since you wrote this comment.
```
// remove once https://github.com/urfave/cli/pull/544 lands
```
Signed-off-by: Xianglin Gao <xlgao@zju.edu.cn>
> Remove byName in cmd/server/main.go, since urfave/cli#544 has been in.

- conmon/conmon.c
- oci/oci.go
- test/ctr.bats
- utils/utils.go
Some OCI container runtimes (in particular the hypervisor based ones like e.g. Clear Containers) will typically create a shim process between the hypervisor and the runtime caller, in order to not rely on the hypervisor process for e.g. forwarding the output streams or getting a command exit code.
When executing a command inside a running container those runtimes will create that shim process and terminate.
Therefore calling and monitoring the runtime process directly from ExecSync() will fail. Instead we need to have a subreaper calling the runtime and monitoring the shim process, and conmon seems to be a natural place for doing so.
This PR does mostly 2 things:
1) Add a `-e` option to `conmon` to also monitor potential shim processes created by `<runtime> exec`
2) Modify `ExecSync` to …
> Fix ExecSync support for runtimes other than runC

- Makefile
{1,5,8} not being parsed correctly when running sudo make install on Ubuntu..
So just splitting it out.
> fixes issue with make install on ubuntu

- cmd/server/config.go
- cmd/server/main.go
- server/config.go
The default configuration can only be accessed from the cmd/server
package, which cannot be imported (since it's a "package main").
This change promotes DefaultConfig() to the "server" package.
Closes: #315
> Promote DefaultConfig() to server package

- test/helpers.bash
- test/network.bats
#316 broke the tests. This fixes it.
We don't need to test host ping as the container isn't assigned an IP Address in that scenario.
@sameo @runcom PTAL
> Remove host ping test

- Makefile
In multiple places, we've been assuming that we can invoke binaries that we install as $GOPATH/bin/$binary.  This doesn't work in cases where $GOPATH is a list.
> Makefile: handle cases where $GOPATH is a list

- .gitignore
- Dockerfile
- Makefile
- test/apparmor.bats
- test/checkseccomp/Makefile
- test/checkseccomp/checkseccomp.go
- test/ctr.bats
- test/helpers.bash
- test/network.bats
- test/pod.bats
- test/restore.bats
- test/seccomp.bats
Trying to tackle performance issues as found in #324 
Also, fixing a bunch of stuff to enable network and seccomp tests in container (otherwise disabled...).
I can run `make integration` in about ~7/8min with this branch.
TODO:
> fix integration tests in docker

- server/server.go
Previously ocicni did not have support for setting the plugin directory.
Now that it has grown support for it, use it to actually respect the
setting a user has provided for ocid.network.* options.
Part of the whole CNI networking information cleanup.
> server: respect ocid.network.plugin_dir setting

- test/testdata/container_config.json
- test/testdata/sandbox_config_seccomp.json
We usually specify MCS Labels as comma separated pair.
Finally if we run two different containers we want them on different
MCS labels.
> Default type for containers is not container_t

- test/helpers.bash
When calling copyimg to pull down an image in the integration tests, don't forget to pass in the test signature policy.  I can't really explain why we didn't hit failures due to this omission earlier.
> Pass --signature-policy to copyimg during integration tests

- Makefile
- hack/libdm_tag.sh
- test/bin2img/Makefile
- test/copyimg/Makefile
Use the same build tags for bin2img and copyimg that we use for ocid, and improve detection of the case where we need to use the "libdm_no_deferred_remove" tag.
> Use build tags for bin2img and copyimg

- pkg/storage/runtime.go
- server/container_create.go
- test/helpers.bash
- test/image.bats
- test/testdata/container_config_by_imageid.json
kubelet sends a request to create a container with an image ID (as
opposed as an image name). That ID comes from the ImageStatus response.
This patch fixes that by setting the image ID as well as the image name
and fix the logic to lookup for image ID as well.
Found while running `make test-e2e-node`.
@nalind PTAL, the logic is tricky in that piece of code since it's full of if/else. Hope I got it correctly though, we can refactor that code soon(ish).
@mrunalp PTAL
> storage: fix image retrieval by id

- test/helpers.bash
This PR makes a couple of changes to the test helpers:
* when restarting ocid as part of a test, we wait for the ocid process to finish exiting before starting a new copy
* when generating the test configuration file, try to avoid inadvertently picking up settings from an installed ocid.conf file
> Minor tweaks to test helpers

- pkg/storage/runtime.go
When looking for the image to use for creating a container, there's no need to attempt parsing the ID a second time, and doing so can create confusing error messages.  This should fix #361.
> Don't try to parse an image ID a second time

- .gitignore
- Makefile
- test/helpers.bash
go install acts incredibly weirdly and rarely does what you want, not to
mention that it's just bad for distribution build setups. Switch back to
go build, which works properly and doesn't have half as many issues.
Fixes: 6c9628cdb11e ("Build and install from GOPATH")
> make: revert switch to 'go install'

- server/sandbox_run.go
- server/seccomp/seccomp.go
- server/seccomp/seccomp_unsupported.go
- server/server.go
This fixes issues running without seccomp compiled in and issues running with seccomp disabled. Before this change, the demo pod in sandbox_config fails to start with runc returning the following error:
`seccomp: config provided but seccomp not supported`
> Run without seccomp

- server/container_list.go
- server/sandbox_list.go
This change fixes some apimachinery imports so they are pulled from their canonical path rather than from the kubernetes staging location. This mismatch prevents removing the vendor directory and building with the version of kubernetes in my GOPATH. The go tools should be enforcing this but they are not due to a bug: golang/go#19224
cc @mzylowski
> Use canonical import path for apimachinery

- cmd/ocid/main.go
- docs/ocid.8.md
- test/bin2img/bin2img.go
- test/copyimg/copyimg.go
container-storage-setup (Formerly docker-storage-setup) is being converted to
run with container runtimes outside of docker.  Specifically we want to use it
with CRI-O/ocid.  It does not know anything about the container runtimes it
is generating options for, so it generates them based on the storage CLI of
docker.  I see no reason to have the storage option for ocid to be different
and we can just depracate the option for now.
> Depracate --storage-option for --storage-opt

- server/sandbox_run.go
We were using a variable before it was set.
> Fix cgroup parent

- cmd/ocid/config.go
- oci/oci.go
- server/config.go
- server/container_create.go
- server/sandbox.go
- server/sandbox_run.go
- server/server.go
Some CRI-O runtimes (like [cc-oci-runtime](https://github.com/01org/cc-oci-runtime)) do not support many host privileged operations like e.g. giving access to the host namespaces or running fully privileged containers (with access to *all* host devices). Those runtimes usually provide a higher level of container security by e.g. running container workloads within virtual machines and therefore running host privileged containers with them makes little sense.
This pull request tries to overcome that problem by allowing `ocid` users to define a *host privileged capable runtime path* in addition to the default runtime path. When `ocid` gets a request for creating a container or a sandbox with either the privileged flag set or access to at least one of the host namespaces (PID, IPC or …
> Support alternate runtime for host privileged operations

- .tool/lint
- server/sandbox_run.go
- utils/utils.go
The pause container is creating an AVC since the /dev/null device
is not labeled correctly.  Looks like we are only setting the label of
the process not the label of the content inside of the container.
This change will label content in the pause container correctly and
eliminate the AVC.
> Set SELinux mount label for pod sandbox

- README.md
- contrib/cni/10-ocid-bridge.conf
- contrib/cni/99-loopback.conf
- contrib/cni/README.md
This also updates the readme to no longer contain CNI configuration
information (which had incorrect steps), and rather just points to the
example configs.
Closes #208
Signed-off-by: Aleksa Sarai <asarai@suse.com>
> contrib: cni: provide example CNI configurations

- server/container_create.go
- server/container_status.go
While testing CRI-O with a kubeadm deployed k8s 1.6 cluster, we found a couple of issues:
- The container status response was missing the image name and ID entries
- The OCI container process arguments were incorrectly built.
With this PR we can run k8s 1.6 on top of CRI-O.
> Fixes for kubelet 1.6 and kubeadm 1.7

- server/container_remove.go
- server/sandbox_remove.go
When starting pods or containers, we create the mount points
first. It seems natural to do something symetrical when stopping
pods or containers, i.e. removing the mount point at last.
Also, the current logic may not work with VM based containers as the
hypervisor may hold a reference on the mount point while we're trying to
remove them.
> server: Remove the mount points after stopping the containers

- server/container_create.go
- server/sandbox.go
- server/sandbox_run.go
- server/server.go
When pod sandboxes come with DNS settings, we build and bind mount a `resolv.conf` file into the pod sandbox rootfs.
In order for pod internal DNS to work, we have to propagate that mount point to all pod containers.
Fixes #402
> Propagate the sandbox DNS mount point to pod containers

- pkg/storage/image.go
When we pull an image, preserve the tag portion of the name that we were asked to use for pulling it, instead of unconditionally replacing it with "latest".  This aims to fix #403.
> Preserve the tag of the pulled image's name

- OWNERS
- docs/ocid.8.md
- docs/ocid.conf.5.md
- server/config.go
- test/testdata/README.md
containers/storage is defaulting to /var/lib/containers/storage
for image and containers storage.  It is also defaulting to
/var/run/containers/storage for all runtime.  The defaults
for CRI-O should match so that lots of other tools that use
containers/storage can share the same storage.
> Default all container storage to /var/lib/containers/storage

- tutorial.md
`tutorial.md` was missing instructions to generate config for the first time install.
> Add instructions to generate config

- server/container_create.go
Fixes #413 
@runcom @sameo PTAL
I have followed the same logic as kubelet. 
You can test this with k8s using 
```
cluster/kubectl.sh run httpd --image=httpd:2.4-alpine
```
Additional groups will now be set correctly in runc config.json and for the container process.
> User lookup

- docs/ocid.8.md
- docs/ocid.conf.5.md
- kubernetes.md
- server/config.go
- tutorial.md
After change in `Makefile` at #304 where `PREFIX` has changed from `/usr` to `/usr/local` these changes has to be reflected in default `conmonPath`.
> Update the default conmonPath

- server/container_create.go
runc/runtime-spec doesn't allow empty working dir
> Set default working directory to /

- server/container_status.go
Found this one while testing kubectl logs with #162 
> Add labels/annotations to container status

- .gitignore
- .tool/lint
- Dockerfile
- conmon/cmsg.c
- conmon/cmsg.h
- conmon/conmon.c
- oci/oci.go
- server/config.go
- server/container_create.go
- server/sandbox.go
- server/sandbox_run.go
- server/server.go
- test/ctr.bats
- test/helpers.bash
- test/runtimeversion.bats
- test/testdata/container_config.json
- test/testdata/container_config_by_imageid.json
- test/testdata/container_config_logging.json
- test/testdata/container_exit_test.json
- test/testdata/container_redis.json
- test/testdata/sandbox_config.json
- test/testdata/sandbox_config_hostnet.json
- test/testdata/sandbox_config_seccomp.json
This adds a very simple implementation of logging within conmon, where
every buffer read from the masterfd of the container is also written to
the log file (with errors during writing to the log file ignored). It also
includes changes to how we compute the logPath for a container.
The WIP part of this PR is that conmon currently doesn't really handle
containers where `terminal: false`. This is going to be not-very-nice to
fix because the current runC API is broken (which is why we need to
make sure that the current state of opencontainers/runtime-spec#513
is **fixed**). However, while that's being sorted (and I work on the
relevant console changes in runC) we can solve it with a `fork+execve`
though no doubt there will be some fun issues with the exit code.
Closes #24.
Signed-off-by: …
> conmon: implement logging

- server/container_create.go
- server/sandbox_run.go
- server/server.go
Interleaving asynchronous updates with pod or container creations can
lead to unrecoverable races and corruptions of the pod or container hash
tables.
This is fixed by serializing update against pod or container creation
operations, while pod and container creation operations can run in parallel.
Fixes #407 
> Serialize Update and Sandbox/Container creation operations

- Dockerfile
- tutorial.md
As of containernetworking/cni commit 1b9caefba5670c59e0ccbf0b008d88da52a7d498,
the script to build has changed from `build` to `build.sh` which broke our
integration tests. Update path to fix them.
> Change path of CNI build script

- server/container_exec.go
This patch prevents k8s's e2e_node tests from killing CRI-O (because of
a panic in marshaling nil responses). This will ensure tests keep
running and just logging the failure.
> server: mock ExecResponse

- server/sandbox_run.go
When RunPodSandbox fails after calling s.addSandbox(sb),
we're left with a sandbox in s.state.sandboxes although the
sandbox is not created.
We fix that by adding removeSandbox() to the deferred cleanup
call
> server: Fix RunPodSandbox error path

- oci/oci.go
Earlier the received container pid was printed as unicode character, this is fixed to print integer.
Fixes #431
> Print received container pid as int

- server/image_pull.go
Fix the following upstream k8s's e2e-node test:
```
should be able to pull from private registry with secret [Conformance]
```
> server: add auth info to image pull

- conmon/conmon.c
- oci/oci.go
- test/seccomp.bats
The CRI requires us to prepend (timestamp, stream) to every line of the
output, and it's quite likely (especially in the !terminal case) that we
will read more than one line of output in the read loop.
So, we need to write out each line separately with the prepended
timestamps. Doing this the simple way (the final part of the buffer is
written partially if it doesn't end in a newline) makes the code much
simpler, with the downside that if we ever switch to multiple streams
for output we'll have to rewrite parts of this.
Alternative to #430.
Fixes: 1dc4c87c93cd ("conmon: add timestamps to logs")
> conmon: handle multi-line logging

- conmon/Makefile
- conmon/conmon.c
- oci/oci.go
- pause/Makefile
- test/ctr.bats
- test/testdata/container_config_logging.json
While it's not currently possible to do this for terminal=true
containers, for !terminal containers we can create separate pipes for
stdout and stderr, and then log them separately. This is required for
k8s's conformance tests.
Now that conmon splits std{out,err} for !terminal containers, ExecSync
can parse that output to return the correct std{out,err} split to the
kubelet. Invalid log lines are ignored but complained about.
Implements #444
> conmon: split std{out,err} pipe for !terminal containers

- pkg/storage/runtime.go
`image` as a variable/field name becomes too redundant and difficult to
grep for. Switching to `imageServer` makes for more readable code.
> pkg/storage: switch to searchable fieldname

- .gitignore
- Makefile
- hack/find-godeps.sh
- test/bin2img/Makefile
- test/checkseccomp/Makefile
- test/copyimg/Makefile
Instead of requiring the developer to set up their own GOPATH somewhere,
do like Kubernetes and OpenShift Origin do:
git clone xxxxx
cd xxxxx
make
by creating an _output/ directory and linking the local source tree
into it, and setting that to be the GOPATH.
@rajatchopra
> build: create a local GOPATH if none specified

- oci/container.go
- oci/memory_store.go
- oci/oci.go
- oci/store.go
- server/sandbox.go
- server/server.go
`git grep -wi store` is not nearly useful enough. Taking steps for
readability.
> oci: more grep'able interface name

- Makefile
- contrib/systemd/ocid-shutdown.service
- server/sandbox_remove.go
- server/server.go
Need to cleanup all pods on service poweroff
When powering off the system, we want the ocid service, to shutdown
all containers running on the system so they can cleanup properly
This patch will cleanup all pods on poweroff.
> Need to cleanup all pods on system shutdown poweroff

- test/helpers.bash
@sameo @mrunalp fix tests on RHEL where `ip` prints garbage on stderr
> test: fix bats dealing with std* streams

- test/helpers.bash
Needed for cases where we need to force a certain driver, like
```
STORAGE_OPTS="--storage-driver=overlay2 --storage-opt overlay2.override_kernel_check=1" make localintegration
```
> test: make storage configurable via env

- conmon/conmon.c
We reversed the logic inadvertently while getting in the logging changes.
> conmon: Fix logic for enabling systemd cgroups

- cmd/ocid/main.go
- docs/ocid.8.md
To collect CPU profile information added a flag `--cpu-profile` which is a path to file where this collected information will be dumped.
~~This flag is valid only in debug mode or when `--debug` flag is applied.~~
Fixes #464
> Add flag --cpu-profile to enable pprof

- server/container_portforward.go
Reusing k8s existing implementation. This could be re-written
to do port-forwarding natively rather than relying on socat/nsenter.
> Add support for port forwarding

- server/container_create.go
- test/helpers.bash
- test/testdata/container_config.json
- test/testdata/container_config_by_imageid.json
- test/testdata/container_config_logging.json
- test/testdata/container_config_seccomp.json
- test/testdata/container_exit_test.json
- test/testdata/container_redis.json
Found while integrating CRI-O with OpenShift Origin:
```
Events:
FirstSeen     LastSeen        Count   From                            SubObjectPath         Type             Reason          Message
---------     --------        -----   ----                            -------------         -------- ------          -------
3s            3s              1       default-scheduler                                     Normal           Scheduled       Successfully assigned nginx10-1-deploy to 192.168.122.186
3s            2s              2       kubelet, 192.168.122.186        spec.containers{deployment}    Normal          Pulled          Container image "openshift/origin-deployer:d98ef74" already present on machine
3s            2s              2       kubelet, 192.168.122.186 …
```
> server: fix set caps on container create

- Makefile
In build environments such as koji, there is no access to download
and install go packages so we should look for go-md2man in system
path first.
> makefile: Look for go-md2man in system path first

- Dockerfile
- server/sandbox.go
- server/sandbox_run.go
- server/sandbox_status.go
- server/sandbox_stop.go
- test/helpers.bash
- test/network.bats
- test/plugin_test_args.bash
Two issues:
1) pod Namespace was always set to "", which prevents plugins from figuring out
what the actual pod is, and from getting more info about that pod from the
runtime via out-of-band mechanisms
2) the pod Name and ID arguments were switched, further preventing #1
@runcom @mrunalp
> sandbox: pass correct pod Namespace/Name to network plugins and fix id/name ordering

- server/container_create.go
For features parity with docker
@mrunalp @rhatdan @sameo PTAL
> server: add RO and masked paths on container creation

- README.md
- contrib/test/crio-integration-playbook.yaml
Rationale: put this into `contrib/test` so that users like the Red Hat CI infra can grab it and test PRs and master branch w/o bothering about keeping in-sync the way we build and test CRI-O.
@mrunalp PTAL
> contrib: test: add jenkins playbook

- contrib/test/crio-integration-playbook.yaml
Update playbook so simply changing xunit to true will function properly.
Currently, if xunit is set to true, it will behave weirdly because the make localintegration command is redirected to the testout file and with xunit turned on, the output will automatically go to bats files.
Signed-off-by: Johnny Bieren <jbieren@redhat.com>
> Update integration playbook to fix xunit compatibility

- server/sandbox_run.go
Fixes #461 
Close #513 
k8s has it's own format for specifying cgroups. We
need to convert it to what runc understands when the
cgroup manager is systemd.
The function here is slightly modified version of
what is in k8s.
> Convert cgroup format to what runc expects

- cmd/crioctl/container.go
- conmon/conmon.c
- oci/container.go
- oci/oci.go
- server/container_status.go
- test/ctr.bats
- test/helpers.bash
Fixes #515
This adds event notification for OOM for the container process. We set it up as described here https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt and add the eventfd to the epoll loop.
When the event is received, we touch a file called oom and then use that to populate the status in ContainerStatus CRI API.
> OOM handling

- .gitignore
- test/helpers.bash
@mrunalp PTAL some of our tests are failing with network timeouts (on slow networks) since we pull redis:alpine by digest in each test (slowing tests time down also)
> fixes for tests and cleanup

- server/container_portforward.go
- server/server.go
During "Port forwarding" e2e tests, the following panic happened:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x64981d]
goroutine 52788 [running]:
panic(0x1830ee0, 0xc4200100c0)
/usr/lib/golang/src/runtime/panic.go:500 +0x1a1
github.com/kubernetes-incubator/cri-o/oci.(*Runtime).UpdateStatus(0xc4202afc00,
0x0, 0x0, 0x0)
/home/amurdaca/go/src/github.com/kubernetes-incubator/cri-o/oci/oci.go:549
+0x7d
github.com/kubernetes-incubator/cri-o/server.streamService.PortForward(0xc42026e000,
0x0, 0x0, 0x0, 0x0, 0xc420d9af40, 0x40, 0xc400000050, 0x7fe660659a28,
0xc4201cd0e0, ...)
```
The issue is `streamService.PortForward` assumed the first argument to
be the sandbox's infra container ID, thus trying to get …
> [e2e fix] server: fix PortForward panic

- server/container.go
- server/container_status.go
- test/ctr.bats
This patch fixes all port forwarding e2e tests. Those tests were
specifically looking for a termination reason to say that a given
container has finished running. CRI-O wasn't actually returning any
reason field for an exited container.
-> https://github.com/kubernetes/kubernetes/blob/master/test/e2e/portforward.go#L116
-> https://github.com/kubernetes/kubernetes/blob/master/test/utils/conditions.go#L97
> [e2e fix] server: correctly fill ctr termination reason

- server/container_create.go
node-e2e tests were failing in RHEL because, if running a privileged
container, we get all capability in the spec. The spec generator wasn't
filtering caps based on actual host caps, it was just adding _everything_.
This patch makes spec generator host specific.
> server: container_create: make the spec hostspecific

- server/container_create.go
Privileged containers should see and reach all host paths.
> container: Do not restrict path access for privileged containers

- pkg/annotations/annotations.go
- server/container.go
- server/container_create.go
- server/sandbox_run.go
- server/server.go
Some runtimes like Clear Containers need to interpret the CRI-O
annotations, to distinguish the infra container from the regular one.
Here we export those annotations and use a more standard dotted
namespace for them.
> pkg/annotations: Export CRI-O annotations namespace

- conmon/conmon.c
conmon.c fails to build on Ubuntu:
cc -std=c99 -Os -Wall -Wextra -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -c -o conmon.o conmon.c
In file included from /usr/include/fcntl.h:289:0,
from conmon.c:4:
In function ‘open’,
inlined from ‘main’ at conmon.c:519:10:
/usr/include/x86_64-linux-gnu/bits/fcntl2.h:50:4: error: call to ‘__open_missing_mode’ declared with attribute error: open with O_CREAT or O_TMPFILE in second argument needs 3 arguments
__open_missing_mode ();
^
<builtin>: recipe for target 'conmon.o' failed
make[1]: *** [conmon.o] Error 1
> conmon: Fix Ubuntu build failure

- contrib/test/crio-integration-playbook.yaml
```
should function for intra-pod communication: http
should function for intra-pod communication: udp
```
> contrib: test: fix failing networking tests in RHEL

- server/container_create.go
It should always be captitalized.
> Need to be consistent in out nameing of OCI

- server/container_create.go
- test/ctr.bats
This patch fixes the following command:
kubectl run -i --tty centos --image=centos -- sh
The command above use to fail with:
/usr/bin/sh: /usr/bin/sh: cannot execute binary file
That's because we were wrongly assembling the OCI processArgs.
Thanks @alexlarsson for spotting this.
This patch basically replicates what docker does when merging container
config and image config. It also replicates how docker sets processArgs
for the OCI runtime.
> container_create: fix OCI processArgs assemblement

- pkg/ocicni/ocicni.go
By only handling create events, we are breaking plugins that don't
create and write atomically, like weave for example.
The Weave plugin creates the file first and later writes to it. We are
missing the second part and never see the final CNI config file.
> ocicni: Handle create and write events

- server/sandbox_run.go
- server/sandbox_status.go
This was cluttering the logs on my clusters. The log should be just in
debug mode as we do for every request/response flow.
> sandbox_status: Infof->Debugf response

- contrib/cni/README.md
The CNI plugins are now living in a repo of their own.
> contrib/cni: Fix README link

- cmd/crio/config.go
- cmd/crio/main.go
- server/config.go
- server/server.go
This makes the lack of an IPv4 address a warning instead of a failure. We run IPv6 only backend nodes. Kubernetes mostly works in this configuration. After #557, cri-o fails to start with  `Unable to select an IP.`
> server: add --bind-address flag

- .tool/lint
- oci/oci.go
This makes it easier to debug container creation failures
looking at cri-o logs.
> oci: Add debugs to print error message on create failure

- conmon/conmon.c
- oci/container.go
- oci/oci.go
- pkg/annotations/annotations.go
- server/container_attach.go
- server/container_create.go
- server/sandbox_run.go
- server/server.go
We use a SOCK_SEQPACKET socket for the attach unix domain socket, which
means the kernel will ensure that the reading side only ever get the
data from one write operation. We use this for frameing, where the
first byte is the pipe that the next bytes are for. We have to make sure
that all reads from the socket are using at least the same size of buffer
as the write side, because otherwise the extra data in the message
will be dropped.
This also adds a stdin pipe for the container, similar to the ones we
use for stdout/err, because we need a way for an attached client
to write to stdin, even if not using a tty.
This fixes #569
Note: This depends on #571 (and thus contains those commits), only the last commit is actually new. Once #571 is merged i'll update the PR with that.
> Implement non-terminal attach

- cmd/crio/config.go
- oci/container.go
- oci/oci.go
- pkg/annotations/annotations.go
- server/config.go
- server/container_create.go
- server/sandbox.go
- server/sandbox_run.go
- server/server.go
Container runtimes provide different levels of isolation, from kernel
namespaces to hardware virtualization. When starting a specific
container, one may want to decide which level of isolation to use
depending on how much we trust the container workload. Fully verified
and signed containers may not need the hardware isolation layer but e.g.
CI jobs pulling packages from many untrusted sources should probably not
run only on a kernel namespace isolation layer.
Here we allow CRI-O users to define a container runtime for trusted
containers and another one for untrusted containers, and also to define
a general, default trust level. This anticipates future kubelet
implementations that would be able to tag containers as trusted or
untrusted. When missing a kubelet hint, containers are trusted …
> oci: Support mixing trusted and untrusted workloads

- vendor.conf
Nothing changed in the vendor we're using :)
> vendor: update kube to v1.6.5

- server/sandbox_stop.go
We don't want to have lingering pods because of CNI failures.
> sandbox_remove: Do not error out when CNI tear down fails

- conmon/conmon.c
- test/ctr.bats
runc has ONCLR unset while kube doesn't have OPOST enabled
so we get our lines shifted without \r in a tty.
Also, we need to take out \r from a \r\n sequence before
writing to log file.
> conmon: Set ONLCR for console

- test/ctr.bats
- test/testdata/container_config_resolvconf.json
- test/testdata/container_config_resolvconf_ro.json
- test/testdata/sandbox_config.json
This patch isn't adding a test for /etc/hosts as that requires host
network and we don't want to play with host's /etc/hosts when running
make localintegration on our laptops. That may change in the future
moving to some sort of in-container testing.
smoke test for https://github.com/kubernetes-incubator/cri-o/pull/599
> test: add a test for /etc/resolv.conf in rw/ro mode

- server/container_remove.go
- server/container_stop.go
- server/sandbox.go
- server/sandbox_remove.go
- server/sandbox_stop.go
- test/ctr.bats
- test/helpers.bash
- test/pod.bats
- test/restore.bats
~~Easily reproducible by stopping a sandbox/container and notice you still have mounts in `mount` output.~~
@mrunalp @sameo @rhatdan PTAL
> server: adhere to CRI for sandbox stop/remove

- conmon/conmon.c
- oci/oci.go
- utils/utils.go
Currently, when creating containers we never call Wait on the
conmon exec.Command, which means that the child hangs around
forever as a zombie after it dies.
However, instead of doing this waitpid() in the parent we instead
do a double-fork in conmon, to daemonize it. That makes a lot of
sense, as conmon really is not tied to the launcher, but needs
to outlive it if e.g. the cri-o daemon restarts.
However, this makes even more obvious a race condition which we
already have. When crio-d puts the conmon pid in a cgroup there
is a race where conmon could already have spawned a child, and
it would then not be part of the cgroup. In order to fix this
we add another synchronization pipe to conmon, which we block
on before we create any children. The parent then makes sure the
pid is in the …
> conmon: Don't leave zombies and fix cgroup race

- server/container_create.go
- server/naming.go
- server/sandbox.go
- server/sandbox_run.go
- test/seccomp.bats
Fix https://github.com/kubernetes-incubator/cri-o/issues/617
This patch rewrites the way we generate container/pod names following what upstream kube does for the dockershim. Including the sandbox UID is also fixing potential naming collisions as we trust k8s.
@alexlarsson @mrunalp PTAL
> server: standardize on naming

- test/ctr.bats
This tests that our ONLCR takes effect as we match \r\n
in the logs
> test: Tighten the grep for logging with tty

- tutorial.md
The Kubernetes Container Runtime Interface document was moved to https://github.com/kubernetes/community/blob/master/contributors/design-proposals/container-runtime-interface-v1.md. Adjust the URL in tutorial.md accordingly.
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
> tutorial: fix Kubernetes CRI interface link

- test/ctr.bats
The test "ctr execsync std{out,err}" from ctr.bats works with runc,
but the semantics behind is wrong.
We should not be able to execute a new process on a container which
has not been previously started. That's why this patch adds a call
to start the container.
Moreover, we don't want to be able to execute a new process on a
container that has already returned because its workload is done.
For that reason, we need to force the container workload to be a
"sleep 10" to ensure it is still running when the call to "exec"
is issued.
> test: Make sure to have a running container before calling into "exec"

- contrib/systemd/crio.service
We don't want cri-o to be OOM killed easily.
> contrib: Set the OOM Score Adjust of cri-o service to be low

- cmd/crio/main.go
can't actually add a test for now as that would require a custom registry in our test infra.
> cmd/crio: fix reading insecure-registry flags

- server/sandbox_run.go
This matches the current kube behavior. This will probably
be provided over the CRI at which point we won't have to
define a constant in cri-o code.
> sandbox: Adjust OOM score of infra container to a low value

- utils/utils.go
Remove the Prctl wrapper function which has been unused since commit
d2f6a4c0e2ee. If a prctl wrapper would be needed in the future,
golang.org/x/sys provides unix.Prctl which could be used instead.
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
> utils: remove unused Prctl wrapper

- conmon/conmon.c
Instead of waiting until stderr/out is closed and then waiting for
the container to exit we wait for the container to exit in the
gmainloop, in addition to everything else, exiting only when
the child dies.
We then drain any output in stderr/out after the child has exited.
> conmon: Change how we detect container exit

- server/container_create.go
The default container config generated by runtime tools sets RLIMIT_NOFILE to 1024. This is too restrictive for many applications. Kubernetes doesn't support setting rlimits per container (see: kubernetes/kubernetes#3595). For now, we shouldn't set rlimits on the containers. This allows the administrator to configure the default rlimits using the normal config files. (This also matches the default behavior of docker.)
> server: containers inherit rlimits from server

- Makefile
Pulling latest code breaks our lint when unstable code is merged
into gometalinter.
> lint: Use a fixed commit for gometalinter

- Makefile
This patch causes the man pages to be created with the correct content.
> Man pages were being created empty

- cmd/kpod/version.go
even when the variables are not provided at compile, the `kpod version`
command ought not fail.
> kpod: version should not fail

- cmd/kpod/common.go
- cmd/kpod/common_test.go
- cmd/kpod/images.go
- cmd/kpod/images_test.go
- cmd/kpod/main.go
- cmd/kpod/rmi.go
- cmd/kpod/rmi_test.go
- completions/bash/kpod
- docs/kpod-images.1.md
- docs/kpod-rmi.1.md
- docs/kpod.1.md
'kpod images' lists all images on a system.  'kpod rmi' removes one or more images from a system.  The images will not be removed if they are associated with a running container, unless the -f option is used
> Add 'kpod images' and 'kpod rmi' commands

- cmd/crio/main.go
- oci/oci.go
- server/container_attach.go
- server/container_create.go
- server/sandbox_run.go
- server/seccomp/seccomp.go
- test/checkseccomp/checkseccomp.go
The syscall package is locked down and the comment in [1] advises to
switch code to use the corresponding package from golang.org/x/sys. Do
so and replace usage of package syscall where possible (leave
syscall.SysProcAttr as per the comment).
[1] https://github.com/golang/go/blob/master/src/syscall/syscall.go#L21-L24
This will also allow to get updates and fixes just by re-vendoring
golang.org/x/sys/unix instead of having to update to a new go version.
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
> all: Switch from package syscall to golang.org/x/sys/unix

- cmd/kpod/main.go
cmd/kpod/main.go had the apps.Flag repeated, probably something messed up during merge. This fixes that by deleting the repeated portion.
> Remove repeated app.Flags in cmd/kpod/main.go

- vendor.conf
- vendor/github.com/containers/image/MAINTAINERS
- vendor/github.com/containers/image/Makefile
- vendor/github.com/containers/image/README.md
- vendor/github.com/containers/image/doc.go
- vendor/github.com/containers/image/vendor.conf
Update the vendored commit for containers/image, because the previous version did not include the function ListNames() in transports.  This is needed for #636
> Update vendor for containers/image

- oci/container.go
- server/server.go
Once kpod is allowed to create and modify pods & containers, we will need to be able to lock shared state to prevent the two from trampling each other. This PR begins the process of allowing file-based locks to enable this.
> Replace sync.Mutex with sync.Locker to allow different locks

- oci/finished.go
- oci/finished_32.go
- oci/oci.go
Should fix #302 
@lsm5 @cyphar could you test this out in Fedora and Suse? Like using my cri-o remote github + this branch to test it out.
> oci: fix type mismatch on some platform/arch

- README.md
- docs/crio.8.md
- docs/crio.conf.5.md
- docs/kpod-images.1.md
- docs/kpod-pull.1.md
- docs/kpod-rmi.1.md
- docs/kpod-tag.1.md
- docs/kpod-version.1.md
- docs/kpod.1.md
This patch will allow people who go to the github page to easily read
man pages.
> Make the README.md more useful in links to man page documentation

- cmd/kpod/info.go
- cmd/kpod/main.go
- docs/kpod-info.1.md
- docs/kpod.1.md
Design: The output of the `info` subcommand ought to be directly
consumable in a format like JSON or yaml.
The structure being a map of sorts.
Each subsection of information being an individual cluster under the
top-level, like platform info, debug, storage, etc.
Even if there are errors under the top level key, the value will be a
map with the key of "error" and the value as the message of the
`err.Error()`. In this way, the command always returns usable output.
Ideally there will be a means for anything that can register info to do
so independently from it being in the single info.go, so this approach
is having a typed signature for the function that gives info, but i'm
sure it could be better.
Current iteration of this outputs the following as a limited user:
```yaml
host:
MemFree: …
```
> kpod: info subcommand

- oci/container.go
- server/container_create.go
- server/container_list.go
- server/container_status.go
- server/sandbox_run.go
- server/server.go
ImageSpec just contains a string, so replacing instances of ImageSpec with string in oci.Containter{} is a simple step towards removing kubernetes dependence in kpod
> Remove ImageSpec dependency from server

- libkpod/containerserver.go
- server/container.go
- server/container_attach.go
- server/container_create.go
- server/container_exec.go
- server/container_execsync.go
- server/container_list.go
- server/container_portforward.go
- server/container_remove.go
- server/container_start.go
- server/container_status.go
- server/container_stop.go
- server/image_list.go
- server/image_pull.go
- server/image_remove.go
- server/image_status.go
- server/runtime_status.go
- server/sandbox_list.go
- server/sandbox_remove.go
- server/sandbox_run.go
- server/sandbox_status.go
- server/sandbox_stop.go
- server/server.go
- server/version.go
Move non-kubernetes-dependent portions of server struct to libkpod.  So far, only the struct fields have been moved and not their dependent functions
> Decouple kubernetes-dependent and non-dependent parts of server

- Makefile
- contrib/rpm/crio.spec
Adding these aliases will make it easier for users who forget to
use crio or cri-o.
> We need to support the name cri-o and crio for rpm and systemd

- cmd/kpod/images.go
kpod images --digests output header not aligned
because there have **sha256:**  prefix at image's digest
Signed-off-by: CuiHaozhi <cuihz@wise2c.com>
> kpod images --digests output align

- hack/find-godeps.sh
go list {{.Imports}} outputs imports as an array, and the leading and trailing square brackets can get caught in the name of a package.  Added a pipe in the dependency command to remove the brackets
> Fix bug in find-godeps

- libkpod/containerserver.go
- server/container.go
- server/container_list.go
- server/server.go
Move container state data to libkpod, separate from the sandbox data in server. However, the move is structured such that sandbox data could easily be moved over into libkpod in the future
> move container state to libkpod

- Dockerfile
When the integration test image is run on a system with apparmor enabled, it needs binaries from the 'apparmor' package, so ensure that it's always there.
> Fix integration tests on systems with apparmor

- test/helpers.bash
Basically none of the clever storage drivers will work when we're on top of AUFS, so if we find ourselves in that situation when running tests, default to storage options of "--storage-driver vfs".
> Force use of the "vfs" driver when testing on AUFS

- Makefile
Build all of our binaries with the same build tags and the same LDFLAGS.  This means we add $(LDFLAGS) to bin2img, copyimg, and cri-o, $(BUILDTAGS) to kpod, and both to crioctl and checkseccomp.
> Build all of our binaries with the same build tags

- cmd/crioctl/container.go
base [pr-512](https://github.com/kubernetes-incubator/cri-o/pull/512), enable input timeout value from cmdline.
Signed-off-by: CuiHaozhi <cuihz@wise2c.com>
> crioctl ctr stop: enable timeout input

- Dockerfile
- Makefile
bin2img/checkseccomp/copyimg are file targets and should not be .PHONY.
This prevents to build them if not necessary.
> Makefile: do not rebuild tests every time "make" runs

- conmon/conmon.c
During my testing in OpenShift I've noticed that a zombie process is
left for each instance of runC being executed.  The reason is that we
are using PR_SET_CHILD_SUBREAPER in conmon and runC forks a new
process (runc init) each time we start a container.  Using
g_child_watch_add only on the main runc process and on the container
process is not enough as we do not cleanup any other zombie process.
Since glib doesn't allow to catch SIGCHLD and to better integrate in the
existing code, catch it with signal(2) then raise a SIGUSR1 that glib
handles.
> conmon: use waitpid to wait for terminated processes

- libkpod/containerserver.go
- server/container_create.go
- server/container_list.go
- server/naming.go
- server/sandbox_list.go
- server/sandbox_remove.go
- server/sandbox_run.go
- server/sandbox_stop.go
- server/server.go
This moves sandbox-related state from the server package into libkpod. It removes remaining server state locking as well.
> Move remaining server state to libkpod

- pkg/storage/image.go
`github.com/containers/image/image.FromUnparsedImage()` "takes ownership" of the `UnparsedImage` that we pass to it, so we shouldn't also `Close()` the `UnparsedImage` ourselves after we've wrapped it up in an `Image` object.
Since creating an `Image` is the only thing we do with the `UnparsedImage` after creating it from a `SourceImage`, just use the `FromSource()` function to handle both steps at once.
> Don't double-free an UnparsedSource

- vendor.conf
- vendor/github.com/containers/image/docker/archive/dest.go
This update allows the creation of docker-archive files when the
destination does not exists or is empty.  kpod save needs this functionality.
> vendor in Update containers/image to add support for kpod save

- cmd/crio/main.go
- cmd/kpod/common.go
- cmd/kpod/history.go
- cmd/kpod/images.go
- cmd/kpod/info.go
- cmd/kpod/inspect.go
- cmd/kpod/main.go
- cmd/kpod/pull.go
- cmd/kpod/push.go
- cmd/kpod/rmi.go
- cmd/kpod/tag.go
- libkpod/config.go
- libkpod/containerserver.go
- server/config.go
- server/container_create.go
- server/server.go
Add a basic config struct to libkpod so that it can be used in commands such as `kpod logs` and `kpod stats`.  This can be refined once kpod gets fleshed out more but it prevents having magic constants all over the place
> add basic config struct to libkpod

- README.md
- cmd/kpod/main.go
- cmd/kpod/save.go
- completions/bash/kpod
- docs/kpod-save.1.md
- test/kpod.bats
- test/kpod_save.bats
Add changes to kpod push to accommodate kpod save. Add changes to containers/image to save to an existing empty file when using stdout as it seems to create the file first before writing to it.
> Add 'kpod save' command

- cmd/kpod/save.go
The kpod save and libkpod config PRs were probably merged around the same time so this went unnoticed
> Switch kpod save to use config

- cmd/kpod/images.go
- libkpod/containerData.go
- libkpod/image/image.go
- libkpod/image/imageData.go
* We parse image data when checking if an image matches a label filter for `kpod images`, so extend that to read the image inspection data and OCI configuration blob.
* Use the creation date from an image's inspection data when the image is to be used as a reference date, and for display.
* Only show the image's OCI configuration in `kpod inspect`, since that's the only information `cri-o` will use when it attempts to run the image.  This discards the "parent" image's ID, so we drop that field, too.
> kpod: display image dates from inspection data, and don't display non-OCI settings in "inspect"

- cmd/crio/config.go
- cmd/crio/main.go
- libkpod/config.go
- libkpod/container_server.go
- server/server.go
This is the first step to allowing proper sharing of state between CRI-O and kpod. For now, only the state lock will be file-based.
> Add option to use file-based locking for CRI-O state

- docs/kpod-pull.1.md
- docs/kpod-push.1.md
Miloslav informs me that the docker transport talking to an OpenShift
registry will handle signatures properly, so no need for the atomic transport
any longer.  We want to stop documenting it.
> Remove atomic transport description.

- .travis.yml
- Dockerfile
Build glib in Travis, because ostree now requires a newer glib than we have in Trusty.
> Build a fixed version of ostree in Travis

- libkpod/container_server.go
- libkpod/image/copy_data.go
- pkg/storage/runtime.go
- server/image_status.go
- server/sandbox_remove.go
- server/sandbox_run.go
- server/sandbox_stop.go
- server/server.go
The storage library uses `github.com/pkg/errors` to wrap errors that it returns from many of its functions, so when passing them to `os.IsNotExist()` or comparing them to specific errors defined in the storage library, unwrap them using `errors.Cause()`.
> Use errors.Cause() when looking at storage errors

- OWNERS
@rhatdan has contributed a lot to cri-o and the projects/libraries that it depends on and spends a lot of time on the project.
> Add rhatdan as an OWNER

- cmd/kpod/push.go
- libkpod/common/common.go
- vendor/golang.org/x/crypto/ssh/terminal/terminal.go
- vendor/golang.org/x/crypto/ssh/terminal/util.go
- vendor/golang.org/x/crypto/ssh/terminal/util_bsd.go
- vendor/golang.org/x/crypto/ssh/terminal/util_linux.go
- vendor/golang.org/x/crypto/ssh/terminal/util_plan9.go
- vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
Previously, docker username and password had to be inputted through the terminal.  This allows the user to only give their username, then type their password at the prompt so that it is not displayed
> Allow password for docker registry to be inputted silently

- cmd/kpod/images.go
- libkpod/image/image.go
Previously, the creation time was set to the time the image was downloaded, but that was being compared to the time the image was built in matchesSinceImage() and matchesBeforeImage().  Updated the time to be the time that the image was built
> fix bug with creation time in ParseFilter()

- oci/finished.go
AND default conditions
should fix failure on arm and 386 I guess.
@rhatdan @lsm5 can you cherry-pick this patch to test it out before we merge?
> oci: fix build condition

- Makefile
This allows modifying the `BUILDTAGS` variable as documented in the README.
> build: Allow overwrite of BUILDTAGS variable

- conmon/conmon.c
The `g_get_temp_dir` function is more cross-platform than hardcoding the `/tmp` path, also it has the nice benefit of falling back to `/tmp` if it can't find the path in other ways like `TMPDIR` or the macro.
Also edited the number of Xs in the template since MKSTEMP(3) accepts six of them and not eight. If that was intended please let me know, or if it breaks anything.
> conmon: Using `g_get_tmp_dir` to build the console socket name

- .travis.yml
Some features cri-o is now using are not supported by golang 1.6.
All Distros that use CRI-O are now using golang 1.7 or better,
so no reason to test with this older version.
> Remove testing with 1.6.

- OWNERS
He is a key contributor to the CRI-O project, he has contributed a lot to cri-o
and the projects/libraries
He is an expert in containers/storage and really solid on containers/image
key components of the cri-o project.  We need to get his advise and appoval
on lots of pull requests interacting with the storage and image layers.
> I would like to add @nalind to the OWNERS of cri-o

- cmd/kpod/inspect.go
Without this, kpod can't find any containers to inspect
> have server update list of containers on creation

- tutorial.md
[runc 1.0 Release Candidate 4](https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc4)
update tutorials
Signed-off-by: CuiHaozhi <cuihz@wise2c.com>
> tutorial: need runc 1.0.0-rc4

- cmd/kpod/export.go
- cmd/kpod/main.go
- completions/bash/kpod
- docs/kpod-export.1.md
- test/kpod_export.bats
kpod export exports the container's filesystem to a tar archive
> Add 'kpod export' command

- cmd/kpod/formats/formats.go
- cmd/kpod/images.go
- completions/bash/kpod
- docs/kpod-images.1.md
- libkpod/common/output_interfaces.go
- test/kpod.bats
For kpod images, we need to output in JSON format so that consumers
(programatic) have structured input to work with.
> cmd/kpod/images.go: Add JSON output option

- cmd/crio/main.go
- conmon/conmon.c
- libkpod/config.go
- libkpod/container_server.go
- oci/oci.go
- server/container_list.go
- server/container_remove.go
- server/server.go
We add an inotify based container exit watch that can asynchronously update the status of the containers that have exited so we don't have to call runtime state on containers during container list which gets called frequently by the kubelet.
Replaces #747
> Inotify exit watch

- README.md
- cmd/kpod/common.go
- cmd/kpod/main.go
- completions/bash/kpod
- docs/kpod-info.1.md
- docs/kpod.1.md
Also set default level of logging to errors,  we should not see
info messages in the kpod command line.
While adding this patch, I found missing options in kpod command line
and bash completions, so I added them in.
> Add --debug flag to kpod to turn up logging level to debug

- code-of-conduct.md
In a previous review I noted a number of minor nits through out the document.  This change fixes that, mostly adding additional space, periods and a missing 'the'.
> Number of minor touch ups to Code of Conduct

- server/container_create.go
Containers running in kubernetes currently do not specify options
for mount propagation and whether to bind or rbind the mount point.
Since docker defaults to bind and rbind, we should match their
behavious, since this is what admins expect
> CRI-O default bind mounts to "rbind, rprivate" to match docker

- libkpod/container_server.go
- libkpod/sandbox/sandbox.go
- oci/container.go
- oci/oci.go
- pkg/annotations/annotations.go
- server/container_create.go
- server/container_remove.go
- server/container_status.go
- server/container_stop.go
- server/sandbox_list.go
- server/sandbox_remove.go
- server/sandbox_run.go
- server/sandbox_status.go
- server/sandbox_stop.go
- server/server.go
We calculate and store the container bind mounts, imageRef and imageName at container creation time so we can avoid the hit of calculation in container status API. Also, we take out the call to runtime status from container status API as the inotify watch should update the container status asynchronously already. We also remove a number of calls to UpdateStatus that aren't required in containers and sandboxes.
> Container status fixes

- cmd/kpod/common.go
- cmd/kpod/diff.go
- cmd/kpod/images.go
- cmd/kpod/inspect.go
- cmd/kpod/logs.go
- cmd/kpod/main.go
- cmd/kpod/rename.go
- cmd/kpod/stats.go
- libkpod/container_server.go
- test/kpod.bats
Before exiting, have kpod shut down the storage library if it can.  This should keep us from leaving mountpoints for the root (for non-vfs cases) and run directory (with newer containers/storage) busy when testing kpod.  We also correct some errors in the tests.
> kpod: shut down the storage library at exit

- utils/utils.go
This fixes the goroutine leak in cri-o.
> utils: Fix close conn after starting scope

- Makefile
`ln -s` errors out with `file exists` if you run `make install.systemd` twice or more. This patch installs the alias directly w/o using a symlink so it can be run multiple times w/o errors.
@rhatdan PTAL
> Makefile: install alias, not symlink

- README.md
Replaces https://github.com/kubernetes-incubator/cri-o/pull/797.
Touches up README.md with appropriate command
> Touchup apt to apt-get in README.md

- Makefile
> Makefile: force symlink to cri-o.service

- cmd/kpod/ps.go
- docs/kpod-images.1.md
Consumers of the json output, like the atomic cli, need the ID of the
image for the container as well as the name.  Specifically, it is used
to tract "used" and "vulnerable" images.
> Add image_id to json output

- cmd/crio/main.go
- cmd/crioctl/main.go
- oci/oci.go
- server/container_remove.go
- server/container_status.go
Found out that during OpenShift testing, node was trying to remove
containers (probably in a bad state) and was failing the removal with
this kind of error:
```
E0828 13:19:46.082710    1235 kuberuntime_gc.go:127] Failed to remove
container
"e907f0f46b969e0dc83ca82c03ae7dd072cfe4155341e4521223d9fe3dec5afb": rpc
error: code = 2 desc = failed to remove container exit file
e907f0f46b969e0dc83ca82c03ae7dd072cfe4155341e4521223d9fe3dec5afb: remove
/var/run/crio/exits/e907f0f46b969e0dc83ca82c03ae7dd072cfe4155341e4521223d9fe3dec5afb:
no such file or directory
```
I believe it's ok to ignore this error as it may happen conmon will
fail early before exit file is written.
> server: container_remove: ignore not existent exit file

- cmd/kpod/info.go
Have the "kpod info" command also package up the driver-level status information that the `github.com/containers/storage.Store`'s `Status()` method returns.
> kpod: add more storage information to "info"

- pkg/ocicni/ocicni.go
Needs testing.
Fixes #791 (or the part of it where a restart is needed after cni dir changes - will not be needed anymore)
@sameo @dcbw, PTAL
/cc @mrunalp 
Signed-off-by: Rajat Chopra <rchopra@redhat.com>
> monitor CNI networks continuously

- cmd/kpod/ps.go
The getCommand func strips out unwanted characters around the
command of the container.  The JSON output should use this func
like the regular ps output for both consistency and because
Python does a literal interpretation of the bracket [] characters
when consuming as JSON.
> cmd/kpod/ps.go: Use getCommand for JSON

- .travis.yml
Couple changes to streamline travis.
1) Kube has moved up to 1.8.3 so probably don't need 1.7 any more.
2) Added stages, to allow both 1.8.x and tip to be tested in parallel, and to test integration only against 1.8.x
Should cut the overall test time down considerably.
Cheers, Mike
> streamlining travis

- contrib/test/requirements.txt
- contrib/test/venv-ansible-playbook.sh
The environment executing the test playbooks matters.  Establish a
script to bootstrap a known-good and fixed-version python virtual
environment.  Spell out precise execution requirements in a standard
pip 'requirements.txt' file, including version numbers and hashes.
Upon executing the ``venv-ansible-playbook.sh`` wrapper, a virtual
environment is setup and contained within a fixed (or temporary)
directory, with full logs from setup.  If this is to be preserved
across executions, the ``$WORKSPACE`` environment variable must be
set and exported beforehand.
Example execution command-line provided in script file
Signed-off-by: Chris Evich <cevich@redhat.com>
> Add Ansible playbook env. setup wrapper script

- cmd/kpod/main.go
Some kpod commands were listed twice in main.go.  Removed these duplicates and alphabetized the remaining commands to prevent this from happening in the future
> Remove duplicate kpod command names

- test/kpod.bats
- vendor.conf
- vendor/github.com/containers/image/docker/docker_client.go
- vendor/github.com/containers/image/oci/archive/oci_dest.go
- vendor/github.com/containers/image/oci/archive/oci_src.go
- vendor/github.com/containers/image/oci/archive/oci_transport.go
- vendor/github.com/containers/image/oci/layout/oci_dest.go
- vendor/github.com/containers/image/oci/layout/oci_transport.go
- vendor/github.com/containers/image/transports/alltransports/alltransports.go
- vendor/github.com/containers/image/vendor.conf
This containers/image fixes the way the image name is saved for an oci image.
Also creates a new transport called oci-archive, which is the tarred version of oci.
> Vendor in changes made to containers/image for OCI

- cmd/crio/main.go
- server/inspect.go
- vendor.conf
- vendor/github.com/soheilhy/cmux/LICENSE
- vendor/github.com/soheilhy/cmux/README.md
- vendor/github.com/soheilhy/cmux/buffer.go
- vendor/github.com/soheilhy/cmux/cmux.go
- vendor/github.com/soheilhy/cmux/doc.go
- vendor/github.com/soheilhy/cmux/matchers.go
- vendor/github.com/soheilhy/cmux/patricia.go
it wasn't actually possible to serve grpc and http on the same socket. This patch modifies code to make it possible.
@mrunalp PTAL, needed by cadvisor handler
> serve grpc and http on the same socket

- cmd/crio/main.go
- cmd/kpod/common.go
- server/config.go
kpod must parse the crio configuration file or the storage
is not set up correctly.  By default it is not.  We now pass
/etc/crio/crio.conf in as the configuration file as part of the
command line parser.  This can of course be overriden by the user.
> Make kpod parse configuration file

- Makefile
This patch will check to see if SELinux is enabled and then pass
the -Z flag to the install command, which causes install to label
all created content with the system default labels.
> When installing content make sure it gets labeled correctly.

- contrib/test/crio-integration-playbook.yaml
Without any swap space enabled, it's possible some intensive operation
can chew up all the memory on the test VM.  Enabling swap space will
prevent this for minor cases, but could lead to disk-thrashing if the
memory demand is excessive.  Since the test system never reboots,
using a file-backed swap should suffice, though not ideal, it's easy to
setup.
Signed-off-by: Chris Evich <cevich@redhat.com>
> Add file-backed swap to prevent OOM

- libkpod/sandbox/sandbox.go
- server/container_create.go
- server/sandbox_run.go
Fixes #842
We ensure that cri-o cgroup manager is compatible with the cgroup parent sent by k8s and do the right conversions to pass the cgroups to runc.
> Fix cgroup config

- contrib/test/crio-integration-playbook.yaml
- test/ctr.bats
Our CI tests on RHEL and Fedora and we want to test the systemd cgroup
driver. However, kubelet needs to run in tests with systemd cgroup
driver as well, or tests fail. This patch fixes broken CI because of
not matching cgroup driver between CRI-O and the kubelet.
Close https://github.com/kubernetes-incubator/cri-o/pull/864
> contrib: test: run kube tests in CI with same cgroup driver

- cmd/kpod/ps.go
- docs/kpod-ps.1.md
QE noticed that kpod ps --last 0 was returning the running containers
Fixed that problem so that it returns nothing
> Slight modification to kpod ps based on QE feedback

- contrib/test/crio-integration-playbook.yaml
ref: https://github.com/kubernetes-incubator/cri-o/issues/533
> contrib: test: switch node-e2e to e2e

- cmd/kpod/tag.go
- test/tag.bats
When performing a tag, if a shortname was provided, tag.go would
preprend docker.io to the shortname through the ParseNormalized
function.  Here we work around that such that is a short name
and tag are provided, the resulting tag will be shortname:tag.  If
a shortname is provided without a tag, we append "latest" as the
tag.
Added specific tag tests too
> cmd/kpod/tag.go: Do not assume docker.io for tagging

- cmd/kpod/ps.go
- completions/bash/kpod
- docs/kpod-ps.1.md
- test/kpod_ps.bats
The verbose flag prints out information about the namespaces
From issue https://github.com/kubernetes-incubator/cri-o/issues/868
Haven't added the colour functionality, not sure if that is needed/wanted.
> Add namespace flag to kpod ps

- server/sandbox_network.go
- server/sandbox_run.go
- server/sandbox_stop.go
Runtimes need to clean up anything that needs it if RunPodSandbox() fails.  Like the network.
@rajatchopra @mrunalp
> server: clean up sandbox network when running the sandbox fails

- cmd/kpod/main.go
If the user specifies --debug flag then print stack trace.
> Only print error message on kpod error not stacktrace

- README.md
- cmd/kpod/main.go
- cmd/kpod/stop.go
- completions/bash/kpod
- docs/kpod-stop.1.md
- docs/kpod.1.md
- test/kpod_stop.bats
Stop one or more containers. Specific a timeout value
that if the stop operation exceeds, will forcibly stop
the container.
> kpod stop -- stop one or more containers

- cmd/kpod/rmi.go
When deleting by ID, kpod rmi was only "untagging" the image
and not actually removing it.
> cmd/kpod/rmi.go: Fix deletion by ID

- README.md
server: clean up sandbox network when running the sandbox fails
Latest Fedora 26 installed go 1.7.6, not the required go 1.8.x.  Adding a note for verification after the install and where to go if needed to get the latest golang.
> Add golang version note to README.md

- vendor.conf
- vendor/github.com/urfave/cli/README.md
- vendor/github.com/urfave/cli/app.go
- vendor/github.com/urfave/cli/cli.go
- vendor/github.com/urfave/cli/command.go
- vendor/github.com/urfave/cli/context.go
- vendor/github.com/urfave/cli/errors.go
- vendor/github.com/urfave/cli/flag.go
- vendor/github.com/urfave/cli/help.go
Updates urfave/cli to v1.20.0.  Now when kpod has an error, it shows just the error and not the error and the stack dump.  Example below of the bad behaviour.
This Fixes #882 
``` kpod save 36b3c5f87501 
refusing to save to terminal. Use -o flag or redirect
main.saveCmd
/builddir/build/BUILD/cri-o-bb1da978e30b3d32f988e30568b5161e8cfd700b/_build/src/github.com/kubernetes-incubator/cri-o/cmd/kpod/save.go:68
github.com/kubernetes-incubator/cri-o/vendor/github.com/urfave/cli.HandleAction
/builddir/build/BUILD/cri-o-bb1da978e30b3d32f988e30568b5161e8cfd700b/_build/src/github.com/kubernetes-incubator/cri-o/vendor/github.com/urfave/cli/app.go:485
github.com/kubernetes-incubator/cri-o/vendor/github.com/urfave/cli.Command.Run …
```
> Update urfave/cli to v1.20.0

- README.md
Added 3 dependencies that are needed to build cri-o to the README.md.   Without skopeo-containers, kpod will error with:
[root@localhost cri-o]# kpod pull alpine
error pulling image from "alpine": open /etc/containers/policy.json: no such file or directory
main.pullCmd
> Add a few build dependencies to README.md

- cmd/kpod/pull.go
- libpod/image.go
- libpod/images/copy_ref.go
- test/helpers.bash
- test/kpod.bats
- test/kpod_pull.bats
- test/registries.conf
- vendor/github.com/containers/image/pkg/sysregistries/system_registries.go
If the user provides kpod pull a short name like 'debian', we
still want the pull to be sucessful.  As such, when a short
name is provided, we get the list of searchable registries via
the systemregistries code in containers-storage.  We then
append a tag of 'latest' (if not provided) and we formulate
a list of possible fully-qualified image names to try.
Vendor update for containers-storage to bring in the system_registries
code.
> libkpod/image/copy.go: Add pull by short-name

- contrib/test/crio-integration-playbook.yaml
- contrib/test/venv-ansible-playbook.sh
Previously, an internal playbook installed many extra
necessary/unnecessary packages before this playbook even started.  Since
this is a terrible design, move all dependencies here so that nothing is
unwritten.  This includes installing some deps. for ansible itself
(which must be done as a raw command).
Signed-off-by: Chris Evich <cevich@redhat.com>
> integration-playbook: Add hidden dependencies

- cmd/crio/config.go
- conmon/conmon.c
- docs/crio.conf.5.md
- libkpod/config.go
- libkpod/container_server.go
- oci/oci.go
runc has a `--no-pivot` flag, that uses MS_MOVE instead.
This patch set bubbles up a runtime config to enable using no-pivot
globally.
> *: allow to not use pivot_root

- Makefile
Where `make install` still has the same behaviour, but you could instead
only `make install.bin` if you don't need the man pages.
> Makefile: break out the `install` target

- README.md
- cmd/kpod/main.go
- cmd/kpod/pause.go
- cmd/kpod/unpause.go
- completions/bash/kpod
- docs/kpod-pause.1.md
- docs/kpod-unpause.1.md
- libkpod/pause.go
- libkpod/remove.go
- libkpod/stop.go
- oci/oci.go
- test/kpod_pause.bats
- transfer.md
Implement the ability to pause and unpause running containers.
Taking over for @rhatdan to finish this up so he can chase down other pressing issues.  This takes over for d `kpod pause` and `kpod unpause` #923
> Add `kpod pause` and `kpod unpause`

- contrib/test/integration/e2e.yml
There are no tasks that we need to run after the suite has finished,
like we do with the integration suite, so it does not make sense to
ignore the errors coming out of the e2e suite.
Signed-off-by: Steve Kuznetsov <skuznets@redhat.com>
/cc @runcom @mrunalp
> Don't ignore failures in the e2e suite

- README.md
- cmd/kpod/kill.go
- cmd/kpod/main.go
- completions/bash/kpod
- docs/kpod-kill.1.md
- docs/kpod.1.md
- libkpod/kill.go
- test/kpod_kill.bats
- test/testdata/container_config_sleep.json
- transfer.md
Kill one or more containers using a user-provided signal.  If not signal
is provided, KILL is used.
> Add support for kpod kill

- docs/kpod-export.1.md
- docs/kpod-history.1.md
- docs/kpod-load.1.md
- docs/kpod-ps.1.md
- docs/kpod-pull.1.md
- docs/kpod-save.1.md
- docs/kpod-version.1.md
kpod ps manpage had misleading info
Fixed the Global options and options in other man pages
Realized I was writing man pages wrong all this while, and @TomSweeneyRedHat pointed out a mistake with the man page of kpod ps
> Made some changes to man pages

- tutorial.md
The design proposals were organized according to SIGs in https://github.com/kubernetes/community/pull/1010. This led to a broken link.
> tutorial: fix link after design proposal move

- cmd/kpod/ps.go
- docs/kpod.1.md
Adds a pause state to kpod-ps and touches up the main kpod man page to list pause and unpause.
> Add pause state to ps, touchup kpod man page

- cmd/kpod/common.go
- cmd/kpod/diff.go
- cmd/kpod/export.go
- cmd/kpod/history.go
- cmd/kpod/images.go
- cmd/kpod/info.go
- cmd/kpod/inspect.go
- cmd/kpod/kill.go
- cmd/kpod/load.go
- cmd/kpod/logs.go
- cmd/kpod/mount.go
- cmd/kpod/ps.go
- cmd/kpod/pull.go
- cmd/kpod/push.go
- cmd/kpod/rename.go
- cmd/kpod/rm.go
- cmd/kpod/rmi.go
- cmd/kpod/save.go
- cmd/kpod/stats.go
- cmd/kpod/stop.go
When a user enters a CLI with a StringFlags or StringSliceFlags and does not add
a value the CLI mistakently takes the next option and uses it as a value.
This usually ends up with an error like not enough options or others.  Some times
it could also succeed, with weird results.  This patch looks for any values that
begin with a "-" and return an error.
> validateFlags command line options to make sure the user entered a value

- libpod/images/rmi.go
As described in https://github.com/kubernetes-incubator/cri-o/issues/888, when
deleting by ID, the name being returned for the untagged message was "".
> kpod rmi by ID untagged: %name incorrect

- libkpod/config.go
- libkpod/container_data.go
- oci/oci.go
- server/server.go
Set the exitsdir for kpod back to /var/run/crio... so kpod can benefit
from the container exit file.
Because 0 is the int32 blank value, kpod needs its own container state
struct with the omitempty removed so it can actually display 0 in
its default json output.
> BUGFIX: Invalid return codes in kpod

- cmd/crio/main.go
- docs/crio.8.md
- docs/crio.conf.5.md
We need log-size-max to be bigger than the read buffer in conmon
to accurately truncate it.
> Make sure log-size-max is atleast as big as read buffer

- cmd/crio/main.go
- docs/crio.8.md
- kubernetes.md
- oci/oci.go
- test/helpers.bash
- tutorial.md
Running crio with `-debug` is very verbose. Having more granularity
on the log level can be useful when e.g. only looking for errors.
This PR replaces `-debug` with `-log-level` and also fixes an OCI container creation log level.
> main: Define -log-level option

- oci/oci.go
Under very heavy load, VM based containers can take more than 10s to start VMs, triggering the CRI-O container creation timeout. To gracefully handling that situation this PR:
- Increases the container creation timeout
- Asks the runtime for container deletion when creation fails.
> Handle container creation failures gracefully

- contrib/test/integration/build/kubernetes.yml
We have to call hack/local-up-cluster from kubernetes directory
as it makes relative calls to cluster/kubectl.sh. The failure
of these calls led to kube-dns not coming up.
> test: Fix kube dns bring up in cluster

- README.md
- docs/kpod-attach.1.md
- docs/kpod-cp.1.md
- transfer.md
Add a man page on how to achieve the same user experience as using
kpod attach by using either the kpod logs or kpod exec commands.
> Add documentation on kpod attach

- test/helpers.bash
Allow overriding CRIO_CNI_PLUGIN (default: /opt/cni/bin) and
make sure it gets written to our crio.conf file. This is
intended for running cri-o tests with containernetworking-cni
rpm which installs into /usr/libexec/cni
> Parameterize CRIO_CNI_PLUGIN

- cmd/kpod/main.go
- completions/bash/kpod
- docs/kpod.1.md
The change in flag from debug to log-level was causing cri-o to fail when started
There was a reference to the debug flag in kpod/main.go that had not been changed
> Changed debug flag to log-level in kpod/main.go

- test/network.bats
When running the test suite interactively, "Connect to pod
hostport from the host" test hangs because nc thinks it's
got a bidirectional connection. Running with --recv-only
closes the connection after receiving the expected data,
letting the tests proceed.
This is just a suggestion for n00b-friendliness. Running
interactively is rare, but it's exactly where a n00b
will begin, and the hang costs a little time and energy
to track down.
> nc (netcat): don't block when run interactively

- cmd/kpod/formats/formats.go
- cmd/kpod/ps.go
For commands that ask for JSON results, if the input to the Go JSON
marshaller is empty, it will return a byte array with a literal
"null" in it.  If that is the case, we should output [] instead
as at least that is valid JSON and will not break consumers of the
data.
> Return Valid JSON for empty data

- cmd/crio/config.go
- cmd/crio/main.go
- libkpod/config.go
- server/container_create.go
- server/secrets.go
- test/crio_secrets.bats
- test/helpers.bash
Allows the user to define secret paths in /etc/containers/mounts.conf
These are then volume mounted into the container
references issue https://github.com/kubernetes-incubator/cri-o/issues/919
> Add secrets support to crio

- oci/oci.go
It always fails because conmon is still there.
But more importantly it adds a 2 seconds delay to the container
creation as we're trying to delete a cgroup but we can't.
With this patch a container creation is down to typically less than
150ms instead of 2+ seconds.
> oci: Remove useless crio-conmon- cgroup deletion

- oci/oci.go
Needed in v1.0.0
runc must kill all processes in a container or we may get something like (during stress testing):
```
TERM failed: exit status 1
```
@mrunalp @rhatdan PTAL (cri-containerd is also behaving like this)
> oci: kill all processes in a container not just the main one

- server/container_create.go
- server/container_list.go
- server/sandbox_run.go
We now can pass 40/55 tests with this PR.  Remaining tests include may be fixed
with 1.8.
[Fail] [k8s.io] PodSandbox runtime should support sysctls [It] should support safe sysctls
[Fail] [k8s.io] Security Context SeccompProfilePath docker/default [It] should support seccomp docker/default on the container
[Fail] [k8s.io] Security Context SeccompProfilePath [It] runtime should not support a custom seccomp profile without using localhost/ as a prefix
[Fail] [k8s.io] Security Context bucket [It] runtime should support RunAsUser
[Fail] [k8s.io] PodSandbox runtime should support basic operations on PodSandbox [It] runtime should support removing PodSandbox [Conformance]
[Fail] [k8s.io] Container runtime should support mount propagation [It] mount with 'rshared' should support propagation from …
> Initial fixes for cri-tests

- cmd/kpod/load.go
- cmd/kpod/pull.go
- completions/bash/kpod
- docs/kpod-load.1.md
- docs/kpod-pull.1.md
- libpod/runtime_img.go
- test/kpod_load.bats
Add signature-policy parameter to kpod load and documentation to the kpod load and pull man pages to cover the parameter.  In testing I discovered that only the default location for policy.json was being used, so that's the cause of the change in runtime_image.go.  This is the second PR for these changes.  This PR contains the fixes per @mheon.  I had a weird CLA issue with the first PR, so closed it.
> Update kpod load to add signature-policy (2)

- contrib/test/integration/build/runc.yml
CI broke cause we're using runc from master - https://github.com/kubernetes-incubator/cri-o/pull/1014#issuecomment-336870378
Let's get this to how it was before the CI refactor by using the same runc commit we have in the Dockerfile
@rhatdan @mrunalp PTAL
> CI: use a fixed runc version, not master

- server/container_create.go
- server/secrets.go
- test/crio_secrets.bats
Tested on a REHL box and found out that the mounts were not showing up
Had a logic flaw, where if the mount was "host:container"
Was setting the mount source to "host" and destination to "ctrRunDir/container"
When instead, the mount source should be "ctrRunDir/container" and destination "container"
with the data copied from "host" to "ctrRunDir/container"
> Fix logic flaw in secrets mount

- server/container_create.go
- server/secrets.go
- test/crio_secrets.bats
Tested on a REHL box and found out that the mounts were not showing up
Had a logic flaw, where if the mount was "host:container"
Was setting the mount source to "host" and destination to "ctrRunDir/container"
When instead, the mount source should be "ctrRunDir/container" and destination "container"
with the data copied from "host" to "ctrRunDir/container"
> Fixed logic flaw in the secrets mounts

- test/network.bats
New network test makes improper assumptions about conmon path.
Use predefined CONMON_BINARY variable instead. And, restore
permissions earlier so a test failure doesn't result in a broken system.
> Issue #1024: don't chmod a nonexistent file

- Makefile
- cmd/crio/main.go
- server/server.go
- server/version.go
- version/version.go
Version handling with a VERSION file isn't really flexible as we can't actually use the version anywhere else in Go code.
This patch switches the crio version to use a new pkg called `version` (you guys can move kpod_version to this later).
This patch is also fixing some stuff with the version CRI api call. We used to return container names as `runc://<CONTAINER_ID>` whether we must have returned `cri-o://<CONTAINER_ID>` (so this patch fixes this as well).
@mrunalp PTAL
> version: fix version handling and kube info

- server/sandbox_list.go
We should not error when we try to find a pod ID in a filtered
list of sandboxes; instead we should return an empty struct
and log it.
This fixes another cri-test failure.
> server/sandbox_list.go: No error on filtered list find by ID

- contrib/test/integration/swap.yml
- contrib/test/integration/system.yml
- contrib/test/integration/vars.yml
If the playbook is run multiple times or a host already has
swap configured, re-adding swap from a file can be problematic.
Avoid this by checking if swap is active, if not, also check
if the swapfile is in-use before truncating/formatting it.
Perform these steps again outside of the ``setup`` tag to ensure
swap is enabled/in use during testing-time as well.
Signed-off-by: Chris Evich <cevich@redhat.com>
> integration-playbook: Don't re-swap

- README.md
- cmd/crio/main.go
- cmd/crioctl/main.go
- contrib/test/integration/build/kubernetes.yml
- docs/crio.8.md
- docs/crio.conf.5.md
- kubernetes.md
- server/config.go
After discussing with @derekwaynecarr we agreed that we shouldn't require any changes to kube for our 1.8. So reverting this for now. 
> Revert "Move crio default sock to /var/run/crio/crio.sock"

- libkpod/container_server.go
- oci/container.go
- oci/oci.go
- server/container_create.go
- server/sandbox_run.go
This patch fixes exec to use the original (start-time) process exec
configuration. Otherwise, we were creating a brand new spec process w/o
additional groups for instance.
Spotted while integrating CRI-O with cri-test...The test was failing
with:
```
• Failure [10.640 seconds]
[k8s.io] Security Context
/home/amurdaca/go/src/github.com/kubernetes-incubator/cri-tools/pkg/framework/framework.go:72
bucket
/home/amurdaca/go/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/security_context.go:407
runtime should support SupplementalGroups [It]
/home/amurdaca/go/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/security_context.go:272
Expected
<[]string | len:1, cap:1>: ["0"]
to contain element matching
<string>: 1234
```
> [release-1.0] Fix process exec v1

- libkpod/container_server.go
- oci/container.go
- oci/oci.go
- server/container_create.go
- server/sandbox_run.go
This patch fixes exec to use the original (start-time) process exec
configuration. Otherwise, we were creating a brand new spec process w/o
additional groups for instance.
Spotted while integrating CRI-O with cri-test...The test was failing
with:
```
• Failure [10.640 seconds]
[k8s.io] Security Context
/home/amurdaca/go/src/github.com/kubernetes-incubator/cri-tools/pkg/framework/framework.go:72
bucket
/home/amurdaca/go/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/security_context.go:407
runtime should support SupplementalGroups [It]
/home/amurdaca/go/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/security_context.go:272
Expected
<[]string | len:1, cap:1>: ["0"]
to contain element matching
<string>: 1234
```
> oci: respect process spec on exec

- Makefile
- contrib/test/integration/test.yml
- test/helpers.bash
- test/kpod_kill.bats
The `$STORAGE_OPTS` environment variable is also used by the storage library, so in cases where it was exported to the logic being tested, it was overriding settings we wanted to use during tests.
Also removes some duplicate definitions in the `kpod_kill` test.
> tests: rename $STORAGE_OPTS to $STORAGE_OPTIONS

- test/crio_secrets.bats
Remove the directory named by `$MOUNT_PATH`, not `MOUNT_PATH`.
Run `cat /proc/mounts` instead of `mount` in the test container.
Run `grep` using the `run` helper when we want to capture its output in `$output` and its exit status in `$status`.
> Fixups for crio_secrets.bats

- libpod/options.go
When copying the GID map at startup, size the map correctly.
> Fix a copy/paste error in libpod initializers

- libpod/runtime.go
- test/kpod_push.bats
When initializing a Runtime, set the default Store for the containers-storage transport in the image library to the same one that we're using, so that the calling process sees the same set of images
in the Runtime that it sees when going through the image library.
Update the `kpod_push` test so that it no longer has to specify a location in the destination image reference, since the default should already be passed to kpod as global options.
> libpod: set the default Store to match a Runtime

- libkpod/container_server.go
- vendor.conf
- vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
- vendor/github.com/opencontainers/selinux/go-selinux/selinux.go
This will release the MCS Label to be used again.  Only do this if we
don't have another sandbox using the same label.
Also vendor in the latest selinux go bindings, which fixes a leak and
properly reserves the SELinux label we are going to use.
> We need to release the SELinux label when we destroy the sandbox

- Dockerfile
In the config file (/etc/crio/crio.conf) installed by `make install.config` , runc runtime path is specified "/usr/bin/runc"
> fixes runc install path on Dockerfile

- conmon/conmon.c
- oci/oci.go
- server/container_attach.go
Convert a constant in `conmon` into an argument. This removes a few unexplained instances of `/var/run/crio` in the code and replaces them with a single constant in the oci package that is passed through to conmon.
This is necessary for some of the work ongoing in libpod.
> Make attach sockets directory an argument in Conmon

- server/server.go
> server: correctly return and close ch from exits routine

- contrib/systemd/crio.service
Borrowed from:
https://github.com/projectatomic/atomic-system-containers/pull/136
From: Antonio Murdaca <runcom@redhat.com>
@mrunalp @runcom PTAL
> systemd: expand limits for tests

- cmd/crio/main.go
Same as #1090 but for 1.0.x
This will avoid the goroutines leak we've been seeing during
performance tests. Goroutines count returns to normal after containers
cleanup.
@mrunalp PTAL
> [release-1.0] cmd: crio: set ReadTimeout on the info endpoint

- cmd/crio/main.go
This will avoid the goroutines leak we've been seeing during
performance tests. Goroutines count returns to normal after containers
cleanup.
This is actually a better fix than #1082 as we're not changing the socket for the info endpoint but that's still something to consider for 1.8/1.9.
@mrunalp PTAL
> cmd: crio: set ReadTimeout on the info endpoint

- Makefile
- hack/ostree_tag.sh
- hack/selinux_tag.sh
We need @rhatdan's change in the 1.0.x line as well (https://github.com/kubernetes-incubator/cri-o/pull/1042)
> [release-1.0] Makefile fixes for v1.0.x

- tutorial.md
Touches up runc kit location per #1069 that wasn't merged.   The runc kit has dropped '-linux-' in favor of a period (.).
> Change runc location of runc in tutorial.md

- README.md
On CentOS, I needed this for `make` build step to complete
> add golang-github-cpuguy83-go-md2man dep

- server/container_create.go
- test/ctr.bats
Fixed https://bugzilla.redhat.com/show_bug.cgi?id=1508391
CRI-O wasn't setting up the cwd in case it didn't exist. Docker does that and this patch fixes the BZ indeed.
handle cwd setup on container creation
added an integration test which fails on master
@rhatdan @mrunalp PTAL
> [release-1.0] container_create: setup cwd for containers

- server/container_create.go
- test/ctr.bats
Fixed https://bugzilla.redhat.com/show_bug.cgi?id=1508391
CRI-O wasn't setting up the cwd in case it didn't exist. Docker does that and this patch fixes the BZ indeed.
handle cwd setup on container creation
added an integration test which fails on master
@rhatdan @mrunalp PTAL
> container_create: setup cwd for containers

- Makefile
Signed-off-by: Shijiang Wei <mountkin@gmail.com>
Make `make dbuild` really works.
Type `make dbuild` to see if it builds the binaries successfully. 
> fix "docker run" command in Makefile

- Makefile
kpod removal actually removed all man1 docs but the Makefile was still
referencing man1 stuff. CRI-O doesn't have man1 so let's drop that
altogether now.
Fix #1128 
> Makefile: do not install man1 files

- vendor.conf
- vendor/github.com/vbatts/tar-split/README.md
- vendor/github.com/vbatts/tar-split/tar/asm/disassemble.go
- version/version.go
> [release-1.0] vendor.conf: update vbatts/tar-split to v0.10.2

- vendor.conf
- vendor/github.com/vbatts/tar-split/README.md
- vendor/github.com/vbatts/tar-split/tar/asm/disassemble.go
Update vendor/github.com/vbatts/tar-split to v0.10.2, to fix CVE-2017-14992, per https://github.com/vbatts/tar-split/pull/42.
> Bump github.com/vbatts/tar-split

- server/container_attach.go
- server/container_create.go
- server/container_exec.go
- server/container_execsync.go
- server/container_list.go
- server/container_portforward.go
- server/container_remove.go
- server/container_start.go
- server/container_stats.go
- server/container_stats_list.go
- server/container_status.go
- server/container_stop.go
- server/container_update_resources.go
- server/container_updateruntimeconfig.go
- server/image_fs_info.go
- server/image_list.go
- server/image_pull.go
- server/image_remove.go
- server/image_status.go
- server/metrics/metrics.go
- server/runtime_status.go
- server/sandbox_list.go
- server/sandbox_remove.go
- server/sandbox_run.go
- server/sandbox_status.go
- server/sandbox_stop.go
- server/server.go
- server/utils.go
- server/version.go
Added metrics to the prometheus endpoint about CRI operations
vim
access `localhost:4242/metrics` on a node running CRI-O with kubernetes. Play with pods, images and everything. Refresh the metrics endpoint and notice metrics about CRI operations:
```
container_runtime_crio_operations{operation_type="create_container"} 3
container_runtime_crio_operations{operation_type="pull_image"} 1
container_runtime_crio_operations{operation_type="remove_pod_sandbox"} 1
container_runtime_crio_operations{operation_type="run_pod_sandbox"} 3
container_runtime_crio_operations{operation_type="stop_pod_sandbox"} 1
container_runtime_crio_operations_latency_microseconds{operation_type="create_container" …
```
> server: add prometheus metrics for CRI operations

- test/ctr_seccomp.bats
- test/helpers.bash
- test/network.bats
* Skip some tests if the bridge-custom plugin is
unavailable. This CNI plugin is not distributed in
any RPM, it is only available by compiling from a
side branch in runcom's private github. We can't
use it in a real integration-test setting.
* Don't use `run()` inside cleanup handlers. It will
override $status, which is a double whammy:
- successful cleanup will mask a test failure
- when a test is `skip()`ed, crictl may fail,
and $status will indicate failure.
* seccomp test: use existing $SECCOMP_PROFILE instead of
assuming a path under $CRIO_ROOT
> Various test-scaffolding fixes

- Dockerfile
- Makefile
- contrib/test/integration/build/cri-tools.yml
- crictl.yaml
- server/container_create.go
- server/container_list.go
- server/sandbox_run.go
- server/utils.go
- test/helpers.bash
- version/version.go
Will tag 88dd6f325bcbb0be6d7ffe70c7d44b69721715b1 v1.0.4
Release notes:
```
Welcome to the release of CRI-O v1.0.4!
This last patch release mainly adds additional Prometheus metrics focusing
on the CRI API itself. It also includes various bug fixes.
Please try out the release binaries and report any issues at
https://github.com/kubernetes-incubator/cri-o/issues.
* Antonio Murdaca
* Daniel J Walsh
* Mrunal Patel
* 88dd6f325 version: bump to v1.0.4
* 97bbc8cd1 container_list: guard against list filter being nil
* 544396a0e *: add crictl.yaml
* ed34ff325 server: validate labels size to avoid dos
* ce319adcf Merge pull request #1140 from runcom/backports-image-pull-metrics
* 12cb42483 server: add prometheus metrics for CRI operations
* 5488bfeb9 image_pull: repull when image ID (config …
```
> Bump v1.0.4

- server/container_create.go
If you're wondering, this is not a bug since the profile is set directly in spec and run. Just adding for consistency and fixing the TODO
> container_create: set the seccomp profile in the container object

- .travis.yml
- Makefile
- hack/validate/.validate
- hack/validate/deprecate-crioctl
`crioctl` is deprecated in favor of  `crictl` from `kubernetes-incubator/cri-tools`. We already wired in the project `crictl` but there are tests still relying on `crioctl`. This patch adds a verification target which if you're adding a test with crioctl, it'll tell you to use `crictl` instead. This would ease the transaction to `crictl`.
added a deprecation script
commit a new test which uses crioctl and notice it's failing here in travis, output looks like the following:
```
$ make verify                                         
These files use crioctl instead of crictl:
- test/ctr.bats
make: *** [Makefile:70: verify] Error 1
```
> hack: validate tests for crioctl deprecation

- .gitignore
- server/config_test.go
- server/fixtures/crio.conf
This change is the first of several needed to address #893.
I added tests to the functions in `server/config.go`.
I am using a fixture I saved on `server/fixtures/crio.conf` to check that the functions in `config.go` are reading and writing conf files properly.
Run the tests.
`Add tests for server/config.go`
Note: some extra paths about Vagrant and VSCode were added to gitignore. Let me know if you want me to remote those.
Note 2: I added a `TODO` on the `.conf` file because I am not sure what to do with that configuration.
> Add tests for server/config.go

- contrib/test/integration/build/kubernetes.yml
- contrib/test/integration/main.yml
This allows us to cache a k8s branch for cri-o 1.0 branch
while allowing overriding of k8s branch in master and other
newer cri-o branches.
@runcom @cevich PTAL
Added support for switching between k8s branches in different cri-o branches.
Added a var for specifying kubernetes checkout version in ansible for tests.
Verify tests work for 1.0 and other branches. 
Add var for kubernetes branch in ansible.
> test: Add a version var for kube branches

- README.md
- cmd/crio/main.go
- cmd/crioctl/main.go
- contrib/test/integration/build/kubernetes.yml
- docs/crio.8.md
- docs/crio.conf.5.md
- kubernetes.md
- server/config.go
`master` is now tracking kubernetes 1.9 and we can switch to `/var/run/crio/crio.sock`. The behavior is still controllable via config and flags.
Refer to #1030 for old discussion
Fix #1028 
cAdvisor PR: https://github.com/google/cadvisor/pull/1773
Kubernetes PR: https://github.com/kubernetes/kubernetes/pull/54136
@mrunalp @rhatdan @derekwaynecarr @smarterclayton PTAL
> Move crio default sock to /var/run/crio/crio.sock

- cmd/crio/config.go
- cmd/crio/main.go
- docs/crio.8.md
- docs/crio.conf.5.md
- libkpod/config.go
- server/container_create.go
- test/helpers.bash
- test/namespaces.bats
Signed-off-by: Wei Wei <weiwei.inf@gmail.com>
enable share pid namespace for containers in a pod, and add a --disable-share-pid-namespace flag to disable this feature
vim
start crio with/without `--disable-shared-pid-namespace`
enable share pid namespace for containers in a pod and add a --disable-share-pid-namespace flag to disable this feature
closes #1135
closes https://github.com/kubernetes-incubator/cri-o/issues/488
> share pid namespace for Pod container

- cmd/crio/config.go
- cmd/crio/main.go
- docs/crio.8.md
- docs/crio.conf.5.md
- libkpod/config.go
- server/container_create.go
- test/helpers.bash
- test/namespaces.bats
We reverse the logic so that pid ns sharing is disabled by default.
@weiwei04 @rhatdan @runcom PTAL
I think we should do this because this is the direction upstream will be headed and we want to 
make this enabled explicitly. Till now all pods have run w/o this feature so enabling it should be 
left to the user to turn on by default rather than the default behavior.
Made pid ns sharing opt-in.
Reversing the logic we merged by changing disable -> enable
Tests pass
```changelog
Disable pid namespace sharing by default and allow enabling it.
```
> Make pid namespace sharing optional and disabled by default

- contrib/test/integration/build/cri-tools.yml
- contrib/test/integration/critest.yml
- contrib/test/integration/main.yml
- contrib/test/integration/test.yml
run `critest` validation _before_ the e2e kube tests. If `critest` fails, there would be no need to trigger the whole e2e.
> CI: wire in critest

- server/container_create.go
- version/version.go
> [release-1.8] Add /proc/scsi to masked paths

- server/container_create.go
> Add /proc/scsi to masked paths

- server/container_create.go
- version/version.go
> [release-1.0] Add /proc/scsi to masked paths

- contrib/test/integration/build/kubernetes.yml
- contrib/test/integration/main.yml
This is needed for the 1.0 branch where we're still using `/var/run/crio.sock`. It happened that w/o this, the ami nightly builds built with the wrong socket, we need this so we have 1.0 back to normal.
@mrunalp PTAL
> contrib: parametrize the crio socket for kube

- contrib/test/integration/golang.yml
> CI: drop git-validation as it's never used

- conmon/conmon.c
- contrib/test/integration/build/cri-tools.yml
- contrib/test/integration/build/kubernetes.yml
- contrib/test/integration/main.yml
- oci/oci.go
- test/ctr.bats
This is for https://github.com/kubernetes/kubernetes/pull/55922
Added support for partial/newline log tags.
Modified conmon to add the log tags. This simplifies log writing logic.
kubectl logs should work fine like before.
```changelog
Add support for partial/newline log tags
```
> conmon: Add support for partial/newline log tags

- contrib/test/integration/main.yml
Updated golang to 1.8.5
Modifying the version in ansible.
Tests pass.
```
Bump up go to 1.8.5 in tests.
```
> Bump up go version to 1.8.5

- version/version.go
Welcome to the release of CRI-O v1.0.7!
This new CRI-O patch release fixes a bug in how we were setting container
environment variables when exec'ing into it.
Please try out the release binaries and report any issues at
https://github.com/kubernetes-incubator/cri-o/issues.
* Antonio Murdaca
* Daniel J Walsh
* Mrunal Patel
* 7a3e37e25 version: bump to v1.0.7
* eb8df9518 Merge pull request #1187 from runcom/fixups-env-1.7
* 762cb4cca test: add exec/execsync env conflict test
* cc0f78dfc container_create: correctly set image and kube envs
* e4470612a oci: do not append conmon env to container process
* 3a36f553a container_exec: use process file with runc exec
* c30571b43 Merge pull request #1182 from runcom/fix-image-pull-v1
* 327c67318 version: bump to v1.0.7-dev
Previous release can be …
> Bump v1.0.7

- version/version.go
Welcome to the release of CRI-O v1.8.3!
This new CRI-O patch release fixes a bug in how we were setting container
environment variables when exec'ing into it.
Please try out the release binaries and report any issues at
https://github.com/kubernetes-incubator/cri-o/issues.
* Antonio Murdaca
* Mrunal Patel
* d9922a9db version: bump to v1.8.3
* 187876571 Merge pull request #1191 from runcom/fix-apparmor-1.8
* 6a9c6b182 Merge pull request #1188 from runcom/fixups-env-1.8
* b2ea67f50 container_create: fix apparmor from container config
* 17ec00c5d test: add exec/execsync env conflict test
* bb327bc3a container_create: correctly set image and kube envs
* 4cde51526 oci: do not append conmon env to container process
* 99b3e82fa container_exec: use process file with runc exec
* 171e31287 Merge …
> Bump v1.8.3

- test/ctr.bats
Under some slow environment (nested VMs) or with some
not as fast runtimes (Clear Containers), asking for a
status right away is racy.
> test: Add timeout before checking for status

- tutorial.md
I was trying to install and test cri-o on my laptop, and faced with few issues that was preventing to install properly, I spent some time for fixing, so decided update this documentation for quick start.
Changes:
- Update Go version to 1.8.5
- Update list packages that need to build crio.
- Added policy.json (without it container won't start)
- Added restart for crio daemon for reading cni config
> Update install.md relevant documentation

- libkpod/container_server.go
- libkpod/sandbox/history.go
- libkpod/sandbox/memory_store.go
- libkpod/sandbox/sandbox.go
- libkpod/sandbox/store.go
same as #1198 but for `release-1.7` branch - note that we're not using the `release-1.0` branch anymore as this way we can avoid confusion around 1.0->1.7 - especially for people integrating automation with our repository.
> [release-1.7] libkpod: sandbox: refactor to memory store

- oci/oci.go
Some oci runtimes may used stderr for logging.  Cri-o should not try to parse this output as json when calling the "state" command.
Use `cmd.Output` (which only includes stdout) instead of `cmd.CombinedOutput` (which combines stdout and stderr).
**- Description**
Only parse stdout from "state" command.  Ignore stderr.
> Only parse stdout from "state" command.  Ignore stderr.

- oci/oci.go
- server/container_exec.go
Fixed and refactored the way we're calling runc exec in container_exec. This patch is fixing a bug where kube requests the terminal for exec but we're not honoring it.
set terminal in runc exec's process json
run `kubectl exec -ti POD -- sh` and see it works, Before this patch, it would just hang.
> container_exec: fix terminal true process json

- version/version.go
@mrunalp PTAL, we need to tag `v1.0.8` afterwards (I've already tagged `v1.8.4`)
> Bump v1.0.8

- Dockerfile
- contrib/test/integration/build/runc.yml
bump runc to c6e4a1ebeb1a72b529c6f1b6ee2b1ae5b868b14f so it contains https://github.com/opencontainers/runc/pull/1651 which is a fix to a weird systemd bug which we're hitting in e2e_rhel
vim
> bump runc to c6e4a1ebeb1a72b529c6f1b6ee2b1ae5b868b14f

- Dockerfile
Build image for integration test on arm64 will fail for lack of
hexdump. Add bsdmainutils tool to eliminate that failure and let
build image succussfully
help me check it  @redbaron @mumoshu  @runcom @mrunalp  
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>
> Add bsdmainutils tool to Dockerfile to enable integration test on arm64

- Makefile
Instead of compiling all of the *.go files each time, the
-i flag will cause them to be only compiled if they changed.
This will make developers much happier.
> Add -i flag to speed up compilation of cri-o packages

- contrib/system_containers/centos/run.sh
- contrib/system_containers/fedora/run.sh
- contrib/system_containers/rhel/run.sh
System containers read environment variables from the `/etc/sysconfig/crio-storage` and
`/etc/sysconfig/crio-network` files in the same way as the systemd service file does on the host.
- system containers honor `/etc/sysconfig/crio-storage` and `/etc/sysconfig/crio-network` configuration files.
> contrib: system containers read env from /etc/sysconfig/crio-(network|storage)

- lib/container_server.go
- lib/sandbox/memory_store.go
- oci/memory_store.go
Should fix a possible deadlock in, at least, ListPodSandbox.
There seems to be no reason to hold stateLock when doing operations on
the memory_store for containers and sandboxes.
> [release-1.9] lib,oci: drop stateLock when possible

- libkpod/container_server.go
- libkpod/sandbox/memory_store.go
- oci/memory_store.go
Should fix a possible deadlock in, at least, ListPodSandbox.
There seems to be no reason to hold stateLock when doing operations on
the memory_store for containers and sandboxes.
> [release-1.8] lib,oci: drop stateLock when possible

- libkpod/container_server.go
- libkpod/sandbox/memory_store.go
- oci/memory_store.go
Should fix a possible deadlock in, at least, ListPodSandbox.
There seems to be no reason to hold stateLock when doing operations on
the memory_store for containers and sandboxes.
> [release-1.7] lib,oci: drop stateLock when possible

- conmon/conmon.c
> Improve error messages on missing runtime

- contrib/system_containers/centos/tmpfiles.template
- contrib/system_containers/fedora/tmpfiles.template
- contrib/system_containers/rhel/tmpfiles.template
Create /var/run/crio so that the system container doesn't fail on startup.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1529039
> syscontainer: create /var/run/crio

- Makefile
found that from a clean checkout of source, that `make install.config` failed to install crio.conf, as it didn't exists.
Made the install.config target depend on the crio.conf file existing.
```shell
[vbatts@chacha] (master) ~/src/github.com/kubernetes-incubator/cri-o$ sudo make install.config
install -Z -D -m 644 crio.conf /etc/crio/crio.conf
install: cannot stat 'crio.conf': No such file or directory
make: *** [Makefile:149: install.config] Error 1
[vbatts@chacha] (master) ~/src/github.com/kubernetes-incubator/cri-o$ make crio.conf
go build -i -ldflags '-s -w -X main.gitCommit="41aaf4e3d812d1dfa9e18b7aad39b0e2be4f1960" -X main.buildInfo=1515619273' -tags "seccomp     selinux …
```
> Makefile: installing a config, requires a config

- test/README.md
And changed the name of their binary.  This commit catches the docs up with intel/cc-oci-runtime#1065 (merged 2017-09-25).
> test/README: Clear Containers moved to clearcontainers/runtime

- kubernetes.md
- tutorial.md
The cri-o entries are stale vs. the content currently installed by the `Makefile`.  This pull-request drops them and just references the make call before starting the table, which lets us stay DRY.
`runc` is not built from the cri-o repository.  The docs have claimed it was since 983aec63 (#353), but it's independent like the CNI plugins.
I've added a link to the in-repo `policy.json` example.  We probably also want to link to [the docs][1] (for the version we vendor?), but I've left that alone for now.
The CNI config examples were removed from the project README in 9088a12c (#295).  I've adjusted the reference to point to the new location, although again, I'd rather replace this with links to upstream docs.
I've also removed some stale `make` output sections from the tutorial.  Notes in …
> kubernetes: Simplify and freshen the required-files table

- test/README.md
Catching up with the `Dockerfile` change from f51b0a10 (#536).  The new plugins commit from f51b0a10 is still the current `Dockerfile` entry.
This pull-request also replaces the previous `go get` call with a `git clone` to match the `Dockerfile`'s approach.  I've added an additional `cd` call so I don't have to repeat `$GOPATH/…` more than once, but other than that, the example matches [the current Dockerfile entry][1].
[1]: https://github.com/kubernetes-incubator/cri-o/blob/1bb5846d7d0d6b6d755728053a11690d053c6362/Dockerfile#L71-L80
> test/README: Update the CNI plugins instructions for /cni → /plugins

- test/namespaces.bats
DRY up this code.  The `${parameter:-word}` syntax is [in POSIX][1].
This is setting the stage for some PID-namespace work I have in progress locally to allow for container PID namespaces that are children of the pod's infra PID namespace (see my comment [here][2]).  I'm filing this as a separate PR, since this seems like an easy improvement regardless of whether you want to pick up my broader PID adjustment.
[1]: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_06_02
[2]: https://github.com/kubernetes-incubator/cri-o/issues/1242#issuecomment-359076499
> test/namespaces: Factor out pid_namespace_test helper

- contrib/system_containers/centos/tmpfiles.template
- contrib/system_containers/fedora/tmpfiles.template
- contrib/system_containers/rhel/tmpfiles.template
Backport of #1250 to `release-1.9` branch.
> Backport 1.9: syscontainer: create /var/run/crio

- contrib/system_containers/centos/run.sh
- contrib/system_containers/fedora/run.sh
- contrib/system_containers/rhel/run.sh
Backport of #1245 to release-1.9 branch.
> Backport 1.9: contrib: system containers read env from /etc/sysconfig/crio-(network|storage)

- server/container_create.go
- server/sandbox_run.go
Fix https://github.com/kubernetes-incubator/cri-o/issues/1254
/cc @vbatts 
use grpc getters that handle nil cases instead of accessing fields directly
> server: use grpc getters to avoid panics

- tutorial.md
Fixed a few minor errors in the tutorial document.
What I did was just s/runs/runp/ and s/inspects/inspectp/. More specifically:
```
$ POD_ID=$(sudo crictl runs test/testdata/sandbox_config.json)
$ sudo crictl inspects --output table $POD_ID
$ POD_ID=$(sudo crictl runp test/testdata/sandbox_config.json)
$ sudo crictl inspectp --output table $POD_ID
```
I used a crictl version `1.0.0-alpha.0` for testing. With this version, hitting `crictl runs ...` or `crictl inspects ...` commands simply returns error `No help topic for 'runs|inspects'`. 
Fixed a few minor errors in the tutorial document
> Fix a few minor errors in the tutorial document

- server/container_create.go
k8s already mounts /etc/hosts from /var/lib/kubelet/pods/<ID>/etc-hosts
even for host network. We shouldn't play with it unless we're running
from crictl for instance.
Relevant k8s code: https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kubelet_pods.go#L259-L266
> container_create: only bind mount /etc/hosts if not provided by k8s

- .tool/lint
There was a `command -v` check back when this script landed in aa748b62 (#30), but it was removed in 741873ad (#70).  The default changed from `gometalinter` to `${GOPATH}/bin/gometalinter` in 6c9628cd (#320) and the `-f` guard landed in 9c240aed (#850).  This commit brings us back to our original `command -v` check ([in POSIX][1]), which allows support for both filesystem and `$PATH` based commands (and shell aliases, etc.).
I've also made the default `LINTER` more flexible, using the `${parameter:-word}` syntax [from POSIX][2].  That keeps the default linter unchanged, but allows callers to set the `LINTER` environent variable to override.  For example:
```console
$ LINTER=gometalinter .tool/lint
```
will use the linter from your $PATH.
[1]: …
> .tool/lint: Use 'command -v' to detect LINTER presence

- server/container_create.go
k8s already mounts /etc/hosts from /var/lib/kubelet/pods/<ID>/etc-hosts
even for host network. We shouldn't play with it unless we're running
from crictl for instance.
Backport of https://github.com/kubernetes-incubator/cri-o/pull/1282
@mrunalp PTAL
> [release-1.9] container_create: only bind mount /etc/hosts if not provided by k8s

- conmon/conmon.c
- oci/oci.go
This is triggered by StdinOnce set to false by the kubelet.
Added support for leaving container stdin open after attach client disconnects.
Added an option to conmon to leave stdin open and hooked it up with StdinOnce setting
passed over the CRI.
The kubectl tests pass. 
```
Support leaving the stdin open.
```
> Support leaving stdin open

- .travis.yml
k8s master builds off go 1.9.x so we run
all tests for 1.9.x and build on 1.9.x, 1.10.x and tip.
> Bump up go versions in travis

- lib/hooks.go
We accidently defined hooks using stages rather then stage,
which causes all of the hooks not to work, but we saw no
complaints in the log files about this.
> Report an warning when no stages are defined for a hook

- server/image_fs_info.go
- utils/filesystem.go
fixes half of https://github.com/kubernetes-incubator/cri-o/issues/1248 (to be in conjunction with https://github.com/kubernetes-incubator/cri-o/pull/1249)
This change fetches the disk info for the `GraphRoot/storagedriver-images` directory.
This was tested by printing out the `FilesystemUsage` values before returning it and 
comparing against:
`blkid` for the UUID 
`du -sb .` for the bytes
`du --inodes .` for the inodes used
Feedback is welcome on any changes such as (not limited to):
- if this is even the right directory to be checking
- coding style
- relocate the code elsewhere
- etc
Thanks!
**Description for the changelog**
Add CRI API support for imagefs usage stats
> Implement the stats for the image_fs_info command

- conmon/conmon.c
We want to pass the no-new-keyring through conmon down to the OCI
Runtime.
> Add no-new-keyring flag to conmon

- conmon/conmon.c
The options should be no-new-keyring, mistakenly written as no-new_keyring.
> Fix typo in options defition

- contrib/system_containers/centos/config.json.template
- contrib/system_containers/centos/manifest.json
- contrib/system_containers/fedora/config.json.template
- contrib/system_containers/fedora/manifest.json
- contrib/system_containers/rhel/config.json.template
- contrib/system_containers/rhel/manifest.json
This allows to accept additional mounts as a json snippet when the system container is installed.
> system container: add $ADDTL_MOUNTS

- contrib/test/integration/main.yml
https://github.com/kubernetes-incubator/cri-o/pull/1298 changed the setup of the AMI to actually skip runc build by default and that's causing the whole CI to fail with the ami built from that PR. (i.e. https://github.com/kubernetes-incubator/cri-o/pull/1297)
Fix it by reverting the logic so that we *always* build runc except when asked otherwise
@giuseppe @mrunalp @nalind PTAL
> contrib: test: fix runc build on AMIs

- Makefile
- cmd/crio/main.go
- contrib/test/integration/main.yml
- version/version.go
Allow to create the parent directory for the listen socket. Otherwise, we get failures like https://openshift-gce-devel.appspot.com/build/origin-ci-test/pr-logs/pull/18478/test_pull_request_origin_extended_conformance_crio/3888/ in the Origin CI
@mrunalp PTAL
> cmd/crio: fix listen address dir creation

- lib/container_server.go
- pkg/annotations/annotations.go
- server/container_create.go
- server/sandbox_run.go
We weren't setting the logPath of the sandbox when restoring sandboxes
and containers upon a crio restarts. That means that if you restart
CRI-O you get sandboxes with empty logPath. That means that when you're
starting a container in a restored sandbox you get a relative logPath
for the container:
sandboxLogPath: "/var/something"
- restore
sandboxLogPath: ""
- create container foo
containerLogPath: "foo_attempt.log"
With this patch we actually get an absolute path (which is correct):
sandboxLogPath: "/var/something"
- restore
sandboxLogPath: "/var/something"
- create container foo
containerLogPath: "/var/something/foo_attempt.log"
> sandbox: fix sandbox logPath when crio restarts

- lib/container_server.go
- lib/sandbox/sandbox.go
- pkg/annotations/annotations.go
- server/sandbox_run.go
- server/sandbox_status.go
We need to record whether the sandbox is using hostnetwok because the
kubelet needs that information when computing pod changes. Without this
patch it could happen that a pod that's using host network is restarted
just because the sandbox's status isn't reporting that it's running
using host network.
> sandbox: record whether sb is using host network

- pkg/storage/image.go
- server/container_create.go
- server/image_list.go
- server/image_status.go
This is #1333 with some caching added, to cache information about images that isn't trivially read from them, so that `ImageStatus` and particularly `ListImages` don't have to do potentially-expensive things for every image that they report.
The cache is an in-memory map, and we prune it after `ListImages` has assembled its result set.
This is an attempt at adding a cache as described at https://github.com/kubernetes-incubator/cri-o/pull/1333#issuecomment-365677747.  I went back and forth on whether or not to just cache the entire image config structure, but that's pretty easy to add if we find that we need to later.
> [release-1.9] imageService: cache information about images

- pkg/storage/image.go
- server/container_create.go
- server/image_list.go
- server/image_status.go
We had a bug in ImageStatus where we weren't returning the default
image user if set, thus running all containers as root despite a user
being set in the image config. We weren't populating the Username field
of ImageStatus.
This patch fixes that along with the handling of multiple images based
on the registry patch for multiple images.
It also fixes ListImages to return Username as well.
same as https://github.com/kubernetes-incubator/cri-o/pull/1332 but for 1.9.x @mrunalp PTAL
> [release-1.9] container_create: correctly set user

- oci/oci.go
The old “won't never” was a potentially-confusing double negative.  This commit rewords the comment to avoid that issue and also lands some other minor cleanups.
Copy-edits for comments aren't particularly important, but I noticed the “won't never” while looking at #1326 (which copies this comment), so I thought I'd file a suggested rewording in case the maintainers felt it was worth improving.
> oci: Copy-edits for waitContainerStop chControl comment

- pkg/storage/image.go
- server/container_create.go
- server/image_list.go
- server/image_status.go
This is #1332 with some caching added, to cache information about images that isn't trivially read from them, so that `ImageStatus` and particularly `ListImages` don't have to do potentially-expensive things for every image that they report.
The cache is an in-memory map, and we prune it after `ListImages` has assembled its result set.
This is an attempt at adding a cache as described at https://github.com/kubernetes-incubator/cri-o/pull/1333#issuecomment-365677747.  I went back and forth on whether or not to just cache the entire image config structure, but that's pretty easy to add if we find that we need to later.
> imageService: cache information about images

- lib/stats.go
- server/container_list.go
- server/container_stats.go
- server/container_stats_list.go
This uses the previously unusued lib/stats.go code to return data
about container stats to the CRI API.
No data on filesystem layer usage is returned at this time.
Fixes one-half of #1248
Signed-off-by: Yann Ramin <atrus@stackworks.net>
Add CRI API support for container statistics
> Add methods for listing and fetching container stats

- Makefile
- vendor.conf
- vendor/github.com/containers/image/copy/manifest.go
- vendor/github.com/containers/image/directory/directory_dest.go
- vendor/github.com/containers/image/docker/docker_client.go
- vendor/github.com/containers/image/docker/docker_image_dest.go
- vendor/github.com/containers/image/image/docker_schema1.go
- vendor/github.com/containers/image/image/oci.go
- vendor/github.com/containers/image/ostree/ostree_dest.go
- vendor/github.com/containers/image/storage/storage_reference.go
- vendor/github.com/containers/image/tarball/tarball_reference.go
- version/version.go
re-vendor c/image to pull in the fix about registries serving (wrongly) text/plain
This also bump to 1.9.6
> [release-1.9] vendor: update c/image to handle text/plain from registries

- Makefile
The hard-coded path landed in 488216f5 (#154), but there's no need to require that path.  Using `command -v` ([in POSIX][1]) supports anyone who has `selinuxenabled` in their `PATH`.
[1]: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/command.html
> Makefile: Use 'command -v selinuxenabled' instead of hard-coded path

- Makefile
This should have happened in f4883dd2 (#1129).  It may have been missed due to the `man1`/`man8` typo from e61c672a (#230).
> Makefile: Drop man1 uninstall

- Makefile
Without this change, hitting these targets directly will fail.  For example:
```console
$ make clean
$ make MANDIR=/tmp install.man
install  -d -m 755 /tmp/man5
install  -d -m 755 /tmp/man8
install  -m 644 docs/crio.conf.5 -t /tmp/man5
install: cannot stat 'docs/crio.conf.5': No such file or directory
make: *** [Makefile:150: install.man] Error 1
```
> Makefile: Fix install.* prerequisites

- Makefile
This patch fixes selinuxopt generation as found in:
```
install /usr/sbin/selinuxenabled -D -m 644 crio.conf /etc/crio/crio.conf
```
The above is clearly wrong when installing the configuration because
`commmand -v` outputs the path of selinuxenabled as well, resulting in
/usr/bin/selinuxenabled -Z
This patch fixes that by just echoing the -Z as needed.
Issue introduced in
https://github.com/kubernetes-incubator/cri-o/pull/1363
> Makefile: fix SELINUXOPT generation

- Makefile
- Makefile.inc
- conmon/Makefile
- conmon/conmon.c
Implemented `conmon --version`
Refactored the Makefile, create a `version.h` file that is used by `conmon.c` to read its version and print it.
`conmon --version` doesn't raise an error
conmon supports `--version`
> conmon: implement --version

- contrib/system_containers/centos/config.json.template
- contrib/system_containers/fedora/config.json.template
- contrib/system_containers/rhel/config.json.template
kubernetes daemon sets want to be able to drop plugin
payload into the /opt/cni/bin directory.
@giuseppe @runcom PTAL
> Make the /opt/cni mount rw

- oci/oci.go
We may consider setting it to true all the time but this
should match our previous behavior before we started
using process json for exec.
> execsync: Set terminal to true when we pass -t to conmon

- README.md
The GOPATH layout is created in the Makefile:
```
mkdir -p "/home/test/cri-o/_output/src/github.com/kubernetes-incubator"
ln -s "/home/test/cri-o" "/home/test/cri-o/_output/src/github.com/kubernetes-incubator"
```
Signed-off-by: Jan Pazdziora <jpazdziora@redhat.com>
I wanted to have the simplest possible way to build CRI-O. Specifically, I did not want to decide, where my "go" stuff will live -- I want the project confined to the CRI-O checkout directory like with any other (non-go) project.
Checked out the git repo, ignored the parts of README that talked about creating directory structure or installing tools -- I just run `make`.
```
1. git clone https://github.com/kubernetes-incubator/cri-o
2. cd cri-o
3. make
4. Profit.
``` …
> The Makefile works without GOPATH set and without install.tools fine.

- .gitignore
We've been occasionally creating this file since 9c44933b (#410).  But it's recording information about the local environment, not part of our common source.  Adding it to .gitignore helps avoid having it accidentally committed.
> .gitignore: Ignore /.gopathok

- conmon/conmon.c
CRI-O's server relies on this for creation attempts, but it can set the option.  `conmon` itself doesn't need to care one way or the other.  Perhaps it is being called by a process that doesn't care about the container exit code or has another way to access that information.  With this commit, we trust callers to set `--exit-dir` if they want it, instead of requiring non-exec callers to set it.
> conmon: Make --exit-dir optional

- conmon/conmon.c
Avoid:
```console
$ make clean && make conmon.o 2>&1
rm -f conmon.o cmsg.o ../bin/conmon
cc -std=c99 -Os -Wall -Wextra -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -DVERSION=\"1.9.0-dev\" -DGIT_COMMIT=\""74cd1ec97c13a9784ce5e67a9e50e8977b5d2f38"\"   -c -o conmon.o conmon.c
conmon.c: In function ‘main’:
conmon.c:1175:3: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
read(start_pipe_fd, buf, BUF_SIZE);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
by catching and exiting on any read errors.  A read error here would be because the caller died before writing to the start pipe, and we don't want to continue in those cases because it would reopen the cgroup race discussed in af4fbcd9 (#583).  af4fbcd9 is where this line originally …
> conmon: Respect start-pipe read errors

- server/server.go
Fixed a double close of a channel as reported here https://github.com/kubernetes-incubator/cri-o/pull/1345#issuecomment-369909740
> server: prevent double channel close

- hooks.md
This is a fairly thorough edit of the hook docs (which are mostly unchanged since #562).  The commits are mostly per-section rewrites, but I'm happy to squash/split/refactor if any particular change is (un)contentious.  Details for each set of changes in the commit messages.
I'd like to rework the hook configuration to more closely match the upstream structure (e.g. we do not expose `timeout`), but I'm leaving that alone for now.  This PR just tightens the docs for the current format.
> hooks: Copy-edits for the Markdown docs (RFC 2119, etc.)

- conmon/conmon.c
provided a way to launch a custom command once conmon terminates.
added two new options `--exit-command=COMMAND` and `--exit-command-arg=ARG_N`
If specified, the command $COMMAND [ARG_0] ... [[ARG_N] is launched.
conmon [...] --exit-command /usr/bin/runc \
--exit-command-arg delete \
--exit-command-arg $CONTAINER_UUID
deletes the runc container once conmon exits.
conmon allows to invoke a command on termination
> conmon: add new option to call cleanup program at exit

- lib/stop.go
- oci/oci.go
- server/sandbox_remove.go
- server/sandbox_stop.go
CRI-O works well with runc when stopping a container because as soon
as the container process returns, it can consider every container
resources such as its rootfs as being freed, and it can proceed
further by unmounting it.
But in case of virtualized runtime such as Clear Containers or Kata
Containers, the same rootfs is being mounted into the VM, usually as
a device being hotplugged. This means the runtime will need to be
triggered after the container process has returned. Particularly,
such runtimes should expect a call into "state" in order to realize
the container process is not running anymore, and it would trigger
the container to be officially stopped, proceeding to the necessary
unmounts.
The way this can be done from CRI-O, without impacting the case of
runc, is to explicitly …
> crio: Ensure container state is stopped when calling StopContainer()

- pkg/storage/image.go
- server/container_create.go
When the image name is resolved with the registries from crio.conf only
the resolved name with the first registry is passed to create_container
eventhough there are more registries in the crio.conf file.
Fix this to try the resolved image names with all the registries given in the conf file.
Fixes https://github.com/kubernetes-incubator/cri-o/issues/1396
> Fix create container failure due to wrong image reference

- pause/Makefile
Debug symbols are needed in distro-supplied debuginfo packages.
disabled binary stripping for pause
by removing the strip command from `pause/Makefile`.
generate pause binary with and without the change, compare both binaries.
pause: do not strip binary (needed by distro's debuginfo packages)
@runcom @mrunalp
> pause: do not strip binary

- .travis.yml
**What I did**
Some steps are now being run with Go tip and not in all the different versions,
there were also moved to their own block so they will fail fast and in the mean
time the unit test for the different versions can start.
Also, "make docs" was removed because it's already being done by "make" without
any argument.
**How to verify it**
- Check the Travis build on this PR.
**Description for the changelog**
_Remove duplication in Travis steps and make verifications of linters and git fail fast._
> Remove unneeded/repeated Travis steps

- Makefile
I tried building with cri-o checked out to a directory name other than `cri-o`, and it didn't build. This patch makes sure it gets linked into the correct directory on the gopath.
> Support src directory name other than cri-o

- conmon/cmsg.c
- conmon/conmon.c
Avoid:
```console
$ make clean && make CFLAGS=-Wpedantic 2>&1 | head -n 5
rm -f conmon.o cmsg.o ../bin/conmon
cc -Wpedantic -std=c99 -Os -Wall -Wextra -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -c -o conmon.o conmon.c
conmon.c: In function ‘write_k8s_log’:
conmon.c:342:33: warning: ISO C99 requires at least one argument for the "..." in a variadic macro
ninfo("Creating new log file");
^
```
by distinguishing between calls with and without user-supplied formatting.
Also remove some user-supplied newlines from the following
* `nwarn` for “Could not find newline in entire buffer”
* `ninfo` for “Got ctl message…”
* `ninfo` for “container %d exited with status…”
because the macros add their own trailing newlines.
Also replace the Glibc extention %m with %s and …
> conmon: Distinguish pexit(s) from pexitf(fmt, ...) and similar

- contrib/cni/10-crio-bridge.conf
- contrib/cni/99-loopback.conf
We've been seeing conflicts with other CNI consumers where CRI-O's configuration files are causing the CNI plugins to fail to start because their versions are too low. Upgrading the plugin versions should resolve this conflict, and not cause any adverse effect to a typical CRI-O install.
> Update CNI config versions to 0.3.0

- contrib/test/integration/README.md
- contrib/test/integration/system.yml
* Add an EPEL requirement to the ``contrib/test/integration/README.md``
* Double the rpm installation timeout
* With ``vim``
* Read the ``README.md``
* Execute the integration test playbook inside a slow-networking environment
> Fix two integration nits

- .travis.yml
- server/config_test.go
- server/sandbox_status.go
- server/sandbox_status_test.go
- server/utils_test.go
**What I did**
- I added version info in a JSON object to [this response](https://github.com/kubernetes/kubernetes/blob/c6ddc749e85f4281628f366d65cf924c22d6cd99/pkg/kubelet/apis/cri/v1alpha1/runtime/api.proto#L391) when [verbose is set to true here](https://github.com/kubernetes/kubernetes/blob/c6ddc749e85f4281628f366d65cf924c22d6cd99/pkg/kubelet/apis/cri/v1alpha1/runtime/api.proto#L335).
**How I did it**
- I added some tests to cover the functionality before changing it, these tests include some fixture that maybe could be good to move to some other place.
**How to verify it**
- The tests should be enough, but if that grpc endpoing can be easilly called it should return the version info in a JSON object.
If PodSandboxStatusRequest.Verbose is true now we are returning the cri-o
version in …
> Add extra info to verbose requests to PodSandboxStatus

- conmon/conmon.c
@rhatdan @runcom @giuseppe  PTAL
Added support for supporting reopening files via conmon ctl file.
Refactored to add helper functions for reopening log file, resizing tty size and handling
ctl messages to call reopen log file function.
This will be exercised in follow-on changes in CRI log re-open API.
> Conmon reopen log file support

- .travis.yml
- Makefile
- hack/seccomp_tag.sh
As an initial step in continuous integration testing for @vbatts' cross-platform work.  Once we get this passing on OS X we can remove the `allow_failures` entry.  The best docs I could find for using `allow_failures` with [build stages][0] was [here][1], so that's the pattern I'm following.  Travis' OS X docs are [here][3].
[0]: https://docs.travis-ci.com/user/build-stages/
[1]: https://github.com/travis-ci/travis-ci/issues/7789#issuecomment-303685412
[3]: https://docs.travis-ci.com/user/reference/osx
> .travis.yml: Add allowed-to-fail OS X compilation

- .gitignore
- cmd/crio/main.go
- conmon/Makefile
- conmon/config.go
- conmon/conmon.c
- oci/oci.go
- server/container_attach.go
This patch adds a little program config.go, which
outputs config.h based on the constants set in oci.go
This will make sure that conmon and crio use the same constants.
> Make conmon and crio share the same constants

- test/ctr.bats
- test/testdata/container_redis.json
Only require a single CPU to avoid failures on single-CPU systems. We could make this conditional, but it's Redis, which isn't particularly CPU intensive.  One CPU would probably be fine in production, and these are just integration tests.
Fixes #1397.
> test/testdata/container_redis.json: Set cpuset_cpus to 0

- utils/filesystem.go
This began as shuffling platform dependent code, but none of the functions were even used. This just removes it instead.
Still cross-platform ;-)
> utils: delete unused code

- oci/oci.go
We were incorrectly inheriting tty true from main container.
Fix #1433 
> container_exec: Fix terminal setting for exec

- conmon/conmon.c
Pass length as we already know it instead of
calling strlen in logging path.
> conmon: Avoid strlen in logging path

- README.md
- tutorial.md
While using the tutorial, noted a few missing pieces in the README.md and tutorial.md. Added changes to clear those up.
vi is my friend.
Install on a new VM and follow the tutorial.
Touch ups to the README.md and tutorial.md files.
> Add make install.tools to README.md and touch up tutorial

- conmon/conmon.c
runc supports checkpointing and restoring containers with the help of
CRIU. To checkpoint a container from podman it is enough to just call
runc to checkpoint the container. To restore a container with podman the
resulting container should again be under the control of conmon.
This extends conmon to be able to also restore a container.
Signed-off-by: Adrian Reber <areber@redhat.com>
> conmon: add support to restore a container

- README.md
- contrib/test/integration/node-e2e.yml
- kubernetes.md
Addressing deprecation warning
```
I0220 12:43:39.634359    2270 remote_runtime.go:43] Connecting to runtime service /var/run/crio/crio.sock
W0220 12:43:39.634394    2270 util_unix.go:75] Using "/var/run/crio/crio.sock" as endpoint is deprecated, please consider using full url format "unix:///var/run/crio/crio.sock".
```
Attempted to start Kubernetes based on the `./hack/local-up-cluster.sh` example in `README.md` and then investigated why I've got no `kubectl get nodes`.
```
PATH=/home/test/kubernetes/third_party/etcd:${PATH} CGROUP_DRIVER=systemd CONTAINER_RUNTIME=remote CONTAINER_RUNTIME_ENDPOINT='/var/run/crio/crio.sock  --runtime-request-timeout=15m' ./hack/local-up-cluster.sh
```
and then checked `/tmp/kubelet.log`.
The …
> Using "/var/run/crio/crio.sock" as endpoint is deprecated.

- contrib/test/integration/e2e.yml
- contrib/test/integration/node-e2e.yml
- contrib/test/integration/test.yml
All-else being equal, there should be as small a timeout as possible so we're not wasting engineer-time.  However, it needs to be long enough that tests don't fail due to minor/random hiccups.
* Added an async/poll statement to ``e2e.yml`` (was missing one)
* Updated all timeouts to be closer to reality (may still need tweaking)
* Async timeouts are specified in seconds, but since everybody isn't a math-wizz, I wrote out the formula as a jinja2 template.  That way normal people can easily make sense of it.
* All CI tests should pass.
> Tweak test timeouts to be readable + realistic

- contrib/test/integration/e2e.yml
- contrib/test/integration/node-e2e.yml
- contrib/test/integration/test.yml
- contrib/test/integration/vars.yml
Add a boolean variables that control whether or not SELinux is enabled during particular tests.
Used the Ansible ``block`` construct to group the SELinux-permissive task along with the test-task.  Utilized the ``always`` clause of the block to ensure SELinux-enforcing happens no matter what.
Execute all CI tests.  This change preserves existing behaviors.  In other PRs, as needed,  change ``vars.yml`` variables as to see what breaks:
```
integration_selinux_enabled: True
e2e_selinux_enabled: True
node_e2e_selinux_enabled: True
```
> Add ability to enable/disable SELinux during tests

- Dockerfile
- contrib/test/integration/main.yml
- pkg/storage/image.go
- server/container_reopen_log.go
Implemented container reopen log.
Added code to call conmon ctl file with the message to reopen log file.
crictl tests pass
> Reopen log file support

- server/container_exec.go
Adds the actual error reason to the error message returned when exec fails.
> Return error for container exec

- test/helpers.bash
If a subtest fails it might leave crio running; this prevents
bats from exiting, causing a hang. It also prevents cleanup of
the test directory because there's an active mount in it.
Solution: run stop_crio from within cleanup_test, just before
the rm -rf. This is safe because stop_crio checks for an active
crio pid.
> run stop_crio inside cleanup_test

- oci/oci.go
- pkg/findprocess/findprocess.go
- pkg/findprocess/findprocess_test.go
- pkg/findprocess/findprocess_unix.go
- pkg/findprocess/findprocess_windows.go
And use the new package for portable process-existence checks in the `oci` package, addressing that part of #1407's portability goals.
The traditional POSIX approach to detecting processes is to [`kill(pid, 0)` them and check for `ESRCH`][1].  However, Go's `os.Process` makes detecting that a bit awkward.
On Unix, [Go's `os.FindProcess` implementation always succeeds][2].  And [`os.Process`'s `Signal` translates `ESRCH`][3] to [an internal `errFinished`][4].  The Unix wrapper here rolls the `FindProcess` and `Signal(0)` calls together, and translates `os`'s `errFinished` to a public `ESRCH`.
On Windows, [`os.Process`'s `Signal` only supports kills][5], so we can't perform a check like [POSIX's `kill(pid, 0)`][1].  Instead, this commit assumes `os.FindProcess` will return errors on …
> pkg/findprocess: Add a new package for portable process detection

- contrib/test/integration/system.yml
There is a bug-fix in 7.5.0 which fixes containers access to cgroups on
the host, despite the default container_manage_cgroup == 0.  When
testing with 7.5.0 and later, this access will be blocked unless this
boolean is enabled.  
Since it's also required in Fedora, and there's no negative consequence
for using it in <= 7.4, simply enable it for all VMs.
With the ``seboolean`` Ansible module
Automated 'ami' tests should pass.  Bonous points if e2e passes after enabling SELinux.  Until then, manual testing is required :face_with_head_bandage: as per ``README.md``.
> Fix accidental positive side-effect of RHEL 7.4- bug

- CONTRIBUTING.md
Remove a dead “Becoming a Maintainer” link and that stub section, since CRI-O currently doesn't document that process.  By leaving it undocumented, maintainer changes falls back to the usual pull-request review process.
Link to `CODEOWNERS` and associated documentation so that folks can figure out what the usual pull-request processs is.  The “most” wiggle is because CRI-O seems to have not [required review from code owners][1], based on [GitHub's][2]:
> Review has been requested on this pull request. *It is not required to merge.*
wording.
[1]: https://help.github.com/articles/enabling-required-reviews-for-pull-requests/
[2]: https://github.com/kubernetes-incubator/cri-o/pull/1265
> CONTRIBUTING: Link to Prow OWNERS

- cmd/crio/config.go
- contrib/system_containers/centos/Dockerfile
- contrib/system_containers/fedora/Dockerfile
- contrib/system_containers/rhel/Dockerfile
- contrib/test/integration/build/cri-o.yml
- lib/config.go
- test/helpers.bash
Change the config to use github.com/containers/storage by default.
Allow users to override in the config, but if the admin does not
override the config.
> Default to the storage defaults

- Makefile
- conmon/Makefile
- pause/Makefile
With this change, we avoid needless rebuilds after a successful build:
```console
$ make binaries
…real build stuff…
$ make binaries
make -C conmon
make[1]: Entering directory '/home/wking/.local/lib/go/src/github.com/kubernetes-incubator/cri-o/conmon'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/wking/.local/lib/go/src/github.com/kubernetes-incubator/cri-o/conmon'
make -C pause
make[1]: Entering directory '/home/wking/.local/lib/go/src/github.com/kubernetes-incubator/cri-o/pause'
make[1]: '../bin/pause' is up to date.
make[1]: Leaving directory '/home/wking/.local/lib/go/src/github.com/kubernetes-incubator/cri-o/pause'
```
Previously `make binaries` would rebuild `conmon`, `pause`, and `crio` every time.
> Makefile: Avoid needless binary rebuilds

- conmon/Makefile
- pause/Makefile
Builds on #1458; review that first.
Avoid:
```console
$ rm -rf bin
$ make -C conmon
…
cc -o ../bin/conmon config.h conmon.o cmsg.o …
In file included from <command-line>:0:0:
/usr/include/stdc-predef.h:1:0: fatal error: can’t create precompiled
header ../bin/conmon: No such file or directory
…
```
by using an [order-only prerequisite][1] for the `bin` directory.  `mkdir -p dir` is [in POSIX][2].
[1]: https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html
[2]: http://pubs.opengroup.org/onlinepubs/9699919799/utilities/mkdir.html
> conmon/pause: Add order-only prereq for ../bin

- conmon/Makefile
- conmon/cmsg.c
- conmon/conmon.c
- pause/Makefile
`-std`, `-O`, and `-W` are all options that the caller should be able to set for themselves.  My personal preference is to drop these defaults (and leave it up to the compiler and system configuration to get reasonable defaults, #1361), but that approach [was not acceptable to the CRI-O maintainers][2].  This pull-request moves options that CRI-O doesn't really need into a fallback [`?=` definition][3].  The options that we do need stay in the [`override +=` append][4].  The main drawback to this approach (vs. dropping the `?=` definition default completely) is that a user setting, for example, `CFLAGS=-O2` will clobber our default `-std`, etc. values.  But I can't see a way around that besides the approach in #1361.
CC @rhatdan and @giuseppe, who both had opinions about #1361.
[2]: …
> conmon/pause: Allow user-specified CFLAGS

- lib/container_server.go
- lib/hooks.go
- server/server.go
Also rename `errNotJSON` to the public `ErrNoJSONSuffix`.  This allows us to push success/failure logging out into `server/server.go` which understands that it is not filtering for `.json` suffixes.  With this change, we no longer log noise when someone:
* Touches a non-`.json` path in the watched directories.
* Removes a non-hook path in the watched directories.
Addition now only results in a logged success or error; previously we'd log the “adding” attempt and possibly *also* log the hook-reading error.
This PR implements [this suggestion][1] from #1345; ping @runcom.
[1]: https://github.com/kubernetes-incubator/cri-o/pull/1345#discussion_r169433836
> *: Return err from AddHook and ok from RemoveHook

- lib/hooks.go
Lift the constraint added in ca940957 (#1345).  For example, you may want to limit a hook to one stage for an `annotations` match and another stage for a `cmd` match.  Using two files with the same hook entry is the only way to do that.
Spun off from [this comment][1]; cc @runcom.
[1]: https://github.com/kubernetes-incubator/cri-o/pull/1345/commits/ca940957390cc830fa609a5408e002faa9cdb794#r169433007
> lib/hooks: Allow the same command in multiple hook files

- CONTRIBUTING.md
I initially thought this file was about scoping review (see “[Require review from Code Owners][1]”), but @rhatdan pointed out that [only the Prow `OWNERS` matter for pull-request approval][2].  @mrunalp explained that [`CODEOWNERS was for managing notifications][3], so I'm documenting that here where it's more discoverable.
[1]: https://help.github.com/articles/enabling-required-reviews-for-pull-requests/
[2]: https://github.com/kubernetes-incubator/cri-o/pull/1272#discussion_r172746401
[3]: https://github.com/kubernetes-incubator/cri-o/pull/1272#issuecomment-373788087
> CONTRIBUTING: Explain .github/CODEOWNERS

- .travis.yml
- CONTRIBUTING.md
So users can check their pull requests locally without leaning on Travis.
Also configure Travis to run `fmt` instead of `gofmt`, taking advantage of the changes from #1460.
> CONTRIBUTING: Document test steps

- docs/crio.8.md
This PR fixes two (trivial) issues in the man page `doc/crio.8.md`. The first fix is the removal of double `--cpu-profile` command line option description and the second is fixing the bit broken alphabetical order of the command line options.
Updated the man page options.
> Fix crio man page bugs.

- conmon/conmon.c
added a new option--conmon-pidfile to conmon
accept a new option --conmon-pidfile=FILE and store the pid of the conmon process to the specified file.
add --conmon-pidfile=FILE to conmon and check that FILE is created and contains the PID of the conmon process
new option --conmon-pidfile to store the pid of conmon.
> conmon: new option --conmon-pidfile=

- contrib/test/integration/disable_swap.yml
- contrib/test/integration/main.yml
- contrib/test/integration/system.yml
fixes #1063
Removed old/disused swap setup which never persisted after creating AMIs.  Add a few late-stage tasks to disable both active and persistent swap.
Tasks added under ``post_tasks`` to suggest they should always happen at the last possible moment.  In case swap ever needs to be enabled prior to this point, for compiling purposes.
CI tests will catch any problems and/or reveal gaps in testing.
> Permanently disable swap prior to testing

- cmd/crio/config.go
- cmd/crio/main.go
- docs/crio.8.md
- docs/crio.conf.5.md
- lib/config.go
- server/container_create.go
Taking over @rhatdan PR https://github.com/kubernetes-incubator/cri-o/pull/1402/files
Add a read-only flag to the cri-o config.  This will force all containers
run on the system to run in readonly mode.  In order to make most containers
work this patch mounts a tmpfs on /run, /tmp and /var/tmp so that these directories can continue to be written to, but the rest of the file system will be
read-only.  If the container needs to write to other locations, then volumes
must be mounted into the container.
Running in read-only mode increases the container security, since a hacked
container will not be able to overwrite existing code.
> Add read-only flag

- .travis.yml
- Dockerfile
- README.md
- tutorial.md
As of opencontainers/runc@db093f6 runc no longer depends on libapparmor
thus libapparmor-dev no longer needs to be installed to build it or
anythind that depends on it (like cri-o). Adjust the documentation
accordingly.
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
> Drop libapparmor dependency from build docs

- cmd/crio/main.go
fixed a typo
sed -i -e 's|servier|server|' cmd/crio/main.go
no "servier" in crio --help
> conmon: fix typo servier->server

- oci/oci.go
We don't need to use the public getter from this same-package code.  This may save the cost of a function call (or maybe the Go compiler optimizes that out).  This exposes us to more maintenance work if we ever rename `Container.id`, but I don't expect us to do that.  And it makes us consistent with the many more `c.id` calls which are already in `oci.go`.
Spun off from [this comment][1].
[1]: https://github.com/kubernetes-incubator/cri-o/pull/1478#discussion_r178848481
> oci: Replace ‘c.ID()’ with ‘c.id’

- test/ctr.bats
When running BATS testing from ctr.bats, it works very well for
runc, but in case of Kata Containers, we can expect actions to
take longer time to be achieved. In the specific case of the test
"ctr /etc/resolv.conf rw/ro mode" from ctr.bats, we should not expect
the container state to be CONTAINER_EXITED right after the start
returned. Indeed, it might take some time for the container to exit
and the call to "crictl inspect $ctr_id --output table" should be
tried several times before we consider the output as failing.
This patch relies on the "ctr oom" test as an example of how to
implement this retry behavior.
Fixes #1488
Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>
> test: Fix race condition in ctr.bats

- README.md
- docs/crio.8.md
Add Configuraton file descriptions to README.md
Now we also have a man page for policy.json, so reference it in man page.
> Fix up config files description

- cmd/crio/main.go
- server/sandbox_status_test.go
- server/sandbox_stop.go
- server/server.go
Fixes #1490, avoiding:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x91b13f]
goroutine 1 [running]:
…
runtime.sigpanic()
/…/runtime/signal_unix.go:388 +0x17a fp=0xc42093a670 sp=0xc42093a620 pc=0x44816a
github.com/kubernetes-incubator/cri-o/oci.waitContainerStop(0x0, 0x0, 0xc4208a2140, 0x2540be400, 0x1873be0, 0xc42000e020)
/…/cri-o/oci/oci.go:589 +0xaf fp=0xc42093a7a0 sp=0xc42093a670 pc=0x91b13f
github.com/kubernetes-incubator/cri-o/oci.(*Runtime).StopContainer(0xc4205294a0, 0x0, 0x0, 0xc4208a2140, 0xa, 0x0, 0x0)
/…/cri-o/oci/oci.go:620 +0x57f fp=0xc42093a920 sp=0xc42093a7a0 pc=0x91b99f
github.com/kubernetes-incubator/cri-o/server.(*Server).StopPodSandbox(0xc4202dc000, 0x0, 0x0, 0xc4201e0fd0, 0x0, …
```
> server/sandbox_stop: Pass context through StopAllPodSandboxes

- contrib/systemd/crio-shutdown.service
We need to make sure the crio-shutdown file does not exist when the service
starts and then make sure the directory and file exist on shutdown.
The current version of this service script is blowing up.
> crio-shutdown.service was not working correctly

- server/container_reopen_log.go
> server: O_WRONLY is not unix only

- cmd/crio/config.go
- contrib/test/integration/build/cri-o.yml
- lib/config.go
- test/helpers.bash
- vendor.conf
- vendor/github.com/BurntSushi/toml/README.md
- vendor/github.com/BurntSushi/toml/decode.go
- vendor/github.com/BurntSushi/toml/decode_meta.go
- vendor/github.com/BurntSushi/toml/doc.go
- vendor/github.com/BurntSushi/toml/encode.go
- vendor/github.com/BurntSushi/toml/lex.go
- vendor/github.com/BurntSushi/toml/parse.go
- vendor/github.com/BurntSushi/toml/type_fields.go
- vendor/github.com/containers/image/pkg/sysregistries/system_registries.go
We want to share registries.conf configuration between all of the tools using
containers/image and then allow crio.conf to override if the user wants, not
to override by default.
> Don't override registries.conf by default

- cmd/crio/main.go
- server/sandbox_stop.go
- server/server.go
Backported from d3b76361 (#1494), fixing a trivial merge conflict in `cmd/crio/main.go`.
I haven't backported 28a0a53a9, because `server/sandbox_status_test.go` doesn't exist in the 1.9 branch.
> [release 1.9] server/sandbox_stop: Pass context through StopAllPodSandboxes

- conmon/conmon.c
added support in conmon for multiple ttys attached at the same time
Closes: #1481 
changed conmon to store an array of ttys instead of a single fd
```
```
and in another terminal:
```
```
What is written in one terminal is visible to the other.
conmon supports more than one attached tty at the same time.
> Conmon multiple attach

- cmd/crio/main.go
- docs/crio.8.md
- lib/config.go
- server/container_create.go
- server/secrets.go
Introduce a new config --bind-mount-prefix=PREFIX that adds a prefix
to the source for every bind mount.  This allows CRI-O to run inside
of a container, and be able to see the host rootfs.
Added a new option --bind-mount-prefix=PREFIX to specify a prefix for every bind mount.
If a bind mount PREFIX is specified, the source for each bind mount is prefixed with it
`# mkdir -p /host/foo`
`# touch /host/foo/bar`
`# crio --bind-mount-prefix=/host/host`
A mount from `/foo/bar` -> `/bar` is converted to `/host/foo/bar` -> `/bar`
New option --bind-mount-prefix=PREFIX to permit CRI-O in a container to get full access to the host rootfs
Marked as WIP …
> cri-o: allow a prefix for all bind mounts

- lib/container_server.go
Lift the constraint added in ca94095 (#1345).  For example, you may want to limit a hook to one stage for an annotations match and another stage for a cmd match.  Using two files with the same hook entry is the only way to do that.
This is very similar to dbd16413 (#1468), where I'd *attempted* to remove the constraint from ca94095, but actually ended up removing a very similar constraint which had been added in 139d0841 (#562).
CC @runcom, @rhatdan.
> lib/container_server: Allow the same command in multiple hook files

- test/image.bats
The registry has some issues. We can re-enable this once the issues are fixed.
@runcom @rhatdan @mtrmac PTAL
> test: Skip image pull with signature

- conmon/conmon.c
The options of conmon are parsed by using glib and the correct
type is gboolean and not bool.
On bigendian architectures as s390, the parsing to bool gives
wrong results.
Signed-off-by: Alice Frosi <afrosi@de.ibm.com>
I substitue `bool` with `gboolean` type in `conmon.c`
On s390 architecture the command `conmon --version` gave wrong output
```sh
conmon>../bin/conmon --version    
Container ID not provided. Use --cid
```
Now 
```sh
conmon>../bin/conmon --version
conmon version 1.10.0-dev
commit: f44ce261c715d28e6d39f433833f2a4ac2a14b1b
```
> Replace bool with gboolean

- contrib/test/integration/build/cri-o.yml
- test/ctr.bats
- test/default_mounts.bats
- test/helpers.bash
- test/image.bats
- test/image_remove.bats
- test/image_volume.bats
- test/inspect.bats
- test/policy.json
- test/registries.conf
- test/testdata/container_config.json
- test/testdata/container_config_hostport.json
- test/testdata/container_config_logging.json
- test/testdata/container_config_resolvconf.json
- test/testdata/container_config_resolvconf_ro.json
- test/testdata/container_config_seccomp.json
- test/testdata/container_config_sleep.json
- test/testdata/container_exit_test.json
- test/testdata/container_redis.json
- test/testdata/container_redis_default_mounts.json
- test/testdata/container_redis_device.json
- test/testdata/container_redis_env_custom.json
Created a crio organization account on quay.io and all images
used in the tests live under quay.io/crio now.
> Move cri-o test images to quay.io

- oci/oci.go
- server/runtime_status.go
We were wrongly reporting runtime as ready even when it wasn't. This
patch correctly checks the network plugin before replying with network
ready.
@mrunalp PTAL
> runtime_status: report correct network status

- lib/container_server.go
- lib/sandbox/sandbox.go
- pkg/annotations/annotations.go
- server/sandbox_run.go
- server/sandbox_status_test.go
After port ManageNetworkNSLifecycle from 1.9 branch the logic
was modified to not save the host network state from the sandbox.
This PR restore the logic to save if the sandbox host network. It saves if the sandbox is using network host-namespace. Then when a container is created `LoadSandbox` will check for the annotation to know if the sandbox where the container is created was using host NetworkNS.
Fixes: #1523
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>
> network: Fix manage NetworkNS lifecycle

- contrib/system_containers/centos/config.json.template
- contrib/system_containers/centos/run.sh
- contrib/system_containers/fedora/config.json.template
- contrib/system_containers/fedora/run.sh
- contrib/system_containers/rhel/config.json.template
- contrib/system_containers/rhel/run.sh
use --bind-mount-prefix for the system containers
hardcoded to the system container cmdline
build a CRI-O system container and be able to bind mount every directory from the host
> syscontainers: use --bind-mount-prefix

- cmd/crio/config.go
- cmd/crio/main.go
- contrib/test/integration/build/cri-o.yml
- lib/config.go
- server/container_create.go
- test/default_mounts.bats
- test/helpers.bash
- vendor.conf
- vendor/github.com/projectatomic/libpod/pkg/secrets/secrets.go
- vendor/github.com/projectatomic/libpod/pkg/secrets/secrets_test.go
Update cri-o to use the secrets package from libpod/pkg/secret,
which also brings in support for FIPS mode secret.
If the host is in FIPS mode (i.e /etc/system-fips exists) /run/secrets/system-fips
is created in the container so that the container can also run in FIPS mode.
> Add FIPS mode secret and vendor in libpod/pkg/secret

- server/container_create.go
- server/sandbox_run.go
- test/shm.bats
- test/testdata/container_sleep.json
>  Fix handling of /dev/shm mounting inside of containers 

- server/container_create.go
- server/sandbox_run.go
- test/image.bats
- test/shm.bats
- test/testdata/container_sleep.json
Add test to make sure /dev/shm is shared between containers in CRI-O
> Fix handling of /dev/shm mounting inside of containers

- server/container_create.go
- server/sandbox_run.go
- test/ctr.bats
Backport to 1.9 including the test.
@rhatdan @umohnani8 @runcom PTAL
> [1.9] Remove ambient capabilities

- oci/oci.go
- server/runtime_status.go
We were wrongly reporting runtime as ready even when it wasn't. This
patch correctly checks the network plugin before replying with network
ready.
> [release-1.9] runtime_status: report correct network status

- pkg/storage/image.go
Enhanced the error message we provide when pulling unqualified images w/o registries configured in `/etc/crio/crio.conf`. There have been questions around this in sig-node slack so better improving this.
vim
pull an unqualified image (`busybox`) w/o a registry configured, you should see the new error message
> pkg: storage: provide an hint when pulling w/o registries configured

- conmon/cmsg.c
Everytime we build conmon we get the following warnings.
STDERR:
---
cmsg.c: In function ‘sendfd’:
cmsg.c:58:9: warning: missing braces around initializer [-Wmissing-braces]
struct iovec iov[1] = {0};
^
cmsg.c:58:9: warning: (near initialization for ‘iov[0]’) [-Wmissing-braces]
cmsg.c: In function ‘recvfd’:
cmsg.c:104:9: warning: missing braces around initializer [-Wmissing-braces]
struct iovec iov[1] = {0};
^
cmsg.c:104:9: warning: (near initialization for ‘iov[0]’) [-Wmissing-braces]
This patch fixes these warnings.
> Fix c compiler warning

- server/inspect.go
- test/ctr_userns.bats
- types/types.go
add information about the ID mappings used for the containers.
Added information about the UIDs/GIDs mappings to the /info endpoint
Added a new field to the JSON output
echo -e "GET /info HTTP/1.1\r\nHost: crio\r\n" | sudo socat - UNIX-CONNECT:/PATH/TO/crio.sock
nothing, it is a followup for https://github.com/kubernetes-incubator/cri-o/pull/1562
> info: add information about ID mappings

- contrib/test/integration/system.yml
Ran AMI-build test with Fedora, playbook encountered encountered this error:
```
TASK [Containers using cgroups and/or systemd after 7.5 are permitted] *********
task path: /go/src/github.com/kubernetes-incubator/cri-o/contrib/test/integration/system.yml:130
fatal: [localhost]: FAILED! => {
"changed": false
}
MSG:
---
This module requires libsemanage-python support
```
Including the necessary RPM in the packages-to-install list.
/test ami_fedora will pass
> WIP: Fix missing ansible dependency

- conmon/conmon.c
The last `CMD_SIZE` consumers were removed by 6df58df2 (#289).
The last `MAX_EVENTS` consumers were removed by 4494d82c (#571).
> conmon: Remove unused CMD_SIZE and MAX_EVENTS

- contrib/system_containers/centos/run.sh
- contrib/system_containers/fedora/run.sh
- contrib/system_containers/rhel/run.sh
export *_PROXY variables in the system container after https://github.com/openshift/openshift-ansible/pull/8615
Installing the system container with the openshift-ansible installer has *_PROXY variables set
> Fix syscontainer proxy export

- Makefile
From [the GNU Make docs][1]:
> Recursive make commands should always use the variable `MAKE`, not the explicit command name `make`...
[1]: https://www.gnu.org/software/make/manual/html_node/MAKE-Variable.html
> Makefile: Transition from 'make' to $(MAKE)

- Dockerfile
- contrib/test/integration/build/plugins.yml
- server/sandbox_network.go
- test/cni_plugin_helper.bash
- test/helpers.bash
- test/network.bats
If the CNI network plugin completes successfully, but something fails
between that success and CRIO's sandbox setup code, plugin resources
may not be cleaned up.  A non-trivial amount of code runs after the
plugin itself exits and ocicni's SetUpPod() returns, and any error
condition recognized by that code would cause this leakage.
The Kubernetes CRI RunPodSandbox() request does not attempt to clean
up on errors, since it cannot know how much (if any) networking
was actually set up.  It depends on the CRI implementation to do
that cleanup for it.
Concrete examples include if the sandbox's container is somehow
removed during during that time, or another OS error is encountered,
or the plugin returns a malformed result to ocicni.
ref: https://bugzilla.redhat.com/show_bug.cgi?id=1532965 …
> server/sandbox: clean up network even if networkStart() fails

- .travis.yml
The separate stage is from 4964bd9d (#1578), but using a separate stage meant that Travis serialized these slow (20+ minute) stages.  By flattening into one stage we can run these in parallel (modulo Travis worker availability) and get the Travis results earlier.
I've shifted the `TEST_USERNS` declaration into an `env` property so it shows up in the Travis UI (e.g. [here][1]).
[1]: https://travis-ci.org/kubernetes-incubator/cri-o/builds/388442789
> .travis.yml: One stage for integration tests (userns and otherwise)

- .travis.yml
I'd missed this in f06674b9 (#1428).  Without the `$`, OSTree was never being compiled, even on Linux.
> .travis.yml: Add missing $ to OSTree guard

- Dockerfile
- contrib/test/integration/build/plugins.yml
- server/sandbox_network.go
- test/cni_plugin_helper.bash
- test/helpers.bash
- test/network.bats
The list of capabilities to be added can be defined in
/etc/crio/crio.conf.
Cherry-pick the changes made to the testdata for pid namespace sharing.
Cherry-pick the changes made to move the cri-o test images to quay.io/crio.
> [1.10] server/sandbox: clean up network even if networkStart() fails

- oci/oci.go
- server/runtime_status.go
We were wrongly reporting runtime as ready even when it wasn't. This
patch correctly checks the network plugin before replying with network
ready.
> [release-1.10] runtime_status: report correct network status

- cmd/crio/config.go
- server/config.go
- server/server.go
Signed-off-by: Nathan Sweet <nathanjsweet@gmail.com>
fixes: #1582 
Add Dyanmic TLS Configuration for the streaming server. Optional CA verification is added, though kubernetes doesn't seem to be requesting the streaming server with a client cert, the option is there to add it.
I simply added a TLSConfig object to stream server config object, that implements GetConfigForClient method.
Start crio, add the `tls_streaming`, `tls_cert`, and `tls_key` options, using the kubelet cert and key for testing. The kube-apiserver also needs to have the CA set that also signed these certs.
Added TLS Encryption to the streaming server
> Add dynamic TLS Configuration for the streaming server

- conmon/conmon.c
backport of https://github.com/kubernetes-incubator/cri-o/pull/1606
> [release-1.10] conmon: fix incorrect log line on a log refresh

- conmon/conmon.c
Backport to 1.10
@runcom @giuseppe
> [1.10] conmon: on a flush error discard the iov buffer

- server/container_create.go
- server/sandbox_run.go
> server: fix race between container create and cadvisor asking for info

- .travis.yml
- server/container_create.go
- server/sandbox_run.go
We create (and run) the containers before adding their info in memory.
Cadvisor queries our /containers/{id} info endpoint as soon as cgroups
show up on the system. That means there's a race between cgroups
creation and info available in memory in CRI-O.
Fix this race by putting containers info in memory prior to actually
creawting the containers with the runtime.
Tested on kube 1.10, I'm not able to reproduce the following error in
kubelet.log:
Failed to process watch event {EventType:0
Name:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod5b7ccb19_6f87_11e8_86dd_0eb037b2774e.slice/crio-e6ccc38071c3b403accd153c11775f7fd933305f31b551d4b6c6597692ce777d.scope
WatchSource:0}: invalid character 'c' looking for beginning of value
The "invalid character 'c' looking for beginning …
> [release-1.9] server: fix race between container create and cadvisor asking for info

- server/container_create.go
We were wrongly setting "shared" to the label.Relabel call when
relabeling mounts.
Basically, we need to pass the equivalent to ":Z" in docker when
setting up and labeling mounts. That's provided by the CRI
"SelinuxRelabel" field. However, even if we checked that field, we were
wrongly setting shared (":z") which automatically sets label to just "s0".
This patch fixes the above by using shared=false when relabeling so
that a full Chcon is performed with the full label.
> container_create: correctly relabel mounts when asked

- conmon/conmon.c
- oci/oci.go
Fixes #1604 
@runcom @rhatdan @giuseppe PTAL
Made logging to syslog optional.
Added a --syslog flag to conmon.
We don't see double logging while using systemd cgroups.
Add a --syslog flag to conmon.
> Make logging to syslog optional

- server/container_create.go
We were wrongly setting "shared" to the label.Relabel call when
relabeling mounts.
Basically, we need to pass the equivalent to ":Z" in docker when
setting up and labeling mounts. That's provided by the CRI
"SelinuxRelabel" field. However, even if we checked that field, we were
wrongly setting shared (":z") which automatically sets label to just "s0".
This patch fixes the above by using shared=false when relabeling so
that a full Chcon is performed with the full label.
> [release-1.10] container_create: correctly relabel mounts when asked

- server/container_create.go
- server/sandbox_run.go
We create (and run) the containers before adding their info in memory.
Cadvisor queries our /containers/{id} info endpoint as soon as cgroups
show up on the system. That means there's a race between cgroups
creation and info available in memory in CRI-O.
Fix this race by putting containers info in memory prior to actually
creawting the containers with the runtime.
Tested on kube 1.10, I'm not able to reproduce the following error in
kubelet.log:
Failed to process watch event {EventType:0
Name:/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod5b7ccb19_6f87_11e8_86dd_0eb037b2774e.slice/crio-e6ccc38071c3b403accd153c11775f7fd933305f31b551d4b6c6597692ce777d.scope
WatchSource:0}: invalid character 'c' looking for beginning of value
The "invalid character 'c' looking for beginning …
> [release-1.10] server: fix race between container create and cadvisor asking for info

- test/helpers.bash
lvm_cleanup function is used for testing CRI-O
with devicemapper driver.
This should fix the errors on the Kata Containers CI.
> [release-1.10] Port lvm_cleanup from master branch

- conmon/conmon.c
When timezones use non-integer-hour offsets, we could potentially generate too-long timestamps that would not fit in the timestamp buffer.
Fixes #1635
> Fix Conmon timestamps with non-integer-hour offsets

- tutorial.md
I corrected the wrong export command and the env variable name for the crictl tool.
> Fix typo in crictl environment variable export

- lib/container_server.go
- lib/sandbox/sandbox.go
- pkg/annotations/annotations.go
- server/sandbox_run.go
- server/sandbox_status_test.go
This is a port to the release-1.10 branch. Original PR was 
https://github.com/kubernetes-incubator/cri-o/pull/1524
After port ManageNetworkNSLifecycle from 1.9 branch the logic
was modified to not save the host network state from the sandbox.
This commit restore the logic to save if the sandbox host network. It saves
if the sandbox is using network host-namespace. Then when a container is
created LoadSandbox will check for the annotation to know if the sandbox
where the container is created was using host NetworkNS.
was modified to not save the hostnetwork state from the sandbox.
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>
> [release 1.10] network: Fix manage NetworkNS lifecycle

- conmon/conmon.c
fixed an error where the exit command was launched with an empty environment
leaving the original env from conmon
https://github.com/projectatomic/libpod/pull/942 works
the exit command launched by conmon has a valid environment
> conmon: do not use an empty env when running the exit command

- contrib/system_containers/centos/Dockerfile
update the repository used by the system container to find the RPM for CentOS.
> system-container: change repo for CentOS

- cmd/crio/selinux_unsupported.go
- conmon/conmon.c
- oci/oci.go
- oci/oci_linux.go
- pkg/storage/runtime.go
- server/container_attach.go
- server/container_create.go
- server/container_reopen_log.go
Changed the Info logs to Debug logs so that it is only
logged if an error occurs or if the log-level is set to debug.
In conmon, only log container status if it is non-zero and removed
the "about to waitpid" logs.
Also only drain stdout and stderr if a timeout does not occur.
> [1.11] Reduce amount of logs being printed by default

- cmd/crio/selinux_unsupported.go
- conmon/conmon.c
- oci/oci.go
- oci/oci_linux.go
- pkg/storage/runtime.go
- server/container_attach.go
- server/container_create.go
- server/container_reopen_log.go
Changed the Info logs to Debug logs so that it is only
logged if an error occurs or if the log-level is set to debug.
In conmon, only log container status if it is non-zero and removed
the "about to waitpid" logs.
Also only drain stdout and stderr if a timeout does not occur.
> Reduce amount of logs being printed by default

- test/ctr.bats
- test/helpers.bash
Starting a container and then stoping it right away can
be racy in some slow environments.
Add a sleep of 5 seconds to let the process finish correctly
before stoping the container.
> tests: Add timeout before stop container.

- test/ctr.bats
- test/helpers.bash
Starting a container and then stopping it right away can
be racy in some slow environments.
Implement a function to poll the status of the container
for a maximum of 100 seconds to let the container finish
its process and exit instead of stopping it.
> [release-1.11] tests: Add timeout before remove container

- test/ctr.bats
- test/helpers.bash
release-1.10 - tests: Add timeout before stop container.
Starting a container and then stopping it right away can
be racy in some slow environments.
Implement a function to poll the status of the container
for a maximum of 100 seconds to let the container finish
its process and exit before stopping it.
> [release-1.10] tests: Add timeout before stop container.

- Makefile
It turns out that using patterns as `.PHONY` prerequisites doesn't work as expected.  With this commit, I define a new `.explicit_phony` target and use it as a prerequisite to force rebuilds for phony pattern rules, as suggested [here][1].
[1]: https://stackoverflow.com/a/38803814
> Makefile: Add .explicit_phony target for bin/crio.cross.%

- version/version.go
@runcom @rhatdan PTAL
We missed the log reduce patch in 1.10.4 so need to cut another release.
> Release v1.10.5

- lib/container_server.go
- server/container_create.go
- server/sandbox_run.go
Keep only one copy of config.json under /run
and store the container state there as well.
Removed extra copy of config.json
Removed the call to save it under /var/lib/containers
There is only one copy of config.json on disk for the container. Tests pass.
`Save only copy of config.json`
> server: Don't make additional copy of config.json

- lib/container_server.go
- server/container_create.go
- server/sandbox_run.go
Keep only one copy of config.json under /run
and store the container state there as well.
> [1.11] server: Don't make additional copy of config.json

- server/container_create.go
> Block use of /proc/acpi from inside containers

- test/ctr.bats
- test/helpers.bash
Change wait_until_exit function to now also
receive the expected exit status, this way we
can wait for containers that we know will fail.
Which is the case of test #3 of ctr.bats.
Also change sleeps use wait_until_exit on test #2
and #3.
> tests: remove more sleeps from ctr.bats

- server/container_create.go
[From Justin Cormack][1]:
> This leaks information about keyrings on the host.  Keyrings are not namespaced.
CC @runcom.
[1]: https://github.com/moby/moby/pull/36368#issue-170520321
> server/container_create: Mask /proc/keys

- test/ctr.bats
- test/helpers.bash
Change wait_until_exit function to now also
receive the expected exit status, this way we
can wait for containers that we know will fail.
Which is the case of test #3 of ctr.bats.
Also change sleeps use wait_until_exit on test #2
and #3.
> [release-1.11] tests: remove more sleeps from ctr.bats

- server/inspect.go
Currently cri-o will not build on 32 bit systems.
> 4294967295 does not fit in an int on 32 bit systems

- server/inspect.go
Currently cri-o will not build on 32 bit systems.
> [1.11] 4294967295 does not fit in an int on 32 bit systems

- server/container_create.go
server/container_create: mask /proc/{acpi,keys}
Cherry-picked-by: Valentin Rothberg <vrothberg@suse.com>
Cherry-pick of commit 2bf6b3ced6d3b544aa6609de7712a897eecc2152.
Cc: @runcom
> server/container_create: mask /proc/{acpi,keys}

- .travis.yml
- lib/container_server.go
- server/container_create.go
- server/container_list.go
- server/container_stats_list.go
- server/sandbox_list.go
- server/server.go
- test/ctr.bats
- test/helpers.bash
Change wait_until_exit function to now also
receive the expected exit status, this way we
can wait for containers that we know will fail.
Which is the case of test #3 of ctr.bats.
Also change sleeps use wait_until_exit on test #2
and #3.
> [release-1.10] tests: remove more sleeps from ctr.bats

- test/ctr.bats
- test/helpers.bash
This commit adds the cleanup_lvm function that needs
to be present to run the tests using devicemapper driver.
It also changes some of the sleeps in the ctr.bats for
the new wait_until_exit function.
> [release 1.9] Fix tests for kata CI

- tutorial.md
The tutorial shows how to create the crio service file
but it has --log-level debug, which is wrong. Should pick
up the log-level from the crio.conf file.
> Remove "--log-level debug" from service file

- oci/oci.go
Submitted this PR which removes the "if priv" clause when we are handling a container which is marked with an untrusted annotation.
vi
:109
d6d
esc
:wq
Started a k8s cluster with CRIO running with this patch applied.  Started a privileged and untrusted container and verified that it used my untrusted-runtime (kata).  Verified all of the VM's device nodes are available to the container.
Prior to this patch, the trusted runtime (ie, runc) was used if the
container was privileged, even if the workload was explicitly marked
untrusted and an untrusted runtime (kata, for example) was provided.
This patch will follow the explicit annotation, since there are cases where
privileged container is desired …
> oci: update privilege/trust handling

- server/container_create.go
We were just logging the fact that the capability provided by kube was
invalid. We need to error out (according to this bz as well
https://bugzilla.redhat.com/show_bug.cgi?id=1608814). I'm going to add
a test in the critest suite, not here as the capability is coming from
the kube pod definition.
> [release-1.11] server/container_create: error out if capability is unknown

- server/container_create.go
> [release-1.10] server/container_create: error out if capability is unknown

- server/container_create.go
We were just logging the fact that the capability provided by kube was
invalid. We need to error out (according to this bz as well
https://bugzilla.redhat.com/show_bug.cgi?id=1608814). I'm going to add
a test in the critest suite, not here as the capability is coming from
the kube pod definition.
> server/container_create: error out if capability is unknown

- test/helpers.bash
This change adds the possibility to change the default
stream_port where cri-o listens.
> tests: Add the possibility to change stream_port

- cmd/crio/config.go
- cmd/crio/main.go
- conmon/conmon.c
- docs/crio.8.md
- docs/crio.conf.5.md
- lib/config.go
- oci/oci.go
- tutorial.md
conmon now has a --log-level flag that changes
the verbosity of the logs based on the value it
is set to. From logrus, panic(0), fatal(1), error(2) tells
conmon to print all pexit and nexit logs (this
is the default). warn(3) adds the nwarn logs, info(4)
adds the ninfo logs, and finally debug(5) adds the ndebug
logs as well.
Adds a log_level field in the crio.conf that can have the
following options: panic, fatal, error, warn, info, and debug.
Changes default from info to error.
> [1.10] Add log-level option to conmon and crio.conf

- server/container_create.go
- test/testdata/container_config.json
- test/testdata/container_config_by_imageid.json
- test/testdata/container_config_hostport.json
- test/testdata/container_config_logging.json
- test/testdata/container_config_resolvconf.json
- test/testdata/container_config_resolvconf_ro.json
- test/testdata/container_config_seccomp.json
- test/testdata/container_config_sleep.json
- test/testdata/container_redis_default_mounts.json
- test/testdata/container_redis_device.json
- test/testdata/container_sleep.json
- test/testdata/template_container_config.json
We set a minimum limit of 4MB. Lower values could result
in container failing to start.
> [1.11] container_create: Set a minimum memory limit

- conmon/conmon.c
fix crash in conmon
add a check when --log-level is not specified
conmon without --log-level works as before
> conmon: fix segfault when --log-level is not specified

- pkg/apparmor/apparmor_supported.go
Fix AppArmor builds by using text/template as the previously referenced
on from docker/docker doesn't exist.
Signed-off-by: Valentin Rothberg <vrothberg@suse.com>
> Fix AppArmor build

- server/container_create.go
We found an issue with mounting of user images inside of a
Image Volume.  The mount point was leaked to the host, since
the default for mountpoint is shared, this can cause container
cleanup to fail.  We should default to private.
> Image Volumes should be bind mounted as private

- server/container_create_linux.go
- test/testdata/container_config.json
- test/testdata/container_config_by_imageid.json
- test/testdata/container_config_hostport.json
- test/testdata/container_config_logging.json
- test/testdata/container_config_resolvconf.json
- test/testdata/container_config_resolvconf_ro.json
- test/testdata/container_config_seccomp.json
- test/testdata/container_config_sleep.json
- test/testdata/container_redis_default_mounts.json
- test/testdata/container_redis_device.json
- test/testdata/container_sleep.json
- test/testdata/template_container_config.json
We set a minimum limit of 4MB. Lower values could result
in container failing to start.
> container_create: Set a minimum memory limit

- pkg/apparmor/apparmor_supported.go
Fix AppArmor builds by using text/template as the previously referenced
on from docker/docker doesn't exist.
Signed-off-by: Valentin Rothberg <vrothberg@suse.com>
> cherry-pick commit 73b6901403 ("Fix AppArmor build")

- lib/container_server.go
- server/container_create_linux.go
- server/sandbox_run_linux.go
we need to store the configuration under /var/lib as /run doesn't
survive a reboot.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1613938
reverted 9699d24a09367e240bce3073435ef333a71f6da7
manually did it as some files were renamed and git revert failed
restart a node and containers start succesfully
fix an issue where containers don't startup after a reboot.
> crio: revert 9699d24a09367e240bce3073435ef333a71f6da7

- cmd/crio/config.go
- lib/config.go
- lib/container_server.go
- oci/oci.go
- oci/oci_linux.go
- server/container_attach.go
- server/container_create_linux.go
- server/rootless.go
- server/sandbox_run_linux.go
- server/server.go
fixed some issues to allow CRI-O running in an user namespace
Allow to configure all directories used by CRI-O
create a namespace, and run CRI-O with a configuration file where all directories are writeable by the user
> basic support for running in an user namespace

- cmd/crio/config.go
- lib/config.go
- lib/container_server.go
- lib/stop.go
- lib/testdata/config.toml
- oci/oci.go
- server/fixtures/crio.conf
- server/sandbox_remove.go
- server/sandbox_stop_linux.go
A minimal timeout is required when waiting for the container
termination since runtimes like Kata Containers might take more
time than standard runc.
This commit introduces a minimal timeout value that will ensure
a proper amount of time will be waited before to issue a timeout.
Fixes #1695
Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>
> oci: Define a minimal timeout for WaitContainerStateStopped()

- server/server.go
no harm in ignoring this error, it comes from the underlying kube
stream server and we have no power on it as we don't own the listener
(containerd/cri also ignores it)
> server: ignore server closed error

- contrib/test/integration/README.md
- contrib/test/integration/main.yml
- contrib/test/integration/test.yml
- contrib/test/integration/vars.yml
* Added a new tag to enables running the integration tests with usernamespaces.
* Updated the README.md regarding the new ``userns`` tag.
* Improved the [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment)-ness of the integration test command-line and environment variables.
* Minor: Removed two unnecessary and disused files.
Leverage the ``environment`` task argument for passing in a dictionary of environment variables to be used.  Define the test-command, and two sets of environment variables in the ``vars.yml`` file.  When the ``userns`` tag is specified in addition to the ``integration`` tag, the two env. var. dictionaries will be combined, enabling usernamespace testing by the test command.
Utilize some jinja2 template logic to …
> CRI-O Integration testing with userns enabled

- cmd/crio/config.go
- docs/crio.conf.5.md
Update the crio.conf(5) manpage to reflect the latest state of CLI flags
and configuration options.  Also reflect those changes in crio-config.
Fixes: #1747
Signed-off-by: Valentin Rothberg <vrothberg@suse.com>
> crio.conf(5): update manpage to the latest state

- docs/crio.8.md
Signed-off-by: Klaas Demter <Klaas-@users.noreply.github.com>
change default storage driver to point to correct driver
simple doc change
check diff
fix manpage to point to correct default storage driver
> Fix manpage to correctly state default storage driver

- contrib/test/integration/golang.yml
We need to keep the old directory for the other branches in the base image.
@runcom  PTAL
> test: Add directory for kubernetes-sigs

- Dockerfile
- contrib/test/integration/build/bats.yml
- contrib/test/integration/critest.yml
- contrib/test/integration/e2e.yml
- contrib/test/integration/golang.yml
- contrib/test/integration/main.yml
- pkg/storage/image.go
- server/container_list.go
- server/container_status.go
- server/image_pull.go
- server/sandbox_list.go
- server/sandbox_run.go
- test/README.md
- vendor/github.com/containers/libpod/README.md
- vendor/github.com/containers/libpod/pkg/hooks/0.1.0/hook.go
we don't run any serial test so it's ok to move to parallel to speed up
test time. You can check no serial in
https://openshift-gce-devel.appspot.com/build/origin-federated-results/pr-logs/pull/kubernetes-incubator_cri-o/1715/test_pull_request_crio_e2e_fedora/1171/
> contrib: test: run e2e in parallel

- pkg/annotations/annotations.go
- server/sandbox_network.go
- server/sandbox_run_linux.go
OCI runtimes may be interested in the results from CNI plugin.
Certain CNI plugins may choose to send out additional information.
Make this information available to the OCI runtime as an annotation.
Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>
> cni: Add CNI result JSON as an annotation

- server/sandbox_run.go
If the CNI setup fails in runPodSandbox, the infra container started is
not stopped/removed and leaks.
Ensure the necessary clean-up steps are executed on error
path.
Fixes: #1816
> [release-1.11] runPodSandbox: clean up containers on error path

- server/container_create_linux.go
Need to do this in the runtime as k8s doesn't allow
arbitrary mount options to be passed in for bind mounts.
Fixes vulnerability issue.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1627633
> Add nodev to options of bind mounts from kube

- lib/container_server.go
Calls to logrus.Debugf() in lib/container.go are missing an argument in the
format string.
Go 1.11 catches the error, previous versions apparently allowed it to compile.
There is a fix on master in commit 0bd3087 that is part of a larger commit.
This commit backports the change to fix compilation with go 1.11 to branch
release-1.11.
> Add missing argument to logrus.Debugf() format string

- cmd/crio/main.go
- utils/utils.go
@runcom @umohnani8 @rhatdan PTAL
> Add support for writing stacks with SIGUSR1

- cmd/crio/config.go
- cmd/crio/main.go
- lib/config.go
- server/container_create_linux.go
- server/sandbox_run_linux.go
- server/utils.go
- test/command.bats
- test/ctr.bats
- test/helpers.bash
> [release-1.12] *: implement default ulimits for containers

- oci/oci.go
#1833 for master @runcom PTAL
Killing the main container process should kill the other processes
in the pid namespace. For the shared case, the shared pid 1 would
reap the processes and remaining would be kiled when it is killed
> Don't use runc kill -all

- server/container_create.go
> BACKPORT: Add nodev to options of bind mounts from kube

- Makefile
@runcom Getting this in first to unblock CI. The other fixes in #1860 can come later.
> Fix release-tool 

- docs/crio.8.md
Since 43bc359fc024d57e628467d72cb6e5a8bba40bf1 cri-o has --enable-metrics and --metrics-port options but these are not listed in the man page. Add them.
> Add --enable-metrics and --metrics-port to man page.

- conmon/conmon.c
address a corner case where the symlink path length can end up to be
the same as the socket.  When it happens, the symlink prevents the
socket to be be created.  This could still be a problem with other
containers, but it is safe to assume the CUUIDs don't change length in
the same directory.  As a workaround, in such case, make the symlink
one char shorter.
> conmon: fix case when symlink == max UNIX socket path

- server/container_create.go
- server/container_create_linux.go
- server/container_create_linux_test.go
- fix #1881 
- made sure we don't add mounts in /dev where not needed
- removed nodev from every mount (I don't even remember why we did that but doesn't look right and could have caused the recent issues in kata as well
vi
the kata job in the CI should cover this scenario and if it passes, then it's verified.
> container_create: fix dev mounts and remove nodev from every mount

- pkg/storage/runtime.go
Due to a change in containers/storage, we need to force umount the
storage of a container to get back to previous behavior.
Conversation happened here: https://github.com/kubernetes-sigs/cri-o/issues/1883#issuecomment-436662573
Fix https://github.com/kubernetes-sigs/cri-o/issues/1883
> pkg/storage: force unmounts

- conmon/conmon.c
When a tty is used, conmon fails to report back the errors from the
OCI runtime as it fails too early on accessing the tty.  Change it to
print only a warning for not accessing the tty and fail later on after
all the errors are reported back.
> conmon: report runtime errors when tty is used

- pkg/storage/image.go
The context here (in imageConfigDigest) is to allow request canceling. The context in GetManifest interface is also to allow request canceling. These two just need to be wired together.
> Cancell imageConfigDigest allong all other requests from ImageService

- server/container_create_linux.go
We need the ability to create overlayfs in empty dir volumes
and support similar use cases.
> [1.12] Remove nodev from mounts

- server/container_create.go
We need the ability to create overlayfs in empty dir volumes
and support similar use cases.
> [release-1.11] Remove nodev from mounts

- version/version.go
We'll wait till #1905 is merged, rebase, get this in and tag the new release ready to be rebuild
I'll tag https://github.com/kubernetes-sigs/cri-o/pull/1907/commits/aa87e49ab46d846cc78550dcf127f0d053a63912 as `v1.11.9`
> Bump 1.11.9

- conmon/conmon.c
Do not use full width of buf, as we intend to assign
buf[num_read] = '\0';
at the end of the buffer, afterwards. In case we have just read full BUF_SIZE,
we will write '\0' to a memory location that is outside of buf. This can be
referred to as CWE-119 although, it seems pretty harmless in this case.
Signed-off-by: Šimon Lukašík <isimluk@fedoraproject.org>
> Do not overflow local buffer

- server/container_create_linux.go
We need the ability to create overlayfs in empty dir volumes
and support similar use cases.
> Remove nodev from mounts

- contrib/sysconfig/crio
- contrib/systemd/crio.service
Adapt our unit file so that metrics options can be defined.
Starting crio with --enable-metrics exposes Prometheus-compatible metrics.
Sample /etc/sysconfig-metrics file:
~~~
CRIO_METRICS_OPTIONS=
~~~
Verifying that crio starts with metrics can be done with netstat:
~~~
tcp6       0      0 :::9090                 :::*                    LISTEN      0          8473135    15496/crio 
~~~
Signed-off-by: François Cami <fcami@fedoraproject.org>
> systemd: add support for a crio-metrics sysconfig file.

- vendor.conf
- vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
inherit a change for not failing a recursive relabelling if the file
is removed between the directory is read and the lsetxattr syscall.
> vendor: update selinux

- vendor.conf
It isn't being used or vendored
> vendor: Remove reference to github.com/juju/ratelimit

- cmd/crio/config.go
- cmd/crio/main.go
- docs/crio.8.md
- docs/crio.conf.5.md
- lib/config.go
- lib/container_server.go
- lib/testdata/config.toml
- test/helpers.bash
The previous approach was breaking when [the default hook directory was missing][1]:
```
crio[15828]: level=debug msg="reading hooks from /usr/share/containers/oci/hooks.d"
crio[15828]: level=debug msg="added hook /usr/share/containers/oci/hooks.d/test.json"
crio[15828]: level=debug msg="reading hooks from /etc/containers/oci/hooks.d"
crio[15828]: level=warning msg="failed to load hooks: open /etc/containers/oci/hooks.d: no such file or directory"
```
With this commit, I've deprecated the implicit defaults in favor of having users explicitly configure their hook directories (either via `--hooks-dir` on the command line or `hooks_dir` in their config file).  This is similar to the recent containers/libpod@a4b483c8 (containers/libpod#1920).
Different from the libpod implementation is that …
> lib/container_server: Deprecate implicit hook directories

- contrib/test/integration/main.yml
- version/version.go
- track 1.13 kube release for e2e
- bump to 1.13.0
I will tag 1.13.0 afterwards with release notes
@mrunalp PTAL
> release v1.13.0

- lib/container_server.go
- server/sandbox_stop.go
backport of https://github.com/kubernetes-sigs/cri-o/pull/1944
> [release-1.11] Fix segfault on network failure

- lib/container_server.go
- server/sandbox_stop_linux.go
backport of https://github.com/kubernetes-sigs/cri-o/pull/1944
> [release-1.12] Fix segfault on network failure

- lib/container_server.go
github.com/kubernetes-sigs/cri-o/lib/sandbox.(*Sandbox).RemoveContainer(0x0, 0xc00071b380)
/gopath/src/github.com/kubernetes-sigs/cri-o/lib/sandbox/sandbox.go:319 +0x22
github.com/kubernetes-sigs/cri-o/lib.(*ContainerServer).RemoveContainer(0xc0004dff40, 0xc00071b380)
/gopath/src/github.com/kubernetes-sigs/cri-o/lib/container_server.go:701 +0x6e
github.com/kubernetes-sigs/cri-o/server.(*Server).removeContainer(0xc0003eb680, 0xc00071b380)
/gopath/src/github.com/kubernetes-sigs/cri-o/server/server.go:431 +0x38
github.com/kubernetes-sigs/cri-o/server.(*Server).CreateContainer.func4(0xc000bf9b18, 0xc0003eb680, 0xc00071b380)
/gopath/src/github.com/kubernetes-sigs/cri-o/server/container_create.go:545 +0x4a
github.com/kubernetes-sigs/cri-o/server.(*Server).CreateContainer(0xc0003eb680, …
> container_server: fix a segfault when the sandbox is not found

- lib/container_server.go
backport of: https://github.com/kubernetes-sigs/cri-o/pull/1955
github.com/kubernetes-sigs/cri-o/lib/sandbox.(*Sandbox).RemoveContainer(0x0, 0xc00071b380)
/gopath/src/github.com/kubernetes-sigs/cri-o/lib/sandbox/sandbox.go:319 +0x22
github.com/kubernetes-sigs/cri-o/lib.(*ContainerServer).RemoveContainer(0xc0004dff40, 0xc00071b380)
/gopath/src/github.com/kubernetes-sigs/cri-o/lib/container_server.go:701 +0x6e
github.com/kubernetes-sigs/cri-o/server.(*Server).removeContainer(0xc0003eb680, 0xc00071b380)
/gopath/src/github.com/kubernetes-sigs/cri-o/server/server.go:431 +0x38
github.com/kubernetes-sigs/cri-o/server.(*Server).CreateContainer.func4(0xc000bf9b18, 0xc0003eb680, 0xc00071b380)
/gopath/src/github.com/kubernetes-sigs/cri-o/server/container_create.go:545 +0x4a …
> [release-1.12] Fix another segfault

- lib/container_server.go
backport of: https://github.com/kubernetes-sigs/cri-o/pull/1955
github.com/kubernetes-sigs/cri-o/lib/sandbox.(*Sandbox).RemoveContainer(0x0, 0xc00071b380)
/gopath/src/github.com/kubernetes-sigs/cri-o/lib/sandbox/sandbox.go:319 +0x22
github.com/kubernetes-sigs/cri-o/lib.(*ContainerServer).RemoveContainer(0xc0004dff40, 0xc00071b380)
/gopath/src/github.com/kubernetes-sigs/cri-o/lib/container_server.go:701 +0x6e
github.com/kubernetes-sigs/cri-o/server.(*Server).removeContainer(0xc0003eb680, 0xc00071b380)
/gopath/src/github.com/kubernetes-sigs/cri-o/server/server.go:431 +0x38
github.com/kubernetes-sigs/cri-o/server.(*Server).CreateContainer.func4(0xc000bf9b18, 0xc0003eb680, 0xc00071b380)
/gopath/src/github.com/kubernetes-sigs/cri-o/server/container_create.go:545 +0x4a …
> [release-1.11] container_server: fix a segfault when the sandbox is not found

- cmd/crio/config.go
> config: Add missing comma after each hooks_dir item

- lib/container_server.go
backport of: https://github.com/kubernetes-sigs/cri-o/pull/1955
github.com/kubernetes-sigs/cri-o/lib/sandbox.(*Sandbox).RemoveContainer(0x0, 0xc00071b380)
/gopath/src/github.com/kubernetes-sigs/cri-o/lib/sandbox/sandbox.go:319 +0x22
github.com/kubernetes-sigs/cri-o/lib.(*ContainerServer).RemoveContainer(0xc0004dff40, 0xc00071b380)
/gopath/src/github.com/kubernetes-sigs/cri-o/lib/container_server.go:701 +0x6e
github.com/kubernetes-sigs/cri-o/server.(*Server).removeContainer(0xc0003eb680, 0xc00071b380)
/gopath/src/github.com/kubernetes-sigs/cri-o/server/server.go:431 +0x38
github.com/kubernetes-sigs/cri-o/server.(*Server).CreateContainer.func4(0xc000bf9b18, 0xc0003eb680, 0xc00071b380)
/gopath/src/github.com/kubernetes-sigs/cri-o/server/container_create.go:545 +0x4a …
> [release-1.13] container_server: fix a segfault when the sandbox is not found

- tutorial.md
Commit containernetworking/plugins@4e1f780 (Split build.sh into two OS-specific scripts) removes the `build.sh` file. Now we have `build_linux.sh` and `build_windows.sh`
Signed-off-by: Radostin Stoyanov <rstoyanov1@gmail.com>
> tutorial: Update CNI plugins install example

- pkg/storage/image.go
fix https://github.com/kubernetes-sigs/cri-o/issues/1980
> pkg/storage/image: set insecure only on docker transport

- utils/utils.go
I added missing interface nil checks to prevent possible nil pointer dereferences. 
Beside that, I think that `preservBuf` must always be larget than 0: 
https://github.com/kubernetes-sigs/cri-o/blob/95ad21041c8a9f337673f97ecca7709daca8b8b2/utils/utils.go#L116-L121
because empty `keys` are not possible within the function:
https://github.com/kubernetes-sigs/cri-o/blob/95ad21041c8a9f337673f97ecca7709daca8b8b2/utils/utils.go#L92-L96
> Add interface nil checks

- README.md
On Ubuntu, the package `skopeo-containers` does not exist. It's called `skopeo` instead.
> fix: Package name is `skopeo` in Ubuntu

- utils/filesystem.go
Hey there, this should be a suitable fix since `os.Lstat()` will return `nil` for `FileInfo` if the path is not accessible. Furthermore the `Walk()` function already does an `os.Lstat()` which makes the additional call obsolete within our implementation.
> Fix segfault for invalid paths in GetDiskUsageStats()

- cmd/crio/config.go
- cmd/crio/main.go
- lib/config.go
- lib/config_test.go
- server/config.go
- server/config_test.go
Hey there :wave:, during my experiments with the `Runtimes` configuration variable I noticed that there is no check for existence of the `runtime_path`. This pull request contains an additional sanity check as well as a debug output to see which runtimes got registered during server instantiation.
For later improvements I would suggest to move the configuration validation into the `config.go` files for a better test-ability. Would you agree to that? :innocent:
> Add existence check for runtime_path

- lib/container_server.go
The only error the `Registrar` can return within the `Reserve()` function is `registrar.ErrNameReserved`. This means the lines 620 and 642 in `container_server.go` were unreachable for now. I also removed the additional `Get` since the only reason that the reservation fails is that it is already reserved.
> Remove unreachable error handling paths

- lib/container_server.go
Hey, since the error variable will not be modified by the preceding statement the check for `err != nil` is not needed any more.
> Remove unneeded error check

- Makefile
Signed-off-by: Lorenzo Fontana <lo@linux.com>
I was building and found a variable that I thought was going to help me to conditionally exclude packages from tests, it turned out the variable is not used so I removed it.
dd
> Remove unused variable in Makefile that was used to exclude vendor packages

- oci/oci.go
be sure we don't leave the conmon process around if we fail to write
to the start pipe.
> oci: read conmon process status

- lib/container_server.go
- lib/kill.go
- lib/pause.go
- lib/remove.go
- lib/rename.go
- lib/stop.go
- lib/wait.go
- oci/container.go
- oci/oci.go
- oci/oci_linux.go
- oci/runtime_v1.go
- server/container_attach.go
- server/container_create_linux.go
- server/container_exec.go
- server/container_execsync.go
- server/container_list.go
- server/container_portforward.go
- server/container_reopen_log.go
- server/container_start.go
- server/container_status.go
- server/container_update_resources.go
- server/sandbox_list.go
- server/sandbox_remove.go
- server/sandbox_status.go
- server/sandbox_stop_linux.go
- server/server.go
oci: Abstract Runtime structure as a Go interface
This is the second step in making a clear separation between different
implementations of the runtime. This commit takes care of defining a
new Go interface RuntimeImpl that can be implemented depending on the
runtime version.
One technical detail is that we had to maintain Runtime as a Go
structure embedding this new Go interface, since there are a few
fields that are common to every implementations. Those common
fields are gathered beneath the new structure RuntimeBase.
Once the abstraction is clearly defined, this patch reuses the
former runtime implementation as the RuntimeV1 implementation.
Fixes #1989
Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>
> oci: Abstract Runtime structure as a Go interface

- oci/oci.go
be sure we don't leave the conmon process around if we fail to write
to the start pipe.
Backport to 1.11 @giuseppe ptal.
> [1.11] oci: read conmon process status

- oci/oci.go
be sure we don't leave the conmon process around if we fail to write
to the start pipe.
Backport to 1.13.
> [1.13] oci: read conmon process status

- lib/container_server.go
- pkg/storage/image.go
- pkg/storage/image_test.go
use and override with the global `/etc/containers/registries.conf` insecure and additional registries
> *: use /etc/containers/registries.conf

- cmd/crio/main.go
We hit a limit when there are a lot of containers running.
Note: For the newer branches I will open PRs with this as a configuration option.
@giuseppe @runcom @rhatdan ptal.
> [1.11] Increase max grpc message size

- cmd/crio/config.go
- cmd/crio/main.go
- server/config.go
> [1.13] config: Add config options for setting grpc msg size max

- cmd/crio/config.go
- cmd/crio/main.go
- server/config.go
> config: Add config options for setting grpc msg size max

- lib/config.go
This PR adds another runtime validation for the `/etc/containers/registries.conf`. The benefit is now that the user gets early feedback on cri-o start (for example if the user has mixed up the v1 and v2 syntax).
Currently this would only considered on image pull (which could be too late).
Beside that I have a question: Is it intended that we switch to sysregistriesv2 for `lib/config.go`? It should be possible since there is a backwards compatibility from v2 to v1, but would imply breaking changes within the configuration syntax of cri-o.
> Validate system registries configuration on start

- contrib/systemd/crio.service
Silly me, I swear this should be the last change we need to expose crio metrics. If I commit this change on an ocp 4 cluster and curl the metrics endpoint I can finally see them.
We'll need another 1.12 rebuild from @lsm5 
> [release-1.12] contrib/systemd: add metrics env

- test/network.bats
Hey, this fix makes the network test a bit more robust. I encountered network names like `last_reserved_ip.0` which will cause the test to fail but should not harm the overall test result.
> Fix network test failure

- oci/container.go
- oci/oci_linux.go
- utils/utils.go
Add a description of the form k8s namespaces/pod/container
for the conmon scope to make it easier to associate container IDs
to k8s objects for debugging.
@giuseppe @vrothberg @umohnani8 @runcom ptal.
> [1.12] Add container description to conmon

- Dockerfile
- test/apparmor.bats
- test/testdata/container_redis_apparmor.json
- test/testdata/sandbox_config_apparmor.json
Hey, this PR fixes the apparmor related integration tests (currently disabled within the pipeline). I verified that it works with openSUSE Kubic. The main test appraoch changed a bit since it now uses the `apparmor_profile` field directly within the `security_context`. The plan is to run these tests later on a regular basis, too.
Closes #2040
> Fix apparmor related integration tests

- cmd/crio/main.go
- lib/config.go
- pkg/config/config.go
- server/config.go
- server/config_test.go
- server/container_create.go
- server/inspect_test.go
Need to use these structs in the CRD and controller
for container runtime config. Moving the structs to
a separate package to reduce dependencies.
> [1.12] Move config structs to pkg/config

- server/container_stats.go
Pick required changes from #1869 and fix #1800 
@lsm5 PTAL and thanks
> Add disk usage for ListContainerStats

- pkg/storage/image_test.go
Hey, this PR makes the related image unit test independent from the current system configuration, which should lead into a more stable test approach.
> Update image-test to be system independent

- server/container_create.go
- server/container_execsync.go
- server/container_remove.go
- server/container_start.go
- server/container_stop.go
- server/sandbox_remove.go
- server/sandbox_run_linux.go
- server/sandbox_stop_linux.go
- server/utils.go
Sandbox and Container CRI commands now log debugging information about the infra-container or container they've just operated upon.
Including adding function in util that translates labels in a sandbox run/container create request into a description. This allows the user to see requests to create a container even if it's failed.
Is currently a WIP because I'm looking for feedback on locations of the logging (for most commands once it's succeeded because there is no information about which container until it's been queried from the server, except for requests with a config), and because there is a single line of code duplication (formatting the description) that I am looking to get rid of somehow.
**- How to …
> Added traces to CRI API pertaining to containers and sandboxes

- contrib/test/integration/e2e.yml
An upstream PR https://github.com/kubernetes/kubernetes/pull/73525/files broke e2e tests.
This commit disables those tests till they are fixed upstream.
> Disable broken tests

- contrib/test/integration/e2e-base.yml
It doesn't have dependencies leading to failures at installation time.
> Drop the external git repo

- contrib/test/integration/e2e.yml
It doesn't have dependencies leading to failures at installation time.
> [1.11] Drop the external git repo

- contrib/test/integration/e2e-base.yml
It doesn't have dependencies leading to failures at installation time.
> [1.13] Drop the external git repo

- conmon/conmon.c
we can specify multiple arguments that are passed down to the OCI
runtime, before the command name:
--runtime-arg --debug
will be used as:
RUNTIME --debug COMMAND ...
Needed by: https://github.com/containers/libpod/issues/2285
> conmon: allow to specify additional arguments to the OCI runtime

- server/server.go
- test/restore.bats
If a pod or a container could not be restored, then delete them
from the storage.
Since the container was present in the storage and CRI-O didn't report
it to the the Kubelet, we would have failed the request from the
Kubelet to re-create it over and over again.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1677509
> server: delete the container if it cannot be restored

- server/container_create.go
Image user could have a gid that we were skipping.
> Always set gid if returned from container user files

- Dockerfile
- contrib/test/integration/main.yml
We can handle travis in a follow-on. 
> test: Switch to golang 1.12

- docs/crio.conf.5.md
Update docs/crio.conf.5.md with information on configuring runtime handlers. This brings the documentation up to date with the changes from https://github.com/kubernetes-sigs/cri-o/commit/9d17af41ba2332b05274f508dab612cc12ad33c6
> Update crio.conf docs for RuntimeHandler

- cmd/crio/config.go
- cmd/crio/main.go
- docs/crio.8.md
- docs/crio.conf.5.md
- lib/config.go
- lib/container_server.go
- pkg/config/config.go
- pkg/storage/runtime.go
- server/config_test.go
- server/container_create_linux.go
- server/fixtures/crio.conf
- server/sandbox_run_linux.go
See https://github.com/kubernetes-sigs/cri-o/pull/2115 for the `master` version of this PR.
Added support for supplying credentials necessary for pulling the pause image.
Added a `pause_image_auth_file` config option, and a corresponding `--pause-image-auth-file` CLI option.
They are disabled by default, preserving the current behavior. Users have to opt in by explicitly pointing at a config file.
Ultimately, run with `--pause-image-auth-file` in the CLI, or the `pause_image_auth_file` option (I didn’t do that yet.)
The `master` version of this PR has GoMock-based tests; this branch does not use GoMock, so this PR does not add them.
New config and CLI options allow supplying credentials …
> Pause credentials 1.12

- cmd/crio/config.go
- cmd/crio/main.go
- docs/crio.8.md
- docs/crio.conf.5.md
- lib/config.go
- lib/container_server.go
- pkg/storage/runtime.go
- server/config_test.go
- server/container_create_linux.go
- server/fixtures/crio.conf
- server/sandbox_run_linux.go
See https://github.com/kubernetes-sigs/cri-o/pull/2115 for the `master` version of this PR.
Added support for supplying credentials necessary for pulling the pause image.
Added a `pause_image_auth_file` config option, and a corresponding `--pause-image-auth-file` CLI option.
They are disabled by default, preserving the current behavior. Users have to opt in by explicitly pointing at a config file.
Ultimately, run with `--pause-image-auth-file` in the CLI, or the `pause_image_auth_file` option (I didn’t do that yet.)
The `master` version of this PR has GoMock-based tests; this branch does not use GoMock, so this PR does not add them.
New config and CLI options allow supplying credentials …
> Pause credentials 1.13

- cmd/crio/config.go
- cmd/crio/main.go
- docs/crio.8.md
- docs/crio.conf.5.md
- lib/config.go
- lib/container_server.go
- pkg/storage/runtime.go
- pkg/storage/runtime_test.go
- server/config_test.go
- server/container_create_linux.go
- server/fixtures/crio.conf
- server/sandbox_run_linux.go
Added support for supplying credentials necessary for pulling the pause image.
Added a `pause_image_auth_file` config option, and a corresponding `--pause-image-auth-file` CLI option.
They are disabled by default, preserving the current behavior. Users have to opt in by explicitly pointing at a config file.
This adds GoMock-based tests for that small piece of code in `runtimeService` (but not an end-to-end test, AFAICS there isn’t any existing test for credential handling either).
Ultimately, run with `--pause-image-auth-file` in the CLI, or the `pause_image_auth_file` option (I didn’t do that yet.)
New config and CLI options allow supplying credentials necessary for pulling the pause image.
> Allow configuring credentials used for pulling the pause image

- docs/crio.conf.5.md
* I tried to improve the crio.conf.5 markdown documentation
* I added a link to toml and crio.8 documentation
* ~I added newlines after the options as intended in the source document~
I reverted this commit because it breaks man page rendering
* Adding markdown link references
* ~for the missing newlines, added a backslash at the end of some lines~
(reverted)
* validate the diff
* look at the rendered version at
https://github.com/petervandenabeele/cri-o/blob/docs-crio-conf-5-formatting/docs/crio.conf.5.md  
and compare it with the "previous" version at
https://github.com/kubernetes-sigs/cri-o/blob/master/docs/crio.conf.5.md
Fix links of crio.conf.5 documentation
> Docs : crio-conf-5 formatting

- cmd/crio/main.go
- server/config.go
- server/server.go
same as https://github.com/kubernetes-incubator/cri-o/pull/1714 but for `release-1.11`
> [release-1.11] server: serve streaming on localhost on a random port

- cmd/crio/main.go
- contrib/systemd/crio.service
crio.conf file may not be present in default /etc/crio directory,
but in /usr/share/defaults/crio directory in stateless systems.
This change includes looking in /usr/share/defaults/crio if
not found in default location.
Signed-off-by: Jose Lamego <jose.a.lamego@intel.com>
> main: allow defining default conf file at build time

- server/container_create.go
- server/container_create_linux.go
- utils/utils.go
- utils/utils_test.go
- vendor/github.com/containers/libpod/pkg/lookup/lookup.go
Create a new /etc/passwd in the container with a record for the
user account that is running the container.
This will allow getpwuid calls to succeed inside of the container.
We have seen failures where getpwduid was not successful.
Also vendor in an update libpod packages
Replaces #1841
> Containers run as a USER should have UID in /etc/passwd

- server/container_create_linux.go
- test/ctr.bats
- test/testdata/container_redis_device.json
- test/testdata/sandbox_config_privileged.json
Before, device mounting was disabled when a container was privileged, because there was no clear way to make distinctions between mounts on the host and directories in the container. Resolve this by decreeing a privileged container cannot mount a device that already exists on the host. This allows privileged container mounts to work in other cases.
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1614734
Allow device mounting in a privileged container.
> Allow device mounting to work in privileged mode

- server/container_create_linux.go
- test/ctr.bats
- test/testdata/container_redis_device.json
- test/testdata/sandbox_config_privileged.json
Before, device mounting was disabled when a container was privileged, because there was no clear way to make distinctions between mounts on the host and directories in the container. Resolve this by decreeing a privileged container cannot mount a device that already exists on the host. This allows privileged container mounts to work in other cases.
> [1.12] Allow device mounting to work in privileged mode

- server/container_create_linux.go
- test/ctr.bats
- test/testdata/container_redis_device.json
- test/testdata/sandbox_config_privileged.json
Before, device mounting was disabled when a container was privileged, because there was no clear way to make distinctions between mounts on the host and directories in the container. Resolve this by decreeing a privileged container cannot mount a device that already exists on the host. This allows privileged container mounts to work in other cases.
> [master] Allow device mounting to work in privileged mode

- .codecov.yml
- .travis.yml
- Makefile
I added codecov unit test coverage reports. Currently the bot is not able to comment since we have nothing to compare (master). The current coverage can be retrieved here: https://codecov.io/gh/kubernetes-sigs/cri-o
> Add codecov coverage reports

- oci/container.go
- oci/container_test.go
- oci/history_test.go
- oci/memory_store.go
- oci/memory_store_test.go
- oci/oci_test.go
- oci/suite_test.go
This PR contains the unit tests of the `oci` package. The coverage is pretty low for now, because there is no lower level abstraction (like for system calls).
> Add oci unit tests

- pkg/storage/runtime_test.go
As a follow up of #2132 we decided to remove the camel-case test because it does not match any real world scenario. Beside this, a small return value by the mock is fixed.
This PR should decrease the unit test coverage a bit.
> Remove camel-case imageName runtime test

- cmd/crio/config.go
- cmd/crio/main.go
- contrib/cni/README.md
- docs/crio.conf.5.md
- lib/config.go
- lib/testdata/config.toml
- server/config_test.go
- server/fixtures/crio.conf
- server/sandbox_network.go
- server/server.go
- server/utils.go
- vendor.conf
- vendor/github.com/containernetworking/cni/README.md
- vendor/github.com/containernetworking/cni/libcni/api.go
- vendor/github.com/containernetworking/cni/libcni/conf.go
- vendor/github.com/containernetworking/cni/pkg/invoke/delegate.go
- vendor/github.com/containernetworking/cni/pkg/invoke/exec.go
- vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go
- vendor/github.com/containernetworking/cni/pkg/types/current/types.go
- vendor/github.com/containernetworking/cni/pkg/types/types.go
- vendor/github.com/containernetworking/cni/pkg/version/plugin.go
- vendor/github.com/containernetworking/cni/pkg/version/version.go
- vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
- vendor/github.com/cri-o/ocicni/pkg/ocicni/types.go
- vendor/github.com/cri-o/ocicni/pkg/ocicni/types_unix.go
- vendor/github.com/cri-o/ocicni/pkg/ocicni/types_windows.go
- vendor/github.com/cri-o/ocicni/pkg/ocicni/util_linux.go
- vendor/github.com/cri-o/ocicni/pkg/ocicni/util_unsupported.go
trash update ocicni and containernetworking/cni to v0.1.0 and
0.7.0-alpha0, respectively.
ocicni v0.1.0 brings a support for multi-network but that is
"crippled" in networkStart(). The reason is there's no mechanism
in Sandbox to provide multiple networks.
pulled in ocicni and containernetworking/cni updates using trash. The goal was to 
have "ocicni: missing default network is not a hard error" included to be able
to use containers with loopback networks only.  The testing shows that it did not
bring the desired functionality and something else is still needed since pods fail
to start. 
Fixes: #1809
> RFC: config: CNI: multiple plugin binary directories

- .travis.yml
- Dockerfile
- README.md
- cmd/crio/config.go
- cmd/crio/main.go
- conmon/Makefile
- conmon/conmon.c
- conmon/ctr_logging.c
- conmon/ctr_logging.h
- conmon/utils.c
- conmon/utils.h
- docs/crio.8.md
- lib/config.go
- lib/container_server.go
- oci/oci.go
- oci/runtime_oci.go
- test/ctr.bats
- test/helpers.bash
Allowed for user to flag --log-to-journal to log container output to journald as well as kubernetes logs (in conmon)
Added conditional code in conmon/Makefile to allow for conmon to compile on systems without libsystemd. Flagging --log-to-journald will error if libsystemd isn't found during compilation.
Added --log-to-journald flag to crio and passed it to conmon.
> [master] journald log driver

- oci/oci_test.go
concurrent merges caused a testing library to expect an extra argument. Fix this :)
> [master] Fix oci_test for journald logging

- test/ctr.bats
- utils/filesystem.go
Follow #2050, this PR add test to check each column of the output of `ListContainerStats` is not empty
> Tests the output of ctr stats is not empty

- .golangci.yml
- cmd/crio/main.go
- lib/config.go
- lib/container_server.go
- lib/rename.go
- lib/sandbox/sandbox.go
- oci/attach.go
- pkg/storage/image.go
- server/config_unix.go
- server/container_create.go
- server/container_list.go
- server/image_list.go
- server/sandbox_run_linux.go
- server/server.go
- server/utils.go
- test/copyimg/copyimg.go
- utils/filesystem.go
I enabled [go-critic](https://github.com/go-critic/go-critic) within the golangci-lint configuration. Beside this, I enabled all go-critic internal linters which made sense to me and caused no larger fixes.
Some fixes are just style related, but others avoid unnecessary copying of structures which could have a real performance impact, like this:
```go
for i := range containers {
container := &containers[i]
}
```
> Update linter to use gocritic

- cmd/crio/config.go
- cmd/crio/main.go
- docs/crio.conf.5.md
- lib/config.go
- lib/config_test.go
- lib/container_server.go
- lib/container_server_test.go
- lib/sandbox/history_test.go
- lib/sandbox/sandbox.go
- lib/sandbox/sandbox_test.go
- lib/sandbox/suite_test.go
- lib/suite_test.go
- oci/container.go
- oci/container_test.go
- oci/oci.go
- oci/oci_test.go
- oci/suite_test.go
- pkg/annotations/annotations.go
- server/config_test.go
- server/container_create_linux.go
- server/inspect_test.go
- server/sandbox_run.go
- server/sandbox_run_linux.go
- server/server.go
As announced when RuntimeClass has been implemented as part of CRI-O,
the deprecated flags trusted/untrusted qualifying the workload will
be removed starting from 1.14.
This patch takes care of removing any reference to those annotations,
which simplifies greatly the code complexity.
Fixes #2139
Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>
> config: Remove trusted/untrusted support for 1.14

- contrib/test/integration/main.yml
k8s requires it for build now.
> test: Update to golang 1.12.1

- contrib/test/integration/e2e.yml
- contrib/test/integration/main.yml
Some of the packages that we rely on don't compile with 1.9 anymore.
> [1.10] test: Switch to golang 1.11.6

- Dockerfile
The current travis integration tests complain about the missing seccomp jessie-backport dependencies. This PR should fix this. The go images are now built on top of stretch, so I will give removing the backport a try.
> Fix travis integration test dependencies

- lib/config.go
- server/config.go
Hey, this is just a small change to increase the customer satisfaction and abort with a more meaningful error in case of configuration issues.
> Update toml decode errors to be more precise

- contrib/test/integration/build/kubernetes.yml
- contrib/test/integration/main.yml
- lib/sandbox/sandbox.go
- server/container_create.go
- server/sandbox_network.go
- server/sandbox_run.go
- server/sandbox_stop.go
Closes #1973 
If the CNI setup fails in runPodSandbox, the infra container started is
not stopped/removed and leaks.
Ensure the necessary clean-up steps are executed on error
path.
Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>
> [1.9] runPodSandbox: clean up containers on error path

- lib/config.go
- lib/config_test.go
- server/config.go
- server/config_test.go
This commit updates to config validation on cri-o startup to work for:
- `RuntimeConfig.HooksDir`
- `RuntimeConfig.Conmon`
- `NetworkConfig.NetworkDir`
- `NetworkConfig.PluginDir`
All unit tests have been updated as well, whereas the returned error now
indicates that the issue happened on "config validation".
> Enhance config validation

- lib/sandbox/sandbox.go
- lib/sandbox/sandbox_linux.go
- lib/sandbox/sandbox_test.go
- test/mocks/sandbox/sandbox.go
fix this segfault:
github.com/kubernetes-sigs/cri-o/lib/sandbox.(*NetNs).SymlinkCreate(0xc0002107b0, 0xc000882180, 0x40, 0x0, 0xc000210690)
src/github.com/kubernetes-sigs/cri-o/lib/sandbox/sandbox_linux.go:68 +0x1d2
github.com/kubernetes-sigs/cri-o/lib/sandbox.(*Sandbox).NetNsCreate(0xc0002a4000, 0x1d042a0, 0xc0002107b0, 0x1c, 0xc0003e2b08)
src/github.com/kubernetes-sigs/cri-o/lib/sandbox/sandbox.go:414 +0x166
github.com/kubernetes-sigs/cri-o/server.(*Server).runPodSandbox(0xc0003d0480, 0x1cf14c0, 0xc0007fcd20, 0xc0005a28e0, 0x0, 0x0, 0x0)
src/github.com/kubernetes-sigs/cri-o/server/sandbox_run_linux.go:460 +0x698c
github.com/kubernetes-sigs/cri-o/server.(*Server).RunPodSandbox(0xc0003d0480, 0x1cf14c0, 0xc0007fcd20, 0xc0005a28e0, 0xc0003d0480, 0x7f8028c0cc00, 0xc000229c28) …
> sandbox: fix segfault with manage_network_ns_lifecycle

- conmon/conmon.c
- conmon/ctr_logging.c
- conmon/ctr_logging.h
- oci/runtime_oci.go
- test/ctr.bats
Two changes to better match docker functionality:
Change MESSAGE_ID to CONTAINER_ID_FULL, as well as add CONTAINER_ID (truncated at 12 characters)
Change stdout output to an info instead of a notice log level
Also small change with where the log buffer is null terminated
Now, the callee doesn't depend on an unchecked invariant that num_read < strlen(buf)
> Small tweaks to journald logging

- server/container_create.go
- test/ctr.bats
- test/testdata/container_redis_user.json
When setting the gid, we were not checking if RunAsGroup
from k8s was nil or not. We were simply converting that
to an int and nil was becoming 0. Hence all the containers
were being run with gid root regardless of their uid.
Adding that check here fixes it and we get the correct gid.
> [1.11] Pick up correct gid

- conmon/conmon.c
In testing the newest conmon with podman, the g_print for oom_handling_score failing to open the fd printed every time podman was run as rootless. Fix this by changing it to ndebugf, so a normal user won't encounter the failure.
Also move the handling higher so the log level is set already
> Log oom_handling_score failure to debug

- oci/runtime_oci.go
The OCI runtime `parseLog()` function is currently called by `ExecSyncContainer()` and the RPC entry point `ExecSync()`.
A temporarily log file within `/tmp/crio-log-$CONTAINERID` is created during the execution of `ExecSync()`, which receives the stdout and stderr output from the provided command.
This commit fixes an index out-of-bounds runtime panic if the log file contains an malicious partial (P) log entry which does not contain a newline at the end of the file, like `2019-03-28T10:24:43.981274081+01:00 stdout P `.
The issue can be reproduced like this:
1. Force creating the logfile in `/tmp` via:
```
> sudo crictl exec -s $CONTAINERID sh -c "echo test && sleep 30"
```
2. Modify the logfile with malicious content:
```
> echo -n "2019-03-28T10:24:43.981274081+01:00 stdout P " >> …
```
> [master] Fix possible out of bounds access during container log parsing

- .golangci.yml
- lib/container_server.go
- oci/oci.go
- oci/runtime_oci.go
- oci/runtime_vm.go
- pkg/seccomp/seccomp.go
- pkg/seccomp/seccomp_test.go
- pkg/seccomp/seccomp_unsupported.go
- pkg/storage/runtime.go
- pkg/storage/runtime_test.go
- server/config_test.go
- server/container_create.go
- server/container_create_linux.go
- server/sandbox_run.go
- server/sandbox_run_linux.go
- server/utils.go
Hey, this improvement should avoid copying to much data around the stack and will fix the following reported issues:
```
oci/oci.go:428:7: hugeParam: e is heavy (224 bytes); consider passing it by pointer (gocritic)
func (e ExecSyncError) Error() string {
^
pkg/storage/runtime.go:380:64: hugeParam: metadata is heavy (157 bytes); consider passing it by pointer (gocritic)
func (r *runtimeService) SetContainerMetadata(idOrName string, metadata RuntimeContainerMetadata) error {
^
lib/container_server.go:482:22: hugeParam: spec is heavy (120 bytes); consider passing it by pointer (gocritic)
func configNetNsPath(spec rspec.Spec) (string, error) {
^
pkg/seccomp/seccomp.go:33:28: hugeParam: config is heavy (88 bytes); consider passing it by pointer (gocritic)
func LoadProfileFromStruct(config …
```
> Update linter to use hugeParam

- oci/oci.go
> [1.10] Fix possible out of bounds access during log parsing

- oci/oci.go
> [1.12] Fix possible out of bounds access during log parsing

- oci/runtime_oci.go
> [1.14] Fix possible out of bounds access during log parsing

- oci/oci.go
> [1.11] Fix possible out of bounds access during log parsing

- server/container_create.go
- test/ctr.bats
- test/testdata/container_redis_user.json
When setting the gid, we were not checking if RunAsGroup
from k8s was nil or not. We were simply converting that
to an int and nil was becoming 0. Hence all the containers
were being run with gid root regardless of their uid.
Adding that check here fixes it and we get the correct gid.
backport https://github.com/kubernetes-sigs/cri-o/pull/2173
> [1.10] Pick up correct gid

- contrib/test/integration/build/kubernetes.yml
Upstream changed the way it accepts flags, and the timeout
flag is causing issues when determining the runtime socket.
Removing for now to unblock cri-o PRs.
> Remove timeout flag from kubernetes.yml

- Makefile
If one tries to build release 1.14.0 using parallel make `make -jX` the
build fails with go build of config.h unable to satisfy seccomp
dependency. This patch tries to mimic what is done on other components
where BUILDTAGS are added if they exist in the system
Signed-off-by: Ganesh Maharaj Mahalingam <ganesh.mahalingam@intel.com>
(cherry picked from commit e24d57d688392e49594ef39eec0ff9f9344231e8)
Backport of PR: https://github.com/kubernetes-sigs/cri-o/pull/2201
> Fix parallel make build failure

- test/ctr.bats
We need to bump up the memory limit as the value we are writing isn't enough
with recent runc changes.
> test: Fix oom test

- conmon/conmon.c
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1671622
> conmon: do not leak fd when creating oom file

- utils/errdefs/errors.go
- utils/errdefs/grpc.go
- utils/fifo/fifo.go
- utils/fifo/handle.go
- utils/io/container_io.go
- utils/io/exec_io.go
- utils/io/helpers.go
- utils/io/logger.go
- utils/ioutil/read_closer.go
- utils/ioutil/write_closer.go
- utils/ioutil/writer_group.go
- utils/typeurl/types.go
Holy smokes!  Not clear why https://github.com/cri-o/cri-o/commit/9e52f00d76810d9162ce707b9df84c9ef3fd8a44
did not include the original headers when copying files from containerd.  That is obviously an egregious error. 
Sebastien is OOO so I'm pushing this on his behalf.
This PR adds the appropriate headers.  Did a quick check of containerd/containerd, and each of them should have:
```
/*
Copyright The containerd Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR …
```
> utils: add license headers for pulled files

- server/server.go
ParseIDMap function was extracted to idtools in
https://github.com/containers/storage/pull/236
it is already used in containers/storage and buildah and libpod. Cri-o should
use the very same code as the others.
Signed-off-by: Šimon Lukašík <isimluk@fedoraproject.org>
> Refactor: use idtools.ParseIDMap instead of bundling own version

- lib/sandbox/sandbox.go
- lib/sandbox/sandbox_test.go
- oci/container.go
- oci/container_test.go
- server/container_create_linux.go
- server/sandbox_run.go
- server/sandbox_run_linux.go
Simplify the implementation for user namespaces by not using an
intermediate mount namespace.  For doing it, we need to relax the
permissions on the parent directories and allow browsing
them. Containers that are running without a user namespace, will still
maintain mode 0700 on their directory.
dropped intermediate mount namespace
when using user namespaces, containers mount are accessible from the host/
when using user namespaces, we no longer use an intermediate mount namespace
> userns: drop intermediate mount namespace

- lib/sandbox/sandbox_linux.go
A Path() function was added for disappearing netns, so we should
use it.
> netns can be nil which can cause a segfault

- lib/container_server.go
- lib/container_server_test.go
This commit fixes a nil pointer dereference when creating a new
`ContainerServer` and providing `nil` as `ConfigIface`. Should no
big issue right now, but seems more safe to me.
> Add config interface nil check

- .golangci.yml
This commits enables the above mentioned linters. No further code
changes are needed due to test passing on `make lint`. :tada:
> Add stylecheck, unused and gosimple linters

- conmon/conmon.c
- conmon/ctr_logging.c
Before, the static building of sd_journal_send args meant there were backwards compatibility issues with conmon.
Mainly, if a name wasn't inputted, any runtime would crash trying to use it.
Fix this by building the journal arguments more dynamically. This also allows the journal arguments to be extended easier.
>  conmon: use sd_journal_sendv

- lib/sandbox/sandbox_linux.go
Fixed a nil pointer when cri-o gets into a state where it tries to clean up existing networks which do not have netns created.
```
time="2019-04-02 10:59:08.732093623+02:00" level=info msg="About to del CNI network mynet (type=calico)"
... stacktrace ...
```
Do not crash when tearing down a pod that doesn't have netns created
> Do not crash when netns is not set up

- lib/sandbox/sandbox_linux.go
This PR backports #2222
Closes #2221
> [1.14] netns can be nil which can cause a segfault

- cmd/crio/config.go
- cmd/crio/main.go
- lib/config.go
- oci/oci.go
- oci/oci_linux.go
- oci/oci_test.go
- oci/runtime_oci.go
- test/helpers.bash
Hey there, the main intention of this PR is to resolve this TODO:
https://github.com/kubernetes-sigs/cri-o/blob/7a9445829c6165d62a75bcdab1843b264bb01f37/oci/oci_linux.go#L75-L80
My approach would be to introduce a RuntimeRoot for the RuntimeHandler and pass it around where it is necessary. This would also help in unit testing, since we now could use a temporarily run root directory for runc where we are privileged.
WDYT?
> Add RuntimeHandler.RuntimeRoot

- Makefile
This commit fixes the binary build targets when running
`sudo make`, like `sudo make install`.
> Fix Makefile targets for sudo

- oci/runtime_oci.go
- test/ctr_userns.bats
specify the runtime root also when using conmon exec.
> runtime: fix a regression introduced by 296d80b6ac61b427583e1cfe06e74da73e7e875b

- test/command.bats
- test/ctr.bats
- test/helpers.bash
$ bats -f "ctr expose metrics" test/ctr.bats 
✓ ctr expose metrics with default port
✓ ctr expose metrics with custom port
2 tests, 0 failures
$ bats -f "invalid metrics port" test/command.bats 
✓ invalid metrics port
1 test, 0 failures
Signed-off-by: Alex Jia <chuanchang.jia@gmail.com>
added metrics test to ctr.bats and command.bats
- add positive testing to ctr.bats
- add negative testing to command.bats
$ bats -f "ctr expose metrics" test/ctr.bats 
$ bats -f "invalid metrics port" test/command.bats 
> tests: added metrics test to ctr.bats and command.bats

- cmd/crio-config/config.go
- lib/config.go
- lib/config_unix.go
- lib/config_windows.go
- oci/oci_unix.go
- oci/oci_windows.go
- oci/runtime_oci.go
- server/server.go
This commit moves the configuration variables
`ContainerAttachSocketDir` and `containerExitsDir` to the library
configuration. This fixes the issue that wrong `--socket-dir-path` is
passed to conmon if `ContainerAttachSocketDir` is configured to
somewhere else than "/var/run/crio". A second fixed issue is that the
target directory for `ContainerAttachSocketDir` is not created correctly
on server `New()`.
> Move ContainerAttachSocketDir/containerExitsDir to lib

- server/sandbox_run_linux.go
The kubelet takes the memory limits of the containers running
in a pod and set is as the memory limit of the pod.
We were enforcing this minimum memory limit check during the
container creation time but not during the sandbox creation
time. Now we take the pod slice path and read the memory file
and double check that it is above the minimum memory limit.
Doing this also returns a correct error message when the memory
limit is too low, instead of the vague "signal killed" message.
> [1.13] Add min memory limit check to sandbox_run_linux.go

- Dockerfile
- contrib/test/integration/main.yml
- pkg/storage/runtime.go
- pkg/storage/runtime_test.go
- server/container_create_linux.go
- server/sandbox_run.go
- server/sandbox_run_linux.go
- server/sandbox_stop_linux.go
- test/ctr.bats
- test/ctr_seccomp.bats
- test/image_volume.bats
We want to be able to share SELinux labels with podman and buildah
as well as any platform that uses containers/storage. By allowing
containers/storage to manage them, we get uniqueness in the labels.
Taking over https://github.com/kubernetes-sigs/cri-o/pull/1868
> Allow containers/storage to manage SELinux labels

- lib/kill.go
- lib/sandbox/suite_test.go
- lib/suite_test.go
- lib/wait.go
- oci/suite_test.go
- pkg/findprocess/findprocess_test.go
- pkg/seccomp/seccomp_test.go
- pkg/storage/suite_test.go
- utils/suite_test.go
Since we vendored golangci lint within the repository we can safely
remove source code based nolints which would have no effect.
> Remove unnecessary nolints

- server/image_status.go
Theoretically it is possible to retrieve an image status size of zero, which would lead into a crash on dereferencing the `status.Size` pointer. This PR fixes this issue.
> Add nil check for image status size

- server/sandbox_run_linux.go
- vendor/modules.txt
The kubelet takes the memory limits of the containers running
in a pod and set is as the memory limit of the pod.
We were enforcing this minimum memory limit check during the
container creation time but not during the sandbox creation
time. Now we take the pod slice path and read the memory file
and double check that it is above the minimum memory limit.
Doing this also returns a correct error message when the memory
limit is too low, instead of the vague "signal killed" message.
> Add min memory limit check to sandbox_run_linux.go

- server/server.go
On improper API usage it is possible to setup a sandbox without any infra container. This commit adds an additional check for that case.
> Add infra container check for pod sandbox

- lib/container_server.go
- lib/container_server_linux.go
- lib/container_server_test.go
- server/sandbox_remove.go
- server/sandbox_run_linux.go
- server/secrets.go
- server/server.go
Hey, this PR updates all related error paths to actually return the new introduced error possibilities from selinux-go 1.2. Beside this the crashing unit test can now be enabled.
Fixes #1987
> Update error handling paths for sandbox add and removal

- .travis.yml
- Dockerfile
- Makefile
- contrib/test/integration/system.yml
- hack/ostree_tag.sh
Since ostree is not needed any more we can remove the installation from our CI to gain a general speedup. Beside this, the script `hack/ostree_tag.sh` does not seem to be needed any more.
> Remove ostree dependency

- Makefile
- contrib/test/integration/golang.yml
golangci-lint already lints with gofmt so we should avoid checking twice.
> Remove gofmt Makefile target

- oci/oci.go
> [1.9] Fix possible out of bounds access during log parsing

- cmd/crio/main.go
Added default value text to the flags to `crio` binary. 
Took default values from docs at https://github.com/cri-o/cri-o/blob/master/docs/crio.8.md
Build the binary with `make` and issue command `bin/crio --help`
`crio` usage now includes text displaying default values
> Add default text to flags

- Makefile
The `PACKAGES` variable has been removed from the Makefile which breaks the `testunit-bin` target, which should be fixed now.
> Fix testunit-bin Makefile target

- Dockerfile
- contrib/test/integration/build/parallel.yml
- contrib/test/integration/build/plugins.yml
- contrib/test/integration/main.yml
- test/cni_plugin_helper.bash
- test/ctr_seccomp.bats
- test/helpers.bash
- test/hooks.bats
- test/hooks/checkhook.sh
- test/network.bats
- test/restore.bats
- test/test_runner.sh
This PR utilizes the parallelism support of bats and applies them to the integration tests. All integration tests should now run int ~15min instead of >30min.
> Update bats tests to run in parallel

- Makefile
The repository should be completely self containing so that the `-i` flag is not needed any more.
> Remove `go build -i` flag

- Makefile
- hack/openpgp_tag.sh
Hey, I'm not sure if we want to support this but we can build CRI-O without `gpgme-devel`, `libassuan-devel` and `libgpg-error-devel`.
> Add openpgp_tag.sh as fallback if no gpgme is available

- lib/config.go
- lib/config_test.go
- server/config_test.go
Kubernetes DeamonSets should be able to add CNI plugins after the start
of CRI-O. But currently, CRI-O fails to start if the PluginDir is not
available. This is now solved by simply creating the directory on
configuration validation.
Furthermore, it will be now validated if the specified PluginDirs are
real directories (and not a files for example).
> Update PluginDir to be created if not existing

- lib/container_server_test.go
- lib/suite_test.go
This makes the unit tests more system independent, since we do not automatically fallback to the default OCI hooks directories.
Closes #2229
> Update unit tests to use empty CNI hooks dir per default

- Makefile
- lib/container_server.go
- lib/container_server_test_inject.go
- oci/container.go
- oci/container_test_inject.go
- server/server_test_inject.go
This commit introduces a new build tag `test` to separate the testing API from the user API. All test targets have been adapted to use this tag, whereas the main binaries are excluded. This make some mentions that "this API function should not be used" obsolete and provides us more flexibility for future mocking approaches.
All methods I added here will be used by unit tests later on.
> Add unit test inject files

- test/test_runner.sh
This is a trivial test if the release-1.13 pipeline runs as intended whether to check if we need to apply a fix.
Relates to: #2285
---
Edit: Found the problem, applied a quick fix and changed the commit message:
```
Some test machines do not have the `cni_plugin_helper.bash` installed
when running the integration tests. This commit fixes it with a manual
installation before running the actual suite.
```
> [1.13] Fix integration tests for missing cni_plugin_helper.bash

- vendor.conf
- vendor/github.com/containers/storage/drivers/overlay/overlay.go
Vendor in changes from containers/storage to recreate symlinks
in overlay/l when they are not found.
> [1.13] Vendor in containers/storage release-1.13

- .gitignore
- .travis.yml
- Dockerfile-nix
- Makefile
- nix/default.nix
- nix/derivation.nix
- nix/nixpkgs.nix
- test/command.bats
- test/helpers.bash
This commit mainly adds a nix package for having a fully reproducible static build of CRI-O for glibc and musl libc.
- only x86-64 targets are supported for now
- the binaries are stripped
- CI builds runs within a prepared container image on travis
- the binaries are integration tested on travis as well
To test it locally without installed nix but inside a container runtime, simply run:
```
make build-static NIX_IMAGE=<IMAGE>
```
The resulting binaries should now be available within:
- `bin/crio-x86_64-static-glibc`
- `bin/crio-x86_64-static-musl`
To test it within your local nix installation, execute from the root of the git repository:
```
nix-build nix
```
The resulting binary should be now reside in:
- `result-bin/bin/crio-x86_64-static-glibc`
- …
> Add static crio binary build for x86-64 (glibc and musl)

- README.md
- tutorials/setup.md
This commits contains all necessary documentation about the static
builds of CRI-O.
Needs #2270
> Add documentation about static builds

- hack/openpgp_tag.sh
Some distributions do not ship the `pkg-config` files for gpgme. This
commit uses the `gpgme-config` tool to check for its availability, which
should work for every distribution.
> Fix hack/openpgp_tag.sh on older distributions

- cmd/crio/config.go
- cmd/crio/main.go
- docs/crio.8.md
- docs/crio.conf.5.md
- lib/config.go
- lib/config_test.go
- server/config.go
- server/config_test.go
- test/helpers.bash
- Update the crio command line arguments to accept `--log-dir`
- Update the corresponding documentation
- Improve configuration validation to test the LogDir
- Update unit tests for the additional code paths
> Improve LogDir configuration

- test/test_runner.sh
Some test machines do not have the `cni_plugin_helper.bash` installed
when running the integration tests. This commit fixes it with a manual
installation before running the actual suite.
Backport of: #2289
Cherry-pick: 67e7515f22a1a0be3aca4c65c92966b280920cd0
> [1.12] Fix integration tests

- server/container_create.go
- server/container_create_linux.go
- utils/utils.go
- vendor/github.com/containers/libpod/pkg/lookup/lookup.go
Create a new /etc/passwd in the container with a record for the
user account that is running the container.
This will allow getpwuid calls to succeed inside of the container.
We have seen failures where getpwduid was not successful.
Also vendor in an update libpod packages
Cherry-pick 77408ef1490002e62c88baacc5c994e97aa793c6
> [1.13] Containers run as a USER should have UID in /etc/passwd

- test/test_runner.sh
- vendor/github.com/fsouza/go-dockerclient/go.mod
- vendor/github.com/lithammer/dedent/go.mod
- vendor/github.com/onsi/gomega/go.mod
- vendor/golang.org/x/sys/go.mod
- vendor/golang.org/x/text/go.mod
- vendor/gopkg.in/yaml.v2/go.mod
We pull the latest version of vndr during `make vendor`, which breaks up
the CI pipeline because of an upstream change.
Relates to: https://github.com/LK4D4/vndr/commit/a6135d4a2be464cb8bf5c3ae61f86da8ac9d6fde
On top of that I cherry picket the integration test fixes.
> [1.14] Fix `make vendor` on travis and integration tests

- .circleci/config.yml
- Dockerfile-circleci
- Makefile
- lib/sandbox/suite_test.go
- lib/suite_test.go
- oci/suite_test.go
- pkg/findprocess/findprocess_test.go
- pkg/seccomp/seccomp_test.go
- pkg/storage/suite_test.go
- test/framework/framework.go
- test/test_runner.sh
- utils/suite_test.go
- vendor/modules.txt
Hey :wave:, this PR adds the CircleCI test pipeline, which includes a docker base image and the ginkgo junit test extension. The pipeline mainly clones the current travis behavior, but in an optimized fashion. Target is to utilize CircleCIs artifact, caching and workspace features to do no task twice and ensure an optimal build and test process. More information and benefits can be found in #2294.
An example test pipeline can be found here:
https://circleci.com/workflow-run/a48896d8-c6dc-4558-8de1-92670f0cbcea
The following CircleCI settings should be ensured by a repository administrator 
https://circleci.com/gh/cri-o/cri-o/edit#advanced-settings:
- GitHub Status updates: **On**
- Free and Open Source: **On**
- Build forked pull requests: **Off**
- Pass secrets to builds from forked pull …
> Add CircleCI support

- test/test_runner.sh
Some test machines do not have the `cni_plugin_helper.bash` installed
when running the integration tests. This commit fixes it with a manual
installation before running the actual suite.
Backport of: #2289
Cherry-pick: 67e7515f22a1a0be3aca4c65c92966b280920cd0
> [1.11] Fix integration tests

- lib/container_server.go
- server/server.go
When cri-o is restarted, we were not returning an error if
an error ocurred when reading container state from disk. So
if the state.json file was corrupted or deleted in the meantime
the containers would be reporting an UNKOWN state and default
values for started time, created time, etc.
We now check for that and if a pod can't be restored, we delete the pod
as well as any containers associated with it. We also release the pod
and container names so that they can be used again.
We do the same for any containers that can't be restored.
Should fix https://bugzilla.redhat.com/show_bug.cgi?id=1702655
> [1.13] Fix logic of server.restore()

- server/container_create.go
- utils/utils.go
When generating a an entry in the /etc/passwd file, we
need to also add username and homedir, so that the user
can properly login.
> [1.13] Add username and homedir to generated password

- conmon/cmsg.c
Cast socklen_t to an unsigned long. Fixes #2321.
Successfully built conmon with Alpine/musl.
Cast socklen_t to an unsigned long. Fixes #2321.
> Fixes assumption that socklen_t is always an unsigned long

- Dockerfile
Hey, if there are no concerns I would like to just use the latest static runc binary from GitHub for integration testing.
> Update runc test dependency to v1.0.0-rc8

- server/image_fs_info_test.go
- server/image_list_test.go
- server/image_pull_test.go
- server/image_remove_test.go
- server/image_status_test.go
The merge of #2309 breaks up the build pipeline of the master, which currently contains some wrong import paths. This should be fixed now.
> Fix kubernetes import paths for cri-api

- server/container_create.go
- utils/utils.go
- utils/utils_test.go
When generating a an entry in the /etc/passwd file, we
need to also add username and homedir, so that the user
can properly login.
> Add username and homedir to generated password

- .golangci.yml
- oci/runtime_vm.go
- server/sandbox_network.go
Nakedret is a Go static analysis tool to find naked returns in functions
greater than a specified function length. This commit enables the linter
via golangci-lint and fixes issues on functions with a larger line
length of `15`.
> Add nakedret linter and related fixes

- vendor.conf
- vendor/github.com/containers/storage/drivers/overlay/overlay.go
- version/version.go
Pulled in the symlink fixes to containers/storage.
> [1.11] Vendor in containers/storage release-1.11

- lib/container_server.go
- lib/container_server_test.go
- lib/suite_test.go
- server/server.go
When cri-o is restarted, we were not returning an error if
an error ocurred when reading container state from disk. So
if the state.json file was corrupted or deleted in the meantime
the containers would be reporting an UNKOWN state and default
values for started time, created time, etc.
We now check for that and if a pod can't be restored, we delete the pod
as well as any containers associated with it. We also release the pod
and container names so that they can be used again.
We do the same for any containers that can't be restored.
> Fix logic of server.restore()

- .golangci.yml
- cmd/crio/main.go
- oci/runtime_vm.go
This commit fixes issues related to the `wrapperFunc` linter,
which detects function calls that can be replaced with convenience
wrappers.
> Add gocritic wrapperFunc linter and fixes

- .golangci.yml
- oci/runtime_oci.go
- server/useragent/useragent.go
- utils/utils.go
This commit fixes issues related to the `appendCombine` linter, which
detects `append` chains to the same slice that can be done in a single
`append` call.
> Add gocritic appendCombine linter and fixes
