contrib/test/integration/e2e.yml
@umohnani8 @rhatdan @giuseppe ptal.
=> [1.13] test: Retry flakes one more time

cmd/crio/main.go, docs/crio.conf.5.md, server/config.go, server/server.go
This is one possible solution to #2101 
=> Add support for host ip configuration

OWNERS
=> Add umohnani8 as an owner

contrib/test/integration/e2e.yml
Our tests are run on AWS.
This will fix issues we are seeing in #2104.
@umohnani8 @haircommander ptal.
=> test: Disable GCE PD tests

lib/stop.go
The old approach with the `if` block inside the `default` dates back to 9db7cf13 (#926), but there's no need for the extra level of nesting.  With this commit, we use the `switch` cases to handle that distinction.
=> lib/stop: Handle ContainerStateStopped with a switch case

version/version.go
=> Release 1.12.7

version/version.go
@rhatdan @giuseppe ptal
cc: @lsm5
=> Release 1.13.2

version/version.go
=> Release 1.12.8

lib/container_server.go, lib/container_server_test.go
This ports containers/libpod@69cb8639 (containers/libpod#2550) to CRI-O.
=> lib/container_server: Split locale at the first dot, etc.

version/version.go
=> Release 1.11.12

docs/crio.8.md
Add missing flags to the man page
Taking over https://github.com/kubernetes-sigs/cri-o/pull/1938
=> Update crio man page

contrib/test/integration/e2e.yml, oci/container.go, server/container_attach.go
Detach automatically on stdin EOF for a non-tty attach when stdin Once is not set.
=> [1.13] Fix detach non tty

pkg/storage/runtime_test.go
This PR should fix the mentioned issue.
Closes #2117
=> Improve pkg/storage/runtime unit tests

OWNERS
Wish everyone and cri-o well.. But my contributions to date have not been worthy of being in this esteemed maintainer list.
Cheers, Mike 
=> remove mike from owners list

version/version.go
@umohnani8 @haircommander @rhatdan ptal
=> Release 1.13.3

contrib/test/integration/e2e.yml, oci/container.go, server/container_attach.go
@umohnani8 @haircommander ptal.
=> [1.12] Fix detach non tty 

OWNERS
As discussed via mail with @mrunalp it would be a pleasure to me to serve as maintainer for cri-o. :pray:
I'm not sure if there is anything else needed than just modifying the OWNERS file. Let me know if I can do anything in particular. :innocent:
=> Add saschagrunert as owner

OWNERS
I haven't contributed to this project in quite a while, and so I think
it's no longer correct to catagorise me as a maintainer of the project.
So long and thanks for all the fish.
Signed-off-by: Aleksa Sarai <cyphar@cyphar.com>
=> OWNERS: remove Aleksa Sarai

lib/sandbox/sandbox.go, server/container_create.go, server/sandbox_network.go, server/sandbox_stop.go
=> [1.11] fix some race conditions with short lived pods

lib/sandbox/sandbox.go, server/container_create.go, server/sandbox_network.go, server/sandbox_stop_linux.go
=> [1.12] fix some race conditions with short lived pods

lib/sandbox/sandbox.go, server/container_create.go, server/sandbox_network.go, server/sandbox_stop_linux.go
=> [1.13] fix some race conditions with short lived pods

conmon/conmon.c
We don't want conmon to be killed.
@giuseppe @rhatdan @umohnani8 ptal.
=> conmon: Adjust OOM score to low value

version/version.go
=> version: 1.12.10

Dockerfile
=> [1.12] Fix integration test dependencies

Dockerfile
=> [1.13] Fix integration test dependencies

conmon/conmon.c
We don't want conmon to be killed
=> [1.12] conmon: Adjust OOM score to low value

conmon/conmon.c
We don't want conmon to be killed
=> [1.13] conmon: Adjust OOM score to low value

Dockerfile
=> [1.11] Fix travis integration

.golangci.yml, Makefile, cmd/crio/main.go, lib/config.go, lib/sandbox/memory_store_test.go, lib/sandbox/sandbox.go, oci/container.go, oci/oci_linux.go, oci/oci_unsupported.go, oci/runtime_oci.go, oci/stats.go, pkg/seccomp/seccomp_test.go, pkg/signals/signal.go, pkg/storage/image.go, pkg/storage/runtime.go, server/container_create.go, server/container_create_linux.go, server/rootless.go, server/sandbox_run.go, server/sandbox_run_linux.go, server/server.go, utils/fifo/handle.go, utils/utils.go, utils/utils_test.go
This PR adds the mentioned linters and their fixes within separate commits.
=> Add unparam, golint, gosec, scopelint, govet, unconvert and maligned linters

client/client.go, oci/runtime_oci.go, server/config.go, server/container_create.go, server/container_create_linux.go, server/sandbox_run.go
=> errors: do not capitalize error messages

version/version.go
@umohnani8 @haircommander ptal.
=> Release 1.13.4

Dockerfile
=> [1.10] Fix travis integration tests

oci/oci.go
=> [1.13] Fix possible out of bounds access during log parsing

.travis.yml, Dockerfile, README.md, cmd/crio/config.go, cmd/crio/main.go, conmon/Makefile, conmon/conmon.c, conmon/ctr_logging.c, conmon/ctr_logging.h, conmon/utils.c, conmon/utils.h, docs/crio.8.md, lib/config.go, lib/container_server.go, oci/oci.go, pkg/config/config.go, test/ctr.bats, test/helpers.bash
Allowed for user to flag --log-to-journal to log container output to journald as well as kubernetes logs (in conmon).
Backport to release 1.12
=> [1.12] Journald 12

lib/sandbox/sandbox.go, server/container_create.go, server/sandbox_network.go, server/sandbox_stop.go
=> [1.10] fix some race conditions with short lived pods

contrib/test/integration/e2e.yml
Our tests fail without increasing this limit.
@giuseppe ptal
=> test: Increase number of inotify user watches

cmd/crio/config.go, contrib/test/integration/build/cri-o.yml, contrib/test/integration/vars.yml
=> config: export manage_network_ns_lifecycle

README.md
=> readme: Update support matrix for 1.14

version/version.go
=> Tagging v1.11.13

oci/oci_linux.go, oci/runtime_oci.go, utils/utils.go
a couple of issues that prevented to work in rootless mode.  More details in each patch
=> rootless: fix rootless mode

contrib/test/integration/main.yml
=> test: Switch to go 1.12.2

.travis.yml
=> travis: Switch to go 1.12.x

vendor/github.com/containers/image/copy/copy.go, vendor/github.com/containers/image/docker/docker_client.go, vendor/github.com/containers/image/docker/docker_image.go, vendor/github.com/containers/image/docker/docker_image_dest.go, vendor/github.com/containers/image/docker/docker_image_src.go, vendor/github.com/containers/image/docker/tarfile/src.go, vendor/github.com/containers/image/ostree/ostree_src.go, vendor/github.com/containers/image/pkg/sysregistriesv2/system_registries_v2.go, vendor/github.com/containers/image/storage/storage_image.go, vendor/github.com/containers/image/storage/storage_reference.go, vendor/github.com/containers/image/storage/storage_transport.go, vendor/github.com/containers/image/version/version.go
Sync the vendored copy of github.com/containers/image to match the version intended in vendor.conf.
=> Re-sync github.com/containers/image

conmon/conmon.c
Some oom related backports for 1.11
=> [1.11] Oom backport

conmon/conmon.c
Some oom backports for release branch 1.13
=> [1.13] Various oom backports

conmon/conmon.c
Various oom backports for release 1.14
=> [1.14] various oom backports

conmon/conmon.c
Backport some oom changes to branch 1.12
=> [1.12] Various oom backports

lib/sandbox/sandbox_linux.go
Backport of: https://github.com/cri-o/cri-o/pull/2200
Cherry pick: 9abcfa0b5729a2979db23c6e7661ce60f3965eda
=> [1.14] Do not crash when netns is not set up

README.md
The link was broken, this fixes it :)
=> fix broken link to policy.json(5) in readme

version/version.go
=> Tag v1.13.6

server/sandbox_run_linux.go
The kubelet takes the memory limits of the containers running
in a pod and set is as the memory limit of the pod.
We were enforcing this minimum memory limit check during the
container creation time but not during the sandbox creation
time. Now we take the pod slice path and read the memory file
and double check that it is above the minimum memory limit.
Doing this also returns a correct error message when the memory
limit is too low, instead of the vague "signal killed" message.
=> [1.14] Add min memory limit check to sandbox_run_linux.go

conmon/conmon.c
Coverity is complaining about a leaded file descriptor, since
we never close dummyfd.
This change will close the dummyfd when the program exits.
=> Fix coverity scan problem

go.mod, go.sum, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go, vendor/github.com/opencontainers/runtime-tools/generate/config.go, vendor/github.com/opencontainers/runtime-tools/generate/generate.go, vendor/github.com/opencontainers/runtime-tools/validate/validate_linux.go, vendor/modules.txt
Pick up changes made to make setting ENV more efficient
=> Vendor update for runtime-tools

tutorials/setup.md
This PR addresses some left over comments from the first round of documentation fixes
=> round 2 of documentation fixes

server/sandbox_run_linux.go
Don't fail hard if we can't find a slice.
@umohnani8 ptal
=> [1.13] sandbox_run: Log a warning if we can't find a slice

server/config_test.go
This commit achieves  to keep the tests structure consistent and raises
the test coverage.
=> Migrate server config test to ginkgo

vendor/github.com/containers/storage/drivers/overlay/overlay.go
Pick up changes to overlay for recreating symlinks.
=> [1.13] Vendor containers/storage

version/version.go
@rhatdan @umohnani8 @haircommander ptal
=> Release  v1.13.7

docs/crio.8.md, lib/testdata/config.toml, server/fixtures/crio.conf, test/bin2img/bin2img.go
=> Remove references to kubernetes/pause image

server/image_fs_info_test.go, server/image_list_test.go, server/image_pull_test.go, server/image_remove_test.go, server/image_status_test.go, server/suite_test.go
This PR adds all image related unit tests to the server implementation, whereas the coverage should be 100%.
=> Add server image unit tests

version/version.go
=> Release 1.13.8

Dockerfile, test/network.bats
Update container and ansible dependencies for the CNI plugins as well as
two tests in test/network.bats.
=> Update CNI plugin test dependency to v0.7.5

conmon/ctr_logging.c
Update the function stub for printing to the journal
Fixes: #2327
=> conmon: fix cross-compilation

server/useragent/suite_test.go, server/useragent/useragent_test.go, server/useragent/version_info_test.go
This commit adds the useragent related server unit tests via a new test
suite.
=> Add useragent unit tests

cmd/crio/main.go
Hey, this is more or less a preparation PR to enable the `errcheck` linter later on. The tricky part is that closing the `crio.sock` automatically shuts down the `httpServer`, which should not harm the application logic, but implies skipping the `httpServer`s errors. I basically did:
- Update all necessary error handling paths to actually return an error
- Rename `s` and `srv` variables to `grpcServer` and `httpServer`
=> Improve error handling for crio main.go

server/sandbox_list_test.go, server/sandbox_remove_test.go, server/sandbox_run_test.go, server/sandbox_status_test.go, server/sandbox_stop_test.go, server/suite_test.go
This commit adds the unit tests for the server sandbox implementation.
=> Add server sandbox unit tests

server/sandbox_list_test.go, server/sandbox_remove_test.go, server/suite_test.go
This commit fixes the master unit-test build pipeline to let the sandbox server tests
succeed again.
=> Fix sandbox tests

version/version.go
@saschagrunert @umohnani8 @haircommander ptal
=> Release 1.14.1

README.md, awesome.md
The idea of an *Awesome List* about CRI-O was born as a follow up of #2337 and should help others to find input about their use cases.
We may add further links to this PR.
What do you think about it?
=> Add awesome list about CRI-O

test/helpers.bash
=> Remove debug output from integration tests

README.md
It isn't relevant anymore compared to version compat table.
=> readme: Remove roadmap

cmd/crio/config.go, cmd/crio/main.go, lib/config.go, lib/container_server.go, oci/oci.go, oci/oci_linux.go, oci/oci_test.go, server/sandbox_run_linux.go, test/cgroups.bats, test/helpers.bash
=> Add config to run conmon under a custom cgroup slice

tutorials/setup.md
=> tutorials/setup: fix broken link

README.md, tutorials/setup.md
Updated docs for easier copy/paste experience
=> refresh apt before installation

conmon/conmon.c
Add support for OOM handling when running in cgroup v2 unified mode.
Wait for notifications using inotify on the
/sys/fs/cgroup/$PATH/memory.events file.
On an inotify event read the "oom" counter from the same file.
Create an "oom" file each time the counter is different than the
previous known value.
Closes: https://github.com/containers/conmon/issues/8
=> conmon: support OOM monitor under cgroup v2

server/container_attach_test.go, server/container_create_test.go, server/container_exec_test.go, server/container_execsync_test.go, server/container_list_test.go, server/container_portforward_test.go, server/container_remove_test.go, server/container_reopen_log_test.go, server/container_start_test.go, server/container_stats_list_test.go, server/container_stats_test.go, server/container_status_test.go, server/container_stop_test.go, server/container_update_resources_test.go, server/container_updateruntimeconfig_test.go, server/sandbox_remove_test.go, server/suite_test.go
This PR adds unit tests to the container handling within the server implementation, which should increase the coverage.
=> Add container related server unit tests

oci/stats.go
PTAL @mrunalp @umohnani8 
Added build constraints on `oci/stats.go` and a new `oci/stats_32.go` for 32 bit.
build failures without the change: https://koji.fedoraproject.org/koji/taskinfo?taskID=35082648
build successful with the change: https://koji.fedoraproject.org/koji/taskinfo?taskID=35083204
fix build issues on x86 and 32-bit arm
=> fix build issues on x86 and 32-bit arm

contrib/test/integration/e2e.yml
=> test: skip runtimes handler test until we can get a better solution

contrib/test/integration/e2e-base.yml, contrib/test/integration/e2e-features.yml, contrib/test/integration/e2e.yml
Signed-off-by: Mrunal Patel mrunalp@gmail.com
=> test: set container runtime to remote for e2e and fixup crio.conf

contrib/systemd/crio-shutdown.service, contrib/systemd/crio.service
=> Update contrib systemd unit files to match project name

oci/stats.go
This PR simply forwardports #2409 to the master branch. :innocent:
=> Fix build issues on 32-bit architectures

lib/sandbox/sandbox_linux.go
The latest update of the internal CNI plugins package introduced some
unhandled errcheck lints. This is now fixed and unblocks the CI.
=> Fix errcheck lint for network namespace creation

oci/oci.go
Backport of #2419 for release-1.14.
=> [1.14] Fix runtime panic when having concurrent writes to runtime impl map

contrib/test/ci/cri-o.spec, contrib/test/ci/crio-metrics.sysconfig, contrib/test/ci/crio-network.sysconfig, contrib/test/ci/crio-storage.sysconfig, contrib/test/ci/crio.service, hack/build-rpms.sh, hack/lib/build/binaries.sh, hack/lib/build/rpm.sh, hack/lib/build/version.sh, hack/lib/constants.sh, hack/lib/init.sh, hack/lib/log/output.sh, hack/lib/log/stacktrace.sh, hack/lib/log/system.sh, hack/lib/util/ensure.sh, hack/lib/util/environment.sh, hack/lib/util/find.sh, hack/lib/util/misc.sh, hack/lib/util/text.sh, hack/lib/util/trap.sh, images/os/Dockerfile
Add a cri-o.spec to be able to build rpms with the
build-rpms.sh script. Also pull in some helper code
from openshift/origin to help in the rpm build process.
=> [1.13] Add logic for running OpenShift CI on cri-o PRs

contrib/test/ci/cri-o.spec, contrib/test/ci/crio-metrics.sysconfig, contrib/test/ci/crio-network.sysconfig, contrib/test/ci/crio-storage.sysconfig, contrib/test/ci/crio.service, hack/build-rpms.sh, hack/lib/build/binaries.sh, hack/lib/build/rpm.sh, hack/lib/build/version.sh, hack/lib/constants.sh, hack/lib/init.sh, hack/lib/log/output.sh, hack/lib/log/stacktrace.sh, hack/lib/log/system.sh, hack/lib/util/ensure.sh, hack/lib/util/environment.sh, hack/lib/util/find.sh, hack/lib/util/misc.sh, hack/lib/util/text.sh, hack/lib/util/trap.sh, images/os/Dockerfile
Add a cri-o.spec to be able to build rpms with the
build-rpms.sh script. Also pull in some helper code
from openshift/origin to help in the rpm build process.
=> [1.14] Add logic for running OpenShift CI on cri-o PRs

lib/config.go
To ensure we don't break upgrades, we set the default runtime to
runc if the default_runtime option in crio.conf is not set.
=> Default to runc is default_runtime is not set

version/version.go
Taking over https://github.com/cri-o/cri-o/pull/2428 since @mrunalp is out today.
=> [1.14] Tag v1.14.3

server/image_list.go, server/image_list_test.go
If images contain no tag or digest then they will now be stubbed with
`<none>:<none>` or `<none>@<none>` to fix invalid node configurations.
The functionality has been refactored into a dedicated function which
will be tested separately now.
Fixes: #2454
=> Fix missing image names on list

server/image_list.go
=> [1.14] Fix missing image names on list

version/version.go
=> Tag version 1.14.4

server/image_list.go
=> [1.13] Fix missing image names on list

tutorials/crictl.md
Fix a typo
Signed-off-by: Nitesh Konkar niteshkonkar@in.ibm.com
=> crictl.md: Fix a typo

test/command.bats, test/ctr.bats
$ bats -f "ctr log max with" test/ctr.bats
✓ ctr log max with default value
✓ ctr log max with minimum value
2 tests, 0 failures
$ bats -f "log max" test/command.bats 
✓ invalid log max
✓ log max boundary testing
2 tests, 0 failures
Signed-off-by: Alex Jia <chuanchang.jia@gmail.com>
=> tests: added log max test to ctr.bats and command.bats

.travis.yml
Signed-off-by: Nitesh Konkar niteshkonkar@in.ibm.com
=> Enable ppc64le Travis CI

hack/build-rpms.sh, images/os/Dockerfile
Make changes to the rpm build and Dockerfile for
running the e2e-aws tests.
=> [1.14] Changes to rpm build and Dockerfile for ci

hack/build-rpms.sh, images/os/Dockerfile
Make changes to the rpm build and Dockerfile for
running the e2e-aws tests.
=> [1.13] Changes to rpm build and Dockerfile for ci

OWNERS
I'm contributing to CRI-O for almost a year, helped maintain, debug, and improve. Other (most) contributions happen indirectly via the containers/image, c/storage, and c/libpod libraries.
This will ultimately allow me to approve Pull Requests and share some power across the continents :^)
@rhatdan @mrunalp @saschagrunert @umohnani8 @sboeuf @sameo PTAL
=> add vrothberg to OWNERS file

contrib/crio-wipe/README.md, contrib/crio-wipe/crio-wipe.bash, contrib/crio-wipe/crio-wipe.service, contrib/crio-wipe/helpers.bash, contrib/crio-wipe/lib.bash, contrib/crio-wipe/test.bats
This also includes a small bug fix which hasn't been backported yet, but is also not that urgent of a fix (small error when putting to stderr when invalid flag parsing happened)
=> [master] Add crio-wipe

contrib/crio-wipe/README.md
As described in https://github.com/cri-o/cri-o/pull/2471
=> crio-wipe: fix readme nits

version/version.go
=>  Tag v1.9.16

.circleci/config.yml
=> [1.11] backport empty circleCI config

version/version.go
=> Bump to v1.14.5

README.md, contrib/test/integration/main.yml, lib/container_server_test.go, tutorials/setup.md, version/version.go
Update deps and docs for release-15
=> Release 1.15.0

docs/crio.8.md, lib/config/config.go, server/container_create_linux.go, server/server.go
Backport of: #2558
Cherry-picked: 65632bac8c6b7d21f7fa2f999b48bc98080d1008
=> [1.15] Change default apparmor profile to actually contain the version

contrib/test/ci/cri-o.spec, contrib/test/ci/crio-metrics.sysconfig, contrib/test/ci/crio-network.sysconfig, contrib/test/ci/crio-storage.sysconfig, contrib/test/ci/crio.service
Added rpm files in `contrib/test/ci`
Run the regular test suite for rpm builds
@umohnani8 PTAL.
=> add rpm files in contrib/test/ci

contrib/test/ci/cri-o.spec, hack/build-rpms.sh, hack/lib/build/binaries.sh, hack/lib/build/rpm.sh, hack/lib/build/version.sh, hack/lib/constants.sh, hack/lib/init.sh, hack/lib/log/output.sh, hack/lib/log/stacktrace.sh, hack/lib/log/system.sh, hack/lib/util/ensure.sh, hack/lib/util/environment.sh, hack/lib/util/find.sh, hack/lib/util/misc.sh, hack/lib/util/text.sh, hack/lib/util/trap.sh, images/os/Dockerfile
Add build-rpms.sh scrip to build the cri-o rpm
that will be injected into the machine os content using the
Dockerfile to run the openshift e2e-aws test suite.
=> Add Dockerfile and update rpm spec for openshift e2e-aws tests

internal/oci/oci_linux.go
Don't create a cgroupfs cgroup when running with systemd as the cgroups
manager.
=> conmon cgroups: don't create cgroupfs group for systemd

contrib/test/integration/build/plugins.yml, contrib/test/integration/golang.yml, contrib/test/integration/main.yml
An approach to make the AMI tests work again as well as minor cleanups and updates.
/test ami
=> Fix AMI builds

README.md, internal/version/version.go, tutorials/setup.md
This is the partial forwardport of #2553
=> Update docs to point to 1.15

contrib/cni/README.md
Signed-off-by: Yeongju Kang <979156@gmail.com>
document changes 
I checked out 0.8.1 instead of using 0.7.4 and built it on fedora 30 container and debian 9 container.
doing same with markdown
document update using CNI plugin 0.8.1
=> version change from 0.7.4 to 0.8.1 released on June 6

cmd/crio/config.go, docs/crio.conf.5.md
Add missing `insecure_registries` and `bind_mount_prefix` to config template.
=> Add missing config template values

server/sandbox_run_linux.go, test/helpers.bash, test/network.bats
Don't fail hard if we can't find a slice.
Port of #2307 
=> [1.14] sandbox_run: Log a warning if we can't find a slice

lib/remove.go, oci/container.go, oci/oci_linux.go, server/sandbox_remove.go
Backports of:
*  #2601
*  #2587
=> [1.14] Fix 838 1.14

lib/remove.go, oci/container.go, oci/oci_linux.go, server/sandbox_remove.go
Backports of:
* https://github.com/cri-o/cri-o/pull/2601
* https://github.com/cri-o/cri-o/pull/2587
=> [1.15] cgroupfs fixes

docs/crio.8.md
Added missing options to the documentation and fixed the default values.
=> Fix documentation between crio.8.md and source

version/version.go
@haircommander @umohnani8 @rhatdan ptal.
=> Release 1.14.9

server/sandbox_run_linux.go, utils/utils.go
some other fixes for running on cgroups v2.
Also update libpod to import the possibility of creating new cgroups.
=> server: support cgroupv2

server/container_create_linux.go, test/ctr.bats, test/testdata/container_config_privileged.json
Set all OCI mounts as privileged when running in privileged mode.
Fixes: #2625
=> privileged: set mounts to rw

tutorials/setup.md
Signed-off-by: Palash Hariyani <phariyan@redhat.com>
Made some changes in the setup.md file under the Tutorials folder for the cgroup-manager setting.
=> Cgroup-hotfix in the Tutorials folder

awesome.md
This adds https://www.cncf.io/blog/2019/07/15/demystifying-containers-part-ii-container-runtimes to the awesome list.
=> Add CNCF article to awesome list

Dockerfile
a package changed names, and made make integration fail
=> fix make integration

README.md
Point to the correct `Container Runtime
Interface` link.
Signed-off-by: Nitesh Konkar niteshkonkar@in.ibm.com
=> Readme: Fix broken CRI link

server/container_create_linux.go
Set all OCI mounts as privileged when running in privileged mode.
Backport-of: d3a50d86f8803e21b9ff8e28d4d821bf677a70ac
=> [1.14] privileged: set mounts to rw

version/version.go
@haircommander @umohnani8 ptal
=> Release 1.14.10

Makefile
Signed-off-by: Lokesh Mandvekar <lsm5@redhat.com>
@mrunalp @haircommander @umohnani8 PTAL
=> allow custom go-md2man binary

Makefile, README.md, cmd/crio-status/main.go, completions/bash/crio-status, completions/fish/crio-status.fish, docs/crio-status.8.md, internal/client/client.go, server/inspect.go, test/helpers.bash, test/status.bats
The client API is now internal but we can provide a simple command line
interface for it.
=> Add crio-status client for convenient HTTP API access

internal/lib/sandbox/sandbox.go
Change the docs from IP to IPs.
=> Fix documentation for IP based sandbox methods

cmd/crio/main.go
Signed-off-by: ethan <guangming.wang@daocloud.io>
just fix message misspell error.
dictionary know.
=> main.go: flag help message error fix

README.md
fixes: https://github.com/cri-o/cri-o/issues/2713
=> Update fedora installation instructions

Makefile
We now use `-mod=vendor` instead of disabling go module support
entirely. The overall behavior should not change except that we are not
able to build CRI-O offline outside of the `$GOPATH`.
Fixes: https://github.com/cri-o/cri-o/issues/2680
Verified on `registry.fedoraproject.org/fedora:rawhide`:
```
[root@b05f712acca9 cri-o]# make
make: which: Command not found
mkdir -p "/cri-o/_output/src/github.com/cri-o"
ln -s "/cri-o" "/cri-o/_output/src/github.com/cri-o/cri-o"
touch "/cri-o/_output/.gopathok"
GO111MODULE=on go build -mod=vendor -ldflags '-s -w -X main.gitCommit="d099a35eb339a943399592fc4287dd65edadcca7" -X main.buildInfo=1564406100' -tags "containers_image_ostree_stub       seccomp selinux" -o bin/crio github.com/cri-o/cri-o/cmd/crio
GO111MODULE=on go build -mod=vendor -ldflags '-s …
```
=> Remove go module disabling and stick to `-mod=vendor`

Makefile
=> Makefile: Fixed go build command

contrib/test/integration/build/kubernetes.yml, contrib/test/integration/build/kubetest.yml, contrib/test/integration/e2e-features.yml, contrib/test/integration/e2e.yml, contrib/test/integration/golang.yml, contrib/test/integration/main.yml
and set --get false when calling e2e.test
=> [1.14] Download kubetest manually

contrib/test/integration/build/kubernetes.yml, contrib/test/integration/build/kubetest.yml, contrib/test/integration/e2e-features.yml, contrib/test/integration/e2e.yml, contrib/test/integration/golang.yml, contrib/test/integration/main.yml
and set --get false
this PR is an alternative approach to https://github.com/cri-o/cri-o/pull/2755 and https://github.com/cri-o/cri-o/pull/2754
set in 1.15 because it hasn't gotten any love yet
=> [1.15] download kubetest manually

contrib/cni/10-crio-bridge.conf, contrib/test/integration/build/kubernetes.yml, contrib/test/integration/build/kubetest.yml, contrib/test/integration/e2e-features.yml, contrib/test/integration/e2e.yml, contrib/test/integration/golang.yml, contrib/test/integration/main.yml
and set --get false, in the hopes that getting kubetest ourselves will fix CI woes
=> download kubetest manually

cmd/crio/main.go, contrib/test/integration/build/kubernetes.yml
to fix problem in update to etcd
as well as carry https://github.com/cri-o/cri-o/pull/2771 to fix grpc in kubelet
=> [1.15] e2e: clean kubernetes before making

version/version.go
=> Version 1.15.2

server/server.go, server/utils.go
First, attempt to find an IP address from /proc/net/route. If we fail to do so, attempt to find a clear primary
=> Allow default route to not be present

server/server.go
The `getHostIP` method does not fail any more because we now use the
local loopback address if no network is available and nothing else is
configured.
=> Fallback to 127.0.0.1 if host IP is unavailable

vendor.conf, vendor/github.com/containers/image/docker/docker_client.go
=> Vendor c/image cri-o-release-1.14

Makefile, contrib/test/integration/main.yml, hack/install-golangci-lint.sh
taking over https://github.com/cri-o/cri-o/pull/2828
cherry pick of https://github.com/cri-o/cri-o/pull/2825
but with an added fix for travis
=> [1.14] e2e: turn on force_clone for kubetest

server/sandbox_remove.go, server/server.go
@rphillips @haircommander @umohnani8 ptal
=> [1.14] sandbox_remove: Ensure that the pod infra container exit file is removed

server/sandbox_remove.go, server/server.go
@rphillips @haircommander @umohnani8 ptal
=> [1.13] sandbox_remove: Ensure that the pod infra container exit file is removed

server/sandbox_remove.go, server/server.go
@umohnani8 @haircommander ptal
=> [1.16] Remove pod infra exit file 

version/version.go
=> version: v1.14.11

internal/version/version.go
=> bump v1.16.0-rc1

.circleci/config.yml
Forwardport of: https://github.com/cri-o/cri-o/pull/2888
Cherry-picked: 7613b963495f89fc2314489335e1bb3c9c0df217
=> Remove docker layer cache from CI

contrib/test/ci/cri-o.spec
=> [1.16] Fix up conmon path in spec file

server/container_create_linux.go
This is a regression from 1.14.
=> [1.16] Set process label to privileged when host network is true

cmd/crio-status/main.go, cmd/crio/main.go, internal/pkg/criocli/completion.go
Both packages have the same purpose so we should merge them into one.
=> Move `completion` into `criocli` package

contrib/test/ci/cri-o.spec
@umohnani8 @haircommander PTAL
=> fix specfile for hack/build-rpms.sh

internal/version/version.go
=> Set master version to v1.17.0-dev

internal/version/version.go
=> bump to v1..16.0-rc2

.golangci.yml, cmd/crio/main.go, internal/lib/config/config.go, internal/oci/container.go, internal/oci/kill.go, internal/oci/runtime_oci.go, internal/oci/runtime_vm.go, internal/pkg/criocli/completion.go, internal/pkg/log/interceptors.go, server/container_create_linux.go, server/container_create_linux_test.go, server/inspect.go, server/naming.go, server/sandbox_run_linux.go, server/server.go, server/utils.go
The corresponding lints have been fixed as well.
=> Enable dogsled and whitespace linters

internal/pkg/criocli/criocli.go
=> [1.16] use metrics cli to configure config

.circleci/config.yml, Dockerfile, contrib/test/integration/main.yml, test/ctr.bats, test/image.bats
=> [1.16] bump to  critools 1.16

internal/version/version.go
@haircommander @umohnani8 @saschagrunert @rhatdan ptal
=> Release v1.16.0

README.md, tutorials/setup.md
Drop support for 1.12 and mention 1.16 to be up to date.
=> Update release versions in documentation

contrib/test/integration/disable_swap.yml, contrib/test/integration/e2e-base.yml
=> test: properly check return code of results

Makefile, pinns/Makefile, pinns/pinns.c, pinns/utils.h
@haircommander @umohnani8 ptal.
This is an initial just enough code to work version. I will clean it up.
=> Add pinns utility for pinning namespaces

awesome.md
The blog post has been release recently and should be part of our list.
=> Add vmblog about CRI-O to awesome list

contrib/test/integration/e2e-features.yml
The current features e2e test does not do anything at all, which should be fixed with this PR.
=> Fix test scope for e2e features

internal/version/version.go
@haircommander @saschagrunert @umohnani8 ptal
=> Release v1.16.1

test/network.bats, test/network_ping.bats
The ping pod tests removed all sandboxes after the test which caused a
race condition in removal of the pod sandbox. Isolating them and
removing only the sandboxes they created should fix that issue.
=> Deflake network integration tests

server/container_create_linux.go
fixes: https://github.com/cri-o/cri-o/issues/2996
=> [1.16] add rw mount of cgroup

server/container_create_linux.go
=> add rw mount of cgroup

server/sandbox_network.go
This adds two new metrics `network_setup_pod` and
`network_setup_overall` which provides a better way for network startup
time debugging.
Closes #2906
---
As a follow-up I suggest adding a documentation part about the available metrics and what they actually do.
=> Add network setup metrics

internal/version/version.go
=> Release v1.16.2

contrib/test/integration/system-packages.yml
as it is more efficient per the docs, as well as should :tm:  work for both python2 and 3
=> test: use dnf instead of package with loop

internal/lib/container_server.go, internal/lib/sandbox/namespaces.go, internal/lib/sandbox/namespaces_linux.go, internal/lib/sandbox/namespaces_test.go, internal/lib/sandbox/sandbox.go, pinns/pinns.c, server/container_create_linux.go, server/sandbox_run_linux.go
including changes to pinns to handle managing userns
=> managed namespaces: manage user ns

internal/lib/container_server.go, internal/lib/sandbox/sandbox.go, internal/oci/container.go, server/container_create.go, server/container_create_generic.go, server/container_create_linux.go, server/sandbox_list.go, server/sandbox_list_test.go, server/sandbox_remove.go, server/sandbox_run_linux.go, server/sandbox_status.go, server/sandbox_stop_linux.go
And do some other things to prepare for dropping the infra container.
~this is mostly a testing PR on top of https://github.com/cri-o/cri-o/pull/3063~
=> InfraContainer(): drop some unneeded calls

contrib/test/integration/golang.yml, contrib/test/integration/main.yml
=> [1.16] Use golang 1.13 

contrib/test/integration/main.yml
=> [1.17] Set k8s version to 1.17 for e2e and e2e-features tests

.circleci/config.yml, Makefile, contrib/test/integration/build/conmon.yml, go.mod, go.sum, scripts/build-test-image, vendor/github.com/containers/conmon/runner/config/config.go, vendor/modules.txt
@haircommander @umohnani8 @rhatdan @saschagrunert ptal
=> Update to conmon v2.0.9

contrib/test/ci/cri-o.spec, contrib/test/ci/crio-metrics.sysconfig, contrib/test/ci/crio-network.sysconfig, contrib/test/ci/crio-storage.sysconfig, contrib/test/ci/crio.service, hack/build-rpms.sh, hack/lib/build/binaries.sh, hack/lib/build/rpm.sh, hack/lib/build/version.sh, hack/lib/constants.sh, hack/lib/init.sh, hack/lib/log/output.sh, hack/lib/log/stacktrace.sh, hack/lib/log/system.sh, hack/lib/util/ensure.sh, hack/lib/util/environment.sh, hack/lib/util/find.sh, hack/lib/util/misc.sh, hack/lib/util/text.sh, hack/lib/util/trap.sh, images/os/Dockerfile
=> [1.17] Add logic for running openshift e2e-aws tests

Makefile
Signed-off-by: Xiaofeng Wang <wasphin@gmail.com>
Fix pinns path to remove.
=> Fix pinns path mismatch for install and uninstall

server/container_stats.go, server/container_stats_list.go
Follows PR #2942 
Show disk usage in the container stats
=> [1.14]: Add disk usage for ListContainerStats

.circleci/config.yml, Makefile, contrib/test/integration/build/plugins.yml, go.mod, go.sum, scripts/build-test-image, vendor/modules.txt
This updates CNI plugins to the latest version.
=> Update CNI plugins to v0.8.4

server/server.go
If a pod cannot be restored after restart, destroy the
pod network and release the IPs for fututre use
=> Destroy the pod's network when it can't be restored

server/container_create.go, server/sandbox_run_linux.go
=> [1.17] Check for context erroring before returning from longer requests

internal/version/version.go
=> Bump version to 1.17.0-rc1

completions/fish/crio.fish, docs/crio.8.md
Just a small fix to make the CI green.
=> [1.17] Fix generated docs for rc1 tag

README.md, tutorials/setup.md
@mrunalp @umohnani8 @haircommander @saschagrunert @vrothberg PTAL
=> update setup info for Debian, Raspbian and Ubuntu

server/container_create_linux.go
use a map to keep track of the different mode used by each mount when
running as readonly.
=> container_create_linux: refactor common code

server/image_list_test.go, server/image_pull_test.go, server/runtime_status_test.go, server/sandbox_remove_test.go, server/server_test.go
Just some small typos I saw during code review.
=> Fix typos in test descriptions

README.md, tutorials/setup.md
This updates our README as well as the tutorial to mention the latest release branch.
=> Mention latest release branch in docs

contrib/test/integration/build/crun.yml, contrib/test/integration/build/runc.yml, contrib/test/integration/main.yml, test/ctr.bats
backport of https://github.com/cri-o/cri-o/pull/2239
=> [1.15] run the tests using the crun runtime

.circleci/config.yml, scripts/circle-setup, test/cgroups.bats, test/critest.bats, test/ctr.bats, test/network_ping.bats
This way we don't need docker any more. :)
=> Run integration tests natively in CircleCI

server/container_create.go, server/sandbox_run_linux.go, server/server.go
We are seeing possible regressions from these fixes so reverting them.
=> [1.17] Revert net cleanup and ctx check

completions/fish/crio.fish, docs/crio.8.md, docs/crio.conf.5.md, internal/pkg/criocli/criocli.go, pkg/config/template.go
We should mention that the port is randomly selected if set to "0".
=> Add documentation about stream_port="0"

.circleci/config.yml, scripts/circle-setup, test/cgroups.bats, test/critest.bats, test/ctr.bats, test/network_ping.bats
=> [1.17] Run integration tests natively in CI

.circleci/config.yml, scripts/circle-setup, test/cgroups.bats, test/critest.bats, test/ctr.bats, test/network_ping.bats
Backport of https://github.com/cri-o/cri-o/pull/3133
=> [1.16] Run integration tests natively in CI

scripts/circle-setup, test/network_ping.bats
Disabling the firewall should help in that case.
=> Fix network ping integration test in CircleCI

pkg/config/config_test.go, test/image.bats
Beside that, I removed the digest test for architectures we do not test at all.
=> Fix integration tests by adjusting image digest

server/server.go, server/utils.go
If stream server address isn't specified, then we
should bind to all addresses.
=> stream server: Bind to all addresses

test/image.bats
manual pick of https://github.com/cri-o/cri-o/pull/3161
=> [1.17] fix integration tests

test/image.bats
=> [1.16] fix integration tests

README.md
Test PR to check what's up with e2e-aws.
=> [1.16] Update test grid

server/container_create_linux.go
The user setup code looks at the env to setup HOME.
Fixes #3186 
=> Setup container environment variables before user

go.mod, go.sum, vendor/github.com/containers/image/v5/docker/docker_client.go, vendor/github.com/containers/image/v5/docker/docker_image_dest.go, vendor/github.com/containers/image/v5/docker/docker_image_src.go, vendor/github.com/containers/image/v5/docker/tarfile/dest.go, vendor/github.com/containers/image/v5/docker/tarfile/src.go, vendor/github.com/containers/image/v5/image/docker_schema2.go, vendor/github.com/containers/image/v5/image/oci.go, vendor/github.com/containers/image/v5/internal/iolimits/iolimits.go, vendor/github.com/containers/image/v5/openshift/openshift.go, vendor/modules.txt
Signed-off-by: Valentin Rothberg rothberg@redhat.com
=> [1.16] update github.com/containers/image

go.mod, go.sum, vendor/github.com/containers/image/v5/docker/docker_client.go, vendor/github.com/containers/image/v5/docker/docker_image_dest.go, vendor/github.com/containers/image/v5/docker/docker_image_src.go, vendor/github.com/containers/image/v5/docker/tarfile/dest.go, vendor/github.com/containers/image/v5/docker/tarfile/src.go, vendor/github.com/containers/image/v5/image/docker_schema2.go, vendor/github.com/containers/image/v5/image/oci.go, vendor/github.com/containers/image/v5/internal/iolimits/iolimits.go, vendor/github.com/containers/image/v5/openshift/openshift.go, vendor/modules.txt
=> [1.17] update github.com/containers/image

go.mod, go.sum, lib/container_server_test.go, test/image.bats, vendor/github.com/containers/image/v5/docker/docker_client.go, vendor/github.com/containers/image/v5/docker/docker_image_dest.go, vendor/github.com/containers/image/v5/docker/docker_image_src.go, vendor/github.com/containers/image/v5/docker/tarfile/dest.go, vendor/github.com/containers/image/v5/docker/tarfile/src.go, vendor/github.com/containers/image/v5/image/docker_schema2.go, vendor/github.com/containers/image/v5/image/oci.go, vendor/github.com/containers/image/v5/internal/iolimits/iolimits.go, vendor/github.com/containers/image/v5/openshift/openshift.go, vendor/modules.txt
Signed-off-by: Valentin Rothberg rothberg@redhat.com
=> [1.15] update github.com/containers/image

version/version.go
Bump up version to 1.14.12 for a new release.
=> [1.14] Bump up version to 1.14.12

internal/version/version.go
Bump up version to 1.16.3 for a new release.
=> [1.16]  Bump up version to 1.16.3 

server/container_create_linux.go
=> [1.15] Set process label to privileged when host network is true

completions/fish/crio.fish, docs/crio.8.md, internal/version/version.go
=> bump to v1.17.0

version/version.go
Bump up version to 1.13.12 for a new release.
=> [1.13] Bump version to 1.13.12

version/version.go
Bump version to 1.15.3 for a new release.
=> [1.15] Bump version to 1.15.3

go.sum
=> Bump containers storage to v1.15.8

contrib/test/integration/build/crun.yml
=> contrib: use crun from the containers repository

bundle/Makefile, bundle/build
Fixes the missing binary in the bundle.
=> Add pinns binary to static bundle

README.md, tutorials/setup.md
=> [1.17] update installation info for debian and forks

README.md, tutorials/setup.md
Related: https://github.com/cri-o/cri-o/pull/3238
=> update installation info for debian and forks

internal/oci/runtime_oci.go
=> [1.17] exec: Close pipe fds to prevent hangs

internal/oci/runtime_oci.go
Cherry-pick of https://github.com/cri-o/cri-o/pull/3243
=> exec: Close pipe fds to prevent hangs

cmd/crio/main.go
=> [1.13] klog: don't write to /tmp

oci/runtime_oci.go, server/container_portforward.go
=> [1.14] port forward: drain the stream on error

contrib/test/integration/build/cri-o.yml, contrib/test/integration/build/crun.yml, contrib/test/integration/main.yml, contrib/test/integration/vars.yml, server/container_create_linux.go, test/ctr.bats, test/ctr_userns.bats, test/image_volume.bats, test/restore.bats
Depends on: https://github.com/openshift/aos-cd-jobs/pull/2113
=> contrib: add tests for cgroup v2

contrib/test/integration/main.yml, contrib/test/integration/vars.yml, test/helpers.bash
Trying to find out why the CI is broken for Fedora.
=> Fix Fedora based tests

server/container_create_linux.go
check once whether the hugetlb controller is enabled and store its
result.
=> cgroups: parse cgroup.controllers once

cmd/crio/wipe.go, completions/fish/crio.fish, docs/crio.8.md
=> wipe: Add a force flag for skipping version check

.circleci/config.yml
This seems the only way to force CircleCI to trigger jobs on tags.
=> Change CircleCI config to build all jobs for all tags

contrib/test/integration/main.yml
=> [1.18] Set k8s version to 1.18 for e2e and e2e-features tests

.circleci/config.yml, Makefile, bundle/build, bundle/test, bundle/vars
/kind cleanup
This adds a dedicated test for the release bundle we provide, which installs the bundle on the machine and runs a container workload on top of it.
None
None
```release-note
None
```
=> Add CI bundle tests

go.mod, go.sum, vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go, vendor/modules.txt
/kind bug
Fix 32bit build by vendoring opencontainers/selinux v1.3.3 
None
None
```release-note
None
```
=> Fix 32bit build by vendoring latest go-selinux

.circleci/config.yml, contrib/test/integration/build/conmon.yml, go.mod, go.sum, scripts/build-test-image, vendor/modules.txt
/kind cleanup
bumps conmon to version 2.0.11
none
none
```release-note
None
```
=> [1.17] bump to conmon 2.0.11

.circleci/config.yml, contrib/test/integration/build/conmon.yml, go.mod, go.sum, scripts/build-test-image, vendor/modules.txt
/kind cleanup
Bump conmon to v2.0.11
None
None
None
```release-note
None
```
=> [1.16] bump to conmon 2.0.11

.circleci/config.yml, Makefile
/kind cleanup
Update golangci-lint to the latest release and enable it based on our standard CI container.
None
None
```release-note
None
```
=> Update golangci-lint to v1.23.8

scripts/circle-setup
/kind cleanup
We can finally use the static binary because it contains all necessary build tags.
None
None
```release-note
None
```
=> Use static runc binary in CircleCI

server/container_portforward.go
=> [1.13] port forward: drain the stream on error

internal/lib/container_server.go
/kind cleanup
cherry pick of https://github.com/cri-o/cri-o/pull/3279
```release-note
NONE
```
=> Restore sandbox selinux labels directly from config.json

internal/storage/image.go, internal/storage/image_test.go
Favour the digest over the tag if both specified.
This is required for docker compatibility.
fixes #2351.
_Docker supports canonical image references (`repo/image:tag@sha`) that contain both a tag and an image ID. The latter is actually used for resolution. Despite its ambiguity this feature is used by tools like skaffold to ensure that the correct image version is used within k8s manifests and enforce rollouts even when the tag was overwritten (e.g. `skaffold dev`) while having the tag there as a hint/documentation.
A downside of this feature - as for image ID based resolution in general - is that, when the image ID is deleted from the registry somehow, an image rebuild will not help as long as you don't regenerate the manifests and do a rollout as well since the new image will usually …
=> Support pulling image specified by tag and digest.

pkg/container/container.go, pkg/sandbox/add_container.go, pkg/sandbox/create.go, pkg/sandbox/delete.go, pkg/sandbox/remove_container.go, pkg/sandbox/sandbox.go, pkg/sandbox/start.go, pkg/sandbox/stop.go
/kind design
Target of this PR is to find a common interface for sandbox creation. The `Creator` interface contains methods which should be called in order to successfully create a sandbox.
Please note that the return and parameters of the functions are still empty, those would have to be defined after we can agree on the general approach.
None
None
```release-note
None
```
=> Add high level Sandbox and Container interface

server/image_pull.go
/kind feature
When pulling images, then we were not able to handle locally build
images before this patch.
Now, the last fallback to `localhost/` prefixed images will be the node,
because it could be theoretically possible that a registry runs on
`localhost`.
Refers to https://github.com/kubernetes-sigs/cri-tools/issues/474
Drawback of this approach is that the new behavior ignores the
`imagePullPolicy` of Kubernetes in conjunction with `localhost/`
prefixed images. This might be not problematic since prefixing local
images with `localhost/` is a general paradigm from buildah/podman.
```release-note
- Take local images into account when pulling images prefixed with `localhost/`
```
=> Take localhost/ images into account during pull

tutorials/setup.md
- Add Table of Content to setup.md
- Minor adjustments
- Add CRI-O logo (Thanks to Tom Sweeney)
Signed-off-by: Douglas Schilling Landgraf <dougsland@gmail.com>
Add TOC to setup.md and improve documentation.
=> docs: add TOC to setup.md

.circleci/config.yml
/kind bug
We should not run the release notes generation on forks because the `GITHUB_TOKEN` is not available there.
None
None
```release-note
None
```
=> Skip release notes generation for forks

.circleci/config.yml, bundle/Makefile, bundle/README.md, bundle/build
/kind feature
This makes the bundle more universal and self-contained.
None
None
```release-note
- Added `conmon`, `runc` and `cni-plugins` to the static release bundle
```
=> Add runc, conmon, crictl and CNI plugins to bundle

contrib/test/integration/build/crun.yml
=> contrib: use crun 0.13

Makefile, internal/storage/runtime.go, pkg/config/config.go, server/sandbox_run_linux.go
/kind cleanup
This update fixes some freshly introduced lints during the linter upgrade.
None
None
```release-note
None
```
=> Update golangci-lint to v1.24.0

.circleci/config.yml, README.md, _config.yml, _layouts/default.html
We use the minimal jekyll theme and a README.md to have a base setup for GitHub pages.
None
Basically looks like this: https://saschagrunert.github.io/w/
```release-note
None
```
=> Add initial gh-pages layout

Makefile
/kind bug
Make sure all installed files are removed.
=> build: make uninstall improvements

.github/PULL_REQUEST_TEMPLATE.md
I think we can add those further kinds as we might want to apply them as well.
None
None
```release-note
None
```
=> Add further kinds to pull request template

.github/PULL_REQUEST_TEMPLATE.md
Since https://github.com/openshift/release/pull/7816 has been merged,
we're now free to use the label here.
None
None
```release-note
None
```
=> Add kind/dependency-change label

internal/oci/oci_linux.go
/kind bug
fixes cri stats for systemd cgroups
passing the slice directly to libpod.cgroups.Load() caused it to not be found. This is because it expected a fully qualified path, rather than a slice name.
write a function to translate slice name to path, and pass that down if we're using systemd cgroups
```release-note
Fixed a bug where systemd cgroups were incompatible with CRI stats endpoint
```
=> [1.18] stats: fix stats when systemd cgroups are used

hack/tree_status.sh
/kind cleanup
it is often the case that there's some git diff in hack/tree_status.sh in CI, but we don't know what it is. Fix this by printing it out when there is something different
```release-note
none
```
=> tree_status: show the git diff

OWNERS
/kind cleanup
I think this will allow us to approve changes on the gh-pages branch.
None
None
```release-note
None
```
=> Add OWNERS to gh-pages branch

server/image_pull.go, server/server.go
Backport of commit 38ba0945318a052d322e1274d1aebaefa5ac7b69.
To suit the needs of OpenShift CI [1], we need to avoid parallel pulls.
While we have an open PR against containers/image [2] to detect parallel
copy operations across processes, we are still far from getting this
merged; it must be split into smaller chunks and we plan to tackle in
the next few months but who knows how long this might take.
To support that in CRI-O, however, we enjoy the benefit of running a
daemon where we can easily avoid redundantly pulling the same image in
parallel as we're in the same process space and can do all
synchronisation in memory.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1785390
[2] https://github.com/containers/image/pull/611
/kind …
=> [release-1.17] avoid parallel pulls of the same image 

assets/css/style.scss
Allow a larger content width by overriding the default theme style.
None
None
```release-note
None
```
=> Fix gh-pages content width

internal/oci/oci_linux.go
/kind cleanup
fixes some style nits brought up in the 1.18 cherry pick of stats fixes
```release-note
None
```
=> stats: fix some style nits

internal/version/version.go
Do we have something for releases? @saschagrunert 
Release a new version of CRI-O with fixes.
Bumps up the version to 1.16.4
```release-note
Release CRI-O version 1.16.4
```
=> version: Release 1.16.4

internal/version/version.go
/kind feature
We now provide the linkmode to the `crio verison` subcommand output.
None
I also refactored the tabwriter printing to use reflection to be a bit more flexible.
```release-note
- Added `linkmode` (dynamic or static) output to `crio version` subcommand
```
=> Add linkmode to crio version output

.circleci/config.yml, README.md
We now add an additional badge to the README as well as a custom note
about the release notes.
None
None
```release-note
None
```
=> Add hint to release notes on gh-pages to README.md

internal/log/hook_filter.go, internal/oci/oci_linux.go, internal/oci/runtime_oci.go, internal/oci/runtime_vm.go, pkg/config/config.go, scripts/release-notes/release_notes.go, server/container_create.go, server/container_create_linux.go, server/sandbox_run_linux.go, server/secrets.go, server/server.go, utils/errdefs/grpc.go, utils/io/container_io.go, utils/utils.go
/kind cleanup
We should stick to a usual `errors.Wrap` if not format specifier is available.
None
```release-note
None
```
=> Do not Wrapf errors if no format is specified

completions/fish/crio.fish, docs/crio.8.md, internal/version/version.go
bumps to 1.17.2
```release-note
```
=> [1.17] bump to 1.17.2

test/ctr.bats
We now add a hint to the tested magic value in ctr bats to not forget
what it was.
References https://github.com/cri-o/cri-o/pull/3119#discussion_r397769485
None
```release-note
None
```
=> Add description to magic test value

Makefile
shfmt is shell format check.
Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>
Documentation
=> build: Makefile - add shfmt target to help

scripts/latest-version/latest_version.go
/kind bug
If the release branch tag contains none then we have to check for the
master branch before giving up. This fixes to have the right version
when creating release branches which contain no actual tag.
None
Relates to https://github.com/cri-o/cri-o/pull/3503
```release-note
None
```
=> Test for master tag if release branch contains none

internal/config/apparmor/apparmor_test.go
Just a typo fix to make the apparmor tests work
None
```release-note
None
```
=> Fix typo in apparmor tests

contrib/test/integration/build/cri-tools.yml, scripts/circle-setup, server/container_create_linux.go
/kind bug
Systemd expects to have /run, /run/lock, and /tmp
on tmpfs. It also expects to be able to write to
/sys/fs/cgroup/systemd and /var/log/journal.
```release-note
```
=> [1.16] Add the mounts that are required by systemd

.circleci/config.yml
It might be possible that we re-run the CI and the artifact already
exists. In that case we will not fail the `results` step.
None
None
```release-note
None
```
=> Skip already uploaded artifacts with gsutil

server/container_create_linux.go
/kind bug
Assuming hugetlb is supported by default means that cri-o is broken on debian's default kernel.
Fixes #3540.
Changed the `supportsHugetlb` default to `false`.
Implemented a `supportsHugetlb` check for cgroups v1.
```release-note
None
```
=> Assume hugetlb is not supported by default

.circleci/config.yml
/kind feature
We have every information we need in place in the results upload step so
we can upload the bundle to GitHub as well.
Refers to https://github.com/cri-o/cri-o/issues/3547
None
```release-note
None
```
=> Upload release bundle automatically to GitHub

pkg/sandbox/sandbox_setnameandid_test.go
We introduced some new lint reports with the latest merge which is now
fixed.
None
None
```release-note
None
```
=> Fix lint reports for setnameandid test

.circleci/config.yml, Makefile, contrib/bundle/Makefile, contrib/bundle/build, contrib/test/integration/e2e-base.yml, test/helpers.bash
/kind design
The config default should be in /etc/crio/crio.conf and not
in /etc/crio/crio.conf.d/00-defaults.conf.
```release-note
```
=> Move crio defaults back to /etc/crio/crio.conf

contrib/test/ci/cri-o.spec, contrib/test/ci/crio-metrics.sysconfig, contrib/test/ci/crio-network.sysconfig, contrib/test/ci/crio-storage.sysconfig, contrib/test/ci/crio.service, hack/build-rpms.sh, hack/lib/build/binaries.sh, hack/lib/build/rpm.sh, hack/lib/build/version.sh, hack/lib/constants.sh, hack/lib/init.sh, hack/lib/log/output.sh, hack/lib/log/stacktrace.sh, hack/lib/log/system.sh, hack/lib/util/ensure.sh, hack/lib/util/environment.sh, hack/lib/util/find.sh, hack/lib/util/misc.sh, hack/lib/util/text.sh, hack/lib/util/trap.sh, images/os/Dockerfile
=> [1.18] Add logic for running openshift e2e-aws tests

README.md
/kind cleanup
We now prefix entries which are non-release notes with `* ` to avoid
confusion in scripting.
None
None
```release-note
None
```
=> Fix README.md on gh-pages branch

internal/version/version.go
/kind feature
Bumps up the version to 1.16.6
```release-note
Release version 1.16.6
```
=> version: Release 1.16.6

docs/crio.8.md, docs/crio.conf.5.md, pkg/config/config.go
bumps pause image to 3.2
fixes https://github.com/cri-o/cri-o/issues/3571
```release-note
Default pause image is `k8s.gcr.io/pause:3.2`
```
=> bump default PauseImage to 3.2

README.md
We now add a badge which links directly to our continuous dependency
report.
None
None
```release-note
None
```
=> Add dependency report badge

internal/lib/sandbox/namespaces.go, internal/storage/runtime.go
/kind bug
Captures a couple more retErr fixes.
```release-note
```
=> couple more retErr fixes

.circleci/config.yml, Makefile, contrib/bundle/vars, contrib/kube-local/kube-local, scripts/versions, test/apparmor.bats, test/cni_plugin_helper.bash, test/crio-wipe/crio-wipe.bats, test/ctr.bats, test/helpers.bash, test/hooks/checkhook.sh, test/image.bats, test/image_remove.bats, test/network.bats, test/test_runner.sh
/kind cleanup
shellcheck is a fantastic shell files linter which is now enabled in our CI.
None
None
```release-note
None
```
=> Add shellcheck linter and apply fixes

.circleci/config.yml, Makefile, scripts/upload-artifacts
We do not need to filter on tags any more in CircleCI since this has no
influence on the build process.
Beside that, we fix the upload by moving the logic into a script and
setting the right bash execution parameters.
None
None
```release-note
None
```
=> Fix GitHub artifact upload via new upload-artifacts target

internal/oci/oci_linux.go
critest tests the stats endpoint by creating a cgroupless container and querying the stats of it. Unfortunately, this doesn't really work, because we gather ctr stats from the cgroup.
Work around this by returning a minimal stats structure when the container does not have a cgroup parent
unblocks https://github.com/cri-o/cri-o/pull/3520
```release-note
```
=> stats: spoof stats on a cgroupless ctr

README.md, contrib/test/integration/main.yml, tutorials/setup.md
Update the docs to mention the release-1.18 branch.
None
```release-note
None
```
=> Add release-1.18 reference to documentation

completions/fish/crio.fish, docs/crio.8.md, internal/version/version.go, server/container_create_linux.go
/kind bug
as title says, as well as pull in https://github.com/cri-o/cri-o/pull/3607
```release-note
```
=> bump to version 1.17.4

Makefile, scripts/release-notes/release_notes.go
Fixing the CircleCI pipeline for this branch.
None
None
```release-note
None
```
=> [1.18] Fix CI

internal/version/version.go
> /kind bug
> /kind design
> /kind flake
```release-note
```
=> [1.18] bump to version 1.18.0

test/image.bats
fix test failures found [here](https://storage.googleapis.com/origin-federated-results/pr-logs/pull/cri-o_cri-o/3641/test_pull_request_crio_integration_rhel/11578/artifacts/testout.txt) 
```release-note
```
=> test: update image digest to fix test

test/image.bats
round 2!
Before, the image pull and list by manifest list tag test was failing because of the wrong digest
because this has happened twice today, also update the test to inform us the value it should be
```release-note
```
=> test: update digests and test

test/image.bats
Now the pipeline should be green again.
None
```release-note
None
```
=> Fix incorrect image digest for test image

test/image.bats
also update the test to inform us the value it should be
cherry picks of https://github.com/cri-o/cri-o/pull/3652  https://github.com/cri-o/cri-o/pull/3649 and https://github.com/cri-o/cri-o/pull/3643, all squashed together because they have essentially the same commit message
```release-note
```
=> [1.17] test: update image digest to fix test

test/image.bats
also update the test to inform us the value it should be
cherry picks of https://github.com/cri-o/cri-o/pull/3652  https://github.com/cri-o/cri-o/pull/3649 and https://github.com/cri-o/cri-o/pull/3643, all squashed together because they have essentially the same commit message
```release-note
```
=> [1.18] test: update image digest to fix test

README.md
we only support n-3 versions. now that 1.18 is out, let's drop support through 1.15
```release-note
```
=> readme: drop support for unsupported branches

contrib/test/integration/build/runc.yml, contrib/test/integration/main.yml, scripts/circle-setup, server/container_create_linux.go, test/pod.bats, test/testdata/container_config_sleep.json
To address
* kubernetes/kubernetes#77873
backport
* https://github.com/cri-o/cri-o/pull/3328
/kind-bug
=> [1.17] CreateContainer: pass TerminationGracePeriod

internal/lib/container_server.go, internal/lib/container_server_test.go, internal/lib/sandbox/namespaces_test.go, internal/lib/sandbox/sandbox_test.go, internal/lib/suite_test.go, internal/oci/container.go, internal/oci/container_test.go, internal/oci/suite_test.go, server/container_create_linux.go, server/inspect_test.go, server/sandbox_run_linux.go
/kind cleanup
drops the container level privileged flag, as it was unused
```release-note
none
```
=> [1.17] oci: drop container level privileged flag

README.md
Adds installation steps for CentOS
None (that I know of)
None
```release-note
None
```
=> add installation steps for CentOS

test/ctr.bats
the test is failing and this fixes it and I'm not sure why it was passing at all. today is confusing
```release-note
```
=> test: check for rw mounts

test/ctr.bats, test/image.bats
backports https://github.com/cri-o/cri-o/pull/3667 and https://github.com/cri-o/cri-o/pull/3661/ 
```release-note
```
=> [1.16] backport ci fixes

hack/build-rpms.sh
=> [1.16] Disable the extra-source when building the rpm.

server/container_create.go, server/sandbox_run_linux.go
/kind cleanup
This will ensure that we do all the clean up when we timeout.
```release-note
```
=> Return an error if context has been cancelled or deadline exceeded

go.mod, go.sum, vendor/github.com/containers/libpod/cmd/podman/cliconfig/config.go, vendor/github.com/containers/libpod/libpod/healthcheck.go, vendor/github.com/containers/libpod/libpod/runtime.go, vendor/github.com/containers/libpod/pkg/rootless/rootless_linux.c, vendor/github.com/containers/libpod/pkg/rootless/rootless_linux.go, vendor/github.com/containers/libpod/version/version.go, vendor/modules.txt
Pull in changes to support systemd selinux labels
```release-note
```
=> Vendor in v1.9.1 containers/libpod

tutorials/setup.md
Provide additional installation options by using Ansible with https://github.com/alvistack/ansible-role-cri_o from source code.
Fixes #3552
```release-note
```
=> Add Installation Guide with Ansible

internal/lib/container_server.go, internal/lib/container_server_test.go, internal/lib/sandbox/namespaces_test.go, internal/lib/sandbox/sandbox_test.go, internal/lib/suite_test.go, internal/oci/container.go, internal/oci/container_test.go, internal/oci/suite_test.go, server/container_create_linux.go, server/inspect_test.go, server/sandbox_run_linux.go, server/suite_test.go
/kind cleanup
drops the container level privileged flag, as it was unused
```release-note
none
```
=> oci: drop container level privileged flag

oci/runtime_oci.go, server/container_status.go, test/ctr.bats, test/image.bats, version/version.go
/kind bug
as well as ci tests and bump to the final version of 1.15
```release-note
ContainerStatus no longer waits for a container operation (such as start or stop) to finish.
```
=> [1.15] server/ContainerStatus: don't lock for c.State() and some friends

README.md
Adds Ubuntu 20.04 to install instructions
Related to #3629
N/A
```release-note
None
```
=> Adds Ubuntu 20.04 to install instructions

internal/lib/container_server.go, internal/lib/container_server_test.go, internal/lib/sandbox/namespaces_test.go, internal/lib/sandbox/sandbox_test.go, internal/lib/suite_test.go, internal/oci/container.go, internal/oci/container_test.go, internal/oci/suite_test.go, server/container_create_linux.go, server/inspect_test.go, server/sandbox_run_linux.go, server/suite_test.go
/kind cleanup
drop unused struct field
```release-note
```
=> [1.18] oci: drop container level privileged flag

tutorials/setup.md
Missing `cd ~/.ansible/roles` Before `git clone`
Fixes https://github.com/cri-o/cri-o/issues/3552
Fixes https://github.com/alvistack/ansible-role-cri_o/issues/1
```release-note
```
=> Missing `cd ~/.ansible/roles` Before `git clone`

server/container_create_linux.go
/kind bug
lack of hugetlb support in the kernel should not be a fatal error in cgroupv1.
this PR patches the error in 1.18. https://github.com/cri-o/cri-o/pull/3565 will fix it in master
fixes https://github.com/cri-o/cri-o/issues/3717
```release-note
Fix a bug where CRI-O could not start a container if CONFIG_CGROUP_HUGETLB was not set in the kernel
```
=> [1.18] make lack of hugetlb support non-fatal for cgroupv1

internal/oci/oci.go
/kind bug
In Runtime#DeleteContainer, when the impl was not found in the runtimeImplMap, there is no need to take write lock on the map at the end of the method.
Assuming the get from runtimeImplMap at beginning of DeleteContainer() returns nothing, the deferred func shouldn't remove map entry someone else puts in the map.
```release-note
None
```
=> Avoid unnecessary locking on runtimeImplMap

Makefile
/kind cleanup
allow customization of go commands
package maintainers may run into situations where they want to override the `go build` command when running make. Let's allow them, as well as allow them to override the other GO commands
```release-note
```
=> Makefile: allow customization of go commands

.golangci.yml, Makefile
Update golangci lint to the latest release
None
None
```release-note
None
```
=> Update golangci lint to v1.26.0

server/container_create_linux.go
/kind bug
If createSandboxContainer returns non-nil error, we should stop the container.
This is backport of #3607
```release-note
None
```
=> [release-1.16] Stop container when there is error in createSandboxContainer

cmd/crio/wipe.go
/kind bug
> /kind design
> /kind flake
those Infof calls saying "wiping x" were meant to be printed once. instead, they're printed every single container/image
```release-note
```
=> crio wipe: log less

internal/version/version.go
as title says
```release-note
```
=> [1.18] bump to v1.18.1

.circleci/config.yml, .gitignore, Makefile, contrib/bundle/Makefile, contrib/bundle/build, nix/default.nix, nix/nixpkgs.json, test/version.bats, tutorials/setup.md
/kind cleanup
Recent changes in the upstream package require us to take action on
naming and the build process of the static binary. This commit changes
everything necessary to stay in sync with nixpkgs.
None
None
```release-note
None
```
=> Update nix image and dependencies

scripts/release-notes/release_notes.go
/kind feature
This changes the release notes generation script to also work for
release branches.
None
Needs a forward-port to the master branch as well.
```release-note
None
```
=> [1.18] Allow release notes for release branches

internal/lib/sandbox/sandbox_linux.go
Signed-off-by: Olena Volotska <ovolotska@lyft.com>
/kind bug
After https://github.com/containernetworking/cni was updated to v0.8.2, network namespace management was moved to container runtime.  Unmount code as shown in this example was not moved over https://github.com/containernetworking/plugins/commit/a0eac8d7d990adc7621e6ac0adf8b351e6e6c34b#diff-4d866d7b5450b9c19b2c89c7e90ec8e0R135
https://github.com/cri-o/cri-o/issues/3736
```
None
```
=> [1.16] unmount network namespace on remove

tutorials/kubeadm.md
/kind bug
> /kind design
> /kind flake
This will fix the documentation error for creating kubeadm cluster
```release-note
NONE
```
=> Fix the kubeadm command

internal/oci/runtime_oci.go, server/container_create.go, server/container_remove.go, server/container_start.go, server/container_stop.go, server/sandbox_remove.go, server/sandbox_run_linux.go, server/sandbox_stop_linux.go
/kind cleanup
This PR cleans up the default info logging.
```release-note
Cleanup default info logging
```
=> Cleanup default info logs

server/sandbox_status.go, server/sandbox_status_test.go, server/suite_test.go
/kind cleanup
Adds additional test for sandbox status verbose mode.
```release-note
None
```
=> Add test for sandbox status verbose mode

Makefile, contrib/test/ci/cri-o.spec, contrib/test/ci/crio-metrics.sysconfig, contrib/test/ci/crio-network.sysconfig, contrib/test/ci/crio-storage.sysconfig, contrib/test/ci/crio.service, hack/build-rpms.sh, hack/lib/build/binaries.sh, hack/lib/build/rpm.sh, hack/lib/build/version.sh, hack/lib/constants.sh, hack/lib/init.sh, hack/lib/log/output.sh, hack/lib/log/stacktrace.sh, hack/lib/log/system.sh, hack/lib/util/ensure.sh, hack/lib/util/environment.sh, hack/lib/util/find.sh, hack/lib/util/misc.sh, hack/lib/util/text.sh, hack/lib/util/trap.sh, images/os/Dockerfile
Not a failing test, but adding a new test.
Add the various specfile and Dockerfile needed to run the e2e-aws tests on PRs in the release-1.19 branch.
```release-note
```
=> [1.19] Add logic for running openshift e2e-aws tests

server/image_pull.go, server/image_status.go
/kind cleanup
This PR adds Info logs for image status and pull CRI calls.
```release-note
Added info logs for image pulls and image status
```
=> Add info logs for image pull and status CRI calls

pkg/container/container.go, pkg/container/container_privileged_test.go, pkg/container/container_setconfig_test.go, pkg/container/container_setnameandid_test.go, server/container_create.go, server/container_create_linux.go, server/container_create_unsupported.go
/kind design
This involves storing the sandbox and container configs.
Eventually, more of the logic happening in createSandboxContainer will happen inside of the container interface, so this prepares to make that move
```release-note
```
=> server: store container privilege bool in pkg/container

internal/oci/runtime_oci.go
/kind bug
In runtimeOCI#AttachContainer, if closeErr is not nil, there would be two writes into the stdinDone channel (and the closeErr may preempt utils.DetachError).
this PR makes sure that only one error is written to the channel.
```release-note
None
```
=> Send only single error to stdinDone

internal/config/ulimits/suite_test.go, internal/config/ulimits/ulimits.go, internal/config/ulimits/ulimits_test.go, pkg/config/config.go, server/container_create_linux.go, server/sandbox_run_linux.go, server/utils.go
/kind design
In a similar fashion to cgroups, seccomp and apparmor, add a ulimit package.
This way, we don't recreate the slice of ulimits each container creation, and
have more complete error validation on server start
```release-note
```
=> config: add ulimits package

contrib/test/integration/build/runc.yml, contrib/test/integration/main.yml, server/naming_test.go
updates runc to 1.0.0-rc10
fixes some ansible and makes comments setting expectation about what jobs are run when
cherry-picks https://github.com/cri-o/cri-o/pull/3761/commits/1aaae410f17bd82656ea360c365d2b403518692d
```release-note
```
=> [1.16] a handful of test fixes

contrib/test/integration/main.yml
including:
make runc build on every test (instead of only on AMI builds)
reorder some things
```release-note
```
=> [1.17] test: refactor some of main.yml

pkg/container/container.go, pkg/container/container_log_path_test.go, pkg/container/container_setnameandid_test.go, server/container_create.go, server/container_create_linux.go, server/sandbox_run_linux.go, test/ctr_seccomp.bats, utils/utils.go
/kind cleanup
move logic for configuring logPath to pkg/container
refactor SetNameAndID to use internal sboxConfig (tech debt from previous PR)
move EnsureSaneLogPath to utils because we need to share between packages
```release-note
```
=> pkg/container: handle logPath

internal/version/version.go
/kind feature
Some important fixes are part of the release branch and I guess we're ready for a new release, right?
None
None
```release-note
None
```
=> [1.18] Bump version to v1.18.2

internal/criocli/criocli_test.go
The error has not been checked which is now the case to make the linter
happy.
None
None
```release-note
None
```
=> [1.18] Fix lint issue in criocli_test.go

server/container_create_linux.go
=> server: re-add gocyclo skip

Makefile, contrib/test/ci/cri-o.spec, contrib/test/ci/crio-metrics.sysconfig, contrib/test/ci/crio-network.sysconfig, contrib/test/ci/crio-storage.sysconfig, contrib/test/ci/crio.service, hack/build-rpms.sh, hack/lib/build/binaries.sh, hack/lib/build/rpm.sh, hack/lib/build/version.sh, hack/lib/constants.sh, hack/lib/init.sh, hack/lib/log/output.sh, hack/lib/log/stacktrace.sh, hack/lib/log/system.sh, hack/lib/util/ensure.sh, hack/lib/util/environment.sh, hack/lib/util/find.sh, hack/lib/util/misc.sh, hack/lib/util/text.sh, hack/lib/util/trap.sh, images/os/Dockerfile
Not a failing test, but adding a new test.
Add the various specfile and Dockerfile needed to run the e2e-aws tests on PRs in the master branch as we automatically forward all master PRs to the 1.19 branch for now.
```release-note
```
=> Add logic for running openshift e2e-aws tests

server/container_create_linux.go, server/sandbox_run_linux.go
/kind bug
Although the current code does apply the correct label, it does it too
late, after the Sandbox has been created and the processes already being
ran.
None
Testing this PR is not something easy without a previously setup environment.
As I have one handy, please, let me know via a private message and I can give you access to it.
```release-note
None
```
=> runtime_vm: Apply the correct label before the sandbox is created

contrib/test/integration/main.yml
as kube now requires it
```release-note
```
=> test: bump go version to 1.14.4

contrib/test/integration/main.yml
:upside_down_face: 
```release-note
NONE
```
=> [1.18] test: build off of release-1.18 and with golang 1.14.4

scripts/release-notes/release_notes.go
/kind feature
The release notes generator now sets the download variables correctly on tags.
None
None
```release-note
None
```
=> Make release notes generator capable of handling tags

contrib/test/integration/build/kubernetes.yml, contrib/test/integration/e2e-base.yml
This reverts commit 0a2c92d17ec060cf14178f16dc9f9edbeaca1775, because upstream kube PR landed
```release-note
none
```
=> test: drop cgroupfs override

internal/oci/runtime_oci.go
/kind cleanup
```release-note
```
=> [1.18] oci: add debug logs for runtime state calls

internal/oci/runtime_oci.go
/kind cleanup
```release-note
none
```
=> oci: add debug logs for runtime state calls

contrib/test/integration/build/kubernetes.yml, contrib/test/integration/e2e.yml, contrib/test/integration/main.yml, server/container_create_linux.go, server/sandbox_run_linux.go, server/server.go, test/pod.bats
> /kind bug
> /kind design
> /kind flake
```release-note
```
=> contrib, cgroup v2: use kubernetes master

.circleci/config.yml, scripts/circle-setup-cgroup_manager, test/cgroups.bats
Add a suite of tests in circle that run the integration tests against cgroupfs, to sanity check it
```release-note
```
=> test: add circle job that runs with cgroupfs

internal/oci/runtime_oci.go
/kind bug
In runtimeOCI#ReopenContainerLog, if the goroutine receives watcher error, we would execute the following (around line 1059):
```
case err := <-errorCh:
```
where the done channel is not closed.
This PR moves the closing of done channel to the main goroutine so that done channel is always closed.
```release-note
None
```
=> Close the done channel in runtimeOCI#ReopenContainerLog

internal/version/version.go
=> bump to version 1.18.3

contrib/test/integration/e2e-features.yml
Let's see if we can enable more `Feature.*` tests.
None
None
```release-note
None
```
=> Enable more feature tests

pkg/container/container.go, pkg/container/container_test.go, server/container_create_linux.go, server/sandbox_run.go, server/sandbox_run_linux.go, utils/utils.go
/kind cleanup
Further the work moving contents of createPodSandbox() to the container pkg. These options were only a couple of lines each, most of the changes come from adding unit tests for the cases.
```release-note
```
=> container: move some relatively low hanging options

server/container_start.go
/kind bug
> /kind design
> /kind flake
Restore the CPU load balancing under the `StartContainer`
only in the case of an error.
```release-note
NONE
```
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
=> Restore CPU load balancing just when an error appears

internal/runtimehandlerhooks/high_performance_hooks.go, internal/runtimehandlerhooks/high_performance_hooks_test.go
Unblocks the CI on the master branch.
None
None
```release-note
None
```
=> Fix gofumpt lints

internal/lib/container_server_test.go, test/mocks/containerstorage/containerstorage.go, test/mocks/oci/oci.go
Fixing the not-failing unit test as well as re-generating the mocks around it.
None
None
```release-note
None
```
=> Fix unit-tests and regenerate mocks 

test/mocks/containerstorage/containerstorage.go, test/mocks/oci/oci.go
Fixing the CI by regenerating the mock files.
None
None
```release-note
None
```
=> [1.18] Regenerate mocks to fix the CI

internal/oci/runtime_oci.go
/kind cleanup
checks for an error when reporting there was an error
```release-note
none
```
=> [1.17] port error: check for error

oci/oci.go
Fixes #3988
> /kind bug
> /kind design
> /kind flake
```release-note
none
```
=> [1.11] Copy spec to not touch original spec on exec(sync)

internal/lib/sandbox/namespaces.go, internal/oci/oci.go, internal/oci/runtime_oci.go, internal/oci/runtime_vm.go, internal/pkg/storage/runtime.go, server/container_create.go, server/container_create_linux.go, server/sandbox_network.go, server/sandbox_run_linux.go, utils/io/helpers.go
/kind bug
pick of https://github.com/cri-o/cri-o/pull/3596 and https://github.com/cri-o/cri-o/pull/3964
```release-note
none
```
=> [1.17] replaces checks in defers from err to retErr

contrib/cni/11-crio-ipv4-bridge.conf, contrib/cni/README.md
including reordering some of the contents, and specify how to run with ipv6 disabled
fixes https://github.com/cri-o/cri-o/issues/3437
```release-note
none
```
=> docs: fix cni documentation

internal/oci/runtime_vm.go
If not set it may result in silently ignored probes by the kubelet
Fixes: https://github.com/kata-containers/runtime/issues/2769
Signed-off-by: Snir Sheriber <snir911@gmail.com>
/kind bug
Fixes: https://github.com/kata-containers/runtime/issues/2769
Fixes: https://github.com/kata-containers/runtime/issues/2769
```release-note
None
```
=> runtime_vm: set container creation time

cmd/crio/wipe.go, go.mod, internal/client/client.go, internal/config/seccomp/seccomp.go, internal/lib/container_server.go, internal/lib/rename.go, internal/oci/container.go, internal/oci/runtime_oci.go, internal/storage/runtime.go, internal/version/version.go, server/container_create_linux.go, server/container_status.go, server/image_status.go, server/inspect.go, server/sandbox_run_linux.go, server/sandbox_status.go, test/restore.bats, utils/typeurl/types.go, vendor/modules.txt
/kind cleanup
faster json encoding/decoding and better usage of memory since buffers can be added to a pool.
```release-note
NONE
```
=> crio: use json-iterator/go instead of encoding/json

internal/oci/runtime_oci.go
/kind cleanup
> /kind design
> /kind flake
many times TempFiles are not closed, and a couple of cases not removed.
Let's clean up after ourselves.
```release-note
none
```
=> exec sync: be more careful about temp files

internal/lib/sandbox/memory_store.go, internal/oci/memory_store.go
/kind cleanup
Just a small cleanup to remove unused code
None
None
```release-note
None
```
=> Remove unused global vars in memory storer

contrib/test/integration/build/crun.yml
/kind  cleanup
> /kind bug
> /kind design
> /kind flake
```release-note
NONE
```
=> contrib: update the crun version to the last release

internal/config/cgmgr/cgmgr_test.go
Makes the CI happy again.
None
None
```release-note
None
```
=> Fix lint pipeline by gofumpt'ing cgmgr_test.go

internal/runtimehandlerhooks/high_performance_hooks.go, server/container_create_linux.go
/kind cleanup
Optimize and/or improve readability of some code I came across. Please see individual commits for details.
```release-note
NONE
```
=> Various nits

README.md, install.md, tutorial.md, tutorials/install-distro.md
=> docs: update installation instructions

.golangci.yml, Makefile
/kind cleanup
Bump golangci lint to the latest version and adapt the config.
None
None
```release-note
None
```
=> Bump golangci-lint to v1.30.0

contrib/test/integration/main.yml, go.mod
k8s 1.19 is going to release with go 1.15
```release-note
Compile with go 1.15
```
=> Switch to go 1.15

server/container_create_linux.go
/kind bug
If the container is not privileged, mask the /sys/dev
path so that we don't leak extra devices in a container.
Fixes #1772993 (https://bugzilla.redhat.com/show_bug.cgi?id=1772993)
```release-note
None
```
=> Add /sys/dev as a masked path

server/container_create.go
/kind cleanup
This avoids code duplication since those new constants have been added
in v1.19.0.
None
None
```release-note
None
```
=> Reuse Kubernetes API consts for seccomp profiles

internal/oci/oci_linux.go
/kind bug
Commit 512fdb2f9f49 (PR #3115) mistakenly used the value of total_inactive_file
from the top-level cgroup, thus the working set value was either
wrong (too low) or invalid (negative), for example:
> Unable to account working set stats: total_inactive_file (1572753409)
> memory usage (585728)" file="oci/oci_linux.go:93"
We need to use total_inactive_file and memory.usage_in_bytes from
the same cgroup, otherwise it does not make any sense.
While at it
- promote the above message from debug to warning;
- optimize getTotalInactiveFile() by using HasPrefix()
rather than Contains().
None
```release-note
Fix working set calculation
```
=> oci_linux: fix working set calculation

completions/fish/crio.fish, docs/crio.8.md, internal/version/version.go
/kind feature
As per [discussion on slack](https://kubernetes.slack.com/archives/CAZH62UR1/p1597731777052600?thread_ts=1596737524.037600&cid=CAZH62UR1), where ready to release a new version on release-1.17.
None
None
```release-note
None
```
=> Bump to v1.17.5

internal/lib/sandbox/namespaces_linux.go, internal/lib/sandbox/sandbox.go
/kind bug
The mount.Mounted check is super expensive, as it has to parse the whole
nine yards of /proc/self/mountinfo, which is slow and sometimes racy
(for latter, see https://github.com/kolyshkin/procfs-test).
It is much simpler and faster to just try unmount, and ignore EINVAL
error. Note that EINVAL might be returned if the argument is not a mount
point, or if flags are wrong. Since the flags is hardcoded here, the
code will only get EINVAL in case the path is not mounted.
This should speed things up a little, and fix an occasional case of real
mount not being unmounted because of the mountinfo race.
Also, since we do not check the path in mountinfo, and umount(2) deals
just fine with symlinks, we no longer need to resolve the path, so
remove the path cleaning code (which in fact …
=> Use Unmount w/o prior Mounted check

test/apparmor.bats, test/ctr.bats, test/ctr_seccomp.bats, test/helpers.bash, test/image.bats, test/network_ping.bats, test/pod.bats
/kind cleanup
Misc shellcheck fixes and related improvements.
None
Please see individual commits for details.
```release-note
NONE
```
=> Shellcheck misc

server/container_create.go, server/container_create_linux.go, server/utils.go, server/utils_test.go
/kind cleanup
Speed up mountinfo-related operations during container creation.
None
Please see individual commits for details.
```release-note
NONE
```
=> Speed up mountinfo-related operations during container creation

internal/oci/oci.go
solves the crash:
goroutine 7073 [running]:
github.com/cri-o/cri-o/internal/oci.(*Runtime).WaitContainerStateStopped.func1(0xc000bda240,
0x23e36a0, 0xc000bdc030, 0xc0001b11e0, 0xc000bda1e0)
src/github.com/cri-o/cri-o/internal/oci/oci.go:132 +0xdc
created by github.com/cri-o/cri-o/internal/oci.(*Runtime).WaitContainerStateStopped
src/github.com/cri-o/cri-o/internal/oci/oci.go:120 +0x156
/kind bug
```release-note
NONE
```
=> oci: move channel close to writer goroutine

server/sandbox_stop_linux.go
Signed-off-by: Jianzhu Zhang<jianzzha@redhat.com>
/kind bug
> /kind design
> /kind flake
Bug fix
Fixes #4095 
```release-note
None
```
=> fix high performance hook self-exit container issue

test/apparmor.bats, test/cgroups.bats, test/helpers.bash
/kind bug
Assorted test fixes and improvements for
- helpers.bash
- ~~critest.bats~~ (update: moved to PR #4087)
- apparmor.bats
- cgroups.bats
See individual commit messages for details.
None
Please review commit by commit. See individual commit messages for details.
```release-note
None
```
=> test/*bats: fixes

server/sandbox_network.go, server/server.go
current portmap is hardcoded to use IPv4 only. We can add IPv6
support just detecting the IP family from the network configuration,
however, this won't work for dual stack.
We add a portManager handler per IP family and use the corresponding
one based on the sandbox registered IPs.
Signed-off-by: Antonio Ojea <aojea@redhat.com>
/kind bug
/kind feature
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1872128
```release-note
crio-o portMapping dual-stack support
```
=> dual stack portmap support

.circleci/config.yml, nix/default.nix, nix/nixpkgs.json
Update nix pin with `make nixpkgs`
Also sync nix `packageOverrides` across skopeo/buildah/podman/cri-o for
utilizing local build cache.
Update nix pin with `make nixpkgs`
Also sync nix `packageOverrides` across skopeo/buildah/podman/cri-o for utilizing local build cache, see
- https://github.com/containers/crun/pull/450
- https://github.com/containers/conmon/pull/189
- https://github.com/containers/skopeo/pull/973
- https://github.com/containers/buildah/pull/2533
- https://github.com/containers/podman/pull/7286
- https://github.com/cri-o/cri-o/pull/4065
```release-note
Update nix pin with `make `nixpkgs`
```
=> Update nix pin with `make nixpkgs`

pkg/sandbox/sandbox.go
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Clarify sandbox config validation error message when metadata name is empty.
```release-note
None
```
=> sandbox config: Improve validation error message

internal/lib/sandbox/sandbox.go, test/stats.bats
/kind flake
cherry-pick of https://github.com/cri-o/cri-o/pull/4141 and https://github.com/cri-o/cri-o/pull/4064 to fix stats flakes and bad error messages
```release-note
none
```
=> [1.19] fix stats test and fix Unmount error

contrib/test/integration/main.yml, install.md
And update the tutorial doc to say release-1.19 instead
of release-1.18.
```release-note
None
```
=> [1.19] Point to k8s release-1.19 branch for tests

server/sandbox_run_linux.go
> /kind bug
> /kind design
> /kind flake
```release-note
none
```
=> [1.19] managed ns: report namespace cleanup failure by default

tutorials/kubeadm.md
Signed-off-by: Athanasios Garyfalos garyfalos@cpan.org
> /kind bug
> /kind design
> /kind flake
```release-note
Updating documentation of kubeadm with offline configurations.
```
=> Updating documentation of kubeadm with offline configurations.

crictl.yaml
The new configuration values in cri-tools v1.19.0 should be added to our vendored config as well.
Follow-up of https://github.com/cri-o/cri-o/pull/4150
None
```release-note
- Updated `crictl.yaml` configuration inside the repository to reflect cri-tools v1.19.0 changes
```
=> Update crictl.yaml to reflect cri-tools v1.19.0 configs

internal/version/version.go
/kind documentation 
> /kind flake
as title says!
```release-note
none
```
=> bump to v1.19.0

go.mod, go.sum, vendor/google.golang.org/grpc/.travis.yml, vendor/google.golang.org/grpc/Makefile, vendor/google.golang.org/grpc/balancer/balancer.go, vendor/google.golang.org/grpc/clientconn.go, vendor/google.golang.org/grpc/credentials/credentials.go, vendor/google.golang.org/grpc/credentials/tls.go, vendor/google.golang.org/grpc/dialoptions.go, vendor/google.golang.org/grpc/internal/envconfig/envconfig.go, vendor/google.golang.org/grpc/internal/internal.go, vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go, vendor/google.golang.org/grpc/internal/transport/handler_server.go, vendor/google.golang.org/grpc/internal/transport/http2_client.go, vendor/google.golang.org/grpc/resolver/resolver.go, vendor/google.golang.org/grpc/resolver_conn_wrapper.go, vendor/google.golang.org/grpc/rpc_util.go, vendor/google.golang.org/grpc/service_config.go, vendor/google.golang.org/grpc/trace.go, vendor/google.golang.org/grpc/version.go, vendor/google.golang.org/grpc/vet.sh, vendor/modules.txt
This fixes the build of the release-note tool, which previously failed
with:
```
vendor/google.golang.org/api/internal/conn_pool.go:29:2: undefined: grpc.ClientConnInterface
```
Refers to 15aa81b
Forward-port of https://github.com/cri-o/cri-o/pull/4190
None
```release-note
None
```
=> Bump GRPC to v1.27.0

contrib/test/integration/build/cri-o.yml
/kind cleanup
this will allow the feature to soak in the e2e tests and give us feedback on how it is working
```release-note
none
```
=> test: drop infra container

pkg/container/container.go, pkg/container/container_setnameandid_test.go, pkg/container/container_test.go, pkg/container/suite_test.go, server/container_create.go, server/container_create_linux.go
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Begins cleaning up the container create functions, and moves the spec generation into container where it can be vendored and reused, and also is easier to test. 
```release-note
none
```
=> container refactor

contrib/test/integration/build/crun.yml, test/ctr.bats
/kind cleanup
use last crun version
```release-note
NONE
```
=> tests: use crun 0.15

transfer.md
Signed-off-by: wangjibao.lc <wangjibao.lc@inspur.com>
documentation
update broken link for podman
None
None
```release-note
update broken link for podman tutorial
```
=> update link for podman

install.md
Signed-off-by: wangjibao.lc <wangjibao.lc@inspur.com>
documentation
update broken link for tutorials
None
update broken link for tutorials
None
```release-note
update broken link for tutorials
```
=> broken link

internal/lib/container.go, internal/lib/container_test.go, internal/lib/suite_test.go, server/container_create.go, server/container_list.go, server/container_reopen_log.go, server/sandbox_remove.go, server/sandbox_stop_linux.go, server/server.go, server/suite_test.go
/kind bug
> /kind design
> /kind flake
there exist many chances for us to use a pod or container that hasn't finished creating. 
This PR fixes these issues, and unifies some code paths in finding containers
```release-note
none
```
=> server: be more careful about using not created pods and containers

internal/version/version.go
Display the correct development version for master branch.
```release-note
None
```
=> Bump master version to 1.20.0-dev

test/network_ping.bats
_This used to be a part of #4127, which I am splitting into smaller PRs._
/kind cleanup
Simplify the code and fix shellcheck warnings; similar to #4245
None
```release-note
None
```
=> test/network_ping.bats: simplify

test/apparmor.bats, test/command.bats, test/crio-wipe.bats, test/helpers.bash, test/reload_config.bats
/kind cleanup
Various cleanups to
- simplify code;
- make it pass shellcheck.
None
```release-note
None
```
=> test/c*: cleanups

test/ctr_userns.bats, test/hooks.bats, test/pod.bats, test/reload_config.bats, test/reload_system.bats, test/restore.bats, test/status.bats, test/version.bats
/kind cleanup
* Fix a bunch of SC2086 shellcheck warnings.
* Fix and improve `version.bats` tests.
None
```release-note
None
```
=> test: fix SC2086; fix version.bats

test/helpers.bash, test/image.bats, test/image_remove.bats, test/network.bats
/kind cleanup
- tidy image prefetch and fix a few minor issues;
- rewrite `image_remove` test to dedup the code and fix some issues;
- fix shellcheck warnings while at it;
None
```release-note
None
```
=> test: image-related fixes+improvements

server/container_create.go, server/container_create_linux.go
/kind bug
/kind cleanup
I've wrapped a few fixes in one, as they're all related to cleaning up after failed container creates. More details in each commit
```release-note
Fixed a bug where a container creation failure caused that container to leak in the runtime
```
=> server: cleanup on failure fixes

test/pod.bats
> /kind bug
/kind cleanup
> /kind design
> /kind flake
simplifies the pod.bats file by removing excessive use of run 
```release-note
None
```
=> removes excessive runs from pod.bats

.gitignore, test/ctr.bats, test/helpers.bash, test/inspect.bats, test/network.bats, test/network_ping.bats, test/shm_size.bats
/kind cleanup
This is a bunch of small improvements, mostly for integration tests,
for which I do not want to open a dozen of separate PRs.
None
Closes: #4127 
```release-note
None
```
=> test: assorted small fixes and improvements

ADOPTERS.md, README.md
> /kind flake
more adopters to come
```release-note
none
```
=> begin ADOPTERS.md file

scripts/release-notes/release_notes.go
The CI was failing for quite a while, not passing the right CLI flag to
the release notes generator should fix that issue.
None
None
```release-note
None
```
=> Fix release notes generation

awesome.md
Adding both talks to be up to date.
None
None
```release-note
None
```
=> Add KubeCon EU 2020 talks to awesome list

internal/version/version.go
as title says
```release-note
none
```
=> version: bump to 1.18.4

contrib/test/ci/cri-o.spec, images/os/Dockerfile
Update the crio.spec to be 1.20 and the machine
os content image to the 4.7 version.
```release-note
None
```
=> Update e2e-aws logic for 4.7

server/container_create_linux.go
/kind bug
> /kind design
> /kind flake
If the mapping is missing it means it wasn't specified by the user.
In this case do not error out but use the unchanged ID.
```release-note
fix bug where runAsUser would only work with runAsGroup if userns annotations were specified
```
=> userns: use the same ID if the mapping is missing

ADOPTERS.md
Signed-off-by: Avi Miller <avi.miller@oracle.com>
Adds [Oracle Linux Cloud Native Environment](https://www.oracle.com/it-infrastructure/software.html) to the `ADOPTERS.md` file.
None
```release-note
NONE
```
=> Adding Oracle Linux Cloud Native Environment to the list of adopters.

ADOPTERS.md
Adding both products to the adopters docs.
None
PTAL @sysrich @kkaempf
```release-note
None
```
=> Add SUSE CaaS Platform and openSUSE Kubic to adopters

test/cgroups.bats, test/config.bats, test/config_migrate.bats, test/crio-wipe.bats, test/ctr_seccomp.bats, test/drop_infra.bats, test/hooks.bats, test/image.bats, test/image_remove.bats, test/image_volume.bats, test/inspecti.bats, test/network.bats, test/restore.bats, test/runtimeversion.bats, test/selinux.bats, test/shm.bats, test/shm_size.bats, test/stats.bats
> /kind bug
/kind cleanup
> /kind design
> /kind flake
Removes excessive runs from the bats tests
```release-note
none
```
=> removes excessive runs from bats tests

README.md
Update the README.md to reflect the latest versions.
None
None
```release-note
None
```
=> Update maintenance versions in README.md

cmd/crio/main.go, internal/version/version.go
Signed-off-by: Hans Feldt <feldt.hans@gmail.com>
> /kind bug
> /kind design
/kind feature
> /kind flake
```release-note
```
=> Log version at startup

OWNERS
I have no idea :-0
Add myself (@kolyshkin) to OWNERS file.
None
```release-note
None
```
=> OWNERS: add myself

internal/config/device/device.go, internal/config/device/device_test.go, internal/config/device/suite_test.go, pkg/config/config.go, pkg/container/container.go, pkg/container/device.go, pkg/container/device_test.go, server/container_create.go, server/container_create_linux.go, server/container_create_linux_test.go, server/container_create_unsupported.go, test/command.bats
/kind design
> /kind flake
This PR does two things:
- move the handling of config level devices (additional_devices) to a dedicated package: internal/config/device"
- move the container configuration of devices from server/ to pkg/container
Both of these changes are in anticipation of adding devices from pod annotations in addition to these sources
```release-note
none
```
=> Refactor handling of devices

tutorials/crictl.md
Signed-off-by: Markus Thömmes <markusthoemmes@me.com>
1. Update command outputs with actual outputs of a more recent version.
2. Simplify the Redis health check by obtaining the Pod's IP automatically and explicitly calling out where to get it from.
3. Further simplifying the Redis health check by using `ncat` instead of `telnet` to just get a simple command rather than having to deal with an interactive shell.
4. Explicitly state what happens when stopping and removing containers and pods and group the respective check commands with the resource that's being removed.
```release-note
None
```
=> Update the crictl tutorial and simplify a few steps

.github/PULL_REQUEST_TEMPLATE.md
/kind other
There was no category to characterize a PR or issue related to CI
(circle-ci setup and scripts, ansible jobs used by Jenkins, etc).
Let's add one.
There are some PRs that can't be clearly characterized as belonging
to a particular category (for example, this one). Add `/kind other`
for such.
:warning: I have taken the liberty of creating the needed labels already. 
If we won't proceed with this PR, those need to be removed).
None
```release-note
NONE
```
=> github/PR template: add /kind ci and /kind other

server/container_create.go
kubernetes forces sandbox to use runtime/default, however, users
may not want to use seccomp.
Allow to use pods with runtime/default profiles if users run
with seccomp disabled and they don' t want to enforce seccomp
/kind bug
```release-note
CRIO allow to run pods with default runtime profile in the Pod.Spec, if seccomp is disabled
```
=> not enforce seccomp profiles if disabled

contrib/test/ci/cri-o.spec
/kind cleanup
when installing with package managers, we leak a broken symlink, as we link to the in-dir crio.service, instead of the one recently installed
a 1.17 version if this pr will fix https://github.com/cri-o/cri-o/issues/3879
```release-note
fix broken symlink of systemd unit file
```
=> make: fix link to cri-o.service

contrib/test/integration/main.yml
/kind other
Pinning the tests to k8s release-1.20 branch
```release-note
none
```
=> [1.20] Point to k8s release-1.20 branch for tests

test/devices.bats
/kind ci
A few minor fixes and improvements to test/devices.bats. Please see individual commits for details.
None
```release-note
NONE
```
=> test/devices.bats: nits

server/image_pull.go
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
so we don't leak a goroutine
```release-note
fix a goroutine leak when checking image pulling progress
```
=> image pull: close progress chan

internal/version/version.go
/kind other
Version bump
```release-note
Cutting the first rc for 1.20 - v1.20.0-rc.1
```
=> [1.20] Bump version to v1.20.0-rc.1

test/helpers.bash, test/image.bats
/kind ci
Assorted cleanups to test/*bats.
None
```release-note
NONE
```
=> test/*bats: nits

scripts/release-notes/release_notes.go
which changed after a k8s release-notes package bump
> /kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
/kind bug
```release-note
none
```
=> [1.20] release-notes: fix flags

internal/version/version.go
> /kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
```release-note
none
```
=> bump to v1.20.0

pinns/Makefile
as a packager may not want the build to always be static
> /kind bug
> /kind ci
/kind cleanup
> /kind design
> /kind flake
> /kind other
```release-note
none
```
=> pinns: make binary not always static

internal/version/version.go
> /kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
```release-note
none
```
=> bump to v1.19.1

ADOPTERS.md
Signed-off-by: Søren Dalby Larsen <soren@uberresearch.com>
/kind other
Adding Digital Science to adopters.
None
```release-note
None
```
=> Add Digital Science to adopters

go.mod, go.sum, vendor/github.com/syndtr/gocapability/capability/enum.go, vendor/github.com/syndtr/gocapability/capability/enum_gen.go, vendor/modules.txt
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
Fixes #4466 
```release-note
None
```
=> Rollback gocapability vendor bump

scripts/release-notes/release_notes.go
which changed after a k8s release-notes package bump
> /kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
/kind bug
```release-note
none
```
=> release-notes: fix flags

install.md, tutorials/kubeadm.md
> /kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
updates the kubeadm installation docs to be more modern
```release-note
none
```
=> docs: update kubeadm tutorial

install.md
https://github.com/cri-o/cri-o/issues/4475
```release-note
none
```
=> Update debian repository url to use https

server/server.go
/kind bug
This avoids prompting for shortname expansion if CRI-O runs inside of a terminal.
Refers to https://github.com/cri-o/cri-o/pull/4455
/assign @vrothberg 
```release-note
None
```
=> Close the stdin/tty on server start to avoid shortname prompts

internal/lib/sandbox/namespaces_test.go
We should target to get the unit tests back to a state where we can
execute them in a rootless way. Right now the system user would not have
a chance to access pid 1's /proc/1/ns directory which make the test
fail. This patch uses the current pid, which should be accessible by the
current user executing the tests.
Can be verified by:
```
> make testunit TESTFLAGS=--focus=SandboxManagedNamespaces
```
None
None
```release-note
None
```
=> Make rootless namespace unit test execution work

README.md
This also removes the mentioning of v1.17 as well as sorting the table
in the way that the most recent entry is on top.
None
None
```release-note
None
```
=> Update compatibility matrix to mention v1.20

server/image_pull.go
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
cherry-pick https://github.com/cri-o/cri-o/pull/4412
```release-note
fix a goroutine leak when checking image pulling progress
```
=> [1.19] image pull: close progress chan

.circleci/config.yml, .github/workflows/test.yml, Makefile, scripts/github-actions-packages
/kind ci
Both CircleCI are now running in GitHub actions, whereas a pipeline
passes the build artifacts to those new jobs.
Refers to #4489 
Example run can be already found in the pipeline below.
```release-note
None
```
=> Move docs and completions validation to GitHub actions

internal/version/suite_test.go, internal/version/version_test.go
> /kind bug
> /kind ci
/kind cleanup
> /kind design
> /kind flake
> /kind other
fixes version_test.go to use ginkgo instead of testing
```release-note
```
=> fixes version_test.go

server/suite_test.go
Some distributions do not ship echo via `/bin/echo`, which means we now
look it up before actually using it within the unit tests.
None
None
```release-note
None
```
=> Lookup echo command for unit tests

.github/workflows/test.yml
The already pre-installed storage.conf has unwanted influence on the test results. This means we now remove it in the same way we do in the other validation test.
None
```release-note
None
```
=> Fix validate-completions GitHub action

contrib/test/integration/e2e.yml
I can't figure out how to make it work, and it doesn't seem to test anything CRI-O related
> /kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
```release-note
none
```
=> test: skip ServiceAccountIssuerDiscovery test

internal/config/cgmgr/systemd.go
/kind bug
conmon forwards the SIGTERM to the main container process.
This is undesirable during node shutdown as it results in
the container receving 2 SIGTERMs. With this change, conmon
ignores the SIGPIPE and will exit after the main container
process dies. If it doesn't for some reason, then
it gets SIGKILL by systemd after 90 seconds.
We need a follow-on to adjust the 90s to a value higher
than the termination grace period as a follow on. This doesn't
matter today as we don't retain container state on reboot.
```release-note
Set conmon scope KillSignal to SIGPIPE
```
=> [1.20] Set conmon scope KillSignal to SIGPIPE

pkg/container/container.go, server/sandbox_run_linux.go
This reverts commit 8164338edc9677b7a14710d3959168e0a2f32636 (PR #4539).
https://bugzilla.redhat.com/show_bug.cgi?id=1925623
/kind bug
```release-note
Revert systemd KillMode to control-group (default)
```
=> [1.20] Revert "Set systemd property KillMode to mixed for containers"

go.mod, go.sum, vendor/github.com/gogo/protobuf/proto/text_parser.go, vendor/github.com/gogo/protobuf/types/any.pb.go, vendor/github.com/gogo/protobuf/types/api.pb.go, vendor/github.com/gogo/protobuf/types/duration.pb.go, vendor/github.com/gogo/protobuf/types/empty.pb.go, vendor/github.com/gogo/protobuf/types/field_mask.pb.go, vendor/github.com/gogo/protobuf/types/source_context.pb.go, vendor/github.com/gogo/protobuf/types/struct.pb.go, vendor/github.com/gogo/protobuf/types/timestamp.pb.go, vendor/github.com/gogo/protobuf/types/type.pb.go, vendor/github.com/gogo/protobuf/types/wrappers.pb.go, vendor/golang.org/x/tools/go/internal/packagesdriver/sizes.go, vendor/golang.org/x/tools/go/packages/external.go, vendor/golang.org/x/tools/go/packages/golist.go, vendor/golang.org/x/tools/go/packages/visit.go, vendor/golang.org/x/tools/internal/event/core/event.go, vendor/golang.org/x/tools/internal/gocommand/invoke.go, vendor/golang.org/x/tools/internal/gocommand/version.go, vendor/golang.org/x/tools/internal/packagesinternal/packages.go, vendor/golang.org/x/tools/internal/typesinternal/types.go, vendor/modules.txt
> /kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
```release-note
none
```
=> [1.20] bump protobuf to 1.3.2

internal/config/nsmgr/types.go, pkg/config/config.go
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
as well as remove any file that exists in that spot
should fix https://bugzilla.redhat.com/show_bug.cgi?id=1922648
```release-note
none
```
=> config: pre-create pinns directories

contrib/test/ci/cri-o.spec, internal/version/version.go
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
```release-note
none
```
=> change binary version to 1.21.0-dev

images/os/Dockerfile
> /kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
Update e2e-aws logic for 4.8
```release-note
None
```
=> Update e2e-aws logic for 4.8

internal/config/nsmgr/nsmgr.go, internal/config/nsmgr/types.go, pkg/config/config.go
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
https://github.com/cri-o/cri-o/pull/4532 had a silly bug where we removed and recreated the incorrect directory :upside_down_face: 
while here, I also moved the responsibility of creating the correct directories to nsmgr, as i think it makes more sense
```release-note
none
```
=> nsmgr: correctly pre-create pinns directories

internal/version/version.go
> /kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
```release-note
none
```
=> bump to v1.20.1

docs/crio.conf.5.md, pkg/config/config.go
> /kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
fix doc of log_level adding trace option.
```release-note
None
```
=> fix doc log_level adding trace option

.github/workflows/test.yml
> /kind bug
/kind ci
> /kind design
> /kind flake
> /kind other
```release-note
none
```
=> gh-actions:  also run on release branches

test/timeout.bats
> /kind bug
/kind ci
> /kind design
> /kind flake
> /kind other
Not totally sure why they're currently passing, they're possibly skipped?
```release-note
none
```
=> test: correct the env variable for dropping the infra container

pkg/container/container.go, pkg/container/container_setnameandid_test.go, pkg/container/container_test.go, pkg/container/suite_test.go, pkg/sandbox/add_container.go, pkg/sandbox/create.go, pkg/sandbox/delete.go, pkg/sandbox/infra.go, pkg/sandbox/infra_test.go, pkg/sandbox/remove_container.go, pkg/sandbox/sandbox.go, pkg/sandbox/start.go, pkg/sandbox/stop.go, pkg/sandbox/suite_test.go, server/container_create.go, server/container_create_linux.go, server/sandbox_run_linux.go, server/sandbox_run_test.go
> /kind bug
> /kind ci
/kind design
> /kind flake
> /kind other
We should move to a world where most of the infra configuration happens in `pkg/sandbox/` instead of `server/`.
This PR begins that process, as well as cleans up some unused functions/files and makes the usage of context more idiomatic
```release-note
none
```
=> sandbox: Initialize the infra container internally

pkg/config/template.go
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
the field should not be commented out
```release-note
none
```
=> config: fix template to show infra_ctr_cpus option

.github/workflows/integration.yml
/kind cleanup
The restore key did never match, which is now fixed by aligning it to the
actual cache key.
None
None
```release-note
None
```
=> Fix GitHub actions cache key

internal/lib/container_server.go, server/container_attach.go, server/container_exec.go, server/container_reopen_log.go, server/container_update_resources.go, server/container_update_resources_test.go, server/sandbox_remove.go, server/sandbox_stop_linux.go
This reverts commit 0aeb7d27e5dd9262420dfc5c34022c88dce9326f.
the first suspicious commit that *could* cause openshift tests to fail
> /kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
```release-note
none
```
=> Revert "server: use IsAlive() more"

contrib/test/integration/build/conmon.yml
> /kind bug
/kind ci
> /kind design
> /kind flake
> /kind other
which will allow us to catch regressions early
```release-note
none
```
=> test: use latest conmon

.github/workflows/integration.yml, .github/workflows/test.yml, scripts/github-actions-packages
> /kind bug
/kind ci
> /kind design
> /kind flake
> /kind other
I forgot, probably, the most important part in the last one. I also cherry-picked https://github.com/cri-o/cri-o/pull/4638/commits for funsies
```release-note
none
```
=> [1.20] update github actions again

install.md
> /kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
```release-note
none
```
=> install: drop support matrix and update instructions

internal/oci/runtime_oci.go
port-forward needs to open a connection inside the namespace to the localhost address.
localhost can resolve to both IPv4 and IPv6 addresses in dual-stack systems
but the application can be listening in one of the IP families only.
golang has enabled RFC 6555 Fast Fallback (aka HappyEyeballs)
by default in 1.12. It means that if a host resolves to both IPv6 and IPv4,
it will try to connect to any of those addresses and use the
working connection.
However, the implementation uses go routines to start both connections in parallel,
and this has limitations when running inside a namespace, so we try to the connections
serially disabling the Fast Fallback support.
xref golang/go#44922
Signed-off-by: Antonio Ojea <aojea@redhat.com>
/kind feature
I've tested it with this snippet
```go
func …
```
=> use (sort of) happy-eyeballs for port-forwarding

contrib/test/integration/build/bats.yml, scripts/versions
/kind cleanup
Use the latest release of bats for integration testing.
None
None
```release-note
None
```
=> Update bats to v1.3.0

.github/workflows/integration.yml, .github/workflows/test.yml, .github/workflows/verify.yml
/kind ci
We have to run the actions on all release branches, too.
None
Refers to https://github.com/cri-o/cri-o/pull/4666
```release-note
None
```
=> Run GitHub actions on release branches

contrib/test/integration/build/cri-tools.yml, internal/version/version.go, pkg/container/container.go, pkg/container/container_test.go, server/container_create_linux.go, server/sandbox_run_linux.go
> /kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
```release-note
none
```
=> bump to v1.20.2

scripts/dependencies/dependencies.go, scripts/release-notes/release_notes.go
/kind ci
The variable does not seem to be set in GitHub actions therefore we need
to remove it.
None
None
```release-note
None
```
=> Remove check for CI env variable for release-notes and dependencies

scripts/dependencies/dependencies.go, scripts/release-notes/release_notes.go
/kind ci
The variable does not seem to be set in GitHub actions therefore we need
to remove it.
Partial cherry-pick of https://github.com/cri-o/cri-o/pull/4670
I also synchronized the implementation of the script from the master branch.
```release-note
None
```
=> [1.20] Remove check for CI env variable for release-notes and dependencies

pkg/container/container.go, pkg/container/container_test.go, server/container_create.go, server/container_create_linux.go
> /kind bug
> /kind ci
/kind cleanup
> /kind design
> /kind flake
> /kind other
with unit tests!
```release-note
none
```
=> pkg/container: take process args

contrib/bundle/build, scripts/versions
This updates available dependencies for the static binary bundle.
None
None
```release-note
None
```
=> Bump static binary dependency versions

.github/workflows/test.yml, Makefile, contrib/bundle/test-e2e
/kind ci
This adds an additional e2e NodeConformance test suite for our static
binary bundle.
Fixes https://github.com/cri-o/cri-o/issues/4688
None
```release-note
None
```
=> Add static bundle node e2e tests to GitHub actions

internal/resourcestore/resourcecleaner.go, internal/resourcestore/resourcestore.go, internal/resourcestore/resourcestore_test.go, server/container_create.go, server/sandbox_run_linux.go
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
as well as fix a bug where the resource store would cleanup the resource out of order
```release-note
fix a bug where pods or containers could be cleaned up out of order if the request timed out
```
=> resourcestore: introduce ResourceCleaner

server/sandbox_status.go
This should make the lint CI pipeline green again.
None
None
```release-note
None
```
=> Fix unnecessary conversion lint report

internal/oci/oci.go, internal/oci/oci_test.go, internal/runtimehandlerhooks/runtime_handler_hooks.go, pkg/annotations/annotations.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/template.go, pkg/config/workloads.go, server/container_create_linux.go, server/container_start.go, server/container_stop.go, server/sandbox_run_linux.go, server/sandbox_stop_linux.go, test/docs-validation/main.go, test/workloads.bats
> /kind bug
> /kind ci
/kind design
> /kind flake
> /kind other
intentionally left blank so it can be filled in once feature complete
```release-note
add support for customizing container specs based on workloads. Each workload has an activation_annotation that, when present, activates the specific workload. Then, each workload has the option to configure different resources. Resources can have default values, or require that they're specified for each individual container. This is done by annotation, which is of the form `$annotation_prefix.$resource_name/$container_name`, where annotation_prefix is configured for the particular workload, …
```
=> add support for customizing workloads (a second time!)

contrib/test/integration/build/cri-tools.yml, contrib/test/integration/main.yml, internal/version/version.go
> /kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
```release-note
none
```
=> bump to v1.21.0

scripts/versions
This should fix the bundle related tests.
None
None
```release-note
None
```
=> Bump crun to 0.19.1

pkg/config/template.go, pkg/config/workloads.go, test/workloads.bats
> /kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
as well as mark the feature as experimental
```release-note
Update how the resources for a workload is specified. Now, to override a workload, the pod must have the annotation `$prefix/$ctr_name = {"$resource_type": "$resource_value"}`. The workloads feature has also been marked as experimental, which should have happened from the beginning.
```
=> workloads: update how overrides are specified

internal/lib/container_server.go
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
```release-note
none
```
=> container server: fix silly typo

ADOPTERS.md
Adding update to ADOPTERS.md per request of @haircommander 
None
```release-note
none
```
=> Add HERE Technologies to ADOPTERS.md

cmd/crio/main.go
/kind bug
This is a partial revert of 975ffc6e482ab8581410b445c2268d60d64be62d,
where we started using the internal log when the context is avaiable.
It turns out that we missed a few pieces during the review, where we end
up using the internal log without having the interceptors set up.  This
was raised by @haircommander during the review, we checked a few parts
of the patch, but we still missed a few others.
We can only use the internal logging after
https://github.com/cri-o/cri-o/blob/d3dbaec060e33870e5cb5c3f7ec4207837804b00/cmd/crio/main.go#L222
happens.  From this moment, we start having different ways of logging in
the very same file and consistency becomes a problem then.
With the consistency in mind, I'd like to **only** use logrus for
debugging as part of this file.
Note: This …
=> main: still rely on logrus (rather than using the internal log)

internal/oci/runtime_vm.go
/kind bug
We now partially revert https://github.com/cri-o/cri-o/pull/4650 to
still use the runtime internal context for its tasks.
Fixes: https://github.com/cri-o/cri-o/issues/4798
None
```release-note
Fixed bug where runtime VM created containers never reach their `completed` state. 
```
=> Use extra context for runtime VM

server/sandbox_network.go, server/sandbox_run_linux.go
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
or else the cleanup will always fail on cleanup from context deadline
```release-note
none
```
=> [1.20] server: use background context for network stop

go.mod, go.sum, vendor/github.com/containers/image/v5/copy/copy.go, vendor/github.com/containers/image/v5/docker/docker_client.go, vendor/github.com/containers/image/v5/docker/docker_image.go, vendor/github.com/containers/image/v5/docker/docker_image_src.go, vendor/github.com/containers/image/v5/pkg/sysregistriesv2/shortnames.go, vendor/github.com/containers/image/v5/storage/storage_image.go, vendor/github.com/containers/image/v5/version/version.go, vendor/modules.txt
to pick up a fd leak
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
```release-note
fix a couple of FD leaks when pulling images
```
=> [1.20] bump containers/image to v5.10.6

contrib/test/integration/build/cri-tools.yml
> /kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
```release-note
none
```
=> [1.20] test: replace critools image repo

README.md
/kind cleanup
```release-note
none
```
=> [1.21] Fix podman name in README

pkg/config/template.go
/kind bug
it is a bool, not a string
```release-note
Fix a bug where `crio config` would print a string for `privileged_without_host_devices`, not a boolean
```
=> config: fix type of privileged_without_host_devices

go.mod, go.sum, vendor/github.com/syndtr/gocapability/capability/enum.go, vendor/github.com/syndtr/gocapability/capability/enum_gen.go, vendor/modules.txt
/kind bug
One day this problem will be fixed
```release-note
Fix a bug where CRI-O can't work with runc 1.0.0-rc93 because of an incorrectly specified list of capabilities
```
=> Pin gocapability to v0.0.0-20180916011248-d98352740cb2

contrib/test/integration/build/cri-tools.yml, contrib/test/integration/main.yml, test/network_ping.bats
> /kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
```release-note
none
```
=> [1.19] test: replace critools image repo

.muse/config.toml
Signed-off-by: arcolife <archit.py@gmail.com>
/kind ci
muse report generated has false postitives. This PR aims to initiate a muse config that could be enhanced as needed.
bugbash reports from muse
references:
- https://docs.muse.dev/docs/repository-configuration/
None
=> add ignore rules to muse config for infer tool

install.md
=> docs: improve installation instructions for debian

.muse/config.toml
/kind other
we shouldn't change anything in the vendor directory, it'll get clobbered by `make vendor`
there's a problem that pops up in `internal/logs/logs_test.go` about an intentionally nil context
```release-note
none
```
=> muse: ignore vendor and logs test

pinns/src/pinns.c
Mount namespaces are a bit odd in that:
- Like user namespaces, you must fork and bindmount the mount namespace
from the parent process (otherwise the bindmount is in the child
mount namespace where no one sees it)
- Additionally, you cannot bindmount a mount namespace to a file if that
file is in a shareable mount namespace, otherwise infinite loops are
possible. So before attempting to bind the mount namespace we
bind-mount the target directory to itself (if it's not already a
mountpoint) and mark it as unbindable.
Usage:
pinns -d ... -f ... [-m|--mnt]
Signed-off-by: Jim Ramsay <jramsay@redhat.com>
/kind feature
This adds the ability for the pinns utility to pin mount namespaces.  This will be useful in the implementation of My …
=> pinns: Allow pinning mount namespaces

tutorials/decryption.md
Signed-off-by: Brandon Lum <lumjjb@gmail.com>
Update decryption doc to use public dockerhub image, now that it is supported upstream! No credentials required.
```release-note
None
```
=> Update image to use public image

go.mod, go.sum, scripts/versions, vendor/github.com/opencontainers/runc/libcontainer/configs/config.go, vendor/github.com/opencontainers/runc/libcontainer/utils/utils.go, vendor/modules.txt
Update runc to the latest release.
None
None
```release-note
Update static binary bundle runc version to `v1.0.0-rc95`.
```
=> Bump runc to 1.0.0-rc95

cmd/crio/main.go
/kind bug
because, why not?
```release-note
Reduce the permission on the listen socket to 0660
```
=> reduce listen socket permissions to 0660

go.mod, go.sum, vendor/github.com/containers/storage/containers.go, vendor/github.com/containers/storage/images.go, vendor/github.com/containers/storage/layers.go, vendor/github.com/containers/storage/store.go, vendor/modules.txt
to pick up fix to possible segfault
```release-note
Fix possible segfault when image is deleted by podman while CRI-O is listing images
```
=> [1.20] bump to latest c/storage 1.24 branch

.github/ISSUE_TEMPLATE.md, CONTRIBUTING.md, README.md, awesome.md
we didn't really spend that much time there anyway, and the hostile take over presents us a good opportunity to sunset it.
```release-note
none
```
=> docs: drop IRC

server/sandbox_list_test.go
Check for the correct return value to fix the unit tests.
None
None
```release-note
None
```
=> Fix unit tests

utils/utils.go
/kind bug
when setting up conmon's cgroup
```release-note
Re-attempt setting up conmon's cgroup if it fails on EAGAIN from dbus
```
=> try again on EAGAIN from dbus

internal/oci/oci.go, internal/oci/oci_test.go, internal/oci/runtime_oci.go, internal/oci/runtime_vm.go, test/mocks/oci/oci.go
/kind design
It is not really needed, and causes unnecessary overhead. Plus, we drop an unkillable child from the mix
allowing cri-o to keep track of its children better.
```release-note
ExecSync requests now don't use conmon, instead calling the runtime directly, which reduces overhead.
```
=> oci: do not use conmon for exec sync

internal/version/version.go
=> [1.20] bump to v1.20.3

internal/version/version.go
=> [1.21] bump to v1.21.1

internal/version/version.go
we are *long* overdue
```release-note
none
```
=> [1.19] bump to v1.19.2

contrib/bundle/test-e2e, go.sum, internal/resourcestore/resourcecleaner_test.go, scripts/versions
This should make the CI green again on 1.21.
None
None
```release-note
Updated static binary bundle crun version to v0.20
```
=> [1.21] Fix CI

internal/log/interceptors.go
/kind cleanup
We forgot those during the previous migration, so they should be now logged uppercase as well.
None
None
```release-note
None
```
=> Fix request and response log capitalization

internal/storage/runtime.go
/kind cleanup
```release-note
none
```
=> storage: succeed in DeleteContainer if container is unknown

internal/config/cgmgr/cgmgr.go, internal/config/cgmgr/systemd.go, internal/dbusmgr/dbusmgr.go, internal/dbusmgr/user.go, internal/storage/image.go, utils/utils.go, utils/utils_test.go
/kind bug
reuse dbus connection and attempt to reconnect if we get a dbus error
this PR heavily adapts https://github.com/opencontainers/runc/blob/7362fa2d282feffb9b19911150e01e390a23899d/libcontainer/cgroups/systemd
eventually, the plan is to upstream the internal/dbusmgr package to godbus, but we're picking this here first
```release-note
Reuse connection when connecting to dbus, as well as reattempt the connection if it fails temporarily
```
=> cgmgr: reuse dbus connection

internal/storage/image.go
Disable the short name mode so we don't use the alias table
when pulling images. We will revisit this is in the next release.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1969599
```release-note
None
```
=> [release-1.21] Disable short name mode

internal/storage/image.go
Disable the short name mode so we don't use the alias table
when pulling images. We will revisit this is in the next release.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1969599
```release-note
None
```
=> Disable short name mode

.github/workflows/integration.yml, .github/workflows/test.yml, .github/workflows/verify.yml, dependencies.yaml
/kind ci
/kind cleanup
This allows an easier go version upgrade as well as saner dependency verification.
None
None
```release-note
None
```
=> Use GitHub actions env variable for go version

test/workloads.bats
=> test: fix cgroupfs workload tests

go.mod, go.sum, vendor/github.com/containers/storage/containers.go, vendor/github.com/containers/storage/images.go, vendor/github.com/containers/storage/layers.go, vendor/github.com/containers/storage/store.go, vendor/modules.txt
to pick up fix to possible segfault
```release-note
Fix possible segfault when image is deleted by podman while CRI-O is listing images
```
=>  [1.19] bump to latest c/storage 1.20 branch

dependencies.yaml, scripts/versions
Update crun to the latest release.
None
None
```release-note
Updated crun in static binary bundle to v0.20.1
```
=> Update crun to v0.20.1

ADOPTERS.md
Just adding a company to adopters list
```release-note
Add Particule as adopters
```
=> Add particule as adopters

internal/oci/runtime_oci.go
This should fix the failling CI.
None
None
```release-note
None
```
=> Remove unused code

server/metrics/metrics.go
/kind feature
If a provided certificate is not valid any more we now handle that as error.
None
None
```release-note
Validate certificate dates for TLS metrics endpoint
```
=> Verify metrics TLS certs for their validity

images/os/Dockerfile
Update e2e-aws logic for 4.9.
```release-note
NONE
```
=> Update e2e-aws logic for 4.9

dependencies.yaml, scripts/versions
This updates runc to the latest release.
None
None
```release-note
Updated runc to v1.0.0 within the static binary bundle.
```
=> Update runc to v1.0.0

internal/oci/runtime_vm.go
/kind bug
When running ExecSync with a timeout, do not report an error, but make an ExecSyncResponse showing that a timeout occurred.
This PR copies the logic found in runtime_oci.go:ExecSyncContainer(), and applies it to runtime_vm.go:ExecSyncContainer(), so that both have the same behaviour.
This issue was found by running the integration tests with Kata as the runtime.
The test "ctr execsync" was failing because the error reported on a timeout was not the one expected.
With this PR, the test passes.
```release-note
none
```
=> runtimeVM: ExecSync should return a recognizable error on timeout

README.md, tutorials/debugging.md
so I don't forget how to do this every time anymore :smile: 
```release-note
none
```
=> tutorials: add tutorial on debugging tips

contrib/test/ci/cri-o.spec, internal/version/version.go
=> version: move to 1.22

go.mod, go.sum, server/image_pull.go, vendor/github.com/containers/image/v5/docker/docker_image_src.go, vendor/github.com/containers/image/v5/types/types.go, vendor/github.com/containers/image/v5/version/version.go, vendor/modules.txt
Backport fix #4438 to release-1.19 for 4.6.
https://bugzilla.redhat.com/show_bug.cgi?id=1976293
```release-note
Crio adds info level log of the physical image source.
```
=> [release-1.19] Bug 1881694: Add pull source as info level log

server/sandbox_stop.go
/kind bug
```release-note
none
```
=> server: prevent segfault by not using a potentially nil sandbox

go.mod, go.sum, internal/config/cgmgr/cgmgr.go, internal/config/cgmgr/systemd.go, internal/dbusmgr/dbusmgr.go, internal/dbusmgr/user.go, utils/utils.go, utils/utils_test.go, vendor/github.com/coreos/go-systemd/v22/activation/files_unix.go, vendor/github.com/coreos/go-systemd/v22/activation/files_windows.go, vendor/github.com/coreos/go-systemd/v22/dbus/dbus.go, vendor/github.com/coreos/go-systemd/v22/dbus/methods.go, vendor/github.com/coreos/go-systemd/v22/journal/journal_unix.go, vendor/github.com/coreos/go-systemd/v22/journal/journal_windows.go, vendor/github.com/coreos/go-systemd/v22/sdjournal/journal.go, vendor/modules.txt
/kind bug
reuse dbus connection and attempt to reconnect if we get a dbus error
this PR heavily adapts https://github.com/opencontainers/runc/blob/7362fa2d282feffb9b19911150e01e390a23899d/libcontainer/cgroups/systemd
eventually, the plan is to upstream the internal/dbusmgr package to godbus, but we're picking this here first
cherry-pick of https://github.com/cri-o/cri-o/pull/4986
```release-note
Reuse connection when connecting to dbus, as well as reattempt the connection if it fails temporarily
```
=> [1.19] cgmgr: reuse dbus connection

README.md
Signed-off-by: Francesco Giudici <fgiudici@redhat.com>
The link to kubernetes releases is old and will be removed by the end of year.
Update to the updated link.
None
This is just an update of an external link in the README.
```release-note
None
```
=> README: fix Kubernetes releases external link

server/container_create.go, server/sandbox_run_linux.go
as it should not be a fatal error, as it indicates we've already cleaned up
```release-note
none
```
=> server: do not repeatedly error with no such id

internal/version/version.go
=> bump to v1.20.4

internal/version/version.go
=> version: bump to 1.19.3

internal/version/version.go
=> version: bump to v1.21.2

server/runtime_status_test.go, server/suite_test.go
Fixing the hanging unit tests within our CI.
Refers to #5046 
None
```release-note
None
```
=> Fix unit test execution

completions/fish/crio.fish, docs/crio.8.md, docs/crio.conf.5.md, pkg/config/config.go, server/sandbox_remove.go, test/infra_ctr_cpuset.bats, test/network.bats
/kind feature
```release-note
the config field `drop_infra_ctr` is now true by default
```
=> config: drop infra container by default

internal/config/node/node.go
because them being errors implies cri-o execution should stop
/kind bug
```release-note
none
```
=> node: only warn on node parameter initialization

assets/css/style.scss
The referencing theme did not work any more in the first place, so we now set it by hand.
None
None
```release-note
None
```
=> Fix jekyll build for gh-pages branch

go.mod, go.sum, vendor/github.com/containers/storage/drivers/overlay/overlay.go, vendor/modules.txt
and pickup fix about recreating link dir symlinks
/kind bug
```release-note
Fix a bug where container storage can get corrupted if the `link` directory is missing.
```
=> [1.19] vendor: bump c/storage to latest v1.20-stable

go.mod, go.sum, vendor/github.com/containers/storage/drivers/overlay/overlay.go, vendor/modules.txt
and pickup fix about recreating link dir symlinks
/kind bug
```release-note
Fix a bug where container storage can get corrupted if the `link` directory is missing.
```
=> [1.20] vendor: bump c/storage

internal/storage/image.go
/kind bug
```release-note
fix a bug where CRI-O prematurely stopped pulling from a blocked registry, even if there was a mirror for that registry it was allowed to pull from.
```
=> [1.19] pull: do check for blocked registries

server/container_create.go, server/sandbox_run_linux.go
/kind bug
cherry-pick of https://github.com/cri-o/cri-o/pull/5137 and https://github.com/cri-o/cri-o/pull/5006
```release-note
none
```
=> [1.21] server: do not repeatedly error with no such id

server/runtime_status_test.go
Signed-off-by: utam0k <k0ma@utam0k.jp>
/kind other
Let me be the first contributor to learn about Go language and CRI. I'm sorry for the small changes, but please review. Please let me know if I'm doing something too weird.
```release-note
none
```
=> make `runtime_status_test` more accurate.

server/container_create_linux.go
Add symlink /etc/mtab to container on rootfs.
Since crio doesn't build and commit new images, it will not cause 
unexpected problems like populating new file to layers unexpected. 
Directly create new symlink on rootfs should be fine.
/kind bug
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1868221
Fixes: #2036 
```release-note
Add symlink /proc/mounts on /etc/mtab to container
```
=> Bug 1868221: Add symlink /etc/mtab to container

Makefile, nix/default-arm64.nix, nix/default.nix, nix/derivation.nix, nix/nixpkgs.json, nix/static.nix
Supersedes https://github.com/cri-o/cri-o/pull/4630
None
```release-note
None
```
=> Bump nixpkgs

internal/version/version.go
/kind bug
We now set the environment to `LANG=C` before running `ldd`. This way we
can ensure that the error checks are consistent.
Fixes #5165
None
```release-note
Fixed linkmode detection for on `en_US` systems `crio version`
```
=> Fix linkmode retrieval for non en_US systems
