cri-o/cri-o

- .golangci.yml
- lib/container_server.go
- server/container_create_linux.go
This commit fixes issues related to the `importShadow` linter, which
detects when imported package names shadowed in the assignments.
> Add gocritic importShadow linter and fixes

- .golangci.yml
- oci/runtime_oci.go
- server/container_create.go
- server/container_create_linux.go
This commit fixes issues related to the `appendAssign` linter, which
detects suspicious append result assignments.
> Add gocritic appendAssign linter and fixes

- .golangci.yml
- lib/container_server.go
- lib/kill.go
- lib/rename.go
- oci/runtime_vm.go
- pkg/storage/runtime.go
- server/container_create.go
- server/container_create_linux.go
- server/container_execsync.go
- server/sandbox_run_linux.go
This commit fixes issues related to the `sloppyReassign` linter, which
detects suspicious and confusing re-assignments.
> Add gocritic sloppyReassign linter and fixes

- .golangci.yml
- server/container_create.go
- server/image_pull.go
- server/image_status.go
- server/naming.go
- server/secrets.go
- utils/io/container_io.go
- utils/io/logger.go
- utils/ioutil/write_closer.go
- utils/utils.go
This commit fixes issues related to the `unnamedResult` linter, which
detects unnamed results that may benefit from names.
> Add gocritic unnamedResult linter and fix issues

- conmon/conmon.c
add detection for a cgroup v2 unified mode.  Skip setting up OOM for
now.  It is not proper support for will temporarily unlock Podman.
> conmon: detect cgroup2 and skip OOM handling

- lib/container_server.go
- lib/container_server_test.go
- lib/suite_test.go
- server/server.go
When cri-o is restarted, we were not returning an error if
an error ocurred when reading container state from disk. So
if the state.json file was corrupted or deleted in the meantime
the containers would be reporting an UNKOWN state and default
values for started time, created time, etc.
We now check for that and if a pod can't be restored, we delete the pod
as well as any containers associated with it. We also release the pod
and container names so that they can be used again.
We do the same for any containers that can't be restored.
> [1.14] Fix logic of server.restore()

- cmd/crio/config.go
- cmd/crio/main.go
- docs/crio.conf.5.md
- server/config.go
- server/server.go
- server/server_test.go
- server/suite_test.go
Hey there :wave:, this is an idea I had recently, so I want to put it under discussion here.
I think it would be nice to reload the CRI-O configuration files (`/etc/crio/crio.conf`, `/etc/containers/*`) without restarting the application. This is surely a feature where it has to be decided per option if an application restart is sensible, so I would add an extra documentation part for every "hot reloadable" option.
For a small test I implemented the feature for the `log_level` option within this PR. It actually works by sending `SIGHUP` to the `crio` process:
```
...
DEBU[2019-05-09 14:04:01.433231541+02:00] successfully registered config file watcher
...
DEBU[2019-05-09 14:04:11.294262201+02:00] reloading configuration
INFO[2019-05-09 14:04:11.298918608+02:00] set config log level to …
```
> Add config hot reload feature (`log_level`)

- .circleci/config.yml
- .travis.yml
- Makefile
- hack/tree_status.sh
The mockgen target takes too much time on local machines to run before
every test. This commit splits up the workflow and should provide a
better local developer experience when running unit tests. The CI
scripts have been adapted to check for modified mocks and fail in that
case.
> Update unit test target to not run `mockgen`

- .golangci.yml
- utils/io/container_io.go
- utils/ioutil/write_closer.go
This commit fixes issues related to the `builtinShadow` linter,
which detects shadowing of predeclared identifiers.
> Add gocritic builtinShadow linter and fixes

- conmon/utils.c
- conmon/utils.h
conmon logging levels, syslog and container ID are now set correctly
This fix also fixes compilation for gcc 9 (which only breaks if syslog default is changed in the code, but it was annoying to deal with)
> conmon: properly set conmon logs

- cmd/crio/config.go
- cmd/crio/main.go
- lib/config.go
- lib/config_test.go
- lib/container_server.go
- lib/container_server_test.go
- lib/suite_test.go
- pkg/storage/image.go
- pkg/storage/image_test.go
- server/config.go
- server/config_test.go
- server/container_create_linux.go
- server/container_status.go
- server/image_list.go
- server/image_pull.go
- server/image_pull_test.go
- server/image_remove.go
- server/image_remove_test.go
- server/image_status.go
- server/image_status_test.go
- server/inspect.go
- server/inspect_test.go
- server/sandbox_run_linux.go
- server/server.go
- server/server_test.go
- server/suite_test.go
- test/mocks/criostorage/criostorage.go
- vendor/modules.txt
The SystemContext is now created from the main binaries like
`cmd/crio/main.go` and then passed down to the actual methods. For this
we now store the `systemContext` at the `Server` in substition to the
`ImageContext` of the `ContainerServer`. All tests have been adapted as
well.
> Cleanup SystemContext usage

- README.md
> readme: Remove timeout from kube documentation

- tutorials/setup.md
This PR switches the parentheses with the brackets to make the Markdown links work like a charm.
> Fix links in tutorials/setup.md

- conmon/conmon.c
We used to continue to listen on the console socket for our terminal master, even though we've already cleaned everything else up.
Instead, we should just remove the callback, so there's no chance of calling it later and printing a very confusing looking loop of "trying to connect, failed to connect".
> Remove terminal watch after success

- docs/crio.conf.5.md
I'd left this out in 461af2814b (#1943).
libpod analog is containers/libpod#3160.
> docs/crio.conf.5: Add "have" to "higher precedence" typo

- conmon/conmon.c
- conmon/ctr_logging.c
This PR backports #2241, which fixes the current incompatibility between podman v1.3.X and conmon v1.14.1.
> [1.14] conmon: use sd_journal_sendv

- .circleci/config.yml
- .travis.yml
- Makefile
Slightly improve the CI speed by utilizing a higher amount of parallel
jobs and separating the mock generation targets.
> Improve CI speed

- conmon/utils.c
- conmon/utils.h
journald logging broke debugging print to syslog, and this PR finishes fixing it
> Fix logging to journal

- .golangci.yml
- Makefile
Some IDEs are able to lint via a simple invocation of `golangci-lint` in
the background. The recommended buildtags needs to be set in the
configuration to ensure that these tests have strong defaults.
> Add predefined build tags to .golangci.yml

- Makefile
- lib/config.go
- lib/config_test.go
- lib/container_server.go
- lib/suite_test.go
- server/container_create_linux.go
- server/suite_test.go
- test/framework/framework.go
- utils/filesystem.go
- utils/filesystem_test.go
If you run the test suite on a host that already has a default
OCI hooks directory, the test suite can fail because it is unable
to parse the host' hooks configuration. Since the tests should
be isolated from the host, ensure that we always specify a safe
default for directories that can be searched for configuration.
Verify that configuration directories are actually directories,
and add the ginkgo `--trace` option to assist in test failure
debugging.
Signed-off-by: James Peach <jpeach@apache.org>
> Ensure the test suite configures config directories.

- hack/apparmor_tag.sh
- hack/btrfs_installed_tag.sh
- hack/btrfs_tag.sh
- hack/libdm_installed.sh
- hack/libdm_no_deferred_remove_tag.sh
- hack/openpgp_tag.sh
- hack/seccomp_tag.sh
- hack/selinux_tag.sh
- hack/tree_status.sh
- test/cni_plugin_helper.bash
- test/helpers.bash
Some distributions have bash installed under a different path than
`/bin`, which can be retrieved via `env`.
> Update scripts to find correct bash path

- lib/container_server.go
- lib/container_server_test.go
This commit fixes a runtime panic which can happen on store shutdown,
for example if the `mountpoints.lock` file got deleted during runtime.
> Fix possible runtime panic on store shutdown

- Makefile
- Makefile.inc
- conmon/Makefile
Some build environments will use the CRI-O sources without containing
the complete git history. To avoid annoying fatal git error messages we
now fallback to "unknown" versions if the git repository is not
available.
> Update Makefile to be usable without git

- cmd/crio/config.go
- cmd/crio/main.go
- docs/crio.conf.5.md
- lib/config.go
- lib/config_test.go
- lib/testdata/config.toml
- server/config_test.go
- server/fixtures/crio.conf
- server/server.go
To maintain backwards compatibility, change plugin_dir to plugin_dirs in crio configs.
Mark plugin_dir depreciated, and send warning as such.
> [1.14] Change plugin_dir to plugin_dirs

- server/container_create_linux.go
- test/ctr.bats
When additional devices are configured in `crio.conf`, they
are correctly bound into the container, but the devices cgroup
permissions were not propagated. Ensure that we propagate the
requested permissions down to the continer spec so that the access
is correct.
Update the spec to create the right container devices when we configure the devices group.
Added a test to ensure that `/dev/kvm` can be made readable in a container by using the `additional_devices` configuration.
Ensured that the `additional_devices` configuration parameter populates the requested device nodes inside the container with the correct permissions.
> Update device cgroup permissions for configured devices.

- server/container_create_linux.go
- server/container_create_linux_test.go
if the container is bind mounting /sys from the host, do not add
another default /sys mount.
This also prevents a "mount bomb" if there is mount with bidirectional
mount propagation that causes the rootfsPropagation to be set to
"rshared".
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1711200
> server: do not add default /sys if bind mounted

- server/container_create_linux.go
- server/container_create_linux_test.go
if the container is bind mounting /sys from the host, do not add
another default /sys mount.
This also prevents a "mount bomb" if there is mount with bidirectional
mount propagation that causes the rootfsPropagation to be set to
"rshared".
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1711200
(cherry picked from commit 184e8580d112ec7f830f1054be97aa053263e7e1)
> [release-1.13] server: do not add default /sys if bind mounted

- cmd/crio/main.go
- server/config_unix.go
- server/config_windows.go
- vendor.conf
- vendor/github.com/google/renameio/LICENSE
- vendor/github.com/google/renameio/README.md
- vendor/github.com/google/renameio/doc.go
- vendor/github.com/google/renameio/go.mod
- vendor/github.com/google/renameio/tempfile.go
- vendor/github.com/google/renameio/writefile.go
- version/version.go
- version/version_test.go
To be able to set auto-upgrades, we need the ability write the current CRI-O version to a file
Add this to version/version.go
Add package google/renameio for an atomic write of the version file
Call WriteVersionFile in main, where we have the gitCommit and we've just created the server
> [1.14] Lay down version file

- server/container_create_linux.go
- server/container_create_linux_test.go
if the container is bind mounting /sys from the host, do not add
another default /sys mount.
This also prevents a "mount bomb" if there is mount with bidirectional
mount propagation that causes the rootfsPropagation to be set to
"rshared".
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1711200
(cherry picked from commit 184e8580d112ec7f830f1054be97aa053263e7e1)
> [release-1.14] server: do not add default /sys if bind mounted

- go.mod
- go.sum
- vendor/github.com/containers/libpod/pkg/spec/storage.go
- vendor/github.com/containers/libpod/version/version.go
- vendor/github.com/seccomp/libseccomp-golang/CHANGELOG
- vendor/github.com/seccomp/libseccomp-golang/seccomp.go
- vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go
- vendor/github.com/vbatts/git-validation/go.mod
- vendor/github.com/vbatts/git-validation/go.sum
- vendor/modules.txt
- Bump github.com/vbatts/git-validation to 1.0.0
- Bump github.com/seccomp/libseccomp-golang from 0.9.0 to 0.9.1
- Bump github.com/containers/libpod from 1.3.1 to 1.3.2
> Update dependencies (Week 22)

- oci/oci.go
We now protect the map of runtime implementations with a RWMutex to
allow concurrent reads, but restrict single write access.
> Fix runtime panic when having concurrent writes to runtime impl map

- Dockerfile
- Dockerfile-circleci
- test/helpers.bash
This commit updates the CNI plugins and fixes the related pod IP parsing for the integration tests.
> Update Dockerfile CNI plugins to v0.8.0

- server/container_create_linux.go
- test/ctr.bats
When additional devices are configured in `crio.conf`, they
are correctly bound into the container, but the devices cgroup
permissions were not propagated. Ensure that we propagate the
requested permissions down to the continer spec so that the access
is correct.
This fixes #2214.
Signed-off-by: James Peach <jpeach@apache.org>
Backport to 1.13 branch
> [1.13] Update device cgroup permissions for configured devices.

- server/container_create_linux.go
- test/ctr.bats
When additional devices are configured in `crio.conf`, they
are correctly bound into the container, but the devices cgroup
permissions were not propagated. Ensure that we propagate the
requested permissions down to the continer spec so that the access
is correct.
This fixes #2214.
Signed-off-by: James Peach <jpeach@apache.org>
Backport to 1.14 branch
> [1.14] Update device cgroup permissions for configured devices.

- README.md
This is just another small improvement to the README.md, which removes the "Status: Stable" header and moves it into a badge. Beside this, the badges are a bit re-ordered by their usual color.
> Switch to 'stable status' badge

- tutorials/setup.md
Currently, the PPA from project atomic only works on Ubuntu. We should
only mention that distribution there otherwise it won't work.
> Fix mentioned distributions within the setup tutorial

- .golangci.yml
- server/sandbox_run_linux.go
- server/sandbox_run_test.go
The method `runPodSandbox` has a very high cyclomatic complexity. Now we
refactor first parts out of it and give them dedicated unit tests to
ensure the overall functionality.
Beside this, the gocyclo linter is now enabled (on its lowest possible
level) and will be continuously updated with further refactorings.
> Refactor sandbox cgroup annotation

- utils/utils_test.go
To be consistent with testing we now use `ToNot` instead of `To(Not(...))`
> Fix gomega matcher syntax

- docs/crio.conf.5.md
- lib/config.go
- lib/testdata/config.toml
It's more efficient to have them in memory
> Disable file locking by default

- contrib/crio-wipe/README.md
- contrib/crio-wipe/crio-wipe.bash
- contrib/crio-wipe/crio-wipe.service
- contrib/crio-wipe/helpers.bash
- contrib/crio-wipe/lib.bash
- contrib/crio-wipe/test.bats
crio-wipe is a program that compares the version file to crio --version, and if the version is sufficiently new, crio-wipe clears storage.
It should be used on any system where it is desired crio auto upgrades between versions
Relies on: https://github.com/cri-o/cri-o/pull/2397
> [1.14] Add crio-wipe

- cmd/crio/config.go
- cmd/crio/main.go
- docs/crio.conf.5.md
- lib/config.go
- lib/config_test.go
- lib/testdata/config.toml
- server/config_test.go
- server/fixtures/crio.conf
- server/server.go
- server/suite_test.go
To maintain backwards compatibility, change plugin_dir to plugin_dirs in crio configs.
Mark plugin_dir depreciated, and send warning as such.
also, ensure future config files generated by crio will not include plugin_dir,
which allows for a seemless transition between config members
> [master] Change plugin_dir to plugin_dirs and remove plugin dir from config

- README.md
Currently, the PPA from project atomic only works on Ubuntu. We should
only mention that distribution there otherwise it won't work.
> Fix mentioned distributions in README.md

- lib/config.go
- lib/config_test.go
The default network directory does not necessarily have to exist before
the cri-o service is started. IF the planned network directory does not
exist, create it when starting the service.
Signed-off-by: Ganesh Maharaj Mahalingam <ganesh.mahalingam@intel.com>
> Create network directory if it doesn't exist

- Makefile
- Makefile.inc
- conmon/Makefile
---
Some build environments will use the CRI-O sources without containing
the complete git history. To avoid annoying fatal git error messages we
now fallback to "unknown" versions if the git repository is not
available.
Cherry-picked: 33af10124c397511723ef6d59dd72edf11353277
> [1.14] Update Makefile to be usable without git

- .gitignore
- vendor/github.com/containers/storage/Vagrantfile
- vendor/github.com/mistifyio/go-zfs/Vagrantfile
We excluded two vendored files due to the gitignore of all Vagrantfiles
within the repository. This lead into small file inconsistencies on
disk, for example when executing `git clean -fdx`.
> Fix Vagrantfile vendor inconsistency

- .circleci/config.yml
- server/config.go
- server/config_test.go
- server/inspect.go
- test/helpers.bash
- test/reload.bats
This commits adds the first integration test suite to the live reload
feature of CRI-O. A small refactoring of the start_crio function within
the helpers.bash is included as well. The HTTP "/info" endpoint contains
now a new field "last_reload", which specifies the last configuration
reload via SIGHUP independently if the reload has been successful or
not.
I had to remove the `-t/--tty` from the CircleCI console to avoid adding
newlines to the console output.
> Add live reload integration tests

- lib/rename.go
This PR fixes a `redundant if` I came across, which our linter didn't see.
I'm a bit curious why not...
> Fix redundant if in lib/rename.go

- cmd/crio/config.go
- docs/crio.conf.5.md
- lib/container_server.go
- pkg/storage/runtime.go
- pkg/storage/runtime_test.go
- server/config.go
- server/config_test.go
- server/sandbox_run_linux.go
- server/sandbox_run_test.go
- test/framework/framework.go
- test/mocks/criostorage/criostorage.go
- test/reload.bats
This commit adds the reload feature for the `pause_image`,
`pause_image_auth_file` and `pause_command` options. To be able to
reload the options on a server configuration level, we now have to
let the server pass in the options instead of adding them as member
of the `runtimeServer`. Documentation and tests have been adapted as
well.
> Add live reload feature to pause configuration

- docs/crio.conf.5.md
- lib/config.go
- lib/testdata/config.toml
File locking adds runtime overhead and thus should be opted into as a user. Disable it by default here
> [1.14] Disable file locking by default

- lib/config.go
- lib/config_test.go
We should assume that both plugin_dir and plugin_dirs should not be set. Either a user expects the legacy configuration
or is using the new one. If the user expects the legacy, we should act as though they correctly specified with the new config, rather
than allowing a mixture of new and old
> [1.14] When plugin_dir is set, only use that value

- README.md
This commit adds documentation about how to use the HTTP API and which
information it provides.
> Add documentation about the HTTP API

- lib/config.go
- oci/runtime_oci.go
There exist situations in which run root can be empty for a runtime. The main situation we could encounter is during an upgrade from 1.14 -> master (and soon 1.15), the crio.conf won't have a runtime.runroot specified (because it is a new feature). 
This PR has two possible solutions for this problem. One is we could only specify the run root to the runtime if it is set. This is a bit verbose, but doesn't require hardcoding a default in the runtime_oci.
The second is simply set a default if it is not set. It's much cleaner.
I am opening a WIP PR with both, and upon deciding which (or both) is better I'll update the PR and take the WIP off
> Fix error when run root is empty

- .circleci/config.yml
This step was missing during the migration from travis to CircleCI.
We're now able to upload the coverage directly from CircleCI, too.
> Add codecov upload step to CircleCI config

- contrib/test/integration/critest.yml
- test/critest.bats
I see a [flaking critest spec](https://circleci.com/gh/openSUSE/cri-o/7306) when running critest in parallel. I think this happens because image layers get removed because of the parallelism which causes other tests to fail. For now I'd suggest to enable the ginkgo `flakeAttempts` to make the tests more reliable.
References https://github.com/kubernetes-sigs/cri-tools/issues/472
> Add flake attempts to critest integration testing

- contrib/test/integration/e2e-features.yml
> Fix SELinux denials in e2e_features_* tests

- server/container_create.go
- server/naming.go
- server/naming_test.go
- server/sandbox_run.go
- server/sandbox_run_linux.go
This commit refactors the name generation of containers and sandboxes,
whereas the unit tests have been added as well.
The handling of duplicate sandbox ids has been removed, since these code
paths were not possible any more after the merge of commit 187f850. This
also removes a regular expression parsing of an error message.
This commit reduced the cyclomatic complexity of `runPodSandbox()` down
to 116 and increases the overall testability and coverage.
---
Refers to #1988
WDYT about the removal of the duplicate ID handling? To me it seemed pretty unlikely that this happens and if so, is removing the pod including all its workload the right approach? I thought "no", so I'd go for a removal of the code part.
> Refactor sandbox and container name reservation

- cmd/crio/config.go
- docs/crio.conf.5.md
- lib/config.go
- lib/container_server.go
- pkg/storage/image.go
- pkg/storage/image_test.go
- pkg/storage/runtime.go
- pkg/storage/runtime_test.go
- server/config_test.go
- server/fixtures/crio.conf
- server/image_pull.go
> Add a global_auth_file option under crio.image to the crio config. This option points to a json file that holds the credentials required to pull images from a secure registry. The json file is similar to that of .docker/config.json.
>
> Will forward-port to master as well.
This starts with #2498, and:
- removes some dead code
- fixes the case when the CRI client provides credentials (for the primary registry)
- adds use of `globalAuthFile` for the pause image if no specific credentials are provided
This is a functionally minimal set of changes that reflect how the API is probably _intended_ to be used, but not quite exhaustive for how it _could_ be used (e.g. it seems that calling CRI `ImageStatus` with a `docker://example.com/foo:tar` image name would actually try to contact the remote …
> [1.14] Add global_auth_file option to crio.image config

- .gitignore
Failing tests will cause the junit XML files to not being moved into the
test results directory. We now exclude them to avoid commiting them into
the repository.
> Add junit test files to .gitignore

- server/sandbox_stop_linux.go
> [1.13] Add state of infracontainer to disk when stopped

- server/sandbox_stop_linux.go
> [1.14] Add state of infracontainer to disk when stopped

- conmon/conmon.c
before we attempt to create the attach socket, make sure it doesn't
already exist otherwise bind(2) will fail with EEXIST.
Closes: https://github.com/containers/libpod/issues/3381
> conmon: force unlink attach socket

- lib/container_server.go
- server/sandbox_stop.go
being stopped.
Changed up the path to match the current cri-o/cri-o repo path, hopefully tests will pass this way.
> [1.9]  Add state of infracontainer to disk when stopped

- lib/container_server.go
- server/sandbox_stop.go
> [1.11] Add state of infracontainer to disk when stopped

- .circleci/config.yml
- .gitignore
- Makefile
- bundle/Makefile
- bundle/build
This commit adds a `bundle` Makefile target which can be used to create
a build artifact tarball which contains static binaries and necessary
configurations. The target will be used by CircleCI to provide
continuous results. We can also attach bundles for specific versions on
corresponding GitHub releases.
Example run:
https://8210-161810706-gh.circle-artifacts.com/0/bundle/crio-33a105c0e.tar.gz
> Add release bundle target

- lib/config.go
- lib/config_test.go
- lib/suite_test.go
- server/config_test.go
- utils/filesystem.go
- utils/filesystem_test.go
Create network and plugins directories if they don't exist
There are situations where pods using the host network wish to inject plugins and networks for cri-o to use later. To do this, cri-o needs to be able to get there. Create network and plugins dirs and allow cri-o to continue until the kubelet asks it for a plugin or network it doesn't have.
> [1.14] Create network and plugin directories

- contrib/test/ci/cri-o.spec
- images/os/Dockerfile
We fail if the cri-o version for 1.14 does not match a certain
pattern.
Use the 4.2 machine os content image for the ci.
> [1.14] Fix up machine os content version and cri-o version in spec

- server/container_create_linux.go
- server/sandbox_run_test.go
Bump up the minimum memory limit allowed for running containers
from 4Mb to 12Mb.
Will backport to 1.14 and 1.13 as well.
For https://bugzilla.redhat.com/show_bug.cgi?id=1705322
> Bump up minMemoryLimit to 12Mb

- contrib/test/integration/e2e.yml
- oci/container.go
- oci/runtime_oci.go
Detach automatically on stdin EOF for a non-tty attach when stdin Once is not set.
Forward port of https://github.com/cri-o/cri-o/pull/2129
> Enable inline exec and attach test

- .circleci/config.yml
We now add a stub that CircleCi does not complain any more.
> [1.14] Backport empty CircleCI config

- .circleci/config.yml
We now add a stub that CircleCi does not complain any more.
> [1.13] Backport empty CircleCI config

- contrib/test/integration/e2e.yml
- oci/container.go
- oci/runtime_oci.go
Detach automatically on stdin EOF for a non-tty attach when stdin Once is not set.
Forward port of https://github.com/cri-o/cri-o/pull/2129
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1723295
> [1.14] enable inline exec and attach test

- version/version.go
- version/version_test.go
There isn't a technical reason we need to error if the gitCommit isn't defined.
Since gitCommit isn't always defined, silently move on instead.
> [1.14] version: if git commit is empty, silently ignore

- .circleci/config.yml
We now add a stub that CircleCi does not complain any more.
> [1.12] Backport empty CircleCI config

- server/container_create_linux.go
Bump up the minimum memory limit allowed for running containers
from 4Mb to 12Mb.
> [1.13] Bump up minMemoryLimit to 12Mb

- server/container_create_linux.go
Bump up the minimum memory limit allowed for running containers
from 4Mb to 12Mb.
> [1.14] Bump up minMemoryLimit to 12Mb

- Makefile
We just exclude everything within the 'vendor' directory since this is out of our direct domain.
> Exclude 'vendor' for git-validation checks

- server/sandbox_stop_linux.go
- server/sandbox_stop_test.go
> Add state of infracontainer to disk when stopped

- cmd/crio/config.go
- cmd/crio/main.go
- lib/config/config.go
- lib/config/suite_test.go
- lib/container_server_test.go
- lib/suite_test.go
- oci/oci_test.go
- server/config.go
- server/config_test.go
- server/inspect_test.go
- server/server.go
- server/server_test.go
- server/suite_test.go
Motivated by https://github.com/cri-o/cri-o/pull/2494#pullrequestreview-251539419, changed `lib.DefaultConfig` to not read defaults from `registries.conf`.
Don't read `registries.conf` for the defaults of `--registry` and `--insecure-registry`:
In both cases, the `ImageService` falls back to `registries.conf` anyway if the values are not specified (explicitly for the search path, and implicitly in containers/image/docker for insecure registries).  The default values in `lib.DefaultConfig` really make a difference only:
- in the help text of `--registry`, which was a bit misleading by suggesting a hard-coded default instead of pointing to `registries.conf`
- in the output of `crio config --default`, which previously copied the search list from …
> RFC: Don't read registries.conf for the defaults of --registry and --insecure-registry

- README.md
RawGit has reached the end of life, so we should consume the logo directly from the repository instead of there.
> Use repository logo instead of rawgit

- cmd/crio/config.go
- cmd/crio/main.go
- docs/crio.conf.5.md
- lib/config/config.go
- lib/config/testdata/config.toml
File locking adds runtime overhead and thus should be opted into as a user. Disable it by default here
> Disable file locking by default and mark depreciated

- pkg/storage/image.go
- pkg/storage/image_test.go
- pkg/storage/runtime.go
- pkg/storage/runtime_test.go
- server/container_create_linux.go
- server/container_create_test.go
- server/image_pull.go
- server/image_pull_test.go
- server/sandbox_run_linux.go
- server/server.go
- test/mocks/criostorage/criostorage.go
- vendor/modules.txt
On top of #2514 , reviewed the uses of c/image API, and made various cleanups and smaller bug fixes.
Two notable major themes:
- `ListImages`/`ImageStatus` now do much less redundant work (decreasing the number of c/storage calls, and the implied locking operations necessary), and share more code
- `types.SystemContext` options that apply ~globally are set once in `server.Server.systemContext`, and automatically used throughout the call stack. Notably `GlobalAuthFile` is now handled only in one place.
See individual commit messages for details.
(This depends on, and currently includes #2514, I will rebase this after that PR is merged.)
Hopefully the existing CI.
`ListImages` and `ImageStatus` …
> c/image API use cleanups

- go.mod
The dependency is not needed within our go.mod, so we remove it.
> Remove unnecessary indirect dependency gopopulate

- cmd/crio/main.go
- lib/config/config.go
- lib/config/config_test.go
- lib/container_server.go
- oci/oci.go
- oci/oci_test.go
- server/config_test.go
- server/suite_test.go
The default runtime path for `runc` is now `""` and we discover the
executable directly from the local $PATH environment. Is it nevertheless
possible to set the `runtime_path` directly, where we still test for
existence on runtime.
The validation of the runtime handlers within `oci.go` has been cleaned
up, to bring back the matter of concerns to `config.go`. We now use
pointers to easily update the runtime handlers during validation, where
a new type `Runtimes` got introduced.
All tests have been adapted as well.
> Discover runtimePath from $PATH environment

- lib/container_server_test.go
The library creation does not validate the runtime config that tight any
more, so we should remove that invalid use case.
> Remove invalid unit test to unblock master branch CI

- .circleci/config.yml
The manually hard-enabled seccomp variable should not be needed if we
pass the right path for the "checkseccomp" executable into the CI.
> Fix seccomp checks for integration tests

- Makefile
Dependent targets to also not run via sudo, which will break up
image-preparation when running via podman.
> Remove unnecessary sudo from Makefile

- test/helpers.bash
The `$CRIO_ROOT` variable seems to be not the root of the repository,
which make the integration tests fail outside of the usual
`../cri-o/cri-o` GOPATHs.
> Fix invalid CRIO_ROOT for integration tests

- docs/crio.8.md
- lib/config/config.go
- server/container_create_linux.go
- server/server.go
This ensures that the default configuration of CRI-O always installs
the default apparmor profile named `crio-default-vx.xx.x[-dev]`. The
logging verbosity has been increased during startup to give the user a
higher transparency about the current profile.
> Change default apparmor profile to actually contain the version

- server/container_create.go
- server/server.go
- vendor/modules.txt
The default values are part of Kubernetes so we do not need to maintain
them in CRI-O.
> Update apparmor defaults to use them of Kubernetes

- Makefile
- cmd/crio/config.go
- docs/crio.8.md
- docs/crio.conf.5.md
- lib/config/config.go
- lib/config/config_test.go
- lib/config/config_unix.go
- lib/config/config_windows.go
If conmon in the config is empty or not available, we now search it
inside the $PATH variable before actually failing.
We could do the same for the runtimes, WDYT?
> Search conmon executable in $PATH

- pkg/storage/image.go
- server/image_pull.go
- test/mocks/criostorage/criostorage.go
The ImageServer interface in pkg/storage documents that images returned
by PrepareImage() should have Close() called. Neglecting to close the
returned image will fill /var/tmp with large temporary files when using
at least the docker-archive transport.
This patch modifies said interface to allow Close() to be called and
adds a call to Close() in PullImage().
Signed-off-by: Marc Burns <m4burns@uwaterloo.ca>
Cherry-pick of: https://github.com/cri-o/cri-o/pull/2440
> Close temporary image in PullImage

- server/container_create.go
- utils/utils.go
- utils/utils_test.go
- version/version.go
When generating a an entry in the /etc/passwd file, we
need to also add username and homedir, so that the user
can properly login.
Port of #2325
> [1.14] Add username and homedir to generated password

- .codecov.yml
I think this should solve our codecov issues with release branches. The configuration is not very well documented so I might miss some point here. Afterwards, we could enable codecov again.
/cc @umohnani8
> Update codecov config to be less strict

- Makefile
- cmd/crio/main.go
- docs/crio.8.md
- test/command.bats
- test/helpers.bash
This commit adds  short flags to the config flags `root`, `log-level`,
`storage-driver` and `config` as well as their usage within our
scripting.
> Add short CLI flags to common configurations

- Makefile
`go build` already creates the output directory so there is no need for
a manual creation. All relevant make targets has been adapted as well.
> Remove unnecessary directory creation

- contrib/crio-wipe/crio-wipe.bash
Stderr was redirected improperly when calling crio-wipe with invalid arguments. Fix this, and an indentation problem
> [1.14] Small crio wipe fix

- tutorials/setup.md
There were several dependencies which couldn't be installed using 'yum install command' for the RHEL8 distribution while creating crio from source. The 'setup.md' file has been modified with a separate section added for the RHEL8 distribution which has the links for installing the dependencies using rpm(s).
> Changes for the RHEL 8 distribution dependencies in the setup.md under the Tutorials folder

- cmd/crio/main.go
- internal/oci/runtime_vm.go
- tutorials/setup.md
Build cri-o with go1.10 (the default go version in Buildroot 2018.05.x, used by minikube)
Built the minikube.iso, see https://github.com/kubernetes/minikube/pull/4703 and `make out/minikube.iso`
`minikube start --container-runtime=cri-o --iso-url=file://$PWD/out/minikube.iso`
Allow building with go1.10
Closes #2573
> Allow building with go1.10

- test/bin2img/bin2img.go
- test/copyimg/copyimg.go
A recent PR (#2571 ) updated usage of "--storage-driver" to "-s" in the Makefile:
https://github.com/cri-o/cri-o/blob/7e0cf4b096d7e0b952cf9c6979346b1afadb034b/Makefile#L187
However the corresponding short flags were not added to test/bin2img/bin2img.go or test/copyimg/copyimg.go
This causes integration tests to fail unless STORAGE_OPTIONS is overridden by the environment.
This commit adds the short flags "-s" (--storage-driver) and "-r" (--root) into copyimg and bin2img.
> Add missing shortflags to bin2img and copyimg to fix integration tests

- Makefile
The new go-build function within the Makefile allows automatic binary
name resolution via the `basename`. We also add an empty echo to avoid
confusing outputs that the target is already up-to-date.
> Update tools make targets to be less verbose

- .codecov.yml
The patch comparison of codecov can still fail which is not what we
want. This can cause trouble if there are no coverage related code
changes involved.
Relevant codecov docs:
https://docs.codecov.io/docs/commit-status#section-patch-status
> Update codecov patch comparison to succeed

- .circleci/config.yml
- Added legacy-go build to the CI config
- Abstract commonly used environment variables into `stdenv`
- Renamed `docker` to `container` in preparation to switch to podman
soon
Follow up of #2574
> Add go 1.10 build to CircleCi

- Makefile.inc
If the `git` executable is not available then the `git-vars` Makefile
target will now cover that as well.
Refers to #2575
> Update git-vars target to check for executable as well

- .codecov.yml
Backport of #2585 and #2570
Cherry-picked: daaa61f1f60dfe358fedc6c6cceccd7c69f831ee
Cherry-picked: e0b80b94225c1c51221933bfd8796638e5e241e5
> [1.15] Update codecov config to be less strict

- Makefile
The `git-vars` target force a rebuild of the `config.h` even if it
already exist. This can break build-setups, so we remove it from the
`config.h` generation.
Related discussion: https://github.com/kubernetes/minikube/pull/4703/files#r301143546
> Remove git-vars from conmon/config.h generation

- .codecov.yml
Backport of #2585 and #2570
Cherry-picked: daaa61f1f60dfe358fedc6c6cceccd7c69f831ee
Cherry-picked: e0b80b94225c1c51221933bfd8796638e5e241e5
> [1.14] Update codecov config to be less strict

- Makefile
The `git-vars` target force a rebuild of the `config.h` even if it
already exist. This can break build-setups, so we remove it from the
`config.h` generation.
Cherry-picked: aea87f45229fe72d82e3dabfa730dd6cddbf92ac
---
Backport of #2583
> [1.15] Remove git-vars from conmon/config.h generation

- Makefile.inc
- conmon/Makefile
Some environments default to `/bin/sh` as shell, which will break the
`git-vars` target because of its `[[ .. ]]` syntax. To avoid such, we
now execute a bash shell around it.
Another fix included in this commit is that the `.git` directory does
not necessary needs to be part of the current working directory, for
example when including the Makefile.inc in the `conmon` dir. For that
we now use the command `git rev-parse --git-dir` to avoid this issue.
The version.go file is now located in `internal/version`, which has been
fixed as well.
---
The output can be verified at: https://circleci.com/gh/openSUSE/cri-o/12346
> Fix git-vars target for shells which do not default to bash

- cmd/crio/main.go
If the version is 'unknown' we don't print it anymore to avoid user
confusion.
> Do not print 'unknown' versions

- cmd/crio/main.go
- docs/crio.8.md
This commit adds the corresponding CLI flag to `config.GlobalAuthFile`.
> Add missing global-auth-file CLI flag

- contrib/crio-wipe/50-crio-wipe.preset
- contrib/crio-wipe/crio-wipe.service
- version/version.go
In openshift, the machine-os-content container is spilled onto disk, and pivot is called. pivot only copies /usr and /etc, and ignores /var. Thus, for crio-wipe to actually exist on reboot, it must be installed into usr.
> [1.14] run crio-wipe from /usr and add system-preset

- Makefile
- tutorials/setup.md
This commit adds a new `release-bundle` target for building a static
release archive locally. Documentation has been added as well. Since we
default to rootless podman, the additional `chown` is not needed any
more when compiling a static binary.
> [1.15] Add release bundle target and documentation

- Makefile
- tutorials/setup.md
This commit adds a new `release-bundle` target for building a static
release archive locally. Documentation has been added as well. Since we
default to rootless podman, the additional `chown` is not needed any
more when compiling a static binary.
Forward-port of: https://github.com/cri-o/cri-o/pull/2602
Cherry-picked: 3b4e3bd54ee139f547d0f4afc5f352f41b79aeef
> Add release bundle target and documentation

- internal/lib/remove.go
- internal/oci/container.go
- internal/oci/oci_linux.go
- server/sandbox_remove.go
Clean up conmon cgroups when removing a sandbox.  This requires to
record the conmon's cgroup path for each container and delete if for
normal and infra containers.
Fixes: #838
---
Once https://github.com/containers/libpod/pull/3554 is merged, we can re-vendor libpod and everything will be clean (I tested locally). Let's get this merged before though as the logic won't change for crio.
> cgroupfs: don't leak conmon cgroups

- cmd/crio/config.go
- cmd/crio/main.go
- docs/crio.conf.5.md
- internal/lib/config/config.go
This PR fixes some documentation related issues. Every single change is done in a dedicated commit. I'm working on a script which could check these kind of issues within the CI.
> Fix documentation between crio.conf.5.md and source

- test/cni_plugin_helper.bash
- test/helpers.bash
- test/network.bats
The AMI update requires a fix of the pod IP retrieval to finally work
again.
> [1.13] Fix integration tests for CNI update

- test/cni_plugin_helper.bash
- test/helpers.bash
- test/network.bats
The AMI update requires a fix of the pod IP retrieval to finally work
again.
Cherry-picked: 82d6ddec8397d8426d34c85eccb7a018ec86d94e
Backport of #2608
> [1.12] Fix integration tests for CNI update

- cmd/crio/config.go
- cmd/crio/main.go
- docs/crio.8.md
- docs/crio.conf.5.md
- internal/lib/config/config.go
- internal/lib/config/config_unix.go
- internal/lib/config/config_windows.go
- internal/lib/config/testdata/config.toml
- internal/lib/container_server.go
- internal/lib/container_server_test.go
- internal/lib/suite_test.go
We deprecated file-locking with the last release so it could be removed
for the next one. Tests and documentation has been adapted as well.
> Remove deprecated file-locking

- oci/container.go
Return before using nil cgroup if there was an error loading conmon
cgroup for a container.
Signed-off-by: Marius Grigoriu <marius.grigoriu@me.com>
Backported-by: Valentin Rothberg <rothberg@redhat.com>
---
Backport of https://github.com/cri-o/cri-o/pull/2621
> [1.14] Return if error loading cgroup CleanupConmonCgroup

- oci/container.go
Return before using nil cgroup if there was an error loading conmon
cgroup for a container.
Signed-off-by: Marius Grigoriu <marius.grigoriu@me.com>
Backported-by: Valentin Rothberg <rothberg@redhat.com>
---
Backport of https://github.com/cri-o/cri-o/pull/2621
> [1.15] Return if error loading cgroup CleanupConmonCgroup

- internal/oci/container.go
Return before using nil cgroup if there was an error loading conmon cgroup for a container
Fixes #2620 
Return if error loading cgroup before calling cg.Delete()
Looks like CleanupConmonCgroup doesn't have any tests. What would be a good way to test this?
Don't panic if conmon cgroup could not be loaded during cleanup (Fixes #2620)
> Return if error loading cgroup CleanupConmonCgroup

- conmon/conmon.c
- test/helpers.bash
- test/network.bats
- version/version.go
Side-ported-by: Peter Hunt <pehunt@redhat.com>
> [1.11] conmon: check it is a valid pid before killing it

- .circleci/config.yml
- Dockerfile
- contrib/test/integration/main.yml
- test/pod.bats
This also updates the image used by CircleCI. We have to modify the
idempotency test because crictl now errors if the pod does not exist any
more.
~Needs https://github.com/kata-containers/tests/pull/1778 merged before kata works.~
> Bump cri-tools to v1.15.0

- Dockerfile
Since the Kata tests are now independent of the Dockerfile we are fine
removing the additional environment variable.
This is a small follow-up of: https://github.com/cri-o/cri-o/pull/2566
> Remove CRICTL_COMMIT from Dockerfile

- server/container_create_linux.go
- test/ctr.bats
- test/testdata/container_config_privileged.json
Set all OCI mounts as privileged when running in privileged mode.
Backport-of: d3a50d86f8803e21b9ff8e28d4d821bf677a70ac
> [1.15] privileged: set mounts to rw

- conmon/conmon.c
> [1.13] conmon: check it is a valid pid before killing it

- conmon/conmon.c
> [1.15] conmon: check it is a valid pid before killing it

- .circleci/config.yml
The test-binaries target needs further dependencies which are not
fulfilled any more by circleci/golang. Beside this we pin it to the
latest 1.12 tag.
> Pin CircleCI base image and update builds

- docs/crio.conf.5.md
Follow up on #1934, based on improvements by Github user Chenditang.
Adding more info to default_ulimits, additional_devices, and bind_mount_prefix.
Signed-off-by: Sameer Chaturvedi <sam.chaturvedi@gmail.com>
> Update crio.conf man page

- conmon/conmon.c
> [1.14] conmon: check it is a valid pid before killing it

- internal/pkg/log/interceptors.go
- internal/pkg/log/log.go
- internal/pkg/log/log_test.go
- internal/pkg/log/suite_test.go
This suite ensures that the internal log abstraction works as intended
and applies necessary unit tests to them.
> Add internal log unit tests

- cmd/crio/main.go
- internal/pkg/log/hooks.go
The newly added log hook will be only executed on debug output, since it
might be possible that it has performance drawbacks. When debug output
is enabled, then we now retrieve the correct file location for the log
message as well via the field `file="name:line"`.
---
Example for debug (with the new `file` field):
```
DEBU[2019-07-22 10:29:52.218612088+02:00] using runtime executable from $PATH "/usr/sbin/runc"  file="config/config.go:695"
DEBU[2019-07-22 10:29:52.218696862+02:00] found valid runtime "runc" for runtime_path "/usr/sbin/runc"  file="config/config.go:701"
INFO[2019-07-22 10:29:52.218830929+02:00] using conmon executable "/usr/lib/crio/bin/conmon"  file="config/config.go:721"
DEBU[2019-07-22 10:29:52.218984011+02:00] [graphdriver] trying provided driver "btrfs" …
```
> Add filename log hook

- conmon/conmon.c
> conmon: check it is a valid pid before killing it

- tutorials/setup.md
Fixes #1668 
Fixes #1664.
On Ubuntu distributions, libudev was missing during make, and add-apt-repository was missing.
Signed-off-by: Sameer Chaturvedi <sam.chaturvedi24@gmail.com>
> Update tutorial for building from source

- Dockerfile
- server/server.go
First, attempt to find an IP address that is clearly the primary. If we fail to do so, find one with /proc/net/route
> [1.13] Allow default route to not be present

- Dockerfile
- test/ctr.bats
The package `libprotobuf-c0-dev` changed to `libprotobuf-c-dev`, so we
adapt our Dockerfile to it.
Cherry-picked: fa7b9795095a4dca64f60d5f9adb0d1bfe9da0d1
Backport of: #2651
> [1.14] Fix container image used for integration tests

- test/helpers.bash
the integration_* suites have been failing because the tempdir is busy.
Make the removal best effort instead
> Make integration tests more reliable

- server/sandbox_run_linux.go
Signed-off-by: Richard Kojedzinszky <richard@kojedz.in>
Fixes #2669
Changed the parsing of memory.limit_in_bytes to use strconv.ParseInt which returns int64.
On armhf platforms it now works.
Commit 76199c9168d86d3ced4fba3ff7d4c10338d5bc6b introduced a check, which on armhf fails to parse numbers larger than 32 bit due to using Atoi for conversion. This fixes that.
> [1.13] Fix parse of memory.limit_in_bytes on 32-bit machines

- server/server.go
First, attempt to find an IP address from /proc/net/route. If we fail to do so, attempt to find a clear primary
> [1.14] Allow default route to not be present

- server/container_status.go
- server/container_status_test.go
Use the name we stored in the container object in container status
rather than recalculating it.
> [1.15] container_status: Use cached value of image name

- server/container_status.go
Use the name we stored in the container object in container status
rather than recalculating it.
> [1.13] container_status: Use cached value of image name

- server/sandbox_run_linux.go
Signed-off-by: Richard Kojedzinszky <richard@kojedz.in>
Forward port of #2668
> [1.14] Fix parse of memory.limit_in_bytes on 32-bit machines

- server/container_create_linux.go
Set all OCI mounts as privileged when running in privileged mode.
Backport-of: d3a50d86f8803e21b9ff8e28d4d821bf677a70ac
> [1.13] privileged: set mounts to rw

- test/helpers.bash
the integration_ suites have been failing because the tempdir is busy
Make the removal best effort instead
pick of: https://github.com/cri-o/cri-o/pull/2582
> [1.15] Make integration tests more reliable

- server/sandbox_run_linux.go
Signed-off-by: Richard Kojedzinszky <richard@kojedz.in>
Forward port of #2668
> [1.15] Fix parse of memory.limit_in_bytes on 32-bit machines

- server/server.go
First, attempt to find an IP address from /proc/net/route. If we fail to do so, attempt to find a clear primary
> [1.15] Allow default route to not be present

- server/container_status.go
Use the name we stored in the container object in container status
rather than recalculating it.
@nalind ptal. I am reversing what was introduced in f3b7065bd80a53e4c48e8c45c36dcb86717e1578.
> [1.14] container_status: Use cached value of image name

- Dockerfile
The package `libprotobuf-c0-dev` changed to `libprotobuf-c-dev`, so we
adapt our Dockerfile to it.
Cherry-picked: fa7b9795095a4dca64f60d5f9adb0d1bfe9da0d1
Backport of: #2651
> [1.15] Fix container image used for integration tests

- cmd/crio/main.go
- oci/runtime_vm.go
- tutorials/setup.md
Backport of https://github.com/cri-o/cri-o/pull/2574
Cherry-picked: 4ca2b7997e6719ac0e9a09bd1291103493cbb9f3
Fixes: #2692
> [1.15] Allow building with go1.10

- vendor.conf
- vendor/github.com/containers/storage/layers.go
this hopefully will prevent a deadlock for calls having to do with images
should fix https://github.com/cri-o/cri-o/issues/2584
> [1.14] pick c/storage #401

- contrib/crio-wipe/lib.bash
With the current code running crio-wipe.bash will
error on operand expected (error token is ""1" + 0").
This patch uses  declare -i will define new/old as integer
Fixes #2704
Signed-off-by: Moshe Levi <moshele@mellanox.com>
just run ./crio-wipe.bash
> crio-wipe: Fix int compare in lib.bash

- server/sandbox_network.go
I'm opening a separate PR for this because I think this is an implementation mistake I did during the IPv6/multi IP integration.
---
If we try to allocate the same hostport twice for a different IP, the result will always be a failure because the host port has already been allocated. To avoid this we only try to bind the port for the first seen IP.
We're currently not capable of deciding what the 'major IP' of the pod should be so we take the first one. WDYT?
> Use only the first IP for host port allocation

- Makefile
- contrib/systemd/crio.service
- changed Makefile to pass config parameters to crio.conf generation
- changed main to set runtime-untrusted from command line
- changed crio.service to enable easier cmdline customization 
- pass ```--runtime-untrusted``` from crio cmdline with various parametes
- build with ```make CONF_OVERRIDES="<any accepted cmdline>"``` to customize ```crio.conf```
- set ```crio.service.d/test.conf``` with ```[Service]\nEnvironment="CRIO_RUNTIME_OPTIONS=--untrusted-runtime /path/to/runtime"```
Add --runtime-untrusted command line option
Improve build and runtime customization
> Improve build and runtime customization

- server/server.go
The apparmor profile content is now printed to the logs when the level
is "trace". Beside this, the apparmor error handling has been unified as well.
> Add apparmor profile content output on "trace" log level

- server/sandbox_run_linux.go
Signed-off-by: Richard Kojedzinszky <richard@kojedz.in>
Forward port of #2668
> Fix parse of memory.limit_in_bytes on 32-bit machines

- server/container_create.go
- server/container_create_linux.go
- test/image_volume.bats
- test/testdata/container_config.json
Fixes #2562, to ensure that image volumes are always writeable from inside the container.
User will have correct permissions if `run_as_user` value is specified for the container.
Also added a test for this feature.
Signed-off-by: Sameer Chaturvedi <sam.chaturvedi24@gmail.com>
> Make image volumes writeable by the container user

- cmd/crio/main.go
gRPC clients which wait until they receive a `SETTINGS` frame may not be
able to connect to CRI-O because of a limitation to cmux:
- https://github.com/soheilhy/cmux#limitations
The issue seems not yet solved and causes impossible connection when
upgrading cri-tools to the latest version of gRPC. A possible workaround
is to export the environment variable: `GRPC_GO_REQUIRE_HANDSHAKE=off`.
References:
- https://github.com/grpc/grpc-go/issues/2636
- https://github.com/kubernetes-sigs/cri-tools/pull/499
> Use HTTP2MatchHeaderFieldSendSettings for incoming gRPC connections

- server/container_status.go
- server/container_status_test.go
Use the name we stored in the container object in container status
rather than recalculating it.
> container_status: Use cached value of image name

- cmd/crio/main.go
- docs/crio.8.md
- docs/crio.conf.5.md
- internal/lib/config/template.go
- test/docs-validation/main.go
This commits adds all missing CLI flags which are not yet existing but
possible to set via the configuration file. These are:
- `--conmon-env`
- `--container-attach-socket-dir`
- `--container-exits-dir`
- `--ctr-stop-timeout`
- `--file-locking-path`
- `--grpc-max-recv-msg-size`
- `--grpc-max-send-msg-size`
- `--host-ip`
- `--manage-network-ns-lifecycle`
- `--no-pivot`
- `--stream-enable-tls`
- `--stream-tls-ca`
- `--stream-tls-cert`
- `--stream-tls-key`
The deprecated file locking related flag has been removed from the
docs check.
> Add missing CLI flags

- test/apparmor.bats
- test/cgroups.bats
- test/critest.bats
- test/ctr.bats
- test/ctr_seccomp.bats
- test/ctr_userns.bats
- test/default_mounts.bats
- test/helpers.bash
- test/hooks.bats
- test/image.bats
- test/image_remove.bats
- test/image_volume.bats
- test/inspect.bats
- test/namespaces.bats
- test/network.bats
- test/pod.bats
- test/reload.bats
- test/restore.bats
- test/runtimeversion.bats
- test/selinux.bats
- test/shm.bats
- test/status.bats
Clean up the integration tests by cleaning /tmp more consistently (more details in commit message) and remove the `|| true` hack to work on getting to the bottom of those flakes.
> Round 2 of integration test fixes

- contrib/test/integration/e2e-base.yml
- contrib/test/integration/e2e.yml
- contrib/test/integration/vars.yml
to enable ssh tests in e2e
(and don't change the k8s branch, in a naive hope that the e2e fixes have magically happened upstream)
> set kube_ssh_user for e2e tests

- server/container_stats.go
This fix allows using short container IDs in the ContainerStats() request
Unlike all of the other CRI RPC calls, ContainerStats() would require using the full container ID. This change enables the short container ID to be used for the ContainerStats() call.
Call ContainerStats() with a ContainerStatsRequest that contains a short container id. 
Allow usage of short container ID in ContainerStats() request
> Allow usage of short container ID in ContainerStats()

- internal/lib/config/config.go
- internal/lib/config/config_test.go
- server/suite_test.go
If the log_dir is an relative path, then the creation of the
container/sandbox will fail during runtime. To avoid this, we now
pre-check if the path is absolute. All tests have been adapted as well.
> Add `log_dir`/`--log-dir` validation to be absolute

- internal/lib/config/config.go
- internal/lib/config/config_test.go
- internal/oci/oci.go
- internal/oci/runtime_vm.go
A follow up of https://github.com/cri-o/cri-o/pull/2748
---
The `runtime_type` for each runtime gets now validated if it's either
empty (falls back to OCI), "oci" or "vm". Everything else will now be
treated as misconfiguration whereas CRI-O won't start any more.
All tests have been adapted as well.
> Add config `runtime_type` validation

- cmd/crio/main.go
- docs/crio.conf.5.md
- server/server.go
- server/server_test.go
- server/suite_test.go
- test/helpers.bash
- test/reload_config.bats
- test/reload_system.bats
This enables SIGHUP based system registry reload via a new configuration
watcher. The path of the system registries.conf can be now set via an
hidden command line flag of CRI-O as well.
The configuration reload based integration tests start now all with
'reload config', whereas the helper functions `reload_crio` and
`wait_for_log` are globally available.
Integration tests for the feature have been added as well as unit tests.
>  Add HUP reload feature for SystemRegistries

- server/container_create.go
If the host directory is not created, and cri-o must create the directory, the selinux label needs to be applied to the new directory.
```
Fix for the selinux label on a newly created host directory.
```
> fix selinux label on volume mount directory creation

- internal/lib/config/template.go
With the wonderful support of @marcov, we now have a better explanation about how to configure additional runtimes. We also added examples for katacontainers.
> Add additional documentation to runtime configurations

- internal/lib/container_server_test.go
This test is not possible to succeed any more, whereas the test result is
wrong when running as `root`.
> Remove unnecessary store nil unit test

- conmon/conmon.c
Signed-off-by: Gábor Lipták <gliptak@gmail.com>
http://jenkins.katacontainers.io/job/kata-containers-firecracker-PR/252/consoleText
```
cc -std=c99 -Os -Wall -Wextra -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -DVERSION=\"1.15.0\" -DGIT_COMMIT=\"unknown\"  -D USE_JOURNALD=0   -c -o conmon.o conmon.c
conmon.c: In function ‘oom_cb_cgroup_v2’:
conmon.c:575:2: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
read(fd, &events, sizeof(events));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
Check inotify events read return code
> Check inotify events read return code

- vendor.conf
- vendor/github.com/containers/storage/layers.go
Pulls in fixes to ensure we don't double lock the mounts list
while saving and cleanup.
> Vendor in updated c/storage cri-o-release-1.14 branch

- internal/pkg/storage/image.go
If we've pulled down more than one manifest for an image (e.g., using different digests for the same image, as identified by its configuration blob), return all of their digests in RepoDigests when we're asked about the image.
> makeRepoDigests(): add all manifest digests to RepoDigests

- contrib/test/integration/main.yml
it causes issues on the git clone on fedora
> [1.16] e2e: turn on force_clone for kubetest

- server/utils.go
**- What I did** 
Set bandwidth default burst limits to 4GB instead of UInt64 Max to accomodate the same logic as per [https://github.com/containernetworking/plugins/pull/389](here)
Changing from MaxUInt64 to MaxUint32 * 8
Compile and use with the PR with [https://github.com/containernetworking/plugins/pull/389](this) CNI plugin
Limit bandwidth burst to 4GB
> Burst for bandwidth can be only 4GB

- cmd/crio/main.go
- docs/crio.conf.5.md
- internal/lib/config/config.go
- internal/lib/config/template.go
- server/server.go
The metrics can now being configured via the crio.conf configuration
file, too. This means we move the metrics server creation logic into
the library and adapt all necessary documentation.
> Add metrics to configuration file

- tutorials/setup.md
Signed-off-by: Pedro Ibáñez <pedro@redhat.com>
Adding the missing part of 'https://' to the git clone command in the conmon setup point.
Editing tutorials/setup.md
Just take a look to the file.
Fixing git clone url for conmon setup.
> missing 'https://' in the clone from the conmon setup part

- .circleci/config.yml
- Makefile
- cmd/crio-status/main.go
- completions/bash/crio-status
- completions/fish/crio-status.fish
- completions/zsh/_crio-status
- docs/crio-status.8.md
The command line parser supports now direct man page generation from the
input commands and flags. This means we do not need to maintain an
intermediate markdown man page any more and can generate the
documentation directly from the command line parameters.
> Generate crio-status man page during build

- contrib/test/integration/build/kubernetes.yml
there were problems found by not doing so
> [1.14] e2e: regenerate api before making k8s

- contrib/test/integration/build/kubernetes.yml
- contrib/test/integration/main.yml
there were problems found by not doing so
> [1.13] e2e: regenerate api before making k8s

- contrib/test/integration/main.yml
Should fix the broken fedora tests.
> [1.16] Move e2e tests to k8s release-1.16 branch

- pkg/storage/utils.go
- server/server.go
before, the restore code would find every container in container storage. This would include podman containers. However, CRI-O never actually filtered podman containers out. This caused podman containers to have their configs and storage removed, so they couldn't be inspected.
Fix this by filtering for podman containers, by filtering containers that don't have a required CRI-O annotation
> [1.13] restore: Filter podman containers

- cmd/crio/wipe.go
- pkg/storage/utils.go
- server/server.go
before, the restore code would find every container in container storage. This would include podman containers. However, CRI-O never actually filtered podman containers out. This caused podman containers to have their configs and storage removed, so they couldn't be inspected.
Fix this by filtering for podman containers, similarly to how `crio wipe` does. While the current method isn't beautiful or elegant, it gets the job done, and opens the door for a lees implementation dependent solution
fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1758500
> [1.14] restore: Filter podman containers

- .circleci/config.yml
it seems it's not allowed in the free version
> [1.16] remove docker layer caching

- contrib/test/integration/e2e.yml
Kubernetes\se2e\ssuite\s\[sig\-storage\]\sCSI\sVolumes\s\[Driver\:\scsi\-hostpath\]\s\[Testpattern\:\sDynamic\sPV\s\(block\svolmode\)\]\svolumes\sshould\sstore\sdata$
is failing on fedora 30, skip it for the time being
> [1.16] skip e2e test

- contrib/test/ci/cri-o.spec
- contrib/test/ci/crio-metrics.sysconfig
- contrib/test/ci/crio-network.sysconfig
- contrib/test/ci/crio-storage.sysconfig
- contrib/test/ci/crio.service
- hack/build-rpms.sh
- hack/lib/build/binaries.sh
- hack/lib/build/rpm.sh
- hack/lib/build/version.sh
- hack/lib/constants.sh
- hack/lib/init.sh
- hack/lib/log/output.sh
- hack/lib/log/stacktrace.sh
- hack/lib/log/system.sh
- hack/lib/util/ensure.sh
- hack/lib/util/environment.sh
- hack/lib/util/find.sh
- hack/lib/util/misc.sh
- hack/lib/util/text.sh
- hack/lib/util/trap.sh
- images/os/Dockerfile
> [1.16] Add logic for running openshift e2e-aws tests

- README.md
Signed-off-by: Kenta Tada <Kenta.Tada@sony.com>
Modify README.md to install the CRI-O package correctly.
Change the apt-get install command  on Ubuntu distributions.
I actually installed CRI-O using my modified README.md.
In addition to that, I confirmed below Kubernetes's document.
https://v1-15.docs.kubernetes.io/docs/setup/production-environment/container-runtimes/
Fix CRI-O apt-get version
> Fix CRI-O apt-get version

- contrib/test/ci/cri-o.spec
With the current libseccomp, we see:
`undefined symbol: seccomp_api_get`.
Updating libseccomp to 2.4.1 resolves this issue.
@umohnani8 PTAL
> Require libseccomp >= 2.4.1-1 for CI

- contrib/test/integration/build/parallel.yml
- contrib/test/integration/python3.yml
- contrib/test/integration/system-packages.yml
the ansible version on rhel 7 is old enough such that a sufficiently complex boolean expression is interpreted as a string. This causes any supports_python3 condition to not execute.
instead, use set_facts with a when, so we properly set supports_python3
cherry-pick of https://github.com/cri-o/cri-o/pull/2898
> [1.16] fix ami rhel7

- contrib/test/integration/build/parallel.yml
- contrib/test/integration/python3.yml
- contrib/test/integration/system-packages.yml
the ansible version on rhel 7 is old enough such that a sufficiently complex boolean expression is interpreted as a string. This causes any supports_python3 condition to not execute.
instead, use set_facts with a when, so we properly set supports_python3
> fix ami rhel7

- bundle/Makefile
- bundle/README.md
- bundle/build
- contrib/policy.json
We now add the CNI, systemd, policy and CRI-O wipe filed to the bundle
as well. Additional documentation how to use the bundle is now included,
too.
> Add missing files to static release bundle

- internal/lib/config/template.go
- internal/lib/sandbox/sandbox.go
- server/sandbox_run_linux.go
- server/sandbox_run_test.go
The general target is to allow `pause_command = ""`, which should take the
entrypoint into account.
If the `pause_command = ""`, then its entrypoint will now be considered as
process arg, whereas the specified command in the image config will be
added as well. This keeps the backwards compatibility with images using
only `Cmd` and no `Entrypoint`.
If the `pause_command` is commented out, then it will still defaults to
`/pause`.
The logic has been refactored into a dedicated function to reduce the
cyclomatic complexity and allow proper testing.
> Fallback to pause image's entrypoint when config is empty

- internal/pkg/criocli/criocli.go
Start crio as regular user and it fail to write version to /var/lib/crio/version.
This change adds a config option to change the path.
Set version_path=/run/user/1000/crio_version to crio.conf
Check /run/user/1000/crio_version exists.
Add version_path option to set a custom CrioVersionPath
> Add version_path option to set a custom CrioVersionPath

- .circleci/config.yml
The CI sees some flakes in parallel build which should be solved in
splitting up the build process into three dedicated stages.
Example issue:
```
touch "/go/.gopathok"
make -C pause
make[1]: Entering directory '/go/src/github.com/cri-o/cri-o/pause'
cc -std=c99 -Os -Wall -Wextra -static   -c -o pause.o pause.c
mkdir -p ../bin
cc -o ../bin/pause pause.o -std=c99 -Os -Wall -Wextra -static 
make[1]: Leaving directory '/go/src/github.com/cri-o/cri-o/pause'
go build -ldflags '-s -w -X main.gitCommit="d735acbd64844c3df28c43b1db3a43c9ebb94998" -X main.buildInfo=1571914439' -tags "containers_image_ostree_stub apparmor      seccomp selinux" -o bin/crio github.com/cri-o/cri-o/cmd/crio
go build -ldflags '-s -w -X main.gitCommit="d735acbd64844c3df28c43b1db3a43c9ebb94998" -X main.buildInfo=1571914439' …
```
> Split-up build process to stabilize CI

- internal/lib/sandbox/sandbox.go
- pkg/config/template.go
- server/sandbox_run_linux.go
- server/sandbox_run_test.go
If the `pause_command = ""`, then its entrypoint will now be considered as
process arg, whereas the specified command in the image config will be
added as well.
If the `pause_command` is commented out, then it will still default to
`/pause`.
Backport of https://github.com/cri-o/cri-o/pull/2881
Cherry-picked: 37b42b5c1414c9e8ff902b0edf8f2987cce5b6f8
> [1.16] Fallback to pause image's entrypoint when config is empty

- contrib/test/integration/e2e-features.yml
- contrib/test/integration/e2e.yml
The `succinct` output of ginkgo should reduce the noise within the
tests, whereas the `noColor` should make it overall more readable.
> Improve e2e test output readability

- docs/crio.8.md
- docs/crio.conf.5.md
- internal/lib/config/config.go
- internal/lib/config/config_test.go
- internal/lib/config/template.go
- internal/pkg/criocli/criocli.go
- server/server.go
As a follow-up of #2781, we are now able to configure ~~multiple~~ up to two host IPs via the command line interface or configuration file. The specified IPs will now be verified during config validation.
@uablrek can you test if this works for you? It is now possible to run CRI-O like
```
> crio --host-ip 192.168.178.101 --host-ip 2a02:8106:20f:a000:3815:37ed:f926:e0f4
```
> Make multiple host IPs configurable

- server/sandbox_run_linux.go
before, if a pod was privileged, a pause container was set as privileged. This caused the rest of the containers in the pod to also need to inherit privileged labels from the pod (so they can join the pause container's namespaces).
In reality, there's little need for the pause container to have privileged (spc_t) label. It can manage an unprivileged namespace, and containers can join regardless of privilege. Further, the privilege of the pause container doesn't affect its ability to reap (if the pod shares pid).
Unconditionally set the pause container's process label, so the rest of the (unprivileged) containers in the pod inherit it.
> [1.16] reduce infra container's selinux privilege

- .circleci/config.yml
- Makefile
- contrib/test/integration/main.yml
- scripts/build-test-image
- test/critest.bats
- test/ctr.bats
- test/image.bats
With this commit we also provide three new build images based on go
1.13.4 and go 1.10.8 (legacy build). The following dependencies have
been updated as well:
- cri-tools: v1.15.0 → v1.16.1
- cni-plugins: v0.8.1 → v0.8.2
- conmon: v2.0.0 → v2.0.2
- runc: v1.0.0-rc8 → v1.0.0-rc9
> Update build dependencies (go 1.13)

- server/sandbox_network.go
- server/server.go
If the runtime returns an IP for a HostNetwork pod, then kubelet will accept that IP as the pod's PodIP. But if it returns nothing, kubelet will fill in the PodIP with whatever it considers the correct node IP to be. In particular, on a dual-stack host, letting kubelet decide will ensure that hostNetwork pods end up with the node's "preferred" IP according to kubelet.
(This change means that the `host_ip` config variable and all of the code for detecting it if it's not set is now *mostly* useless, although it still gets used to figure out `bindAddress`... Probably that can be simplified though.)
/cc @mrunalp @haircommander
> don't set PodIPs on host network pods

- completions/fish/crio.fish
The default storage driver should be empty and not btrfs,
which will finally fix-up the CI now.
> Fix default storage driver for completions validation

- docs/crio.conf.5.md
- internal/lib/config/config.go
Move from "pod" to "system.slice" for the conmon cgroup.
> Default to system.slice for conmon cgroup

- README.md
- transfer.md
We now add a note that we cannot guarantee a full interloper ability at
this time, which should avoid customers misusage from a certain level.
> Update usage transfer to include podman interoperability

- completions/fish/crio.fish
This seems to have been slipped through during all the merges. Fixed now :)
> Fix fish shell completion for new default conmon system.slice

- README.md
The badge indicates that something is wrong which isn't
> Remove unused travis build status from README

- contrib/test/integration/build/cri-tools.yml
- contrib/test/integration/golang.yml
- contrib/test/integration/main.yml
> bump go version to build kubernetes

- contrib/test/integration/golang.yml
- go.mod
To avoid inconsistent behavior between go versions we now use go 1.13 per
default.
> Bump go.mod to use go 1.13

- test/image.bats
Add a check that ensures that when we pull an image using a canonical reference to a manifest list, that we correctly retrieve the configuration blob from the runnable image that we pulled.
> image.bats: check start with canonical list reference

- test/image.bats
Add a check that ensures that when we pull an image using a canonical reference to a manifest list, that we correctly retrieve the configuration blob from the runnable image that we pulled.
> [1.16] image.bats: check start with canonical list reference

- server/sandbox_status.go
We already log every request and response via the interceptors,
so there is no need to log it twice.
> Remove double log of PodSandboxStatusResponse

- completions/fish/crio.fish
- docs/crio.8.md
- internal/pkg/criocli/criocli.go
- pkg/config/template.go
conmon 2.0.3 now fully supports the trace log level.
This means that we also should outline that in our documentation since
we're using this level already.
> Mention trace level in documentation

- awesome.md
As the title indicates, we now add both talks hosted on YouTube.
> Add KubeCon NA 2019 talks about CRI-O to awesome list

- pinns/pinns.c
The clang static analyzer complains that the variables
`bind_uts`, `bind_ipc` and `bind_net` may be uninitialized on certain
conditions, which is now fixed.
Reproducible via:
```
> scan-build make
scan-build: Using '/usr/bin/clang-9.0.0' for static analysis
/usr/bin/ccc-analyzer -std=c99 -Os -Wall -Wextra -static   -c -o pinns.o pinns.c
pinns.c:105:7: warning: Branch condition evaluates to a garbage value
if (bind_uts) {
^~~~~~~~
pinns.c:111:7: warning: Branch condition evaluates to a garbage value
if (bind_ipc) {
^~~~~~~~
pinns.c:117:7: warning: Branch condition evaluates to a garbage value
if (bind_net) {
^~~~~~~~
3 warnings generated.
/usr/bin/ccc-analyzer -o ../bin/pinns pinns.o -std=c99 -Os -Wall -Wextra -static
scan-build: 3 bugs found.
scan-build: Run 'scan-view …
```
> Fix possible branch condition evaluates to a garbage value

- contrib/test/integration/build/crun.yml
- contrib/test/integration/build/runc.yml
- contrib/test/integration/main.yml
- test/ctr.bats
> run e2e tests using crun

- version/version.go
This commit bumps the version of 1.13 to 1.13.11. we are dropping the `-dev` suffix like in the newer branches. this will allow for automatic building of packages.
> version 1.13.11

- Makefile
- internal/lib/sandbox/sandbox_test.go
- pkg/config/suite_test.go
- server/sandbox_run_test.go
- server/secrets_test.go
We also remove two flaking unit tests in conjunction with the new test
images (running as root user).
> [1.16] Use vendored go modules when running unit tests

- completions/fish/crio.fish
- docs/crio.8.md
- pkg/config/config.go
In removing the implicit hooks dir, we also don't have any hooks dirs we ship by default. Given we'd like some sane defaults, we should add hooks.DefaultDir in the default config.
> add default hooks dir to crio.conf

- pkg/config/config_test.go
The recent hooks dir change broke the unit tests, which is now fixed.
> Fix unit tests for master branch

- test/network.bats
- test/network_ping.bats
The ping pod tests removed all sandboxes after the test which caused a
race condition in removal of the pod sandbox. Isolating them and
removing only the sandboxes they created should fix that issue.
> [1.16] Deflake network integration tests

- server/container_stats.go
- server/container_stats_list.go
backport PR #2942 to release-1.16
Add disk usage for ListContainerStats
> [1.16]: Add disk usage for ListContainerStats

- completions/fish/crio.fish
- pkg/config/config.go
- pkg/config/config_test.go
In removing the implicit hooks dir, we also don't have any hooks dirs we ship by default. Given we'd like some sane defaults, we should add hooks.DefaultDir in the default config.
(replace: https://github.com/cri-o/cri-o/pull/3011, hopefully fixing the test issues)
> [1.16] add default hooks dir to crio.conf

- internal/lib/container_server.go
this error pops up every once in a while, but without the printed error, we don't actually know what happened. add the error to the logging call so we know what went wrong.
> add error to reservation printed error

- internal/lib/container_server.go
this error pops up every once in a while, but without the printed error, we don't actually know what happened. add the error to the logging call so we know what went wrong.
> [1.16] add error to reservation printed error

- README.md
- tutorials/metrics.md
Add available metrics, their labels and the purpose in a dedicated
document. This documents is now linked in the main README.md as well.
> Add metrics documentation

- internal/lib/container_server.go
- internal/lib/wait.go
- internal/oci/container.go
- internal/oci/memory_store_test.go
- internal/oci/runtime_oci.go
- internal/oci/runtime_vm.go
- server/container_status.go
- server/container_status_test.go
- utils/utils.go
conmon will save the exit file of the container under
/var/lib so it gets persisted and available even on reboot.
Fixes to better handle exit code:
1. Change ExitCode to be a pointer to distinguish from
exit code 0.
2. On reboot if we can't get runc state, then attempt
to read exit code from the persisted exit file.
This handles cases where crio was unable to persist
the state for the container but conmon had written
the exit file for the container.
3. When restoring state during CRI-O startup,
write back the state to disk so that any missed
exit file updates are accounted for.
> [1.16] Persist exit status 

- go.mod
- go.sum
- internal/lib/conmonmon.go
- internal/lib/container_server.go
- internal/oci/oci.go
- internal/oci/runtime_oci.go
- server/container_create.go
- server/container_remove.go
- server/container_start.go
- server/sandbox_remove.go
- server/sandbox_run_linux.go
- server/server.go
- test/conmonmon.bats
- vendor/github.com/containers/psgo/README.md
- vendor/github.com/containers/psgo/internal/process/process.go
- vendor/github.com/containers/psgo/psgo.go
- vendor/modules.txt
One of the many shortcomings of kernel space OOM killing is there isn't very much a process can do to prevent itself from being OOM killed. Even adjusting its score doesn't prevent the kernel from killing it.
Unforuntately for CRI-O, conmon being OOM killed is very bad. A container can be orphaned and left running, with no way to report it state to CRI-O. At worst, it could keep PIDs in CRI-O that really should have gone away.
Introducing conmonmon, a conmon monitor. conmonmon loops in a routine and intermittantly calls `kill 0` on conmon, seeing if its still alive. If it has for some reason been killed, then conmonmon kills its associated container, and sets the container's state as though it OOM'd. This way, we can report to the kubelet that the container OOM'd, even though there is no …
> add conmonmon

- internal/oci/runtime_oci.go
> [1.16] fix concurrent merge compile error

- Makefile
The unit test runs via ginkgo will start downloading the dependencies
when we do not specify `--mod=vendor` which is now the case.
> Use vendored go modules when running unit tests

- contrib/test/integration/build/kubernetes.yml
by removing a hardcoded line to tell the kubelet to not use cri stats if it's using crio
> test: use cri stats instead of cadvisor

- internal/lib/sandbox/namespaces.go
- internal/lib/sandbox/namespaces_test.go
- internal/lib/sandbox/sandbox_test.go
- server/container_create_linux.go
- server/sandbox_run_linux.go
- test/mocks/oci/oci.go
to save on holding the sandbox lock for each namespace, introduce NamespacePaths() to get all namespace paths the sandbox or infra container manage
also share a bit more code between infra and container namespace generation
As well as add unit tests and update some old ones
> managed namespaces: batch infra.State() calls

- tutorials/crictl.md
The linked needs to point to the root of project dir, not
the tutorial dir.
Signed-off-by: yihuaf <fang.yihua.eric@gmail.com>
Fixed a link to CNI setup in `tutorial/crictl.md`
> Fixed cni setup link in crictl.md

- internal/pkg/criocli/criocli.go
- test/helpers.bash
The `--pinns-path` CLI flag was not connected to the `PinnsPath` config variable and so was having no effect.
`make integration` failed due to not being able to find a pinns binary.  This PR provides the path to `./bin/pinns` to the `crio.conf` used in the integration test.
- Fixed the `--pinns-path` CLI flag
- Provided the path to `./bin/pinns` to the integration test.
- Connected `--pinns-path` to `config.PinnsPath`
- added `$PINNS_BINARY_PATH` (defaulted to `$CRIO_PATH/bin/pinns`) to `test/helpers.bash`
- added `--pinns-path "$PINNS_BINARY_PATH"` to the config build line in `test/helpers.bash`
`make integration`
Fix pinns-path CLI flag
> Fix pinns-path CLI flag and pass to integration test

- .golangci.yml
- Makefile
Updating golangci lint to the latest version.
> Bump golangci-lint to v1.22.2

- .circleci/config.yml
- contrib/test/integration/build/conmon.yml
- go.mod
- go.sum
- internal/oci/runtime_oci.go
- scripts/build-test-image
- vendor/github.com/containers/conmon/runner/config/config.go
- vendor/modules.txt
We shouldn't return a custom error when an exec sync command
times out. Instead, we should return a non-zero exit code.
When the prober code in kubernetes sees a custom error
it goes into Unknown status and doesn't restart containers
on timed out probes as expected.
> [1.16] oci: Handle timeouts correctly for probes

- server/sandbox_run_linux.go
The check for `err` instead of `err2` will cause a segmentation fault if
`err2 == nil`.
Reproducible by:
```
> sudo ./bin/crio --cni-config-dir=/empty/path
```
```
> sudo crictl run test/testdata/container_redis.json test/testdata/sandbox_config.json
FATA[0000] Running container failed: run pod sandbox failed: rpc error: code = Unavailable desc = transport is closing
```
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1a1fd17]
goroutine 57 [running]:
github.com/cri-o/cri-o/server.(*Server).runPodSandbox.func8(0xc0006b5f90, 0xc0000e4210, 0x1, 0x1, 0x224be20, 0xc00067a690, 0x0)
/go/src/github.com/cri-o/cri-o/server/sandbox_run_linux.go:431 +0x67 …
```
> Fix possible segmentation fault in error handling

- internal/lib/sandbox/sandbox.go
- server/sandbox_remove.go
- server/sandbox_run_linux.go
- server/sandbox_stop_linux.go
If conmon gets killed either with running or without running CRI-O, then
we have no way to cleanup the shared memory for the pod. This will cause
an unlinkat failure, which is now fixed by removing the SHM before
actually touching the sandbox.
Reproduce via:
```bash
> sudo crictl runp test/testdata/sandbox_config.json
> sudo pkill conmon
> sudo crictl rmp -fa
7e4148565ae9430830515329a0cc3578c55fb041232bda4d77a9b3e11a0580d6
ERRO[0000] removing the pod sandbox "7e4148565ae9430830515329a0cc3578c55fb041232bda4d77a9b3e11a0580d6" failed: \
rpc error: code = Unknown desc = failed to remove pod sandbox 7e4148565ae9430830515329a0cc3578c55fb041232bda4d77a9b3e11a0580d6: \
unlinkat /var/run/containers/storage/overlay-containers/7e4148565ae9430830515329a0cc3578c55fb041232bda4d77a9b3e11a0580d6/userdata/ …
```
> Cleanup sandbox shared memory before removing it

- contrib/test/integration/e2e.yml
This test is failing only on fedora with the following text: 
```
[sig-storage]  CSI Volumes [Driver: csi-hostpath] [Testpattern: Dynamic PV (block  volmode)] volumeMode should create sc, pod, pv, and pvc, read/write to  the pv, and delete all created resources expand_less | 1m5s
-- | --
/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/test/e2e/storage/testsuites/volumemode.go:252 "dd if=/tmp/file1 of=/mnt/volume1 bs=64 count=1" should succeed, but failed with exit code 1 and error message "error running &{/go/src/k8s.io/kubernetes/_output/bin/kubectl [kubectl --server=https://172.18.4.0:6443 --kubeconfig=/var/run/kubernetes/admin.kubeconfig exec --namespace=volumemode-4510 security-context-2b0de23f-3097-11ea-b472-0e349060153d -- /bin/sh -c dd if=/tmp/file1 of=/mnt/volume1 …
```
> [1.14] skip test failing on mount eperm

- server/container_create.go
- server/container_create_linux.go
- server/server.go
If no AppArmor profile is specified, but AppArmor is supported, then we
automatically fallback to `runtime/default`, which is the profile
configured in `crio.conf`.
Beside this we now fail on startup if the profile provided via the
configuration does not exist. This ensures that we can avoid failures
during runtime.
Relates to #3079
> Change AppArmor profile handling to fallback to the default

- internal/lib/sandbox/namespaces.go
Before this patch, if the namespace is closed or not retrievable, then
we still assign `nil` to it. In this case the interface checks for `nil`
will not work any more on removal and will trigger a segmentation fault.
This is now fixed by only touching pointers when necessary. Reproducible
via:
```bash
> sudo ./bin/crio &
> sudo crictl runp test/testdata/sandbox_config.json
> sudo pkill crio
> sudo pkill conmon
> sudo umount /run/crio/ns/*/*
> sudo ./bin/crio &
> sudo crictl rmp -fa
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19840d9]
goroutine 73 [running]:
sync.(*Mutex).Lock(...)
/usr/lib64/go/1.13/src/sync/mutex.go:74
github.com/cri-o/cri-o/internal/lib/sandbox.(*Namespace).Remove(0x0, 0x0, 0x0) …
```
> Fix possible segmentation fault in namespace removal

- server/container_stats.go
- server/container_stats_list.go
backport PR #2942 to release-1.15
Add disk usage for ListContainerStats
> [1.15]: Add disk usage for ListContainerStats

- internal/lib/sandbox/namespaces_linux.go
We already use the dependency for logging interception so we can use it
for namespace path generation as well.
> Use UUID generator for namespace path

- internal/lib/sandbox/namespaces.go
- internal/lib/sandbox/namespaces_linux.go
- internal/lib/sandbox/namespaces_test.go
- server/sandbox_run_linux.go
- test/mocks/sandbox/sandbox.go
We now add an additional abstraction layer on of of available namespace
types by defining a new type `NSType`, which is basically just a string.
This ensures that we (from a programming perspective) only can pass
around the available namespaces defined in `namespaces.go`.
> Add new NSType for available namespaces

- server/container_create_linux.go
when running on a cgroup 2 host, create automatically the cgroupns.
This is being discussed as part of the cgroup v2 support KEP
> server: create cgroupns when running on cgroup v2

- internal/lib/container_server.go
This is a minimal change backported for 1.16 to solve the issues seen in https://github.com/openshift/containernetworking-plugins/pull/15 and https://bugzilla.redhat.com/show_bug.cgi?id=1754154#c11 as discussed here: https://github.com/cri-o/cri-o/pull/3048#pullrequestreview-339880592
#3086 is a more comprehensive solution for future versions
Signed-off-by: Richard Brown rbrownccb@opensuse.org
> [1.16] Don't check for closed namespaces

- tutorials/setup.md
This patch adds:
- Mention about CodeReady Linux Builder for x86_64 repo, required for
glibc-static and device-mapper-devel
- Real examples for subscription-manager (RHEL-8)
- Added make as requirement
- Added example how to install Go programming language tools and libraries (go-toolset)
- Added libassuan-devel as dep. for RHEL8 example (build from source)
- Added command macro for go get go-md2man
Signed-off-by: Douglas Schilling Landgraf <dougsland@gmail.com>
**- What I did**  Improved setup.md
**- How I did it** Testing all changes locally.
**- How to verify it** RHEL-8 Machine
> doc: improve setup.md

- internal/lib/container_server.go
- internal/lib/sandbox/namespaces.go
- internal/lib/sandbox/namespaces_linux.go
we only returned this error if IsNSorError fails, which means the namespace either doesn't exist, or the path is not a namespace.
Both of these errors means the saved spec doesn't accurately describe the pod being created, which is cause for dropping the pod and starting over (a failed restore).
> managed namespaces: remove ErrClosedNS

- server/server.go
If a pod cannot be restored after restart, destroy the
pod network and release the IPs for fututre use
> [1.14] Destroy the pod's network when it can't be restored

- tutorials/setup.md
RHEL-8 beta is outdated. The repo mentioned was last updated
at 15-Nov-2018. Users with RHEL-8 subscription can
have all dependencies installed with no problem.
Signed-off-by: Douglas Schilling Landgraf <dougsland@gmail.com>
**- What I did** Remove old ref. to RHEL-8 beta repo
**- How I did it**  Updating tutorials/setup.md
**- How to verify it**  Double check the last time the repo was updated. Additionally, 8 beta repo is old bits.
> docs: remove mention to RHEL-8 beta repo in setup.md

- server/image_pull.go
- server/metrics/metrics.go
- tutorials/metrics.md
We now add a new set of image pull metrics, which collect the transferred
bytes per image name or digest every second during an image pull. We
also add a metric which collects the skipped bytes if an image has
already been downloaded.
This fixes the ignored command line parameters for the metrics, too.
Example output from the metrics server:
1. Download the image 
1. Remove the image, download it again
1. Download the already existing image 
```bash
container_runtime_crio_image_pulls_by_digest{digest="sha256:2f1a357cf2898f6700b74d933e1784a348df8f719c4db77203423e63b538de9b",mediatype="application/vnd.docker.container.image.v1+json",name="docker.io/nixos/nix",size="5127"} 10254
container_runtime_crio_image_pulls_by_digest{digest="sha256:480223332b134112f7f7f1292789ae19b695c1329a7180200ae8277 …
```
> Extend image pull metrics

- completions/fish/crio.fish
- docs/crio.8.md
- internal/pkg/criocli/criocli.go
This fixes the markdown as well as the man page formatting for the CLI
documentation.
> Fix generated docs formatting

- internal/oci/oci_linux.go
- internal/oci/stats.go
- server/container_stats.go
We should take the `total_inactive_file` into consideration
when providing the `WorkingSetBytes` to align with other
container runtimes.
Closes #3106
> Take total_inactive_file into consideration for memory usage

- .golangci.yml
- Makefile
This also enables two new linters which do not complain out of the box.
> Update golangci-lint to v1.23.1

- pkg/config/config.go
If CRI-O is already listening on a socket, then we should fail to start
the server, which was not the case before this patch.
> Fail to start when already listening on socket

- server/server.go
If the streaming server port is already used then we should fail on
CRI-O startup.
> Fail to start when stream server port already allocated

- pkg/config/config.go
Just a small enhancement to increase the debug capabilities.
> Log path location when using binaries discovered in $PATH

- pkg/config/config_test.go
Running unit tests locally require a valid namespace path as well as pinns which can be faked around.
> Fix unit tests for rootless runs

- docs/crio.8.md
- docs/crio.conf.5.md
- internal/pkg/criocli/criocli.go
- pkg/config/config.go
- pkg/config/reload_test.go
- server/server.go
We already search required runtime dependencies inside paths so the
existence of global `crio.conf` is not necessary in all cases. We will
now not warn any more if the configuration file does not exist on the
system as well as set default the `log_level` to `info` to provide a
better default startup context.
> Allow server to start without config

- go.mod
- go.sum
- vendor/github.com/opencontainers/runtime-tools/generate/generate.go
- vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default.go
- vendor/modules.txt
Fixes clone syscall for s390x
Pulls in https://github.com/opencontainers/runtime-tools/pull/700
Will cherry-pick to 1.17, 1.16, and 1.14
> Vendor in latest opencontainers/runtime-tools

- internal/pkg/criocli/criocli.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/sysctl.go
- pkg/config/sysctl_test.go
- server/sandbox_run_linux.go
- server/utils.go
This fixes the CLI default_sysctl string slice handling and refactors
the validation/parsing of the sysctls in to the config package. We now
pre-check if the sysctls are parsable via the CLI to reduce the error
surface. Unit tests for all parsing and validation cases have been added
as well.
> Refactor sysctl handling and add unit tests

- completions/fish/crio.fish
- internal/lib/container_server.go
- internal/lib/sandbox/sandbox.go
- internal/lib/sandbox/sandbox_test.go
- server/container_create_test.go
- server/sandbox_network.go
- server/sandbox_run_linux.go
- server/sandbox_stop_linux.go
- server/sandbox_stop_test.go
- server/server.go
Move stopNetwork call to earlier in sandbox stop function. This means we unconditionally stop the network.
Add sb.*NetworkStopped functions
Create files in infra's persistent dir to restore {,network}Stopped state
update tests accordingly
> [1.16] fail on network stop

- internal/lib/container_server.go
- internal/lib/wait.go
- internal/oci/container.go
- internal/oci/memory_store_test.go
- internal/oci/runtime_oci.go
- internal/oci/runtime_vm.go
- server/container_status.go
- server/container_status_test.go
- utils/utils.go
conmon will save the exit file of the container under
/var/lib so it gets persisted and available even on reboot.
Fixes to better handle exit code:
Change ExitCode to be a pointer to distinguish from
exit code 0.
On reboot if we can't get runc state, then attempt
to read exit code from the persisted exit file.
This handles cases where crio was unable to persist
the state for the container but conmon had written
the exit file for the container.
When restoring state during CRI-O startup,
write back the state to disk so that any missed
exit file updates are accounted for.
Signed-off-by: Mrunal Patel mrunalp@gmail.com
cherry-pick of #3041
> [1.17] persist exit status

- cmd/crio/config.go
- cmd/crio/main.go
- internal/lib/container_server.go
- internal/lib/container_server_test.go
- internal/lib/suite_test.go
- internal/pkg/criocli/criocli.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/reload.go
- pkg/config/reload_test.go
- server/container_create_linux.go
- server/image_list.go
- server/image_pull.go
- server/image_remove.go
- server/image_status.go
- server/inspect.go
- server/sandbox_run_linux.go
- server/server.go
- server/server_test.go
- server/suite_test.go
- server/useragent/useragent.go
- server/useragent/useragent_test.go
This allows to simplify the configuration reload strategy as well as
updating parts of the system context during live reload. There are now
fewer locations where the context has to be passed around.
> Move SystemContext from Server into Config

- internal/lib/container_server.go
- internal/lib/wait.go
- internal/oci/container.go
- internal/oci/memory_store_test.go
- internal/oci/runtime_oci.go
- internal/oci/runtime_vm.go
- server/container_status.go
- server/container_status_test.go
- utils/utils.go
conmon will save the exit file of the container under
/var/lib so it gets persisted and available even on reboot.
Fixes to better handle exit code:
Change ExitCode to be a pointer to distinguish from
exit code 0.
On reboot if we can't get runc state, then attempt
to read exit code from the persisted exit file.
This handles cases where crio was unable to persist
the state for the container but conmon had written
the exit file for the container.
When restoring state during CRI-O startup,
write back the state to disk so that any missed
exit file updates are accounted for.
Signed-off-by: Mrunal Patel mrunalp@gmail.com
cherry-pick of https://github.com/cri-o/cri-o/pull/3041
> persist exit status

- server/container_create.go
- server/sandbox_run_linux.go
- server/server.go
We reverted two commits thinking it was causing a regression, but it prove to not be the cause.
So reverting the revert now.
> [1.17] Add the context and network destroy commits back in

- Makefile
Currently, make install is not installing systemd files and configs.
Based on that, the environment is incomplete when building and
installing the project manually.
Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>
**- What I did**: Improved Makefile
**- How I did it**: Changing the install target from Makefile
**- How to verify it**: make && make install (Now I see config and systemd files in the env)
> build: make install providing systemd and config

- docs/crio.8.md
- docs/crio.conf.5.md
- internal/pkg/criocli/criocli.go
- pkg/config/config.go
- pkg/config/reload_test.go
- server/server.go
We already search required runtime dependencies inside paths so the
existence of global `crio.conf` is not necessary in all cases. We will
now not warn any more if the configuration file does not exist on the
system as well as set default the `log_level` to `info` to provide a
better default startup context.
> [1.17] Allow server to start without config

- internal/lib/container_server.go
- internal/lib/sandbox/namespaces.go
- internal/lib/sandbox/namespaces_test.go
- internal/lib/sandbox/sandbox.go
- internal/lib/sandbox/sandbox_test.go
- server/container_create_test.go
- server/sandbox_network.go
- server/sandbox_run_linux.go
- server/sandbox_stop_linux.go
- server/sandbox_stop_test.go
- server/server.go
Move stopNetwork call to earlier in sandbox stop function. This means we unconditionally stop the network.
Add sb.*NetworkStopped functions
Create files in infra's persistent dir to restore {,network}Stopped state
update tests accordingly
cherry-pick-of: #3127 
> [1.17] fail on network stop

- server/sandbox_run_linux.go
skip the memory check if the value is set to the string "max".  That
is used on cgroup v2 when no limits are present.
> sandbox: skip memory check if set to "max"

- server/container_create.go
- server/container_remove.go
- server/container_start.go
- server/container_stop.go
- server/sandbox_run_linux.go
- server/sandbox_stop_linux.go
of "removed".
Will cherry-pick into the release branches.
> Add the container IDs that cri-o assigns to various logs

- completions/fish/crio.fish
- docs/crio.8.md
- docs/crio.conf.5.md
- pkg/config/config_unix.go
move default version file location to /var/run/crio/version instead of /var/lib/crio/version
as we should really wipe crio after every reboot, so let's put it on a tmpfs
> config: move default version file location to tmpfs

- tutorials/setup.md
This patch improve the following in setup.md:
- Do not set btrfs-progs-devel package as required
package for installation.
- For Fedora/CentOS steps: add make as requirement.
- Add to RHEL8 steps: pkgconf-pkg-config package
(replacement for pkgconfig).
- Add a note about btrfs-progs-devel and pkgconfig
replacement.
Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>
**- What I did** Improved setup.md
**- How I did it** Testing in local machines, based on the info provided in #3130
**- How to verify it** RHEL8 and Fedora
> docs: improve setup.md

- pkg/config/config_test.go
by changing expected log level
> [1.17] fix unit tests

- Makefile
We also print out the enabled/disabled linters as well as the version
for CI debugging purposes.
> Update golangci-lint to v1.23.3

- internal/lib/container_server.go
- internal/lib/sandbox/namespaces.go
- internal/lib/sandbox/namespaces_test.go
- internal/lib/sandbox/sandbox.go
- internal/lib/sandbox/sandbox_test.go
- server/container_create_test.go
- server/sandbox_network.go
- server/sandbox_run_linux.go
- server/sandbox_stop_linux.go
- server/sandbox_stop_test.go
- server/server.go
Move stopNetwork call to earlier in sandbox stop function. This means we unconditionally stop the network.
Add sb.*NetworkStopped functions
Create files in infra's persistent dir to restore {,network}Stopped state
update tests accordingly
cherry-pick-of: #3127
> fail on network stop

- completions/fish/crio.fish
- docs/crio.8.md
- docs/crio.conf.5.md
- pkg/config/config_unix.go
as we should really wipe crio after every reboot, so let's put it on a tmpfs
> [1.17] move default version file location a tmpfs

- server/container_create.go
- server/container_remove.go
- server/container_start.go
- server/container_stop.go
- server/sandbox_run_linux.go
- server/sandbox_stop_linux.go
of "removed".
cherry-pick of https://github.com/cri-o/cri-o/pull/3185
> [1.16] Add the container IDs that cri-o assigns to various logs

- Makefile
- cmd/crio/main.go
- cmd/crio/version.go
- completions/bash/crio
- completions/fish/crio.fish
- completions/zsh/_crio
- docs/crio.8.md
- internal/version/version.go
- test/version.bats
This adds the ability to display detailed version information about CRI-O.
Demo:
```
> ./bin/crio version
GitVersion:    1.17.0-dev
GitCommit:     ca6e4a06c2d2ce4d583df6190666276837a9052b
GitTreeState:  dirty
BuildDate:     2020-02-04T08:53:50Z
GoVersion:     go1.13.7
Compiler:      gc
Platform:      linux/amd64
```
```
> ./bin/crio version -h
NAME:
crio version - display detailed version information
USAGE:
crio version [command options] [arguments...]
OPTIONS:
--json, -j  print JSON instead of text (default: false)
--help, -h  show help (default: false)
```
```
> ./bin/crio version -j
{
"gitCommit": "ca6e4a06c2d2ce4d583df6190666276837a9052b",
"gitTreeState": "dirty",
"buildDate": "2020-02-04T08:53:50Z",
"goVersion": "go1.13.7",
"compiler": "gc",
"platform": "linux/amd64"
}
```
> Add `crio version` subcommand

- server/container_create.go
- server/container_remove.go
- server/container_start.go
- server/container_stop.go
- server/sandbox_run_linux.go
- server/sandbox_stop_linux.go
of "removed".
cherry-pick of https://github.com/cri-o/cri-o/pull/3185
> [1.17] Add the container IDs that cri-o assigns to various logs

- server/label_linux.go
- server/sandbox_run_linux.go
- server/secrets.go
label.Relabel() can now return wrapped errors, so unwrap them before comparing them to ENOTSUP.  Add a similar check in the path that handles setting up secrets.  Spurred by discussion in https://github.com/cri-o/cri-o/pull/3202#discussion_r375264784.
> Unwrap errors from label.Relabel() before checking for ENOTSUP

- internal/lib/container_server.go
- internal/lib/sandbox/sandbox.go
- internal/oci/container.go
- server/container_create.go
- server/container_create_generic.go
- server/container_create_linux.go
- server/sandbox_list.go
- server/sandbox_list_test.go
- server/sandbox_remove.go
- server/sandbox_run_linux.go
- server/sandbox_status.go
- server/sandbox_stop_linux.go
This reverts commit 1d7d97192c031f02c05a025de80ac319c070f987.
This revert is needed because 1.17 is not ready to remove infra containers, and this  code is incomplete (the Ready() check wasn't correct). as such, revert it until we actually drop the infra container
> [1.17] Revert "infra: remove unneeded uses of infra container"

- completions/fish/crio.fish
- docs/crio.8.md
- internal/pkg/criocli/criocli.go
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/template.go
If a specified or the default hooks directory is not available, then we
warn the user but do not fail any more.
Fixes: #3179
> Skip invalid hooks directories by default

- internal/pkg/storage/image.go
If we reload via SIGHUP, then the systemContext may get populated with new
unqualified search registries. We have to check those in every pull
operation, because otherwise the update of the unqualified search
registries would have no effect.
```
unqualified-search-registries = ["docker.io"]
```
> Fix reload behavior for unqualified search registries

- docs/crio.conf.5.md
as we don't support setting that option in the crio.conf anymore
> drop host_ip from crio.conf.5.md

- go.mod
- go.sum
- vendor/github.com/opencontainers/runtime-tools/generate/generate.go
- vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default.go
- vendor/modules.txt
Pulls in the fix that adds the missing clone
masked_eq seccomp rule which causes clone syscalls
to fail on s390x - opencontainers/runtime-tools#700
> [1.16] Vendor latest opencontainers/runtime-tools

- go.mod
- go.sum
- test/image.bats
- vendor/github.com/containers/image/v5/docker/docker_client.go
- vendor/github.com/containers/image/v5/docker/docker_image_dest.go
- vendor/github.com/containers/image/v5/docker/docker_image_src.go
- vendor/github.com/containers/image/v5/docker/tarfile/dest.go
- vendor/github.com/containers/image/v5/docker/tarfile/src.go
- vendor/github.com/containers/image/v5/image/docker_schema2.go
- vendor/github.com/containers/image/v5/image/oci.go
- vendor/github.com/containers/image/v5/internal/iolimits/iolimits.go
- vendor/github.com/containers/image/v5/openshift/openshift.go
- vendor/modules.txt
Same dance as for the 1.16 and 1.17 branches:
Bumping it directly to v5.2.0 was my preferred approach but this is obviously rejected by the CI.
I create a v5.1-stable branch in c/image and cherry-picked the fixes which are now vendored by commit.
> [1.14] update github.com/containers/image

- vendor/github.com/containers/image/docker/docker_client.go
- vendor/github.com/containers/image/docker/docker_image_dest.go
- vendor/github.com/containers/image/docker/docker_image_src.go
- vendor/github.com/containers/image/docker/tarfile/dest.go
- vendor/github.com/containers/image/docker/tarfile/src.go
- vendor/github.com/containers/image/image/docker_schema2.go
- vendor/github.com/containers/image/image/oci.go
- vendor/github.com/containers/image/internal/iolimits/iolimits.go
- vendor/github.com/containers/image/openshift/openshift.go
> [1.13] update github.com/containers/image

- server/container_create.go
- server/container_remove.go
- server/container_start.go
- server/container_stop.go
- server/sandbox_run_linux.go
- server/sandbox_stop_linux.go
of "removed".
Cherry pick of https://github.com/cri-o/cri-o/pull/3185
> [1.14] Add the container IDs that cri-o assigns to various logs

- cmd/crio/wipe.go
- go.sum
- internal/lib/container_server.go
- internal/lib/container_server_test.go
- internal/pkg/storage/utils.go
- server/container_create_linux.go
- server/sandbox_run_linux.go
- server/server.go
- server/server_test.go
The previous behavior was that CRI-O forcely tried to remove running
podman containers on startup, which only succeeded for the container
storage but not the running process. The result was was a running
container process in podman, which got broken because its storage got
removed.
This is now fixed by excluding podman containers on restore, discovered
by the new podman annotation.
A dedicated unit test has been added as well.
> [1.17] Fix server restore to not remove podman containers

- .circleci/config.yml
- go.mod
- go.sum
- internal/oci/runtime_oci.go
- scripts/build-test-image
- vendor/github.com/containers/conmon/runner/config/config.go
- vendor/modules.txt
oci: Handle timeouts correctly for probes
We shouldn't return a custom error when an exec sync command
times out. Instead, we should return a non-zero exit code.
When the prober code in kubernetes sees a custom error
it goes into Unknown status and doesn't restart containers
on timed out probes as expected.
cherry-pick of https://github.com/cri-o/cri-o/pull/3065
> [1.17] oci: handle timeouts correctly for probes

- internal/oci/runtime_oci.go
We shouldn't return a custom error when an exec sync command
times out. Instead, we should return a non-zero exit code.
When the probe code in kubernetes sees a custom error
it goes into Unknown status and doesn't restart containers
on timed out probes as expected.
> oci: Handle timeouts correctly for probes

- server/container_create.go
- server/container_remove.go
- server/container_start.go
- server/container_stop.go
- server/sandbox_run_linux.go
- server/sandbox_stop_linux.go
of "removed".
cherry-pick of https://github.com/cri-o/cri-o/pull/3185
> [1.13] Add the container IDs that cri-o assigns to various logs

- vendor.conf
- vendor/github.com/opencontainers/runtime-spec/README.md
- vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
- vendor/github.com/opencontainers/runtime-tools/README.md
- vendor/github.com/opencontainers/runtime-tools/generate/config.go
- vendor/github.com/opencontainers/runtime-tools/generate/generate.go
- vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default.go
- vendor/github.com/opencontainers/runtime-tools/validate/validate_linux.go
Pulls in the fix that adds the missing clone
masked_eq seccomp rule which causes clone syscalls
to fail on s390x - opencontainers/runtime-tools#700
Vendor in a newer version of opencontainers/runtime-specs
as well as some chnages in runtime-tools depends on it
> [1.13] Vendor latest opencontainers/runtime-tools

- go.mod
- go.sum
- vendor/github.com/opencontainers/runtime-tools/generate/generate.go
- vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default.go
- vendor/modules.txt
Pulls in the fix that adds the missing clone
masked_eq seccomp rule which causes clone syscalls
to fail on s390x - https://github.com/opencontainers/runtime-tools/pull/700
> [1.14] Vendor latest opencontainers/runtime-tools

- server/container_stats.go
- server/container_stats_list.go
This adds the logging context to the container stats function to provide
more detailed request tracing.
> Add log context to container stats

- pkg/config/template.go
Just a cosmetic adaption to remove the trailing whitespace from the
config template.
> Remove trailing whitespaces from configuration template

- cmd/crio/config.go
- cmd/crio/main.go
- cmd/crio/wipe.go
- internal/pkg/criocli/criocli.go
- pkg/config/config.go
- pkg/config/reload.go
- pkg/config/reload_test.go
- server/server.go
- server/server_test.go
- server/suite_test.go
We now store the config dir and path locations directly at the `Config`
structure, which allows us to use that information on SIGHUP reload to
check both locations for possible new configuration files.
> Make SIGHUP reload for drop-in config dir work

- .circleci/config.yml
- Makefile
- bundle/Makefile
- bundle/build
- nix/default.nix
- nix/nixpkgs.nix
The upstream nix package has been merged and we can now remove our
custom derivation from `nix/default.nix`.
> Update nix package dependencies and cleanup default.nix

- internal/oci/container.go
- internal/oci/container_test.go
- internal/oci/kill.go
- internal/oci/runtime_oci.go
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1800107
> Pass down the integer value of the stop signal

- internal/oci/container.go
- internal/oci/container_test.go
- internal/oci/kill.go
- internal/oci/runtime_oci.go
Cherry pick of https://github.com/cri-o/cri-o/pull/3249
> [1.16] Pass down the integer value of the stop signal

- cmd/crio/main.go
- go.mod
fixes: https://github.com/cri-o/cri-o/issues/1879
> klog: don't write to /tmp

- oci/container.go
- oci/container_test.go
- oci/kill.go
- oci/runtime_oci.go
> [1.15] Pass down the integer value of the stop signal

- lib/kill.go
- oci/container.go
> [1.13] Pass down the integer value of the stop signal

- oci/container.go
- oci/container_test.go
- oci/kill.go
- oci/runtime_oci.go
> [1.14] Pass down the integer value of the stop signal

- internal/lib/conmonmon.go
when conmonmon decides a conmon is gone, and its container should have oom kill spoofed, that's a big deal.
As an admin, we'd typically want that feedback.
Error is a standard value for log level, so this message is more likely to show up. Error is more representative of the severity of the situation
> conmonmon: errorf when OOM killing

- pinns/Makefile
- pinns/pinns.c
- pinns/utils.h
Just a couple of enhancements to pinns:
- Strip the binary to reduce its size
- Make `bind_ns()` static to scope to single object
- Print a `:` separator on logging errno
> Update pinns build and add small cleanups

- lib/container_server.go
> [1.14] Restore sandbox selinux labels directly from config.json

- oci/runtime_oci.go
- server/container_portforward.go
> [1.15] port forward: drain the stream on error

- completions/fish/crio.fish
- docs/crio.8.md
- docs/crio.conf.5.md
- internal/oci/oci.go
- internal/pkg/criocli/criocli.go
- pkg/config/config.go
- pkg/config/template.go
We now mention in the documentation that the lowest possible value for
the ctr_stop_timeout is 30seconds. We also move the validation of this
fact into the config validation part of the library.
> Add user-notice about minimal ctr_stop_timeout

- pkg/config/config.go
- pkg/config/reload.go
- pkg/config/template.go
- server/image_pull.go
- server/server.go
- server/utils.go
- server/utils_test.go
- test/reload_config.bats
This adds the live configuration reload feature to the
`decryption_keys_path`. We still check per-pull if the path exists and
decide if the key should be loaded or not.
> Add live reload to DecryptionKeysPath

- vendor.conf
- vendor/github.com/containers/image/docker/docker_client.go
- vendor/github.com/containers/image/docker/docker_image_dest.go
- vendor/github.com/containers/image/docker/docker_image_src.go
- vendor/github.com/containers/image/docker/tarfile/dest.go
- vendor/github.com/containers/image/docker/tarfile/src.go
- vendor/github.com/containers/image/image/docker_schema2.go
- vendor/github.com/containers/image/image/oci.go
- vendor/github.com/containers/image/internal/iolimits/iolimits.go
- vendor/github.com/containers/image/openshift/openshift.go
Pulls in fixes for CVE-2020-1702 from the new cri-o-release-1.11 branch
from containers/image.
Fixes: CVE-2020-1702
> [1.11] update containers/image

- internal/pkg/log/hook_filter.go
- internal/pkg/log/hook_filter_test.go
- test/helpers.bash
Just for sake of the general beautifulness of our logs, we now uppercase the
first character of them:
```
DEBU[…] Using runtime executable from …
DEBU[…] Found valid runtime "runc" for…
DEBU[…] Using  hooks directory: /usr/s…
DEBU[…] Using conmon from $PATH: /usr/…
DEBU[…] Using pinns from $PATH: /usr/b…
DEBU[…] Cached value indicated that ov…
DEBU[…] Cached value indicated that me…
DEBU[…] Cached value indicated that na…
DEBU[…] BackingFs=btrfs, projectQuotaS…
INFO[…] [graphdriver] using prior stor…
DEBU[…] Reading hooks from /usr/share/…
INFO[…] Found CNI network crio-bridge …
INFO[…] Found CNI network podman (type…
INFO[…] Update default CNI network nam…
INFO[…] No seccomp profile specified, …
INFO[…] Installing default apparmor pr…
DEBU[…] Golang's threads limit set to …
INFO[…] Got …
```
> Uppercase first log char per default

- server/container_create_linux.go
give privileged containers a full view on the cgroups.  This reflects
the current status of the cgroupv2 KEP.
> server, cgroupv2: do not create cgroupns

- .clang-format
- pinns/pinns.c
This adds the ablity to unshare a cgroup namespace via pinns. We also
update the .clang-format file to enable proper auto-formatting.
> Add cgroup namespace unsharing to pinns

- pkg/config/config.go
- pkg/config/reload.go
- pkg/config/reload_test.go
- pkg/config/seccomp/seccomp.go
- pkg/config/seccomp/seccomp_test.go
- pkg/config/seccomp/suite_test.go
- pkg/config/template.go
- server/container_create.go
- server/sandbox_run_linux.go
- server/server.go
- server/server_test.go
- test/docs-validation/main.go
- test/reload_config.bats
The seccomp profile is now processed in a dedicated sub-package of the
`config` package and supports the live config reload feature. Necessary
test have been added as well.
> Add live configuration reload to seccomp profile

- .circleci/config.yml
- Makefile
- cmd/crio/main.go
- internal/oci/runtime_vm.go
- scripts/build-test-image
- scripts/circle-setup
- scripts/versions
- tutorials/setup.md
To be able to update Kubernetes to the latest release we have to drop
support for go 1.10 and agreed on supporting down to golang v1.12.x.
Needed for https://github.com/cri-o/cri-o/pull/3280
> Drop support for golang < v1.12

- pkg/config/config.go
We do not set default struct values any more and focus only on the
actual differences in `DefaultConfig()` to reduce the noise. Unnecessary
const values have been merged into that function as well.
> Cleanup config default values

- Makefile
We have to make the `bin/pinns` target `PHONY` to have a rebuild based
on file system changes (via `pinns/Makefile`), otherwise we would omit
the "file changed check" inside the `pinns` directory.
> Make bin/pinns a PHONY target

- Makefile
We only support go > 1.12 which means that we do not have to work around
go modules any more.
> Remove extra check for go modules in Makefile

- Makefile
- cmd/crio-status/main.go
- cmd/crio/main.go
- internal/version/version.go
- internal/version/version_test.go
- server/useragent/useragent.go
- server/version.go
We now make the unnecessary public variables `version.GitCommit` and
`version.Version` private again.
The output of `crio -v` and the `VERSION` section of `crio -h` now show
the full version details, equally to `crio version`.
We can use the newly introduced `version.Get()` API to retrieve the
version information, for example in `useragent.go` and
`server/version.go`.
Refers to https://github.com/cri-o/cri-o/issues/2979
> Improve crio --version / version output

- Makefile
This is not optimal, because it takes every *.go file into account. But
before this patch a binary, like `bin/crio` has not been re-build if any
dependent *.go file changed.
> Rebuild bin/* targets on *.go file changes

- internal/config/apparmor/apparmor.go
- internal/config/apparmor/apparmor_test.go
- internal/config/apparmor/suite_test.go
- pkg/config/config.go
- pkg/config/reload.go
- pkg/config/reload_test.go
- pkg/config/template.go
- server/container_create.go
- server/container_create_linux.go
- server/server.go
- test/reload_config.bats
The apparmor profile is now processed in a dedicated sub-package of the
`config` package and supports the live config reload feature. Necessary
test have been added as well.
> Add live configuration reload to AppArmor profile

- .github/PULL_REQUEST_TEMPLATE.md
We could generate the release notes (automatically via [the release notes generator](https://github.com/kubernetes/release/tree/master/cmd/release-notes)) from the PR’s as well as applying proper labels via the kinds.
What do you think? This would also mean that we have to follow the PR template, but I'm not sure if we already have the plugins (like for the kinds) in flight.
None
None
```release-note
None
```
> Apply Kubernetes PR template

- bundle/Makefile
- bundle/build
- completions/fish/crio.fish
- docs/crio-status.8.md
- docs/crio.8.md
- docs/crio.conf.5.md
- docs/crio.conf.d.5.md
- internal/pkg/criocli/criocli.go
- internal/pkg/criocli/documentation.go
This adds a small man page about the usage of the configuration directory `crio.conf.d`
None
```release-note
Added man page for crio.conf.d(5)
```
> man page for crio.conf.d

- contrib/test/integration/e2e.yml
/kind cleanup
Skip failing upstream storage test
The root cause hasn't been completely found, but the offending PR was the introduction of this test: https://github.com/kubernetes/kubernetes/commit/1f9f2390cb57832f5fbd02e53d39023b81500cc2
It fails for the same reason we skip the other Dynamic PV (block volmode) test. For some reason, loop back files on fedora hosts have different permissions than rhel (and whatever upstream kube is testing with). This difference in permissions causes a failure when trying to read a device backed with a loopback. Further investigation needs to happen, but for now we can disable the test to get CI moving
None
None
None
```release-note
```
> skip failing storage test

- Makefile
/kind feature
This allows user to easily inject the `criocli.DefaultsPath` variable
via `make DEFAULTS_PATH=<PATH>`. 
Fixes #2979
None
```release-note
- Provide the possibility to set the default config path via `make DEFAULTS_PATH=<PATH>`
```
> Add DEFAULTS_PATH to Makefile

- contrib/test/integration/build/crun.yml
- contrib/test/integration/build/runc.yml
- server/container_create_linux.go
- test/pod.bats
- test/testdata/container_config_sleep.json
Enable passing of kubernetes termination grace period
down to OCI runtime, as an annotation for systemd.
This builds on top of
* https://github.com/opencontainers/runc/pull/2224   (or https://github.com/containers/crun/pull/266)
and is part of the fix for
* https://github.com/kubernetes/kubernetes/issues/77873
Replaces: #3317
1. Install runc from latest git.
2. Compile cri-o with this patch, run it.
3. Run kubernetes so it uses the cri-o daemon compiled above.
4. Add the following into kubernetes pod yaml:
```yaml
apiVersion: v1
kind: Pod
....
spec:
terminationGracePeriodSeconds: 111
....
```
5. Apply the above pod, wait for container(s) to start.
6. Find out any container id from the above pod (field `Container ID` from `kubectl describe pod ...` output, with `cri-o://` suffix removed). …
> CreateContainer: pass TerminationGracePeriod

- contrib/test/integration/golang.yml
- server/container_create.go
- server/sandbox_run_linux.go
/kind bug
The issue seems to be that the kubelet times out on the create request but crio doesn't error out when kubelet client times out. So, we end up with the pod being created and then kubelet keeps on trying to create the pod again and it can't since the name is reserved.
With the change, we error out on timeouts so the pod creation fails and the name is unreserved so later attempts by the kubelet to create a pod or container may succeed.
We may want to add more of these checks around long running operations rather than just at the end in follow-ups.
Possible fix for https://github.com/cri-o/cri-o/issues/2984
Taking over https://github.com/cri-o/cri-o/pull/3102
No
```release-note
```
> [1.16] Check for context erroring before returning from longer requests

- test/conmonmon.bats
I ran tests on my laptop and saw this:
> ok 12 conmonmon cleans up running conmon # skip conmon pid found empty; probably kata containers
Looking into it, I found out that `ps -eo "%p %a"` formats its output
into columns, and the PID column is right-aligned, e.g.
```
100763 /usr/local/bin/conmon <....>
```
(note the extra space before the PID). This results in `cut -d' ' -f1`
printing nothing instead of a PID.
Replacing `cut` with `awk '{print $1}'` would solve the issue, but
it will be even better to use `pgrep` which allows to filter by command
name and does not do fancy whitespace formatting. It can also filter by
the complete command line, making other greps and cuts redundant.
Tested with pgrep from procps-ng-3.3.15, as well as busybox-1.30.1.
Fixes: ec3187b3e
/kind bug …
> test/conmonmon: fix getting conmon pid

- cmd/crio/main.go
- go.mod
- go.sum
- vendor/k8s.io/klog/.travis.yml
- vendor/k8s.io/klog/README.md
- vendor/k8s.io/klog/go.mod
- vendor/k8s.io/klog/go.sum
- vendor/k8s.io/klog/klog.go
- vendor/modules.txt
> [1.15] klog: don't write to /tmp

- cmd/crio/main.go
- go.mod
> [1.16] klog: don't write to /tmp

- contrib/test/integration/golang.yml
- internal/oci/runtime_oci.go
- server/container_portforward.go
> [1.16] port forward: drain the stream on error

- cmd/crio/main.go
- go.mod
- vendor/modules.txt
> [1.14] klog: don't write to /tmp

- .circleci/config.yml
- Makefile
- bundle/Makefile
- bundle/build
- bundle/test
- contrib/cni/README.md
- contrib/test/integration/build/cri-o.yml
- contrib/test/integration/e2e-base.yml
- test/helpers.bash
- tutorials/decryption.md
- tutorials/kubeadm.md
- tutorials/metrics.md
- tutorials/setup.md
/kind cleanup
This updates the Makefile targets for the general builds and the bundle
to use the net `crio.conf.d` configuration directory. The documentation
has been adapted as well as the tests.
None
None
```release-note
None
```
> Update Makefile targets and docs to crio.conf.d

- Dockerfile
- contrib/test/integration/build/conmon.yml
- go.mod
- go.sum
- vendor/github.com/containers/conmon/runner/config/config.go
- vendor/modules.txt
/kind cleanup
bumps conmon to 2.0.11
Not only do we want to test against the latest and greatest, conmon 2.0.11 also reduces the chance of incorrectly reporting a container OOM, and also is protected against conmon OOMs. This prevents then need for conmonmon and other tools to protect this branch from incorrect OOM reporting
```release-note
NONE
```
> [1.14] conmon: bump to 2.0.11

- internal/log/interceptors.go
- internal/log/log.go
- internal/log/log_test.go
- server/image_status.go
/kind feature
Beside the unique ID we now add the full gRPC method name to the logs,
which allow better traceability and removes the necessity to prefix the
logs with hard-coded method names.
None
We now have an additional `name` field ad the end of the logs:
```
DEBU[2020-03-10 10:59:23.041438456+01:00] Response: &ListContainersResponse{Containers:[]*Container{},}  file="go-grpc-middleware/chain.go:25" id=420e073d-2d14-4126-a6d7-d3a79db698a1 name=/runtime.v1alpha2.RuntimeService/ListContainers
DEBU[2020-03-10 10:59:50.426689794+01:00] Request: &ListImagesRequest{Filter:&ImageFilter{Image:&ImageSpec{Image:,},},}  file="go-grpc-middleware/chain.go:25" id=5b73c5ba-0b32-47b6-bc44-456c7005e233 name=/runtime.v1alpha2.ImageService/ListImages
```
```release-note
- Added gRPC method names to log …
```
> Add gRPC method name to logs

- README.md
- bundle/test
- contrib/test/integration/build/cri-o.yml
- contrib/test/integration/vars.yml
- internal/oci/oci_linux.go
- test/cgroups.bats
- test/helpers.bash
- test/pod.bats
- test/testdata/sandbox1_config.json
- test/testdata/sandbox2_config.json
- test/testdata/sandbox3_config.json
- test/testdata/sandbox_config.json
- test/testdata/sandbox_config_apparmor.json
- test/testdata/sandbox_config_hostnet.json
- test/testdata/sandbox_config_hostport.json
- test/testdata/sandbox_config_privileged.json
- test/testdata/sandbox_config_seccomp.json
- test/testdata/sandbox_config_selinux.json
- test/testdata/sandbox_config_sysctl.json
- test/testdata/sandbox_pidnamespacemode_config.json
- test/testdata/template_sandbox_config.json
Considering it's the default and has been for a while
closes the open portion of https://github.com/cri-o/cri-o/issues/3301
Also fix a bug where using systemd as a cgroup_manager would cause stats to return nothing
> integration tests: switch to systemd cgroups

- Makefile
The release version for which are the notes generated an be part of the
output markdown document.
None
None
```release-note
None
```
> Add target release version to generated notes

- pkg/container/container.go
- pkg/container/container_test.go
- pkg/container/suite_test.go
- server/container_create.go
/kind cleanup
This commit adds a configuration setter and getter to the new
`Container` interface, which can be used as a base for further
refactorings. The container creation RPC now uses the new interface to
validate and retrieve the config. Unit tests have been added as well.
None
/cc @rhafer 
```release-note
None
```
> Add container config (set/get) to Container interface

- README.md
/kind bug
Starting cri-o is required for running kubernetes with cri-o. Otherwise you would see:
```
W0318 08:26:30.130587   36467 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {/var/run/crio/crio.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/run/crio/crio.sock: connect: no such file or directory". Reconnecting...
```
None
```release-note
```
> Mention starting cri-o for running with kubernetes

- internal/oci/runtime_oci.go
- utils/utils.go
- utils/utils_test.go
/kind cleanup
We only use standard streams so we can fallback to the `utils.ExecCmd`
function. Beside that, we printed results of lower level runtimes (like
runc) directly to stdout/err which is annoying when triaging the CRI-O logs.
None
None
```release-note
- Removed annoying logs coming directly from lower level runtimes like runc
```
> Remove utils.ExecCmdWithStdStreams in favor of utils.ExecCmd

- Makefile
- pkg/sandbox/sandbox.go
- pkg/sandbox/sandbox_test.go
- pkg/sandbox/suite_test.go
- server/sandbox_run_linux.go
/kind cleanup
Similar to what was done for the "Container" interface in PR #3387 this adds set/get methods for the sandbox config to the new "Sandbox" interface. It is used by the RunPodSandbox rpc to
validate and retrieve the configuration.
None
//cc @saschagrunert 
```release-note
None
```
> Add PodSandboxConfig (get/set) to Sandbox interface 

- server/container_create_linux.go
/kind cleanup
The `LogPath` inside the container config should be mostly relative
according to:
https://github.com/kubernetes/kubernetes/blob/84dc7046797aad80f258b6740a98e79199c8bb4d/pkg/kubelet/kuberuntime/helpers.go#L167-L170
This means we can remove the annoying warning for every container and
just fallback to a default log path if empty.
None
None
```release-note
- Removed warning about non-absolute container log paths when creating a container
```
> Simplify container log path handling

- test/testdata/container_config.json
- test/testdata/container_config_by_imageid.json
- test/testdata/container_config_hostport.json
- test/testdata/container_config_logging.json
- test/testdata/container_config_privileged.json
- test/testdata/container_config_resolvconf.json
- test/testdata/container_config_seccomp.json
- test/testdata/container_config_sleep.json
- test/testdata/container_exit_test.json
- test/testdata/container_redis.json
- test/testdata/container_redis_apparmor.json
- test/testdata/container_redis_default_mounts.json
- test/testdata/container_redis_device.json
- test/testdata/container_redis_env_custom.json
- test/testdata/container_redis_namespace.json
- test/testdata/container_sleep.json
- test/testdata/template_container_config.json
/kind cleanup
fixes up the integration tests by correctly putting readonly_rootfs and privileged bools in correct place (As well as dropping privilege where it's clearly not needed)
(carrying https://github.com/cri-o/cri-o/pull/2992)
```release-note
None
```
> test: move readonly_rootfs and privileged to correct place

- server/container_stats.go
- server/container_stats_list.go
/kind bug
prevents a segfault from accessing a nil sandbox
segfault found here: https://storage.googleapis.com/origin-federated-results/pr-logs/pull/cri-o_cri-o/3409/test_pull_request_crio_e2e_rhel/11062/artifacts/journals/crio.service
```release-note
none
```
> stats: prevent a segfault

- .circleci/config.yml
/kind bug
The container executor was hit by OOM kills because golangci-lint uses a
tremendous amount of memory. We now switch back to the machine executor
to have better memory constraints.
None
None
```release-note
None
```
> Switch back to machine executor for CI lint stage

- server/image_pull.go
- server/server.go
To suit the needs of OpenShift CI [1], we need to avoid parallel pulls.
While we have an open PR against containers/image [2] to detect parallel
copy operations across processes, we are still far from getting this
merged; it must be split into smaller chunks and we plan to tackle it in
the next few months but who knows how long this might take.
To support that in CRI-O, however, we enjoy the benefit of running a
daemon where we can easily avoid redundantly pulling the same image in
parallel as we're in the same process space and can do all
synchronisation in memory.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1785390
[2] https://github.com/containers/image/pull/611
> avoid parallel pulls of the same image

- server/container_attach.go
- server/container_exec.go
- server/container_execsync.go
- server/container_remove.go
- server/container_start.go
- server/container_status.go
- server/container_stop.go
- server/sandbox_status.go
/kind cleanup
Returns grpc code NotFound when we can't find a container or a pod.
This will help the kubelet as it will be able to distinguish from other errors.
We want to make use of other grpc codes as well but this is a first step.
No.
```release-note
Return grpc code NotFound when we can't find a container or pod
```
> server: Return grpc code NotFound when we can't find a container or pod

- Dockerfile
- contrib/test/integration/build/conmon.yml
bumps conmon to 2.0.12, which is more strict about when conmon reports a container OOM.
https://bugzilla.redhat.com/show_bug.cgi?id=1801568
```release-note
none
```
> [1.13] bump conmon to 2.0.12

- internal/oci/runtime_oci.go
- server/container_portforward.go
> [1.17] port forward: drain the stream on error

- scripts/release-branch-forward/release-branch-forward.go
/kind design
Add a first golang based script for release branch automation.
None
Maybe we can try the tool manually in the first place to see if it fits our requirements. 
/cc @haircommander @mrunalp 
```release-note
None
```
> Add release-branch-forward script

- scripts/release-notes/release_notes.go
/kind bug
We do not have to prefix an `origin/` to the branch when pushing the
gh-pages branch.
None
None
```release-note
None
```
> Fix gh-pages push for remote branch

- internal/oci/oci_linux.go
- server/container_stats.go
- server/container_stats_list.go
/kind bug
this pulls two stats fixes into 1.17:
https://github.com/cri-o/cri-o/pull/3425 and https://github.com/cri-o/cri-o/pull/3398
```release-note
fixes bug where stats when CRI-O uses systemd cgroups are incorrectly reported 
```
> [1.17] stats fixes

- server/container_status.go
c.State() is using opLock which can sometimes be held for minutes
in e.g. runtime.ContainerStop. The opLock is there so that
operations changing the container state won't clash. There
is no reason to wait for the lock here.
The side effect is, ContainerStatus will return immediately,
not e.g. after container has finished starting or stopping,
and show the old, rather than new, state.
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>
/kind bug
This might fix https://github.com/cri-o/cri-o/issues/3455
```release-note
ContainerStatus no longer waits for a container operation (such as start or stop) to finish.
```
> server/ContainerStatus: don't lock for c.State()

- server/container_status.go
Backport of https://github.com/cri-o/cri-o/pull/3457 to 1.17; may fix https://github.com/cri-o/cri-o/issues/3455
c.State() is using opLock which can sometimes be held for minutes
in e.g. runtime.ContainerStop. The opLock is there so that
operations changing the container state won't clash. There
is no reason to wait for the lock here.
The side effect is, ContainerStatus will return immediately,
not e.g. after container has finished starting or stopping,
and show the old, rather than new, state.
/kind bug
```release-note
ContainerStatus no longer waits for a container operation (such as start or stop) to finish.
```
> [1.17] server/ContainerStatus: don't lock for c.State()

- internal/storage/image_test.go
/kind cleanup
The system context is not stored any more in the image server, which
means that we cannot pass `nil` to sysregistries, because this will
access the host configured registries and might cause the unit tests to
fail.
None
`make testunit` should now work with any configuration in `/etc/containers/registries.conf`
```release-note
None
```
/cc @rhafer
> Fix unit tests for locally configured registries

- contrib/test/integration/build/cri-o.yml
While in production we want cri-o to restart when it crashes, when we're testing we'd like to catch panics and crashes. Set restart policy in the systemd unit file to never restart, so we fail tests that make cri-o panic
also drop make install.{systemd,config} when building cri-o, as the targets are already hit when running make install
I consider this a failing test because we are failing to catch when CRI-O crashes
```release-note
none
```
> test: set cri-o systemd restart policy to no

- Makefile
Previously, make clean command was not cleaning
bin/crio-status and bin/ dir. This patch make sure
the generated bin/ is cleaned.
Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>
/kind bug
Fix make clean
> build: clean generated bin/ dir

- .circleci/config.yml
- Makefile
This is a workaround to stabilize our CI and reduce to out of memory
kills in CircleCI.
None
None
```release-note
None
```
> Downgrade golangci-lint to v1.23.8

- contrib/test/integration/build/runc.yml
This is the master branch and it makes sense to use
the latest runc for CI.
Suggested-by: @mrunalp 
```release-note
NONE
```
> Use HEAD for runc built from source

- .circleci/config.yml
- Dockerfile-nix
- Makefile
- contrib/bundle/Makefile
- contrib/bundle/build
- nix/default.nix
- nix/nixpkgs.json
- nix/nixpkgs.nix
- tutorials/setup.md
/kind cleanup
We have to drop the musl toolchain which increases the image build time
as well as gives us the opportunity to update to go 1.14. Build and test
scripts have been adapted as well.
None
None
```release-note
- Removed the musl libc build target from the static binary bundle in favor of the existing glibc variant
```
> Drop musl build from nix to update to go 1.14

- server/container_create_linux.go
/kind bug
Systemd expects to have /run, /run/lock, and /tmp
on tmpfs. It also expects to be able to write to
/sys/fs/cgroup/systemd and /var/log/journal.
None
Signed-off-by: Urvashi Mohnani umohnani@redhat.com
> Add the mounts that are required by systemd

- scripts/circle-setup
- server/container_create_linux.go
/kind bug
Systemd expects to have /run, /run/lock, and /tmp
on tmpfs. It also expects to be able to write to
/sys/fs/cgroup/systemd and /var/log/journal.
```release-note
```
> [1.17] Add the mounts that are required by systemd

- docs/crio.8.md
- docs/crio.conf.5.md
- internal/lib/sandbox/namespaces.go
- internal/lib/sandbox/namespaces_linux.go
- pinns/pinns.c
- pkg/config/config.go
- test/restore.bats
/kind bug
This change is largely needed for third party networking plugins. These plugins often bind mount /var/run/netns and expect to be able to operate on the namespaces of the pods. Unfortunately, by pinning to /var/run/crio/ns*, we lose this capability. Rather than pinning everything to /var/run/netns/ns/uts or something odd, change the way pinns builds the pinned namespace. Now, we bind namespaces to /var/run/$NS_NAMEns/$ID
Also, add a test that verifies some different permutations of managing namespace lifecycle and restore, to make sure changes like this, as well as admins toggling namespace lifecycle management, don't mess up a restore
once https://github.com/cri-o/cri-o/pull/3487 merges, I think the NamespaceDir change is a good candidate.
```release-note
when pinning …
```
> pinns: pin to /var/run/*ns instead of /var/run/crio/ns/*

- completions/fish/crio.fish
- docs/crio.8.md
- docs/crio.conf.5.md
- internal/lib/sandbox/namespaces.go
- internal/lib/sandbox/namespaces_linux.go
- pinns/pinns.c
- pkg/config/config.go
- test/restore.bats
This change is largely needed for third party networking plugins. These plugins often bind mount /var/run/netns and expect to be able to operate on the namespaces of the pods. Unfortunately, by pinning to /var/run/crio/ns*, we lose this capability. Rather than pinning everything to /var/run/netns/ns/uts or something odd, change the way pinns builds the pinned namespace. Now, we bind namespaces to /var/run/$NS_NAMEns/$ID
Also, add a test that verifies some different permutations of managing namespace lifecycle and restore, to make sure changes like this, as well as admins toggling namespace lifecycle management, don't mess up a restore
once https://github.com/cri-o/cri-o/pull/3487 merges, I think the NamespaceDir change is a good candidate.
```release-note
when pinning …
```
> [1.17] pinns: pin to /var/run/*ns instead of /var/run/crio/ns/* 

- internal/lib/container_server.go
- server/sandbox_run_linux.go
/kind bug
sandbox: Make sure the label annotation is proper JSON
The io.kubernetes.cri-o.Labels annotation is supposed to contain a JSON formatted string. Make sure that we set a proper JSON value (null) even if there are no labels. The empty string '' that was used before is not valid JSON.
Fixes #3511
cc @saschagrunert 
```release-note
- Empty sandbox labels are now serialized into proper JSON (`null`)
```
> sandbox: Make sure the label annotation is proper JSON

- internal/lib/container_server.go
- server/sandbox_run_linux.go
/kind bug
sandbox: Make sure the label annotation is proper JSON
The io.kubernetes.cri-o.Labels annotation is supposed to contain a JSON formatted string. Make sure that we set a proper JSON value (null) even if there are no labels. The empty string '' that was used before is not valid JSON.
Fixes #3511
backport of https://github.com/cri-o/cri-o/pull/3523
```release-note
- Empty sandbox labels are now serialized into proper JSON (`null`)
```
> [1.17] sandbox: Make sure the label annotation is proper JSON

- Makefile
- nix/default.nix
/kind feature
Setting DEBUG=1 during build will now result in a binary containing the
debug symbols. The same applies to the nix build when setting "DEBUG=1"
in `nix/default.nix`.
Fixes https://github.com/cri-o/cri-o/issues/3528
None
```release-note
None
```
> Enable debug symbols for binaries when make DEBUG=1

- internal/lib/container_server.go
- server/sandbox_run_linux.go
/kind bug
sandbox: Make sure the label annotation is proper JSON
The io.kubernetes.cri-o.Labels annotation is supposed to contain a JSON formatted string. Make sure that we set a proper JSON value (null) even if there are no labels. The empty string '' that was used before is not valid JSON.
Fixes #3511
backport of https://github.com/cri-o/cri-o/pull/3523
```release-note
- Empty sandbox labels are now serialized into proper JSON (`null`)
```
> [1.16] sandbox: Make sure the label annotation is proper JSON

- Makefile
/kind cleanup
this allows us to inject a version when the version script doesn't work (building rpm specs, disconnected cri-o builds, etc...)
```release-note
CRI-O's version can be overriden at buildtime with `VERSION=my.version.number make bin/crio`
```
> makefile: allow version to be overridden

- .circleci/config.yml
- Makefile
- scripts/release-branch-forward/release_branch_forward.go
/kind feature
We now add the release branch forward script to CircleCI, which will on
on every master branch push.
None
None
```release-note
None
```
> Add release branch forward to CircleCI

- contrib/systemd/crio.service
/kind cleanup
drop requires for crio wipe in systemd unit file as it really only "required" in openshift, and admins can configure their unit files to add it if they want. most of what it did is cause headaches for new users, so it's better to drop it
fixes https://github.com/cri-o/cri-o/issues/3544
```release-note
systemd unit file: drop crio-wipe.service as a requirement
```
> systemd unit: drop requirement of crio wipe

- server/container_create_linux.go
do not specify a memory limit=0 if there are no limits in place.
/kind bug
do not set a memory limit=0 if the container doesn't have any limit in place.
OCI specifies -1 to be the value for unlimited memory.
```release-note
NONE
```
> server: skip setting memory limit to 0

- .circleci/config.yml
- scripts/latest-version/latest_version.go
We should not publish the release notes if no binary bundle has been
uploaded. To fix that scenario, we now only allow notes generation if
the `results` step has been finished.
None
None
```release-note
None
```
> Make release notes require results in CircleCI

- cmd/crio/config.go
- completions/fish/crio.fish
- docs/crio.8.md
- internal/config/migrate/from_1_17.go
- internal/config/migrate/migrate.go
- test/config_migrate.bats
- test/testdata/config/config-v1.17.0.toml
/kind feature
We now offer a new option `crio config -m/--migrate` to migrate the current provided config to the latest version. The feature also logs which changes will be done to the config before printing the result:
```console
> sudo ./bin/crio config -m 1.17
INFO Migrating config from 1.17
INFO Checking for NET_RAW and SYS_CHROOT capabilities, which have been removed per default
INFO Removing "default_capabilities" entry "NET_RAW"
INFO Removing "default_capabilities" entry "SYS_CHROOT"
INFO Checking for default AppArmor profile, which does not contain the version number any more
INFO Checking for the log level, which has changed from error to info
INFO Checking for ctr_stop_timeout, which now has a minimum value of 30
INFO Changing "ctr_stop_timeout" to 30
#
…
```
None
I will add …
> Add crio config --migrate feature

- internal/storage/image.go
- server/image_status.go
/kind feature
The custom `Info` field can be used to add additional data to the image
status, where we now align with docker to add the image labels there.
References to https://github.com/kubernetes-sigs/cri-tools/issues/584
None
```release-note
- Add available image labels to image status info
```
> Add image labels to ImageStatus Info

- Makefile
/kind bug
The local configuration should have no influence on the created config
so we now reset the "-d" option as well.
None
None
```release-note
None
```
> Do not take config dir into account on config creation

- internal/lib/sandbox/namespaces.go
- internal/lib/sandbox/namespaces_linux.go
- internal/lib/sandbox/namespaces_test.go
/kind bug
now that we bind mount to $dir/$ns/$rand instead of $dir/$rand/$ns, we should not cleanup the middle directory, as it will attempt to cleanup the namespace directory for all pods
```release-note
```
> manage ns: don't cleanup top level directories

- scripts/release-branch-forward/release_branch_forward.go
/kind bug
skips tags that don't fit the form [version].[0-9]*$ (i.e. 1.18.0-rc1)
we shouldn't consider release candidates as reason to not forward master. We should stop forwarding from master once we cut a sub-minor release
```release-note
```
> branch foward: skip release candidates

- pkg/config/config.go
- pkg/config/config_test_inject.go
- server/runtime_status.go
- server/sandbox_network.go
- server/server.go
- server/server_test.go
- server/server_test_inject.go
- server/suite_test.go
- server/utils.go
/kind cleanup
The network configuration validation seems to be the right place to init
the CNI plugin, because after that we have all necessary information for
it.
None
None
```release-note
None
```
> Move CNI plugin into NetworkConfig

- scripts/dependencies/dependencies.go
Using the `_posts` directory was not optimal (they have not been
rendered to HTML) so we're switching to the repo root for the generated
reports.
None
None
```release-note
None
```
> Generate dependencies file in gh-pages root

- server/container_create_linux.go
/kind bug
In Server#createSandboxContainer, the deferred func calls DeleteContainer if there is error.
Subsequently, some error is not assigned to the error variable which is checked by the deferred func.
This PR names the error return and checks this error in deferred func.
Fixes #3558
```release-note
None
```
> Use proper variable for error return in Server#createSandboxContainer

- .circleci/config.yml
We should run the jobs which modify the gh-pages branch sequentially to
avoid races between both jobs.
None
None
```release-note
None
```
> Fix CircleCI job race accessing gh-pages branch

- README.md
Fixes: gh#3495
Following up on pr#3514 and gh#3495, it seemed better
to create a separate OBS sub-project for each
major.minor version like CentOS SIGs did.
Updates steps for install on CentOS 7, 8 and Stream. The OBS repo structure for cri-o on CentOS has been changed such that users can add repos for multiple versions in parallel and then run `yum install cri-o` without explicitly specifying the version in there.
Fixes #3495 
None.
```release-note
None.
```
> Update installation steps for CentOS

- internal/storage/image.go
- server/image_status.go
- server/image_status_test.go
- test/inspecti.bats
/kind feature
Added the full OCI image spec to the verbose `ImageStatusResponse`,
for example when running `crictl inspecti $IMAGE`.
Fixes https://github.com/cri-o/cri-o/issues/3567
I also added the output only if the request is specified in verbose mode.
```release-note
- Added the full OCI image spec to the verbose `ImageStatusResponse`, for example when running `crictl inspecti $IMAGE`.
```
> Add OCI image spec to image stats info

- internal/lib/container_server.go
- internal/lib/rename.go
/kind bug
This PR names error return variable to cover all possible error return code paths.
None
```release-note
None
```
> Use named error return for container_server

- server/sandbox_run_linux.go
- server/sandbox_run_test.go
/kind bug
Storage needs a StopContainer if it is started, and runPodSandbox errors.
```release-note
```
> Storage StopContainer on error

- go.mod
- go.sum
- vendor/github.com/containers/storage/go.mod
- vendor/github.com/containers/storage/go.sum
- vendor/github.com/containers/storage/store.go
- vendor/modules.txt
bumps c/storage to crio-release-1.17 which contains https://github.com/containers/storage/pull/581/commits/01ee1656d552287053be7f5b08eca72962a9ed9f, as we saw 
```
Apr 15 13:44:43 ip-10-0-129-128.us-east-2.compute.internal crio[70396]: panic: attempted to update last-writer in lockfile without the write lock
Apr 15 13:44:43 ip-10-0-129-128.us-east-2.compute.internal crio[70396]: goroutine 135 [running]:
Apr 15 13:44:43 ip-10-0-129-128.us-east-2.compute.internal crio[70396]: panic(0x560e8b171000, 0x560e8b4bc160)
``` 
```release-note
fix containers/storage panic
```
> [1.17] bump storage to 01ee1656d552

- server/container_status.go
- server/container_status_test.go
- test/ctr_userns.bats
/kind feature
Added the full OCI runtime spec to the verbose `ContainerStatusResponse`, for example when running `crictl inspect $CONTAINER_ID`
Fixes #3568
None
```release-note
- Added the full OCI runtime spec to the verbose `ContainerStatusResponse`, for example when running `crictl inspect $CONTAINER_ID`
```
> Add runtimeSpec field to container stats info

- internal/config/migrate/from_1_17.go
/kind cleanup
https://github.com/cri-o/cri-o/pull/3509 and  https://github.com/cri-o/cri-o/pull/3582 changed some defaults from 1.17.0. Add these defaults to config migrate 
```release-note
```
> config migrate: add pause image and namespace dir

- Makefile
- pkg/config/config.go
/kind cleanup
The two make targets `docs-generation` and `completions` should behave
the same in rootless and root execution. To achieve this, we now disable
rootless for the storage options. This should not harm the overall
behavior since CRI-O does not support rootless mode yet.
None
None
```release-note
None
```
> Make docs-generation and completions work rootless

- OWNERS
Adds /me as an approver, making official a position I have been pretending to have for a while :smile: 
the issue of people forgetting I do not get an `approve` label with my PRs
```release-note
```
> add haircommander to OWNERS file

- go.mod
- go.sum
- internal/config/capabilities/capabilities.go
- internal/config/capabilities/capabilities_test.go
- internal/config/capabilities/suite_test.go
- pkg/config/config.go
- vendor/github.com/containers/common/pkg/config/config.go
- vendor/github.com/containers/common/pkg/config/containers.conf
- vendor/github.com/containers/common/pkg/config/default.go
- vendor/modules.txt
/kind feature
We now validate the provided capabilities on config validation to give
users more feedback about their input.
None
None
```release-note
- Added verification of provided `--default-capabilities`/`default_capabilities` on configuration validation (CRI-O startup)
```
> Validate capabilities on CRI-O start

- server/sandbox_run_linux.go
- server/sandbox_run_test.go
Backports https://github.com/cri-o/cri-o/pull/3588 and replaces the bot backport https://github.com/cri-o/cri-o/pull/3594
/kind bug
```release-note
```
> [release-1.17] add stop container for StorageRuntimeServer on error

- server/container_create_linux.go
/kind bug
In Server#createSandboxContainer, the deferred func calls DeleteContainer if there is error.
Subsequently, some error is not assigned to the error variable which is checked by the deferred func.
This PR names the error return and checks this error in deferred func.
Fixes #3558
```release-note
None
```
> [release-1.17] Use proper variable for error return in Server#createSandboxContainer

- server/container_create_linux.go
/kind bug
If createSandboxContainer returns non-nil error, we should stop the container.
```release-note
None
```
> Stop container when there is error in createSandboxContainer

- contrib/test/integration/build/crun.yml
- server/container_create_linux.go
- server/container_update_resources.go
- test/ctr.bats
/kind bug
Per https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#how-pods-with-resource-limits-are-run, when kubernetes runs a container with a memory usage limit set, it expects results comparable to using docker run --memory=....
Per https://docs.docker.com/config/containers/resource_constraints/#--memory-swap-details, if the --memory flag is used, but the --memory-swap flag is not used, the swap space limit value is expected to be equal to the memory limit value.
This swap space limit includes the memory limit, though, so kubernetes effectively expects us to not allow the container to use swap.
CRI-O currently doesn't ask a runtime to set a limit on the amount of swap space a container is allowed to use, but OpenShift has build tests that check for …
> SetLinuxResourcesMemorySwap to the LinuxResourcesMemoryLimit

- server/container_create_linux.go
/kind bug
In Server#createSandboxContainer, the deferred func calls DeleteContainer if there is error.
Subsequently, some error is not assigned to the error variable which is checked by the deferred func.
This PR names the error return and checks this error in deferred func.
Fixes #3558
```release-note
None
```
> [release-1.16] Use proper variable for error return in Server#createSandboxContainer

- server/sandbox_run_linux.go
- server/sandbox_run_test.go
Backports https://github.com/cri-o/cri-o/pull/3588 and replaces the bot backport https://github.com/cri-o/cri-o/pull/3595
/kind bug
```release-note
```
> [release-1.16] add stop container for StorageRuntimeServer on error

- nix/default.nix
/kind bug
This should prevent the net package to link against the host resolver.
Fixes https://github.com/cri-o/cri-o/issues/3612
None
```release-note
- Fixed glibc static binary bug to not resolve DNS correctly
```
> Fix static build DNS resolving with netgo

- internal/version/version.go
/kind bug
This fixes some issues where the linkmode cannot be retrieved because of
non-absolute paths.
None
None
```release-note
- Fix bug in `crio version` output where the linkmode cannot be retrieved because of non absolute paths of the executable
```
> Use absolute path to binary when retrieving linkmode

- server/container_create.go
- server/container_create_linux.go
- server/container_remove.go
- server/container_stop.go
- server/sandbox_network.go
- server/sandbox_remove.go
- server/sandbox_run_linux.go
- server/sandbox_stop_linux.go
Add info logs to all the defers in container and sandbox create.
Add logs for when we get a request from kubelet to stop and remove
a container and sandbox.
And Check for context erroring before returning from longer requests
The kubelet times out on the create request but crio doesn't error out
when kubelet client times out. So, we end up with the pod being created
and then kubelet keeps on trying to create the pod again and it can't
since the name is reserved.
With the change, we error out on timeouts so the pod creation fails and
the name is unreserved so later attempts by the kubelet to create a pod
or container may succeed.
```release-note
```
> Add info logs where needed and check for context erroring

- go.mod
- go.sum
- server/sandbox_network.go
- server/sandbox_stop_test.go
- test/ctr.bats
- test/mocks/ocicni/types.go
- vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
- vendor/github.com/cri-o/ocicni/pkg/ocicni/types.go
- vendor/modules.txt
What type of PR is this?
/kind bug
What this PR does / why we need it:
Update ocicni vendored code to get new "WithContext" methods.
Pass a child context from the one supplied to cri-o calls to ocicni, with half of the timeout for that respective request
Which issue(s) this PR fixes:
Special notes for your reviewer:
Does this PR introduce a user-facing change?
None
> [1.18] Pass context from caller to ocicni methods

- internal/version/version.go
/kind bug
The actual output of ldd is in the error which caused static binaries to
return the wrong linkmode.
None
None
```release-note
- Fixed wrong linkmode output (on `crio version`) for static binaries
```
> Fix linkmode for static binaries

- internal/version/version.go
In case if crio is located and run from `$PATH`, `Args[0]` is just `crio`, so `filepath.Abs` returns `${PWD}/crio`
os.Executables() should be used instead
/kind bug
```release-note
None
```
> Fix Linkmode path resolution

- internal/oci/runtime_oci.go
/kind bug
If cmd.Start() returns error in runtimeOCI#CreateContainer, we should close childStartPipe.
```release-note
None
```
> Close childStartPipe if cmd.Start() fails

- internal/pkg/storage/runtime.go
/kind bug
Backports https://github.com/cri-o/cri-o/pull/3596 to 1.16
```release-note
NONE
```
> [1.16] more retErr fixes

- go.mod
- go.sum
- vendor/github.com/containers/storage/go.mod
- vendor/github.com/containers/storage/go.sum
- vendor/github.com/containers/storage/store.go
- vendor/modules.txt
bumps c/storage to crio-release-1.17 which contains https://github.com/containers/storage/pull/581/commits/01ee1656d552287053be7f5b08eca72962a9ed9f, as we saw 
```
Apr 15 13:44:43 ip-10-0-129-128.us-east-2.compute.internal crio[70396]: panic: attempted to update last-writer in lockfile without the write lock
Apr 15 13:44:43 ip-10-0-129-128.us-east-2.compute.internal crio[70396]: goroutine 135 [running]:
Apr 15 13:44:43 ip-10-0-129-128.us-east-2.compute.internal crio[70396]: panic(0x560e8b171000, 0x560e8b4bc160)
``` 
```release-note
fix containers/storage panic
```
> [1.16] bump c/storage to 01ee1656d5522870

- internal/oci/runtime_oci.go
/kind cleanup
In runtimeOCI#UpdateContainerStatus, we shouldn't hold lock when ExponentialBackoff() is called.
This PR 
* makes the command calling code a lambda
* releases the lock before ExponentialBackoff() is called
* obtains the lock after backoff ends
* call command again
```release-note
None
```
> Do not hold lock when ExponentialBackoff() is called

- test/mocks/ocicni/types.go
Re-generation of the mocks should make lint and unit tests work again.
None
None
```release-note
None
```
> [1.18] Fix CI by re-generating mocks

- internal/oci/runtime_oci.go
/kind bug
In runtimeOCI#CreateContainer, the channel for syncStruct is not closed.
This PR closes the channel after sending syncStruct to it.
```release-note
None
```
> Close the channel for syncStruct

- server/container_create.go
- server/container_create_linux.go
- server/container_remove.go
- server/container_stop.go
- server/sandbox_network.go
- server/sandbox_remove.go
- server/sandbox_run_linux.go
- server/sandbox_stop_linux.go
/kind cleanup
Add info logs to all the defers in container and sandbox create.
Add logs for when we get a request from kubelet to stop and remove
a container and sandbox.
And add a storage stop container in container create as a defer so
we clean up if we fail to start the container.
```release-note
```
> [1.16] Add info logs where needed

- hack/build-rpms.sh
- server/container_create.go
- server/container_create_linux.go
- server/container_remove.go
- server/container_stop.go
- server/sandbox_network.go
- server/sandbox_remove.go
- server/sandbox_run_linux.go
- server/sandbox_stop_linux.go
/kind cleanup
Add info logs to all the defers in container and sandbox create.
Add logs for when we get a request from kubelet to stop and remove
a container and sandbox.
```release-note
```
> [release-1.17] Add info logs where needed

- internal/oci/runtime_oci.go
- internal/oci/runtime_vm.go
/kind bug
In runtimeVM#execContainerCommon, if err is nil after select statement finishes, we call r.remove().
However, if the remove call returns error, the deferred func would try to call r.remove() again (almost certain to fail).
This PR avoids calling remove() a second time.
```release-note
None
```
> Avoid removing container twice

- internal/oci/runtime_vm.go
/kind cleanup
The err is filled by the goroutine, at the time runtimeVM#StartContainer returns, err would be nil.
This PR removes the ineffective error wrapping.
```release-note
None
```
> Remove unnecessary error wrapping for runtimeVM#StartContainer

- internal/criocli/criocli.go
- internal/criocli/criocli_test.go
- internal/criocli/suite_test.go
/kind feature
The string slice parser of urfave/cli takes arguments like this:
`--flag value1 --flag value2`. We now re-add the removed behavior to
parse comma separated values like `--flag value1,value2` as a fallback
to the current one.
None
None
```release-note
- Re-add the behavior that string slices can be passed to the CLI comma separated, for example `--default-capabilities CHOWN,KILL`
```
> Allow comma separated string slice parsing

- hack/build-rpms.sh
@umohnani8 @haircommander @mrunalp  PTAL
reverts a temporary change caused by problems in CentOS Infra which have since been fixed
None
None
```release-note
None
```
> Release 1.16 revert centos url hack

- contrib/bundle/Makefile
- contrib/bundle/build
/kind cleanup
Both systemd units are not required and therefore should not be part of
the static bundle.
None
None
```release-note
- Removed `crio-wipe.service` and `crio-shutdown.service` systemd units from the static bundle since they are not required
```
> Remove crio-wipe and crio-shutdown systemd units from bundle

- server/container_create.go
- server/container_create_linux.go
- server/container_remove.go
- server/container_stop.go
- server/sandbox_network.go
- server/sandbox_remove.go
- server/sandbox_run_linux.go
- server/sandbox_stop_linux.go
Add info logs to all the defers in container and sandbox create.
Add logs for when we get a request from kubelet to stop and remove
a container and sandbox.
And Check for context erroring before returning from longer requests
The kubelet times out on the create request but crio doesn't error out
when kubelet client times out. So, we end up with the pod being created
and then kubelet keeps on trying to create the pod again and it can't
since the name is reserved.
With the change, we error out on timeouts so the pod creation fails and
the name is unreserved so later attempts by the kubelet to create a pod
or container may succeed.
```release-note
```
> [1.18] Add info logs where needed and check for context erroring 

- server/container_status.go
c.State() is using opLock which can sometimes be held for minutes
in e.g. runtime.ContainerStop. The opLock is there so that
operations changing the container state won't clash. There
is no reason to wait for the lock here.
The side effect is, ContainerStatus will return immediately,
not e.g. after container has finished starting or stopping,
and show the old, rather than new, state.
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>
> [1.16] server/ContainerStatus: don't lock for c.State()

- internal/oci/runtime_oci.go
/kind bug
This PR closes receiveStdout and stdinDone in runtimeOCI#AttachContainer.
Also closes errorCh in runtimeOCI#ReopenContainerLog
```release-note
None
```
> Close channels in runtimeOCI

- internal/lib/sandbox/sandbox.go
/kind bug
In Sandbox#SetNetworkStopped, we shouldn't close f without checking error return from os.Create
```release-note
None
```
> Check error return from os.Create before closing file

- Makefile
- internal/version/version_test.go
- server/naming_test.go
By using the right before-each function.
None
None
```release-note
None
```
> Fix naming unit test

- Makefile
Add support for setting SOURCE_DATE_EPOCH
See: https://reproducible-builds.org/specs/source-date-epoch/
Also make BUILD_DATE into a make variable
/kind feature
Makes it possible to reproduce builds.
Fixes #3702
Code is from https://reproducible-builds.org/docs/source-date-epoch/#Makefile
```release-note
Add build support for setting SOURCE_DATE_EPOCH
```
> Add support for making reproducible builds

- go.mod
- go.sum
- server/sandbox_network.go
- server/sandbox_stop_test.go
- test/mocks/ocicni/types.go
- vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
- vendor/github.com/cri-o/ocicni/pkg/ocicni/types.go
- vendor/modules.txt
What type of PR is this?
/kind bug
What this PR does / why we need it:
Update ocicni vendored code to get new "WithContext" methods.
Pass a child context from the one supplied to cri-o calls to ocicni, with half of the timeout for that respective request
Which issue(s) this PR fixes:
Special notes for your reviewer:
Does this PR introduce a user-facing change?
None
> Pass context from caller to ocicni methods

- internal/lib/container_server.go
/kind bug
In ContainerServer#LoadSandbox, if podIDIndex.Add() call fails, we should delete container Id from ctrIDIndex.
```release-note
None
```
> Delete container Id from ctrIDIndex if podIDIndex.Add fails

- go.mod
- internal/oci/runtime_oci.go
- server/container_portforward.go
- vendor/modules.txt
> port forward: drain the stream on error

- internal/version/version.go
> /kind bug
omitempty on String(), as we already have set omitempty on the JSON version, but the String() method left in empty strings
also return empty string when we fail to check the ldd status of the binary (as opposed to setting the field as the error)
```release-note
```
> version: small tweaks

- internal/oci/oci.go
/kind bug
In Runtime#WaitContainerStateStopped, the goroutine waiting for ContainerStateStopped may time out.
In this case, the select statement should close done channel.
```release-note
None
```
> Close done channel if the wait for ContainerStateStopped times out

- internal/oci/oci.go
/kind bug
In Runtime#DeleteContainer, we should only delete the container Id from runtimeImplMap if the call to impl.DeleteContainer(c) doesn't return non-nil error.
```release-note
None
```
> Delete container Id only when impl.DeleteContainer(c) passes

- go.mod
- go.sum
- vendor/modules.txt
/kind cleanup
Running `go mod tidy` and `go mod vendor` cleaned up these files.
gopls choking up on CRI-O master.
No
```release-note
Cleanup go module and vendor files.
```
> Cleanup go modules and vendor

- server/sandbox_network.go
/kind bug
We are now passing a context down to the networkPlugin stack. We are seeing timeouts at 1 minute cleaning up networking. This proposes we remove the 1 minute timeout, and use the context deadline that is passed.
```release-note
```
> removes the one minute network stop timeout

- server/image_pull.go
/kind bug
A number of active goroutines are running for an extended period of time:
```
goroutine 6975025 [chan receive, 38 minutes]:
github.com/cri-o/cri-o/server.(*Server).pullImage.func1(0xc0021a3860, 0x562778dc32c0, 0xc0063841e0, 0xc002cd0ff0, 0x562778dee420, 0xc007139a40)
/builddir/build/BUILD/cri-o-5f5c5e443806e56ce083fa6c40cfc916804fac3d/_output/src/github.com/cri-o/cri-o/server/image_pull.go:157 +0x80
created by github.com/cri-o/cri-o/server.(*Server).pullImage
/builddir/build/BUILD/cri-o-5f5c5e443806e56ce083fa6c40cfc916804fac3d/_output/src/github.com/cri-o/cri-o/server/image_pull.go:156 +0x575
```
This PR closes the progress channel cleaning up the goroutine.
```release-note
```
> [1.17] Close image pull progress goroutine after completion

- scripts/upload-artifacts
The upload URL has to be retrieved before doing an upload to GitHub.
With this fix we will do this now.
None
None
```release-note
None
```
> Use correct upload URL for binary uploads

- Makefile
Distro packaging often uses non-default build and linker flags.
The current Makefile cannot be used in the package build process as it
will end up rebuilding the binaries with the default flags.
This commit introduces install targets which do not depend on the build
targets. Distro packages should prefer these if they want to use any
non-default flags.
NOTE: This commit effectively leaves prior targets unchanged, so users
won't notice any difference.
(Couldn't find a better /kind)
This PR makes it easier for distros to re-use Makefile install targets
while continuing to build with custom flags/rules.
```release-note
None
```
> Makefile: include -nobuild install targets

- internal/version/version.go
/kind bug
The actual output of ldd is in the error which caused static binaries to
return the wrong linkmode.
None
Cherry-picked: 2843f551e6079dffa280cfc56ed326e0a208672d
```release-note
- Fix linkmode retrieval on `crio version` for static binaries
```
> [1.18] Fix linkmode for static binaries

- Makefile
Distro packaging often uses non-default build and linker flags.
The current Makefile cannot be used in the package build process as it
will end up rebuilding the binaries with the default flags.
This commit introduces install targets which do not depend on the build
targets. Distro packages should prefer these if they want to use any
non-default flags.
NOTE: This commit effectively leaves prior targets unchanged, so users
won't notice any difference.
(cherry picked from commit c6233a2b4b26daa21195078f0883d1cbfc56ba49)
Allows packaging to reuse upstream Makefile
None
None
```release-note
None
```
> [1.18] Makefile: include -nobuild install targets

- test/crio-wipe.bats
- test/helpers.bash
The selected binary in the crio wipe integration tests had the wrong
path, which should be now fixed.
None
None
```release-note
None
```
> [1.18] Fix static binary integration tests

- Makefile
Distro packaging often uses non-default build and linker flags.
The current Makefile cannot be used in the package build process as it
will end up rebuilding the binaries with the default flags.
This commit introduces install targets which do not depend on the build
targets. Distro packages should prefer these if they want to use any
non-default flags.
NOTE: This commit effectively leaves prior targets unchanged, so users
won't notice any difference.
(cherry picked from commit c6233a2b4b26daa21195078f0883d1cbfc56ba49)
Allows packaging to reuse upstream Makefile
None
None
```release-note
None
```
> [1.17] Makefile: include -nobuild install targets

- server/container_create_linux.go
- vendor/github.com/containers/libpod/pkg/selinux/selinux.go
- vendor/modules.txt
/kind Feature
Newer versions of container-selinux, container-selinux-2.132.0 or newer,
supply a `container_init_t` label.  If CRI-O is running systemd or init inside
of the container, then the container will require different SELinux privs
to run the container.
By using the new SELinux label, we can run ordinary containers with a tighter
selinux policy then those running the init system, makeing the overlay system
more secure.
The eliminates the need to turn on the container_manage_cgroup SELinux boolean.
Ie. no need to execute
```
setsebool -P container_manage_cgroup 1
```
Any longer. On systems without the updated container-selnux package, the containers will still
attempt to run the standard container type `container_t`, and still require the boolean.
Signed-off-by: Daniel J Walsh …
> Automatically label containers running systemd with the correct label

- contrib/test/integration/build/runc.yml
We should only use HEAD in master branch (see #3493), not in release branches. This is to prevent possible CI failures caused by changes in upstream runc.
/kind flake
```release-note
NONE
```
> [1.18] Pin runc for CI

- server/naming_test.go
This is supposed to fix the following panic in "ci/circleci: unit-tests" job observed in https://github.com/cri-o/cri-o/pull/3752:
•! Panic [0.008 seconds]
cri-o: Server cri-o: ReserveSandboxContainerIDAndName [It] should succeed
/go/src/github.com/cri-o/cri-o/server/naming_test.go:16
Test Panicked
runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:212
Full Stack Trace
github.com/cri-o/cri-o/server.(*Server).ReserveSandboxContainerIDAndName(0x0, 0xc00053d3a8, 0x0, 0x3, 0x0, 0xc0006c2960)
/go/src/github.com/cri-o/cri-o/server/naming.go:34 +0xfa
github.com/cri-o/cri-o/server_test.glob..func22.1.1()
/go/src/github.com/cri-o/cri-o/server/naming_test.go:19 +0x10c
github.com/cri-o/cri-o/test/framework.RunFrameworkSpecs(0xc00029a7e0, 0x1f305cd, …
> [1.18] fix naming test panic

- internal/version/version.go
/kind bug
omitempty on String(), as we already have set omitempty on the JSON version, but the String() method left in empty strings
also return empty string when we fail to check the ldd status of the binary (as opposed to setting the field as the error)
```release-note
fix some `crio version` oddities
```
> [1.18] version: small tweaks

- scripts/release-notes/release_notes.go
This changes the release notes generation script to also work for
release branches.
None
Forward-port of https://github.com/cri-o/cri-o/pull/3766
```release-note
None
```
> Allow release notes for release branches

- go.mod
- go.sum
- server/container_create_linux.go
- vendor/github.com/containers/libpod/cmd/podman/cliconfig/config.go
- vendor/github.com/containers/libpod/libpod/healthcheck.go
- vendor/github.com/containers/libpod/libpod/image/image.go
- vendor/github.com/containers/libpod/libpod/runtime.go
- vendor/github.com/containers/libpod/pkg/cgroups/cgroups.go
- vendor/github.com/containers/libpod/pkg/rootless/rootless_linux.c
- vendor/github.com/containers/libpod/pkg/rootless/rootless_linux.go
- vendor/github.com/containers/libpod/pkg/rootlessport/rootlessport_linux.go
- vendor/github.com/containers/libpod/pkg/selinux/selinux.go
- vendor/github.com/containers/libpod/pkg/spec/config_linux.go
- vendor/github.com/containers/libpod/pkg/spec/config_unsupported.go
- vendor/github.com/containers/libpod/pkg/spec/spec.go
- vendor/github.com/containers/libpod/version/version.go
- vendor/modules.txt
/kind Feature
Newer versions of container-selinux, container-selinux-2.132.0 or newer,
supply a `container_init_t` label.  If CRI-O is running systemd or init inside
of the container, then the container will require different SELinux privs
to run the container.
By using the new SELinux label, we can run ordinary containers with a tighter
selinux policy then those running the init system, makeing the overlay system
more secure.
The eliminates the need to turn on the container_manage_cgroup SELinux boolean.
Ie. no need to execute
```
setsebool -P container_manage_cgroup 1
```
Any longer. On systems without the updated container-selnux package, the containers will still
attempt to run the standard container type `container_t`, and still require the boolean.
Signed-off-by: Daniel J Walsh …
> [1.18] Automatically label containers running systemd with the correct label

- server/container_create_linux.go
/kind bug
This PR adds check for containerConfig.GetLinux().GetSecurityContext() not to be nil before dereferencing.
This would give the if statement parity consistent with how GetPrivileged() is called in other parts of the file.
```release-note
None
```
> Check that SecurityContext is not nil before dereferencing

- pkg/sandbox/sandbox.go
- pkg/sandbox/sandbox_setnameandid_test.go
/kind bug
before we started switching to have sandbox be in an interface, the only reason we fatally failed on run pod sandbox was if there was no Namespace. Uid did not need to be defined. I see no harm in continuing to do this.
fixes https://github.com/cri-o/cri-o/issues/3618
```release-note
Fixed bug where Pod creation would fail if Uid was not specified in Metadata of sandbox config passed in a run pod sandbox request
```
> sandbox iface: don't fail if uid is not specified

- internal/log/interceptors.go
- internal/oci/oci.go
- internal/oci/runtime_oci.go
- internal/oci/runtime_vm.go
- server/container_portforward.go
- tutorials/setup.md
/kind feature
This is the analogous implementation to
https://github.com/containerd/cri/pull/1470 to remove the socat runtime
dependency from CRI-O.
None
None
```release-note
- Removed `socat` runtime dependency which was needed for pod port forwarding
```
> Remove socat runtime dependency

- conmon/conmon.c
There are no situations that conmon should be OOM killed. In all situations conmon would be OOM killed, it is from a poorly acting container in conmon's cgroup. Even with -999, if conmon allocates memory at the wrong time, it will be OOM killed. If conmon is made un-OOM-killable, the container will be the one to be killed, as is correct.
/kind bug
> [1.11] conmon: make un-OOM-killable

- internal/oci/runtime_oci.go
We want to return early from a non-tty attach only if stdin is
enabled otherwise we want to wait for the output as well.
This PR fixes a race exposed by recent changes in https://github.com/kubernetes/kubernetes/pull/91227
```release-note
None
```
> oci: Don't return early for non-tty attach if there is no stdin

- tutorials/kubeadm.md
cri-o bridge default subnet is 10.85.0.0 now, as per
https://github.com/cri-o/cri-o/blob/master/contrib/cni/10-crio-bridge.conf
What type of PR is this?
What this PR does / why we need it:
Cleanup docs
> Fixed cidr standard net in documentation

- internal/lib/container_server.go
- server/sandbox_run_linux.go
- server/sandbox_status.go
- test/pod.bats
/kind feature
This PR  adds verbose info to sandbox status CRI 
so we can return useful information about the pod
such as the image in use.
```release-note
Return pod image, pid and spec in sandbox_status CRI verbose mode
```
> Add sandbox verbose info

- internal/storage/runtime.go
- internal/storage/runtime_test.go
- server/container_create_linux.go
- server/container_status.go
- server/container_status_test.go
- server/sandbox_run_linux.go
- server/sandbox_run_test.go
- test/ctr.bats
- test/mocks/criostorage/criostorage.go
/kind feature
We now add an additional field to the `info` of the container status
indicating if a container is running in privileged mode or not.
Fixes https://github.com/cri-o/cri-o/issues/3769
None
```release-note
- Added `privileged` field to container status `info`
```
> Add `privileged` indicator to container status

- go.mod
- server/image_pull.go
- server/metrics/metrics.go
- tutorials/metrics.md
- vendor/modules.txt
/kind feature
This commit adds two new metrics `crio_image_pulls_failures` and
`crio_image_pulls_successes`.
`crio_image_pulls_successes` counts every successful image pull
operation by the image name, wheras `crio_image_pulls_failures` contains
an additional `error` label. Possible error labels are:
- `UNKNOWN`:
The default label which gets applied if the error is not known
- `CONNECTION_REFUSED`:
The local network is down or the registry refused the connection
- `CONNECTION_TIMEOUT`:
The connection timed out during the image download
- `404_NOT_FOUND`:
The registry does not exist at the specified resource
- `BLOB_UNKNOWN`:
This error may be returned when a blob is unknown to the registry in a
specified repository. This can be returned with a standard get or if a
manifest references an …
> Add image pull success and failure metrics

- server/sandbox_run_linux.go
/kind cleanup
In Server#runPodSandbox, we currently create one deferred func for each cleanup func.
This is not necessary.
This PR uses one deferred func to run the cleanup.
```release-note
None
```
> Use one deferred func to execute cleanup func's

- pkg/sandbox/sandbox.go
- pkg/sandbox/sandbox_setnameandid_test.go
/kind bug
It is not strictly needed, just a namespace is
```release-note
Fixed bug where Pod creation would fail if Uid was not specified in Metadata of sandbox config passed in a run pod sandbox request
```
> [1.18] sandbox iface: don't fail if uid is not specified

- internal/config/seccomp/seccomp_test.go
/kind cleanup
When I run tests on Fedora, I got the following failure:
```
cri-o: Config cri-o: IsDisabled [It] should be false per default
/home/zyu/cri-o/internal/config/seccomp/seccomp_test.go:22
Expected
<bool>: true
to be false
/home/zyu/cri-o/internal/config/seccomp/seccomp_test.go:28
Full Stack Trace
github.com/cri-o/cri-o/internal/config/seccomp_test.glob..func1.2.1()
/home/zyu/cri-o/internal/config/seccomp/seccomp_test.go:28 +0xfc
github.com/cri-o/cri-o/test/framework.RunFrameworkSpecs(0xc000178500, 0x88fbb4, 0xd)
/home/zyu/cri-o/test/framework/framework.go:99 +0x15a
github.com/cri-o/cri-o/internal/config/seccomp_test.TestLibConfig(0xc000178500)
/home/zyu/cri-o/internal/config/seccomp/suite_test.go:14 +0x8a
```
Looking at …
> Check whether seccomp is enabled before making assertion

- server/container_create.go
/kind bug
In ensureSaneLogPath(), if the call to os.RemoveAll fails, we log the error.
However, the format string is wrong. '%s' shouldn't be used with err.
This PR corrects the mistake.
```release-note
None
```
> Use correct format for logPath removal log

- server/server.go
/kind bug
When the following case is triggered, done channel is not closed.
```
case err := <-watcher.Errors:
logrus.Debugf("watch error: %v", err)
return
```
This PR closes the done channel before returning.
```release-note
None
```
> Close the done channel when there is watcher error

- pkg/config/template.go
It makes sense to have crun in the config template to give users a hint
that there is another drop-in OCI runtime available.
None
None
```release-note
- Added `crun` container runtime to `crio.conf` (commented out per default)
```
> Add crun to config template

- server/server.go
/kind bug
In Server#restore() 
```
ips, err := s.getSandboxIPs(sb)
if err != nil {
logrus.Warnf("could not restore sandbox IP for %v: %v", sb.ID(), err)
}
sb.AddIPs(ips)
```
sb.AddIPs() should only be called when err return from getSandboxIPs() is nil.
```release-note
None
```
> Add sandbox IPs if there is no error in IP retrieval

- internal/lib/sandbox/namespaces.go
- internal/lib/sandbox/namespaces_test.go
- test/mocks/containerstorage/containerstorage.go
- test/mocks/oci/oci.go
/kind flake
turns out, the PID 42 (as idiomatic a test variable it is) is not the best PID to use.
NamespacePaths() returns /proc entries if the PID is running, so sometimes there was a PID 42 on the system, and the tests returned valid paths, causing the test to fail
This PR updates the tests to use the values 0 (unset pid), 1 (running pid), and 4194305 (never running pid, as it's max_pid+1)
it also fixes a small inconsistency in reserving space for the slice of namespace paths
```release-note
```
> managed_ns: deflake tests

- internal/lib/stop.go
- internal/oci/container.go
- internal/oci/container_test.go
- internal/oci/runtime_oci.go
- internal/oci/runtime_vm.go
/kind flake
in stop, we need to check the pod's status before stopping it.
However, as it stands, we do it in two distinct steps: State() followed by ContainerStop()
There exists a race where:
the State() call happens
followed by an UpdateContainerStatus() (marking the container as stopped)
followed by the Container Stop()
we've hit this race quite a bit in circleCI running 'pod stop idempotent with ctrs already stopped'
fix this by moving the check branching on Status to after we take the opLock()
```release-note
```
> oci: check container status before stop atomically

- internal/lib/container_server.go
- internal/lib/container_server_test.go
/kind bug
In ContainerServer#ListContainers, we should only include container once even if there are two filters which the container passes.
```release-note
None
```
> Container should only be added once after passing filter

- internal/oci/runtime_oci.go
- server/container_execsync.go
/kind cleanup
logging "Exec'd..." for every exec sync is too much, especially on Info
if we fail to decode state, we should log why the `$runtime state` command failed
```release-note
```
> logs: fix some problems

- contrib/bundle/Makefile
- contrib/bundle/build
- scripts/versions
/kind feature
This allows us to give users the possibility to use crun instead of runc.
Refers to https://github.com/kubernetes-sigs/cri-tools/issues/613
@giuseppe do we need to have crun as drop-in for runc? Because I always see that it gets symlinked as runc and not used as stand-alone `crun`.
```release-note
- Added latest `crun` version to static binary bundle
```
> Add crun to static binary bundle

- internal/oci/runtime_oci.go
/kind bug
In waitContainerStop, done channel should be closed by the goroutine.
```
case <-chControl:
return
```
The close of channel was missing in the above case.
```release-note
None
```
> Close the done channel in waitContainerStop

- internal/config/node/node.go
- internal/config/node/systemd.go
- server/container_create_linux.go
- server/sandbox_run_linux.go
/kind cleanup
currently, systemd leaks some scopes if they're failed.
This can be changed with the CollectMode annotation (which runc will set).
However, only systemd version >= 236 has support for this, so we need a new entry in internal/config/node to check whether systemd is the correct version
```release-note
```
> use inactive-or-failed CollectMode if appropriate

- server/sandbox_run.go
> /kind bug
> /kind design
/kind feature
> /kind flake
There is a protocol filter in the current code that filters out all host ports that do not have TCP or UDP as protocol defined. Originally this protocol filter was introduced to prevent the loading of the SCTP kernel module on the nodes. But the iptables chain creation alone does not load the kernel module. The module would be loaded if an SCTP socket was created. The host port manager imported by CRI-O already filters out the SCTP ports from the set of ports on which it starts listening. As there is no socket operation (listening) on the SCTP ports the kernel module is not loaded. We can remove this filter here …
> Remove the protocol filter from the portMappings constructor

- cmd/crio/main.go
- internal/criocli/criocli.go
- internal/criocli/criocli_test.go
/kind bug
Make  StringSliceTrySplit return a copy of the underlying slice as otherwise the underlying flags in the ctx might be overriden, which can cause issue when the config is reloaded (GetConfigFromContext() is called more than once).
Fixes #3862 
```release-note
Fix handling of the --cni-plugin-dir and other multivalue command line flags
```
> StringSliceTrySplit: return a copy of the underlying slice

- internal/lib/stop.go
- internal/oci/container.go
- internal/oci/container_test.go
- internal/oci/runtime_oci.go
- internal/oci/runtime_vm.go
/kind flake
in stop, we need to check the pod's status before stopping it.
However, as it stands, we do it in two distinct steps: State() followed by ContainerStop()
There exists a race where:
the State() call happens
followed by an UpdateContainerStatus() (marking the container as stopped)
followed by the Container Stop()
we've hit this race quite a bit in circleCI running 'pod stop idempotent with ctrs already stopped'
fix this by moving the check branching on Status to after we take the opLock()
```release-note
```
> [1.17] oci: check state before stop atomically

- cmd/crio/main.go
- internal/criocli/criocli.go
- internal/criocli/criocli_test.go
/kind bug
Fixes #3862
1.18 Backport of PR #3870 
```release-note
Make StringSliceTrySplit return a copy of the underlying slice as otherwise the underlying flags in the ctx might be overriden, which can cause issue when the config is reloaded (GetConfigFromContext() is called more than once).
```
> [1.18] StringSliceTrySplit: return a copy of the underlying slice

- oci/oci.go
- test/ctr.bats
> /kind bug
> /kind design
> /kind flake
We shouldn't return a custom error when an exec sync command
times out. Instead, we should return a non-zero exit code.
When the prober code in kubernetes sees a custom error
it goes into Unknown status and doesn't restart containers
on timed out probes as expected.
Signed-off-by: Mrunal Patel mrunalp@gmail.com
```release-note
```
> [1.11] oci: handle timeouts correctly for probes

- contrib/test/integration/e2e-features.yml
- internal/criocli/criocli_test.go
/kind feature
The `[Feature:SCTP]` and `[Feature:Seccomp]` are now enabled by default
as well as the lint issue got fixed.
None
None
```release-note
None
```
> Select disabled e2e features manually and enable SCTP/Seccomp tests

- server/container_status.go
r.ContainerStatus(c) is using opLock which can sometimes be held for minutes
in e.g. runtime.ContainerStop. The opLock is there so that
operations changing the container state won't clash. There
is no reason to wait for the lock here.
The side effect is, ContainerStatus will return immediately,
not e.g. after container has finished starting or stopping,
and show the old, rather than new, state.
adapted from https://github.com/cri-o/cri-o/pull/3457
Signed-off-by: Kir Kolyshkin <kolyshkin@gmail.com>
> /kind bug
> /kind design
> /kind flake
```release-note
```
> [1.11] server/ContainerStatus: don't lock

- contrib/test/integration/e2e-base.yml
/kind flake
it seems the `get service` command succeeded before the cluster was actually ready to take workloads,
which occasionally means kubetest runs before the node is ready for it to, causing a flake
```release-note
```
> test: use node readiness as an indicator to run kubetest

- completions/fish/crio.fish
- docs/crio.8.md
- internal/criocli/criocli.go
- test/helpers.bash
/kind feature
Let's add a new field to the "--runtimes" option, allowing consumers of
the cli to also define the type of the runtime.
This is particularly useful to ease testing of the "vm" runtime, used by
kata-containers.
Mind that this PR does *not* break the command-line backwards
compatibility as we do not mandate 4 fields to be defined, but in case a
4th field is define, it'll be treated as the runtime_type.
Fixes #3877
```release-note
Adds a new optional field, runtime_type, to the "--runtimes" option.
```
> Add runtime_type as an option of "--runtimes"

- server/container_execsync.go
/kind cleanup
we lost https://github.com/cri-o/cri-o/pull/3860/commits/71165c783b4717e496337279a0667bdfe6110be4 in the many attempts to find the `runc state` problem
```release-note
```
> [1.18] logs: drop print on execsyncs

- Makefile
- cmd/crio/main.go
- internal/version/version.go
The version was missing from the first output line,
ldd warnings were printed and the link information
was missing (due to reusing the $LDFLAGS variable).
This broke compatibility with earlier crio versions.
Cherry-picked to `master` from PR #3845
> Restore version output from crio --version

- internal/config/node/systemd.go
/kind bug
The "systemctl --version" parsing code assumed output like, eg:
systemd 243 (v243.8-1.fc31)
but it may just be, eg
systemd 239
None; seen in logs while debugging something else:
`Jul 10 00:49:38 master-0 crio[2250]: time="2020-07-10 00:49:38.185271104Z" level=error msg="Node configuration validation for systemd CollectMode failed: systemd version command returned incompatible formatted information: systemd 239\n+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=legacy\n"`
```release-note
NONE
```
> config: fix systemd version parsing

- internal/oci/oci.go
/kind bug
Currently the done channel may be closed in the goroutine or by the select statement starting on line 139.
We need to consider the following scenario:
* detection of ContainerStateStopped exhausts the timeout, with done channel closed by the select statement starting on line 139
* around the same time, ContainerStateStopped is returned from UpdateContainerStatus call, resulting in the close of done channel on line 132.
This PR moves the close of done channel to the main goroutine of WaitContainerStateStopped.
Fixes #3925
```release-note
None
```
> Streamline how done channel is closed in Runtime#WaitContainerStateStopped

- pkg/config/config.go
- pkg/config/config_test.go
/kind feature
Usually we would trigger this error on runtime but we can also report it
on CRI-O startup. This allows user to act early on misconfigurations.
None
None
```release-note
- Added configuration validation to ensure a `conmon_cgroup == "pod"` if `cgroup_manager == "cgroupfs"`
```
> Validate cgroupfs conmon cgroup on start

- server/utils.go
Signed-off-by: Brandon Lum <lumjjb@gmail.com>
/kind bug
> /kind design
> /kind flake
Initializes decrypt config to appropriate value if decryption-keys directory doesn't exist.
Fixes #3913 
```release-note
```
> Return empty DecryptConfig when no keys to force decryption

- internal/oci/runtime_vm.go
/kind bug
When shutting the container down, we're dealing with the following piece
of code on Kata side:
https://github.com/kata-containers/runtime/blob/master/containerd-shim-v2/service.go#L785
```
func (s *service) Shutdown(ctx context.Context, r *taskAPI.ShutdownRequest) (_ *ptypes.Empty, err error) {
defer func() {
err = toGRPC(err)
}()
s.mu.Lock()
if len(s.containers) != 0 {
s.mu.Unlock()
return empty, nil
}
s.mu.Unlock()
s.cancel()
os.Exit(0)
// This will never be called, but this is only there to make sure the
// program can compile.
return empty, nil
}
```
The code shown above will simply stop the service, closing the ttrpc
channel, raising then the "ErrClosed" error, which is returned by the
Shutdown.
Differently from containerd code, which simply igores the error, CRI-O …
> runtime_vm: Ignore ttrpc.ErrClosed when shutting the container down

- internal/oci/runtime_vm.go
It looks like a concurrent map accces can occur here, since the only
lock taken is per-container. Guard such accesses with a mutex lock.
/kind bug
```release-note
None
```
> internal/oci/runtime_vm: lock around map access

- internal/oci/oci.go
- internal/oci/runtime_oci.go
- internal/oci/runtime_vm.go
- server/container_create.go
- server/container_create_linux.go
- server/sandbox_network.go
- server/sandbox_run_linux.go
- utils/io/helpers.go
if we're branching on whether we errored in execution at the end of a function, we should use the retErr name, as it should not get shadowed
partial port of https://github.com/cri-o/cri-o/pull/3934/commits
/kind bug
```release-note
fixed bug where pod names would sometimes leak on creation, causing the kubelet to fail to recreate
```
> [1.18] change variable name err to retErr for deferred comparisons

- internal/oci/runtime_vm.go
/kind bug
In case of failures on CreateContainer, let's do a full cleanup by
closing the IO opened, removing the container, shutting it down, and
finally removing it from the containers' map, which is performed by the
recently introduced deleteContainer() function.
```release-note
None
```
> runtimeVM: Improve CreateContainer cleanup in case of failures

- .golangci.yml
- Makefile
We also enable non-complaining linters as well as adding new ones to the
list in .golangci.yml.
None
None
```release-note
None
```
> Update golangci lint to v1.28.3

- cmd/crio/main.go
This reverts commit ffffdf8f36267cd07dbe46e356b49cbdac4ccd65.
/kind bug
```release-note
Fix a bug where a sudden reboot causes incomplete image writes. This could cause image storage to be corrupted, resulting in an error `layer not known`.
```
> [1.18] Revert "container_server: disable fdatasync() for atomic writes"

- internal/oci/oci.go
- internal/oci/runtime_oci.go
- internal/oci/runtime_vm.go
- server/container_create.go
- server/container_create_linux.go
- server/sandbox_network.go
- server/sandbox_run_linux.go
- utils/io/helpers.go
/kind bug
if we're branching on whether we errored in execution at the end of a function,
we should use the retErr name, as it should not get shadowed
this includes the non-controversial half of https://github.com/cri-o/cri-o/pull/3934 (all of https://github.com/cri-o/cri-o/pull/3950)
```release-note
fixed bug where pod names would sometimes leak on creation, causing the kubelet to fail to recreate
```
> change variable name err to retErr for deferred comparisons

- internal/version/version.go
/kind bug
The returned error is `Not a valid dynamic program` which is now catched
by the binary check as well.
None
None
```release-note
- Fixed `crio version` binary mode parsing on musl toolchains
```
> Fix static binary mode retrieval for musl toolchains

- contrib/systemd/crio-shutdown.service
- contrib/systemd/crio-wipe.service
/kind bug
Some distributions have bash in other paths so we should call out to
`/usr/bin/env` to verify that the unit file works there as well.
None
None
```release-note
- Fix path to bash via `/usr/bin/env` in crio-shutdown.service
```
> Use /usr/bin/env bash in crio-shutdown.service

- server/sandbox_run_linux.go
/kind bug
This PR removes resolvPath if Relabel fails in Server#runPodSandbox.
Fixes #3976
```release-note
None
```
> Remove resolvPath when Relabel fails

- server/sandbox_run_linux.go
/kind cleanup
This PR performs log directory validation early in Server#runPodSandbox.
Fixes #3977
```release-note
None
```
> Perform log directory validation early in Server#runPodSandbox

- internal/oci/runtime_oci.go
- test/ctr.bats
/kind bug
We have to make a spec copy before overwriting the args to not overwrite them for each exec(sync).
Fixes #3988
None
```release-note
- Fixed a bug where exec sync requests (manually or automatically triggered via readiness/liveness probes) overwrite
the runtime `info.runtimeSpec.process.args` of the container status (for example via `crictl inspect`).
```
> Copy spec to not touch original spec on exec(sync)

- Makefile
/kind bug
> /kind design
> /kind flake
When trying to build a statically linked `crio` binary I was getting:
```shell
→ make build-static
podman run --rm -it -v /home/ifont/go/src/github.com/cri-o/cri-o:/cri-o quay.io/crio/nix:1.4.0 sh -c \
"nix build -f cri-o/nix && \
mkdir -p cri-o/bin && \
cp -r result/bin cri-o/bin/static"
error: opening file '/cri-o/nix/default.nix': Permission denied
make: *** [Makefile:178: build-static] Error 1
```
This happens because SELinux requires the correct labeling on content that is volume mounted within the container. This option tells Podman to relabel the file objects on the volume with a private unshared label. …
> Add volume mount option for SELinux labeling

- internal/lib/container_server.go
- server/container_update_resources.go
- server/container_update_resources_test.go
/kind bug
> /kind design
> /kind flake
Call to the `UpdateContainerResources` did not update the resources under the container spec,
so we had a situation when resources had updated values under the cgroup, but it did not reflect
under the container spec.
Now `UpdateContainerResources` will update the container spec under the memory store once the updated command succeeded.
Fixes #3963
```release-note
Reflects resource updates under the container spec.
```
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
> Update the container resources under the spec

- .circleci/config.yml
- Makefile
- contrib/test/integration/build/crun.yml
- nix/default.nix
- nix/nixpkgs.json
Similar PR goes for crun/conmon/libpod/cri-o/etc, too.
Also see:
- ~~https://github.com/containers/crun/pull/372~~
- ~~https://github.com/containers/conmon/pull/161~~
- ~~https://github.com/containers/skopeo/pull/932~~
- ~~https://github.com/containers/buildah/pull/2380~~
- ~~https://github.com/containers/libpod/pull/6402~~
- https://github.com/cri-o/cri-o/pull/3804
Static binaries:
- [crun-0.13-linux-amd64](https://github.com/alvistack/crun/releases/download/0.13/crun-0.13-linux-amd64)
- [conmon-v2.0.17-linux-amd64](https://github.com/alvistack/conmon/releases/download/v2.0.17/conmon-v2.0.17-linux-amd64)
- [skopeo-v1.1.0-linux-amd64](https://github.com/alvistack/skopeo/releases/download/v1.1.0/skopeo-v1.1.0-linux-amd64)
- …
> Cleanup and update nix derivation for static builds

- .circleci/config.yml
/kind cleanup
This should bring the CI in order again to not slip-through the recently
added integration suite.
None
None
```release-note
None
```
> Make integration-cgroupfs tests depdent on results

- internal/lib/container_server.go
- internal/lib/sandbox/history_test.go
- internal/lib/sandbox/sandbox.go
- internal/lib/sandbox/sandbox_test.go
- internal/lib/sandbox/suite_test.go
- internal/lib/suite_test.go
- server/sandbox_run_linux.go
- server/suite_test.go
- test/restore.bats
/kind bug
When restarting cri-o, try to restore the createdAt timestamp of Sandboxes from the annotations. Previously the timestamp was reset to time.Now() when restoring Sandboxes. As Sandbox are not guaranteed to be restored in creation order in server.restore() this could lead to ordering issues in calls like e.g. ListPodSandbox which would not return the Pods in the orginial creations order.
To reproduce this issue in crio, create a couple of Sandboxes (with `crictl`) using the same name but different "Attempt" numbers. Then restart crio and run `crio pods`. Two things should be visible:
* the `CREATED` time in the `crio pods` is reset with every crio restart. While the createdAt annoation seen with `crio inspectp` is staying the same
* The order in which the pods are listed might …
> Restore Sandbox createdAt timestamp on cri-o restart

- cmd/crio/main.go
Commit 6025578f11 (Oct 23 2019, "Update golangci lint and apply fixes")
inadvertently removed the pprof import, as a result, pprof can't be used
even when enabled during runtime (via --profile flag), giving 404 on
every URL.
Bring it back.
Fixes PR #2916 (https://github.com/cri-o/cri-o/pull/2916/commits/6025578f117b2905f91d75dded6d2aac346c2af2#diff-702431da3a2e35392cf253955d15f774)
/kind bug
```release-note
None
```
> Bring back pprof

- server/sandbox_run_linux.go
/kind bug
In Server#runPodSandbox, when both parseDNSOptions and removeFile calls return error, we shouldn't assign err1 to err because that would erase the reason behind parseDNSOptions failure.
```release-note
None
```
> Remove unnecessary err assignment

- internal/oci/runtime_vm.go
/kind bug
StartContainer() function will hold the opLock, while a goroutine will
be waiting for the container to terminate. Once it happens, the
goroutine would update the container status, calling then
UpdateContainerStatus() which will try to get the opLock and,
consequently, a deadlock will happen.
In order to avoid such situation, let's create the
updateContainerStatus() helper, which actually does status update but
does not try to get the opLock, leaving it up to the caller to do so.
This new helper will be used from both StartContainer() and
UpdateContainerStatus() functions.
```release-note
None
```
> runtime_vm: Avoid possible deadlock on UpdateContainerStatus()

- internal/oci/runtime_vm.go
/kind bug
When the container finishes its execution a containerd-shim-kata-v2
process is left behind (only when using CRI-O).
The reason for that seems to be CRI-O not doing a cleanup of the process
whenever the container state has changed its state from running to
stopped.
The most reasonable way found to perform such cleanup seems to be taking
advantage of the goroutine used to update the container status and
performing the cleanup there, whenever it's needed.
Related: https://github.com/kata-containers/runtime/issues/2719
This is yet another part of the series trying to not leave container-shim-kata-v2 processes around, but this time focusing on cleaning up when the container finishes its execution without errors.
This series also includes the patch provided in …
> runtimeVM: Cleanup a "Completed" container

- pkg/config/config.go
- pkg/config/config_test.go
Fixes - #3536
/kind bug
This PR addresses the concerns raised in #3536 about having runtimes other than default `runc` be responsible for making sure the existing `runc` configuration is not broken. For example, please refer to #3536 for additional info on how it affects the users of Kata runtime. 
Fixes #3536 
Yes
```release-note
Adding additional runtime handler doesn't require the user to copy existing default runtime handler configuration. The existing default runtime handler configuration will be preserved while adding the new runtime handler. 
```
> Do not remove existing runtime handler

- server/container_create.go
- server/sandbox_run_linux.go
/kind cleanup
even if cri-o perfectly cleans up its state after failures, name is reserved errors are still possbile.
Mainly: when cri-o times out attempting to provision networking or disk resources.
Given this is the most likely scenerio, print this as a debug message, rather than the cryptic "reserving * name"
```release-note
none
```
> name is reserved: give more informative error

- .circleci/config.yml
- Dockerfile-nix
- Makefile
- nix/nixpkgs.json
Speedup static build by utilizing CI cache on `/nix` folder
Also see:
- https://github.com/containers/crun/pull/428
- https://github.com/containers/conmon/pull/189
- https://github.com/containers/skopeo/pull/973
- https://github.com/containers/buildah/pull/2428
- https://github.com/containers/podman/pull/7076
- https://github.com/cri-o/cri-o/pull/4012
Fixes #4005
Fixes #4009
Some more founding:
- Due to `nixos/nix` limitation which without `bash` bundled, not every CI with Docker engine direct support would happy with :-(
- Caching `/nix` directly may also make some CI not happy due to permission issue; therefore I cache it with `.cache` and export/import it in case already warm up, else copy from `nixos/nix` directly.
- Cache for Circle CI (for …
> Speedup static build by utilizing CI cache on `/nix` folder

- internal/config/cgmgr/cgmgr.go
- internal/config/cgmgr/cgmgr_test.go
- internal/config/cgmgr/cgroupfs.go
- internal/config/cgmgr/systemd.go
- internal/oci/oci_linux.go
- test/stats.bats
/kind bug
Allows viewing of stats by individual container instead of the whole pod
Fixes #3580 
How the stats display for containers
```release-note
fixed a bug where crictl only showed pod level stats, not container level stats.
```
> Improves container memory usage stats

- server/container_list.go
/kind feature
The `PodSandboxID` can now be truncated because we're just checking for its prefix.
Refers to https://github.com/kubernetes-sigs/cri-tools/pull/643
None
```release-note
- Added behavior to allow filtering by a partial Pod Sandbox ID
```
> Make filter container list be able to filter short pod IDs

- pinns/Makefile
/kind cleanup
Allows cross compile tool-chains to select the correct `strip` binary to use.
Without this change it will attempt to use the host tool-chain instead of the target tool-chain, which will fail if the underlying architecture is not the same.
```release-note
None
```
> Parameterize strip binary in pinns/Makefile for cross-compilation

- Makefile
- scripts/release/release.go
/kind feature
The new `make release` target can be used to automatically create a PR
which bumps the CRI-O version. The fork organization has to be set
manually like this:
```
> make release ORG=saschagrunert
```
We are also able to specify the remote name for which we wanna push the
changes:
```
> make release ORG=saschagrunert REMOTE=other-than-origin
```
The script will automatically pick-up the local branch (the target
branch for the PR), increment the version in version.go and create the
PR for that.
Refers to #4003 
None
```release-note
None
```
> Add `make release` target

- cmd/crio/wipe.go
- internal/lib/container_server.go
- internal/oci/runtime_vm.go
- internal/storage/runtime.go
- server/label_linux.go
- server/sandbox_remove.go
- server/sandbox_run_linux.go
- server/sandbox_stop_linux.go
- server/secrets.go
- server/server.go
/kind bug
a strange interaction between the go compiler and errors.Cause() seems to happen.
Sometimes, the condition `err != nil` is checked after `errors.Cause(err)...`
since errors.Cause(err) segfaults if err == nil, we need to put the second check in a new block
it sucks, but we've seen a segfault like in https://storage.googleapis.com/origin-federated-results/pr-logs/pull/cri-o_cri-o/3887/test_pull_request_crio_e2e_fedora/13716/artifacts/journals/crio.service once already
```release-note
```
> fix segfault with errors.Cause()

- internal/config/node/cgroups.go
- internal/config/node/node.go
/kind bug
our rhel 7 boxes that are used to package cri-o are failing with the following error:
```
panic: cannot statfs cgroup root
goroutine 1 [running]:
```
this is because the libcontainer cgroup packages opts to panic when the stat on /sys/fs/cgroup fails, rather than return an error
The point of the node package is to gracefully catch and handle these errors, so we switch to libpod version instead, and will now print
we failed to stat, rather than panic on it.
Note: these nodes are not suitable for running workloads, as runc will later panic, but packaging (in this case, building a config) should not panic because of it.
```release-note
fixes panic when /sys/fs/cgroup can't be stat'ed
```
> node: fix panic if /sys/fs/cgroup failed to stat

- internal/oci/runtime_vm.go
/kind bug
This is the backport of a bunch of PRs touching the runtimeVM, which would be really good to have them as part of 1.18 stable branch.
None
```release-note
None
```
> [1.18] runtimeVM backports to release-1.18 branch

- server/container_stats_list.go
- server/container_stats_test.go
/kind bug
skip stopped containers when reporting stats
we have run into situations where cri-o reports a cgroup is deleted on list container stats calls, and it takes a while for cri-o to actually remove the container from the state. Stopped containers shouldn't matter with reporting stats, so we can skip them.
should fix spammed logs [here](https://storage.googleapis.com/origin-federated-results/pr-logs/pull/cri-o_cri-o/3477/test_pull_request_crio_e2e_crun_fedora/2405/artifacts/journals/crio.service) 
also fixes https://github.com/cri-o/cri-o/issues/3259
```release-note
none
```
> stats: skipped stopped containers on container list stats

- test/ctr.bats
- test/helpers.bash
- test/profile.bats
/kind bug
(NB: why don't we have kind: ci?)
Adds a CI integration test to make sure crio --profile works
This is a followup to #4011, addressing the https://github.com/cri-o/cri-o/pull/4016#issuecomment-663587938
```release-note
NONE
```
> add crio --profile test

- pkg/config/config.go
- pkg/config/config_test.go
/kind design
We've changed the handling of hooks_dir quite a bit, hopefully this is the last of such changes.
There are cases where directories are not present on the host, but admins would desire some entity put hooks into said directory. The primary use case I can think of is a temporary directory in /run that allows hooks to be wiped on reboot. Not really a use case worth packaging for everyone, but instead something cri-o should handle  
```release-note
hooks_dir entries are now created if they don't exist
```
> config: create hooks dir if not present

- vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/network/hostport/hostport.go
- vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/network/hostport/hostport_manager.go
/kind bug
Cherry-picks vendored Kubernetes PR 80591.
```release-note
Fixes a bug where traffic from localhost is always masqueraded.
```
> UPSTREAM: 80591: hostport: Don't masquerade localhost-to-localhost traffic

- internal/oci/runtime_vm.go
/kind bug
This PR contains all the VM runtime type fixes provided in the last month or so.
Those fixes are related to processes (qemu, virtiofs, and containerd-shim-kata-v2) being left behind in several situations, such as:
- pod deletion;
- pod failure;
- pod completion;
Together with those, a bunch of possible deadlocks were fixed, some locks have been added, and a fix for a health check failures.
Although this PR brings a bunch of fixes for 1.17 branch, I would **not** do a 1.17 release after it's merged.
I'd wait a little bit for one or two more fixes which are in the queue to be reviewed / worked on. 
```release-note
None
```
> [1.17] backports related to the VM runtime type

- test/ctr.bats
First, the code
[ "$status" -ne 0 ] || [ "$output" =~ "Exit code: 1" ]
is not working since one can't use `=~` operator inside `[..]`
(it is only working inside `[[..]]`).
Here's an example:
```console
$ [ "aaa bbb" =~ "aaa" ]; echo $?
bash: [: =~: binary operator expected
2
```
Since the test never failed, I guess $status was always non-zero,
so the second part was never evaluated, thus it is not needed.
This was found by shellcheck:
```
In ctr.bats line 1008:
[ "$status" -ne 0 ] || [ "$output" =~ "Exit code: 1" ]
^-- SC2074: Can't use =~ in [ ]. Use [[..]] instead.
```
Second, the cleanup/stop stuff added by the commit is not needed,
since `teardown()` is executed after each test, and it contains
a call to `cleanup_test()` which calls the same 3 functions that
were added.
This reverts …
> test/ctr.bats: fix test check

- test/image_volume.bats
1. Use `CONTAINER_IMAGE_VOLUME` rather than `IMAGE_VOLUME`. The test
case was working before because `mkdir` is the default.
2. Quote the value assigned to CONTAINER_IMAGE_VOLUME. This helps
readability, and eliminates the following shellcheck warning:
```
In test/image_volume.bats line 74:
IMAGE_VOLUMES=mkdir start_crio
^----------------------------^ SC2209: Use var=$(command) to assign output (or quote to assign string).
```
3. Remove the cleanup/stop from the last test case. This is performed in
teardown() anyway.
/kind cleanup
```release-note
NONE
```
> test/image_volume.bats: fixes

- internal/oci/runtime_vm.go
/kind bug
For shim v2 `exec` API, the call sequences to runtime is uncertain.
It's may be `CloseIO` -> `Exec` -> `Start` or `Exec` -> `CloseIO` -> `Start`, or
`Exec` -> `Start` -> `CloseIO`. The last call sequence is the right one.
This PR will ensure the call sequence as `Exec` -> `Start` -> `CloseIO`.
Fixes #4046 
None
```release-note
None
```
> Ensure CloseIO is called after Start for exec

- internal/oci/runtime_vm.go
/kind bug
The first patch of this series reverts commit 924a8e9830f112821f03984d417f938f945ba442, as the commit in question introduced a regression on CRI-O, when using the VM runtime type, which caused the logs to never be stored in:
`/var/log/pods/$namespace_$pod_name_$pod_uid/$container_name/$restart_number.log`
The second commit fixes the log format as the current format of logs stored by CRI-O, when using the VM runtime type, looks like:
```
[root@k8s cri-o]# cat /var/log/pods/default_fio-test_855d9cec-2b0f-42d2-bbe5-cce769cb7b10/fio/0.log
{
"fio version" : "fio-2.17-45-g06cb",
"timestamp" : 1597428680,
"timestamp_ms" : 1597428680853,
"time" : "Fri Aug 14 18:11:20 2020",
"jobs" : [
{
"jobname" : "random-writers-emptydir",
"groupid" : 0,
"error" : 0,
"eta" : 0,
"elapsed" : 61,
"job …
```
> runtimeVM: Store logs again, and store them in the correct format

- test/apparmor.bats
- test/cgroups.bats
- test/command.bats
- test/config.bats
- test/crio-wipe.bats
- test/ctr.bats
- test/ctr_seccomp.bats
- test/ctr_userns.bats
- test/default_mounts.bats
- test/image.bats
- test/image_volume.bats
- test/inspect.bats
- test/network.bats
- test/pod.bats
- test/restore.bats
- test/status.bats
- test/version.bats
/kind cleanup
```release-note
NONE
```
This fixes shellcheck warning SC2076, for example
```
In default_mounts.bats line 90:
[[ "$output" =~ "test.txt" ]]
^--------^ SC2076: Don't quote right-hand side of =~, it'll match literally rather than as a regex.
```
So, operator `~=` does a comparison against a regular expression, and yet
in all the places we are actually using it to search for a substring, not a regex.
Use the substring syntax (i.e. `[[ "$output" == *"substring"* ]]`) instead
to be more clear about what we're doing.
This commit is courtesy of
```bash
for f in *.bats; do sed -i -e 's/ =\~ "\(.*\)" ]]/ == *"\1"* ]]/g' $f; done
```
and a few manual fixes on top of it.
------
> [[ "$output" != *"$ctr3_id"* ]]
> [[ "$output" != "$pod3_id" ]]
These two checks meant to check that the …
> test/*bats: fix shellcheck SC2076

- pkg/container/container.go
use the sandbox selinux label options from the pod when if they are
not overriden in the configuration.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1868122
/kind bug
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1868122
```release-note
NONE
```
> selinux: override only specified values

- .github/CODEOWNERS
- OWNERS
I've been working in the VM runtime type, and would like to officially
become responsible for this area.
Contributions made so far:
* runtime_vm: Apply the correct label before the sandbox is created
- https://github.com/cri-o/cri-o/pull/3889
* Add runtume_type as an option of "--runtimes"
- https://github.com/cri-o/cri-o/pull/3903
* runtime_vm: Ignore ttrpc.ErrClosed when shutting the container down
- https://github.com/cri-o/cri-o/pull/3924
* runtimeVM: Improve CreateContainer cleanup in case of failures
- https://github.com/cri-o/cri-o/pull/3956
* runtime_vm: Avoid possible deadlock on UpdateContainerStatus()
- https://github.com/cri-o/cri-o/pull/3987
* runtimeVM: Cleanup a "Completed" container
- https://github.com/cri-o/cri-o/pull/3998
* runtimeVM: Store logs again, and store them in …
> Add fidencio to OWNERS file

- server/container_create_linux.go
We had a customer incident where they ran out of space on /run.
If you don't specify size, it will be still limited to 50% or memory
available in the cgroup the container is running in.  If the cgroup is
unlimited then the /run will be limited to 50% of the total memory
on the system.
/kind bug
We are limiting the size of /run, which is not unnecessary, and can cause random issues.
```release-note
None
```
> Don't limit the size on /run for systemd based containers

- internal/config/cgmgr/cgroupfs.go
/kind bug
In case cgroupfs cgroup manager is used, the container got created under
the conmon cgroup (rather than under the root), and then the stats
doesn't work because the cgroup path is invalid.
For example, if the conmon cgroup is created as
/sys/fs/cgroup/pod_123-456/crio-conmon-<ID>, then the container cgroup
is created as
/sys/fs/cgroup/pod_123-456/crio-conmon-<ID>/pod_123-456/crio-<ID>,
rather than sys/fs/cgroup/pod_123-456/crio-conmon-<ID>.
The `cricrl stats` then fails as it can't find the container cgroup.
This happens because the cgroupsPath set in spec for such containers
is not absolute, so the cgroup is created under the current cgroup,
which is that of conmon.
The fix is easy.
Fixes #4075 
Found while working on https://github.com/cri-o/cri-o/pull/4064. That PR has a test …
> Fix container cgroup under cgroupfs

- test/critest.bats
- test/helpers.bash
A set of few fixes related to using bats' `run` function in the tests.
These are real fixes, not some refactoring or code style improvements.
Using `if ! run cmd` is useless as `run` always succeeds (and puts the
exit code of `cmd` to `$status`. Remove it.
1. The bats `run` command always returns 0 exit code, so
`ping_pod_from_pod` never tested anything, as it always succeeded.
2. Using `$output=$(run cmd)` is wrong, since `run` assigns the output
itself, and do not print anything per se (so `$output` is always
empty in this case).
3. Using `exit 1` from the function is excessive.
4. There is no need for the whole `if ... ` construct, as bats tests are
run with `set -e` and if the ping fails the test will fail.
Fix the `ping_pod` in the same way.
Commit 39aef1a09c1ad …
> Assorted test fixes (might help CI flakes)

- server/sandbox_run_linux.go
/kind cleanup
We already test for the availability of seccomp in `setupSeccomp()` so
we can remove the additional check.
None
None
```release-note
None
```
> Remove duplicate check for enabled seccomp

- pkg/config/config.go
- pkg/config/template.go
> /kind bug
https://github.com/cri-o/cri-o/commit/91d3d2791ce348098ba0a6a731f5809a060a1a67 introduced a regression that would cause CRIO to fail at startup if the `runc` binary is not present on the system. 
This PR attempts to preserve the changes brought in by https://github.com/cri-o/cri-o/commit/91d3d2791ce348098ba0a6a731f5809a060a1a67 as well as fix the https://github.com/cri-o/cri-o/issues/4069
Fixes #4069 
Yes
```release-note
If the default_runtime is changed from the default configuration, the corresponding existing default entry in the runtime map in the configuration will be ignored. 
```
> handle runc not present on the system

- test/stats.bats
/kind bug
* test/stats.bats: fix typo in a variable name
* test/stats.bats: improve test case
* test/stats.bats: fix/improve container stats test case
See individual commits for more details.
~~Currently blocked by #4080 and #4068~~.
```release-notes
NONE
```
@wgahnagl @haircommander PTAL
> test/stats.bats: fixes

- Makefile
- server/container_create.go
> /kind bug
This is a backport of PR #2091 (which itself is a backport of PRs #1898 and #2090) to 1.11 branch, fixing supplementary container user groups.
Should fix https://bugzilla.redhat.com/show_bug.cgi?id=1782105
```release-note
Fix supplementary container user groups
```
> [1.11 backport] RunAsGroup fixes

- Makefile
/kind bug
If the GOSUMDB cache is not up to date remotely a vendoring errors with:
```
go: github.com/containers/common@v0.14.7/go.mod: verifying module: invalid GOSUMDB: malformed verifier id
```
To aviod such failures in the future we now unset the GOSUMDB variable
which forces golang to use the plain upstream address.
None
None
```release-note
None
```
> Unset GOSUMDB when vendoring

- server/sandbox_run_linux.go
/kind cleanup
it could be useful to know whether the namespaces are actually getting cleaned up
```release-note
none
```
> managed ns: report namespace cleanup failure by default

- scripts/release-branch-forward/release_branch_forward.go
/kind cleanup
We forgot the release branch forward scripts ignored rc releases when checking if there was a release.
as such, we merged a (potentially) dangerous PR: usernamespaces, jepordizing the stability of the soon-to-be-released 1.19 branch
To fix this, revert behavior to stop fast forward on rcs
```release-note
none
```
> branch forward: stop on rc

- internal/lib/sandbox/namespaces.go
- internal/oci/container.go
/kind bug
> /kind design
> /kind flake
everytime we create a sandbox with a pinned namespace, we spit out an error that says:
`Pid for infra container $id not found: PID not initialized`
in the pinned namespace case, we create the namespaces, create the networking stack (giving the created net namespace to the plugin), THEN create the pod.
Thus, we don't expect the infra container to be initialized.
Fix this by ignoring ErrNotInitialized when we're fetching the infraPid when finding the namespaces.
We can safely do this because the managed namespace case is covered (we don't use the pid, but use the managed namespace struct we've created)
And in the non-managed …
> managed ns: ignore `PID not initialized` on sandbox creation

- server/sandbox_network.go
- server/server.go
This reverts commit f97ad7fd3fb3f0901e70a45e7caa57724715ce6c.
This PR uncovered a serial of issues in the portmap behavior that is present upstream too-
When a pod with a PortMapping is created, the portmapper opens a socket in ALL addresses to avoid that another applications can "steal" the port.
https://github.com/cri-o/cri-o/blob/master/vendor/k8s.io/kubernetes/pkg/kubelet/dockershim/network/hostport/hostport.go#L68-L84
However, as the test indicates, you should be able to user several host-ports in the same host on different addresses, this means that ALWAYS will fail to bind the first time.
It was working because, the second pod fails the first time
> Aug 28 15:03:59 crio-worker crio[18574]: time="2020-08-28 15:03:59.167098356Z" level=info msg="TEST adding hostport ips: 10.244.2.44 …
> Revert "dual stack portmap support"

- internal/runtimehandlerhooks/high_performance_hooks.go
- internal/runtimehandlerhooks/high_performance_hooks_test.go
- internal/runtimehandlerhooks/runtime_handler_hooks_suite_test.go
- internal/runtimehandlerhooks/utils.go
- internal/runtimehandlerhooks/utils_test.go
added handling for irq smp balance and cpu cfs quota control
added safety check step to make them only work on pods with exclusive cpus
> /kind bug
> /kind design
/kind feature
> /kind flake
One of the requirements for real time application is to minimize scheduling delay and interrupt. When a real time application is allocated with exclusive cpu set, we can prevent these cpus from handling interrupt work by disabling the irq smp balance on these cpus.  Additionally, since these cpus are to be solely used by this particular application, cpu cfs quota is not needed on these cpus. As a matter of fact, we have seen inappropriate throttle issues caused by cpu cfs quota. …
> added irq smp balance and cpu cfs quota control

- version/version.go
/kind bug
Tag the 1.11.16 release.
- #4115 fix supplementary user groups (fixes [BZ 1782105](https://bugzilla.redhat.com/show_bug.cgi?id=1782105))
- #4062 hostport: don't masquerade localhost-to-localhost traffic (fixes https://github.com/kubernetes/kubernetes/issues/66067)
- #3995 do not touch original spec on exec(sync) (fixes #3988)
- #3532 oci: handle timeouts correctly for probes
- #3881 no lock on container status (fixes #3455)
- #3784 conmon: protect from OOM killer
- #3299 update containers/image (fixes CVE-2020-1702)
- #3218 port forward: drain the stream on error (fixes [BZ 1798193](https://bugzilla.redhat.com/show_bug.cgi?id=1798193))
- #2630 conmon: check it is a valid pid before killing it (fixes [BZ 1730919](
https://bugzilla.redhat.com/show_bug.cgi?id=1730919)) …
> [1.11] Release 1.11.16

- internal/oci/runtime_vm.go
/kind bug
This reverts commit 814c1bb01e84d6e42cd01b5957cad6e441228fa5.
We cannot simply delete the container when its status changes to
stopped. The intention of this fix is okay-ish, but implemented in the
wrong layer.
What containerd does is calling Shutdown(), when the *pod* is finished,
and that's what we should do as well.
None
```release-note
None
```
> Revert "runtime_vm: Cleanup process when the Container is Stopped"

- pinns/utils.h
/kind bug
In case the macro is not available we now define it on our own in the utils.
Fixes https://github.com/cri-o/cri-o/issues/4136
```release-note
- Fixed pinns compilation if the `TEMP_FAILURE_RETRY` macro is not available
```
> Fix pinns compilation for TEMP_FAILURE_RETRY

- internal/oci/runtime_vm.go
/kind bug
This reverts commit 67dcd05de1ea559008ff041729b390504a4b9d03.
We cannot simply delete the container when its status changes to
stopped. The intention of this fix is okay-ish, but implemented in the
wrong layer.
What containerd does is calling Shutdown(), when the *pod* is finished,
and that's what we should do as well.
None
```release-note
None
```
> [release-1.17] Revert "runtime_vm: Cleanup process when the Container is Stopped"

- internal/lib/sandbox/sandbox.go
- test/stats.bats
/kind flake
deflake stats test by making the two containers different
deflake all tests by ignoring ENOENT on the shm unmount (as we're allowed to attempt to UnmountShm() multiple times)
```release-note
none
```
> test: reduce flakes

- internal/lib/sandbox/namespaces_linux.go
/kind bug
1. In case pinns fails, we want to return a clear error message saying
it has failed, not that we failed to unmount some mounts. So, do not
return the "failed to unmount" error as it's minor in nature, and log
the failures instead.
2. In case pinns fails, we want to see its stderr, not just stdout.
Before this patch, only stdout is collected (and now shown as it's empty).
3. We can't be sure that the mounts we are trying to unmount were
actually mounted, so ignore EINVAL from unmount(2). EINVAL means
that either argument is not the mount point (i.e. not mounted),
or that the flags are wrong. We only provide MNT_DETACH which
is not a wrong flag, ergo EINVAL means "not mounted" and it should
be ignored.
4. Only log pinns output in case of error, and do it as a warning since
it is …
> Fix pinns error diagnostics, cleanup, and return

- internal/oci/container.go
> /kind bug
/kind cleanup
> /kind design
> /kind flake
```release-note
none
```
> oci: improve error message for verifyPid()

- internal/oci/container.go
- internal/oci/container_test.go
- server/container_execsync.go
/kind cleanup
> /kind design
> /kind flake
When a container has been stopped, but the rest of its pod is still stopping, the kubelet still runs exec probes
IsAlive() correctly identifies the container has been stopped, and logs an error, but in reality, this is expected.
Instead of logging the error, return it in IsAlive (and also ExecSync), and let the kubelet report it if it thinks it'll be problematic
This fixes superluous errors like this:
"Checking if PID of 4a81020e858fbdd1ee6a271190ab36aec1940489386e177f33c2e62afa309580 is running failed: PID running but not the original container. PID wrap may have occurred"
```release-note
none
```
> oci: return IsAlive error instead of logging

- server/container_create_linux.go
/kind cleanup
Noticed there was a TODO to assign GetSecurityContext()
a variable and use that through out the create function.
```release-note
None
```
> Code clean up in containers_create_linux.go

- server/container_create_linux.go
- server/sandbox_run_linux.go
/kind feature
In order to have take fully advantage of SELinux, would be good to have the commits enabling it on CRI-O side as part of release-1.18 as well (and not only 1.19).
While I know backporting features is not exactly the best practices, this only affects the VM runtime type and is a quite self-contained.
None
```release-note
None
```
> [release-1.18] Backport "Use the container_kvm_t label when using kata as the runtime" (and follow-ups)

- pkg/config/config.go
- pkg/config/config_test.go
/kind bug
After we pull in the initial config, it is our source of truth for telling the world where our container storage is
in particular, if we, say, have an empty `storage` entry, we will return `StorageDriver: ""` on an Inspect request
the problem is, that is a lie. c/storage populates defaults for us, so we actually use overlay in that scenerio.
we don't encounter this normally, because if the toml field isn't specified (as it isn't by default), then we inherit the information from the default config
However, if a user (or an ignition config) overrides those fields to empty, we will listen to it as the source of truth, and never update to what is actually being used
Fix this by inheriting the values from c/storage on the validation step.
```release-note
Fix bug where empty config …
```
> config: set internal RootConfig to default storage if not specified

- tutorials/metrics.md
It was missing, not it's there.
None
None
```release-note
- Added `crio_image_layer_reuse` to tutorials/metrics.md documentation
```
> Add image layer reuse docs to metrics.md

- internal/lib/sandbox/namespaces.go
- internal/oci/container.go
/kind bug
> /kind design
> /kind flake
everytime we create a sandbox with a pinned namespace, we spit out an error that says:
`Pid for infra container $id not found: PID not initialized`
in the pinned namespace case, we create the namespaces, create the networking stack (giving the created net namespace to the plugin), THEN create the pod.
Thus, we don't expect the infra container to be initialized.
Fix this by ignoring ErrNotInitialized when we're fetching the infraPid when finding the namespaces.
We can safely do this because the managed namespace case is covered (we don't use the pid, but use the managed namespace struct we've created)
And in the non-managed …
> [1.19] managed ns: ignore `PID not initialized` on sandbox creation

- internal/config/apparmor/apparmor.go
/kind cleanup
This makes the definition of an own `unconfined` value obsolete by
sticking to the predefined ones in Kubernetes.
None
None
```release-note
None
```
> Switch to Kubernetes AppArmor unconfined const

- internal/oci/container.go
- internal/oci/container_test.go
/kind bug
as we have seen the ctime of it's proc entry fluctuate, and the process start time (item 22 in /proc/pid/stat)
could be more reliable
this removes superfluous log lines like this: 
`0e06ea75835a28aee51b37751e51c6a6f4ac5a54fbe5b805d13c9184c075b74b: PID 3240 is running but has start time of 1598893538, whereas the saved start time is 1598893381. PID wrap may have occurred"` 
```release-note
none
```
> oci: parse stat file instead of using ctime

- internal/oci/container.go
- internal/oci/container_test.go
/kind bug
pick of https://github.com/cri-o/cri-o/pull/4146
including https://github.com/cri-o/cri-o/pull/4154
```release-note
none
```
> [1.19] oci: parse stat file instead of using ctime

- internal/oci/runtime_vm.go
/kind bug
This reverts commit 814c1bb01e84d6e42cd01b5957cad6e441228fa5.
We cannot simply delete the container when its status changes to
stopped. The intention of this fix is okay-ish, but implemented in the
wrong layer.
What containerd does is calling Shutdown(), when the *pod* is finished,
and that's what we should do as well.
None
```release-note
None
```
> [release-1.19] Revert "runtime_vm: Cleanup process when the Container is Stopped"

- go.mod
- go.sum
- vendor/google.golang.org/grpc/.travis.yml
- vendor/google.golang.org/grpc/Makefile
- vendor/google.golang.org/grpc/balancer/balancer.go
- vendor/google.golang.org/grpc/clientconn.go
- vendor/google.golang.org/grpc/credentials/credentials.go
- vendor/google.golang.org/grpc/credentials/tls.go
- vendor/google.golang.org/grpc/dialoptions.go
- vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
- vendor/google.golang.org/grpc/internal/internal.go
- vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go
- vendor/google.golang.org/grpc/internal/transport/handler_server.go
- vendor/google.golang.org/grpc/internal/transport/http2_client.go
- vendor/google.golang.org/grpc/resolver/resolver.go
- vendor/google.golang.org/grpc/resolver_conn_wrapper.go
- vendor/google.golang.org/grpc/rpc_util.go
- vendor/google.golang.org/grpc/service_config.go
- vendor/google.golang.org/grpc/trace.go
- vendor/google.golang.org/grpc/version.go
- vendor/google.golang.org/grpc/vet.sh
- vendor/modules.txt
This fixes the build of the release-note tool, which previously failed
with:
```
vendor/google.golang.org/api/internal/conn_pool.go:29:2: undefined: grpc.ClientConnInterface
```
Refers to https://github.com/cri-o/cri-o/commit/15aa81b6bf6b0fc3a8982f099cb3d8ae1582f697
Unblocks the release after https://github.com/cri-o/cri-o/pull/4188
@haircommander I think we have to re-align the v1.19.0 tag afterwards.
```release-note
None
```
> Bump GRPC to v1.27.0

- internal/oci/runtime_vm.go
/kind bug
This reverts commit adb657c38057c6916ec2166e49076b49ea947a94.
We cannot simply delete the container when its status changes to
stopped. The intention of this fix is okay-ish, but implemented in the
wrong layer.
What containerd does is calling Shutdown(), when the *pod* is finished,
and that's what we should do as well.
None
```release-note
None
```
> [release-1.18] Revert "runtime_vm: Cleanup process when the Container is Stopped"

- server/container_create.go
/kind bug
partial cherry-pick of https://github.com/cri-o/cri-o/pull/4198
```release-note
Fixed a bug where a container creation failure caused that container to leak in the runtime
```
> [1.19] server: cleanup container in runtime after failed creation

- server/container_create.go
otherwise, we leak containers in runc
/kind bug
cherry pick of https://github.com/cri-o/cri-o/pull/4201
```release-note
Fixed a bug where a container creation failure caused that container to leak in the runtime
```
> [1.17] server: cleanup container in runtime after failed creation

- scripts/release-notes/release_notes.go
/kind cleanup
This helps to debug any issues we encounter within the CI.
None
None
```release-note
None
```
> Enable debug logs for release notes generation

- completions/fish/crio.fish
- docs/crio.8.md
- docs/crio.conf.5.md
- internal/criocli/criocli.go
- pkg/config/config.go
- pkg/config/template.go
the option was introduced in 1.17, and set as default in 1.19. Mark it as deprecated, and set to be removed by 1.21
```release-note
The `manage_ns_lifecycle` option is now deprecated, and will be set to true unconditionally in the future. 
```
> deprecate manage_ns_lifecycle option

- internal/config/seccomp/seccomp.go
/kind cleanup
To sync up the behavior with AppArmor, we now print the content of the
seccomp profile only on trace log level. Beside that, we print the JSON
instead of the struct to provide more information to the user.
None
None
```release-note
- Changed the output of the printed seccomp profile to JSON instead of the struct. The profile will be only printed on CRI-O startup and if the `--log-level`/`log_level` is set to `trace`.
```
> Print seccomp profile JSON only on trace log level

- test/config.bats
/kind bug
Sometimes this test fails like this:
> not ok 11 config dir should fail with invalid option
> (in test file ./config.bats, line 38)
>   `RES=$(cat "$CRIO_LOG")' failed
> cat: /tmp/tmp.nho2aP6lqh/crio.log: No such file or directory
> unable to decode configuration /tmp/tmp.nho2aP6lqh/crio.conf: Near line 2 (last key parsed 'crio.runtime.log_level'): expected value but found "info" instead
The reason it fails is logs are written by using tee,
which for some reason is run in a subshell, and it looks
like a race between the main shell and the subshell.
Anyway, using tee is not needed here. Simplify it by using run,
and add a check for non-zero exit code.
The second proble is, the test is not doing what it supposed to.
Judging by the test name ("config dir should fail"), it seems the …
> test/config: fix "config dir should fail with invalid option"

- internal/oci/runtime_vm.go
Implement as runtimeOCI has done.
Signed-off-by: bin liu <bin@hyper.sh>
With this user can get the same experience as containerd, and in k8s it will show the detailed reason `OOMKilled` in `STATUS` field for `kubectl get pods` command.
Fixes #4203 
This depends on that runtime like Kata containers to write `oom` file into the container's bundle directory, this is on the road for Kata containers( PR not merged yet: https://github.com/kata-containers/kata-containers/pull/698/commits/d7c77b69dc221195f66eb82799fd89f56ad24842 )
```release-note
None
```
> runtime: parse oom file for VM type runtimes

- pkg/config/config.go
- pkg/config/config_test.go
After we pull in the initial config, it is our source of truth for telling the world where our container storage is
in particular, if we, say, have an empty `storage` entry, we will return `StorageDriver: ""` on an Inspect request
the problem is, that is a lie. c/storage populates defaults for us, so we actually use overlay in that scenerio.
we don't encounter this normally, because if the toml field isn't specified (as it isn't by default), then we inherit the information from the default config
However, if a user (or an ignition config) overrides those fields to empty, we will listen to it as the source of truth, and never update to what is actually being used
Fix this by inheriting the values from c/storage on the validation step.
/kind bug …
> [1.17] config: set internal RootConfig to default storage if not specified

- contrib/test/integration/main.yml
- internal/config/node/node.go
- internal/config/node/sysctl.go
- test/sanity_checks.bats
The following failure happens in CI on RHEL7 from time to time:
> removing the pod sandbox "0d5bf5eeb0048bb70ab8ee9bca0a497e216a6c6cfa42507a8d735f61c825784d": rpc error: code = Unknown desc = unable to remove managed namespaces: Removing namespaces encountered the following errors [unlinkat /var/run/netns/0376543d-4917-417f-b406-7e8ab07cb847: device or resource busy]
(with different test cases and different namespaces).
RHEL7 kernel has upstream commit [1] backported, but the feature is
controlled by a sysctl and is off by default. For the feature to work,
one needs to set fs.may_detach_mounts = 1.
On production RHEL7 systems, this is done by runc rpm (see [2]), but
we're not using those rpms for CI, so we have to set the sysctl
manually.
Add an integration test case to …
> Fix bogus CI test failures

- internal/oci/runtime_vm.go
Signed-off-by: bin liu <bin@hyper.sh>
> /kind bug
If Pid or InitPid is not set correctly, then c.Alive()
will return false, and all calls depending on c.Alive()
will fail.
Fixes #4224 
```release-note
None
```
> runtime_vm: set Pid and InitPid for VM runtimes

- contrib/test/integration/main.yml
- test/sanity_checks.bats
_This is a partial backport of #4217 to release-1.17 branch_
/kind flake
The following failure happens in CI on RHEL7 from time to time:
> removing the pod sandbox "0d5bf5eeb0048bb70ab8ee9bca0a497e216a6c6cfa42507a8d735f61c825784d": rpc error: code = Unknown desc = unable to remove managed namespaces: Removing namespaces encountered the following errors [unlinkat /var/run/netns/0376543d-4917-417f-b406-7e8ab07cb847: device or resource busy]
(with different test cases and different namespaces).
RHEL7 kernel has upstream commit [1] backported, but the feature is
controlled by a sysctl and is off by default. For the feature to work,
one needs to set fs.may_detach_mounts = 1.
On production RHEL7 systems, this is done by runc rpm (see [2]), but
we're not using those rpms for CI, so we have to …
> [1.17] Fix bogus CI test failures on RHEL7

- test/config.bats
_this is a partial backport of https://github.com/cri-o/cri-o/pull/4213 to release-1.18 branch_
/kind flake
Sometimes this test fails like this:
> not ok 11 config dir should fail with invalid option
> (in test file ./config.bats, line 38)
>   `RES=$(cat "$CRIO_LOG")' failed
> cat: /tmp/tmp.nho2aP6lqh/crio.log: No such file or directory
> unable to decode configuration /tmp/tmp.nho2aP6lqh/crio.conf: Near line 2 (last key parsed 'crio.runtime.log_level'): expected value but found "info" instead
The reason it fails is logs are written by using tee,
which for some reason is run in a subshell, and it looks
like a race between the main shell and the subshell.
Anyway, using tee is not needed here. Simplify it by using run,
and add a check for non-zero exit code.
The second problem is, the test …
> [1.18] test/config: fix "config dir should fail with invalid option"

- internal/config/cgmgr/cgmgr.go
- internal/config/cgmgr/cgroupfs.go
- internal/config/cgmgr/systemd.go
Refractoring to check if cgroupfs cgroup manager has enough memory
Fixes  #3840 
```release-note
None
```
> Verify Cgroup Memory - cgroupfs

- server/container_create.go
- test/helpers.bash
This is a non-automated cherry-pick of #4201
/kind bug
it also includes https://github.com/cri-o/cri-o/commit/5bce7486aca3a07441bbee01c1fd2207c4949878 to hopefully fix integration_fedora flakes on this branch
```release-note
Fixed a bug where a container creation failure caused that container to leak in the runtime
```
> [1.18] server: cleanup container in runtime after failed creation

- contrib/test/integration/main.yml
- test/sanity_checks.bats
_This is a partial backport of #4217 to release-1.17 branch_
/kind flake
The following failure happens in CI on RHEL7 from time to time:
> removing the pod sandbox "0d5bf5eeb0048bb70ab8ee9bca0a497e216a6c6cfa42507a8d735f61c825784d": rpc error: code = Unknown desc = unable to remove managed namespaces: Removing namespaces encountered the following errors [unlinkat /var/run/netns/0376543d-4917-417f-b406-7e8ab07cb847: device or resource busy]
(with different test cases and different namespaces).
RHEL7 kernel has upstream commit [1] backported, but the feature is
controlled by a sysctl and is off by default. For the feature to work,
one needs to set fs.may_detach_mounts = 1.
On production RHEL7 systems, this is done by runc rpm (see [2]), but
we're not using those rpms for CI, so we have to …
> [1.18] Fix bogus CI test failures on RHEL7

- server/sandbox_run_linux.go
/kind cleanup
when we're managing ns lifecycle, we don't need to wait until the infra container has started before setting up the networking resources, as we have all that is needed (the network namespace, and sandbox annotations).
A key to this is this allows the network create to happen before the infra container creation, which prioritizes the work in case of long running network creations.
this also fixes a case where we may fail to clean up the networking resources if we fail in marshalling the returned structure
```release-note
none
```
> server: create pod network as early as possible

- test/network.bats
_This used to be a part of #4127, which I am splitting into smaller PRs_
/kind cleanup
1. Simplify the code.
For example,
```bash
run crictl start ...
echo "$output"
[ "$status" -eq 0 ]
```
is equivalent to
```bash
crictl start ...
```
as it much easier to read (yes, bats runs tests with set -e
so there is an error check in place).
One more example,
```bash
run crictl runp ...
echo "$output"
[ "$status" -eq 0 ]
pod_id="$output"
```
is roughly equivalent to
```bash
pod_id=$(crictl runp ...)
```
(except it does not print stdout, only stderr).
Another example,
```bash
cfg=$(python .... < $input)
echo "$cfg" > $output
```
is equivalent to
```bash
python ... < $input > $output
```
and avoids the use of a temporary variable (saves some memory).
Finally,
```bash
run crictl start ...
echo …
```
> test/network.bats: simplify, fix shellcheck

- test/config.bats
_this is a partial backport of https://github.com/cri-o/cri-o/pull/4213 to release-1.17 branch_
/kind flake
Sometimes this test fails like this:
> not ok 11 config dir should fail with invalid option
> (in test file ./config.bats, line 38)
>   `RES=$(cat "$CRIO_LOG")' failed
> cat: /tmp/tmp.nho2aP6lqh/crio.log: No such file or directory
> unable to decode configuration /tmp/tmp.nho2aP6lqh/crio.conf: Near line 2 (last key parsed 'crio.runtime.log_level'): expected value but found "info" instead
The reason it fails is logs are written by using tee,
which for some reason is run in a subshell, and it looks
like a race between the main shell and the subshell.
Anyway, using tee is not needed here. Simplify it by using run,
and add a check for non-zero exit code.
The second problem is, the test …
> [1.17] test/config: fix "config dir should fail with invalid option"

- utils/utils.go
This allows callers to set properties such as CollectMode.
This PR adds functionality to pass properties to systemd scope creation utility function
None
No
```release-note
None
```
> Support passing properties to RunUnderSystemScope

- test/helpers.bash
- test/network.bats
/kind cleanup
Commit 58657488e31 replaced the last component of
/var/lib/cni/networks path in network.bats to be $RANDOM_CNI_NETWORK,
while in fact it should be $CNI_DEFAULT_NETWORK
(see https://github.com/cri-o/cri-o/commit/58657488e31518ebebe3ea27ae3f540f8a9fb5b2#diff-807eaca3d52b5557160919f85ff738bc)
The bug was never found because bats do not `set -o pipefail`
and so the non-zero exit code from `ls` was ignored.
Let's fix the bug. While at it,
- merge some 90% duplicated code;
- introduce and use `fail` helper function.
None
```release-note
None
```
> test/network.bats: fix "Clean up network" tests

- test/status.bats
/kind cleanup
> /kind design
> /kind flake
Improvements for `status.bats` tests:
* Remove excessive `run` usage
* Move `echo` to `run_crio_status`
* Fix shellcheck SC2086 warning
* Reformat using shfmt (which gained bats support recently, see https://github.com/mvdan/sh/issues/600)
None
Please review commit-by-commit. Last one is just whitespace changes.
```release-note
None
```
> test/status.bats: improve

- internal/oci/runtime_vm.go
/kind bug
Initialize the InitPid when starting a pod with a _vm_ runtime.
Fixes #4264 
```release-note
None
```
> [1.19] runtime_vm: set Pid and InitPid for VM runtimes

- internal/oci/runtime_vm.go
/kind bug
It's been reported by Robert Krawitz that some pods were not terminating when using the VM runtime type.  I've tried to reproduce the issue locally and failed.  Robert, then, gave me access to one of his macines and his scripts and turns out the situation doesn't happen all the time and, when it happens, it happens usually with an infra pod hanging and with pods containing init pods, and it seems to happen because the VM is shutdown, which causes a ttrpc.ErrClosed report, but we don't handle it properly.   This PR tries to fix the issue mentioned.
None
@haircommander, I remember in the past we had issues with removing pods on runtime VM side that caused kubelet to get confused.  Would you have any tip on how I could ensure this is not happening in this case?
Also, I'm not …
> runtime_vm: Fix non terminating pods

- internal/oci/runtime_vm.go
/kind bug
It's been reported by Robert Krawitz that some pods were not terminating when using the VM runtime type.  I've tried to reproduce the issue locally and failed.  Robert, then, gave me access to one of his macines and his scripts and turns out the situation doesn't happen all the time and, when it happens, it happens usually with an infra pod hanging and with pods containing init pods, and it seems to happen because the VM is shutdown, which causes a ttrpc.ErrClosed report, but we don't handle it properly.   This PR tries to fix the issue mentioned.
None
```release-note
None
```
> [release-1.18] runtime_vm: Fix non terminating pods

- server/sandbox_run_linux.go
/kind bug
> /kind design
> /kind flake
a rebase failure between infra container and userns caused the wrong mappings to be used
This could cause a segfault, and causes wrong behavior. Fix it
```release-note
fix bug where we attempted to chown with the mappings configured on server level, when they could have been from annotations
```
> use correct mappings when they exist

- scripts/upload-artifacts
/kind cleanup
If we want to auto-upload the artifacts to GitHub, then we now error if
there could be no release found.
None
None
```release-note
None
```
> Error if GitHub release could not be found

- scripts/circle-setup
- scripts/versions
We were using golang from longsleep/golang-backports PPA.
Unfortunately, that repo is apparently no longer updated for Ubuntu
Xenial, with the latest golang being 1.13.
Since 1.13 is no longer supported, let's switch to binary distribution
from google.com, and update to 1.15.
Fixes: https://github.com/cri-o/cri-o/issues/4298
None
```release-note
None
```
> circle-ci: use go 1.15.3

- .circleci/config.yml
- scripts/circle-setup
Changes circle-ci base image from ubuntu 16.04 to ubuntu 20.04.
None
```release-note
None
```
> circleci: use ubuntu 20.04

- test/helpers.bash
- test/image.bats
/kind cleanup
We already preload a bunch of images before running tests, and it makes
sense to disable pull during crictl create, as it should save some time
and result in less flakiness in the tests (related to network glitches).
crictl 1.19 added this option, and "no pull on create" is the new
default. This reverts the hunk of commit 40b9d971fe (PR #4150)
which changes the default.
For more details, see https://github.com/kubernetes-sigs/cri-tools/pull/627
This should eventually fix the flakes caused by network issues
while running tests.
```release-note
None
```
> test: disable crictl pull on create

- nix/default.nix
/kind bug
When building a static version of cri-o, the following (valid) warnings
are shown:
```
[1/0/1 built, 0.0 MiB DL] building cri-ouildPhase)cri-o> go build  -ldflags '-s -w -X github.com/cri-o/cri-o/internal/pkg/criocli.DefaultsPath="" -X github.com/cri-o/cri-o/internal/version.buildDate='1980-01-01T00:00:00Z' -X github.com/cri-o/cri-o/internal/version.gitCommit=30353e32fa65a9e1d39249f2e5b0951278e8b493 -X github.com/cri-o/cri-o/internal/version.gitTreeState=dirty -s -w -linkmode external -extldflags "-static -lm"' -tags "static netgo exclude_graphdriver_btrfs exclude_graphdriver_devicemapper seccomp apparmor selinux" -o bin/crio github.com/cri-o/cri-o/cmd/crio
[1/0/1 built, 0.0 MiB DL] building cri-ouildPhase)cri-o> # github.com/cri-o/cri-o/cmd/crio
[1/0/1 built, 0.0 MiB DL] …
```
> nix: fix static build

- .circleci/config.yml
We have issues with integration test timeouts, which is now increased
from 10 to 30 minutes. Beside that, we upload the binary bundle without
their influence in a separate step. This should increase the
availability of uploaded artifacts and make commands like this working
better:
```
> curl -f https://storage.googleapis.com/k8s-conform-cri-o/artifacts/\
crio-$(git ls-remote https://github.com/cri-o/cri-o master | cut -c1-9).tar.gz -o crio.tar.gz
```
None
cc @harche 
```release-note
None
```
> Upload bundle in separate CI step

- Makefile
- contrib/bundle/build
- contrib/test/integration/build/crun.yml
- scripts/upload-artifacts
- scripts/versions
1. Since this is a master branch, it makes sense to test crun from
HEAD (rather than a released version) if we're compiling it from
source. A similar change was done for runc in commit 9e10f54d3ba834d (PR #3493).
2. For binary crun version, bump to latest 1.15.
```release-note
None
```
@giuseppe PTAL
> ci: bump crun to 0.15/HEAD

- test/ctr.bats
- test/drop_infra.bats
- test/image_volume.bats
- test/network.bats
- test/network_ping.bats
- test/restore.bats
- test/test_runner.sh
/kind bug
(I consider it a bug in CI that prevented userns testing)
Commit 92caff26d ("Added EnvVar to cri-o cli flags", May 29 2019)
changed some testing code to use CONTAINER_{U,G}ID_MAPPING
instead of {U,G}ID_MAPPING environment variables, but a place
in test/test_runner.sh was omitted. This, I guess, resulted
in not testing userns (at least partially -- there are tests that enable
it explicitly rather through a TEST_USERNS env var).
Next, commit b80c31b9cf ("Allow CRI-O to manage IPC and UTS namespaces",
Dec 16 2019) changed the option ManageNetworkNSLifecycle to
ManageNSLifecycle, and changed its default to be true. Since this
commit, it is now needed to disable the option to allow userns testing
(otherwise we get "cannot use UIDMappings with ManageNSLifecycle"
error).
This commit …
> test: do test user namespace

- test/ctr_userns.bats
- test/helpers.bash
- test/test_runner.sh
/kind cleanup
This workaround was added a long time ago and the feature
should supposedly be fixed by now.
Removing it, though, revealed a bug in crun that is being fixed
in containers/crun#531. Until the fix is available in a released crun
version, add another workaround.
None
None
```release-note
None
```
> test: rm disabling selinux from userns tests

- pinns/src/pinns.c
when creating a user namespace, make sure the user namespace is
created first and the right mappings are assigned.  Once that is done,
create the remaining namespaces so that they are owned by root in the
user namespace.
/kind bug
> /kind design
> /kind flake
we can use user namespaces and selinux with managed ns lifecycle
```release-note
NONE
```
> pinns: fix ownership for created namespaces

- pkg/config/config.go
- pkg/config/config_test.go
- server/container_create_linux.go
- server/sandbox_run_linux.go
- test/ctr_userns.bats
- test/restore.bats
- test/test_runner.sh
/kind feature
Allow using rootless/userns together with ManageNSLifecycle, which is especially useful in view of
> level=info msg="The manage-ns-lifecycle option is being deprecated, and will be unconditionally true in the future"
Fixes: #4327
Closes: #4331
Please review commit by commit.
```release-note
Allow using userns together with ManageNSLifecycle
```
> Allow userns with manage ns lifecycle

- docs/crio.conf.5.md
- internal/config/device/device.go
- internal/config/device/device_test.go
- internal/oci/oci.go
- pkg/annotations/annotations.go
- pkg/config/config.go
- pkg/config/template.go
- pkg/container/container.go
- pkg/container/device.go
- pkg/container/device_test.go
- server/container_create_linux.go
- test/ctr.bats
- test/devices.bats
- test/helpers.bash
/kind feature
> /kind flake
Before there was no way for a user to specify a device to be added to their containers.
The standard mechanism in k8s were clunky and didn't really work.
Instead, in the same way we allow userns to be specified with an annotation, add one such annotation for Devices.
Admins can restrict different runtime classes from this behavior with runtime classes.
also refactor devices tests to be all together in a separate file
```release-note
Add `io.kubernetes.cri-o.Devices` annotation to the list interpretable allowed annotations. Now, users can pass in devices they want added to their containers, but only if the runtime class is allowed to use the annotation.
```
> add Devices to allowed annotations structure

- contrib/test/integration/build/cri-tools.yml
- scripts/circle-setup
(this is not about failing-test; it's just I could not find any category which is closer to ci than this one)
Use cri-tools from git head for CI.
This is done so changes in cri-tools will be caught instantly
(as opposed to after a release).
Should help in finding bugs like the one fixed by https://github.com/kubernetes-sigs/cri-tools/pull/683
Note this should only be done for master cri-o branch.
None
```release-note
NONE
```
> ci: use cri-tools from git head

- tutorials/crictl.md
- tutorials/kubeadm.md
Signed-off-by: Markus Thömmes <markusthoemmes@me.com>
/kind cleanup
This PR fixes a few links to a document that is no longer there but crucial during initial setup of cri-o.
```release-note
None
```
> Fix links to installation documentation

- .circleci/config.yml
- .github/workflows/verify.yml
- .golangci.yml
- Makefile
/kind ci
This moves a few short and straightforward CI jobs
out of circleci pipeline and into github actions.
The motivation is circleci's parallelism limit, which appears
to be recently introduced. Because of that, jobs like integration
testing are often not started right away, since the jobs like
shfmt and shellcheck are run first.
The other benefit is now commits are annotated with warnings
from e.g. shellcheck. This is not done for all linters though.
Now, I can't demo the end result here in this repo, but
you can take a look at how it looks like here: https://github.com/kolyshkin/cri-o/pull/1
In particular, take a look at annotations in commits.
Below is detailed description, copy-pasted from commits.
1. circleci: rm build-test-binaries job
It looks like it is obsoleted by …
> CI: remove unused job, move some jobs to github-actions

- contrib/cni/README.md
Signed-off-by: Markus Thömmes <markusthoemmes@me.com>
This calls out explicitly how to install the example CNI configurations (and also actually call out that the user has to do something here).
In addition to that this adds a few missing full stops and slightly alters the wording around the CNI version used, as the tutorial is explicitly **not** using the version at master.
```release-note
None
```
> Make CNI setup instructions a bit more clear and fix nits

- scripts/circle-setup
/kind ci
scripts/circle-setup currently fails like this while trying to install
cri-tools:
> sudo make BINDIR=/usr/bin install
> make: go: Command not found
This is caused by https://github.com/kubernetes-sigs/cri-tools/pull/684.
Basically, it now tries to build binaries under sudo and it fails
because go binary is not in the $PATH.
To fix, use `sudo -E PATH=$PATH`.
While at it, drop `make binaries` as this is now redundant.
None
```release-note
NONE
```
> circleci: fix cri-tools install

- contrib/test/integration/e2e-features.yml
- contrib/test/integration/e2e.yml
/kind cleanup
TL;DR:
- filter out some flaky tests in e2e-features (less flakes in CI :tada:)
- remove some (obsoleted?) elements from the skip regex in e2e
- simplify adding tests to skip (improve maintainability :tada:)
1. contrib/test/int/e2e: rm obsoleted TODO
Commit 7d2bde110abe94242 (Dec 8 2017) adds the TODO item, and excludes
the "should.support.inline.execution.and.attach" test case.
Now, commit 54d1971c71f68 (Jun 24 2019) removes this test from the
exclude regexp, but forgots to remove the TODO.
2. contrib/test/int/e2e: rework skip regex
In its current form, it is very hard to read, maintain, or make any
sense out of.
Play with ansible/jinja a bit to enable much simpler way to list
the tests to skip.
The downside is we have to play some tricks to create a regular
expression:
1. …
> enable/disable some e2e tests; rm TODOs; rework regex

- internal/lib/sandbox/sandbox.go
- server/sandbox_run_linux.go
/kind bug
> /kind design
> /kind flake
If we create the network before we have an infra container, but fail to fully create a sandbox,
we attempt to clean up the network. Calling networkStop() causes CRI-O to place a file in the
sandbox's infra container's directory, thus allowing us to restore the fact that the network had been stopped
The problem is, we don't have a infra container directory, so the call segfaults.
Instead, check if the sandbox has finished creating before attempting to create the file. if it hasn't, there will be
no sandbox to restore, so we don't really need the temp file.
Another option would be to wire it so that the sandbox has access to the …
> network stop: don't segfault if sandbox isn't created yet

- .circleci/config.yml
- .github/workflows/verify.yml
- Makefile
/kind ci
Following the footsteps of #4373, let's move verify vendor job from circleci to github actions.
None
```release-note
None
```
> ci: move check vendor to github actions

- internal/lib/container_server.go
- internal/lib/sandbox/namespaces.go
- internal/lib/sandbox/sandbox.go
- internal/lib/sandbox/sandbox_test.go
- server/sandbox_run_linux.go
- server/sandbox_status.go
/kind cleanup
The fact that we re-use the protobuf devotions in the lower level
implementation details of CRI-O increases the burden to support multiple
Container Runtime Interface versions. This patch is one of a series of
patches to remove the protobuf type usage from the internal lib. This
allows us to create a middle layer later on to support two CRI versions
in parallel.
Required for https://github.com/cri-o/cri-o/pull/4372
We have to do that with every `pb.Type` we're using in CRI-O. This seems the only way to me to cleanly re-use the implementations without having a need for copy-pasting code around.
```release-note
None
```
> Make NamespaceOption an internal type in sandbox

- contrib/test/integration/e2e.yml
/kind ci
/kind flake
/release-note-none
This is failing a lot recently. There is an open issue [1],
but let's disable this one until the issue is fixed.
[1] https://github.com/kubernetes/kubernetes/issues/96565
> test/e2e: disable a flaky test

- internal/oci/oci.go
- internal/oci/oci_test.go
- internal/runtimehandlerhooks/high_performance_hooks.go
- internal/runtimehandlerhooks/runtime_handler_hooks.go
- pkg/annotations/annotations.go
- server/container_start.go
- server/container_stop.go
- server/sandbox_stop_linux.go
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
The current value of CPU load balancing, IRQ balancing, and CPU quota annotations is misleading.
To provide a better UX, we should rename it to reflect the real functionality that done when these annotations are specified under the pod.
```release-note
Provide an option to run performance hooks via specifying allowed_annotations under the runtime handler configuration
[DEPRECATION] The run of performance hooks for the high-performance runtime handler without specifying allowed_annotations will be deprecated under release 1.21
[DEPRECATION] Usage of performance annotation with the true …
```
> Provide a better value for features specific annotations

- server/cri/v1alpha2/api.go
- server/cri/v1alpha2/rpc_attach.go
- server/cri/v1alpha2/rpc_container_stats.go
- server/cri/v1alpha2/rpc_container_status.go
- server/cri/v1alpha2/rpc_create_container.go
- server/cri/v1alpha2/rpc_exec.go
- server/cri/v1alpha2/rpc_exec_sync.go
- server/cri/v1alpha2/rpc_image_fs_info.go
- server/cri/v1alpha2/rpc_image_status.go
- server/cri/v1alpha2/rpc_list_container_stats.go
- server/cri/v1alpha2/rpc_list_containers.go
- server/cri/v1alpha2/rpc_list_images.go
- server/cri/v1alpha2/rpc_list_pod_sandbox.go
- server/cri/v1alpha2/rpc_pod_sandbox_status.go
- server/cri/v1alpha2/rpc_port_forward.go
- server/cri/v1alpha2/rpc_pull_image.go
- server/cri/v1alpha2/rpc_remove_container.go
- server/cri/v1alpha2/rpc_remove_image.go
- server/cri/v1alpha2/rpc_remove_pod_sandbox.go
- server/cri/v1alpha2/rpc_reopen_container_log.go
- server/cri/v1alpha2/rpc_run_pod_sandbox.go
- server/cri/v1alpha2/rpc_start_container.go
- server/cri/v1alpha2/rpc_status.go
- server/cri/v1alpha2/rpc_stop_container.go
- server/cri/v1alpha2/rpc_stop_pod_sandbox.go
- server/cri/v1alpha2/rpc_update_container_resources.go
- server/cri/v1alpha2/rpc_update_runtime_config.go
- server/cri/v1alpha2/rpc_version.go
To be able to support v1alpha2 as well as the new v1 CRI API we would
have to decouple the server from the protobuf API. This patch is the
first step in adding a clean interface around the v1alpha2 API.
None
None
```release-note
None
```
> Add clean v1alpha2 CRI API interface

- Makefile
/kind ci
This fixes the intentionally unset `GOSUMDB` variable when running `make
vendor`.
None
None
```release-note
None
```
> Fix make vendor GOSUMDB

- server/container_create.go
- server/sandbox_run_linux.go
/kind cleanup
> /kind design
> /kind flake
it doesn't make very much sense to have so many deferred funcs queued, and check retErr each time
instead, we can check retErr once, and loop through a slice of cleanupFuncs
this also carries https://github.com/cri-o/cri-o/pull/4240 to avoid a merge conflict
```release-note
none
```
> server: refactor handling of cleanup funcs

- server/cri/types/types.go
/kind feature
The added types will be later on used by the `server` package to not
rely on the external protobuf types any more. This enables us to
decouple the implementation from the types and support two CRI versions
side by side.
None
None
```release-note
None
```
> Add CRI glue types for v1alpha2 and v1 usage

- internal/lib/container_server.go
- internal/lib/container_server_test.go
- internal/lib/rename.go
- internal/lib/sandbox/history_test.go
- internal/lib/sandbox/namespaces_test.go
- internal/lib/sandbox/sandbox.go
- internal/lib/sandbox/sandbox_test.go
- internal/lib/sandbox/suite_test.go
- internal/lib/suite_test.go
- internal/oci/container.go
- internal/oci/container_test.go
- internal/oci/suite_test.go
- internal/runtimehandlerhooks/high_performance_hooks_test.go
- pkg/container/container_test.go
- server/container_create_linux.go
- server/container_list.go
- server/container_stats.go
- server/container_status.go
- server/inspect_test.go
- server/sandbox_list.go
- server/sandbox_run_linux.go
- server/sandbox_status.go
- server/suite_test.go
/kind cleanup
To be able to switch to a different protocol we have to use our own
`Metadata` type definitions for sandboxes and containers.
Follow-up of https://github.com/cri-o/cri-o/pull/4386
Required for #4372
None
```release-note
None
```
> Use own metadata types

- pkg/container/container.go
/kind bug
Some OCI hooks like the oci-seccomp-bpf-hook may re-use the sandbox
annotations which would get lost before applying this patch. This means
we now preserve all sandbox annotations for containers and overwrite
specific values during setup.
None
None
```release-note
- Fixed bug that all custom sandbox annotations will be passed to OCI hooks and therefore are also available on the containers
```
> Preserve sandbox annotations for handling OCI hooks

- test/ctr.bats
/kind ci
/kind flake
This test case is sometimes fails like this:
> not ok 40 ctr execsync
>  (in test file ./ctr.bats, line 429)
>    `[[ "$output" == *"command timed out"* ]]' failed
> .....
>  time="2020-12-02T23:28:58Z" level=fatal msg="connect: connect endpoint 'unix:///tmp/tmp.ncaFI2tZzn/crio.sock', make sure you are running as root and the endpoint has been started: context deadline exceeded"
This happens because our CI might be slow and this 1 second timeout
also applies to connect.
Increase the timeout and the sleep accordingly to fix the flake.
(seen in https://github.com/cri-o/cri-o/pull/4377#issuecomment-740206506)
None
None
```release-note
None
```
> test/ctr.bats: fix a "ctr execsync" flake

- completions/bash/crio
- completions/bash/crio-status
- completions/zsh/_crio
- completions/zsh/_crio-status
Give the completion functions different names for crio and crio-status, fix the single quote in crio completion function.
Signed-off-by: Grammy Jiang <grammy.jiang@gmail.com>
Sorry, I am not familiar with fish completion functions, so I only fix bash and zsh.
bug
> /kind ci
> /kind design
> /kind flake
> /kind other
The completion functions' names are identical between `crio` and `crio-status`, this will ruin each other when both of them are enabled.
The single quote are not escaped in `crio` completion function, which will cause syntax error:
* [cri-o/_crio at release-1.20 · cri-o/cri-o](https://github.com/cri-o/cri-o/blob/release-1.20/completions/zsh …
> Fix the functions' name in completions

- crictl.yaml
- test/ctr.bats
- test/helpers.bash
/kind ci
/kind flake
This builds on #4311.
crictl 1.19 added these options in https://github.com/kubernetes-sigs/cri-tools/pull/627
First, set no-pull-on-run, which should eliminate flakes like this one:
> `ctr_id=$(crictl run "$TESTDIR"/container_pids_limit.json "$TESTDATA"/sandbox_config.json)' failed
> time="2020-11-18T05:02:01Z" level=fatal msg="running container: creating container failed: rpc error: code = Unknown desc = Error reading blob sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4: Get \"https://cdn02.quay.io/sharedimages/86f0a285-6f29-47c4-a3ae-7e2c70cad0ba/layer?Expires=1605676304&Signature=N976UlLi1Hb~jhKGQAy8JcmhlqFPdTzI3I3WiR7iEmb-x1YaIA6cWgWB3DffhwlaOrkzwHU8bAuWUEcwbD1N4tx3tAy7rhfQSyqWzbrs-OZJGON9aH7C5PkoqYPFDwGxQ1dzxtLSFR-hx1FmyN1lIuzFUKRmiQlPZPj1 …
> test: add no-pull-on-run; fix no pull on create

- awesome.md
Signed-off-by: timyinshi <shiguangyin@inspur.com>
/kind bug
the podctl's url is error
https://podctl.com/an-introduction-to-cri-o
the right url is https://podctl.buzzsprout.com/110399/585611-an-introduction-to-cri-o
```release-note
none
```
> modify the error url of podctl

- internal/config/node/node.go
- internal/config/node/systemd.go
- pkg/config/config.go
- server/container_create_linux.go
- server/sandbox_run_linux.go
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
This commit introduces a bare bones internal/config/node package to support this feature.
Not cleaning failed scopes can cause mounts to fail, this piece of functionality is definitely a bug.
The rest of the internal/config/node package is not fixing a bug, so it's excluded.
currently, systemd leaks some scopes if they're failed.
This can be changed with the CollectMode annotation (which runc will set).
However, only systemd version >= 236 has support for this, so we need a new entry in internal/config/node to check whether systemd is the correct version
Signed-off-by: Peter Hunt …
> [1.18] set inactive-or-failed CollectMode if appropriate

- contrib/test/integration/build/parallel.yml
/kind ci
When running the contrib/test/integration main playbook on CentOS, the parallel installation fails as there is no packaged version of parallel in CentOS 7 nor in CentOS 8.
I guess we should build it as we do for RHEL.
Moreover, the build process ends adding a symbolic link to the just compiled parallel binary: if we don't force the link creation (-f) the operation will fail if the playbook runs twice.
None
Wondering if I'm missing an extra repo that we usually add here and that provides the parallel package for CentOS
```release-note
None
```
> contrib/test/integration: parallel build process in CentOS

- contrib/test/integration/build/cri-o.yml
- contrib/test/integration/build/kata.yml
- contrib/test/integration/main.yml
- contrib/test/integration/test.yml
- contrib/test/integration/vars.yml
/kind ci
This PR introduces support to Kata Containers  runtime in the contrib/test/integration playbook to allow to run integration tests via ansible. A new boolean environment variable has been added (build_kata). When set to true, Kata Container packages are installed and the environment configured to use Kata as the default runtime (shimv2 binary).
Only a small subset of the integration tests are run: many are not working with Kata Containers yet.
Targeted distributions are Fedora and CentOS.
None
This PR aims to bring initial support to Kata Containers. The set of integration tests run is small, but tested to pass on CentOS 7 and Fedora 32/33. More integration tests may be later added and Kata Containers packages may be updated as newer stable versions are released.
```release-note …
```
> Add initial Kata Containers support to contrib/test/integration playbook

- server/cri/v1/rpc_version.go
- server/cri/v1alpha2/rpc_version.go
- server/version.go
- server/version_test.go
/kind feature
To be able to distinguish the chosen CRI API version, we now return the
runtime API version based on the RPC code path.
None
The CRI protocol mentioned that the version has to be semver compatible:
https://github.com/kubernetes/cri-api/blob/3094f92ca2a23915931d9345285a6721be06cf62/pkg/apis/runtime/v1alpha2/api.proto#L143-L145
Before this patch we had returned `v1alpha1`, which is neither the current CRI API version nor semver compatible. Any thought on that?
```release-note
- Changed `VersionResponse.RuntimeApiVersion` to return either the `v1alpha2` or `v1` CRI API version
```
> Return runtime API version based on protocol

- docs/crio.conf.5.md
- pkg/config/config.go
The `registries` option will be removed from CRI-O 1.21.  To better
communicate this upcoming change to users, add a deprecation warning
when loading a config and another to the man page.
@haircommander forced me to.
```release-note
The `registries` option from crio.conf(5) has been deprecated in favour of using containers-registries.conf(5) for configuring unqualified-search registries.  The `registries` option will be removed from CRI-O 1.21.
```
> add `regitries` deprecation notice

- server/utils.go
Bandwidht CNI plugin reserved an upper limit on burst,in which banned include boundary.  
See: https://github.com/containernetworking/plugins/blob/v0.8.7/plugins/meta/bandwidth/main.go#L113. 
Signed-off-by: Zizon Qiu <zzdtsv@gmail.com>
> 
/kind bug
> /kind design
> /kind flake
bandwidth CNI plugin use equality compare, which prevents the exactly 4GB setting. 
make it slightly below 4GB.
A better approach maybe introduc new annotation for burst but would still need to under this value to let default behavior go.
```release-note
Ingress/Egress burst limit is now set slightly below 4GB, which properly sets 4GB as the upper limit of burst
```
> Make Ingress/Egress Burst upper limit slightly under 4GB

- internal/lib/container_server.go
- server/container_attach.go
- server/container_exec.go
- server/container_reopen_log.go
- server/container_update_resources.go
- server/container_update_resources_test.go
- server/sandbox_remove.go
- server/sandbox_stop_linux.go
> /kind bug
> /kind ci
/kind cleanup
> /kind design
> /kind flake
> /kind other
this replaces unneeded State() and UpdateContainerResources() calls,
which both saves on lock contention, as well as possibly saves on a call to `runc state`
replaces https://github.com/cri-o/cri-o/pull/3864
```release-note
none
```
> server: use IsAlive() more

- internal/config/seccomp/seccomp.go
- internal/oci/runtime_oci.go
- server/server.go
- server/utils.go
- test/docs-validation/main.go
- utils/utils.go
/kind cleanup
The error message will already indicate which file is affected by the
failure. This way we do not have to need to log the filename multiple
times to lower the logging noise.
None
None
```release-note
None
```
> Do not log file path on ioutil.ReadFile

- Makefile
/kind bug
We have to export the `BINDIR` variable, otherwise it will not be
picked-up by the script.
None
cc @kolyshkin 
```release-note
None
```
> Fix `make lint`

- internal/oci/runtime_vm.go
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
or else we get garbage in the reported output
```release-note
Fix a bug where containers didn't have a finished time set when using the "vm" style runtimes.
```
> runtime_vm: set finished time when containers stop

- pkg/config/config_test.go
- pkg/config/suite_test.go
The storage retrieval does not work without providing an UID map in
rootless mode. To avoid adding such non-used options we now exclude
those tests if they run in rootless mode.
Beside that, the conmon path might be different than the hard coded
within the test. This means we now lookup the path during test
execution to make the tests more robust.
None
None
```release-note
None
```
> Make config tests work rootless

- internal/oci/oci.go
- internal/oci/oci_linux.go
- server/container_create.go
- server/container_create_linux.go
- server/sandbox_run_linux.go
- test/stats.bats
/kind bug
this involves some reworking of where we save the scopePrefix (now renamed CrioScopePrefix and marked public in oci)
cherry pick of https://github.com/cri-o/cri-o/pull/3933
```release-note
fixed a bug where crictl only showed pod level stats, not container level stats.
```
> [1.18] stats: return information on container level, not pod

- internal/config/nsmgr/nsmgr.go
- internal/config/nsmgr/types.go
- pinns/src/pinns.c
- server/sandbox_run_linux.go
> /kind bug
> /kind ci
> /kind design
/kind feature
> /kind flake
> /kind other
When we manage NS lifecycle, we currently do nothing for host level namespaces, instead using the /proc/ entry of the infra container for the location of that namespace.
The problem is, when we drop infra, there's no pid to use in the /proc/ entry, so we don't know where the namespace is.
This means, when we drop the infra container, we actually can't use port_forward on pods that use the host network... oops.
This PR, among many other things, updates pinns to support binding the location of the namespace, but not unsharing, thus binding the location of the host namespace.
replaces …
> update pinns to support pinning host level namespaces

- .circleci/config.yml
- .github/workflows/test.yml
- contrib/bundle/Makefile
- contrib/bundle/build
/kind feature
This moves the whole static build pipeline from CircleCI to GitHub
actions, except the integration tests. The integration tests will follow
at some later point, if other integration tests are available and the
overall test strategy is clear.
Refers to #4489 
None
```release-note
- Added `crio-status.8` man page to static release bundle
```
> Move static build to GitHub actions

- .github/workflows/verify.yml
/kind ci
Some name fields are duplicate because GitHub actions already names the
job based on its identifier. Beside that, it's easier to not name single
line bash jobs because then we can see the actual invocation better in
the UI.
None
None
```release-note
None
```
> Remove implicit GitHub action `name` fields

- internal/resourcestore/resourcestore.go
- internal/resourcestore/resourcestore_test.go
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
There is a chance that a WatcherForResource() followed by a Get() would cause cri-o to segfault. Fix this
also extend the test suite to add a test for this and another situation, as well as move around the tests so they're all run
cherry-pick of https://github.com/cri-o/cri-o/pull/4530
```release-note
fixed a bug that could cause CRI-O to segfault when a node is under heavy load
```
> [1.20] ResourceStore: fix segfault and update tests

- internal/config/nsmgr/types.go
- internal/lib/sandbox/namespaces.go
- internal/lib/sandbox/namespaces_linux.go
- internal/lib/sandbox/namespaces_test.go
- pkg/config/config.go
- server/sandbox_run_linux.go
- test/mocks/sandbox/sandbox.go
as well as remove any file that exists in that spot
as well as create nsmgr package to mirror release-1.21 structure (only holding the NSType right now)
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
as well as remove any file that exists in that spot
and introduce a skeleton of nsmgr package. We'd have to introduce a new package regardless (if we wanted to keep NSType and SupportedNamespacsForPinning() together) as we get a cyclical import importing sandbox from the config
pick of https://github.com/cri-o/cri-o/pull/4532
```release-note
none
```
> [1.20] config: pre-create pinns directories

- pkg/container/container.go
- server/sandbox_run_linux.go
/kind bug
This PR sets the systemd KillMode for container scopes to mixed
so on stop, only the main process gets the SIGTERM and is 
responsible for forwarding it if needed to child processes.
Without this, we end up with double SIGTERMS leading to unexpected
failures in graceful termination on node shutdown or reboot.
https://bugzilla.redhat.com/show_bug.cgi?id=1882750
```release-note
Set systemd KillMode to mixed for container scopes modifying behavior on node shutdown
```
> [1.20] Set systemd property KillMode to mixed for containers

- contrib/test/integration/build/kubernetes.yml
The test ` validates that there is no conflict between pods with same hostPort but different hostIP and protocol [LinuxOnly] [Conformance]` creates two pods with the same hostPort but different NodeIPs.
It assumes that the Node has an IP that is not 127.0.0.1, so it tries to use HostIP=NodeIP and HostIP=127.0.0.1.
However, CRI-O CI has the kubelet nodeIP set to 127.0.0.1, hence the test tries to schedule 2 pods with the same hostport and hostIP in the same node, and it fails as expected.
We can configure the kubelet with the nodeip of the host where it is running, so it is more realistic, since Kubernetes nodes can't not use loopbacks as InternalIP, well, the can, but nobody will be able to communicate with them :)
```release-note
NONE
```
> set kubelet node IP

- docs/crio.conf.5.md
- go.mod
- go.sum
- internal/oci/oci.go
- pkg/annotations/annotations.go
- pkg/config/config.go
- pkg/config/template.go
- pkg/container/container.go
- pkg/container/container_test.go
- server/container_create_linux.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/state.go
- vendor/github.com/opencontainers/runtime-tools/generate/generate.go
- vendor/modules.txt
/kind feature
allow to override the cgroup v2 unified configuration through a custom annotation.  Multiple values are separed with `;`.
Each value can be specified in the base64 format.  If it is not a valid base64 encoded string, then its original value is used.
The container is specified as part of the annotation name.
```
apiVersion: v1
kind: Pod
metadata:
name: unified-test
annotations:
io.kubernetes.cri-o.UnifiedCgroup.cgroup-test: "memory.high=8000000;memory.low=100000"
spec:
containers:
- name: cgroup-test
image: docker.io/alpine
command: ["top"]
```
None
```release-note
it is possible to override cgroup v2 unified configuration through the io.kubernetes.cri-o.UnifiedCgroup.$CTR_NAME annotation
```
> server: support setting raw unified cgroupv2 settings

- internal/hostport/hostport_manager.go
The host port manager, when Remove the hostport from the system, exists fast if there are no
iptables rules to delete.
However, it was missing to call the method that remove the hostports bound, so there is a possibility that we leak sockets.
Signed-off-by: Antonio Ojea <aojea@redhat.com>
Thanks to @johnbelamaric 
https://github.com/kubernetes/kubernetes/pull/98755#discussion_r570413563
> /kind bug
```release-note
NONE
```
> hostport manager clean up host ports

- internal/config/node/cgroups.go
CRI-O assumed that the swap memcg is always present on cgroup v2 but
that is not always true as a kernel can be compiled without
CONFIG_SWAP or CONFIG_MEMCG_SWAP.
Implement the swap memcg check by looking into the current cgroup if
the memory.swap.current is present.  Now the assumption is that the
"memory" controller is enabled in the current cgroup.
Closes: https://github.com/containers/crun/issues/570
/kind feature
None
```release-note
None
```
> cgroup: implement fix for swap memcg on cgroup v2

- .circleci/config.yml
- .github/workflows/test.yml
/kind ci
We now use GitHub actions for the unit test execution instead of
CircleCi. We also separate the pipeline into the three steps of mock
verification, unit test execution and coverage upload.
Refers to #4489 
None
```release-note
None
```
> Move unit tests to GitHub actions

- .circleci/config.yml
- .github/workflows/test.yml
/kind ci
This patch moves the CircleCI go1.14 and 386 architecture build into GitHub actions.
Refers to #4489
/hold requires https://github.com/cri-o/cri-o/pull/4510 to be merged first
```release-note
None
```
> Move go1.14 and 386 builds to GitHub actions

- pinns/src/pinns.c
- pinns/src/utils.h
/kind bug
Pinns had some minor quirks in its output that I fixed while I was poking around to enhance it to pin mount namespaces (that PR is coming soon). This just fixes up some error messages so they're a bit more consistent.
None
```release-note
None
```
(Minor cosmetic changes to the output of the internal 'pinns' utility only)
> Pinns minor cleanup

- server/container_update_resources.go
if the memory swap limit is not supported by cgroup, leave the value
unset instead of forcing it to 0.
/kind bug
if swap memcg is not supported, leave the value unset instead of setting it to 0
None
```release-note
None
```
> server: leave swap mem limit unset if not supported

- server/container_stop.go
/kind cleanup
Logs the container stop timeout so it is always visible at the info level.
None
```release-note
Log the container stop timeout at default log level
```
> [1.20] Log container stop timeout

- .github/workflows/test.yml
Two fixes are part of this patch:
- Fixing the fetch depth to contain the full history of the repository.
This allows to checkout branches like `gh-pages`.
- Adding the access token to the checkout to be able to make repository
modifications within the CI.
Refers to #4489 
None
```release-note
None
```
> Fix GitHub actions checkout permissions

- internal/config/node/systemd.go
shout out to Kir (@kolyshkin) for coming up with this method
Drastically simplify querying systemd for CollectMode.
This is more resistant to the feature being backported into the version shipped in distros.
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
```release-note
Fix a bug where CollectMode wouldn't be set if the feature was backported to systemd (in RHEL/CentOS 7, for instance)
```
> config/node: refactor checking for CollectMode

- .github/workflows/test.yml
Both actions will access the `gh-pages` branch which can result in a
race. To fix this issue we now make both jobs dependent on each other.
None
None
```release-note
None
```
> Run release-notes GitHub action after dependencies

- internal/resourcestore/resourcestore.go
- internal/resourcestore/resourcestore_test.go
- server/server.go
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
There is a chance that a WatcherForResource() followed by a Get() would cause cri-o to segfault. Fix this
also extend the test suite to add a test for this and another situation, as well as move around the tests so they're all run
```release-note
fixed a bug that could cause CRI-O to segfault when a node is under heavy load
```
> ResourceStore: fix segfault and update tests

- server/container_create_linux.go
even when running as privileged container, prevent cgroup mounts to be
propagated to the host as it could cause errors when running with
rshared and systemd inside of the container.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1903553
/kind bug
fixes https://bugzilla.redhat.com/show_bug.cgi?id=1903553
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1903553
```release-note
Fix running privileged systemd containers with bidirectional mounts
```
> server: mount cgroup with rslave

- pkg/config/config.go
the directory is at `$namespaceDir/$ns"ns"` not `$namespaceDir/$ns`
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
```release-note
none
```
> [1.20] config: remove and create the correct dir

- internal/oci/oci.go
- internal/oci/oci_test.go
- pkg/annotations/annotations.go
- pkg/config/config.go
- pkg/config/template.go
- pkg/container/container.go
- server/sandbox_run_linux.go
/kind feature
This change allows us to trace different containers into dedicated
files. For example the workload:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: test
spec:
selector:
matchLabels:
app: test
replicas: 1
template:
metadata:
labels:
app: test
annotations:
io.containers.trace-syscall/nginx: of:/tmp/nginx.json
io.containers.trace-syscall/redis: of:/tmp/redis.json
spec:
containers:
- name: nginx
image: nginx:latest
- name: redis
image: redis:latest
```
Will now create two separate files containing only the syscalls from
each workload.
Fixes https://github.com/containers/oci-seccomp-bpf-hook/issues/74
None
```release-note
Added feature to allow the OCI seccomp BPF hook to trace containers into dedicated files by
using the annotation key …
```
> Allow seccomp hook tracing for separate containers

- internal/lib/container_server.go
- server/container_update_resources.go
It is better to skip sending the values, instead of sending 0s.
crun will try to enforce a memory.Limit=0, making the contianer OOM.
We can also do the same as containerd to copy old spec and update the values, but I think
this is better.
> /kind bug
```release-note
Fix OOMs when using crun together with CPU Manager
```
> Fix oci container update config

- server/image_pull.go
/kind bug
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1881694
This BZ needs change the log level of the image pull location from the debug to info.
Crio could use SystemContext.DockerLogPullSource to log the physical image source if it's from a mirror.
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1881694
```release-note
Crio adds info level log of the physical image source.
```
> [release-1.20] Bug 1881694 Add pull source as info level log

- .github/workflows/test.yml
The current CI is broken because GitHub reports that the workflow is invalid:
https://github.com/cri-o/cri-o/actions/runs/600281951
```
The workflow is not valid.
.github/workflows/test.yml (Line: 235, Col: 9): Unexpected symbol: '"refs/heads/release"'.
Located at position 59 within expression: github.ref == 'refs/heads/master' || contains(github.ref, "refs/heads/release")
```
Follow-up of https://github.com/cri-o/cri-o/pull/4601
None
```release-note
None
```
> Fix GitHub actions workflow syntax

- .github/workflows/test.yml
- Makefile
- README.md
- contrib/bundle/10-crun.conf
- contrib/bundle/Makefile
- contrib/bundle/build
- contrib/bundle/test
- contrib/bundle/vars
- install.md
- nix/default-arm64.nix
- scripts/get
- scripts/release-notes/release_notes.go
- scripts/upload-artifacts
- scripts/versions
/kind feature
This adds a new derivation to build statically linked binaries for
arm64.
Refers to https://github.com/cri-o/cri-o/issues/4551
None
```release-note
Added arm64 variant to static binary bundle. The bundle is now available via the URL
`https://storage.googleapis.com/k8s-conform-cri-o/artifacts/cri-o.$ARCH.$VERSION.tar.gz`,
where `$ARCH` can be `amd64` or `arm64` and `$VERSION` a tag or full length git SHA.
Beside that, we provide a new installation script
`curl https://raw.githubusercontent.com/cri-o/cri-o/master/scripts/get | bash`.
For this script, it is also possible to pass the architecture and version as arguments:
`get [amd64|arm64] [VERSION|SHA]`.
The static binary bundle now uses crun as default container runtime for CRI-O.
```
> Add arm64 static build to GitHub actions and bundle

- tutorials/kubeadm.md
The `yq` command in the script is no longer valid with `yq` v4 which is backwards incompatible with v3. This change updates the script to work with `yq` v4
Updates script to run with new v4 version of `yq`
Fixes #4599
```release-note
none
```
> Updates yq commnands for yq v4

- scripts/get
/kind bug
The parameter query does not seem to be correct so we now rely on plain
extraction via `jq`. This seems more robust and future proof.
Fixes https://github.com/cri-o/cri-o/issues/4608
None
```release-note
None
```
> Fix `get` script commit SHA retrieval

- contrib/systemd/crio.service
- contrib/test/ci/crio.service
> /kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
on top of making logical sense (kubelet can't do anything without crio running), this also avoids odd situations
where the kubelet can't register an imagefs without crio being up first
```release-note
The installed cri-o.service file now attempts to be run before kubelet.service
```
> crio.service: Request to be run before kubelet.service

- server/container_create_linux.go
This is a cherry-pick of #4575
```release-note
Fix running privileged systemd containers with bidirectional mounts
```
> [1.18] server: mount cgroup with rslave

- server/container_create_linux.go
This is a cherry-pick of #4575
```release-note
Fix running privileged systemd containers with bidirectional mounts
```
> [1.19] server: mount cgroup with rslave

- .github/workflows/verify.yml
- .golangci.yml
- Makefile
- utils/utils_test.go
This also fixes a new gofumpt issue as well as enabling linters which do
not report any further errors.
None
None
```release-note
None
```
> Bump golangci-lint to v1.35.2

- crictl.yaml
/kind other
This change removes the `image-endpoint:` line from the `crictl.yaml`
file in this repository which gets bundled into the cri-o RPMs. Doing so
ensures that as long as cri-o uses the same path for the runtime and
image RPC endpoints, a user can do the naive thing and execute
`crictl --runtime-endpoint /somewhere/else [command]`, assuming thatthe
path to the alternate runtime's RPC will be used as the image endpoint
for that command too.
Fixes #4607
```release-note
None
```
> fix: Don't set `image-endpoint` in crictl config

- internal/oci/container.go
- internal/oci/oci_unix.go
- internal/oci/runtime_oci.go
- internal/oci/runtime_oci_test.go
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
oci: don't wait too long on a long stop
if a long stop timeout comes in, and a shorter one comes in after
we never interrupt the old one. This can cause the new container stop to be DOSed
instead, interrupt the old stop, so the new one can proceed as expected
This PR is https://github.com/cri-o/cri-o/pull/4548 plus a couple of usability tweaks and unit tests
```release-note
none
```
> oci: don't wait too long on a long stop
