test/ctr.bats
/kind cleanup
This adds an integration test to verify the container start/finished time.
None
None
```release-note
None
```
=> Add integration test for started/finished container time

internal/config/node/node.go, internal/config/node/systemd.go, pkg/config/config.go, server/container_create_linux.go, server/sandbox_run_linux.go
This commit introduces a bare bones internal/config/node package to support this feature.
Not cleaning failed scopes can cause mounts to fail, this piece of functionality is definitely a bug.
The rest of the internal/config/node package is not fixing a bug, so it's excluded.
currently, systemd leaks some scopes if they're failed.
This can be changed with the CollectMode annotation (which runc will set).
However, only systemd version >= 236 has support for this, so we need a new entry in internal/config/node to check whether systemd is the correct version
/kind bug
> /kind ci
> /kind design
> /kind flake
> …
=> [1.17] set inactive-or-failed CollectMode if appropriate

test/README.md, test/config.bats, test/devices.bats, test/drop_infra.bats, test/helpers.bash, test/restore.bats, test/shm_size.bats, test/timeout.bats
/kind cleanup
As well as update documentation describing how to specify an alternative runtime
And fix some inconsistencies in how the runtime is called in restore.bats
replaces https://github.com/cri-o/cri-o/pull/4099
```release-note
none
```
=> test: reconfigure how runtimes are passed in

internal/config/seccomp/seccomp.go, internal/config/seccomp/seccomp_test.go, server/container_create.go, server/container_create_linux.go, server/cri/types/types.go, server/cri/v1/rpc_create_container.go, server/cri/v1/rpc_pull_image.go, server/cri/v1/rpc_run_pod_sandbox.go, server/cri/v1alpha2/rpc_create_container.go, server/cri/v1alpha2/rpc_pull_image.go, server/cri/v1alpha2/rpc_run_pod_sandbox.go, server/sandbox_run_linux.go, test/ctr_seccomp.bats
/kind feature
We now add support for seccomp security profiles within the CRI. We still support the deprecated code paths until the field is not available any more.
AppArmor support will follow later on.
None
None
```release-note
Support Container Runtime Interface (CRI) security profiles for seccomp, which has been introduced with Kubernetes v1.20.0 and the graduation of the CRI.
```
=> Support CRI seccomp security profiles

internal/oci/oci.go, internal/oci/runtime_vm.go
/kind cleanup
Instead of hardcoding the directory for the Global FIFOs on
`/tmp/crio/fifo", let's at least put that inside the
`runtime_root`/crio/fifo, which is defined by the admin.
None
```release-note
None
```
=> runtime_vm: Create the global fifo inside the runtime root path

server/image_pull.go
This BZ needs change the log level of the image pull location from the debug to info.
Crio could use SystemContext.DockerLogPullSource to log the image source if it's from a mirror.
This PR should work with PR https://github.com/containers/image/pull/1099
/kind bug
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1881694
```release-note
Crio adds info level log of the physical image source.
```
=> Bug 1881694: Add pull source as info level log

scripts/get
/kind bug
It may be possible that we do not find a result on the first page. This
means we do now add paging support to the search for a successful GitHub
actions run.
None
None
```release-note
None
```
=> Add GitHub API pages support to `get` script

scripts/github-actions-packages
Fix unit tests by adding libbtrfs-dev to be installed.
Signed-off-by: Ryan Phillips <rphillips@redhat.com>
/kind ci
```release-note
NONE
```
=> add libbtrfs-dev to unit tests

internal/oci/runtime_vm.go
The latest merges caused an lint issue which seems to make the master
branch failing:
```
internal/oci/runtime_vm.go:55:1: paramTypeCombine: func(path string, root string) RuntimeImpl could be replaced with func(path, root string) RuntimeImpl (gocritic)
func newRuntimeVM(path string, root string) RuntimeImpl {
^
```
None
None
```release-note
None
```
=> Fix lint GitHub action

scripts/get, scripts/upload-artifacts
/kind feature
This allows us to not rely on the GitHub API any more when querying the
latest master version bundle for CRI-O. We still use the GitHub API
approach as fallback, which should make the `get` script more fail-safe.
The version marker gets updated for each branch (master and release branches) within a file like this:
https://console.cloud.google.com/storage/browser/_details/k8s-conform-cri-o/latest-master.txt
None
None
```release-note
None
```
=> Use and publish version marker for CRI-O

.github/workflows/integration.yml, .github/workflows/test.yml, .github/workflows/verify.yml
/kind ci
We have to run the actions on all release branches, too.
Cherry-picked: 128151e82620095352d6a0a4f075c3294564ae35
Signed-off-by: Sascha Grunert <sgrunert@redhat.com>
None
Refers to https://github.com/cri-o/cri-o/pull/4665
```release-note
None
```
=> [1.20] Run GitHub actions on release branches

internal/oci/stats.go, server/container_stats_list.go
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
Because we don't lock in stats collection (to keep it speedy), we run into
races with other routines deleting stuff from underneath us.
As such, we should be wary to print errors in these expected situations.
Instead, ignore or reduce the log level for some common errors that are not really worth reporting.
```release-note
none
```
=> stats: fix log spam

internal/config/cgmgr/cgmgr.go, internal/config/cgmgr/cgroupfs.go, internal/config/cgmgr/systemd.go, internal/lib/container_server.go, internal/oci/container.go, internal/oci/container_test.go, server/inspect.go, server/sandbox_run_linux.go, test/inspect.bats
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
.. that's a mouthful!
When we drop the infra container, there's no PID associated with the pod. This is fine, unless cAdvisor is trying to find the network stats for the pod, as it uses the PID to parse `/proc/$pid/net/dev`, and skips for a PID that is 0.
Luckily, containers in the pod share the pod's network namespace. We can find the first running container in the pod, return that PID, and cAdvisor will parse the correct dev file
```release-note
When dropping the infra container, the container inspect endpoint now returns a PID when requesting the infra container. 
```
=> inspect: use first container when reporting pid of a pod with no infra

server/container_stop.go
/kind cleanup
Logs the container stop timeout so it is always visible at the info level.
None
```release-note
Log the container stop timeout at default log level
```
=> Log container stop timeout

README.md, cri.md, server/image_list.go, server/image_list_test.go
/kind feature
We now plainly use the `RepoTags` and `RepoDigests` from the returned
image result, with one exception: If there is a previous image name
available, then we use it together with the `Digest` to let tools like
`crictl` be able to display them together with the `<none>` placeholder.
Follow-up of https://github.com/cri-o/cri-o/pull/4662
@mtrmac please take a look
```release-note
CRI-O does not return `<none>` placeholders for missing tags and digests any more when doing a `ListImages` RPC
```
=> Do not return `<none>` placeholders for images any more

pkg/container/container.go
I'm debugging an issue with the Kube API server not shutting down fully on a reboot. I'm not seeing the scope being terminated since DefaultDependencies is disabled. This PR enables the DefaultDependency as documented in the systemd [documentation](https://github.com/systemd/systemd/blob/fee6441601c979165ebcbb35472036439f8dad5f/man/systemd.scope.xml#L70-L85).
/kind bug
```release-note
cri-o managed scopes now depend on the shutdown.target and network.target to allow graceful shutdowns.
```
=> fix default dependencies on container scopes to fix graceful shutdowns

pkg/config/config.go, pkg/config/config_test.go
/kind bug
CRI-O is too strict by simply not starting up in case a **non** default runtime is misconfigured.
Fixes: #4621
I need to get to writing tests to it, but I wasn't successful on a  quick try. :-/
```release-note
Instead of failing to start, CRI-O now only prints a warning and ignores the runtime, in case a **non** default runtime is misconfigured.
```
=> config: Don't fail if the non default runtime doesn't pass validation

internal/oci/oci.go, internal/oci/oci_test.go, internal/oci/runtime_vm.go, pkg/config/config.go, pkg/config/config_test.go
/kind bug
shim v2 expected the runtime name to be in the following format:
```
($dir.)?$prefix.$name.$version
-------- ------ ----- ---------
|     |     |      |
v     |     |      |
"/usr/local/bin"    |      |
(optional)  |     |      |
v     |      |
"containerd.shim."  |
|      |
v      |
"kata-qemu" |
v
"v2"
```
The current code simply replaces all the "-" by ".", which ends up
working well as long as the $name doesn't have a "-" in it, which is, by
luck, what's done by the Kata Operator.  However, whenever a name has
"-" in it, which we can see happening on upstream kata-deploy - which
uses $name as kata-qemu, for instance - it'll simply make containerd
library confused, not being able to invoke the binary.
With everything said above in mind, let's introduce a specialized
function …
=> runtimeVM: Fix shimv2 binary name construction

cmd/crio/wipe.go, test/crio-wipe.bats, test/helpers.bash
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
We created the CleanShutdownFile to work around issues where nodes didn't have time
to sync changes to disk before rebooting. This caused an unclean reboot.
However, for this to be relevant, the node had to actually reboot. If it didn't,
we could fail to remove the storage because the containers are still running.
In this case, we shouldn't wipe anything.
```release-note
fix a bug where crio wipe incorrectly wiped container storage even though the node wasn't rebooted
```
=> crio wipe: only completely wipe storage after a reboot

cmd/crio/main.go, cmd/crio/wipe.go, pkg/config/config.go, test/crio-wipe.bats
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
or else, we will unconditionally try to remove the whole directory after upgrading from 1.20,
rather than pointedly removing crio specific containers
```release-note
none
```
=> crio-wipe: only clear storage if CleanShutdownFile is supported

pkg/config/config.go, pkg/config/reload.go
/kind bug
When reloading the configuration, don't overwrite the name of the main configuration file with the name of the last drop-in that we parse, which would prevent us from reloading its contents the next time.
None
`pkg/config.Config.UpdateFromPath()` was calling `pkg/config.Config.UpdateFromFile()`, which always updated the `Config` object's `singleConfigPath` value, which it would later treat as the main configuration file in `pkg/config.Config.Reload()`.
```release-note
Fixed a bug which would cause configuration files to not be reloaded properly on SIGHUP when one or more "drop-in" configuration files were being used.
```
=> Reload the main config file when reloading configs

docs/crio.8.md, docs/crio.conf.5.md, internal/config/migrate/from_1_17.go, pkg/config/config.go, test/helpers.bash
bumps pause image to 3.5
Per https://github.com/kubernetes/kubernetes/pull/100292
None
part of https://github.com/kubernetes/kubernetes/pull/98205 (changelogs there)
k8s.gcr.io/pause:3.4.1 is for both windows/linux. Details in kubernetes/kubernetes/#98205
```release-note
Default pause image is `k8s.gcr.io/pause:3.5`
```
=> update pause image to 3.5（3.4.1 for multi-arch support and 3.5 for non-root）

cmd/crio/main.go
/kind cleanup
Before applying this patch the startup time would be zero
(`INFO[0000]`), which is now changed to use the correct formatting
timestmap we're defaulting to.
None
None
```release-note
Fixed version log timestamp when starting CRI-O
```
=> Add correct start time to initial log output

.github/workflows/test.yml, Makefile, contrib/bundle/Makefile, contrib/bundle/build, contrib/bundle/test, contrib/bundle/vars, contrib/test/integration/critest.yml, nix/default-arm64.nix, nix/nixpkgs.json, scripts/get, scripts/upload-artifacts, scripts/versions, test/critest.bats
> /kind ci
Adds arm64 static builds to v1.20 releases.
Fixes #4717
A similar commit has been merged for v1.21 releases,
https://github.com/cri-o/cri-o/commit/4ff8662ffbb9c570fbd668b18671a46af42dac26#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88
```release-note
None
```
=> Add arm64 static builds to v1.20 release.

README.md
We now clarify how CRI-O follows Kubernetes releases and is independent
from the patch versions. We also apply the same `n-2` version skew
policy, which is right now the default for Kubernetes.
None
None
```release-note
None
```
=> Clarify release cadence and version skew

cmd/crio/main.go, internal/lib/container_server.go, internal/lib/stop.go, internal/log/log.go, internal/log/log_test.go, internal/oci/runtime_oci.go, internal/oci/runtime_vm.go, server/server.go, test/copyimg/copyimg.go
/kind cleanup
As stated in the issue, `internal/log` package stores more information than logrus and functions including context parameter should use `internal/log` package instead logrus.
Fixes #4660 
```release-note
None
```
=> Use internal logging when context available

scripts/versions
This mainly affects the static binary bundle, for testing we already use
the latest cri-tools master.
None
None
```release-note
Updated cri-tools to v1.21.0 within static binary bundle
```
=> Bump cri-tools to v1.21.0

internal/storage/image.go
/kind feature
This will ensure that is the short name alias is not
found in the alias table it will always fall back to
looking through the search registries list as the user
cannot be prompted to select which registry to pull from.
None
```release-note
Fall back to search registries list if short name alias is not found in the alias table.
```
=> Set short name mode to permissive

cmd/crio/config.go, internal/criocli/criocli.go, pkg/config/config.go, pkg/config/template.go, pkg/config/template_test.go, test/config.bats, test/config_migrate.bats, test/crio-wipe.bats, test/docs-validation/main.go, test/helpers.bash
As described in #4506 , this PR lets ``crio config`` only prints the fields that are different than the default.
Fixes #4506
Yes.
```release-note
"crio config" only prints the fields that are different than the default configuration.
```
=> [CLI] "crio config" only prints the fields that are different than the default

contrib/test/integration/build/cri-tools.yml, contrib/test/integration/critest.yml, contrib/test/integration/main.yml
We changed the output build path in cri-tools a while ago which would cause always falling back to the wrong version.
None
None
```release-note
None
```
=> Bump OpenShift CI cri-tools version and fix build path

contrib/bundle/test-e2e, pkg/config/template.go, test/helpers.bash
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
now that we only print fields that are different from the default,
we can uncomment the config template fields that we previously didn't want to mess with.
```release-note
Some fields in the crio configuration related to storage and images were commented out by default (when running `crio config`). They have been uncommented, and will be applied (if they're different from the default value).
```
=> config: drop commented config lines

.github/workflows/test.yml, scripts/release-notes/release_notes.go
This should avoid races where release branches and the master try to
update the release notes in parallel. It also enables release notes for
tags, which may have the same issue.
None
None
```release-note
None
```
=> Rebase release-notes job before pushing gh-pages

.github/workflows/test.yml
/kind ci
Those branches do not have to upload any artifacts, so we focus from now
on only on release branches, the master and tags.
None
None
```release-note
None
```
=> Do not upload artifacts on dependabot branches

.github/workflows/test.yml, README.md, scripts/get, scripts/release-notes/release_notes.go, scripts/upload-artifacts
/kind cleanup
We now switch to our own GCS bucket, update the keys and necessary paths
for those. The latest master artifacts have been already uploaded as
well as the v1.21.0 tag.
None
None
```release-note
Switched build artifacts to be published via the [cri-o](https://console.cloud.google.com/storage/browser/cri-o) bucket.
```
=> Switch to `cri-o` bucket

test/helpers.bash
/kind cleanup
We already use crictl v1.21.0 or the latest master branch of it within
our tests. This means we now can safely remove that line.
None
None
```release-note
None
```
=> Remove TODO in helpers.bash

internal/config/cgmgr/systemd.go, pkg/container/container.go
This allows us to predictably shut down the node and help ensure
clean shutdown.
/kind cleanup
```release-note
Add systemd After=crio.service to containers and conmon
```
=> Add After=crio.service dependency to containers and conmon

contrib/bundle/test-e2e
Settings the right iptables rules and sysctls should make the deployment more robust. I'm not completely sure if this fixed the flaking bundle e2e tests, but they seem to fail at coredns not becoming ready.
None
None
```release-note
None
```
=> Fix bundle e2e test setup

internal/storage/image.go, server/image_pull.go
Fix Bug 1942608, during the call of ListImages, do not list the image if the there's no manifest exist.
> /kind bug
https://bugzilla.redhat.com/show_bug.cgi?id=1942608
```release-note
None
```
=> Bug 1942608: do not list the image with error locating manifest

internal/config/seccomp/seccomp.go
/kind bug
The internal seccomp profile (`RuntimeDefault`) should be ignored in the
same way as it was before using the new field. This aligns the
implementation with CRI-O releases before v1.21.0.
Fixes https://github.com/cri-o/cri-o/issues/4786
The bug comes up because `SecurityProfileTypeRuntimeDefault == 0` (the default value if the field is not set)
```release-note
Fixed bug where it was not possible to run containers using the default or no seccomp profile on 
seccomp disabled builds/machines
```
=> Fix RuntimeDefault seccomp behavior if disabled

internal/config/nsmgr/nsmgr.go, internal/config/nsmgr/types.go, internal/lib/container_server.go
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
If we fail to initially attach the namespaces, we need to cleanup the ones we've already created
Also, we are currently unconditionally recreating the namespaces when restoring. I believe that's from a rebase issue
```release-note
Fix a bug where CRI-O would leak opened files for namespaces on a server restore
```
=> nsmgr: fix some leaks with GetNamespace

server/rootless.go
/kind feature
rootless: enable resource limit when cgroup v2 controllers are delegated.
Required by [Usernetes](https://github.com/rootless-containers/usernetes)
The patch is from https://github.com/rootless-containers/usernetes/blob/v20210201.0/src/patches/crio/0001-rootless-enable-resource-limit-when-cgroup-v2-contro.patch .
```release-note
rootless: enable resource limit when cgroup v2 controllers are delegated.
```
- - -
Just as in Rootless Podman, cgroup v2 delegation needs to be configured: https://rootlesscontaine.rs/getting-started/common/cgroup2/
Also, the following sysctl is needed, depending on distro:
```bash
sudo sysctl kernel.dmesg_restrict=0
```
[Usernetes v20210201.0](https://github.com/rootless-containers/usernetes) contains CRI-O binary (`./usernetes/bin/crio`) with this …
=> rootless: enable resource limit when cgroup v2 controllers are delegated

server/sandbox_network.go, server/sandbox_run_linux.go
/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
or else the cleanup will always fail on cleanup from context deadline
```release-note
none
```
=> [1.19] server: use background context for network stop

.gitignore, vendor/github.com/Microsoft/hcsshim/.gitattributes, vendor/github.com/containerd/fifo/.gitattributes, vendor/github.com/fsnotify/fsnotify/.gitattributes, vendor/github.com/fsouza/go-dockerclient/.gitattributes, vendor/github.com/go-task/slim-sprig/.gitattributes, vendor/github.com/kevinburke/ssh_config/.gitattributes, vendor/k8s.io/client-go/pkg/version/.gitattributes, vendor/k8s.io/component-base/version/.gitattributes
/kind cleanup
.gitattributes files containing `export-subst` will cause that the
source code tarball  contents will change when the short commit does. To
avoid that we now ignore .gitattributes files from the vendor directory.
Fixes https://github.com/cri-o/cri-o/issues/4820
None
```release-note
None
```
=> Remove .gitattributes files from vendor directory

.github/PULL_REQUEST_TEMPLATE.md
Prow supports excluding HTML comments since quite some time. We now
switch to the same syntax like in k/k to make setting the `/kind` more
comfortable.
None
None
```release-note
None
```
=> Use HTML comment for /kind in PR template

internal/resourcestore/resourcestore.go, internal/resourcestore/resourcestore_test.go
/kind bug
if a resource has a watcher, but has not yet been put to the store, we should not be marking it as stale.
related to https://bugzilla.redhat.com/show_bug.cgi?id=1955596
```release-note
Fix a segfault when CRI-O has takes more than 8 minutes to create a pod or container
```
=> resource store: prevent segfault on cleanup step

server/sandbox_network.go, server/sandbox_run_linux.go
or else the cleanup will always fail on cleanup from context deadline
/kind bug
pick of https://github.com/cri-o/cri-o/pull/4851
```release-note
none
```
=> [1.21] server: use background context for network stop

Makefile
/kind ci
Ginkgo v1.16.2 introduced a feature to hide the warnings spamming the test logs. This patch enables to turn them off for now.
None
Introduced in https://github.com/cri-o/cri-o/pull/4849
```release-note
None
```
=> Suppress ginkgo warning when running tests

internal/oci/runtime_vm.go
/kind bug
https://github.com/cri-o/cri-o/pull/4803 partially reverted
https://github.com/cri-o/cri-o/pull/4650, but ended up missing two
places where the context is used to ensure the goroutines are stopped.
Fixes #4798 
This was caught due to some tests failing in a non deterministic manner
on kata-containers CI.
Related:
https://github.com/kata-containers/tests/pull/3503#issuecomment-834717567
```release-note
None
```
=> runtimeVM: Use internal context to ensure goroutines are stopped

internal/oci/runtime_vm.go
/kind bug
https://github.com/cri-o/cri-o/pull/4803 partially reverted
https://github.com/cri-o/cri-o/pull/4650, but ended up missing two
places where the context is used to ensure the goroutines are stopped.
Fixes #4798 
This was caught due to some tests failing in a non deterministic manner
on kata-containers CI.
Related:
https://github.com/kata-containers/tests/pull/3503#issuecomment-834717567
This is a backport of https://github.com/cri-o/cri-o/pull/4879
```release-note
None
```
=> release-1.21 | runtimeVM: Use internal context to ensure goroutines are stopped

contrib/test/integration/build/kata.yml, contrib/test/integration/python3.yml, contrib/test/integration/system-packages.yml, contrib/test/integration/vars.yml
/kind ci
Starting from CentOS 8 and Fedora 34 we have packages for the 2.x kata branch.
Use these newer packages for the integration tests: instruct the playbook to install the newer packages.
Change also the subset of the run tests to match the passing ones.
None
None
```release-note
None
```
=> contrib/test/integration playbook with kata: use kata 2.x when available

.gitpod.Dockerfile, .gitpod.yml, README.md
Hi cri-o team! 👋
here is a PR that fully-automates the dev setup of cri-o with Gitpod, providing anyone with a pre-built, browser-based development environment in one click:
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/cri-o/cri-o)
* Comes with all cri-o lifecycle dependencies pre-installed (Go, Docker...)
* Runs `make` ahead-of-time so you don't need to wait
* Gives anyone immediate access to the pre-compiled cri-o, and allows to easily edit & rebuild the code
I hope this can make life easier for contributors, and for maintainers who need to review many PRs (hint: you can already open this PR in Gitpod to easily review & test it without messing up your local checkout).
I'm looking forward to your feedback on this PR! 🚀 …
=> Added Gitpod config

server/container_create_linux.go
if the bind mount points to the container root, raise a warning.
Closes: https://bugzilla.redhat.com/show_bug.cgi?id=1950408
/kind cleanup
warn the user when a bind mount targets the container root
Fixes: https://bugzilla.redhat.com/show_bug.cgi?id=1950408
```release-note
raise a warning when creating a bind mount on the container root
```
=> server: add warning when bind mounting to the root

internal/lib/container_server.go, internal/lib/container_server_test.go, server/server.go, test/crio-wipe.bats
/kind bug
Embarrassingly, the main use-case of internal wipe was one that I had not tested appropriately. It turns out, we never actually have any containers wipeIfAppropriate after we call restore.
This is because the managed ns no longer exists (it is in /run, a tmpfs). Even if its not in a tmpfs, it is not correctly mounted on reboot.
this is okay, though. It reduces complexity a bit. Now, instead of using the version_file to determine whether we rebooted, we just have to make sure we call CNI DEL as much as possible if we fail to restore a sandbox.
To do this, we must rework LoadSandbox to return the sandbox in question (as soon as possible, basically after unmarshalling all the data from the config.json), then call networkStop on that sandbox (inside a resource cleaner so we retry if …
=> server: rework internal wipe to play better with reboots

server/server.go
/kind bug
This PR has two QOL commits for internal wipe
The first commit simply reduces the verbosity of the logs (by not calling two warns on a failed LoadSandbox, as well as not re-calling DeleteContainer/ReleaseName for each previously deleted container
the second commit significantly speeds up crio's start up by not attempting to call CNI del before adding it as a cleanup func.
```release-note
Fix a bug where server startup was significantly slowed down by attempting to clean up CNI resources after a reboot.
```
=> server: reduce log verbosity and speed up startup on restore

server/container_create.go, server/container_create_linux.go, server/sandbox_run_linux.go
The current implemention has an issue where we add the default
capabilties when the user does drop ALL and add few.
/kind bug
#4922 
```release-note
Fix drop ALL and add back few caps behavior to not include the default configured capabilities
```
=>  Add support to drop ALL and add back few capabilities

internal/resourcestore/resourcecleaner_test.go
The cleanup does not run in parallel any more which means that this test
blocks forever.
None
None
```release-note
None
```
=> Remove "should cleanup in parallel" test

.github/workflows/verify.yml, .golangci.yml, Makefile, internal/oci/runtime_oci.go, test/copyimg/copyimg.go, utils/utils.go
/kind ci
/kind dependency-update
This updates golangci-lint to the latest release and fixes new lints. It
also enables linters which do not report any issue.
None
None
```release-note
None
```
=> Update golangci-lint to v1.40.1 and fix lints

internal/storage/runtime.go
overlay supports a new mount option "volatile" that reduces I/O by
ignoring fsync and syncfs requests.
Enable it for CRI-O containers as they are "volatile" by nature and
are not supposed to survive a reboot.
Even in the case containers created by CRI-O are persistent, we
already have code in place to throw away the storage if the shutdown
was not clean, so they will be cleaned up in any case.
/kind feature
Enable `volatile` for the overlay storage.
```release-note
Enable the  "volatile" option for the overlay drivers when it is supported by the underlying kernel.
```
=> storage: use volatile containers

.github/workflows/test.yml
The latest update of k/release requires using go 1.16. This is now being
fixed with this patch.
None
None
```release-note
None
```
=> Use go 1.16 for release notes and forward jobs

server/metrics/metrics.go, server/metrics/metrics_test.go, server/server.go, server/server_test.go, test/metrics.bats
/kind feature
We now add new file watchers for the metrics TLS cert and key as well as
reloading them on any event. If the reload fails, then we keep the old
certificates as fallback.
None
None
```release-note
Automatically reload metrics TLS certificate and key if any of those specified files change.
```
=> Watch and reload TLS certificates for metrics

internal/oci/oci.go, internal/oci/oci_test.go, internal/oci/runtime_oci.go, internal/oci/runtime_vm.go, internal/resourcestore/resourcestore_test.go, server/container_exec.go, server/container_execsync.go, server/server.go, test/mocks/oci/oci.go
/kind bug
It is not really needed, and causes unnecessary overhead. Plus, we drop an unkillable child from the mix
allowing cri-o to keep track of its children better.
Backport of #4943
None
```release-note
ExecSync requests now don't use conmon, instead calling the runtime directly, which reduces overhead.
```
=> [1.20] oci: do not use conmon for exec sync

internal/oci/oci.go, internal/oci/runtime_oci.go, internal/oci/runtime_vm.go, server/container_exec.go, server/container_execsync.go, server/server.go
/kind bug
It is not really needed, and causes unnecessary overhead. Plus, we drop an unkillable child from the mix
allowing cri-o to keep track of its children better.
Backport of https://github.com/cri-o/cri-o/pull/4943
eebef460c83f76db187f5c404267d09100ff347c is not part of this backport, because we do not have internal types at this point in time.
```release-note
ExecSync requests now don't use conmon, instead calling the runtime directly, which reduces overhead.
```
=> [1.19] oci: do not use conmon for exec sync

internal/oci/runtime_oci.go
/kind bug
previously we had lots of instances of
`Failed to get pid (-1) or pgid (-1) from file /tmp/pidfile097828553: strconv.Atoi: parsing \"\": invalid syntax"`
because we precreated the pid file. stop doing this, and also kill the runtime process if we timeout an exec run
```release-note
Fix a bug where an exec sync timeout would fail to cleanup the runtime exec process
```
=> oci: fix issues with exec

cmd/crio/main.go, go.mod, internal/log/klog.go, vendor/modules.txt
/kind feature
Add a klog to logrus logging shim. This allows us to convert messages into the logrus format by preserving the log layout.
None
Before:
```
INFO[2021-06-07 13:33:27.507085664+02:00] Starting CRI-O, version: 1.21.0, git: 1559a9af5e08f7c0a184ca5a3e0656848cfb6482(dirty)
E0607 13:33:30.689353 1786399 httpstream.go:143] (conn=&{0xc000560160 [0xc000323a40] {0 0} 0x1b90c80 0x13b4320}, request=0) timed out waiting for streams
E0607 13:33:30.690007 1786399 httpstream.go:143] (conn=&{0xc000560160 [0xc000323a40 0xc0006a2280] {0 0} 0x1b90c80 0x13b4320}, request=0) timed out waiting for streams
```
After:
```
INFO[2021-06-07 13:34:26.749451747+02:00] Starting CRI-O, version: 1.21.0, git: 793452dc36a72251984f65a79eb28959b54e49e2(dirty)
ERRO[2021-06-07 13:34:29.546098148+02:00] …
```
=> Add klog to logrus shim

internal/oci/runtime_vm.go
/kind bug
Currently the shimv2 debug is only enabled when CRI-O is, specifically,
on debug mode.  However, it should be enabled whenever the CRI runtime
is on debug *or any other lower* mode, as in trace mode.
None
A similar PR has been opened for the containerd side, so we ensure we behave the same as they do.
https://github.com/containerd/containerd/pull/5617
```release-note
None
```
=> runtimeVM: Enable shimv2 debug when CRI-O is on debug+ log level

pkg/config/template.go, server/metrics/metrics.go, test/metrics.bats
/kind feature
This allows starting CRI-O without having the certificates on disk. A Kubernetes controller can later on reconcile their own certificates into the same location for reload.
None
None
```release-note
Added generation of self-signed certificates for the secure metrics endpoint
if the provided cert and key paths are not available on disk.
```
=> Generate self-signed metrics cert/key if provided ones are not available

internal/oci/runtime_oci.go, internal/oci/runtime_vm.go, server/image_pull.go, server/metrics/interceptors.go, server/metrics/metrics.go, server/sandbox_network.go
/kind cleanup
We now provide an `Instance()` singleton for metrics as well as
modification helper functions to be able to enable/disable them in
further patches.
Part of https://github.com/cri-o/cri-o/issues/4982
None
```release-note
None
```
=> Move metrics into singleton helpers

go.mod, go.sum, server/sandbox_network.go, test/cni_plugin_helper.bash, test/network.bats, vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go, vendor/github.com/cri-o/ocicni/pkg/ocicni/types.go, vendor/modules.txt
Ongoing sandbox requests cannot be (or are not) canceled by kubelet, leading to a situation where short-lived pods (especially Kubernetes e2e tests for stateful sets) cause overlapping sandbox requests. If the CNI plugin needs to wait for network state to converge, it's pointless to wait for a sandbox who's pod has been deleted so the plugin should cancel the request and return to the runtime. However, it's impossible to do that race-free without the pod UID the sandbox was created for, since the there is a gap between when kubelet requests the sandbox creation and when the plugin gets the pod object from the apiserver when the pod could have been deleted and recreated, and the CNI plugin would retrieve information for the new pod, not the pod the sandbox was created for.
Passing the pod …
=> network: pass pod UID to ocicni when performing network operations

go.mod, go.sum, server/sandbox_network.go, test/cni_plugin_helper.bash, test/network.bats, vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go, vendor/github.com/cri-o/ocicni/pkg/ocicni/types.go, vendor/modules.txt
Ongoing sandbox requests cannot be (or are not) canceled by kubelet, leading to a situation where short-lived pods (especially Kubernetes e2e tests for stateful sets) cause overlapping sandbox requests. If the CNI plugin needs to wait for network state to converge, it's pointless to wait for a sandbox who's pod has been deleted so the plugin should cancel the request and return to the runtime. However, it's impossible to do that race-free without the pod UID the sandbox was created for, since the there is a gap between when kubelet requests the sandbox creation and when the plugin gets the pod object from the apiserver when the pod could have been deleted and recreated, and the CNI plugin would retrieve information for the new pod, not the pod the sandbox was created for.
Passing the pod …
=> [release-1.21] network: pass pod UID to ocicni when performing network operations

internal/storage/image.go
Do not check whether a registry is blocked.  c/image is taking care of
that implicitly when attempting to copy an image.
/kind bug
or else mirrored registries cannot resolve there
```release-note
fix a bug where CRI-O prematurely stopped pulling from a blocked registry, even if there was a mirror for that registry it was allowed to pull from.
```
=> [1.20] pull: do check for blocked registries

dependencies.yaml, scripts/versions
This reverts commit 3373b31094ba707a27d0d94caecdcf3146ed9f80.
Caused upstream kubernetes CI to fail: https://prow.k8s.io/?job=*ci-crio-cgroupv1-node-e2e*
None
None
```release-note
None
```
=> Revert "Update runc to v1.0.0"

go.mod, go.sum, vendor/github.com/containers/storage/pkg/lockfile/lockfile_unix.go, vendor/modules.txt
/kind bug
Fixes a runtime panic if the layers lockfile parent directory got removed.
Refers to https://github.com/containers/storage/pull/964
None
```release-note
Fixed runtime panic if container storage layers lockfile parent directory got removed.
```
=> [1.19] Bump c/storage to latest v1.20-stable

go.mod, go.sum, vendor/github.com/containers/storage/pkg/lockfile/lockfile_unix.go, vendor/modules.txt
/kind bug
Fixes a runtime panic if the layers lockfile parent directory got removed.
Refers to https://github.com/containers/storage/pull/965
None
```release-note
Fixed runtime panic if container storage layers lockfile parent directory got removed.
```
=> [1.20] Bump c/storage to latest release-1.24

internal/config/cnimgr/cnimgr.go, internal/config/cnimgr/cnimgr_test_inject.go, pkg/config/config.go, pkg/config/config_test_inject.go, server/runtime_status.go, server/runtime_status_test.go, server/sandbox_run_linux.go, server/suite_test.go
/kind bug
The way kubernetes deals with networking infra is that it doesn't. it's mostly up to the cri impl to figure out how pods are connected to each other. the problem with not being networking aware is that the kubelet won't wait for the network to be ready before starting pods. in resource constrained environments, this can cause large delays in node bootstrap, as the a pod that is the cni plugin is competing to start with all others.
instead, we can rate limit the pod creation by waiting until the cniplugin is ready before starting a pod. since it won't make progress until the cni plugin is up anyway, this should only improve how quickly a node comes up
```release-note
Wait for CNI plugins to be ready before starting non-host-network pods, to allow pods that may run CNI plugins to …
```
=> Introduce CNIManager

internal/lib/container_server.go, server/container_create.go, server/sandbox_run_linux.go, test/timeout.bats
before, if crictl sent a duplicate request (runp, wait till finish, runp), cri-o would stall crictl, thinking it was a timeout.
Now, we check whether the pod has been created before waiting on the already created resource
/kind bug
```release-note
Fix a bug where duplicate requests would stall even if the pod or container was already created
```
=> server: properly handle duplicate requests

internal/hostport/hostport.go, internal/hostport/hostport_manager.go, internal/hostport/meta_hostport_manager.go
/kind cleanup
The klog messages can be converted to logrus to align with our general logging approach.
None
None
```release-note
None
```
=> Switch from klog to logrus in hostport manager

internal/oci/runtime_oci.go, test/ctr.bats
/kind bug
or else containers may have trouble accessing the terminal
The background here is a bit weird. I tried figuring out why we actually specified this in the first place. It seems we first introduced this when adding initial support for execsync with conmon: https://github.com/cri-o/cri-o/pull/310
As the file before that was just https://github.com/cri-o/cri-o/blob/61e60bfe4740c0a5f2a574d259f98ba9834fa4e6/oci/oci.go#L181 which makes no mention of tty.
let's see what the tests think.
related to https://bugzilla.redhat.com/show_bug.cgi?id=1983205
edit: Turns out this is needed, for https://github.com/cri-o/cri-o/pull/1386/files and https://bugzilla.redhat.com/show_bug.cgi?id=1549029. changed the PR to account for this case
```release-note …
```
=> oci: properly handle tty on execsync

pkg/container/container.go, test/ctr.bats, test/testdata/sandbox_config.json
Commit 8cf32223a1dc1208b53167763638886fd23bde67 introduces some
extra processing of seccomp-related sandbox annotations.  But it
introduced a regression where most sandbox annotations are no longer
propagated to the container annotations.  Add an `else` clause to
ensure we propagate all the sandbox annotations to the container's
OCI configuration.
/kind bug
Fixes: https://github.com/cri-o/cri-o/issues/5077
```release-note
None
```
=> Fix propagation of annotations from sandbox to container

Makefile
/kind cleanup
The flag removes all file system paths from the resulting executable.
Instead of absolute file system paths, the recorded file names will
begin with either "go" (for the standard library), or a module
path@version (when using modules), or a plain import path (when using
GOPATH).
None
None
```release-note
None
```
=> Use -trimpath for builds

docs/crio.8.md, docs/crio.conf.5.md, internal/process/defunct_processes.go, server/metrics/collectors/collectors.go, server/metrics/collectors/collectors_test.go, server/metrics/metrics.go, tutorials/metrics.md
/kind feature
This patch adds `internal/process/defunct_processes.go` that retrieves the total number of defunct/zombie processes in a node and adds a new metric `crio_processes_defunct` that uses `internal/process/defunct_processes.go` to collect the total number of defunct processes.
None
None
```release-note
Added `internal/process/defunct_processes.go` and `crio_processes_defunct` metric to collect the total number of defunct/zombie processes in a node.
```
=> Monitor defunct processes in a node

cmd/crio/main.go
This showed up when I was grepping a journal for `error:`, and it's
not an error.
```release-note
NONE
```
=> main: Don't log an error if the clean shutdown file doesn't exist

server/sandbox_run_linux.go, test/inspect.bats
/kind bug
or else kubelet logs will be spammed with
```
hyperkube[1354]: E0727 15:45:29.058957    1354 fsHandler.go:114] failed to collect filesystem stats - rootDiskErr: could not stat "diff" to get inode usage: stat diff: no s
```
```release-note
Fix a bug where cAdvisor couldn't read the disk usage of a pod with a dropped infra container
```
=> server: configure MountPoint for dropped infra containers

contrib/test/ci/cri-o.spec
We require golang 1.16 to build CRI-O.
This change should only affect the test cases `ci/prow/e2e-agnostic`, `ci/prow/e2e-gcp` and `ci/prow/images`.
Follow-up of https://github.com/openshift/release/pull/20939
```release-note
None
```
=> Bump required golang version for cri-o.spec

cmd/crio/main.go, contrib/test/integration/build/cri-tools.yml, contrib/test/integration/critest.yml, contrib/test/integration/golang.yml, lib/node/node.go, lib/node/systemd.go, server/container_create.go, server/sandbox_run.go, test/ctr_seccomp.bats, vendor.conf
/kind bug 
These commit introduces a bare bones internal/config/node package to support this feature.
Not cleaning failed scopes can cause mounts to fail, this piece of functionality is definitely a bug.
The rest of the internal/config/node package is not fixing a bug, so it's excluded.
currently, systemd leaks some scopes if they're failed.
This can be changed with the CollectMode annotation (which runc will set).
takes https://github.com/cri-o/cri-o/pull/4572 and https://github.com/cri-o/cri-o/pull/4458
relates to https://bugzilla.redhat.com/show_bug.cgi?id=1965900
```release-note
Fix a bug where CollectMode wouldn't be set if the feature was backported to systemd (in RHEL/CentOS 7, for instance)
```
=> [1.11] set inactive-or-failed collectmode if appropriate

tutorials/kubeadm.md
Fixed a typo in the kubeadm.md file. The `script` word.
Signed-off-by: Imanol Valiente <me@imanol.dev>
It fixes a little typo in the kubeadm.md documentation file.
None
None
=> Fix kubeadm.md typo

internal/log/log.go, server/container_start.go
/kind feature
We now correlate the container ID, sandbox ID as well as its process ID
together on container start log. This way consumers can rely on it and
easily parse the output.
None
Example log outout:
```
INFO[2021-07-28 09:33:46.768702002+02:00] Started container    PID=261797 containerID=6c86fb7717891971ec157702ec295cc4b77ef9c70e4332b95096869711e1914e description=// id=f009591f-fbb6-4245-b521-ce0022221ba8 name=/runtime.v1alpha2.RuntimeService/StartContainer sandboxID=b01b6b644c912a32ac97fdfd984b5b7733f57cac0f523950cfe41cd1606418cb
``` 
```release-note
Added structural logging of container ID, sandbox ID and process ID on container start.
```
=> Log structured container/sandbox ID and PID on start

internal/version/buildtag_apparmor.go, internal/version/buildtag_devicemapper.go, internal/version/buildtag_openpgp.go, internal/version/buildtag_ostree.go, internal/version/buildtag_seccomp.go, internal/version/buildtag_selinux.go, internal/version/version.go, test/version.bats
/kind feature
We now add the used build tags to the `crio version` output to enable
better debug abilities. Beside that, we also indicate if AppArmor and
seccomp are available on the local system (runtime check).
None
Example output:
```
> ./bin/crio version
Version:          1.22.0
GitCommit:        fe4b22c64a6655759eb0a253ef6174fa1b4fc5d0
GitTreeState:     dirty
BuildDate:        1980-01-01T00:00:00Z
GoVersion:        go1.16.6
Compiler:         gc
Platform:         linux/amd64
Linkmode:         dynamic
BuildTags:        apparmor, containers_image_ostree_stub, seccomp, selinux
SeccompEnabled:   true
AppArmorEnabled:  false
> ./bin/crio version -j
{
"version": "1.22.0",
"gitCommit": "fe4b22c64a6655759eb0a253ef6174fa1b4fc5d0",
"gitTreeState": "dirty",
"buildDate": "1980-01-01T00:00:00Z", …
```
=> List build tags and seccomp/apparmor status on `version` subcommand

dependencies.yaml, scripts/versions
Updating the binary within the bundle.
None
Refers to https://github.com/kubernetes/kubernetes/issues/104280
```release-note
Update runc within static binary bundle to v1.0.1
```
=> Bump runc to 1.0.1

scripts/node_e2e_installer
/kind ci
We now update the pinned node e2e test commit to use one which ships runc v1.0.1
Follow-up on https://github.com/cri-o/cri-o/pull/5203
None
```release-note
None
```
=> Bump node e2e test commit to use runc v1.0.1

internal/version/linkmode_dynamic.go, internal/version/linkmode_static.go, internal/version/version.go
/kind cleanup
We now do not call `ldd` any more when finding out the linkmode of the
binary, instead we rely on build tags.
Closes https://github.com/cri-o/cri-o/issues/5165
None
```release-note
Use build tag for `linkmode` detection on `crio version`.
```
=> Switch to build tag for linkmode

server/container_create.go, server/sandbox_run_linux.go, server/server.go
/kind cleanup
Remove effectively unused Server.updateLock. It is only
ever RLocked()/RUnlocked(). A leftover that should have
been removed in b56da85fc.
None
None
None
=> server: remove ineffective `updateLock`.

contrib/metrics-exporter/cluster.yaml
/kind bug
The yaml parser fails if the indentation is not on the same level as the key.
Fixes https://github.com/cri-o/cri-o/issues/5285
None
```release-note
Fixed `contrib/metrics-exporter/cluster.yaml` for `kubectl create`.
```
=> Fix cluster.yaml for kubectl create

internal/config/rdt/rdt.go
/kind cleanup
This reduces the noise on systems not having Intel RDT enabled. We already log that RDT is not enabled on profile load.
None
None
```release-note
Do not log on startup if Intel RDT is not supported.
```
=> Do not log on startup if Intel RDT is not supported

internal/oci/runtime_oci.go
If we haven't signaled on the stop pipe, then conmon will be sitting waiting to be told to start
Instead, we need to kill the process.
/kind bug
```release-note
fix a bug where CRI-O waits forever on a conmon process that will not stop
```
=> server: do not wait forever on conmon cgroup move fail

docs/crio.8.md, docs/crio.conf.5.md, pkg/config/config.go, test/helpers.bash
Updates pause image to 3.6 from 3.5 per https://github.com/kubernetes/kubernetes/pull/104711 
part of https://github.com/kubernetes/kubernetes/issues/104890 
```release-note
bumps pause image to 3.6
```
=> updates pause image to 3.6

server/sandbox_remove_test.go
Signed-off-by: utam0k <k0ma@utam0k.jp>
/kind other
Add unit test for the `server/sandbox_remove` to increase code coverage.
None
```release-note
None
```
=> Add unit test for the `server/sandbox_remove`.

test/ctr.bats
to better match docker journald logging behavior, conmon will be switching to having the
syslog identifer set to the contanier name or ID. this means this test fails, as it was previously conmon.
update the test
/kind ci
```release-note
none
```
=> test: fix journald test for new conmon

docs/crio.conf.5.md
Signed-off-by: utam0k <k0ma@utam0k.jp>
Removed` one of the explanations for `bind_mount_prefix` because it is duplicated.  Perhaps a blank string would be more correct as the default.
Fixes https://github.com/cri-o/cri-o/issues/5330
```release-note
None
```
=> Remove one of the explanations for `bind_mount_prefix` because it is duplicated.

test/testdata/sandbox_config.json
/kind other
8.8.8.8 would be a server, not a search domain, so change the section it appears in in the test sandbox config from "searches" to "servers".
None
```
None
```
=> test/testdata/sandbox_config.json: fix the dns_config

go.mod, go.sum, vendor/github.com/opencontainers/selinux/go-selinux/label/label_linux.go, vendor/github.com/opencontainers/selinux/go-selinux/rchcon.go, vendor/github.com/opencontainers/selinux/go-selinux/rchcon_go115.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go, vendor/github.com/opencontainers/selinux/go-selinux/xattrs_linux.go, vendor/github.com/opencontainers/selinux/pkg/pwalk/README.md, vendor/github.com/opencontainers/selinux/pkg/pwalkdir/README.md, vendor/github.com/opencontainers/selinux/pkg/pwalkdir/pwalkdir.go, vendor/modules.txt
Bump opencontainers/selinux 1.8.2 -> 1.8.5
Notable changes include:
* getting rid of pkg/errors (https://github.com/opencontainers/selinux/pull/148)
* using filepath.WalkDir on Go 1.16+ (https://github.com/opencontainers/selinux/pull/150)
* other small performance improvements (https://github.com/opencontainers/selinux/pull/153, https://github.com/opencontainers/selinux/pull/154, https://github.com/opencontainers/selinux/pull/155)
The pkg/error change is already handled by commit 371a600936.
https://bugzilla.redhat.com/show_bug.cgi?id=2007458
```release-note
None
```
=> [1.21] bump opencontainers/selinux to 1.8.5

install.md
Based on my attempt to build crio with btrfs graph driver in Debian 10(where the package in opensuse kubic seems missing it).
With help of the info provided by https://github.com/cri-o/cri-o/pull/5157
=> fix debian 10 build doc

pkg/config/config.go, pkg/config/config_test.go
Fix https://bugzilla.redhat.com/show_bug.cgi?id=2012838
Merge in the storage_option from drop-in crio.conf to the storage.conf, do not override the configs from storage.conf.
The override leads to configuration of containerruntimeconfig not working.
/kind bug
https://bugzilla.redhat.com/show_bug.cgi?id=2012838
The storage_option from /etc/crio/crio.conf.d/00-default overrides the configurations from /etc/containers/storage.conf.
```release-note
Merge storage_option from drop-in files to sttorage_option from storage.conf
```
=> Bug 2012838: fix override storage options from storage.conf

internal/lib/sandbox/sandbox.go, internal/lib/sandbox/sandbox_test.go, server/container_create_linux.go, server/sandbox_run_linux.go, test/ctr.bats
/kind feature
This aligns CRI-O with podman, by adding a specific file to help programs running inside its containers to detected they are in fact running inside a container.
Fixes #5461
Decided to use the same file name as podman, given that docker's approach is vendor specific.
```release-note
Containers now have a `/run/.containerenv` file to help applications identify that they are running inside a container.
```
=> Add .containerenv file to containers

internal/config/nsmgr/types.go, internal/lib/container_server.go, internal/lib/sandbox/namespaces.go, internal/lib/sandbox/namespaces_test.go, server/sandbox_stop_linux.go
or else namespaces will appear to leak before kubelet GCs the associated pods.
To do so, do all of the namespace unmounting pieces on stop, but don't actually delete the file.
/kind bug
```release-note
Move namespace cleanup from sandbox stop to sandbox remove. This allows veth entries in the network namespaces of pods to be cleaned up earlier
```
=> server: close namespaces on sandbox stop

server/container_create_linux.go
/kind bug
This adds a relabelling of the containerenv file that is missing in #5463. This is needed to run kata-containers on an SELinux enabled host.
Fixes #5483 
Change comes from code inspection. I haven't had time to try this fix yet but I'm proposing it anyway for review, as it is currently blocking our downstream workflow.
```release-note
None
```
=> Relabel containerenv files

pkg/config/workloads.go, test/workloads.bats
/kind bug
```release-note
fix a segfault if a workload is configured without the resources table
```
=> [1.22] workloads: fix if resources are empty

server/sandbox_run_linux.go
Some error messages related to userns mappings do not quite match
CRI-O's behaviour.  Furthermore, the same error message was used for
two different conditions.  Make the error messages clearer and more
actionable.
None
None
```release-note
Improved some error messages related to user namespaces.
```
=> clarify some error messages

internal/config/cnimgr/cnimgr.go, pkg/config/config.go, server/sandbox_run_linux.go, server/server.go
Or else they don't know why cri-o is waiting
also, catch server shutdown so the process does eventually shutdown.
/kind bug
```release-note
fix a bug where CRI-O would never shutdown if the networking plugin wasn't configured correctly
```
=> server: notify user when network is not ready yet

pkg/config/config.go, pkg/config/config_test.go
Backport 8daa9039aadf1bc3676f6b1e41f6937900503339.
Fix bug https://bugzilla.redhat.com/show_bug.cgi?id=2020716 in 4.7
original bug: https://bugzilla.redhat.com/show_bug.cgi?id=2012838
Merge in the storage_option from drop-in crio.conf to the storage.conf, do not override the configs from storage.conf.
The override leads to configuration of containerruntimeconfig not working.
```release-note
Backport the fix of merging storage_option from drop-in files to sttorage_option from storage.conf.
```
=> [release-1.20] Bug 2012838: Backport the fix override storage options from storage.conf

server/metrics/metrics.go
/kind bug
Fixes a problem with image pull metrics that got introduced by https://github.com/cri-o/cri-o/pull/5487 accidentally.
Following CI test job https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-openshift-release-master-nightly-4.10-e2e-aws/1474040369288056832 is reporting the following CRI-O metric error in the node logs.
```
Dec 23 16:31:43.856269 ip-10-0-152-30 crio[1336]: time="2021-12-23 16:31:43.856139768Z" level=warning msg="Unable to write image pulls by digest metric: inconsistent label cardinality: expected 2 label values but got 4 in []string{\"image-registry.openshift-image-registry.svc:5000/e2e-test-build-volumes-slncv/mydockerstream@sha256:4500255aeb9969639ccbc31a8e526c206b5072c39e633797a93f9634e28dec0a\", …
```
=> [metrics] Fixed a problem where metricImagePullsBytesTotal was raising an error

Makefile, internal/config/conmonmgr/conmonmgr.go, internal/config/conmonmgr/conmonmgr_test.go, internal/config/node/systemd.go, internal/config/nsmgr/nsmgr.go, internal/dbusmgr/user.go, internal/oci/runtime_oci.go, internal/runtimehandlerhooks/high_performance_hooks.go, internal/runtimehandlerhooks/utils.go, pkg/config/config.go, test/mocks/cmdrunner/cmdrunner.go, utils/cmdrunner/cmdrunner.go, utils/cmdrunner/cmdrunner_test.go, utils/cmdrunner/cmdrunner_test_inject.go, utils/cmdrunner/suite_test.go, utils/utils.go
/kind feature
If InfraCtrCPUSet is configured, then there is an expectation that all commands land on certain CPUs. However, this isn't always the case. Thus, we need a way of spawning commands given a list of CPUs.
To do this, update cmdrunner to be a singleton object that stores an optional command and args to prepend to commands. Then use this singleton anytime exec.Command would be called.
```release-note
Add functionality to use taskset to spawn new commands cri-o runs. Now, if InfraCtrCPUSet is called, all newly spawned commands will be placed in the InfraCtrCPUSet (as it's expected to be set to the reserved CPU set that system commands should run on).
```
=> prepend commands with taskset if InfraCtrCPUSet is configured

pkg/container/device.go, pkg/container/device_test.go
/kind bug
Fixes in some cases incorrectly chosen device node group ID in containers.
None
Pass host side GID, not UID, as fallback GID to getDeviceUserGroupID().
Update the corresponding unit tests to trigger/catch the original bug.
```release-note
None
```
=> pkg/container: fix container device GID fallback.

internal/config/nsmgr/types.go, internal/lib/sandbox/namespaces.go, internal/lib/sandbox/namespaces_test.go, internal/oci/container.go, pkg/container/namespaces_test.go, server/sandbox_stop_linux.go, server/server.go, test/crio-wipe.bats, test/restore.bats
/kind bug
Unfortunately, having an unmounted namespace in /var/run/netns causes `ip a` to report `Error: Peer netns reference is invalid`. To fix this, we need to partially revert https://github.com/cri-o/cri-o/pull/5336/commits/efcf8afe6a7b7f942833746a1b357e591000153c and replace it.
related to https://bugzilla.redhat.com/show_bug.cgi?id=2035969
```release-note
Fix bug where `ip a` reports `Error: Peer netns reference is invalid`
```
=> namespace: drop and replace stop method

Makefile, internal/config/conmonmgr/conmonmgr.go, internal/config/conmonmgr/conmonmgr_test.go, internal/config/node/systemd.go, internal/config/nsmgr/nsmgr.go, internal/dbusmgr/user.go, internal/oci/runtime_oci.go, internal/runtimehandlerhooks/high_performance_hooks.go, internal/runtimehandlerhooks/utils.go, pkg/config/config.go, test/mocks/cmdrunner/cmdrunner.go, utils/cmdrunner/cmdrunner.go, utils/cmdrunner/cmdrunner_test.go, utils/cmdrunner/cmdrunner_test_inject.go, utils/cmdrunner/suite_test.go, utils/utils.go
/kind feature
If InfraCtrCPUSet is configured, then there is an expectation that all commands land on certain CPUs. However, this isn't always the case. Thus, we need a way of spawning commands given a list of CPUs.
To do this, update cmdrunner to be a singleton object that stores an optional command and args to prepend to commands. Then use this singleton anytime exec.Command would be called.
```release-note
Add functionality to use taskset to spawn new commands cri-o runs. Now, if InfraCtrCPUSet is called, all newly spawned commands will be placed in the InfraCtrCPUSet (as it's expected to be set to the reserved CPU set that system commands should run on).
```
=> [1.22] prepend commands with taskset if InfraCtrCPUSet is configured

utils/utils.go
We're now using a timeout which is able to unblock gaining
the sandbox mutex in a container creation vs sandbox stop race.
Signed-off-by: Sascha Grunert <sgrunert@redhat.com>
/kind bug
```release-note
none
```
=> [1.21] Use timeout for conmon cgroup move

server/container_create_linux.go
/kind bug
createSandboxContainer is passing down the wrong root image path to MountsWithUIDGID. This results in the directory not being discoverable within the container image and have crio setup the bind for the directory.
```release-note
Fix crypto-profile bind within RHEL based containers.
```
=> Bug 2043254: pass the main image mount point to fix crypto profiles binding

server/container_create.go, server/container_create_test.go
Fix a potential NULL-pointer dereference in a log message.
/kind bug
Fixes a potential NULL-pointer dereference in a log message that could crash the daemon.
None
None
```release-note
Fix a potential crash caused by a log message NULL-pointer dereference.
```
=> server: fix a potential NULL-pointer dereference.

internal/lib/stats/stats_server.go
/kind bug
The `Linux` field of the pod sandbox stats is accessed in multiple
places while we do not init it before. This caused a runtime panic with
the following backtrace:
```
DEBU[2022-02-02 13:49:20.074139178+01:00] Request: &ListPodSandboxStatsRequest{Filter:&PodSandboxStatsFilter{Id:,LabelSelector:map[string]string{},},}  file="go-grpc-middleware@v1.3.0/chain.go:25" id=bf81646b-e1d7-4fd8-a312-3e84fdef3cfe name=/runtime.v1.RuntimeService/ListPodSandboxStats
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf77ca9]
goroutine 807 [running]:
github.com/cri-o/cri-o/internal/config/cgmgr.populateSandboxCgroupStatsFromPath({0xc00074ca40, 0x20}, 0xc0002f1740) …
```
=> Fix runtime panic on pod sandbox stats retrieval

Makefile, internal/config/conmonmgr/conmonmgr.go, internal/config/conmonmgr/conmonmgr_test.go, internal/dbusmgr/user.go, internal/oci/oci.go, internal/oci/runtime_oci.go, internal/runtimehandlerhooks/high_performance_hooks.go, internal/runtimehandlerhooks/utils.go, pkg/config/config.go, test/mocks/cmdrunner/cmdrunner.go, utils/cmdrunner/cmdrunner.go, utils/cmdrunner/cmdrunner_test.go, utils/cmdrunner/cmdrunner_test_inject.go, utils/cmdrunner/suite_test.go, utils/utils.go
/kind feature
```release-note
Add functionality to use taskset to spawn new commands cri-o runs. Now, if InfraCtrCPUSet is called, all newly spawned commands will be placed in the InfraCtrCPUSet (as it's expected to be set to the reserved CPU set that system commands should run on).
```
=> [1.20] various deadlock backports

install.md
Signed-off-by: Wang Kai <persistence201306@gmail.com>
The installation instructions of Debian should be improved
Fixes #5598 
add `Debian_11` OS variable 
```release-note
none
```
=> Add Debian_11 OS variable on installation instructions of Debian

internal/oci/runtime_oci.go
/kind bug
It is impossible to debug what happened in conmon if it doesn't write to syslog. For some reason, syslog logging was only enabled when the cgroupmanager was cgroupfs, which I find odd and incorrect. fix this
```release-note
conmon now always writes its logs to syslog, instead of only when the cgroup manager is cgroupfs
```
=> oci: always have conmon log to syslog

internal/lib/sandbox/sandbox.go, internal/oci/container.go
Unfortunately, since each struct has state, if we directly edit the structure then protobuf panics
/kind bug
```release-note
fix an issue where protobuf panics when serializing ListContainer and ListPodSandbox calls
```
=> deep copy List{PodSandbox,Container} structs

contrib/bundle/build, contrib/bundle/vars, scripts/release-notes/release_notes.go, scripts/upload-artifacts
/kind ci
Provide checksum details for the uploaded artifacts.
Fixes #5600
Following checksum files would be generated for each artifacts.
```
Download one of our static release bundles via our Google Cloud Bucket:
cri-o.amd64.9b7f5ae815c22a1d754abfbc2890d8d4c10e240d.tar.gz
cri-o.amd64.9b7f5ae815c22a1d754abfbc2890d8d4c10e240d.tar.gz.sha256sum
cri-o.arm64.9b7f5ae815c22a1d754abfbc2890d8d4c10e240d.tar.gz
cri-o.arm64.9b7f5ae815c22a1d754abfbc2890d8d4c10e240d.tar.gz.sha256sum
```
```release-note
None
```
=> Add checksum details for artifacts

internal/oci/oci.go, internal/oci/runtime_vm.go
/kind bug
When cri-o is running with kata runtime, cri-o could not restore containers correctly after it restarts. The `containerd-shim-kata-v2` and `qemu-system-x86_64` processes are leak every time.
This PR attempts to restore containers properly with the existing `containerd-shim-kata-v2` and `qemu-system-x86_64` processes. `containerd-shim-kata-v2` writes the gRPC socket address under container bundle path with a file named `address`. After cri-o restarts, we can read from that file for shim socket address and connect to. Besides, we also need to restore the container io so that we can exec or attach the container.
I tested these changes on our internal cluster, everything worked well.
Fixes https://github.com/cri-o/cri-o/issues/2112 https://github.com/cri-o/cri-o/issues/5569 …
=> Fix vm containers could not restore after CRI-O restart

contrib/bundle/test-e2e
Don't pass the deprecated `--non-masquerade-cidr` command line option to `kubelet`. It was recently removed altogether and now breaks tests in CI.
None
```release-note
None
```
=> contrib/bundle: remove deprecated kubelet option.

utils/utils.go
This is easier, and as an added bonus `f.Sync()` retries on `EINTR`.
=> utils: Sync: use f.Sync

internal/config/apparmor/apparmor.go, test/apparmor.bats
/kind bug
Specifying a `localhost/` profile for AppArmor would run containers as
unconfined and not the selected default profile. This means we now check
that case explicitly and error if so.
None
None
```release-note
Forbid AppArmor profiles with the name `localhost/`.
```
=> Deny empty `localhost/` AppArmor profiles

test/crio-wipe.bats
Commit 6c69b44953 remove bats "run" from `run_podman_with_args`, meaning
variables $output and $status are no longer set after using it.
Commit f48f90d365 added a new test case which checks $output. Most
probably the $output is not even set, so the check isn't working.
Fix by using podman container exists which is the most straightforward
check.
Use the same check in `start_crio_with_stopped_pod`.
```release-note
NONE
```
=> test/crio-wipe: fixups

Makefile, dependencies.yaml, test/apparmor.bats, test/cni_plugin_helper.bash, test/test_runner.sh
/kind ci
/kind cleanup
Bumps shellcheck to 0.8.0, fixes or suppresses new warnings.
None
```release-note
NONE
```
=> Bump shellcheck to 0.8.0, fix or suppress new warnings

pkg/config/config.go, pkg/config/config_test.go
Inherits graphroot, runroot, storage_driver from storage.conf if these configs of crio.conf [crio] is "".
Fix: https://bugzilla.redhat.com/show_bug.cgi?id=2034296
```release-note
Inherits storage configs from storage.conf if crio config does not set.
```
=> [Bug 2034296] Inherits storage configs from storage.conf if crio config does not set

.gitpod.Dockerfile
/kind bug
This PR makes this repo compile in Gitpod again.
- Use the latest version of the `gitpod/workspace-full` image by explicit tag to get the latest Go version
- added package `libgpgme-dev` to fix compile error
Fixes #5664
Rebuilding the new docker image may take a few minutes. 
```release-note
None
```
=> [gitpod] use latest workspace full

internal/lib/container_server.go, internal/lib/stop.go, internal/oci/oci.go, internal/oci/runtime_oci.go, internal/oci/runtime_vm.go, test/mocks/oci/oci.go
/kind cleanup
both oci and vm runtimes do wait until the container state is stopped before returning
the only new piece of work WaitContainerStateStopped did was update container status.
Drop WaitContainerStateStopped and call UpdateContainerStatus in its place
```release-note
none
```
=> oci: drop WaitContainerStateStopped

pkg/config/sysctl.go, pkg/config/sysctl_test.go, test/pod.bats
pinns doesn't understand 'key = value', but rather 'key=value'
/kind bug
```release-note
Fix a bug where invalid default_sysctls could be specified, leading to an error like "Failed to configure sysctls after unshare: No such file or directory"
```
=> config/sysctls: validate against invalid spaces

contrib/test/integration/build/kubernetes.yml, contrib/test/integration/main.yml, dependencies.yaml, scripts/versions
/kind ci
Use kubernetes 1.23, cri-tools 1.23 in CI, since this is 1.23 branch.
None
```release-note
NONE
```
=> [1.23] CI: use kubernetes 1.23, cri-tools 1.23

server/server.go, utils/utils.go
/kind bug
Fsync is not enough when sync'ing the storage to disk, because it would sync only the directory inode metadata.
Instead use syncfs to persist all the changes to the underlying file system.
```release-note
None
```
=> server: use syncfs instead of fsync

test/helpers.bash
Use per-test crictl configuration files to ensure concurrent
tests don't stumble upon each other while updating the crictl
(othrewise global) configuration file.
/kind ci
During test setup `crictl config --set` is used to alter/disable the default image pulling
logic. By default the configuration file where this information is written to and subsequently
read from is `/etc/crictl.yaml` and it is shared among all test cases. `crictl` uses golang's
`ioutil/os.WriteFile()` to update the file content in place. This is suspected to cause occasional
failures where multiple test cases are being run/set up in parallel and read/write concurrently
that single shared file. The error manifests itself with occasional failures like this: 
```
not ok 72 ctr /etc/resolv.conf rw/ro mode
```
This PR …
=> test: avoid concurrent crictl config writes.

server/container_create.go, server/container_create_linux.go, server/sandbox_run_linux.go
Backport https://github.com/cri-o/cri-o/pull/4923 to release-1.19
The current implemention has an issue where we add the default
capabilties when the user does drop ALL and add few.
```release-note
Fix drop ALL and add back few caps behavior to not include the default configured capabilities
```
=> [release-1.19] Add support to drop ALL and add back few capabilities

contrib/test/integration/build/bats.yml, contrib/test/integration/main.yml
/kind ci
Currently CI nodes are expected to be set up correctly by regularly scheduled
ansible runs with the `setup` tag. However, empirical evidence (logging BATS
version from `integration` runs on CI nodes) proves that many of the CI nodes
are still running older versions (1.2.1 or 1.2.1-dev).
So instead of relying nodes to get independently set up with the correct BATS
version this PR installs that one right before running the tests. Furthermore, it
makes sure that the freshly installed version is correctly symlinked in place, to
replace any previously present/distro-provided versions.
None
```release-note
None
```
=> CI: always install required BATS version.

test/cgroups.bats
Don't dereference $TESTDATA before the test case is set up. The incorrect setup order prevents `cgroups.bats`
tests from being properly isolated from each other, causing very often `localintegration` cgroups tests to fail in github workflows or OpenShift CI.
/kind ci
Don't dereference $TESTDATA before the test case is set up.
Doing otherwise breaks proper isolation of test cases. This
manifests itself in many ways, since concurrently cgroups
BATS tests can now interfere with each other when mangling
test input data. The most typical symptom is the expected
memory limit being incorrect in one of the test cases like
this:
```
not ok 14 cgroupv2 unified support
(in test file ./cgroups.bats, line 103)
`[[ "$output" == *"209715200"* ]]' failed
```
None
Like the BATS installation fixing bits, …
=> test/cgroups.bats: fix incorrect setup order.

test/crio-wipe.bats
Delay running `cleanup_test()`, and thus removing $TESTDIR,
after having stopped and removed containers using a podman
wrapper function, which in turn uses directories relative
to $TESTDIR.
/kind ci
The order of calling `cleanup_test()` and the test-specific podman
wrapper function is the wrong way around. The latter tries to use
directories relative to $TESTDIR which is removed by the former.
It is not known if this causes any GH workflow or CI test failures
but it is probably a good idea to fix the ordering anyway.
None
```release-note
None
```
=> test/crio-wipe.bats: fix test case teardown ordering.

test/helpers.bash, test/test_runner.sh
Allow tests to be kept intact upon failure for better debugging and diagnosing.
/kind other
Allow tests to be kept intact upon failure for better debugging and diagnosing. If set, the newly introduced `TEST_KEEP_ON_FAILURE` variable causes failing tests to skip their teardown phase, leaving all test artifacts and any related cri-o instances intact.
This should allow one to look for flakes locally with something like this:
`while true; do TEST_KEEP_ON_FAILURE=1 JOBS=8 ./test/test_runner.sh || break; done`
None
```release-note
None
```
=> test: allow state of failing tests to be kept intact.

Makefile
/kind bug
Pin nixos/nix version
Newer nix versions fail with:
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override
=> Pin nixos/nix version

SECURITY.md, SECURITY_CONTACTS
This also publishes the new CNCF security mailing list for reporting vulnerabilities.
None
cc @mrunalp @haircommander 
We also remove @runcom and @rhatdan from the security contacts because they became emeritus approvers.
```release-note
None
```
=> Add dedicated security information

scripts/get
/kind bug
/kind ci
We forgot to rename the branches in the script which basically pins CRI-O back to the renaming point.
None
None
```release-note
Fixed `get` script pointing to `main` instead of `master` for retrieving the latest revision.
```
=> Switch to `main` for `get` script

contrib/bundle/install, scripts/get, scripts/node_e2e_installer
/kind feature
This allows SELinux enabled distributions to automatically set the right contexts.
None
None
```release-note
Automatically `chcon` and `restorecon` on get script for SELinux enabled distributions.
```
=> Automatically `chcon` and `restorecon` on get script

completions/fish/crio.fish, contrib/test/integration/critest.yml, docs/crio.8.md, docs/crio.conf.5.md, internal/config/seccomp/seccomp.go, internal/criocli/criocli.go, pkg/config/config.go, test/critest.bats, test/ctr_seccomp.bats
/kind feature
This is a premature step before the graduation of the `seccompDefault`
feature planned for Kubernetes v1.25. We now use the `runtime/default`
profile for every workload specifying none (empty) in the pod manifest.
None
None
```release-note
Enable `--seccomp-use-default-when-empty`/`seccomp_use_default_when_empty` by default.
This is a premature step before the graduation of the `seccompDefault` feature planned for
Kubernetes v1.25. We now use the `runtime/default` profile for every workload specifying 
none (empty) in the pod manifest. 
```
=> Enable `--seccomp-use-default-when-empty` by default

internal/config/nsmgr/nsmgr.go, pinns/src/pinns.c, pinns/src/sysctl.c, pinns/src/sysctl.h
/kind cleanup
Use repeated '-s' arguments to pass sysctls keys and values to pinns to replace the serialization in cri-o and parsing in pinns.
To simplify the logic, this allocates an 'argc/2' sized array to store the pointers to the sysctls `k=v` pairs. This array will in most cases be much bigger than what is really needed but this should be safe as argc is limited in size on Linux.
This is a followup fix for https://github.com/cri-o/cri-o/security/advisories/GHSA-6x2m-w449-qwx7.
None
```release-note
None
```
=> pinns: Pass sysctls as repeated '-s' arguments

test/pod.bats, test/workloads.bats
In #5500, defensive code was added to ensure all child processes are
cleaned up when conmon early initialization fails.  This bats test
forces one of the error scenarios (by adding an unparseable workload
annotation to a container) and then ensures no zombies leak in this
failure scenario.
Verified by temporarily reverting #5500 (test fails with 10 zombies
created), then bringing back #5500 (test passes)
Signed-off-by: Jim Ramsay <jramsay@redhat.com>
/kind cleanup
Adds bats testing for the issue originally fixed in #5000
```release-note
None
```
=> Add bats test for zombie conmon cleanup

.github/workflows/verify.yml, .golangci.yml, Makefile, dependencies.yaml, internal/client/client.go, internal/config/cnimgr/cnimgr.go, internal/hostport/fake_iptables.go, internal/hostport/meta_hostport_manager.go, internal/lib/stats/stats_server.go, internal/log/klog.go, internal/oci/runtime_oci.go, internal/oci/runtime_oci_test.go, internal/process/defunct_processes_test.go, internal/resourcestore/resourcestore.go, pkg/config/config.go, server/image_pull.go, server/inspect_ginkgo_test.go
/kind cleanup
We now update the golangci-lint version to the latest release as well as
the configuration. This enables the linters bidichk, decorder, errchkjson,
grouper, tenv as well as new gocritic linters and fixes their reports.
None
None
```release-note
None
```
=> Update golangci-lint and config

internal/oci/container.go, internal/oci/runtime_oci.go, test/ctr.bats
by only closing the stopStoppingChan once
/kind bug
```release-note
fix a segfault when multiple container stops come in for the same container
```
=> oci: fix segfault in pod stop code

server/label_linux.go, test/selinux.bats
/kind bug
If you try to use the annotation: io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel, It doesn't work because, the selinux label with the mcs from the annotation in the namespace, has the wrong order in the mcs.
```
$ oc get project test -o yaml | grep mcs
openshift.io/sa.scc.mcs: s0:c75,c35
```
The selinux label for the comparison with the label in the filesystem will be:  **system_u:object_r:container_file_t:s0:c75,c35**
but in the filesystem the label is: **system_u:object_r:container_file_t:s0:c35,c75**
None
```release-note
Fixed `io.kubernetes.cri-o.TrySkipVolumeSELinuxLabel` annotation usage with the OpenShift MCS.
```
=> server: Canonize selinux label for comparison with filesystem label

internal/runtimehandlerhooks/high_performance_hooks.go
/kind bug
It is possible that the kernel will rebuild sched_domain related files and
because of it enabling or disabling CPU load balancing for container CPUs
will fail with different file errors:
1. lstat /proc/sys/kernel/sched_domain/cpu22/domain1/flags: no such file or directory
2. readdirent /proc/sys/kernel/sched_domain/cpu66/domain0: no such file or directory
Add retry logic around setting CPU load balancing values to reduce the possibility of such errors.
```release-note
NONE
```
Signed-off-by: Artyom Lukianov <alukiano@redhat.com>
=> Bug 1977100: retry setting CPU load balancing

pinns/src/pinns.c
/kind cleanup
This is unlikely to ever happen but let's do it just to be safe.
Fixes: 1af1f8af2 pinns: Pass sysctls as repeated '-s' arguments
```release-note
None
```
=> pinns: Check calloc return value

internal/oci/container.go, internal/oci/runtime_oci.go, test/ctr.bats
by only closing the stopStoppingChan once
cherry-pick of https://github.com/cri-o/cri-o/pull/5782
/kind bug
```release-note
fix a segfault when multiple container stops come in for the same container
```
=> [1.22] oci: fix segfault in pod stop code

server/container_create_linux.go
Disable systemd-mode cgroup detection if /sys/fs/cgroup is bind mounted from the host 
/kind bug
Disable systemd-mode cgroup detection if /sys/fs/cgroup is bind mounted from the host
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=2064741
```release-note
Disable systemd-mode cgroup detection if /sys/fs/cgroup is bind mounted from the host 
```
=> Bug 2064741: Disable systemd-mode cgroup detection if /sys/fs/cgroup is bind mounted from the host

go.mod, go.sum, vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/doc.go, vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/spec.go, vendor/modules.txt
Pin container-device-interface dependencies to the latest version tagged in upstream.
Pins container-device-interface dependencies to the latest tagged version in upstream.
None
```release-note
None
```
=> go.{mod,sum}: update CDI dependency to v0.3.2.

internal/oci/runtime_oci.go, internal/oci/runtime_vm.go, test/ctr.bats
/kind bug
```release-note
fix a bug where CRI-O would leak a log file if a container failed to be created and the pod hadn't yet been cleaned up. 
```
=> oci: cleanup log path if the container failed to create

test/pod.bats
Signed-off-by: Jim Ramsay <jramsay@redhat.com>
/kind ci
Adds a bats test to ensure namespace cleanup happens as a result of pod stop.
None
```release-note
None
```
=> Add bats test to ensure namespaces are cleaned up on pod stop

.github/workflows/test.yml, internal/hostport/hostport_manager.go, internal/hostport/hostport_manager_test.go, internal/hostport/meta_hostport_manager_test.go, scripts/github-actions-packages
We can use netlink call directly
Signed-off-by: Antonio Ojea <antonio.ojea.garcia@gmail.com>
Fixes: #5807
/kind bug
```release-note
crio no longer requires the conntrack binary
```
=> remove the external dependency on the conntrack binary

internal/lib/stats/stats_server.go
/kind bug
Fix  broken container disk usage stats  on zfs driver
Fixes #5820 
I'm not sure if the same problem happens with other drivers than `zfs` and `overlayfs`. may more tests required.
None
```release-note
fix filesystem stats on zfs driver.
```
=> fix(stats): incorrect id on zfs driver

server/sandbox_network.go, server/utils.go
to be more flexible with changes to runtime-request-timeout
/kind bug
```release-note
Internal pod and container creation timeouts now account for changes in `runtime-request-timeout` in the Kubelet
```
=> server: no longer use hardcoded timeouts

internal/config/seccomp/seccomp.go, internal/config/seccomp/seccomp_test.go, test/ctr_seccomp.bats
when it comes to confining processes, having a contained process have access to unshare has historically lead to a host of vulnerabilities. CRI-O attempts to be secure by default, so in addition to adding a seccomp profile by default, we should also drop unshare by default, unless a container has CAP_SYS_ADMIN
```release-note
Block containers without CAP_SYS_ADMIN on `unshare` syscall in the default seccomp profile, to better contain unprivileged container processes.
```
=> seccomp: drop unshare syscall from default profile

.github/workflows/test.yml
/kind bug
This fixes the availablility of the SHA files in the bucket.
Refers to https://github.com/cri-o/cri-o/issues/5600
None
```release-note
None
```
=> Add sha256sum bundle files to uploaded artifacts

server/container_create_linux.go
/kind bug
The changes introduced in https://github.com/cri-o/cri-o/pull/5778 weren't perfect. When iterating over the mount options of the sysfs mount provided in the pod definition will not have `rbin` or `bind` set. This causes that fix to not work. I might have goofed up in testing and might have tested with https://github.com/cri-o/cri-o/compare/240e311ea8e9daeb2ba34a2e81000c4560215421..9a7037b9f87f94120e3f8df33e8cd3729a60bb38 instead of the final version by mistake. Apologies for that. 
But I just tested this patch with 4.10 and 4.11 nightlies and it seem to fix this issue now. 
Fixes # https://bugzilla.redhat.com/show_bug.cgi?id=2064741
```release-note
None
```
=> Move WillRunSystemd call after iterating the mounts 

cmd/crio/main.go
/kind bug
`reexec.Init()` returning true is an indication that a handler was invoked and that we should return immediately because we're not the parent process.  It isn't an error condition, and we shouldn't be treating it as an error.
h/t to @adrianreber who asked about this while working on something else.
```release-note
None
```
=> main(): do not treat reexec.Init() == true as an error

server/container_status.go
crio:fix a bug about log container
Signed-off-by: jiang wei <jwcesign@gmail.com>
/kind bug
When container is in unknown state, will have this error when log it(using critl and kubectl).
fix bug to log container, in upper layer interface, we need `status.CreatedAt`
none
```release-note
none
```
=> crio:fix a bug about log container

contrib/test/ci/cri-o.spec
/kind ci
After the merge of https://github.com/openshift/release/pull/27332 we should be able to use the pod runtime again in the packages.
None
None
```release-note
None
```
=> Reenable pod runtime in package spec

dependencies.yaml, internal/config/cgmgr/cgmgr.go, internal/oci/runtime_oci.go, pkg/config/config.go, pkg/config/template.go, scripts/versions
/kind bug
Currently, exec sync containers are launched under the crio cgroup. For applications with a large number of exec probes, this can impact cpu usage for reserved platform cores, in addition to affecting accounting. To address this, this PR introduces an opt-in exec_cgroup option (defaults to false) that moves the exec probe process to the pod's cgroup. This ensures cpu usage and resource accounting are restricted to the pod's allowances.
None
```release-note
Add `monitor_exec_cgroup` to the configuration's runtime handler struct. This allows an admin to specify which cgroup the monitor for exec sync requests runs in (defaults to that of CRI-O).
```
=> Exec cgroup

Makefile, cmd/crio-status/main.go, cmd/crio/main.go, cmd/crio/version.go, completions/fish/crio.fish, docs/crio.8.md, internal/version/buildtag_apparmor.go, internal/version/buildtag_devicemapper.go, internal/version/buildtag_openpgp.go, internal/version/buildtag_ostree.go, internal/version/buildtag_seccomp.go, internal/version/buildtag_selinux.go, internal/version/version.go, pkg/config/config.go, server/useragent/useragent.go, server/useragent/useragent_test.go, server/version.go
/kind feature
This allows adding more information to the version output, for example listing all of its dependencies. We can also get rid of the build tag retrieval and some other `-X` ldflags.
None
Demo:
```
> ./bin/crio version -v
Version:        1.24.0
GitCommit:      d256f1b07b02219451c4ece7472cf8a9afb4a581
GitCommitDate:  2022-03-24T07:21:42Z
GitTreeState:   dirty
BuildDate:      1980-01-01T00:00:00Z
GoVersion:      go1.18rc1
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:      
containers_image_ostree_stub
apparmor
containers_image_openpgp
seccomp
selinux
LDFlags:          -s -w -X github.com/cri-o/cri-o/internal/pkg/criocli.DefaultsPath="" -X github.com/cri-o/cri-o/internal/version.buildDate=1980-01-01T00:00:00Z 
SeccompEnabled:   true …
```
=> Use go 1.18 buildinfo for version output

.github/workflows/test.yml
Add standard CodeQL Github actions with autobuild.
/kind ci
CodeQL is a static analysis tool and we need it because it can help find bugs. CodeQL is an official Github product: https://github.com/github/codeql-action
None
No, unless the CI is considered a user-facing change, am not sure? 
```release-note
none
```
=> Add CodeQL Github actions

OWNERS
Hey CRI-O team, since I will not be able to fulfill the CRI-O reviewer duties (in the near future at least), I propose to demote myself from 'Reviewer' to 'Community Member', as per our [GOVERNANCE](https://github.com/cri-o/cri-o/blob/main/GOVERNANCE.md).
This PR will remove myself from the CRI-O OWNERS file.
=> OWNERS: remove fgiudici

server/server.go
/kind feature
There are environments where the umask of CRI-O is set to something more open, for example `0o000`. To have a standard behavior across all containers we now use a default umask of `0o022` while informing the user via an info log if that change has been done.
Refers to https://bugzilla.redhat.com/show_bug.cgi?id=2040612
None
```release-note
Use default umask `0o022` if CRI-O runs under a different umask value.
```
=> Use a default umask of `0o022`

internal/oci/container.go, internal/oci/runtime_oci.go, test/ctr.bats
When PID 1 of a PID namespace is killed, all of the remaining processes are also killed.
However, for containers with a host PID namespace, this does not happen.
While we will eventually kill these processes when the kubelet tears down the sandbox's cgroup,
it looks like a leak (and could cause weird situations with duplicated processes running)
Fix it by killing the processes in this case.
/kind bug
```release-note
Fix a bug where child processes of containers in the host's PID namespace appear to leak after the child exits
```
=> oci: kill children of container if it is in the host pid namespace

.github/workflows/verify.yml
Apparently, ubuntu-latest now comes with a recent version of golang,
which is too new for golangci-lint we use in this branch. As a result,
we have errors like
...could not import internal/goarch (-: could not load export data: cannot import \"internal/goarch\" (unknown iexport format version 2), export data is newer version - update tool)))))]]"
Explicitly installing golang 1.16 and upgrading the action itself should fix the issue.
/kind ci
```release-note
NONE
```
=> [1.21] ci/gha: fixup golangci-lint job

internal/config/conmonmgr/conmonmgr.go, internal/config/conmonmgr/conmonmgr_test.go, internal/oci/oci.go, internal/oci/runtime_oci.go, internal/oci/runtime_oci_test.go, internal/oci/runtime_vm.go, internal/version/version.go, pkg/config/config.go, test/ctr.bats, vendor/k8s.io/kubernetes/pkg/kubelet/util/ioutils/ioutils.go, vendor/modules.txt
=> [1.24] oci: add support for capping memory and disk usage from exec sync output

internal/config/conmonmgr/conmonmgr.go, internal/config/conmonmgr/conmonmgr_test.go, internal/oci/oci.go, internal/oci/runtime_oci.go, internal/oci/runtime_oci_test.go, internal/oci/runtime_vm.go, internal/version/version.go, pkg/config/config.go, test/ctr.bats, vendor/k8s.io/kubernetes/pkg/kubelet/util/ioutils/ioutils.go, vendor/modules.txt
=> [1.22] oci: add support for capping memory and disk usage from exec sync output

internal/config/conmonmgr/conmonmgr.go, internal/config/conmonmgr/conmonmgr_test.go, internal/oci/oci.go, internal/oci/runtime_oci.go, internal/oci/runtime_oci_test.go, internal/oci/runtime_vm.go, internal/version/version.go, pkg/config/config.go, test/ctr.bats, vendor/k8s.io/kubernetes/pkg/kubelet/util/ioutils/ioutils.go, vendor/modules.txt
=> [1.23] oci: add support for capping memory and disk usage from exec sync output

utils/utils.go
As seen in [1], sometimes coreos/go-systemd/dbus package deadlocks: the
jobCompete is stuck trying to send job result string to the channel
while holding the jobListener lock, while startJob (called by
StartTransientUnit) waits for the same lock.
Alas, it is not clear why the channel is not being read, nor was I able
to reproduce it locally.
Make the job result channel buffered, so jobJistener won't block on
channel send and thus StartTransientUnit won't be stuck either.
While at it,
- move the error wrapping out of mgr.RetryOnDisconnect function,
and use fmt.Errorf with %w instead of obsoleted errors.Wrap;
- improve error messages, printing the systemd unit name (so we can
check it in systemd log);
- do check the job result string -- in case it is not "done",
return an error back to the …
=> utils/RunUnderSystemdScope: fix wrt channel deadlock

conmon/conmon.c, oci/oci.go
/kind bug
```release-note
Fix a bug where ExecSync requests (exec probes) could use an arbitrary amount of memory and disk. Output from ExecSync requests is now limited to 16MB (the amount that exec output was limited to in the dockershim). See https://github.com/cri-o/cri-o/security/advisories/GHSA-fcm2-6c3h-pg6j and CVE-2022-1708 for more information.
```
=> [1.11] oci: add support for capping memory and disk usage from exec sync output

internal/oci/container.go, internal/oci/runtime_oci.go, test/ctr.bats
When PID 1 of a PID namespace is killed, all of the remaining processes are also killed.
However, for containers with a host PID namespace, this does not happen.
While we will eventually kill these processes when the kubelet tears down the sandbox's cgroup,
it looks like a leak (and could cause weird situations with duplicated processes running)
Fix it by killing the processes in this case.
/kind bug
```release-note
Fix a bug where child processes of containers in the host's PID namespace appear to leak after the child exits
```
=> [1.24] oci: kill children of container if it is in the host pid namespace

internal/config/conmonmgr/conmonmgr.go, internal/config/conmonmgr/conmonmgr_test.go, internal/oci/oci.go, internal/oci/runtime_oci.go, internal/oci/runtime_oci_test.go, internal/oci/runtime_vm.go, internal/version/version.go, pkg/config/config.go, test/ctr.bats, vendor/k8s.io/kubernetes/pkg/kubelet/util/ioutils/ioutils.go, vendor/modules.txt
=> [1.21] oci: add support for capping memory and disk usage from exec sync output

internal/config/conmonmgr/conmonmgr.go, internal/config/conmonmgr/conmonmgr_test.go, internal/oci/oci.go, internal/oci/runtime_oci.go, internal/oci/runtime_oci_test.go, internal/oci/runtime_vm.go, internal/version/version.go, pkg/config/config.go, test/ctr.bats, vendor/k8s.io/kubernetes/pkg/kubelet/util/ioutils/BUILD, vendor/k8s.io/kubernetes/pkg/kubelet/util/ioutils/ioutils.go, vendor/modules.txt
=> [1.20] oci: add support for capping memory and disk usage from exec sync output

go.mod, go.sum, vendor/github.com/containernetworking/cni/pkg/invoke/exec.go, vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go, vendor/github.com/cri-o/ocicni/pkg/ocicni/util_linux.go, vendor/modules.txt
```release-note
Fix a panic caused by using the improper Result structure version when setting up CNI plugins
```
=> [1.24] bump ocicni to 0.4.0

internal/config/conmonmgr/conmonmgr.go, internal/config/conmonmgr/conmonmgr_test.go, internal/oci/oci.go, internal/oci/runtime_oci.go, internal/oci/runtime_oci_test.go, internal/oci/runtime_vm.go, internal/version/version.go, pkg/config/config.go, test/ctr.bats, vendor/k8s.io/kubernetes/pkg/kubelet/util/ioutils/BUILD, vendor/k8s.io/kubernetes/pkg/kubelet/util/ioutils/ioutils.go, vendor/modules.txt
=> [1.19] oci: add support for capping memory and disk usage from exec sync output

internal/oci/container.go, internal/oci/runtime_oci.go, test/ctr.bats
When PID 1 of a PID namespace is killed, all of the remaining processes are also killed.
However, for containers with a host PID namespace, this does not happen.
While we will eventually kill these processes when the kubelet tears down the sandbox's cgroup,
it looks like a leak (and could cause weird situations with duplicated processes running)
Fix it by killing the processes in this case.
/kind bug
cherry-pick of https://github.com/cri-o/cri-o/pull/5943
```release-note
Fix a bug where child processes of containers in the host's PID namespace appear to leak after the child exits
```
=> [1.23] oci: kill children of container if it is in the host pid namespace

internal/resourcestore/resourcecleaner.go, server/container_create.go, server/sandbox_run_linux.go
/kind cleanup
- move cleanup func closer to the resource provisioning it is cleaning up
- deduplicate code by moving the logging into the retry func
- replace uses of fmt.Sprintf with string concatenation 
```release-note
none
```
=> server: cleanup cleanup funcs

.github/workflows/integration.yml, .github/workflows/test.yml, .github/workflows/verify.yml, Makefile, scripts/get, scripts/github-actions-setup, scripts/sign-artifacts
/kind feature
We now sign our static binary bundle via cosign keyless signing.
None
None
```release-note
We now sign the static binary bundle via sigstore signatures. This also includes support for the [get script](https://github.com/cri-o/cri-o/blob/main/scripts/get).
```
=> Sign static binary bundle via cosign

internal/oci/container.go, internal/oci/runtime_oci.go, test/ctr.bats
When PID 1 of a PID namespace is killed, all of the remaining processes are also killed.
However, for containers with a host PID namespace, this does not happen.
While we will eventually kill these processes when the kubelet tears down the sandbox's cgroup,
it looks like a leak (and could cause weird situations with duplicated processes running)
Fix it by killing the processes in this case.
/kind bug
cherry-pick of https://github.com/cri-o/cri-o/pull/5943
```release-note
Fix a bug where child processes of containers in the host's PID namespace appear to leak after the child exits
```
=> [1.22] oci: kill children of container if it is in the host pid namespace

server/container_create.go
/kind bug
```release-note
Fix CVE-2022-27652 by dropping and refusing to add any inheritable capabilities
```
=> [1.23] capabilities: drop inheritable

.github/workflows/stale.yml
/kind ci
We now mark issues and PRs as stale after a while. We also close them and mark the mas rotten if there has been no acidity. 
None
None
```release-note
None
```
=> Add stale bot workflow

scripts/node_e2e_installer
/kind ci
Updating the latest node e2e commit to test.
Refers to https://github.com/cri-o/cri-o/issues/5202
We still have to update everything in test-infra:
https://cs.k8s.io/?q=40cdd9c2d97384eb5601c1af28e7092cdda3815e&i=nope&files=&excludeFiles=&repos=kubernetes/test-infra
I'm wondering why do do not point those to `main` at all. :thinking: 
```release-note
None
```
=> Pin upstream node e2e test to latest `main`

.github/workflows/integration.yml, .github/workflows/test.yml, .github/workflows/verify.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

.github/workflows/stale.yml
/kind ci
I wasn't completely sure if that works but the default token should point to the GitHub actions bot rather than my account-bound token.
None
None
```release-note
None
```
=> Use default token for stale bot

scripts/release-notes/release_notes.go
/kind ci
I've tested this in a local environment by reproducing the checkout behavior of GitHub actions. This should fix the tag retrieval for the release notes generation.
Fixes: https://github.com/cri-o/cri-o/issues/5687
```release-note
None
```
=> Fix release-notes tag determination

.github/workflows/test.yml
/kind ci
Backport of https://github.com/cri-o/cri-o/pull/6012 `to release-1.24`.
Cherry-picked: 66d33db6b66c57dac4f3c6ff38d7da9cfd9b0559
None
None
```release-note
None
```
=> [release-1.24] Fix unit test coverage

internal/runtimehandlerhooks/high_performance_hooks.go, internal/runtimehandlerhooks/high_performance_hooks_test.go, internal/runtimehandlerhooks/runtime_handler_hooks.go, pkg/annotations/annotations.go
Adding the following high performance feature annotations:
cpu-c-states.crio.io: \<enable|disable>
This annotation will enable or disable c-states for each cpu by writing to the
power/pm_qos_resume_latency_us for the cpu under sysfs.
cpu-freq-governor.crio.io: \<any supported cpu frequency governor>
This annotation will set the cpufreq governor for each cpu by writing to the
cpufreq/scaling_governor for the cpu under sysfs.
When a container is stopped, the original pm_qos_resume_latency_us and
scaling_governor values are restored.
As with the other high performance feature annotations, the new annotations
are only considered for pods with a guaranteed QoS Class.
Signed-off-by: Bart Wensley <bwensley@redhat.com>
/kind feature
In order to support high performance (i.e. low latency) …
=> Add annotations to allow power management configuration

server/container_create_linux.go
/kind bug
Set masked and readonly paths based on the securityContext only.
Kubernetes as of v1.13 will always populate these based on
ProcMountType.
This can be used to allow running Docker within a container, with fewer contortions (particularly when combined with user namespaces this can be safer, as the container isn't root on the host, but root within a user namespace). Obviously there's other ways to achieve running containers within containers without this, but given this is an option the Kubernetes API supports (even if at alpha stage) it seems worthwhile supporting it.
Fixes #6009.
The list in CRI-O has /sys/dev in it from #4072, note however the code as it was before this change overwrites it with the list supplied from Kubernetes, so I am fairly sure this is not used. (I don't …
=> server: Fix Unmasked ProcMountType

utils/utils.go
As seen in [1], sometimes coreos/go-systemd/dbus package deadlocks: the
jobCompete is stuck trying to send job result string to the channel
while holding the jobListener lock, while startJob (called by
StartTransientUnit) waits for the same lock.
Alas, it is not clear why the channel is not being read, nor was I able
to reproduce it locally.
Make the job result channel buffered, so jobJistener won't block on
channel send and thus StartTransientUnit won't be stuck either.
While at it,
- move the error wrapping out of mgr.RetryOnDisconnect function,
and use fmt.Errorf with %w instead of obsoleted errors.Wrap;
- improve error messages, printing the systemd unit name (so we can
check it in systemd log);
- do check the job result string -- in case it is not "done",
return an error back to the …
=> [1.21] utils/RunUnderSystemdScope: fix wrt channel deadlock

cmd/crio/main.go, docs/crio.8.md, go.mod, go.sum, internal/criocli/documentation.go, test/helpers.bash, test/namespaces.bats, test/restore.bats, vendor/github.com/containers/kubensmnt/LICENSE, vendor/github.com/containers/kubensmnt/Makefile, vendor/github.com/containers/kubensmnt/README.md, vendor/github.com/containers/kubensmnt/kubensmnt.c, vendor/github.com/containers/kubensmnt/kubensmnt.go, vendor/github.com/containers/kubensmnt/kubensmnt.h, vendor/github.com/containers/kubensmnt/kubensmnt_linux.go, vendor/github.com/containers/kubensmnt/kubensmnt_nonlinux.go, vendor/modules.txt
/kind feature
This is in support of OpenShift Enhancement https://github.com/openshift/enhancements/pull/1127
CRI-O will now check whether `$KUBENSMNT` is set in the environment.  If this
environment variable is defined, assume the file it points at is a bindmount to
a mount namespace that CRI-O should join:
- If the environment variable is not set, take no action
- If the environment variable is set and points at a valid mount
namespace, join that mount namespace.
- If the environment variable is set but points at a missing file, or
the file is not a valid mount namespace, print a warning but continue
to run in the original mount namespace.
The approach makes use of a cgo init block to ensure the namespace is
joined before any go threads start up.
None
Ready for final review. Includes CI …
=> Enter mount namespace if set in $KUBENSMNT environment

Vagrantfile, contrib/test/ci/critest.yml, contrib/test/ci/critest_images.yml, contrib/test/ci/sync_images.sh, contrib/test/ci/vars.yml, contrib/test/integration/critest.yml, contrib/test/integration/vars.yml
Signed-off-by: Ryan Phillips <rphillips@redhat.com>
/kind other
This change adds a GCP setup to the Vagrantfile for CI development. It also adds quay.io mirrors of test images, so we are not throttled by docker.io.
Adds a shell script to mirror critest images with skopeo:
```
DESTINATION_REPO=quay.io/crio contrib/test/ci/sync_images.sh
```
```release-note
NONE
```
=> add GCP vagrant environment and mirror critest images

internal/runtimehandlerhooks/utils.go, internal/runtimehandlerhooks/utils_test.go
/kind bug
Make sure we do not add stray extra `\n` when the high performance hooks update the `/etc/sysconfig/irqbalance` file
Fixes #6086
N/A
```release-note
none
```
=> highperfhooks: avoid unbound growth of irqbalance

internal/oci/runtime_pod.go
/kind bug
If no stdin is provided, then we still wrapped the type in `&In{…}` which means that the nil check in `github.com/containers/conmon-rs/pkg/client/attach.go:204` cannot evaluate correctly. This caused a runtime panic like:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x293b0e9]
goroutine 695 [running]:
github.com/containers/conmon-rs/pkg/client.(*In).Read(0xc000fe7ec0?, {0xc0012f6000?, 0xc000fa6ef0?, 0x11846aa?})
<autogenerated>:1 +0x29
github.com/containers/common/pkg/util.CopyDetachable({0x349a2c0, 0xc000b7a080}, {0x3495060, 0xc000960d10}, {0x0, 0x0, 0x1?})
github.com/containers/common@v0.48.1-0.20220720100622-5e4fc04c2e94/pkg/util/copy.go:16 +0xa7 …
```
=> Fix possible panic in pod runtime attach

utils/utils.go
A slightly incorrect porting of https://github.com/cri-o/cri-o/pull/5914/commits/343bcdd8f793af
to main branch resulted in duplicated case statement in a switch. Remove it.
Fixes: 1e277b8364eb8e
/kind cleanup
```release-note
NONE
```
=> utils/RunUnderSystemdScope: fix

internal/oci/runtime_oci.go
UpdateContainer requests can come in at any time in a container's
lifecycle, even when it's shutting down.
In some cases, it can cause a container to get stuck: runc pauses the
cgroup on v1 and systemd to prevent systemd from mucking around while
the cgroup is being updated. In some cases, CRI-O calls
`UpdateContainerStatus` during that time, and gets `paused` state. CRI-O
does not expect a container to be paused, so it doesn't know how to
handle it.
Fix this by taking opLock when updating
/kind bug
related to https://bugzilla.redhat.com/show_bug.cgi?id=2094865
```release-note
fix a bug where a container is stuck in INIT because CRI-O believes it to be paused, and never updates the state
```
=> oci: take opLock for UpdateContainer

utils/utils.go
As seen in [1], sometimes coreos/go-systemd/dbus package deadlocks: the
jobCompete is stuck trying to send job result string to the channel
while holding the jobListener lock, while startJob (called by
StartTransientUnit) waits for the same lock.
Alas, it is not clear why the channel is not being read, nor was I able
to reproduce it locally.
Make the job result channel buffered, so jobJistener won't block on
channel send and thus StartTransientUnit won't be stuck either.
While at it,
- move the error wrapping out of mgr.RetryOnDisconnect function,
and use fmt.Errorf with %w instead of obsoleted errors.Wrap;
- improve error messages, printing the systemd unit name (so we can
check it in systemd log);
- do check the job result string -- in case it is not "done",
return an error back to the …
=> [1.20] utils/RunUnderSystemdScope: fix wrt channel deadlock

server/container_create.go
This reverts commit cfef9b7b9f26ae0673d5936a682b2a353ba0b633.
/kind bug
```release-note
Revert fix for CVE-2022-27652 by re-adding inheritable capabilities. While there is a workaround, we believe this causes regression mid cycle with is contrary to CRI-O's backporting policy. The risk of the CVE is low, and so there is little risk in reverting here. 
```
=> [1.23] Revert "capabilities: drop inheritable"

internal/config/cgmgr/cgmgr.go
It has been reported that sometimes pod creation fails with an
error like this one:
> cgroup: error creating cgroup path /pod_123.slice/pod_123-456.slice/crio-0dd29e75c4072e6d8227a338500c5a9a0cae2b41215c136150640c21e3e07fdf.scope: write /sys/fs/cgroup/pod_123.slice/pod_123-456.slice/cgroup.subtree_control: no such file or directory"
The error comes from containers/common/pkg/cgroups.New, which
eventually calls createCgroupv2Path, which does Mkdir immediately
followed by WriteFile, which fails with ENOENT.
It seems that this is caused by systemd which seems an unknown cgroup
hierarchy and removes it (in this case, in between Mkdir and WriteFile).
The solution is to not create paths when using systemd driver, since
systemd is going to create those for us.
Use cgroups.NewSystemd when …
=> cgmgr: use NewSystemd from createSandboxCgroup

server/metrics/metrics.go
/kind bug
Shutdowns the metric listener on cri-o termination.
```release-note
```
=> metrics: close listener on shutdown

contrib/custom-node-e2e/README.md, contrib/custom-node-e2e/create-ignition-config.sh, contrib/custom-node-e2e/upload-artifacts.sh, scripts/get
Signed-off-by: Swarup Ghosh <swghosh@redhat.com>
/kind other
Adds a script to generate a custom ignition config for running k8s-node-e2e test on Fedora CoreOS VM. It builds CRI-O locally in a container, prepares a bundle and uploads it to a GCP bucket for it to be used with the ignition config, which is consumed by the VM to install the custom cri-o build.
None
None
```release-note
None
```
=> [OCPNODE-1208] Add scripts to run node e2e tests using custom cri-o builds

server/container_create.go, server/sandbox_run_linux.go, test/timeout.bats
turns out, kubelet does behave like this in some scenerios (static
pods). Instead of failing forever, return the already created pod.
/kind bug
alternative to https://github.com/cri-o/cri-o/pull/6111
```release-note
Fix a bug where static pods cannot be created because they've already been created.
```
=> server: return already created ID for duplicated requests

contrib/test/ci/build/conmon-rs.yml, contrib/test/ci/build/cri-o.yml, contrib/test/ci/setup.yml, contrib/test/ci/vars.yml
/kind ci
This adds the conmonrs installation as well as usage to the ansible playbook, if the `USE_CONMONRS` environment variable is set to `true`.
None
PTAL @wgahnagl @rphillips @haircommander 
Refers to https://github.com/openshift/release/pull/32276
```release-note
None
```
=> Add conmon-rs e2e to ansible playbook

internal/resourcestore/resourcestore.go, internal/resourcestore/resourcestore_test.go, server/container_create.go, server/container_create_linux.go, server/sandbox_run_linux.go, server/utils.go
/kind feature
Often, users are met with the error "Kubelet may be retrying requests that are timing out in CRI-O..." but aren't provided with any details as to why.
This PR adds functionality that saves the stage of container and pod creations, as well as logs them. Now, users will be able to see where their pod or container is
```release-note
```
=> resource store: save stage of resource creation and report to callers

internal/factory/container/container.go, internal/factory/container/container_test.go
This reverts commit 3e9d7725714057d5fc2ce7eb9f905dc50c96647c.
It causes problems with non-root users attempting to specify capabilities.
```release-note
Fix a bug by re-adding the inheritable capabilities when adding capabilities. While it fixes an atypical unix environment, it causes a regression with non-root users using capabilities.
```
=> [1.24] Revert "capabilities: drop inheritable"

docs/crio.conf.5.md, pkg/config/config.go, pkg/config/reload.go, pkg/config/reload_test.go, test/reload_config.bats
/kind feature
This PR adds support for reloading runtime configs on SIGHUP. This allows for runtimes to be added dynamically and the default runtimes to be adjusted.
This is useful for cases where runtimes are added / configured after crio is started. One example of this is the NVIDIA Container Runtime which is managed by the NVIDIA GPU Operator. Without this change, adding a runtime to the config requires a node restart which is disruptive.
Fixes #6036
```release-note
Allow for a reload to add additional runtimes and change the default runtime
```
=> Allow runtimes to be added and default runtime to be modified on config reload

completions/bash/crio, completions/fish/crio.fish, completions/zsh/_crio, docs/crio.8.md, docs/crio.conf.5.md, internal/criocli/criocli.go, internal/factory/container/container.go, internal/factory/container/container_test.go, internal/factory/sandbox/infra.go, pkg/config/config.go, pkg/config/template.go, server/container_create_linux.go, test/ctr.bats
/kind feature
add an option to re-add the inheritable capabilities. there are situations where users previously expected non-root users to get these capabilities, which adding them to the inheritable list enabled. 
related to https://github.com/kubernetes/kubernetes/issues/111196 and https://github.com/cri-o/cri-o/security/advisories/GHSA-4hj2-r2pm-3hc6
```release-note
Add an option "add_inheritable_capabilities" which adds added capabilities to the inheritable list as well. As of CRI-O 1.24.0, CRI-O drops the inheritable capabilities to fix CVE-2022-27652 . However, this can cause regressions in workloads that attempt to pass capabilities to non-root users through inheritable capabilities. 
```
=> add "add_inheritable_capabilities" option

pkg/config/config.go, pkg/config/template.go, test/config.bats
This commit reverts d2ded1d73c9ce282028ec2b4d6016546267322a9 and adds a test that maintains what it was trying to do.
When upgrading from a cluster that uses runc to one that uses crun, there may be workloads that specifically request the old default. Those workloads will fail on restart. To fix this, don't remove runc from the map. We've since added code that means we don't fail if one of the non-default runtimes fails validation (if the binary doesn't exist) so we can handle that situation, which
d2ded1d73c9ce282028ec2b4d6016546267322a9 meant to fix.
/kind bug
```release-note
Fix a bug where updating `default_runtime` would cause the `runc` entry in the runtimes table to be deleted
```
=> config: do not remove runc if different default runtime

docs/crio.conf.5.md, pkg/config/reload.go, pkg/config/reload_test.go, test/reload_config.bats
/kind feature
This feature extends the work done for #6056 to allow for complete updates of the runtime configuration. The previous work limited the changes to the runtimes config to adding runtimes and updating the default runtime. These changes allow the complete `crio.runtime.runtimes` table to be updated on reload.
This was originally discussed in #6036.
None
```release-note
Allow `crio.runtime.runtimes` configuration to be updated on reload.
```
=> Allow runtime configs to be updated completely

pkg/config/config.go, pkg/config/config_test.go, test/config.bats
A situation arises when printing the config where
`translateMonitorFields` didn't previously run. This causes situations where the `conmon_cgroup` field looks like it's some other value, but the corresponding `monitor_cgroup` field does not reflect it
note: this is only a cosmetic change. The underlying config does eventually render correctly, just didn't print right.
/kind bug
```release-note
fix a bug where `conmon_cgroup` and `monitor_path` became out of sync
```
=> config: translate monitor fields when printing config

install.md
update supported os versions according to package url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/
The supported OS versions info is out of date.
Fixes #5240
Nothing.
No.
=> [#5240] update supported OS versions

test/README.md
This PR updates the url for the kata containers project as the current url is not longer valid.
Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>
=> test/README: Update url for kata containers

internal/lib/restore.go, internal/lib/restore_test.go, internal/oci/container.go, internal/oci/container_test.go, internal/oci/oci_test.go, internal/storage/image.go, internal/storage/image_test.go, pkg/annotations/checkpoint.go, scripts/github-actions-setup, scripts/versions, server/container_create.go, server/container_create_test.go, server/container_restore.go, server/container_restore_test.go, server/image_status.go, test/checkpoint.bats, test/helpers.bash
/kind feature
This adds the Podman support to export checkpoints to OCI images which can be pushed to registry to CRI-O.
With this change it is possible to do something like this:
```shell
```
The image `quay.io/adrianreber/checkpoint-image:tag1` can then be used on the same or another system to restore the container using `crictl create` and `crictl start`.
The image `quay.io/adrianreber/checkpoint-image:tag1` can also be used in Kubernetes to start a container from a checkpoint image without Kubernetes knowing that it is restore.
This PR is not targeting the 1.25.0 CRI-O release.
A side effect from this PR is that `crictl inspecti` will contain `spec.annotations`.
None
```release-note
This introduces the ability to store checkpoint archives as OCI images and push the checkpoint images …
```
=> support checkpointing to oci image

internal/lib/checkpoint.go, internal/lib/checkpoint_test.go, internal/lib/restore.go, internal/lib/restore_test.go, server/container_restore.go, test/checkpoint.bats
/kind feature
This commit has the following changes:
* Use ContainerConfig from checkpointctl and populate all fields
* Include stats-dump in the checkpoint archive to keep checkpointing statistics
Depends on: #6203
None
```release-note
None
```
=> Minor Checkpoint/Restore improvements

internal/lib/checkpoint.go, internal/lib/checkpoint_test.go, internal/lib/restore.go, internal/lib/restore_test.go, test/checkpoint.bats
/kind bug
/kind feature
This change is especially helpful to restore containers checkpointed in Kubernetes.
During restore CRIU remounts all bind mounts which have been mounted in the container during checkpointing. If the source of the bind mount is missing, because the restore is on another system or if the restore happens outside of Kubernetes and Kubernetes specific mount points are missing, CRIU will fail during restore.
Interestingly CRI-O creates all missing bind mount sources during container start automatically. During container restore this is
disabled, as CRI-O creates all missing bind mounts as directories.
One very prominent case where this produces an error during restore, is /etc/resolv.conf. CRI-O would create the source of this bind mount as a directory and CRIU will try …
=> Track bind mounts during checkpoint/restore

go.mod, hack/log-capitalized.sh, internal/log/interceptors.go, internal/log/log.go, internal/opentelemetry/tracing_config.go
/kind feature
We now use the log interceptor to enrich the otel traces with additional data. For example we now have detailed logging information from CRI-O and propagate the error to the traces.
None
For example, the output now looks like this on container creation:
And the error propagation looks like this:
Side note: We need the additional span to capture most of the logs, otherwise we will miss some information (see the error propagation).
cc @sallyom 
```release-note
Added logs and GRPC error codes to OpenTelemetry traces.
```
=> Add logs to OpenTelemetry traces

internal/resourcestore/resourcestore.go, internal/resourcestore/resourcestore_test.go, server/container_create.go, server/container_create_linux.go, server/sandbox_run_linux.go, server/utils.go
/kind feature
```release-note
```
=> [release-1.23] resource store: save stage of resource creation and report to callers

completions/fish/crio.fish, docs/crio.8.md, docs/crio.conf.5.md, internal/criocli/criocli.go, pkg/config/config.go, pkg/config/template.go
Updates the docs to hint how to enable sampling for every span.
Replaces https://github.com/cri-o/cri-o/pull/6322
None
```release-note
Updated CLI and config documentation to show how to enable Open Telemetry trace sampling for every span.
```
=> Add docs that `tracing-sampling-rate-per-million` set to 1000000 refers to always sample.

internal/oci/runtime_oci.go
/kind bug
The way I extended the PATH when calling conmon during restore was just wrong. This fixes the wrong PATH.
Fixes: #6337
```release-note
None
```
=> Correctly extend $PATH before calling conmon during restore

server/container_create.go
/kind other
To see if the specified container image is a checkpoint image, each image is checked, if it is a checkpoint image during container create. If checkpoint support is not enabled in CRI-O return as early as possible from this check without even looking at the image.
None
```release-note
None
```
=> Disable checkpoint image check as early as possible

pkg/config/template.go, test/config.bats
/kind bug
fixes https://github.com/cri-o/cri-o/issues/6188
```release-note
fix a segfault in `crio config` when `runtime.workloads.resources` is nil 
```
=> config: avoid segfault when workloads.resources is nil

contrib/test/ci/test.yml, contrib/test/ci/vars.yml
This is required to run a few integration tests with crun.
/kind ci
None
```release-note
None
```
=> contrib/test: set env variables for integration tests

.github/workflows/test.yml, .github/workflows/verify.yml, .golangci.yml, internal/factory/container/container.go, scripts/github-actions-packages
Fixing the failing GitHub actions CI.
Fixes https://github.com/cri-o/cri-o/issues/6396
None
```release-note
None
```
=> Fix GitHub actions CI

go.mod, go.sum, vendor/github.com/containers/storage/drivers/quota/projectquota.go, vendor/modules.txt
/kind bug
Incorporates https://github.com/containers/storage/pull/1325 into release-1.24.
This allows us to test it in CI before 1.26 gets released.
Refers to https://github.com/cri-o/cri-o/pull/6387 and https://github.com/cri-o/cri-o/pull/6390
/hold
for verification on release-1.25 branch.
```release-note
Fixed bug to restore `/var/lib/containers/storage/overlay/backingFsBlockDev` on XFS file systems.
```
=> [1.24] Bump c/storage to v1.37.3 (OCPBUGS-4470)

go.mod, go.sum, vendor/github.com/containers/storage/drivers/quota/projectquota.go, vendor/modules.txt
/kind bug
Incorporates https://github.com/containers/storage/pull/1325 into release-1.23.
This allows us to test it in CI before 1.26 gets released.
Refers to https://github.com/cri-o/cri-o/pull/6387 and https://github.com/cri-o/cri-o/pull/6389
/hold
for verification on release-1.24 branch.
```release-note
Fixed bug to restore `/var/lib/containers/storage/overlay/backingFsBlockDev` on XFS file systems.
```
=> [1.23] Bump c/storage to v1.37.3 (OCPBUGS-4471)

go.mod, go.sum, vendor/github.com/containers/storage/drivers/quota/projectquota.go, vendor/modules.txt
/kind bug
Incorporates https://github.com/containers/storage/pull/1325 into release-1.22.
This allows us to test it in CI before 1.26 gets released.
Refers to https://github.com/cri-o/cri-o/pull/6387 and https://github.com/cri-o/cri-o/pull/6389
/hold
for verification on release-1.23 branch.
```release-note
Fixed bug to restore `/var/lib/containers/storage/overlay/backingFsBlockDev` on XFS file systems.
```
=> [1.22] Bump c/storage to v1.34.2 (OCPBUGS-4472)

contrib/systemd/crio.service
/kind bug
There are some cases that cri-o should actually restart if it's failed (specifically, when network manager flips back and fourth). To prevent it from spamming a lot, give it restart seconds of 10 too
```release-note
Update systemd unit restart policy to be `on-failure`
```
=> systemd: use on-failure as restart policy

internal/resourcestore/resourcestore.go, server/container_create.go, server/sandbox_run_linux.go
ResourceStore leaks memory if entries added because the stage is saved are never removed. Fix this by deleting the entry after they're used
/kind bug
```release-note
Fix a bug where `internal/resourcestore.(*ResourceStore).SetStageForResource` leaks memory 
```
=> ResourceStore: cleanup created entries

server/container_create.go, test/ctr.bats
```release-note
Fix CVE-2022-4318 by failing to create container if it's passed a HOME environment variable with a newline
```
=> server: fail if HOME variable has a newline 

internal/oci/oci_linux.go, internal/oci/runtime_oci.go, internal/oci/runtime_pod.go, test/cgroups.bats
/kind bug
We didn't handle the case of moving conmonrs to the right
cgroup when infra container is dropped. This PR fixes that.
```release-note
Fix conmonrs cgroup when infra container is dropped
```
=> Fix conmonrs cgroup when infra container is dropped

server/container_status.go
/kind bug
Pod stuck in terminating state indefinitely until the kubelet is restarted as the crio-o responds with below response during the deletion process. 
```
Type     Reason      Age                    From     Message
----     ------      ----                   ----     -------
Warning  FailedSync  4m35s (x2331 over 8h)  kubelet  error determining status: status.CreatedAt is not set
```
This has larger impact when the nodes are being updated(or auto-scaled to low count) and they can't just go down as the pod is still at terminating state.
```
Nov 30 03:38:02  kubelet[5584]: I1130 03:38:02.145598    5584 kubelet.go:2142] "SyncLoop (PLEG): event for pod" pod="redacted POD NAME" event=&{ID:d522de36-73e7-4a24-a087-2a1dc4f85c31 Type:ContainerStarted Data:redacted}
Nov 30 03:38:02 …
```
=> [1.23] crio:fix a bug about log container

scripts/get
/kind ci
Fix the `get-script` job caused by `install: cannot stat 'contrib/10-crio-bridge.conflist': No such file or directory`
```release-note
None
```
=> get script: fix conflist path

scripts/node_e2e_installer
Signed-off-by: Sai Ramesh Vanka <svanka@redhat.com>
/kind ci
This code change helps in enabling the evented pleg feature in cri-o while running the CI(node e2e tests) jobs in the upstream k8s/test-infra
```release-note
None
```
=> OCPNODE-1336: Enable upstream CI to test node e2e with evented pleg feature

.github/workflows/test.yml, internal/config/seccomp/notifier.go, internal/config/seccomp/seccomp.go, internal/config/seccomp/seccomp_unsupported.go
This allows building crio.cross.linux.amd64 on non-linux platforms. The only thing which I needed to change was to add non-cgo stubs for seccomp. The main use-case for this is to avoid breaking the Linux build while refactoring to allow for a FreeBSD port of cri-o.
Signed-off-by: Doug Rabson <dfr@rabson.org>
/kind cleanup
This is useful to support porting cri-o to non-linux platforms.
None
```release-note
None
```
=> Allow cross building from non-linux

go.mod, go.sum, vendor/github.com/opencontainers/runtime-tools/validate/capabilities/validate_unsupported.go, vendor/modules.txt
This moves the hash one step forward to fix a package name mistake which affects non-linux builds.
Signed-off-by: Doug Rabson <dfr@rabson.org>
This allows code which depends on opencontainers/runtime-tools to build on non-linux platforms.
None
```release-note
None
```
=> Update vendor of opencontainers/runtime-tools

.github/workflows/test.yml, scripts/release-notes/release_notes.go
This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/6534
```release-note
None
```
=> [release-1.24] Inject release-notes branch from GitHub actions 

.github/workflows/verify.yml
This is manual cherry-pick of https://github.com/cri-o/cri-o/pull/6528
Closes https://github.com/cri-o/cri-o/issues/6512
```release-note
None
```
=> [release-1.24] ci-verify: Run get-scripts only on main branch

.packit.yaml
In January 2023, Packit changed the way SRPMs are built. You can (and
have to) specify all dependencies that are utilized during the SRPM
build phase, in this case, wget.
/kind ci
Get RPM builds working again.
no
=> packit: install wget before build

internal/lib/stats/stats_server.go, test/stats.bats
The stats were being collected but not added to the PodSandboxStats.Linux.Containers array. Closes #6563.
Signed-off-by: Doug Rabson <dfr@rabson.org>
/kind bug
Fixes #6563
```release-note
None
```
=> Add container stats to the ListPodSandboxStats response

go.mod, go.sum, internal/lib/checkpoint.go, internal/lib/checkpoint_test.go, internal/lib/restore.go, internal/lib/restore_test.go, internal/oci/container.go, internal/oci/runtime_oci.go, server/container_checkpoint.go, server/container_checkpoint_test.go, server/container_restore.go, server/container_restore_test.go, server/container_start.go, server/container_status.go, server/container_status_test.go, test/checkpoint.bats, vendor/github.com/checkpoint-restore/checkpointctl/lib/metadata.go, vendor/modules.txt
/kind feature
This PR adds additional metadata to the inspect command if checkpointing support is active. The following three fields are added to inspect:
```json
"checkpointedAt": "timestamp",
"restored": "true or false",
```
With "checkpointedAt" it is possible to see when a checkpoint was created. With "restoredAt" is is possible to see when this container was restored from a checkpoint. "restored" is true if the container has been restored from a checkpoint for all other container this is set to false.
These information are also part of the checkpoint archive. If checkpoint archive contains a container that has been restored "restoredAt" will be empty but "checkpointedAt" will still contain the time of the checkpointing.
To add these additional fields it was necessary to pull in a …
=> Add additional metadata to inspect and checkpoint

internal/version/version.go, internal/version/version_test.go
This is a manual backport of 935652c90c9f87e001f9453a5b102d538edc06f7
```release-note
Do not wipe images when the filename is empty.
```
=> [release-1.24] do not wipe images by default

go.mod, go.sum, vendor/github.com/opencontainers/runtime-tools/generate/generate.go, vendor/modules.txt
Update runtime-tools to commit a6a073817ab0. This reverts commit 09d837b of the same repo (mount `/dev` with the `noexec` flag), which triggered problems when containers try to create Intel SGX enclaves.
Commit [09d837b](https://github.com/opencontainers/runtime-tools/commit/09d837bf40a7356a478e40642e36f5f7e1dea7d1) of runtime-tools changed `/dev` to be mounted by default with the `noexec` flag. This triggers problems when containers try to create Intel SGX enclaves. Please see [the revert commit](https://github.com/opencontainers/runtime-tools/commit/0524bb2cf613004f1cc291f81a68f308e83d846f) message for more details or the related [runtime-tools issue](https://github.com/opencontainers/runtime-tools/issues/759).
None
```release-note
'/dev' is now mounted again …
```
=> Update runtime-tools to mount '/dev' without the 'noexec' flag.

go.mod, go.sum, vendor/github.com/opencontainers/runtime-tools/generate/generate.go, vendor/github.com/opencontainers/runtime-tools/validate/capabilities/validate_unsupported.go, vendor/modules.txt
Update runtime-tools to latest HEAD. This reverts commit 09d837b in runtime-tools (mount /dev with 'noexec'), which triggered problems when containers try to create Intel SGX enclaves.
Signed-off-by: Krisztian Litkey <krisztian.litkey@intel.com>
cherry-pick of https://github.com/cri-o/cri-o/pull/6582
```release-note
'/dev' is now mounted again without the 'noexec' flag.
```
=> [1.26] Update opencontainers/runtime-tools to a6a073817ab0

internal/oci/oci.go, internal/oci/runtime_vm.go
/kind bug
The integration test "ctr pod lifecycle with evented pleg enabled" is failing for kata containers.
This is because of how the container's exit is handled for kata.
For regular containers, the exit is detected by the `server.exitsMonitor()`, and it calls `handleExit()` for it, where the event `CONTAINER_STOPPED_EVENT` is generated.
For kata containers, the exit is detected by a wait function started when the container is started, and it doesn't send the event.
The event can be sent by calling the function `server.generateCRIEvent()`. But having a handle on the server in runtimeVM seems cumbersome.
Also I think runtimeVM containers could benefit from leveraging the handleExit() code in general - rather than handling the exit separately.
This is why I modified the code on the wait …
=> Fix issues with PLEG events for kata

cmd/crio/main.go
/kind bug
this PR partially reverts https://github.com/cri-o/cri-o/pull/852/commits/dacc5c3ece43ca645b2177171704e19a23a7a1e0 to fix https://github.com/cri-o/cri-o/issues/6626
```release-note
fix panic of server when EnablePodEvents is set to true
```
=> main: shutdown server only once

internal/storage/runtime.go
/kind bug
There are cases where the container storage unmount has been already (partially) done. This would cause `StopContainer()`  in `server/container_stop.go:76` fail and therefore make containers get stuck in recreation, making their pods stuck in `NotReady`.
We now double check the two c/storage errors `ErrContainerUnknown` and `ErrLayerUnknown`
Somehow related to: https://github.com/containers/podman/issues/11207#issuecomment-920768804
None
Cherry-pick of https://github.com/cri-o/cri-o/pull/6517
Issue: https://issues.redhat.com/browse/OCPBUGS-6585
```release-note
None
```
=> [1.23] Make storage unmount less strict

go.mod, go.sum, vendor/github.com/opencontainers/runtime-tools/generate/generate.go, vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default.go, vendor/github.com/opencontainers/runtime-tools/generate/seccomp/seccomp_default_linux.go, vendor/github.com/opencontainers/runtime-tools/validate/capabilities/validate.go, vendor/github.com/opencontainers/runtime-tools/validate/capabilities/validate_linux.go, vendor/github.com/opencontainers/runtime-tools/validate/capabilities/validate_unsupported.go, vendor/github.com/opencontainers/runtime-tools/validate/validate.go, vendor/github.com/opencontainers/runtime-tools/validate/validate_linux.go, vendor/modules.txt
Update runtime-tools to latest HEAD. This reverts commit 09d837b in runtime-tools (mount /dev with 'noexec'), which triggered problems when containers try to create Intel SGX enclaves.
Signed-off-by: Krisztian Litkey krisztian.litkey@intel.com
Signed-off-by: Peter Hunt~ pehunt@redhat.com
cherrry-pick of https://github.com/cri-o/cri-o/pull/6618
```release-note
'/dev' is now mounted again without the 'noexec' flag.
```
=> [1.25] Bump runtime-tools to v0.9.1-0.20230110161035-a6a073817ab0

test/pod.bats
Every now and then, the kata-jenkins job is failing on "pod stop idempotent with ctrs already stopped".
Investigating it, I found it is due to a race condition, when the container completes while we are processing the "StopContainer" request. This results in the kata agent reporting an "cannot find init process!" error.
I don't think it is the intent of the test to check this kind of issue, so I used the longer-running "container_sleep.yaml" file, and verified the issue does not happen again.
An alternative would be to add a delay between the `crictl start` and `crictl stop` commands, making sure the container is actually done when we stop it, but that would make the test longer, so I preferred this method.
The race condition itself may be a problem, but I think the …
=> test: use container_sleep for idempotent test

scripts/node_e2e_installer
/kind cleanup
The variable is not used any more since we can create them directly via butane / ignition:
- https://github.com/kubernetes/test-infra/blob/6c3045e/jobs/e2e_node/crio/templates/base/crio-enable-pod-events.yaml
- https://github.com/kubernetes/test-infra/blob/6c3045e/jobs/e2e_node/crio/templates/base/40-evented-pleg.conf
None
None
```release-note
None
```
=> Drop `ENABLE_POD_EVENTS` var from e2e installer script

cmd/crio/main.go
This reverts commit 62173e97494a4154f41e2c550f2457584b50ce97. it seems to break github actions
```release-note
none
```
=> Revert "main: shutdown server only once"

server/container_create_linux.go, test/helpers.bash, test/pod.bats
Fixes: https://issues.redhat.com/browse/OCPBUGS-6026 
This fixes the folder ownership issue for `/etc` inside the pod.
/kind bug
```release-note
None
```
=> server: fix the permission issue for `/etc`

internal/config/cgmgr/cgmgr.go, internal/config/cgmgr/cgroupfs.go, internal/config/cgmgr/systemd.go
Fix cgroup leak for systemd cgroup driver
- Removed redundant call to cgroup creation from `systemd.go:CreateSandboxCgroup`
- Cleaned-up `cgmgr.go:createSandboxCgroup` to handle cgroup creation only for `cgroupfs` driver
Closes #6349
/kind bug
This PR would make cgroup approach idiomatically uniform to all releases prior to `release-1.26`
Fixes #6349 
```release-note
None
```
=> Fix cgroup leak for systemd cgroup driver

server/container_update_resources.go, server/container_update_resources_test.go
/kind bug
If `nil` returned from nri call, set the current `LinuxContainerResources` data.
Integration test: Enabling nri in the server config. 
If the protection is valid, tests should pass.
Additional info in the issue itself 
https://github.com/cri-o/cri-o/issues/6642
```release-note
None
```
=> nri: add protection against nil dereference

.github/workflows/test.yml, dependencies.yaml
We have to pin nix to v2.13.3 to avoid having the regression mentioned in https://github.com/cachix/cachix-action/issues/138#issuecomment-1448952201.
This should fix the static builds.
None
None
```release-note
None
```
=> Pin nix version to fix static builds

internal/config/cgmgr/cgmgr.go, internal/config/cgmgr/cgroupfs.go, internal/config/cgmgr/systemd.go
Backmerge PR
Closes #6349
/kind bug
This PR fixes an issue whereby cgroups are not cleaned up after a Pod is terminated, this is an issue with cri-o versions prior to `1.26`
Fixes #6349 
No
```release-note
```
=> [1.25] Fix cgroup leak for systemd cgroup driver

server/container_restore.go, server/container_restore_test.go
/kind bug
With this change the restored container has the same MaskedPaths and ReadonlyPaths as the originally checkpointed container.
Fixes #6374
```release-note
None
```
=> Take MaskedPaths and ReadonlyPaths from checkpointed container

internal/config/cgmgr/cgmgr.go, internal/config/cgmgr/cgroupfs.go, internal/config/cgmgr/systemd.go
Initial commit to get feedback from the maintainers, need to add integration tests
Closes #6349
Signed-off-by: Neeraj Shah <neerajx86@gmail.com>
/kind bug
This PR fixes an issue whereby cgroups are not cleaned up after a Pod is terminated, this is an issue with cri-o versions prior to `1.26`
Fixes #6349 
This is a draft PR, I need to add integration tests for my changes.
No
```release-note
```
=> [1.24] Fix cgroup leak for systemd cgroup driver

internal/runtimehandlerhooks/utils.go, internal/runtimehandlerhooks/utils_test.go
/kind bug
Kernel got more strict in parsing the interrupt cpu mask strings, we are no longer allowed to pass in more 4B (32 bit) words than necessary to cover all cpus on a given system.
See https://bugzilla.redhat.com/show_bug.cgi?id=2181546 for more detail about what kernel accepts and what gets rejected.
The logic of mapByteToHexChar (from internal/runtimehandlerhooks/utils.go) was rounding to 8 bytes (64 bits) which triggered the linked bug.
Fixes https://issues.redhat.com/browse/OCPBUGS-10970
```release-note
None
```
=> OCPBUGS-10970: Fix the interrupt mask width when encoding

scripts/get, scripts/release-notes/release_notes.go
/kind ci
The check of the cosign-based keyless signature check accepted any valid signature. This opens the attack vector that a malicious file with a valid signature passes the check when executing the command from the release notes.
Values as per [rekor record for `cri-o.arm64.v1.26.3.tar.gz`](https://search.sigstore.dev/?hash=f2fee35b23b4fda0a32c79b7eacdff96258cd84655899a0a7f6012e2b257f293)
Fixed #6781 
None
=> Generate proper signature check

contrib/test/ci/critest.yml, contrib/test/ci/e2e-base.yml, contrib/test/ci/integration-main.yml, contrib/test/ci/setup.yml
This change fixes the cri-o CI which will now pick the PR content for testing.
/kind bug
/kind ci
```release-note
None
```
=> contrib/test: don't cache the cri-o content

internal/oci/runtime_vm.go
/kind bug
When running kata containers, the initial specs for the containers are overwritten by an Exec or ExecSync command.
It was fixed for the default runtime (see #3989), but the same fix must be applied on runtime_vm.go
This PR fixes the integration test "ctr execsync should not overwrite initial spec args" with the kata runtime.
None
```release-note
- Fixed a bug when running kata containers, where exec sync requests (manually or automatically triggered via readiness/liveness probes)
overwrite the runtime `info.runtimeSpec.process.args` of the container status (for example via `crictl inspect`).
```
=> runtimeVM: fix Exec(sync) overwriting the initial spec args

internal/oci/runtime_oci.go
/kind bug
Since https://github.com/checkpoint-restore/criu/pull/1357, CRIU would fail if it finds file locks being used by the application that is being checkpointed and the --file-locks option has not been specified. This pull request enables checkpointing of file locks by default.
cc: @adrianreber 
```release-note
none
```
=> oci: Enable checkpointing of file locks

internal/version/version.go
/kind bug
We have to trim the field by whitespace, otherwise we will end up printing empty Dependencies, like:
```
> ./bin/crio version | tail -n3
AppArmorEnabled:  false
Dependencies:
```
None
None
```release-note
Don't print `Dependencies` field if `crio version` it not verbose.
```
=> Don't print `Dependencies` if `crio version` it not verbose

completions/fish/crio.fish, docs/crio.8.md, docs/crio.conf.5.md, internal/criocli/criocli.go, pkg/config/config.go, pkg/config/template.go
as SeccompDefault FeatureGate has gone GA in upstream Kubernetes
```release-note
Mark `seccomp-use-default-when-empty` option as deprecated, as it is replaced by the SeccompDefault FeatureGate
```
=> config: mark seccomp-use-default-when-empty as deprecated

server/runtime_status.go, server/runtime_status_test.go
/kind feature
Adds information about pause image to `crictl info`, as used by kubeadm in 1.27
Fixes #6816
```release-note
a new field "config" has been added to the verbose output of crictl info
```
`crictl info`
```json
{
"status": {
"conditions": [
{
"type": "RuntimeReady",
"status": true,
"reason": "",
"message": ""
},
{
"type": "NetworkReady",
"status": false,
"reason": "NetworkPluginNotReady",
"message": "Network plugin returns error: No CNI configuration file in /etc/cni/net.d/. Has your network provider started?"
}
]
},
"config": {
"sandboxImage": "registry.k8s.io/pause:3.9"
}
}
```
=> Add basic crictl info config with sandboxImage

server/container_create_linux.go
/kind bug
fixes https://github.com/cri-o/cri-o/issues/6833
```release-note
fix a segfault when a user namespace is requested but no OCI ID mappings are present
```
=> user ns: fix segfault when host id mapping is empty

server/container_create_linux.go
This makes it easier to verify whether relabel is being done or not for a volume.
/kind cleanup
None
```release-note
Adds debug log to identify when a relabel was not requested
```
=> Add debug to identify when a relabel was not requested

contrib/test/ci/build/cri-tools.yml
We're building cri-tools binaries on an RHEL/Fedora system, so it makes sense to hardcode the bin path to `linux/amd64`.
/kind ci
```release-note
None
```
=> contrib/test/ci: fix the bin folder location for cri-tools

internal/runtimehandlerhooks/high_performance_hooks.go, internal/runtimehandlerhooks/high_performance_hooks_test.go
/kind feature
The cpu-c-states.crio.io annotation currently allows c-states to be disabled for a pod (with guaranteed QoS). The annotation is defined as follows:
cpu-c-states.crio.io: <enable|disable>
This annotation enables or disables c-states for each cpu by writing to the power/pm_qos_resume_latency_us for the cpu under sysfs.
However, users of this new annotation now want to be able to have more control over the c-states for each pod - instead of just disabling c-states completely, they would like to be able to specify a maximum latency for the pod.
The cpu-c-states.crio.io annotation is being extended to support these values:
- enable: enable all c-states (cpu-c-states.crio.io: "enable")
- disable: disable all c-states (cpu-c-states.crio.io: "disable")
- max_latency: enable c-states …
=> Extend cpu-c-states.crio.io annotation to add max latency

internal/config/cgmgr/cgmgr.go, internal/config/cgmgr/cgroupfs.go, internal/config/cgmgr/systemd.go, server/sandbox_remove.go, test/cgroups.bats, test/pod.bats
The history here is a bit convoluted. Originally, runc created the cgroup for the infra container.
cAdvisor was built to assume the cgroup for the infra container would be created, and it uses
this to find the network metrics for the pod. When we dropped the infra container, cri-o needed to make this
cgroup so cAdvisor could still find the network metrics.
However, systemd didn't like the way we did it, and would remove the cgroup mid pod creation, which was fixed in
https://github.com/cri-o/cri-o/pull/6196. This actually caused the cgroup to not be created at all, which then caused
the networking metrics to not be gathered at all.
Thus, we do need to create a cgroup underneath the systemd cgroup. Attempt to use a slice for this, as systemd won't require a
process be underneath it.
/kind …
=> cgmgr: create cgroups for systemd cgroup driver for dropped infra pods

internal/lib/checkpoint.go, server/container_restore.go, server/container_restore_test.go
/kind bug
/kind feature
Up until now CRI-O was using ImageName to remember the base image of the restored container. This works, but has two problems:
* The output from the restored container was different, especially for the Kubernetes use case. The output of 'crictl ps' contains for the original container under 'IMAGE' something like 'registry/path/container@sha256:123444444...'. The restored container was, however, only displaying something like 'registry/path/container'.
* More problematic, however, was that CRI-O might pull the wrong image from the registry.  If the container in the registry was updated (new latest tag for example) all of a sudden the wrong base image would be downloaded and the restore would potentially fail.
With this change the output of Kubernetes containers in …
=> Use ImageRef instead of ImageName for restore

tutorials/debugging.md
Closes #5900
Signed-off-by: Rory Chapman <rchap4@gmail.com>
This PR add documentation to force Go garbage collection for CRI-O.  CRI-O has the functionally to catch signal SIGUSR2 and manually run garbage collection.  However, at present using this feature is undocumented.
This fixes issues 5900, a request to document the use of this feature.
Fixes #5900
I was able to successfully test manually initiating Go garbage collection for CRI-O running as a Systemd using the `systemctl kill -s USR2 crio.service` approach.  The worker node for the test was OpenShift 4.10.43, CRI-O 1.23.3, and RHEL CoreOS.  Success was observed as a significant decrease in the Memory RSS used by CRI-O on the node.  However, in testing on the same worker, I observed no change in CRI-O's RSS when …
=> Added documentation to force the Go garbage collector for CRI-O

test/timeout.bats
The timeout.bats tests are all skipped with the message `must have a crictl with the -T option to test CRI-O's timeout handling`.
Looking into it, I think it started with https://github.com/cri-o/cri-o/commit/5cad5f287482c045ac7c6c1aa70a1352636b843a, where the `crictl()` wrapper was modified to use a config file in the `TESTDIR` folder.
Because of that, calling `crictl()` before `setup_test()` means calling it with a non-existing config file, causing an error.
This PR modifies the test to use the crictl binary directly, skipping the wrapper function.
None
```release-note
None
```
=> tests: use crictl binary directly when checking its capabilities

go.mod, go.sum, server/sandbox_network.go, vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go, vendor/github.com/cri-o/ocicni/pkg/ocicni/types.go, vendor/github.com/onsi/ginkgo/v2/.gitignore, vendor/github.com/onsi/ginkgo/v2/CHANGELOG.md, vendor/github.com/onsi/ginkgo/v2/ginkgo_t_dsl.go, vendor/github.com/onsi/ginkgo/v2/internal/interrupt_handler/interrupt_handler.go, vendor/github.com/onsi/ginkgo/v2/internal/output_interceptor_unix.go, vendor/github.com/onsi/ginkgo/v2/internal/suite.go, vendor/github.com/onsi/ginkgo/v2/internal/testingtproxy/testing_t_proxy.go, vendor/github.com/onsi/ginkgo/v2/internal/writer.go, vendor/github.com/onsi/ginkgo/v2/reporters/junit_report.go, vendor/github.com/onsi/ginkgo/v2/types/deprecation_support.go, vendor/github.com/onsi/ginkgo/v2/types/version.go, vendor/golang.org/x/tools/internal/gcimporter/iexport.go, vendor/golang.org/x/tools/internal/gcimporter/iimport.go, vendor/golang.org/x/tools/internal/tokeninternal/tokeninternal.go, vendor/modules.txt
There is an optional CNI capability [arg](https://github.com/containernetworking/cni/blob/main/CONVENTIONS.md#well-known-capabilities), cgroupPath, where plugins can request that runtimes inject a PodSandbox's cgroup path. So, plumb that in.
/kind other
```release-note
cri-o now sets the cgroupPath CNI capability arg.
```
=> CNI: set cgroup path capabilty arg

.github/ISSUE_TEMPLATE/bug-report.yml
The command `kubectl --version` in bug report template is invalid.
`kubectl version` is correct, but is deprecated: output will be equal to `kubectl version --short` in the future.
JSON or YAML output will continue to contain full version information.
This PR updates the bug report template to output JSON, which is stable long-term.
None
```release-note
None
```
=> fix kubectl version in bug report template

go.mod, go.sum, vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go, vendor/github.com/containers/common/pkg/umask/umask.go, vendor/modules.txt
/kind bug
None
Manual pick of https://github.com/cri-o/cri-o/pull/6843
Refers to https://issues.redhat.com/browse/OCPBUGS-13280
```release-note
```
=> [1.26] Update c/common to fix umask bug

go.mod, go.sum, vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go, vendor/github.com/containers/common/pkg/umask/umask.go, vendor/modules.txt
/kind bug
None
Manual pick of https://github.com/cri-o/cri-o/pull/6843
Refers to https://issues.redhat.com/browse/OCPBUGS-13282
```release-note
```
=> [1.25] Update c/common to fix umask bug

server/image_pull.go
/kind feature
We now check for c/image policy errors and convert them to the CRI equivalent if necessary.
None
None
```release-note
Support image policy verification error through the CRI.
```
=> Support image policy verification error

internal/runtimehandlerhooks/high_performance_hooks.go, server/container_create_linux.go, test/cgroups.bats, test/helpers.bash
/kind bug
if cpu quota is disabled as part of container creation, then the pod
cgroup does not have it disabled, which causes the cgroup to continue to
have cpu quota. Instead, partially revert efaea10606ce6c7012 and use
libcontainer to fix the issue it was originally trying to (an issue
where newer systemd reverts the disabling of cpu quota because it was
only applied on the cgroupfs)
```release-note
Fix a bug where the `cpu-quota.crio.io` annotation was not propagated to the pod cgroup, meaning cpu quota was not disabled for the container
```
=> OCPBUGS-13542: high perf hooks: disable CPU quota with libcontainer as a pre start hook

internal/runtimehandlerhooks/high_performance_hooks.go, server/container_create_linux.go, test/cgroups.bats, test/helpers.bash
cherry-pick of #6917
/kind bug
```release-note
Fix a bug where the `cpu-quota.crio.io` annotation was not propagated to the pod cgroup, meaning cpu quota was not disabled for the container
```
=> [1.26] OCPBUGS-13853: high perf hooks: disable CPU quota with libcontainer as a pre start hook

internal/config/cgmgr/cgmgr.go, internal/config/cgmgr/cgroupfs.go, internal/config/cgmgr/systemd.go, server/sandbox_remove.go, test/cgroups.bats, test/pod.bats
The history here is a bit convoluted. Originally, runc created the cgroup for the infra container.
cAdvisor was built to assume the cgroup for the infra container would be created, and it uses
this to find the network metrics for the pod. When we dropped the infra container, cri-o needed to make this
cgroup so cAdvisor could still find the network metrics.
However, systemd didn't like the way we did it, and would remove the cgroup mid pod creation, which was fixed in
https://github.com/cri-o/cri-o/pull/6196. This actually caused the cgroup to not be created at all, which then caused
the networking metrics to not be gathered at all.
Thus, we do need to create a cgroup underneath the systemd cgroup. Attempt to use a slice for this, as systemd won't require a
process be underneath it.
/kind …
=> [1.25] cgmgr: create cgroups for systemd cgroup driver for dropped infra pods

go.mod, go.sum, vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go, vendor/github.com/containers/common/pkg/umask/umask.go, vendor/modules.txt
/kind bug
None
Manual pick of https://github.com/cri-o/cri-o/pull/6843
Refers to https://issues.redhat.com/browse/OCPBUGS-13281
```release-note
```
=> [1.24] Update c/common to fix umask bug

contrib/test/ci/build/cri-o.yml, contrib/test/ci/e2e-base.yml, contrib/test/ci/vars.yml
/kind ci
This PR enables a new ci job to run e2e tests with the evented pleg feature enabled both in the kubelet and the cri-o configurations
None
Linked PR in the `openshift/release` repository
https://github.com/openshift/release/pull/39629 
No
```release-note
`None`
```
=> OCPNODE-1286: Add a CI job to run cri-o e2e tests by enabling the evented pleg feature

go.mod, go.sum, vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go, vendor/github.com/containers/common/pkg/umask/umask.go, vendor/modules.txt
/kind bug
None
Manual pick of https://github.com/cri-o/cri-o/pull/6843
Refers to https://issues.redhat.com/browse/OCPBUGS-13283
```release-note
```
=> OCPBUGS-13283: [1.23] Update c/common to fix umask bug

internal/factory/container/container_test.go, internal/lib/container_server.go, internal/lib/container_server_test.go, internal/lib/sandbox/history_test.go, internal/lib/sandbox/sandbox.go, internal/lib/sandbox/sandbox_test.go, internal/lib/sandbox/suite_test.go, internal/lib/suite_test.go, pkg/annotations/annotations.go, server/nri-api.go, server/sandbox_run_linux.go, server/suite_test.go
The CRI PodLinuxOverhead and PodLinuxResources fields were not saved which meant that NRI plugins would need to cache the data in order not to miss them if cri-o is restarted. These two fields are already passed to NRI plugins by containerd. Solve this issue by caching those two fields and restoring them if cri-o is restarted.
/kind feature
This change allows cri-o to store PodLinuxOverhead and PodLinuxResource CRI resource fields and then later send them to NRI plugins. The issue is seen when cri-o is restarted in which case it has lost the value of these two fields and cannot forward them to NRI plugins. With this change, NRI plugins do not need to cache the fields as it is able to receive them when the plugin is started. The containerd already passes these fields to NRI plugins.
None …
=> sandbox: Handle PodLinuxOverhead and PodLinuxResources CRI fields

contrib/test/integration/main.yml, dependencies.yaml, scripts/versions
/kind ci
Use kubernetes 1.22 and cri-tools 1.22 in CI, since this is 1.22 branch.
None
```release-note
NONE
```
=> [1.22] ci: use kubernetes 1.22 and cri-tools 1.22

test/cgroups.bats, test/drop_infra.bats, test/network.bats, test/restore.bats
We removed that option in https://github.com/cri-o/cri-o/pull/4428/files
/kind cleanup
Remove remnants of CONTAINER_MANAGE_NS_LIFECYCLE that are no longer applicable.
```release-note
None
```
=> Remove remnants of CONTAINER_MANAGE_NS_LIFECYCLE

transfer.md
[transfer.md](https://github.com/cri-o/cri-o/blob/main/transfer.md) is not relevant anymore.
Updated the doc to share information about how CRI-O is not a drop-in replacement of docker, a bit about the CRI, and how Podman can be used as an alternative for debugging.
Fixes #6896 
None
```release-note
None
```
=> docs: update cri-o podman doc and remove stale information

.github/workflows/integration.yml, .github/workflows/test.yml, .github/workflows/verify.yml
Since commit b34038f8f4b1bc / PR #6735, gha ci uses actions/setup-go v4. This version adds implicit caching, very similar to what we did, and so we don't have to use actions/cache explicitly anymore.
The only catch is, it needs go.mod, so make sure that actions/checkout is run before actions/setup-go.
Remove own caching, except for build-i386.
/kind ci
```release-note
NONE
```
=> ci/gha: fix double caching

internal/config/cgmgr/cgmgr.go, internal/config/cgmgr/cgroupfs.go, internal/config/cgmgr/systemd.go, server/sandbox_remove.go, test/cgroups.bats, test/pod.bats
The history here is a bit convoluted. Originally, runc created the cgroup for the infra container.
cAdvisor was built to assume the cgroup for the infra container would be created, and it uses
this to find the network metrics for the pod. When we dropped the infra container, cri-o needed to make this
cgroup so cAdvisor could still find the network metrics.
However, systemd didn't like the way we did it, and would remove the cgroup mid pod creation, which was fixed in
https://github.com/cri-o/cri-o/pull/6196. This actually caused the cgroup to not be created at all, which then caused
the networking metrics to not be gathered at all.
Thus, we do need to create a cgroup underneath the systemd cgroup. Attempt to use a slice for this, as systemd won't require a
process be underneath it.
/kind …
=> [1.24] cgmgr: create cgroups for systemd cgroup driver for dropped infra pods

test/helpers.bash
This fixes 
```
not ok 19 cpu-quota.crio.io can disable quota
```
in integration/test-cgroupfs.
Fixes: a875ef486e3640bb1b3c6a21bf0c6e8bb3f5804d
/kind bug
/kind ci
```release-note
NONE
```
=> test/cgroup: fix for cgroupfs

test/test_runner.sh
Each parallel job eats lots of disk space in /tmp (mostly due to container images, I guess). Usually, /tmp resides on a tmpfs, which is limited to half the RAM.
As a result, when I run integration tests on my laptop (16 GB RAM, quad-core with hyperthreading), JOBS is 32, my /tmp quickly becomes full, and everything breaks. Manual cleanup after this takes time thanks to overlayfs mounts in /tmp (a separate issue).
This is the second time I came across this unfortunate behavior, and every single time I forget to set JOBS manually.
Let's be more conservative and run `nproc --all` jobs.
PS I believe this won't affect CI since we always set JOBS explicitly.
/kind other
```release-note
NONE
```
=> test: limit number of parallel jobs

go.mod, go.sum, vendor/github.com/containerd/nri/pkg/api/resources.go, vendor/modules.txt
/kind bug
Update `github.com/containerd/nri` dependency to latest. Current code assumes that any resource update has a non-nil runtime-spec.LinuxMemory field. Tries to blindly dereference it in `internal/lib/container_server.go` without a nil-check. This is not a problem for internally generated `LinuxResources`, because the implicit assumption there is true. NRI used to violate this assumption and the latest commit fixes that. Without that fix an NRI plugin updating a container without touching memory resources/cgroupfs parametrization triggers a nil-pointer dereference/SIGSEGV panic and a crash in CRI-O. 
None
```release-note
None
```
=> go.{mod,sum}, vendor: update NRI.

test/timeout.bats
These tests are not compatible with conmon-rs, and are failing. It seems it does not make sense to test both conmon and conmon-rs.
/kind ci
```release-note
NONE
```
=> tests/timeout: skip for conmon-rs

README.md
We always forget to add the new release, which is now not required any more considering a new format. We also outline that the patch release of CRI-O (`.y`) does not have to match with them from Kubernetes (`.z`).
Since we only have two data rows within the table, we also can avoid the key mapping and add their description directly to it.
None
None
```release-note
None
```
=> Update `README.md` version table

internal/config/cgmgr/cgmgr.go, internal/config/cgmgr/cgroupfs.go, internal/config/cgmgr/systemd.go, internal/runtimehandlerhooks/default_cpu_load_balance_hooks.go, internal/runtimehandlerhooks/high_performance_hooks.go, internal/runtimehandlerhooks/runtime_handler_hooks.go, server/container_remove.go, server/container_stop.go, server/sandbox_run_linux.go, server/sandbox_stop_linux.go, test/cpu_load_balancing.bats
/kind bug
This PR fixes two separate bugs with high performance hooks, and does some code reorganization while it's at it.
It's kept in one PR to simplify backporting.
- Fix a bug where the wrong cgroup path was chosen by libcontainer when disabling cpu quota
- Reoganize hooks and NRI plugins so they're called in all cases containers are stopped
- Fix a bug where stale containers (ones that have stopped but not been cleaned up) break cpu load balancing by disabling load balancing after they're stopped.
```release-note
Fix a bug with cpu quota annotation that manifests like:
`pod with cpu-quota.crio.io: disable fails with error: set CPU CFS quota: invalid slice name: /kubepods.slice`
Fix a bug where stopped containers break cpu load balancing being disabled
```
=> OCPBUGS-13980,OCPBUGS-14018: Fix bugs with high performance hooks

test/helpers.bash
Simplify the most hard-to-read portion of `setup_crio`.
/kind ci
```release-note
NOTE
```
=> test/helpers: simplify setup_crio()

docs/crio.8.md, server/metrics/metrics.go, server/otel-collector/collectors/collectors.go, server/otel-collector/collectors/collectors_test.go, server/utils.go, test/timeout.bats
there's already a log emitted for when a resource (pod or container) is stuck at a stage of creation, but no corresponding metric. Add a metric to make resource limiting scenerios easier to debug.
/kind feature
```release-note
add a new metric `resources_stalled_at_stage` to show when pods and containers are stuck at different stages of creation.
```
=> metrics: add metric for resource stalled at stage

Makefile, internal/criocli/criocli.go
Commit 1e54cdd362e6ff8e (PR #1740) added support for setting build-time DefaultsPath.
Commit 97b9587f160583d6 (PR #3321) added setting DefaultsPath from the Makefile.
Commit eb9cc161cb0f47b8 (PR #3298) renamed internal/criocli to internal/pkg/criocli.
The last two commits/PRs were merged the same day (5 March 2020).
This means the feature never worked (it could have worked in backports but they
never happened).
Since it never worked for 3+ years, it probably have no users.
Remove it.
Essentially, this reverts commits 1e54cdd362e6ff8e and 97b9587f160583d6.
```release-note
NONE
```
=> crio: remove DefaultsPath

go.mod, go.sum, vendor/github.com/containerd/nri/pkg/api/resources.go, vendor/modules.txt
/kind bug
Update `github.com/containerd/nri` dependency to latest. Current code assumes that any resource update has a non-nil runtime-spec.LinuxMemory field. Tries to blindly dereference it in `internal/lib/container_server.go` without a nil-check. This is not a problem for internally generated `LinuxResources`, because the implicit assumption there is true. NRI used to violate this assumption and the latest commit fixes that. Without that fix an NRI plugin updating a container without touching memory resources/cgroupfs parametrization triggers a nil-pointer dereference/SIGSEGV panic and a crash in CRI-O. 
None
This is effectively a backport of #6880 to 1.26.
```release-note
none
```
=> [release-1.26] update NRI.

completions/fish/crio.fish, docs/crio.8.md, internal/criocli/config.go
/kind cleanup
Deprecate config migration support which will be removed in v1.29.0
Fixes #6884
:)
```release-note
Deprecate config migration support (will be removed in v1.29.0)
```
=> crio: deprecate config migrate support

server/container_stop.go
/kind bug
The pod is already dead when the PostStop hook is called and so there is nothing to block anyway. Just log the error.
Fixes: https://issues.redhat.com/browse/OCPBUGS-14750
```release-note
Failure in a PostStop hook does not prevent proper termination of a container anymore.
```
=> OCPBUGS-14750: Pod termination must succeed when a hook fails

internal/config/cgmgr/cgmgr.go, internal/config/cgmgr/cgroupfs.go, internal/config/cgmgr/systemd.go, server/sandbox_remove.go, test/cgroups.bats, test/pod.bats
The history here is a bit convoluted. Originally, runc created the cgroup for the infra container.
cAdvisor was built to assume the cgroup for the infra container would be created, and it uses
this to find the network metrics for the pod. When we dropped the infra container, cri-o needed to make this
cgroup so cAdvisor could still find the network metrics.
However, systemd didn't like the way we did it, and would remove the cgroup mid pod creation, which was fixed in
https://github.com/cri-o/cri-o/pull/6196. This actually caused the cgroup to not be created at all, which then caused
the networking metrics to not be gathered at all.
Thus, we do need to create a cgroup underneath the systemd cgroup. Attempt to use a slice for this, as systemd won't require a
process be underneath it.
/kind …
=> [1.23] cgmgr: create cgroups for systemd cgroup driver for dropped infra pods

internal/linklogs/link_logs.go, pkg/annotations/annotations.go, pkg/config/config.go, server/container_create_linux.go, server/sandbox_run_linux.go, server/sandbox_stop_linux.go, test/ctr.bats, test/helpers.bash
/kind feature
follow up of https://github.com/cri-o/cri-o/pull/6911, changing a couple of things:
- reverting a wip test change
- moving the log linking code to a separate package
- updating the test to include cleanup
- adding a feature where the directory of container logs is symlinked to the container ID to aid in log processing
```release-note
Add support for `io.kubernetes.cri-o.LinkLogs` annotation, which allows a pod's logs to be mounted into a specified empty-dir for inspection by a log aggregator
```
=> Add support for linking pod logs

internal/linklogs/link_logs.go, pkg/annotations/annotations.go, pkg/config/config.go, server/container_create_linux.go, server/sandbox_run_linux.go, server/sandbox_stop_linux.go, test/ctr.bats, test/helpers.bash
/kind feature
follow up of https://github.com/cri-o/cri-o/pull/6911, changing a couple of things:
- reverting a wip test change
- moving the log linking code to a separate package
- updating the test to include cleanup
- adding a feature where the directory of container logs is symlinked to the container ID to aid in log processing
cherry-pick of https://github.com/cri-o/cri-o/pull/6990
```release-note
Add support for `io.kubernetes.cri-o.LinkLogs` annotation, which allows a pod's logs to be mounted into a specified empty-dir for inspection by a log aggregator
```
=> [1.27] Add support for linking pod logs

internal/linklogs/link_logs.go, internal/runtimehandlerhooks/high_performance_hooks.go, pkg/annotations/annotations.go, pkg/config/config.go, server/container_create_linux.go, server/sandbox_run_linux.go, server/sandbox_stop_linux.go, test/ctr.bats, test/helpers.bash
/kind feature
follow up of https://github.com/cri-o/cri-o/pull/6911, changing a couple of things:
- reverting a wip test change
- moving the log linking code to a separate package
- updating the test to include cleanup
- adding a feature where the directory of container logs is symlinked to the container ID to aid in log processing
cherry-pick of https://github.com/cri-o/cri-o/pull/6990
```release-note
Add support for `io.kubernetes.cri-o.LinkLogs` annotation, which allows a pod's logs to be mounted into a specified empty-dir for inspection by a log aggregator
```
=> [1.26] Add support for linking pod logs

utils/utils.go, utils/utils_linux.go, utils/utils_unix.go
Thie moves RunUnderSystemdScope and Syncfs to utils_linux and adds an approximation of Syncfs on non-linux platforms. Part of #6492.
/kind cleanup
None
```release-note
None
```
=> utils: make this package build on non-linux platforms

pkg/config/reload.go, server/server.go
/kind cleanup
We need to be able to watch other instances/caches than the configuration later on, so we now move the config scoped watcher into the server instance.
From https://github.com/cri-o/cri-o/pull/7046
None
None
```release-note
None
```
=> Move reload watcher into `Server`

contrib/test/ci/vars.yml, contrib/test/integration/vars.yml, dependencies.yaml, internal/config/seccomp/seccomp.go, internal/config/seccomp/seccomp_test.go, internal/factory/container/container.go, internal/factory/container/container_test.go, scripts/github-actions-setup, server/container_create_linux.go, server/sandbox_run_linux.go, test/ctr_seccomp.bats, test/seccomp_notifier.bats
/kind cleanup
Field based profiles should be standard since many Kubernetes releases, means we can drop the path based logic and cleanup some code.
None
None
```release-note
Dropped support for annotation based seccomp profiles, Kubernetes uses a native field since many releases.
```
=> Drop support for path based seccomp profiles

contrib/test/ci/build/bats.yml, dependencies.yaml
/kind ci
The `pull-ci-cri-o-cri-o-main-ci-fedora-integration` test is complaining about the wrong bats version:
```
/usr/go/src/github.com/cri-o/cri-o/test/./helpers.bash: line 4: bats_require_minimum_version: command not found
```
We should keep them in sync which is now enforced via `dependencies.yaml`.
None
None
```release-note
None
```
=> Bump bats in ci jobs to latest release

internal/factory/container/container_test.go
"AddCapabilities ALL" means different values in different environments, and our base value should be last rather than a fixed list value.
Fixes #7071 
```release-note
None
```
=> container_test: fix "AddCapabilities ALL" test case

server/container_status.go, server/inspect.go, server/inspect_test.go
This is a manual cherry-pick of #6925
```release-note
Fix a bug where sending information to cadvisor is stalled on taking the container's state lock
```
=> [1.26] server: do not take lock to populate pid in container status and inspect

internal/factory/container/device.go
/kind bug
When running a container with the kata runtime and setting up a block device, the device appears in the container with permissions set to 0.
The kata agent, creating this device in the VM, is applying the file mode provided in the spec file by cri-o - this field is not filled by cri-o, and defaults to 0.
This PR makes sure that the device's permission is provided in the spec, so that the agent can apply them appropriately.
None
```release-note
Fixed an issue preventing the use of block devices with kata containers
```
=> Fix filemode for device

internal/oci/container.go, internal/oci/container_test.go, internal/oci/container_test_inject.go, internal/oci/runtime_oci.go, internal/oci/runtime_oci_test.go, internal/oci/runtime_vm.go, server/container_execsync.go, server/container_remove.go, server/container_remove_test.go, server/container_stop.go, server/container_stop_test.go, server/sandbox_stop_linux.go
/kind bug
Before, there was the possibility load could cause cri-o to segfault from double closing of channels.
this PR aims to simplify container stop code while retaining the required behavior.
Now, the first stop begins a registration process where the container stop begins and new timeouts
come in to interrupt. There are two communication channels, and only one location where they can be closed.
This also adds a watcher mechanism so callers can wait on the container stop
This PR also includes some cleanups:
- replace IsAlive() with Living()
- move around where ShouldBeStopped() is called
cherry-pick of https://github.com/cri-o/cri-o/pull/7129
```release-note
Fix a very rare panic from a double closed channel in container stop
```
=> OCPBUGS-15868: [1.27] oci: simplify stopping code

test/metrics.bats
/kind ci
Currently, this test case keeps waiting for the container that was
already killed in case OOM detection has failed. This is a huge (15
minutes) waste of time.
To fix, change the logic to wait for container exit, and then check the
OOM. This also makes the test code more readable.
Also, add some debug info in case the test has failed.
Also, add a 1 second sleep to the container command, which apparently
improves the chances for the test to succeed.
None
Related to: https://github.com/cri-o/cri-o/issues/7035
```release-note
NONE
```
=> test/metrics: simplify OOM test

server/container_create_linux.go, test/helpers.bash, test/image.bats
/kind bug
When restoring containers, then we always restore an image ID based on the annotation. When creating containers, then we use the first digest with a higher priority than the image ID. We now streamline this behavior by always using an image ID.
Fixes https://github.com/cri-o/cri-o/issues/7143
Refers to https://github.com/kubernetes-incubator/cri-o/issues/531
cc @QiWang19 @mtrmac @nalind 
The change got introduced in https://github.com/cri-o/cri-o/pull/1116/commits/f3b7065bd80a53e4c48e8c45c36dcb86717e1578#diff-1ec6bb9cf833fd4ded46ce1feb6440f1d7532294e0445623f2f2e0bb2726ea63L976-R975
```release-note
Fixed bug where `ImageRef` refers to a digest rather than an image ID, which negatively impacted kubelets garbage collection.
```
=> Fix ImageRef field for containers to default to an image ID

server/container_status.go, server/inspect.go, server/inspect_test.go
This is a manual cherry-pick of #6925
```release-note
Fix a bug where sending information to cadvisor is stalled on taking the container's state lock
```
=> [1.25] server: do not take lock to populate pid in container status and inspect

scripts/version_bump.go
This PR adds the ```version_bump.go``` script to automatically bump the version in internal/version/version.go file.
/kind feature
We needed this feature to automate the version bumping using GitHub actions. This script has little use as of now, but as per issue https://github.com/cri-o/cri-o/issues/4003 this script would be used in the CI environment of GitHub actions to change the version and create pull requests.
fixes #7169 
This script is designed to work as below:
- run the command ```go run scripts/version_bump.go```
- The version inside the internal/version/version.go would be changed. For example: 1.2.3 to 1.2.4
It also supports additional arguments like:
- ```go run scripts/version_bump.go patch``` for patch bump. Example: 1.2.3 to 1.2.4
- ```go run scripts/version_bump.go …
```
=> add version_bump.go script to automate the release pipeline

internal/factory/container/device.go
This commit caused issue for non-root access to block devices
```release-note
Revert kata containers block devices fix because it prevents non-root users from accessing block devices (where they were previously able to)
```
=> [1.27] Revert "Fix filemode for device"

internal/factory/container/device.go
This commit causes issues with non-root access to block volumes
This reverts commit 320671ed237c3fb079a31c0dc9a46ee98d959781.
```release-note
Revert kata containers block devices fix because it prevents non-root users from accessing block devices (where they were previously able to)
```
=> Revert "devices: fill the FileMode field in spec"

docs/crio.conf.5.md, internal/factory/container/container.go, internal/factory/container/container_test.go, internal/lib/container_server.go, internal/oci/container.go, internal/oci/oci.go, internal/oci/runtime_oci.go, pkg/annotations/annotations.go, pkg/config/config.go, pkg/config/template.go, server/container_create_linux.go, test/helpers.bash, test/image.bats
This is a manual cherry-pick of #7180
cc @mrunalp 
```release-note
add platform_runtime_paths option to the runtime handler structure, which allows admins to define specific runtime paths based on different platforms.
```
=> [1.27] add platform_runtime_paths to RuntimeHandler

install.md
Fixes the indentation of some items in the installation instructions that I noticed were odd while installing cri-o.
None
None
```release-note
None
```
=> Fix indentation in installation instructions

scripts/release-notes/release_notes.go
The release notes now contain the full set of available bundles.
None
None
```release-note
Added `ppc64le` binaries to release notes
```
=> Add `ppc64le` binaries to release notes

.github/dependabot.yml
/kind ci
This allows updating the opentelemetry dependencies in a single PR.
Refers to https://github.com/cri-o/cri-o/pull/7259, https://github.com/cri-o/cri-o/pull/7258, https://github.com/cri-o/cri-o/pull/7260, https://github.com/cri-o/cri-o/pull/7261
```release-note
None
```
=> Add dependabot group for OTEL deps

server/container_create.go, server/container_create_linux.go, server/sandbox_run_linux.go
The current implemention has an issue where we add the default
capabilties when the user does drop ALL and add few.
```release-note
Fix drop ALL and add back few caps behavior to not include the default configured capabilities
```
=> [1.20] Add support to drop ALL and add back few capabilities

.github/workflows/test.yml, Makefile, contrib/bundle/Vagrantfile, contrib/bundle/build, contrib/bundle/install, contrib/bundle/registries.conf, dependencies.yaml, scripts/get
/kind ci
This test ensures a basic working setup for kubeadm bootstrapped clusters using the official packages.
We also have to add a default `registries.conf` to the bundle to make it work. As follow-up we will remove non-required binaries like the CNI plugins (no installed in parallel to the official packages).
Refers to https://github.com/cri-o/cri-o/issues/7280
The tests `get-script` and `get-script-with-verification` should become green after merge.
```release-note
Added default `registries.conf` to static binary bundle, which gets installed if not existing.
Only install `policy.json` from bundle if not existing.
```
=> Add Kubernetes package test for static binary bundle

internal/lib/checkpoint.go, internal/lib/checkpoint_test.go, server/container_checkpoint_test.go
/kind bug
The initial implementation of checkpointing in CRI-O was based on Podman and initially the default workflow would have been that the container is stopped after checkpointing. CRIU will just kill all processes in the container.
As the initial Kubernetes checkpointing feature is based on the Forensic Container Checkpointing KEP, the container keeps on running after checkpointing.
If the container keeps on running after checkpointing it can happen that the files in the container are changed once we put the into the checkpoint archive. This means that the files are different during restore than they were during checkpointing.
CRIU aborts restoring if the file size of any open file has changed as restoring will put the FD pointer at the same location as during checkpointing. If the …
=> Pause container during checkpointing

install.md
Using `apt-get install golang-go` on Debian/Ubuntu will end up with an older golang version, which will result in multiple errors while installing `cri-o`. 
If Go is already installed, it will shadow the installed version and change the env variables to point to the `apt-get` installed version ( an older version of Go) 
See: https://stackoverflow.com/questions/17480044/how-to-install-the-current-version-of-go-in-ubuntu-precise#comment38681257_17566846
For more information on release notes see:
https://git.k8s.io/community/contributors/guide/release-notes.md
```release-note
None
```
=> Remove golang-go from debian installation

go.mod, go.sum, internal/oci/oci.go, pkg/config/config.go, server/container_create_linux.go, server/container_create_linux_test.go, vendor/github.com/opencontainers/runtime-spec/specs-go/features/features.go, vendor/github.com/opencontainers/runtime-spec/specs-go/version.go, vendor/modules.txt
This is a backport of #7289 as the [automatic backport failed][link] due to changes in go.sum.
I don't know if the project uses manual backports, but doing it in case it helps, as time is pressing to get this in a new release. Feel free to close this if another solution is better :)
I've also tested this locally in this branch, all works fine.
cc @haircommander 
[link]: https://github.com/cri-o/cri-o/pull/7289#issuecomment-1714750921
---
if we don't, we risk container creation failures or security holes from the runtime not correctly setting up idmaps
/kind feature
For the 1.28 release branch it:
Fixes: #7262 
```release-note
Check the runtime supports IDMap support before specifying it
```
=> [1.28] config/server: add functions to check IDMap support in runtime

internal/storage/image.go
The current implementation of image names exhibits unpredictable behavior for users, as it relies on the order in which names were pulled, which is not guaranteed by the API. To address this issue, this commit proposes processing all names in image.Names through the filter.
/kind bug
```release-note
Fixed image name consistency for more predictable behavior with pinned images.
```
=> internal/storage: address unpredictable behavior of image names

install.md, tutorials/kubeadm.md
Branch master was renamed to main, update it directly without the help of github page redirection.
```release-note
None
```
=> docs: Update the containers/image branch name

internal/storage/image.go, internal/storage/image_test.go, server/container_create_linux.go, server/image_pull.go, server/image_remove.go, server/image_remove_test.go, server/image_status.go, server/image_status_test.go
/kind cleanup
As a prerequisite of work on sigstore signature signing (earlier #7046), I need to tighten how CRI-O refers to images, to use types and values with strict semantics. That significantly revolves around the values consumed and returned by `ResolveNames`; I will want to completely replace that with code more explicit about the semantics/heuristics.
Let’s start with some baby steps:
- Eliminate the `ErrCannotParseImageID` special error, which almost all callers special-case exactly the same way. Instead, have `ResolveNames` do what the callers need.
- This allows optimizing out one c/storage lookup (= 2 FS lock hits), when starting a container from an already-pulled image or when deleting an image by Kubelet’s GC
- Also fix some other smaller bugs and remove unnecessary code. …
=> Simplify, and optimize, ImageServer.ResolveNames

contrib/bundle/build, contrib/bundle/install, contrib/bundle/registries.conf, contrib/bundle/test, contrib/bundle/test-e2e, scripts/get
/kind feature
To make the build in OBS work with the latest spec.
Refers to https://github.com/cri-o/cri-o/issues/7280 and https://github.com/kubernetes/release/issues/3214
Inherited from https://github.com/cri-o/cri-o/pull/7243 and https://github.com/cri-o/cri-o/pull/7232
```release-note
Added registries.conf to CRI-O bundle
```
=> [1.28] Add registries.conf to CRI-O bundle

nix/derivation.nix
/kind cleanup
We do not need to patch the shebangs because all of those scripts are not required during build. This results in a `clearn` instead of `dirty` output when running `crio version`.
None
None
```release-note
None
```
=> Fix nix `dirty` build

internal/storage/runtime.go, internal/storage/runtime_test.go, server/sandbox_run_linux.go, server/sandbox_run_test.go, test/mocks/criostorage/criostorage.go
/kind cleanup
As one of prerequisites of per-namespace signature enforcement (the effort of #7046 ), it is _strictly necessary_ that exactly the image ID for which we have verified a signature is used to eventually create the container. This is a part of that, one of the necessary steps, starting fairly deep in the call stack. (With possibly more to come, as I actually come to understand the relevant parts of the full container lifecycle).
I also want to more strictly limit the semantics of values passed to `PullImage`, to make the problem space more manageable. This does not change anything about the value itself, but the simplification makes analysis a tiny bit more tractable.
Currently, `runtimeService.createContainerOrPodSandbox` handles both non-infra containers and the pause=infra …
=> Disambiguate image identification in container creation

.github/workflows/cron.yml, .github/workflows/test.yml, dependencies.yaml
/kind ci
This allows to decouple the racing CI between `main` and the latest release branch, which should make it more stable.
It's also possible to dispatch the forward manually, giving us more flexibility.
None
None
```release-note
None
```
=> Make the release branch fast forward a cronjob

contrib/test/ci/build/runc.yml, contrib/test/ci/vars.yml, contrib/test/integration/build/runc.yml, contrib/test/integration/vars.yml
Fixes https://github.com/cri-o/cri-o/issues/7337
Let's pin the latest release until the issue related to SELinux for runc gets relsoved.
/kind ci
```release-note
None
```
=> contrib/test: pin the latest release of runc

internal/oci/runtime_oci.go, test/mocks/cmdrunner/cmdrunner.go, utils/cmdrunner/cmdrunner.go
Support passing context through to *exec.Command by adding CommandContext to the CommandRunner interface. This allows context cancellation to terminate the running command.
/kind feature
Support creating an `*exec.Command` with a context, and link the lifetime of commands started by `ExecContainer` to that of the passed in context.
#6699 
```release-note
None
```
=> feat(cmdrunner): add support for context

internal/storage/image.go, internal/storage/image_test.go, server/image_list.go, server/image_list_test.go, server/image_status.go, test/image.bats, test/mocks/criostorage/criostorage.go
/kind cleanup
Turn `ListImages(filter)` into `ImageStatus`. That "filter" was never really much of a filter, we always only got one image.
The current logic is, effectively, the only user which accepts that specific form of heuristically-interpreted syntax (because all other non-`PauseImage` users of internal/storage use `ResolveNames`), so removing that syntax would consolidate and clarify the semantics of internal/storage names.
Kubelet never calls `ListImages` with a filter AFAIK, so this should make no difference in practice - and it means we get to remove a chunk of code and tests.
None
Do note that this changes how `ListImagesRequest.Filter.Image.Image` is interpreted (to be the same as the same field in of the same struct in `ImageStatusRequest.Image.Image`), and that might be an …
=> RFC: Turn ListImages(filter) into ImageStatus

docs/crio.conf.5.md, internal/storage/runtime.go, internal/storage/runtime_test.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/reload.go, pkg/config/reload_test.go, server/sandbox_run_linux.go, test/mocks/criostorage/criostorage.go
/kind cleanup
The handling of `pause_image` in `CreatePodSandbox` currently heuristically accepts many different values, and most would lead to very surprising behavior:
- Don't accept storage IDs (they work locally but can't be pulled)
- Don't accept prefixes of storage IDs either (if they ever match locally, that would be VERY surprising)
- Don't accept short names (`dir:foo` could locally search for `docker.io/library/dir:foo`, but then try to "pull" from local filesystem at `./foo`)
- Don't accept `transport:`_..._ values
Instead, just accept ordinary registry references, qualified with a host name (and, _undocumented_, use the traditional `docker.io/[library]` fallback semantics).
Also parse the `pause_image` option already at daemon start, and every reload.
I don’t expect this to …
=> RFC: Explicitly define a much stricter format for pause_image

internal/storage/image.go, internal/storage/image_id.go, internal/storage/image_id_test.go, internal/storage/image_test.go, internal/storage/references/registry_reference.go, internal/storage/references/registry_reference_test.go, internal/storage/references/suite_test.go, internal/storage/registry_reference.go, server/image_remove.go, server/image_remove_test.go, test/mocks/criostorage/criostorage.go
/kind cleanup
Split `ImageServer.ResolveNames` into two well-typed parsers
We will push the heuristics to the callers to make the heuristics explicit, very loud to readers, and most importantly to give callers well-typed data instead of ambiguous strings.
This introduces `storage.StorageImageID` and `storage.RegistryImageReference` types, with the intent that users dealing with `internal/storage` should only use these strongly-typed values, not strings, for image identification/referencing.
None
See individual commit messages for details. Overall, this should not actually change behavior of `RemoveImage`.
This is the beginning of the payoff of the recent API/semantics PRs. I have two similar directly related items queued to follow:
- Migrate `ImageServer.ImageStatus` to accept well-typed …
=> Use strongly encapsulated types with strict semantics for RemoveImage

internal/config/node/node_linux.go, internal/config/node/systemd_linux.go, internal/factory/container/container.go, internal/factory/container/container_test.go, internal/storage/image.go, server/container_create_linux.go, server/sandbox_run_linux.go
it was originally added because failed scopes weren't being cleaned up. This is the incorrect solution. Instead, the oci runtime should reset a failed unit after the container is done.
With inactive-or-failed property, systemd races with conmon reading the oom file of a container.
Note: this means that CRI-O should run with crun 1.9 and runc 1.1.8 or later. This should be enforced in the package.
fixes https://github.com/cri-o/cri-o/issues/7035
```release-note
No longer set inactive-or-failed collect mode property, which fixes a race with container that OOM kill. As a result, users should upgrade to runc 1.1.8 or crun 1.9
```
=> drop inactive-or-failed property

internal/criocli/status.go, pkg/types/types.go, server/inspect.go
/kind feature
This exposes imagestore to clients of CRI-O.
https://github.com/google/cadvisor/pull/3395 is one example of someone using this.
```release-note
add image store to crio-info.
```
=> update the crio api to reflect image store

install.md
For compiling crio  the `libseccomp` development version is needed otherwise `pkg-config` failed to find the library
and failed with
```
go build github.com/seccomp/libseccomp-golang:
Package libseccomp was not found in the pkg-config search path.
Perhaps you should add the directory containing `libseccomp.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libseccomp', required by 'virtual:world', not found
pkg-config: exit status 1
```
None
```release-note
none
```
=> docs: install `libseccomp-devel` instead of `libseccomp`

.github/workflows/nixpkgs.yml, .github/workflows/test.yml
/kind ci
We reuse the branch if we don't merge the PR within one week to avoid creating stale branches.
None
None
```release-note
None
```
=> Reuse nixpkgs branch for scheduled CI job

internal/config/cgmgr/cgmgr.go, internal/runtimehandlerhooks/default_cpu_load_balance_hooks.go, internal/runtimehandlerhooks/high_performance_hooks.go, test/cgroups.bats, test/cpu_load_balancing.bats
```release-note
fix a bug where the cgroup crun configures is different than that CRI-O sets load balancing/cpu quota on
```
=> [1.27] highperfhooks: apply cgroup setting to crun cgroup

server/container_create_linux.go, test/ctr.bats
previously we would never allow a container to get anything other than HostToContainer for something that contains the storage root. This breaks situations where the container wishes to update mount points within the container and see them propegated to the host.
Instead, we should only override this if the mount is Private.
/kind bug
fixes https://github.com/cri-o/cri-o/issues/7308
```release-note
fix a bug where CRI-O would override a Bidirectional mount in favor of a HostToContainer if the mount contained the host's container storage
```
=> server: allow Bidirectional mounts that contain storage root

server/container_create_linux.go, server/container_create_linux_test.go, test/ctr.bats
This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/7076 and https://github.com/cri-o/cri-o/pull/7408
```release-note
- Set mount type HostToContainer for mounts that include container storage root
- Fix a bug where CRI-O would override a Bidirectional mount in favor of a HostToContainer if the mount contained the host's container storage
```
=> [release-1.27] NO-ISSUE: server: allow Bidirectional mounts that contain storage root

internal/lib/restore.go, internal/lib/restore_test.go, internal/oci/container.go, internal/oci/container_test.go, server/container_create.go, server/container_restore.go, server/container_restore_test.go
/kind bug
The code was calling `checkIfCheckpointOCIImage`, which resolves short names into all candidates, and then using `ParseStoreReference`, which interprets short names as `docker.io/[library]`.
Instead, have `checkIfCheckpointOCIImage` return the resolved storage ID, use that, and avoid the redundant lookup entirely.
None
Initially, fixing this bug seemed easier than building the test mocks to work with the previous version of the code in #7302. Other than that, this has no relationship to signature verification.
Alternatively, the input → image ID resolution could use some other rules; either not resolving short names and hard-coding `docker.io`, or maybe even conceivably requiring an image ID as input. I don’t know what’s the right thing to do here; using the same rules as for …
=> Fix inconsistency in restore image name resolution

internal/storage/image.go, internal/storage/image_test.go, internal/storage/runtime.go, internal/storage/runtime_test.go, server/image_pull.go, server/image_pull_test.go, test/mocks/criostorage/criostorage.go
/kind bug
This is mostly refactoring:
- Split the 180-line `Server.pullImage` function into 3 major components, making it more manageable and simplifying the control flow
- Modify the `copyImageChild` subprocess interface to be able to return values. This will be necessary to return the correct resolved image reference after pulling an image.
- Then share _everything_ in the implementation of `PullImage` between the in-process and `copyImageChild` variants, so that we can consistently enforce signature policies in the future without duplicating it in two implementations (which have _already_ diverged by now).
+ some smaller cleanups and bug fixes along the way.
None
See individual commit messages for details.
I didn’t even smoke-test the “experimental” `copyImageChild` code path.
Cc: …
=> Prepare image pulling for per-namespace signature enforcement

internal/factory/container/container.go, internal/factory/sandbox/sandbox.go, internal/factory/sandbox/sandbox_setnameandid_test.go
/kind bug
Pre-validate sandbox uid values before creation in the same way it's already done for the container name.
Fixes https://github.com/cri-o/cri-o/issues/7351
**_This is a revert of https://github.com/cri-o/cri-o/pull/3774_**
```release-note
Validate pod namespace and uid before creation.
```
=> Validate pod uid

pkg/config/config.go
since /dev/fuse is the default allowed device, this effectively only allows /dev/fuse for all pods in the default runtime class
```release-note
allow the `io.kubernetes.cri-o.Devices` annotation in the default runtime class, which along with AllowedDevices containing /dev/fuse by default, gives containers in the default runtime class optional access to /dev/fuse
```
=> config: allow the devices annotation in the default runtime class

.golangci.yml, server/container_create_linux.go
/kind cleanup
Combining both settings does not make much sense because the option `noNewPrivileges` will do nothing for containers using privileged or `CAPCAP_SYS_ADMIN`. We now warn users if that's the case.
None
None
```release-note
Warn users on container creation when trying to use `noNewPrivileges` on privileged or `CAP_SYS_ADMIN`.
```
=> Warn users when trying to use `noNewPrivileges` on privileged or `CAP_SYS_ADMIN`

go.mod, go.sum, vendor/github.com/containers/common/pkg/apparmor/apparmor_linux.go, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
/kind bug
`github.com/containers/common` need to bump to v0.55.4+165b7a4d, for fixing AppArmor error with Ubuntu 23.10.
Fixes https://github.com/cri-o/cri-o/issues/7490
go get github.com/containers/common@v0.55.5-0.20231119144331-165b7a4dd43c
go mod tidy
go mod vendor
find vendor/ -type f -name '.gitattributes' -delete
git add --all --force vendor/
git add --all .
make
```release-note
go get github.com/containers/common@v0.55.5-0.20231119144331-165b7a4dd43c
```
=> [release-1.28] `go get github.com/containers/common@v0.55.5-0.20231119144331-165b7a4dd43c`

docs/crio.8.md, docs/crio.conf.5.md, pkg/config/config.go
even though the oci runtime spec says 0 should be unlimited, runc does not interpret it as such
```release-note
update pids_limit field to be -1 by default. Even though it's deprecated, having -1 is correctly interpreted by runc as unlimited, as the original intent of the 0 value was meant to be.
```
=> config: set default pids limit to -1

contrib/test/ci/e2e-base.yml
=> Fix git package upgrade for e2e tests

go.mod, go.sum, vendor/github.com/containers/common/pkg/apparmor/apparmor_linux.go, vendor/modules.txt
/kind bug
`github.com/containers/common` need to bump to v0.53.0+165b7a4d, for fixing AppArmor error with Ubuntu 23.10.
Fixes https://github.com/cri-o/cri-o/issues/7490
I give a temp fork branch for v0.53.0 + cherry-pick, see https://github.com/alvistack/containers-common/commits/alvistack/v0.53
go mod edit -replace="github.com/containers/common@v0.53.0=github.com/alvistack/containers-common@v0.53.0"
sed -i 's?common v0.53.0?common v0.53.1-0.20231122050942-6c64d1accb28?g' go.mod
go mod tidy
go mod vendor
find vendor/ -type f -name '.gitattributes' -delete
git add --all --force vendor/
git add --all .
make
```release-note
go get github.com/alvistack/containers-common@v0.53.1-0.20231122050942-6c64d1accb28
```
=> [release-1.27] `go get github.com/containers/common@v0.53.1-0.20231122050942-6c64d1accb28`

.github/workflows/test.yml
I think we can remove the test since it inherits from old CircleCI times. 
Fixes https://github.com/cri-o/cri-o/issues/7570
None
```release-note
None
```
=> Remove 386 build test

go.mod, go.sum, vendor/github.com/containers/common/pkg/apparmor/apparmor_linux.go, vendor/modules.txt
Reverts cri-o/cri-o#7499, as per the consensus that we cannot rely on private forks.
This bug fix has a rather complex history behind it, see:
- https://github.com/containers/common/issues/1746
None
None
```release-note
None
```
=> Revert "[release-1.27] `go get github.com/containers/common@v0.53.1-0.20231122050942-6c64d1accb28`"

scripts/github-actions-setup
/kind ci
To fix the following failure related to Ginkgo setup step:
```
+ install_ginkgo
++ go env GOPATH
+ GOPATH=/home/runner/go
++ id -u
++ id -g
+ sudo chown -R 1001:127 /home/runner/go
+ go install github.com/onsi/ginkgo/ginkgo@latest
go: downloading github.com/onsi/ginkgo v1.16.5
go: github.com/onsi/ginkgo/ginkgo@latest: github.com/onsi/ginkgo/ginkgo: open /home/runner/.cache/go-build/7e/7ef034d25a873f232bad78599087e86cefc2feaa947b7b1a0bba5926e9eb2430-d: permission denied
```
None
None
```release-note
None
```
=> [release-1.25] Backport install_ginkgo() from CRI-O release 1.26

scripts/github-actions-setup
/kind ci
To fix the following failure related to Ginkgo setup step:
```
+ install_ginkgo
++ go env GOPATH
+ GOPATH=/home/runner/go
++ id -u
++ id -g
+ sudo chown -R 1001:127 /home/runner/go
+ go install github.com/onsi/ginkgo/ginkgo@latest
go: downloading github.com/onsi/ginkgo v1.16.5
go: github.com/onsi/ginkgo/ginkgo@latest: github.com/onsi/ginkgo/ginkgo: open /home/runner/.cache/go-build/7e/7ef034d25a873f232bad78599087e86cefc2feaa947b7b1a0bba5926e9eb2430-d: permission denied
```
None
None
```release-note
None
```
=> [release-1.24] Backport install_ginkgo() from CRI-O release 1.26

dependencies.yaml, scripts/github-actions-setup, scripts/versions
Buildah doesn't install well on arm64, which is now fixed. We also update the version to the latest release.
None
None
```release-note
None
```
=> Fix buildah setup for critest on arm64

internal/lib/checkpoint.go
/kind bug
The CRI-O implementation for container checkpointing is based on Podman. One of the differences between CRI-O and Podman is that with CRI-O, containers continue to run after checkpointing, and the checkpoint is exported as a tar archive file. However, after the checkpoint has been created, all checkpoint files remain in the userdata directory of the container. As a result, subsequent checkpoints include files from previous checkpoints. To fix this problem, this patch ensures that we clean up the checkpoint directory after the checkpoint files have been exported.
The original pull request introducing container checkpoint (https://github.com/cri-o/cri-o/pull/4199) contains more information about exporting of checkpoints.
```release-note
Clean up container checkpoint directory …
```
=> checkpoint: clean-up checkpoint dir after export

docs/crio.conf.5.md
`The final policy to be used on image pull will be <SIGNATURE_POLICY_DIR>/<NAMESPACE>.json.` is shown as 
`The final policy to be used on image pull will be <SIGNATURE_POLICY_DIR>/.json. `
None
```release-note
None
```
=> Fix typo in crio.conf.5.md signature policy path

server/image_fs_info.go, server/image_fs_info_test.go
Implement Image_Fs_Info as part of the separate gc KEP.  We should not merge unless this KEP is approved.  TODO: Add a link.  
Opening this up now to gather feedback on feasibility of this implementation.
Note, since I had a few changes in other areas, I vendored these changes here.  I already opened up a PR into c/storage.  Kubernetes is based on KEP approval.
We are having some problems with the integration tests picking up an older version of crictl. I moved the integration tests to https://github.com/cri-o/cri-o/pull/7269 just to move this PR through.
```release-note
Added more file system information in `ImageFsInfo` as part of the garbage collection KEP.
```
=> CRIO changes to support split filesystem 

cmd/crio/main.go
when node reboot, cri-o no longer clear containers anymore
/kind cleanup
as https://github.com/cri-o/cri-o/pull/6509/files has already fixed, node reboot will not trigger containers wipe anymore
no
```release-note
None
```
=> cri-o no longer wipe containers when node reboot

utils/utils.go, utils/utils_test.go
/kind cleanup
Replaces the `WriteGoroutineStacks()` function, which is an open-coded version of the same goroutines stacks printer routine that is available in the built-in **runtime/pprof** package, per:
- [runtime/pprof/pprof.go;l=697-716](https://cs.opensource.google/go/go/+/refs/tags/go1.21.0:src/runtime/pprof/pprof.go;l=697-716) (Go version **1.21.0**)
The built-in function also provides a larger default internal buffer size to fit the results (64 MiB by default).
Generally, we don't need to carry this code ourselves; as such, it's safe to remove it.
Related to:
- https://github.com/cri-o/cri-o/pull/1813
- https://github.com/cri-o/cri-o/pull/2373
None
None
```release-note
None
```
=> Remove open-coded goroutines stacks printer

.github/workflows/test.yml, go.mod, go.sum, vendor/github.com/containers/common/version/version.go, vendor/modules.txt
/kind bug
Manually cherry-pick changes from https://github.com/containers/common/pull/1689 as these changes contain a fixe that needs to be backported to CRI-O release 1.28, part of OpenShift 4.15 release.
Related:
- https://github.com/containers/common/pull/1689
- https://github.com/containers/common/issues/1746
- https://github.com/cri-o/cri-o/pull/7496
- https://github.com/cri-o/cri-o/pull/7498
Closes:
- https://github.com/cri-o/cri-o/issues/7490
None
None
```release-note
None
```
=> [release-1.28] Cherry-pick changes from containers/common/pull#1689

go.mod, go.sum, vendor/github.com/containers/common/pkg/apparmor/apparmor_linux.go, vendor/modules.txt
/kind bug
Manually cherry-pick changes from https://github.com/containers/common/pull/1689 as these changes contain a fixe that needs to be backported to CRI-O release 1.27, part of OpenShift 4.14 release.
Related:
- https://github.com/containers/common/pull/1689
- https://github.com/containers/common/issues/1746
- https://github.com/cri-o/cri-o/pull/7496
- https://github.com/cri-o/cri-o/pull/7499
- https://github.com/cri-o/cri-o/pull/7573
Closes:
- https://github.com/cri-o/cri-o/issues/7490
None
None
```release-note
None
```
=> [release-1.27] Cherry-pick changes from containers/common/pull#1689

go.mod, go.sum, vendor/github.com/Microsoft/hcsshim/.gitattributes, vendor/github.com/containerd/fifo/.gitattributes, vendor/github.com/containers/storage/layers.go, vendor/github.com/fsnotify/fsnotify/.gitattributes, vendor/github.com/fsouza/go-dockerclient/.gitattributes, vendor/github.com/go-task/slim-sprig/.gitattributes, vendor/github.com/kevinburke/ssh_config/.gitattributes, vendor/github.com/klauspost/compress/.gitattributes, vendor/go.opentelemetry.io/otel/.gitattributes, vendor/k8s.io/client-go/pkg/version/.gitattributes, vendor/k8s.io/component-base/version/.gitattributes, vendor/modules.txt
/kind bug
Manually cherry-pick changes from https://github.com/containers/storage/pull/1641 as these changes contain a fixe that needs to be backported to CRI-O release 1.24, part of OpenShift 4.11 release.
Related:
- https://github.com/containers/storage/pull/1641
- https://github.com/cri-o/cri-o/pull/7171
- https://github.com/cri-o/cri-o/pull/7536
None
None
```release-note
None
```
=> [release-1.24] OCPBUGS-25909: Cherry-pick changes from containers/storage/pull#1641

go.mod, go.sum, vendor/github.com/Microsoft/hcsshim/.gitattributes, vendor/github.com/containerd/fifo/.gitattributes, vendor/github.com/containers/common/pkg/apparmor/apparmor_linux.go, vendor/github.com/fsnotify/fsnotify/.gitattributes, vendor/github.com/fsouza/go-dockerclient/.gitattributes, vendor/github.com/go-task/slim-sprig/.gitattributes, vendor/github.com/kevinburke/ssh_config/.gitattributes, vendor/github.com/klauspost/compress/.gitattributes, vendor/go.opentelemetry.io/otel/.gitattributes, vendor/k8s.io/client-go/pkg/version/.gitattributes, vendor/k8s.io/component-base/version/.gitattributes, vendor/modules.txt
/kind bug
Manually cherry-pick changes from https://github.com/containers/common/pull/1689 as these changes contain a fixe that needs to be backported to CRI-O release 1.24, part of OpenShift 4.11 release.
Related:
- https://github.com/containers/common/pull/1689
- https://github.com/containers/common/issues/1746
- https://github.com/cri-o/cri-o/pull/7496
Closes:
- https://github.com/cri-o/cri-o/issues/7490
None
None
```release-note
None
```
=> [release-1.24] Cherry-pick changes from containers/common/pull#1689

.snyk
/kind other
Some security scanners, such as the [csmock](https://github.com/csutils/csmock), wrap the Snyk scanner and often hand paths directly to it that are fully qualified. This seems to make Snyk not apply the exclude configuration correctly, since the `vendor` directory can have a prefix (of some other top-level directory), for example:
```console
"file_name": "cri-tools-3c91ebf539bd2035d60813386f5b1f023937423f/vendor/k8s.io/apimachinery/pkg/util/managedfields/pod.yaml"
```
The above would result in Snyk not respecting directory exclusion and scanning the content of the `vendor` directory, which is undesirable.
Thus, we add a wildcard to accept any prefix in front of the `vendor` directory, should any be provided.
Related to:
- …
=> Update Snyk configuration file to exclude vendor directory with a prefix

deprecating_process.md
Documented the general deprecation process in cri-o. 
Issue : Document configuration deprecation process #6959
```release-note
```
=> Added a document of the deprecating process

contrib/test/ci/critest-images.yaml, server/utils.go
/kind cleanup
```release-note
None
```
=> fix typo for time out

go.mod, go.sum, vendor/github.com/cri-o/ocicni/pkg/ocicni/util_freebsd.go, vendor/modules.txt
This picks up fixes which make the mapping from pods/containers to FreeBSD jails slightly more efficient.
Once this is merged, I will rebase #7472, aiming to move the FreeBSD port forward a little quicker this year.
/kind cleanup
Sync with github.com/cri-o/ocicni to pick up FreeBSD improvements
None
```release-note
None
```
=> build(deps): bump ocicni to latest master

internal/oci/runtime_oci.go, internal/oci/runtime_vm.go, server/metrics/metrics.go, test/metrics.bats
to prevent an ever growing vector and cardinality
/kind bug
```release-note
cleanup deleted container from `container_runtime_crio_containers_oom` metric, preventing leaks and high cardinality
```
=> metrics: remove deleted containers from OOM count metrics

internal/runtimehandlerhooks/default_cpu_load_balance_hooks_linux.go, internal/runtimehandlerhooks/default_cpu_load_balance_hooks_unsupported.go, internal/runtimehandlerhooks/high_performance_hooks_linux.go, internal/runtimehandlerhooks/high_performance_hooks_test.go, internal/runtimehandlerhooks/runtime_handler_hooks.go, server/container_create_linux.go
/kind bug
When the prestart hook gets called the config.json files is already created. This means the process exist but it's not contating the mixed CPUS environment variables.
In order to fix that we should implement a new hook point - precreate hook that runs before the container create stage and inject the environment variables if needed.
None
```release-note
None
```
=> OCPBUGS-27963: highperfhooks: add precreate hook for injecting envs

internal/oci/container.go, internal/oci/runtime_oci.go, internal/oci/runtime_oci_test.go
if we hit a TOCTOU race with c.Living() and StopLoopForContainer, then we will be forced to wait until the kubelet re-requests. instead, update watchers immediately so this doesn't happen
/kind bug
```release-note
fix a bug where a container that exits soon after a StopContainer request is issued will be paused in termination for longer than the grace period
```
=> oci: handle early exited container faster in stop loop

internal/lib/container_server.go, internal/lib/container_server_test.go
/kind bug
Although there is a PR #6153 to fix issue #5490, but the problem still persists (see: https://github.com/cri-o/cri-o/issues/5490#issuecomment-1403716666). The root cause of the issue is that after crio restarts, the data for infraContainers is lost as  it is stored in memory(https://github.com/cri-o/cri-o/blob/main/internal/lib/container_server.go#L585). During the restore process, the sandbox and containers are reconstructed and restored through **LoadSandbox** and **LoadContainer** in restore funtion(https://github.com/cri-o/cri-o/blob/main/server/server.go#L222-L279), but the infraContainers are not restored during **LoadSandbox**.
As a result, when kubelet cadvisor queries and retrieves infraContainer information, it returns an **errCtrNotFound** …
=> When crio restarts, restore the infraContainers

test/ctr.bats
We have to omit the runc warning introduced by:
https://github.com/opencontainers/runc/blob/02120488a4c0fc487d1ed2867e901eeed7ce8ecf/libcontainer/specconv/spec_linux.go#L1017-L1030
None
None
```release-note
None
```
=> Fix ctr log max test on arm64

tutorials/install-distro.md
documentation
While I was reading through the documentation, I noticed that the URL for openSUSE's OBS in the `install-distro.md` file is not working. Therefore, this PR updates the URL to fix the issue. The previous URL was missing the `https://` protocol, which could cause problems when trying to access the site. This update corrects the URL to include the `https://` protocol, ensuring that the link will properly direct users to openSUSE's OBS page.
Please verify that the updated link works as expected.
No
```release-note
None
```
=> Update openSUSE's OBS URL in install-distro.md file

internal/factory/sandbox/infra.go
if DnsConfig empty, it should copy the host's resolv.conf
/kind other
This PR coordinates the behavior with the containerd. https://github.com/containerd/containerd/pull/9730
None
Reference https://github.com/kubernetes/kubernetes/issues/120748
I guess some users will find this behavior a breaking change.
```release-note
In case of an empty struct of DSNConfig /etc/resolv.conf be copied.
```
=> CRI: An empty DNSConfig != unspecified

internal/lib/container_server.go, internal/lib/container_server_test.go
This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/7726
/kind bug
```release-note
Restore infra containers state on CRI-O restart. Without this, the infra containers will be accounted as missing, leading to a spurious error message.
```
=> [release-1.25] When crio restarts, restore the infraContainer

.github/workflows/integration.yml, .github/workflows/test.yml
/kind ci
The integration tests seems to be a bit flaky these days. We now set `fail-fast` to `false` to not abort ongoing jobs which may succeed.
Ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast
None
None
```release-note
None
```
=> GitHub actions: Don't fail-fast matrix

go.mod, go.sum, vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go, vendor/github.com/containers/common/pkg/umask/umask.go, vendor/modules.txt
/kind bug
Refers to https://issues.redhat.com/browse/OCPBUGS-29251
None
None
```release-note
Fixed wrong umask of `0000`.
```
=> OCPBUGS-29251: [release-1.25] Fix wrong umask by updating c/common

go.mod, go.sum, vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go, vendor/github.com/containers/common/pkg/umask/umask.go, vendor/modules.txt
/kind bug
Refers to https://issues.redhat.com/browse/OCPBUGS-29398
None
None
```release-note
Fixed wrong umask of `0000`.
```
=> OCPBUGS-29398: [release-1.26] Fix wrong umask by updating c/common

contrib/test/ci/vars.yml, server/container_create_linux.go, test/seccomp_oci_artifacts.bats
/kind bug
We should filter the image annotations in the same way as for the sandbox/container annotations to avoid misusage. The seccomp OCI artifact feature relies on image annotations which will only be considered when allowed by the runtime now.
None
None
```release-note
None
```
=> Filter image annotations before used

server/container_create_linux.go, test/helpers.bash, test/image.bats
/kind bug
This reverts commit 41b13e28dd75828ab9cc24806ad4d2d3b4a605b9 and therefore https://github.com/cri-o/cri-o/pull/7149.
None
None
```release-note
Reverted image ID field change in the container status.
```
=> [release-1.28] Revert "Fix ImageRef field for containers to default to an image ID"

.github/dependabot.yml
/kind ci
We now group all types of updates together and don't focus on a subset of them.
None
None
```release-note
None
```
=> Add all update types to dependabot groups

internal/config/nsmgr/test/utils.go, internal/lib/container_server.go, internal/lib/container_server_test.go, internal/lib/restore_test.go, internal/lib/sandbox/sandbox_test.go, internal/lib/suite_test.go, internal/oci/container.go, internal/oci/container_test.go, internal/oci/suite_test.go, internal/runtimehandlerhooks/high_performance_hooks_test.go, server/container_create_linux.go, server/container_status.go, server/inspect.go, server/inspect_test.go, server/sandbox_run_freebsd.go, server/sandbox_run_linux.go, server/suite_test.go, test/helpers.bash, test/image.bats
/kind bug
This reverts commit 41b13e28dd75828ab9cc24806ad4d2d3b4a605b9 and therefore https://github.com/cri-o/cri-o/pull/7149
None
None
```release-note
Reverted image ID field change in the container status. While the change did fix an issue with Kubelet image GC, it caused an unintended change in the container status of the Kubernetes pod API, breaking an accidentally stable API
```
=> Revert "Fix ImageRef field for containers to default to an image ID"

.golangci.yml, internal/config/nsmgr/test/utils.go, internal/lib/container_server.go, internal/lib/container_server_test.go, internal/lib/restore_test.go, internal/lib/sandbox/sandbox_test.go, internal/lib/suite_test.go, internal/oci/container.go, internal/oci/container_test.go, internal/oci/suite_test.go, internal/runtimehandlerhooks/high_performance_hooks_test.go, server/container_create_linux.go, server/container_status.go, server/inspect.go, server/inspect_test.go, server/sandbox_run_linux.go, server/suite_test.go, test/helpers.bash, test/image.bats
/kind bug
This reverts commit 41b13e2.
Manual backport of https://github.com/cri-o/cri-o/pull/7762
None
None
```release-note
Reverted image ID field change in the container status. While the change did fix an issue with Kubelet image GC, it caused an unintended change in the container status of the Kubernetes pod API, breaking an accidentally stable API.
```
=> [release-1.29] Revert "Fix ImageRef field for containers to default to an image ID"

contrib/test/ci/vars.yml, docs/crio.conf.5.md, internal/config/seccomp/seccompociartifact/seccompociartifact.go, pkg/annotations/annotations.go, pkg/config/config.go, pkg/config/template.go, test/seccomp_oci_artifacts.bats
/kind feature
We now additionally allow the plain
`seccomp-profile.kubernetes.cri-o.io` annotation for container images, to not require users to suffix the annotation using `/POD` or a container name.
None
None
```release-note
None
```
=> Allow plain annotation `seccomp-profile.kubernetes.cri-o.io` for images

contrib/test/ci/vars.yml, internal/config/ociartifact/ociartifact.go, internal/config/seccomp/seccompociartifact/seccompociartifact.go, internal/config/seccomp/seccompociartifact/seccompociartifact_test.go, test/mocks/ociartifact/ociartifact.go, test/seccomp_oci_artifacts.bats
/kind cleanup
CRI-O now pulls OCI artifacts directly in-memory after the discussions in https://github.com/containers/image/pull/2306 and https://github.com/kubernetes/website/pull/45121.
CRI-O also enforces the config media type
`application/vnd.cncf.seccomp-profile.config.v1+json` for seccomp profiles.
None
None
```release-note
None
```
=> In-memory OCI artifact pull

scripts/versions
/kind cleanup
None
Files sourced in a shell script (often used as configuration files) should not set new settings for the shell instance itself or explicitly export any variables. This way, shell scripts that include it wouldn't be affected/changed following sourcing the file.
```release-note
None
```
=> Keep versions file simple to source only

server/runtime_status.go
/kind bug
The feature can be enabled when we implemented it in CRI-O.
Follow-up on https://github.com/cri-o/cri-o/pull/7765#discussion_r1506892815
Refers to https://github.com/kubernetes-sigs/cri-tools/pull/1344#issuecomment-1970245805
cc @giuseppe @AkihiroSuda 
```release-note
None
```
=> Disable Recursive Read-only (RRO) mounts feature

internal/runtimehandlerhooks/high_performance_hooks_linux.go, internal/runtimehandlerhooks/high_performance_hooks_test.go
/kind bug
When a container in a pod with the cpu-c-states.crio.io or cpu-freq-governor.crio.io annotations is restarted, the high performance pre-start hook is called again. The current code will overwrite the stored pm_qos_resume_latency and/or scaling_governor with those that were written to /sys/devices/system/cpu/cpuX the first time the pre-start hook was called. Then when the pod is deleted, the pre-stop hook will restore the incorrect pm_qos_resume_latency and/or scaling_governor values.
The fix is to only store the pm_qos_resume_latency and/or scaling_governor the first time the pre-start hook is run. If the stored values already exist the pre-start hook will not overwrite them.
None
None
```release-note
None
```
=> Do not overwrite stored latency/governor on container restart

internal/process/defunct_processes.go
/kind cleanup
/kind other
The number of defunct (zombie) processes, ideally zero, can go up and down on a given node. Such orphaned processes might be a sign of a problem with some software or a script. This is something we track as part of CRI-O's process metrics collection.
Collecting data about processes in such a state is helpful, but there is no need for the metrics collector code, which also runs quite often, to produce a log line every time a defunct process is found. Why? There is nothing CRI-O can do about these processes, and eventually system init process will reparent them and collect their pending statuses, hopefully.
However, given that it might take a while for a defunct process to be taken care of, the current code would produce a substantial number of log lines that added …
=> Change process metrics collector log levels

go.mod, go.sum, vendor/github.com/containerd/otelttrpc/config.go, vendor/github.com/containerd/otelttrpc/interceptor.go, vendor/github.com/containerd/otelttrpc/internal/parse.go, vendor/github.com/containerd/otelttrpc/metadata_supplier.go, vendor/github.com/containerd/otelttrpc/semconv.go, vendor/github.com/containerd/otelttrpc/version.go, vendor/modules.txt
Update otelttrpc to latest HEAD to get rid of custom import path checks which reportedly break RPM package builds.
Without this change the otelttrpc version we use has 'custom import path check' annotating comments in place, which reportedly break RPM package building. The updated otelttrpc version has eliminated those annotations.
None
```release-note
None
```
=> OCPBUGS-30203: deps: update otelttrpc to get rid of 'custom import path checks'

go.mod, go.sum, vendor/github.com/containerd/otelttrpc/config.go, vendor/github.com/containerd/otelttrpc/interceptor.go, vendor/github.com/containerd/otelttrpc/internal/parse.go, vendor/github.com/containerd/otelttrpc/metadata_supplier.go, vendor/github.com/containerd/otelttrpc/semconv.go, vendor/github.com/containerd/otelttrpc/version.go, vendor/modules.txt
Update otelttrpc to latest HEAD to get rid of custom import path checks which reportedly break RPM package builds.
Without this change the otelttrpc version we use has 'custom import path check' annotating comments in place, which reportedly break RPM package building. The updated otelttrpc version has eliminated those annotations.
None
```release-note
None
```
=> [release-1.29] OCPBUGS-30240: deps: update otelttrpc to get rid of 'custom import path checks'

internal/config/ociartifact/impl.go, internal/config/ociartifact/ociartifact.go, internal/config/ociartifact/ociartifact_test.go, internal/config/seccomp/seccompociartifact/seccompociartifact.go, test/mocks/ociartifact/ociartifact.go
/kind feature
We now utilize an on-disk key/value cache for OCI artifacts. The digests will be used to identify if a layer has to be re-pulled or not. The artifact API now returns a path to the file on disk.
None
None
```release-note
Added OCI artifact layer cache to avoid repeatedly pulling the same container image.
```
=> Add OCI artifact layer cache

test/helpers.bash, test/pod_annotations_capability.bats
/kind flake
We hit the following error in CI:
```
time="2024-03-12 08:43:22.550384064Z" level=info msg="CNI monitoring event CREATE        \"/tmp/tmp.PiZMelzV6x/cni/net.d/001-log_cni_plugin.conflist\"" file="ocicni/ocicni.go:155"
time="2024-03-12 08:43:22.550557032Z" level=error msg="Error loading CNI config list file /tmp/tmp.PiZMelzV6x/cni/net.d/001-log_cni_plugin.conflist: error parsing configuration list: unexpected end of JSON input" file="ocicni/ocicni.go:298"
```
Assuming that CRI-O reads the config while the test still writes to it causes invalid JSON. This can be mitigated by writing the config before starting CRI-O.
Fixes https://github.com/cri-o/cri-o/issues/7802
None
```release-note
None
```
=> Deflake `pod annotations capability for chained cni plugins` test

internal/runtimehandlerhooks/high_performance_hooks_test.go
/kind cleanup
The `goconst` linter, part of the linter suite offered through the `golangci-lint` project, keeps raising issues about duplicated and repeated string values that can be turned into a set of constants, for example:
```console
Error: string `conservative ondemand userspace powersave performance schedutil` has 3 occurrences, make it a constant (goconst)
Error: string `schedutil` has 3 occurrences, make it a constant (goconst)
Error: string `n/a` has 3 occurrences, make it a constant (goconst)
```
This is nice the https://github.com/cri-o/cri-o/pull/7827 has been merged. Thus, collect and turn such string values into constants.
Related:
- https://github.com/cri-o/cri-o/pull/7827
None
Perhaps this particular linter is best to be disabled?
```release-note
None
```
=> Change duplicated string values into constants

go.mod, go.sum, vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go, vendor/modules.txt
/kind bug
Manually cherry-pick changes from https://github.com/containers/common/pull/1437 as these changes contain a fix that needs to be backported to CRI-O release 1.25, part of OpenShift 4.12 release.
Related:
- https://github.com/containers/common/pull/1421
- https://github.com/containers/common/pull/1437
- https://github.com/containers/common/pull/1908
Closes:
- https://github.com/cri-o/cri-o/issues/7880
None
None
```release-note
None
```
=> [release-1.26] OCPBUGS-30896: Cherry-pick changes from containers/common/pull#1437

go.mod, go.sum, vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go, vendor/modules.txt
/kind bug
Manually cherry-pick changes from https://github.com/containers/common/pull/1437 as these changes contain a fix that needs to be backported to CRI-O release 1.25, part of OpenShift 4.12 release.
Related:
- https://github.com/containers/common/pull/1421
- https://github.com/containers/common/pull/1437
- https://github.com/containers/common/pull/1907
Closes:
- https://github.com/cri-o/cri-o/issues/7880
None
None
```release-note
None
```
=> [release-1.25] OCPBUGS-30883: Cherry-pick changes from containers/common/pull#1437

contrib/test/ci/vars.yml, internal/oci/container.go, internal/oci/container_linux.go, internal/oci/container_test.go, internal/oci/container_unsupported.go, internal/oci/runtime_oci.go, internal/oci/runtime_oci_test.go, test/ctr.bats
=> [release-1.29] OCPBUGS-30653: Add exponential backoff to the container stop loop

contrib/test/ci/vars.yml, internal/oci/container.go, internal/oci/container_freebsd.go, internal/oci/container_freebsd_nocgo.go, internal/oci/container_linux.go, internal/oci/container_test.go, internal/oci/runtime_oci.go, internal/oci/runtime_oci_test.go, test/ctr.bats
/kind bug
Currently, when CRI-O attempts to stop a container where the process within, especially an init process (the so-called "PID 1"), is in an uninterruptible blocking state (for example, it's sleeping and waiting for a disk I/O completion, etc.), CRI-O will enter a broken state where it tries to delivery termination signals to such a process as fast as possible.
Nonetheless, a blocked process might not promptly respond to the signals delivered, causing CRI-O to enter a "busy loop" while it repeatedly tries to signal delivery. This seemingly unbound loop can render CRI-O unresponsive and result in high CPU usage while it happens.
Thus, add exponential backoff support to the container stop loop to fix the possible busy loop issue irregardless of the current state of the process to be …
=> OCPBUGS-28981: Add exponential backoff to the container stop loop

contrib/test/ci/vars.yml, internal/oci/container.go, internal/oci/container_test.go, internal/oci/runtime_oci.go, internal/oci/runtime_oci_test.go, test/ctr.bats
=> [release-1.28] OCPBUGS-30654: Add exponential backoff to the container stop loop

contrib/test/ci/vars.yml, internal/oci/container.go, internal/oci/container_test.go, internal/oci/runtime_oci.go, internal/oci/runtime_oci_test.go, test/ctr.bats
=> [release-1.27] OCPBUGS-30655: Add exponential backoff to the container stop loop

.packit.yaml
With this change:
- COPR builds are now run per-PR
- Packit will open PRs to the Fedora dist-git repo when a new release is created
- the `%global commit0` value is updated in the specfile for each build
cc @haircommander 
/kind ci
```release-note
packit: Update config and sync to Fedora
```
=> packit: Update config and sync to Fedora

internal/storage/image.go, internal/storage/image_test.go, internal/storage/runtime.go, internal/storage/runtime_test.go, server/image_pull.go, server/image_pull_test.go, test/mocks/criostorage/criostorage.go
/kind feature
We now support a pull context which can actually be cancelled. This way we can combine the pull progress together with a dynamic timeout, which cancels the context if no progress is being made on pull.
Refers to https://github.com/cri-o/cri-o/issues/7885
cc @mrunalp 
```release-note
Added dynamic image pull timeout if the network availability goes down during the operation.
```
=> Add dynamic image pull timeout

internal/config/cgmgr/cgroupfs_linux.go, internal/config/cgmgr/systemd_linux.go, pkg/config/template.go, pkg/config/workloads.go, pkg/config/workloads_test.go
Added the ability to support cpuquota and cpuperiod for specific workloads, this allows more fine tune control for containers that are assigned to those workloads to be set to a specific CPU quota.
Added a wrapper struct for annotation object to be used for information such as cpu milli cores to be used in the calculation for cpu quota.
Design Info:
[Enhancement Proposal](https://github.com/openshift/enhancements/pull/1546)
/kind feature
Currently the workloads feature does not take into account `cpuquota` for cpu limits. CPU limits just get ignored for the time as it currently stands, this feature adds support for cpu limits by exposing cpu quota configuration.
```release-note
Extend `workloads` config option to support CPU limits for containers that use the workloads annotations. This …
```
=> Add support for setting CPU limits for workloads

internal/oci/runtime_oci.go
conmon uses blocking writes on attach socket, if we do not read at all, conmon will be stuck.
/kind bug
On an attach request with both stdout and stderr disabled, when there are output, since we never read from conmon attach socket in this case, conmon will be stuck at writing, and as a result, stdio of the container will be frozen.
It can be reproduced with a container that runs `cat` and an attach request with large enough data (above 1MB seems to be enough) for stdin, and disabled stdout, stderr.
None
```release-note
None
```
=> oci: AttachContainer: always read attach socket

contrib/test/ci/vars.yml, internal/oci/container.go, internal/oci/container_test.go, internal/oci/runtime_oci.go, internal/oci/runtime_oci_test.go, test/ctr.bats
=> [release-1.26] OCPBUGS-30656: Add exponential backoff to the container stop loop

contrib/test/ci/vars.yml, internal/oci/container.go, internal/oci/container_test.go, internal/oci/runtime_oci.go, internal/oci/runtime_oci_test.go, test/ctr.bats
=> [release-1.25] OCPBUGS-31253: Add exponential backoff to the container stop loop

test/seccomp_notifier.bats
/kind bug
/kind ci
In some cases the notifier does not have time to stop the workload, in that cases 
exit code is `0`.
This PR increase a bit the timers and sleep interval.
Fixes #7932
None
```release-note
None
```
=> Deflake seccomp notifier bats tests

docs/crio.conf.5.md, pkg/config/config.go, server/container_restore.go
/kind feature
With the graduation of "Forensic Container Checkpointing" from Alpha to Beta the Kubernetes checkpoint feature defaults to on.
One of the arguments when introducing checkpoint/restore in CRI-O to default to off was to have the same behaviour as Kubernetes.
With this commit the behaviour of CRI-O is adapted to Kubernetes to default checkpoint/restore to on with the option to disable it explicitly.
CRI-O will also disable the feature if the CRIU binary is not found during initial CRI-O startup.
None
```release-note
CRI-O's checkpoint/restore support defaults to on mirroring the changes in Kubernetes.
```
=> Change CRIU support from default off to default on

completions/fish/crio.fish, docs/crio.8.md, docs/crio.conf.5.md, internal/config/nri/nri.go, test/helpers.bash, test/nri.bats
/kind other
Flip NRI on in the default configuration.
None
As discussed in the last community meeting, this PR flips NRI on in the default configuration.
For maintaining command line backward compatibility this PR leaves the original `--enable-nri` command line option intact, only changing its default to `true` from `false` (as opposed to flipping it to `--disable-nri=[false]`). Hence, NRI can now be disabled on the command line using the `--enable-nri=false` option.
```release-note
Flip NRI on by default.
To revert to a configuration with NRI disabled, either either pass the `--enable-nri=false` option to crio
on the command line, or set the `enable_nri = false` in the `[crio.nri]` section of the configuration.
```
=> config, docs, completions: enable NRI by default.

test/image.bats
/kind flake
I've seen occasional failures of the `run container in pod with local timezone` test in `images.bats`. Looking at he test case I think the reason for the failures is in the assumption that running `date` twice with second-level accuracy would always result in the same timestamp. This is not necessarily true when the initial invocation happens close enough to the 'edge' of a second. This PR removes that assumption by passing an explicit timestamp for formatting to both invocations of `date`.
None
```release-note
None
```
=> test: fix potential flake in timezone tests.

pkg/config/config.go
/kind bug
Now that checkpoint/restore is turned on by default, CRI-O no longer starts up if the CRIU binary is missing. This changes the error if the CRIU binary is not found to an information message. Checkpoint/Restore support is turned of but CRI-O still starts.
None
I would have preferred a way to detect if the option has been explicitly set by the user, but that seems hard to detect (if possible at all). If the user explicitly requests `--enable-criu-support=true` then it would make sense to fail if the CRIU binary is not found. If the user is just using the default setting then it  should not be fatal if the CRIU binary is missing.
In Kubernetes I have seen something like this in combination with `*int` and if the value is `!=nil` something was selected by the user and if it is …
=> Do not abort startup if CRIU binary not found

go.mod, go.sum, vendor/github.com/containers/image/v5/docker/docker_client.go, vendor/modules.txt
/kind bug
Manually cherry-pick changes from https://github.com/containers/image/pull/2363 as these changes contain a fix that needs to be backported to CRI-O release 1.29, part of OpenShift 4.16 release.
Related:
None
None
```release-note
None
```
=> [release-1.29] OCPBUGS-29439: Cherry-pick changes from containers/image/pull#2363

go.mod, go.sum, vendor/github.com/containers/image/v5/docker/docker_client.go, vendor/modules.txt
/kind bug
Manually cherry-pick changes from https://github.com/containers/image/pull/2363 as these changes contain a fix that needs to be backported to CRI-O.
Related:
None
None
```release-note
None
```
=> Cherry-pick changes from containers/image/pull#2363

go.mod, go.sum, vendor/github.com/containers/image/v5/docker/docker_client.go, vendor/modules.txt
/kind bug
Manually cherry-pick changes from https://github.com/containers/image/pull/2363 as these changes contain a fix that needs to be backported to CRI-O release 1.28, part of OpenShift 4.15 release.
Related:
None
None
```release-note
None
```
=> [release-1.28] OCPBUGS-31925: Cherry-pick changes from containers/image/pull#2363

completions/fish/crio.fish, docs/crio.8.md, docs/crio.conf.5.md, internal/config/cgmgr/cgmgr_linux.go, internal/config/cgmgr/cgmgr_test.go, internal/config/cgmgr/cgmgr_unsupported.go, internal/config/cgmgr/cgroupfs_linux.go, internal/config/cgmgr/systemd_linux.go, internal/criocli/criocli.go, internal/oci/oci.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/template.go, server/container_create_linux.go, server/nri-api.go, server/sandbox_run_linux.go, test/image.bats
/kind feature
Provide a way to configure container minimum memory limit per OCI runtime.
Fixes #7694
None
```release-note
Add configurable container minimum memory limit that can be set per OCI runtime.
```
=> Add configurable container minimum memory limit

pkg/config/config.go
/kind feature
We now print a full runtime version execution on startup for each found runtime. If the runtime does not support `--version`, then we just emit a warning.
Refers to https://github.com/cri-o/cri-o/pull/7998#issuecomment-2056410698
None
```release-note
Print runtime version info on CRI-O startup.
```
=> Print runtime version info on CRI-O startup

contrib/test/ci/vars.yml, internal/oci/container.go, internal/oci/oci.go, pkg/config/config.go, pkg/config/config_freebsd.go, pkg/config/config_linux.go, pkg/config/config_test.go, pkg/config/config_unsupported.go, pkg/config/config_windows.go, server/container_create_linux.go, server/container_create_linux_test.go, server/container_restore.go, server/container_status.go, server/runtime_status.go, test/ctr.bats, test/helpers.bash, test/selinux.bats
/kind feature
Currently, the read-only option set for the host mounts does not correctly propagate recursively from the top level of the given mount point. As such, any sub-mounts that happen to be part of the tree would retain their current options, and should it be a read/write type mount, then it could be modified without any restriction. This is often both unexpected and undesirable.
Thus, add support for so-called Recursive Read-only (RRO) mounts. This allows a mount point to propagate the read-only option through the tree, marking the entire mount point read-only.
Support for the RRO mounts has already been available in the runtimes, such as **crun** and **runc**, for some time now.
> [!NOTE] 
> Support of the Recursive Read-only (RRO) mounts requires:
>
> - For Linux, kernel …
=> OCPNODE-2213: Add support for Recursive Read-only (RRO) mounts

completions/fish/crio.fish, docs/crio.8.md, docs/crio.conf.5.md, internal/config/cgmgr/cgmgr_linux.go, internal/config/cgmgr/cgmgr_test.go, internal/config/cgmgr/cgmgr_unsupported.go, internal/config/cgmgr/cgroupfs_linux.go, internal/config/cgmgr/systemd_linux.go, internal/criocli/criocli.go, internal/oci/oci.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/template.go, server/container_create_linux.go, server/nri-api.go, server/sandbox_run_linux.go, test/image.bats
This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/7832
```release-note
None
```
=> [release-1.29] OCPNODE-2247: Implement configurable container minimum memory limit per OCI runtime.

.github/workflows/patch-release.yml, dependencies.yaml
/kind ci
We run the workflow always from `main`, means the release branch restriction will not allow to execute it.
Other than that, the golang version is now checked from `dependencies.yaml`.
Refers to https://github.com/cri-o/cri-o/issues/4003
PTAL @cri-o/cri-o-maintainers 
cc @olad5 
```release-note
None
```
=> Fix patch release workflow restriction

test/ctr.bats
/kind ci
Following the release of both Kubernetes 1.30 and crictl 1.30, we no longer skip the Recursive Read-only (RRO) mounts tests. However, on some platforms (such as Arm64), the support for the new feature is not present—not because of the hardware platform in itself, but because of the runtime environment, where the kernel version can be too old to provide the necessary support per:
```console
```
Thus, we should skip RRO mounts-related tests when the kernel does not include the required support.
None
None
```release-note
None
```
=> Add missing kernel version check to the RRO mounts integration tests

go.mod, go.sum, vendor/github.com/containers/image/v5/docker/docker_client.go, vendor/modules.txt
/kind bug
Manually cherry-pick changes from https://github.com/containers/image/pull/2363 as these changes contain a fix that needs to be backported to CRI-O release 1.27, part of OpenShift 4.14 release.
Related:
None
None
```release-note
None
```
=> [release-1.27] OCPBUGS-31926: Cherry-pick changes from containers/image/pull#2363

scripts/patch-release/patch-release.go
/kind ci
The label will not be considered when opening the PR, means we stick to the release notes block for now.
None
None
```release-note
None
```
=> Use release-note block instead of label

internal/version/version.go
Automated version bump to version `1.29.3`
/release-note-none
=> Bump version to 1.29.3

internal/config/conmonmgr/conmonmgr.go
/kind cleanup
Both errors have the same message so it's hard to distinguish them. We now fix that by slightly changing the message to be more concrete.
None
None
```release-note
Change conmon version parse error to be distinguishable from the binary execution error.
```
=> Distinguish conmon version parse from execution error

contrib/test/ci/vars.yml, internal/criocli/criocli.go, test/image.bats
/kind bug
When you provide `--runtime` option (or `CONTAINER_RUNTIMES` variable) with no `container_min_memory`, it doesn't respect the default container_min_memory (12MiB) and it will be 0B. 
```
sudo crio --log-level=debug --runtimes=runc:/usr/local/sbin/runc:
...
INFO[2024-04-22 12:17:08.039694857Z] Using runtime handler runc version 1.1.12, commit: v1.1.12-0-g51d5e946, spec: 1.0.2-dev, go: go1.20.13, libseccomp: 2.5.4  file="config/config.go:1291"
DEBU[2024-04-22 12:17:08.039769758Z] Runtime handler "runc" container minimum memory set to 0 bytes  file="config/config.go:1300"
...
```
It should be 12 MiB.
None
```release-note
None
```
=> Stop using BytesSize when merging the config

internal/oci/container.go, internal/oci/oci_unix.go, internal/oci/runtime_oci.go, test/ctr.bats
=> oci: keep track of exec PIDs and stop them on container stop

contrib/test/ci/integration.yml, contrib/test/ci/vars.yml, internal/storage/image.go, pkg/config/reload.go, server/server.go, test/mocks/criostorage/criostorage.go, test/reload_config.bats
/kind bug
/kind feature
Updates pinned images list on config reload
Fixes #7954 
None
```release-note
Updates pinned images list on config reload
```
/cc @haircommander @sohankunkerkar @hexfusion @kwilczynski
=> Reload config update pinned_images

nix/default-s390x.nix, nix/derivation.nix
/kind bug
Building using musl until https://github.com/NixOS/nixpkgs/issues/306473 is resolved.
Refers to https://github.com/cri-o/cri-o/issues/7911
None
```release-note
Using musl libc for s390x until the static glibc issue is resolved.
```
=> Build s390x binaries using musl libc

contrib/test/ci/integration.yml, contrib/test/ci/vars.yml, internal/storage/image.go, pkg/config/reload.go, server/server.go, test/mocks/criostorage/criostorage.go, test/reload_config.bats
This is a manual [cherry-pick of https://github.com/cri-o/cri-o/pull/7937](https://github.com/cri-o/cri-o/pull/7976)
```release-note
Updates pinned images list on config reload
```
=> [release-1.29] Reload config update pinned_images

.golangci.yml, contrib/test/ci/vars.yml, dependencies.yaml, docs/crio.conf.5.md, pkg/annotations/annotations.go, pkg/config/config.go, pkg/config/template.go, scripts/github-actions-setup, scripts/versions, server/container_create_linux.go, test/pod.bats
With [this](https://github.com/opencontainers/runc/pull/4246) change, we can disable FIPS mode in containers for a cluster that is FIPS-enabled.
/kind feature
This isn't fully tested; I'm relying on our CI, which can build `runc` with Go 1.21
```release-note
Allow containers within a Kubernetes cluster to opt out of FIPS mode when required
```
=> server: allow containers within a cluster to opt out of FIPS mode

internal/version/version.go, pkg/annotations/annotations.go, test/workloads.bats
```release-note
Fix CVE-2024-3154 , a security flaw where CRI-O allowed users to specify annotations that changed specific fields in the runtime. One consequence is a user can change the systemd properties of the container, allowing unsafe properties to be set by the runtime
```
=> version: bump to 1.28.6

internal/version/version.go, pkg/annotations/annotations.go, test/workloads.bats
/kind bug
```release-note
Fix CVE-2024-3154 , a security flaw where CRI-O allowed users to specify annotations that changed specific fields in the runtime. One consequence is a user can change the systemd properties of the container, allowing unsafe properties to be set by the runtime
```
=> version: bump to 1.27.6

pkg/annotations/annotations.go, test/workloads.bats
```release-note
Fix CVE-2024-3154, a security flaw where CRI-O allowed users to specify annotations that changed specific fields in the runtime. One consequence is a user can change the systemd properties of the container, allowing unsafe properties to be set by the runtime
```
=> fix typo and lints of CVE-2024-3154 fix

internal/runtimehandlerhooks/high_performance_hooks_linux.go
/kind bug
When shared cpus are configured for the container, the child state object that represents that cpuset under the container's child cgroup is already exists under the managers slice.
This means, we should override last element instead of append a new one, because the child state is already there.
None
```release-note
None
```
=> OCPBUGS-28586: higeperfhooks: mixedcpus: set only exclusive cpus in child cgroup

.github/workflows/patch-release.yml, .github/workflows/release-branch-forward.yml, .github/workflows/test.yml
/kind ci
We should use GitHub action native tokens and not personal ones from an ancient time.
/cherry-pick release-1.29
/cherry-pick release-1.28
/cherry-pick release-1.27
None
```release-note
None
```
=> Remove `GH_TOKEN` usage from repo

.github/workflows/patch-release.yml, .github/workflows/release-branch-forward.yml, .github/workflows/test.yml
/kind ci
We need to set the env variable because it will not get exposed automatically.
Follow-up on https://github.com/cri-o/cri-o/pull/8107
None
```release-note
None
```
=> Re-add `GITHUB_TOKEN` for GitHub actions jobs

.github/workflows/cron.yml, .github/workflows/test.yml
/kind cleanup
We should use GitHub action native tokens and not personal ones from an ancient time.
None
Manual cherry-pick of 4b4e66c63aef2fad1e07117856cd6510e8fdbeca
Refers to https://github.com/cri-o/cri-o/pull/8107
```release-note
None
```
=> [release-1.29] Remove `GH_TOKEN` usage from repo

internal/config/apparmor/apparmor_linux.go, internal/config/apparmor/apparmor_test.go, test/apparmor.bats
/kind bug
When applying a given AppArmor profile, the `Apply()` function should correctly handle the "Unconfined" profile type for both fields, the `Apparmor` (which is a `SecurityProfile` type) and `ApparmorProfile` (a bare string), of the `LinuxContainerSecurityContext` type.
Fixes #8080.
None
None
```release-note
Fix AppArmour profile Apply() function to correctly handle an "Unconfined" mode.
```
=> Fix AppArmor profile Apply() function to correctly handle an "Unconfined" mode

internal/oci/container.go
/kind cleanup
The following Pull Request introduced the concept of internally tracking the PID of the process created using the exec (whether synchronous or not) calls. This is very useful and immediately stops CRI-O from losing track of the processes created as part of the exec invocation.
However, aside from a debug log line added for each exec request, nothing else can be used to track a particular exec invocation and termination.
Thus, add a debug log line to expose details of an exec PID being newly started and to be killed, which can aid with troubleshooting.
Related:
- https://github.com/cri-o/cri-o/pull/7937
None
None
```release-note
None
```
=> Add debug log to expose details of an exec PID lifecycle

.github/workflows/test.yml
/kind cleanup
We should use GitHub action native tokens and not personal ones from an ancient time.
None
Manual cherry-pick of 4b4e66c63aef2fad1e07117856cd6510e8fdbeca
Refers to https://github.com/cri-o/cri-o/pull/8107
```release-note
None
```
=> [release-1.28] Remove `GH_TOKEN` usage from repo

.github/workflows/test.yml
/kind cleanup
We should use GitHub action native tokens and not personal ones from an ancient time.
None
Manual cherry-pick of 4b4e66c63aef2fad1e07117856cd6510e8fdbeca
Refers to https://github.com/cri-o/cri-o/pull/8107
```release-note
None
```
=> [release-1.27] Remove `GH_TOKEN` usage from repo

internal/oci/container.go, server/container_status.go
/kind bug
Using the implementation of https://github.com/kubernetes/kubernetes/pull/123508 to fix https://github.com/cri-o/cri-o/issues/7143
Also incorporating https://github.com/kubernetes/kubernetes/pull/123583 now.
Fixes #7143
taking over https://github.com/cri-o/cri-o/pull/7815
```release-note
Fixed kubelet image garbage collection when images being referenced as digests instead of IDs. 
```
=> Fix kubelet image GC by using new `image_id` CRI field

Makefile, hack/libsubid_tag.sh
/kind bug
This PR addresses the following issues that occurred while building CRI-O locally.
```sh
$ make binaries
go: golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64: verifying module: invalid GOSUMDB: malformed verifier id
go: golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64: verifying module: invalid GOSUMDB: malformed verifier id
/bin/sh: line 1: [: too many arguments
go: golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64: verifying module: invalid GOSUMDB: malformed verifier id
go build  -trimpath  -ldflags '-s -w -X github.com/cri-o/cri-o/internal/version.buildDate='2024-05-03T19:42:28Z' ' -tags "containers_image_ostree_stub      containers_image_openpgp seccomp selinux " -o bin/crio github.com/cri-o/cri-o/cmd/crio
go: golang.org/toolchain@v0.0.1-go1.22.2.linux-amd64: verifying …
```
=> Drop GOSUMDB/GOPROXY and fix unary operator error while building crio

go.mod, go.sum, vendor/github.com/containers/image/v5/docker/docker_client.go, vendor/modules.txt
/kind bug
Manually cherry-pick changes from https://github.com/containers/image/pull/2363 as these changes contain a fix that needs to be backported to CRI-O release 1.26, part of OpenShift 4.13 release.
Related:
None
None
```release-note
None
```
=> [release-1.26] OCPBUGS-31927: Cherry-pick changes from containers/image/pull#2363

go.mod, go.sum, vendor/github.com/containers/image/v5/docker/docker_client.go, vendor/modules.txt
/kind bug
Manually cherry-pick changes from https://github.com/containers/image/pull/2363 as these changes contain a fix that needs to be backported to CRI-O release 1.25, part of OpenShift 4.12 release.
Related:
None
None
```release-note
None
```
=> [release-1.25] OCPBUGS-31928: Cherry-pick changes from containers/image/pull#2363

test/image.bats
/kind cleanup
/kind ci
The `go` command is not installed in the `arm64` runner. This hasn't been a problem because the test doesn't fail because of a failure in command substitutions. However, this gives us the wrong idea that we can use the `go` command generally, which is, in fact, not always available.
I found this when working on https://github.com/cri-o/cri-o/pull/8057#issuecomment-2073973560.
None
None
```release-note
None
```
=> Replace go env GOARCH with ARCH environment variable

internal/oci/container.go, internal/oci/oci_unix.go, internal/oci/runtime_oci.go, test/ctr.bats
This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/7937
Related:
- https://github.com/cri-o/cri-o/pull/8095
```release-note
```
=> [release-1.28] OCPBUGS-32481: oci: keep track of exec PIDs and stop them on container stop

nix/default-s390x.nix, nix/derivation.nix
/kind ci
Manual cherry-pick of 2edec2888ee27af5b225a1a2b739fbdef968985d
Fixes the failing build in https://github.com/cri-o/packaging/actions/runs/8962233518
Refers to https://github.com/cri-o/cri-o/pull/8070
```release-note
Build s390x statically linked binaries using musl libc.
```
=> [release-1.29] Build s390x binaries using musl libc

nix/default-s390x.nix, nix/derivation.nix
/kind ci
Manual cherry-pick of 2edec2888ee27af5b225a1a2b739fbdef968985d
Fixes the failing build in https://github.com/cri-o/packaging/actions/runs/8962233278
Refers to https://github.com/cri-o/cri-o/pull/8070
```release-note
Build s390x statically linked binaries using musl libc.
```
=> [release-1.28] Build s390x binaries using musl libc

.github/workflows/test.yml, Makefile
The upload hangs for a while and also fails with:
```
{'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected available in 10 seconds.', code='throttled')}{'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected available in 10 seconds.', code='throttled')}{'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected available in 10 seconds.', code='throttled')}{'detail': ErrorDetail(string='Rate limit reached. Please upload with the Codecov repository upload token to resolve issue. Expected available in 10 seconds.', code='throttled')}{'detail': …
```
=> Use `codecov/codecov-action` to fix coverage report

internal/oci/container.go, internal/oci/oci_unix.go, internal/oci/runtime_oci.go, test/ctr.bats
This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/7937
Related:
- https://github.com/cri-o/cri-o/pull/8095
```release-note
```
=> [release-1.27] OCPBUGS-32482: oci: keep track of exec PIDs and stop them on container stop

.github/workflows/tag-reconciler.yml, dependencies.yaml
By this, we also:
- Add the go version check to `dependencies.yaml`
- Fix the name of the tag reconciler job
Fixing the GitHub action run: https://github.com/cri-o/cri-o/actions/runs/8981671336
cc @olad5 
```release-note
None
```
=> Fix tag-reconciler job by using `GITHUB_TOKEN`

contrib/test/ci/integration.yml, contrib/test/ci/vars.yml, server/server.go, test/reload_config.bats
Fixes https://github.com/cri-o/cri-o/issues/8074
/kind ci
/kind flake
This PR makes some "reload config" tests to wait for the completion of reload.
Currently, those tests in `reload_config.bats` don't wait for `PinnedImagesList` updated.
- reload config should update 'pinned_images'
- reload config should update 'pinned_images' and only 'pause_image' is pinned
- reload config should update 'pause_image' and it becomes 'pinned_images'
It causes a race condition and test failures.
Specifically, The test sends SIGHUP and runs `crictl images`.
It expects the results to be updated with the reloaded new config.
However when `crictl images` runs before `PinnedImagesList` is updated, the `regexForPinnedImages` are not updated, and the image which should be pinned won't be regarded as pinned. …
=> Wait for configuration reload completion to stabilize e2e tests

contrib/test/ci/vars.yml, internal/config/nsmgr/nsmgr_linux.go, pinns/src/pinns.c, test/pod.bats
/kind bug
```release-note
fix a bug where pinns wasn't setting the sysctls at the correct time when it was also pinning a user namespace 
```
=> [release-1.29] pinns: write sysctls in correct process when userns

server/container_restore.go
/kind bug
The Protocol Buffers specification does not mandate that the Linux Resources for a container definition be present or that any of its attributes be required—most values are left to be the default, often unset, values. This means that the container definition stored as JSON document also does not require nor mandate that the "linux" attribute (with any of its sub-attributes) has to be present, etc. As such, once the JSON document is parsed, any missing sections will be set to `nil` within the `ContainerConfig` type, and attempting to access such object attributes to dereference them will result in a panic.
Thus, add `nil` check to ensure that the `Linux` field of the `ContainerConfig` type has been set before accessing any fields from within it, which would prevent a potential …
=> Check for nil values when importing container definition

internal/oci/container.go, internal/oci/oci_unix.go, internal/oci/runtime_oci.go, test/ctr.bats
This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/7937
Related:
- https://github.com/cri-o/cri-o/pull/8095
```release-note
```
=> [release-1.25] OCPBUGS-33175: oci: keep track of exec PIDs and stop them on container stop

internal/oci/container.go, internal/oci/oci_unix.go, internal/oci/runtime_oci.go, test/ctr.bats
This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/7937
Related:
- https://github.com/cri-o/cri-o/pull/8095
```release-note
```
=> [release-1.26] OCPBUGS-33174: oci: keep track of exec PIDs and stop them on container stop

server/container_restore.go
This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/8150
```release-note
Check for nil values when importing container definition for a given container checkpoint to be restored.
```
=> [release-1.29] Check for nil values when importing container definition

server/sandbox_run_linux.go, test/network_ping.bats
/kind bug
ping_group_range sysctl requires the upper bound be within the range of IDs the user has access to. ping_group_range is often set to the max allowable range "0 2147483647", but this will break for every usernamespace pod.
Instead, hack around it by updating the max GID to be the largest one we find in the IDMappings
```release-note
fix a bug where a pod with a userns would fail to be created when `ping_group_range` sysctl was specified for it (and the max of that range was outside of the pods user namespace)
```
=> server: support ping_group_range if in a userns

internal/oci/runtime_oci.go
/kind bug
/kind regression
Before applying this patch we killed the exec PIDs right away on container stop which leads into the failing e2e test:
```
[sig-node] [NodeFeature:SidecarContainers] Containers Lifecycle should terminate sidecars simultaneously if prestop doesn't exit
```
This regression is now fixed by killing the exec PIDs after the main container as well as in the same thread.
Needs a cherry-pick since the enhancement got already backported into supported release branches.
Fixes https://github.com/kubernetes/kubernetes/issues/124743
Follow-up on https://github.com/cri-o/cri-o/pull/7937
```release-note
Fixed pod lifecycle regression where the exec PID's got killed before the actual container.
```
=> Kill exec PIDs after main container exited

.golangci.yml
/kind ci
The linter allows additional checks while the `argument-limit` (known as problematic in some cases) is disabled for now.
None
None
```release-note
None
```
=> Enable `revive` linter

server/sandbox_run_linux.go
/kind cleanup
```release-note
none
```
=> server: use max function instead of manually calculating max

server/server.go
/kind bug
Currently when the watcher in "exit monitor" gets an error, whole "exit monitor" stops and it is never restarted again.
In other words, if the watcher gets an error, cri-o continues to work but it can no longer watch exits.
Watcher errors (= errors in `fsnotify`) are supposed to be something recoverable, and therefore `fsnotify` doesn't stop if it gets an error (see the usage of `sendError` in the codes below).
https://github.com/fsnotify/fsnotify/blob/main/backend_inotify.go#L410-L573
https://github.com/fsnotify/fsnotify/blob/main/backend_windows.go#L483-L647
This PR keeps the monitor from stopping when the watcher gets error, and makes it keep monitoring.
It also fixes `close of closed channel` when cri-o shuts down. (#8031)
Fixes #8031 
Even if this PR is merged, there is …
=> Keep the monitor exits from stopping when the watcher gets error

tutorial.md, tutorials/crio-in-kind.md
Small tutorial: How to run CRI-O as container runtime in kind.
None
None
```release-note
None
```
=> Add tutorial showing how to run CRI-O in kind

Makefile, contrib/kube-local/kube-local.profile, hack/govulncheck.sh, hack/libdm_installed.sh, hack/libdm_no_deferred_remove_tag.sh, install.md, scripts/github-actions-packages, test/helpers.bash
Device mapper storage driver is hard to set up, slow, and obsoleted by overlayfs.
My best guess is nobody is using it nowadays.
Let's remove it.
Fixes: #7002
* replaces #7003.
* related to https://github.com/containers/storage/pull/1622 and https://github.com/containers/storage/issues/1619.
* includes some Makefile cleanups (the first two commits).
```release-note
Remove device mapper storage driver.
```
=> Remove devicemapper storage driver

.golangci.yml, server/container_create_linux.go
=> [release-1.29] OCPBUGS-33812: server: use SecureJoin when setting container /etc directory

.golangci.yml, server/container_create_linux.go
=> [release-1.28] OCPBUGS-33811: server: use SecureJoin when setting container /etc directory

.golangci.yml, server/container_create_linux.go
=> [release-1.27] OCPBUGS-33810: server: use SecureJoin when setting container /etc directory

go.mod, go.sum, vendor/github.com/containers/image/v5/copy/progress_bars.go, vendor/github.com/containers/image/v5/copy/single.go, vendor/github.com/containers/image/v5/directory/directory_dest.go, vendor/github.com/containers/image/v5/directory/directory_src.go, vendor/github.com/containers/image/v5/directory/directory_transport.go, vendor/github.com/containers/image/v5/docker/docker_client.go, vendor/github.com/containers/image/v5/docker/docker_image.go, vendor/github.com/containers/image/v5/docker/docker_image_dest.go, vendor/github.com/containers/image/v5/docker/docker_image_src.go, vendor/github.com/containers/image/v5/docker/internal/tarfile/dest.go, vendor/github.com/containers/image/v5/docker/internal/tarfile/writer.go, vendor/github.com/containers/image/v5/docker/registries_d.go, vendor/github.com/containers/image/v5/openshift/openshift_src.go, vendor/github.com/containers/image/v5/ostree/ostree_dest.go, vendor/github.com/containers/image/v5/ostree/ostree_src.go, vendor/github.com/containers/image/v5/storage/storage_dest.go, vendor/github.com/containers/image/v5/storage/storage_image.go, vendor/github.com/containers/image/v5/storage/storage_reference.go, vendor/github.com/containers/image/v5/storage/storage_src.go, vendor/modules.txt
/kind bug
Related:
None
None
```release-note
None
```
=> [release-1.30] Cherry-pick changes from containers/image/pull#2418

scripts/release-notes/release_notes.go
/kind ci
Updating the [release notes GitHub pages](https://cri-o.github.io/cri-o) can lead into merge conflicts if multiple jobs run on a single branch in parallel (for example for merge commits and tags). We do not consider this as fatal error any more, because we need the release notes output for the next CI steps.
Failure ref: https://github.com/cri-o/cri-o/actions/runs/9350292608/job/25733441349#step:5:271
None
None
```release-note
None
```
=> Don't fail CI on GitHub pages push

contrib/test/ci/system-packages.yml
/kind ci
This also adds a bunch of other netfilter related dependencies which may solve https://github.com/cri-o/cri-o/issues/8270
None
None
```release-note
None
```
=> Add `conntrack-tools` to CI system packages

.packit.yaml
The `$(git rev-parse HEAD)` isn't expanded properly otherwise.
<!--  Thanks for sending a pull request!
/kind other
.packit.yaml: Fix `%global commit0 <sha>` generation
None
```release-note
None
```
/cc @haircommander
=> .packit.yaml: Fix `%global commit0 <sha>` generation

.golangci.yml, server/container_create_linux.go
=> [release-1.26] OCPBUGS-33809: server: use SecureJoin when setting container /etc directory

.golangci.yml, server/container_create_linux.go
=> [release-1.25] OCPBUGS-33808: server: use SecureJoin when setting container /etc directory

go.mod, go.sum, vendor/github.com/containers/image/v5/copy/progress_bars.go, vendor/github.com/containers/image/v5/copy/single.go, vendor/github.com/containers/image/v5/directory/directory_dest.go, vendor/github.com/containers/image/v5/directory/directory_src.go, vendor/github.com/containers/image/v5/directory/directory_transport.go, vendor/github.com/containers/image/v5/docker/docker_client.go, vendor/github.com/containers/image/v5/docker/docker_image.go, vendor/github.com/containers/image/v5/docker/docker_image_dest.go, vendor/github.com/containers/image/v5/docker/docker_image_src.go, vendor/github.com/containers/image/v5/docker/internal/tarfile/dest.go, vendor/github.com/containers/image/v5/docker/internal/tarfile/writer.go, vendor/github.com/containers/image/v5/docker/registries_d.go, vendor/github.com/containers/image/v5/openshift/openshift_src.go, vendor/github.com/containers/image/v5/ostree/ostree_dest.go, vendor/github.com/containers/image/v5/ostree/ostree_src.go, vendor/github.com/containers/image/v5/pkg/blobcache/blobcache.go, vendor/github.com/containers/image/v5/pkg/blobcache/dest.go, vendor/github.com/containers/image/v5/pkg/blobcache/src.go, vendor/github.com/containers/image/v5/storage/storage_dest.go, vendor/github.com/containers/image/v5/storage/storage_image.go, vendor/github.com/containers/image/v5/storage/storage_reference.go, vendor/github.com/containers/image/v5/storage/storage_src.go, vendor/modules.txt
/kind bug
Related:
None
None
```release-note
None
```
=> [release-1.29] Cherry-pick changes from containers/image/pull#2418

go.mod, go.sum, vendor/github.com/containers/image/v5/copy/progress_bars.go, vendor/github.com/containers/image/v5/copy/single.go, vendor/github.com/containers/image/v5/directory/directory_dest.go, vendor/github.com/containers/image/v5/directory/directory_src.go, vendor/github.com/containers/image/v5/directory/directory_transport.go, vendor/github.com/containers/image/v5/docker/docker_client.go, vendor/github.com/containers/image/v5/docker/docker_image.go, vendor/github.com/containers/image/v5/docker/docker_image_dest.go, vendor/github.com/containers/image/v5/docker/docker_image_src.go, vendor/github.com/containers/image/v5/docker/internal/tarfile/dest.go, vendor/github.com/containers/image/v5/docker/internal/tarfile/writer.go, vendor/github.com/containers/image/v5/docker/registries_d.go, vendor/github.com/containers/image/v5/openshift/openshift_src.go, vendor/github.com/containers/image/v5/ostree/ostree_dest.go, vendor/github.com/containers/image/v5/ostree/ostree_src.go, vendor/github.com/containers/image/v5/pkg/blobcache/blobcache.go, vendor/github.com/containers/image/v5/pkg/blobcache/dest.go, vendor/github.com/containers/image/v5/pkg/blobcache/src.go, vendor/github.com/containers/image/v5/storage/storage_dest.go, vendor/github.com/containers/image/v5/storage/storage_image.go, vendor/github.com/containers/image/v5/storage/storage_reference.go, vendor/github.com/containers/image/v5/storage/storage_src.go, vendor/modules.txt
/kind bug
Related:
None
None
```release-note
None
```
=> [release-1.28] Cherry-pick changes from containers/image/pull#2418

internal/runtimehandlerhooks/high_performance_hooks_linux.go, server/container_start.go
/kind design
The kubelet isn't going to try again to start a container, instead opting to recreate it.
Thus, this container will get leaked (until the pod cgroup is deleted)
This has impacts in disabling cpu load balancing on v2, as the container cgroup sticking around
means the target cpus are in use, breaking the kernel's exclusivity rule
Also note: we do clean up a failed container creation
```release-note
Remove a container after it fails to start, to prevent copies of it from piling up until it succeeds.
```
=> server: clean up container after it failed to start

server/container_stats_list.go, test/stats.bats
/kind bug
We need to filter the labels for each container to be able to support the corresponding cri-tools feature.
Fixes: https://github.com/kubernetes-sigs/cri-tools/issues/950
None
```release-note
Fixed container stats label filtering.
```
=> Fix container stats label filter

.github/workflows/test.yml, internal/config/seccomp/seccomp_test.go, internal/factory/container/namespaces_test.go, internal/oci/container_test.go, internal/oci/runtime_oci_test.go, pkg/config/config_test.go, pkg/config/reload_test.go, server/container_restore_test.go, server/sandbox_run_test.go, server/suite_test.go
/kind ci
- Make tests which require root optional
- Fix the reload tests if runc is not in `/usr/bin/runc`
- Make the network dir test more independent from previous runs
- Set the NRI socket path and seccomp notifier path to something rootless writeable
- Add a rootless unit test run to CI to verify that it works in the future
None
None
```release-note
None
```
=> Make unit tests work rootless

internal/storage/image_test.go, server/image_pull.go
/kind feature
This allows to set a pull timeout (currently not used neither by the kubelet nor cri-tools) using the CRI context. Future consumers can then limit the pul not only if no network traffic is available (introduced in \#7887), but also in a more general way.
None
None
```release-note
Respect image pull timeout set by RPC context to potentially abort an ongoing image pull.
```
=> Respect image pull timeout set by RPC context

go.mod, go.sum, vendor/github.com/containers/image/v5/copy/progress_bars.go, vendor/github.com/containers/image/v5/copy/single.go, vendor/github.com/containers/image/v5/directory/directory_dest.go, vendor/github.com/containers/image/v5/directory/directory_src.go, vendor/github.com/containers/image/v5/directory/directory_transport.go, vendor/github.com/containers/image/v5/docker/docker_client.go, vendor/github.com/containers/image/v5/docker/docker_image.go, vendor/github.com/containers/image/v5/docker/docker_image_dest.go, vendor/github.com/containers/image/v5/docker/docker_image_src.go, vendor/github.com/containers/image/v5/docker/internal/tarfile/dest.go, vendor/github.com/containers/image/v5/docker/internal/tarfile/writer.go, vendor/github.com/containers/image/v5/docker/registries_d.go, vendor/github.com/containers/image/v5/openshift/openshift_src.go, vendor/github.com/containers/image/v5/ostree/ostree_dest.go, vendor/github.com/containers/image/v5/ostree/ostree_src.go, vendor/github.com/containers/image/v5/pkg/blobcache/blobcache.go, vendor/github.com/containers/image/v5/pkg/blobcache/dest.go, vendor/github.com/containers/image/v5/pkg/blobcache/src.go, vendor/github.com/containers/image/v5/storage/storage_dest.go, vendor/github.com/containers/image/v5/storage/storage_image.go, vendor/github.com/containers/image/v5/storage/storage_reference.go, vendor/github.com/containers/image/v5/storage/storage_src.go, vendor/modules.txt
/kind bug
Related:
None
None
```release-note
None
```
=> [release-1.27] Cherry-pick changes from containers/image/pull#2418

go.mod, go.sum, vendor/github.com/containers/image/v5/copy/progress_bars.go, vendor/github.com/containers/image/v5/copy/single.go, vendor/github.com/containers/image/v5/directory/directory_dest.go, vendor/github.com/containers/image/v5/directory/directory_src.go, vendor/github.com/containers/image/v5/directory/directory_transport.go, vendor/github.com/containers/image/v5/docker/docker_client.go, vendor/github.com/containers/image/v5/docker/docker_image.go, vendor/github.com/containers/image/v5/docker/docker_image_dest.go, vendor/github.com/containers/image/v5/docker/docker_image_src.go, vendor/github.com/containers/image/v5/docker/internal/tarfile/dest.go, vendor/github.com/containers/image/v5/docker/internal/tarfile/writer.go, vendor/github.com/containers/image/v5/docker/registries_d.go, vendor/github.com/containers/image/v5/openshift/openshift_src.go, vendor/github.com/containers/image/v5/ostree/ostree_dest.go, vendor/github.com/containers/image/v5/ostree/ostree_src.go, vendor/github.com/containers/image/v5/pkg/blobcache/blobcache.go, vendor/github.com/containers/image/v5/pkg/blobcache/dest.go, vendor/github.com/containers/image/v5/pkg/blobcache/src.go, vendor/github.com/containers/image/v5/storage/storage_dest.go, vendor/github.com/containers/image/v5/storage/storage_image.go, vendor/github.com/containers/image/v5/storage/storage_reference.go, vendor/github.com/containers/image/v5/storage/storage_src.go, vendor/modules.txt
/kind bug
Related:
None
None
```release-note
None
```
=> [release-1.26] Cherry-pick changes from containers/image/pull#2418

go.mod, go.sum, vendor/github.com/containers/image/v5/copy/progress_bars.go, vendor/github.com/containers/image/v5/copy/single.go, vendor/github.com/containers/image/v5/directory/directory_dest.go, vendor/github.com/containers/image/v5/directory/directory_src.go, vendor/github.com/containers/image/v5/directory/directory_transport.go, vendor/github.com/containers/image/v5/docker/docker_client.go, vendor/github.com/containers/image/v5/docker/docker_image.go, vendor/github.com/containers/image/v5/docker/docker_image_dest.go, vendor/github.com/containers/image/v5/docker/docker_image_src.go, vendor/github.com/containers/image/v5/docker/internal/tarfile/dest.go, vendor/github.com/containers/image/v5/docker/internal/tarfile/writer.go, vendor/github.com/containers/image/v5/docker/registries_d.go, vendor/github.com/containers/image/v5/openshift/openshift_src.go, vendor/github.com/containers/image/v5/ostree/ostree_dest.go, vendor/github.com/containers/image/v5/ostree/ostree_src.go, vendor/github.com/containers/image/v5/pkg/blobcache/blobcache.go, vendor/github.com/containers/image/v5/pkg/blobcache/dest.go, vendor/github.com/containers/image/v5/pkg/blobcache/src.go, vendor/github.com/containers/image/v5/storage/storage_dest.go, vendor/github.com/containers/image/v5/storage/storage_image.go, vendor/github.com/containers/image/v5/storage/storage_reference.go, vendor/github.com/containers/image/v5/storage/storage_src.go, vendor/modules.txt
/kind bug
Related:
None
None
```release-note
None
```
=> [release-1.25] Cherry-pick changes from containers/image/pull#2418

Makefile, dependencies.yaml, scripts/release-notes/release_notes.go
/kind ci
Skip the first commit to avoid issues like https://github.com/cri-o/cri-o/issues/8249
None
Manual cherry-pick of https://github.com/cri-o/cri-o/pull/8273
```release-note
None
```
=> [release-1.28] release-notes: Skip first commit

Makefile, dependencies.yaml, scripts/release-notes/release_notes.go
/kind ci
Skip the first commit to avoid issues like https://github.com/cri-o/cri-o/issues/8249
None
Manual cherry-pick of https://github.com/cri-o/cri-o/pull/8273
```release-note
None
```
=> [release-1.27] release-notes: Skip first commit

server/container_create.go, test/pod.bats, utils/utils.go, utils/utils_test.go
When securityContext of runAsGroup is added the
gid has to be added in /etc/group. Test case for
the same is also being added
/kind bug
This PR has changes to add gid [value of RunAsGroup in SecurityContext] under /etc/group
Fixes #8216
```release-note
```
=> server/*: Fix a bug where the GID is not added to /etc/group when run_as_group is set

internal/version/version.go
We can release one more v1.27 in the beginning of July (like Kubernetes does), but after that is should marked as end of life.
None
/hold
Should merge after the July patches.
```release-note
None
```
=> Mark v1.27 as EOL

test/ctr.bats
Updated jq command to correctly set the supplemental groups policy in sandbox_config.json
/kind ci
Fixes this issue:
```sh
level=fatal msg="load podSandboxConfig: json: cannot unmarshal string into Go struct field LinuxSandboxSecurityContext.linux.security_context.supplemental_groups_policy of type v1.SupplementalGroupsPolicy"
```
```release-note
None
```
=> test: ensure correct parsing of supplemental groups policy in JSON

cmd/crio/main.go, completions/bash/crio, completions/fish/crio.fish, completions/zsh/_crio, docs/crio.8.md
We now sort the commands by name in the same way we do it for the flags.
None
None
```release-note
Sorted `crio` subcommands by name.
```
=> Sort `crio` subcommands by name

cmd/crio/main.go
Before:
```
VERSION:
1.30.2
Version:        1.30.2
GitCommit:      unknown
GitCommitDate:  unknown
GitTreeState:   clean
BuildDate:      1980-01-01T00:00:00Z
GoVersion:      go1.22.3
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:
apparmor
seccomp
selinux
containers_image_openpgp
containers_image_ostree_stub
LDFlags:          unknown
SeccompEnabled:   true
AppArmorEnabled:  false
DESCRIPTION:
OCI-based implementation of Kubernetes Container Runtime Interface
```
After:
```
VERSION:
Version:        1.31.0
GitCommit:      f68b12ced5b49799aaa42097540def6a67dc6643
GitCommitDate:  2024-07-02T10:59:18Z
GitTreeState:   clean
BuildDate:      1980-01-01T00:00:00Z
GoVersion:      go1.22.3
Compiler:       gc
Platform:       linux/amd64
Linkmode: …
```
=> Fix version output in help

test/common.sh
/kind ci
The binary value defaults to `command -v crictl` which cannot be overridden. We now fallback to that and let users set their own `CRICTL_BINARY` path.
None
None
```release-note
None
```
=> Allow setting `CRICTL_BINARY` externally

.github/dependabot.yml
/kind ci
As a result we should get one PR for Kubernetes dependency bumps instead of multiple ones.
None
None
```release-note
None
```
=> Add `kubernetes` group in dependabot

internal/nri/domain.go, internal/nri/nri.go, server/nri-api.go
/kind cleanup
We now pass around the context to understand where the "Failed to get pid" message is coming from. We also don't have to log the message in case that the container is spoofed, otherwise the message may be misleading.
None
None
```release-note
Reduced "Failed to get pid for pod infra container" NRI message for spoofed containers and lowering the verbosity to `DEBUG`. 
```
=> nri: pass around context and log failed pid for not spoofed containers

server/image_status.go
/kind cleanup
```bash
$ sudo crictl inspecti registry.k8s.io/pause:3.9 | jq .status.pinned
true
```
None
None
```release-note
None
```
=> server: propagate the pinned status of an image when queried via crictl 

.github/workflows/verify.yml
/kind ci
We do not need go for binary related checks, so we remove that step.
None
None
```release-note
None
```
=> Remove go-setup from jobs not using golang

server/useragent/useragent.go
/kind bug
The version CRI-O uses to set the **User-Agent** header when making requests against a remote container registry can be overridden during the build process, and it might contain more information than just a simple semver compatible version string in the "X.Y.Z" format. For example, the OpenShift-specific build of CRI-O includes release and build information as part of the version string, such as the following:
```console
1.27.8-2.rhaos4.14.gitbfac241.el9
```
This extra information, while useful as part of binary package metadata or when requesting a version using command-line switches such as `--version`, would not necessarily be useful when included in the User-Agent header. Usually, there isn't any need for the User-Agent header to include a very detailed version, release and …
=> Sanitize CRI-O version set in the User-Agent header

.golangci.yml, internal/hostport/fake_iptables_test.go, internal/hostport/hostport_manager_test.go, internal/hostport/meta_hostport_manager_test.go, internal/hostport/noop_hostport_manager_test.go, test/nri/nri_suite_test.go, test/nri/nri_test.go
/kind cleanup
We should stick to use ginkgo as main testing framework for this project rather than testify. We also apply testifylint to the nri tests, which are still using this dependency.
None
None
```release-note
None
```
=> Move hostport tests to use ginkgo

nix/derivation.nix
/kind cleanup
The Makefile already sets this flag, so there is no need to do it manually again.
None
None
```release-note
None
```
=> Remove duplicate `exclude_graphdriver_devicemapper` from static builds

contrib/test/ci/build/kata.yml, contrib/test/ci/vars.yml, test/helpers.bash, test/kata.bats
/kind ci
Update the version of kata to test with - using the latest 3.6.0 version. 
Also make kata test specific changes (affecting only the fedora-kata job).
Details:
- move to kata 3.6.0
- enable hooks tests, as the fix for it was released with 3.5.0
- make sure the storage.overlay.skip_mount_home flag is set to true (problem introduced with kata 3.3.0)
- enable debug logs for kata
- cleanup lingering kata processes on teardown
- add an integration test specific to kata, testing we're actually using the kata runtime. Useful to validate config/script changes in the CI
None
```release-note
None
```
=> test: use kata 3.6.0 for testing

internal/oci/container.go, internal/oci/container_test.go, internal/oci/runtime_oci.go, internal/oci/runtime_oci_test.go, internal/oci/runtime_vm.go, server/container_stop.go, test/ctr.bats
/kind bug
This commit removes the `ShouldBeStopped` function to address the issue where stopping container blocks all further stop attempts for the same container. That function acquired the `opLock` mutex to check the container's state, which could lead to contention and potential deadlocks if other goroutines were waiting to acquire the same lock.
Additionally, the container's state is checked later in the `StopContainer` function by calling the `Living` method, which checks if the container's process is still running. Therefore, the `ShouldBeStopped` function is redundant and can be removed.
Fixes https://github.com/cri-o/cri-o/issues/8030.
None
```release-note
```
=> OCPNODE-2408: internal/oci: remove redundant ShouldBeStopped check for stopping containers

test/network_ping.bats
/kind ci
Disabling the tests on arm runners for now.
Refers to https://github.com/cri-o/cri-o/issues/8388
None
```release-note
None
```
=> Disable network ping tests for actuated runners

internal/oci/container.go, internal/oci/container_test.go, internal/oci/runtime_oci.go, internal/oci/runtime_oci_test.go, internal/oci/runtime_vm.go, server/container_stop.go, test/ctr.bats
=> [release-1.30] internal/oci: remove redundant ShouldBeStopped check for stopping containers 

internal/oci/container.go, server/container_create_linux.go, server/container_status.go, test/oci_volumes.bats
/kind feature
We need to return the image ID for the localhost mount, otherwise the kubelet garbage collection is not able to handle them.
Refers to https://github.com/kubernetes/enhancements/issues/4639
Follow-up on https://github.com/cri-o/cri-o/pull/8317
None
```release-note
None
```
=> Make ImageVolume garbage collection work

internal/oci/container.go, internal/oci/container_test.go, internal/oci/runtime_oci.go, internal/oci/runtime_oci_test.go, internal/oci/runtime_vm.go, server/container_stop.go, test/ctr.bats
=> [release 1.29] internal/oci: remove redundant ShouldBeStopped check for stopping containers 

cmd/crio/main.go
/kind cleanup
Having subcommands like `crio status` or `crio config` to log the version seems a bit odd, so we now silence this behavior and log the version only on the main `crio` command.
None
None
```release-note
Log version only for main CRI-O command, not on others like `crio config` or `crio status`.
```
=> Log version only for main CRI-O command

contrib/test/ci/integration.yml, contrib/test/ci/vars.yml, test/config.bats
/kind ci
Config tests are meant to verify the configuration code, by exercising it in specific configurations.
When run in an environment where the default runtime is modified, these tests fail because the configuration they use do not have this runtime defined.
As the runtime itself is not involved in these tests, it seems safe to unset the CONTAINER_DEFAULT_RUNTIME variable in their context.
None
```release-note
None
```
=> test: config tests should ignore default runtime environment variable

internal/oci/container.go, internal/oci/container_test.go, internal/oci/runtime_oci.go, internal/oci/runtime_oci_test.go, internal/oci/runtime_vm.go, server/container_stop.go, test/ctr.bats
=> [release 1.28] internal/oci: remove redundant ShouldBeStopped check for stopping containers 

internal/oci/container.go, internal/oci/container_test.go, internal/oci/runtime_oci.go, internal/oci/runtime_oci_test.go, internal/oci/runtime_vm.go, server/container_stop.go, test/ctr.bats
=> [release 1.27] internal/oci: remove redundant ShouldBeStopped check for stopping containers

.github/workflows/verify.yml, .golangci.yml
/kind ci
Fix the linter timeout option. Also enable the `promlinter` which does not report anything.
None
None
```release-note
None
```
=> Fix lint timeout option

cmd/crio/main.go, internal/criocli/version.go
/kind cleanup
We duplicated the `version` name for the output of `crio -v`, which is now fixed for all variants:
- `crio -v`
- `crio -h` (Section "VERSION")
- `crio version`
None
None
```release-note
None
```
=> Trim `crio version Version: …` prefix from `crio -v`

server/container_remove.go, server/container_remove_test.go, server/container_stop.go, server/container_stop_test.go, server/image_remove.go, server/image_remove_test.go, test/restore.bats
/kind cleanup
Fully conform to the CRI as well as the new tests from https://github.com/kubernetes-sigs/cri-tools/pull/1536
None
None
```release-note
Made `StopContainer`, `RemoveContainer` and `RemoveImage` idempotent per CRI API definition:
https://github.com/kubernetes/cri-api/blob/c20fa40/pkg/apis/runtime/v1/api.proto
```
=> Make container and image removal/stop idempotent

contrib/test/ci/cri-o.spec, hack/build-rpms.sh
/kind ci
This PR fixes release-1.29-* CI failure.
I opened the PR https://github.com/openshift/release/pull/54846 to update the build-root image to the rhel9-based one.
The build script also has to be modified accordingly.
Since I use the image from the same repository with different version as the main one, I cherry-picked the commit in the main.
cf. pj-rehearse failure in https://github.com/openshift/release/pull/54846:
https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/openshift_release/54846/rehearse-54846-pull-ci-cri-o-cri-o-release-1.29-images/1816633789661581312
This PR and https://github.com/openshift/release/pull/54846 will fix /#8414
```release-note
None
```
=> hack/build-rpms.sh: Update for new builder image

cmd/crio/main.go, internal/criocli/criocli.go, pkg/config/config.go, pkg/config/config_test.go, pkg/config/reload.go, pkg/config/reload_test.go, server/server.go, test/reload_config.bats
/kind cleanup
We now log how the initial CRI-O configuration gets assembled, like:
```
INFO[…] Updating config from single file: /etc/crio/crio.conf
INFO[…] Updating config from drop-in file: /etc/crio/crio.conf
INFO[…] Skipping not-existing config file "/etc/crio/crio.conf"
INFO[…] Updating config from path: /etc/crio/crio.conf.d
INFO[…] Updating config from drop-in file: /etc/crio/crio.conf.d/00-default.conf
INFO[…] Updating config from drop-in file: /etc/crio/crio.conf.d/10-runtimes.conf
```
None
None
```release-note
Log exactly how configuration gets loaded into memory on `SIGHUP` and CRI-O start.
```
=> Log how configuration gets loaded

cmd/crio/main.go, completions/bash/crio, completions/fish/crio.fish, completions/zsh/_crio, contrib/test/ci/integration.yml, contrib/test/ci/vars.yml, docs/crio.8.md, internal/criocli/check.go, internal/criocli/wipe.go, internal/lib/container_server.go, test/crio-check.bats, test/crio-wipe.bats, test/helpers.bash, utils/utils.go, utils/utils_test.go
This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/8417
> [!NOTE]  
> This cherry-pick does not include the following commit:
>
> - a79fa8ba4: Make internal repair the new default and disable internal wipe
>
> The internal repair feature will remain disabled and opt-in in CRI-O v1.30 or older.
/kind feature
```release-note
Update the type of checks the internal repair feature performs on CRI-O's start-up following an unclean shutdown, and add a new `crio check` sub-command.
```
=> [release-1.30] Use custom storage check options for CRI-O internal wipe

cmd/crio/main.go, completions/bash/crio, completions/fish/crio.fish, completions/zsh/_crio, contrib/test/ci/integration.yml, contrib/test/ci/vars.yml, docs/crio.8.md, docs/crio.conf.5.md, internal/criocli/check.go, internal/criocli/wipe.go, internal/lib/container_server.go, pkg/config/config.go, test/crio-check.bats, test/crio-wipe.bats, test/helpers.bash, utils/utils.go, utils/utils_test.go
/kind feature
When enabled, the internal repair feature uses the `storage.CheckEverything()`  helper function to configure what the `storage.Check()` should check for when scanning the storage directory. The following options are enabled:
```go
func CheckEverything() *CheckOptions {
return &CheckOptions{
LayerDigests:   true,
LayerMountable: true,
LayerContents:  true,
LayerData:      true,
ImageData:      true,
ContainerData:  true,
}
}
```
Two of these options, `LayerDigests` and `LayerContents`, are known to be I/O and CPU intensive, and both of these options are used to perform storage integrity checks and require the contents of the images to be read, checksums generated, and the current state compared against the desired state. As such, depending on the number of images, the layers …
=> Use custom storage check options for CRI-O internal wipe

internal/version/version.go, internal/version/version_test.go
/kind bug
Fixes incorrect tab character handling in the internal/version/String
function when dealing with array values. Previously, a tab was added
after field names containing arrays, which was unnecessary as array
values should be on the next line.
Additional tab character on String method. Which was causing additional space being created after key name for slice values.
```release-note
None
```
=> Fix incorrect tab handling while converting Info to string and add unit tests

install.md
Document the process of installing CRI-O using systemd-sysexts on Flatcar Container Linux. This guide provides a straightforward and supported method for setting up CRI-O, making it easier for users to leverage this container runtime on Flatcar.
Closes #8172.
Add installation guide for CRI-O on Flatcar Container Linux, utilizing the systemd-sysexts feature. There was a gap in the existing documentation, and this aims to fill that by providing clear, step-by-step instructions.
None
```
None
```
=> Add documentation for setting up CRI-O with Flatcar

dependencies.yaml, docs/crio.8.md, docs/crio.conf.5.md, internal/storage/image_test.go, pkg/config/config_linux.go, pkg/config/config_unsupported.go, test/common.sh
Update the pause image to 3.10 per:
- https://github.com/kubernetes/kubernetes/issues/125092
Supersedes:
- https://github.com/cri-o/cri-o/pull/8215
Related to:
- https://github.com/kubernetes/kubernetes/pull/125112
None
None
```release-note
Update pause image to 3.10.
```
=> Update pause image to 3.10

.github/workflows/release-branch-forward.yml, scripts/release-branch-forward/release_branch_forward.go
/kind ci
This updates https://storage.googleapis.com/cri-o/latest-release-1.31.txt and therefore also the packages for that release branch.
Refers to https://github.com/kubernetes/kubernetes/issues/126734#issuecomment-2295914145
None
```release-note
None
```
=> Trigger `test` workflow after release branch fast forward

pkg/config/config.go
/kind other
Validations for the runtimes table sometimes depend on `runtime_type` to
determine which configuration options are valid.
For example
```
runtime_type = vim
runtime_config_path = /usr/share/defaults/kata-containers/configuration.toml
```
would cause "runtime_config_path can only be used with the 'vm' runtime type" instead of the more desirable error that "vim" is not a valid runtime type. (`ValidateRuntimeConfigPath` runs before `ValidateRuntimeType`)
Give this dependency on a valid `runtime_type` we should run this validation first.
None
```release-note
None
```
=> Run the runtime RuntimeType validation first

docs/crio.8.md, docs/crio.conf.5.md, pkg/config/config.go, tutorials/tracing.md
/kind other
It is prudent to move this endpoint to listen on 127.0.0.1 as a sensible default, which would improve the default security stance a little more, especially as there aren't any reasons for these services to listen on anything else than localhost.
We don't have to change conmon-rs because it already uses localhost.
https://github.com/containers/conmon-rs/blob/main/conmon-rs/server/src/config.rs#L119-L125
Fixes a part of #7448 
Users who are using this endpoint via not localhost(127.0.0.1) will need to set the tracingEndpoint option explicitly.
```release-note
Move the tracing endpoint listener to use 127.0.0.1 as the new default.
```
=> Change default tracing endpoint to 127.0.0.1

.github/workflows/integration.yml, contrib/test/ci/vars.yml, server/container_create_linux.go, test/oci_volumes.bats
/kind feature
This should allow using different SELinux contexts if multiple pods use a single image.
Inherited from https://github.com/cri-o/cri-o/commit/61d4a591b2f57bae57e6718d84e3f41404a2f251#diff-1e0877112035840d3e2f073c693665f8daffa241a440e54a866ad7382b510ea2R1240
Follow-up on https://github.com/cri-o/cri-o/pull/8317
Refers to:
- https://github.com/containers/storage/issues/1994
- https://github.com/kubernetes/kubernetes/issues/126956
- https://github.com/kubernetes/website/pull/47588
/hold
This needs to be well tested.
```release-note
None
```
=> Add additional bind mount to image volumes

docs/crio.8.md, pkg/config/config.go
/kind feature
to help users run podman inside of containers
```release-note
config: add /dev/net/tun to default allowed devices
```
=> config: add /dev/net/tun to default allowed devices

internal/config/seccomp/seccomp.go, test/ctr_seccomp.bats, test/testdata/clone-ns.c
/kind bug
Taking over https://github.com/cri-o/cri-o/pull/8437
> The default seccomp policy used by CRI-O did not previously block clone(2) system call (syscall) with CLONE_NEWNS and other namespace creation flags. Changes here block those flags. In addition, also disable the clone3(2) syscall as it is not currently possible to filter a struct argument (struct clone_args) with seccomp; this matches the approach containerd took.
None
None
```release-note
The default seccomp policy now blocks clone and clone3 system calls that can create a Linux namespace. This matches the default seccomp policy containerd uses.
```
=> Block clone with namespace flag in seccomp default profile

server/container_create.go, test/pod.bats, utils/utils.go, utils/utils_test.go
> [!NOTE] 
```release-note
```
=> [release-1.29] OCPBUGS-41243: server/*: Fix a bug where the GID is not added to /etc/group when run_as_group is set

.golangci.yml, internal/storage/image.go, internal/storage/image_test.go, internal/storage/runtime.go, internal/storage/runtime_test.go, server/container_create_linux.go, server/container_create_test.go, server/container_restore.go, server/container_restore_test.go, server/image_pull.go, server/image_pull_test.go, test/checkpoint.bats, test/helpers.bash, test/image.bats, test/mocks/criostorage/criostorage.go, test/nri/runtime.go, test/policy.bats, test/seccomp_oci_artifacts.bats, test/testdata/container_config.json, test/testdata/container_config_ping.json, test/testdata/container_redis.json, test/testdata/container_sleep.json, vendor/github.com/containers/image/v5/image/docker_schema2.go, vendor/github.com/containers/image/v5/image/sourced.go, vendor/github.com/containers/image/v5/image/unparsed.go, vendor/modules.txt
/kind feature
Adds support for verification using namespaced policies during container creation. 
None
```release-note
Add support for validating signatures on container creation. Now, if there is a namespaced policy in the `signature_policy_dir`, CRI-O will validate the signature defined in `signature_policy_dir`/`NS`.json for pods in namespace `NS`
```
=> Image verification for namespaced policies

server/sandbox_status.go
/kind bug
Using the right value to address issues in the evented pleg implementation.
Fixes https://github.com/cri-o/cri-o/issues/8580
```release-note
Fixed evented pleg pod sandbox status timestamp to use a time in nanosecond resolution. 
```
=> Use nanosecond timestamp for evented pleg pod status

cmd/crio/main.go
/kind cleanup
This sanitizes the logs timestamps to use a standard format rather than our own definition.
Follow-up on https://github.com/cri-o/cri-o/pull/8582#issuecomment-2340371941
None
```release-note
Switched to use `RFC3339Nano` timestamp log format (`2006-01-02T15:04:05.999999999Z07:00`)
```
=> Switch to `RFC3339Nano` log format

dependencies.yaml, nix/derivation.nix
/kind ci
Build static binaries using the latest go.
None
None
```release-note
Use go 1.23 for nix (static) builds.
```
=> Use go 1.23 for nix (static) builds

.github/workflows/test.yml, dependencies.yaml, hack/govulncheck.sh
/kind ci
Per the following document:
- Release History / [Release Policy](https://go.dev/doc/devel/release#policy)
> Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release. We fix critical problems, including [critical security problems](https://go.dev/security), in supported releases as needed by issuing minor revisions (for example, Go 1.6.1, Go 1.6.2, and so on).
There are no guarantees of backward compatibility for the `govulncheck` utility, as such, latest version might require much modern language features, either directly for itself or for one of its dependencies. An example of such an issue can be seen as follows: 
```console
Error: …
```
=> Pin govulncheck to specific version to match Go version requirements

.github/workflows/test.yml, dependencies.yaml, hack/govulncheck.sh
This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/8572
```release-note
None
```
=> [release-1.30] Pin govulncheck to specific version to match Go version requirements

.github/workflows/test.yml, dependencies.yaml, hack/govulncheck.sh
This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/8572
```release-note
None
```
=> [release-1.29] Pin govulncheck to specific version to match Go version requirements

internal/oci/container.go, internal/oci/container_test.go, internal/oci/runtime_oci.go, internal/oci/runtime_oci_test.go, internal/oci/runtime_vm.go, server/container_stop.go, test/ctr.bats
=> [release 1.26] internal/oci: remove redundant ShouldBeStopped check for stopping containers

.github/workflows/test.yml, dependencies.yaml, hack/govulncheck.sh, server/container_create.go, test/pod.bats, utils/utils.go, utils/utils_test.go
> [!NOTE] 
```release-note
```
=> [release-1.28] OCPBUGS-41245: server/*: Fix a bug where the GID is not added to /etc/group when run_as_group is set

internal/config/seccomp/seccomp.go, test/ctr_seccomp.bats, test/testdata/clone-ns.c
This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/8514
```release-note
The default seccomp policy now blocks clone and clone3 system calls that can create a Linux namespace. This matches the default seccomp policy containerd uses.
```
=> [release-1.30] Block clone with namespace flag in seccomp default profile

.github/workflows/test.yml, dependencies.yaml, hack/govulncheck.sh
This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/8572
```release-note
None
```
=> [release-1.28] Pin govulncheck to specific version to match Go version requirements

internal/config/seccomp/seccomp.go, test/ctr_seccomp.bats, test/testdata/clone-ns.c
This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/8514
```release-note
The default seccomp policy now blocks clone and clone3 system calls that can create a Linux namespace. This matches the default seccomp policy containerd uses.
```
=> [release-1.29] Block clone with namespace flag in seccomp default profile

contrib/test/ci/integration.yml, contrib/test/ci/vars.yml, test/helpers.bash, test/reload_config.bats
Modify the "wait_for_log" function in helpers.bash to allow it to catch multiple occurrences of the same message.
Use that in the failing test to synchronize and wait for config reload to be finished before checking the content of the configuration.
Fixes #8324
```release-note
None
```
=> ci: fix reload config for empty pinned image test

server/container_create.go, test/pod.bats, utils/utils.go, utils/utils_test.go
> [!NOTE] 
```release-note
```
=> [release-1.27] OCPBUGS-41246: server/*: Fix a bug where the GID is not added to /etc/group when run_as_group is set

pkg/config/config.go
/kind bug
It is necessary to use composefs from CRI-O.
None
Maintain the pull options as-is as they are read from the `storage.conf` file, so we don't lose options like `convert_images` that are necessary to convert existing images to a format usable with composefs.
> [!NOTE]  
> Do not expose this configuration via the CRI-O drop-in configuration, as the `PullOptions` API is still experimental in `containers/storage` package.
```release-note
None
```
=> config: pass down PullOptions from the storage configuration

server/container_create.go, test/pod.bats, utils/utils.go, utils/utils_test.go
> [!NOTE] 
```release-note
```
=> [release-1.26] OCPBUGS-41247: server/*: Fix a bug where the GID is not added to /etc/group when run_as_group is set

server/container_create.go, test/pod.bats, utils/utils.go, utils/utils_test.go
> [!NOTE] 
```release-note
```
=> [release-1.25] OCPBUGS-41248: server/*: Fix a bug where the GID is not added to /etc/group when run_as_group is set

go.mod, go.sum, vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go, vendor/github.com/go-task/slim-sprig/v3/.gitattributes, vendor/modules.txt
/kind bug
Manually cherry-pick changes from https://github.com/containers/common/pull/2185 as these changes contain a fix that needs to be backported to CRI-O release 1.31, part of OpenShift 4.18 release.
Related:
None
None
```release-note
None
```
=> [release-1.31] OCPBUGS-42661: Cherry-pick changes from containers/common/pull#2185

contrib/test/ci/e2e-base.yml
/kind ci
/kind cleanup
Initially, the `baseos` and `appstream` repositories were not enabled for RHEL CI images, and the periodic job never failed for that:: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-cri-o-cri-o-main-periodics-setup-periodic/1843078810862358528/artifacts/setup-periodic/cri-o-setup-test/build-log.txt
That's been fixed, and here’s the latest run:
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/openshift_release/54530/rehearse-54530-periodic-ci-cri-o-cri-o-main-periodics-setup-periodic/1843501944937648128/artifacts/setup-periodic/cri-o-setup-test/build-log.txt
```release-note
None
```
=> contrib/test: avoid running setup tasks twice

go.mod, go.sum, vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go, vendor/modules.txt
/kind bug
Manually cherry-pick changes from https://github.com/containers/common/pull/2185 as these changes contain a fix that needs to be backported to CRI-O release 1.27, part of OpenShift 4.14 release.
Related:
None
None
```release-note
None
```
=> [release-1.27] OCPBUGS-42652: Cherry-pick changes from containers/common/pull#2185

go.mod, go.sum, vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go, vendor/modules.txt
/kind bug
Manually cherry-pick changes from https://github.com/containers/common/pull/2185 as these changes contain a fix that needs to be backported to CRI-O release 1.25, part of OpenShift 4.12 release.
Related:
None
None
```release-note
None
```
=> [release-1.25] OCPBUGS-42654: Cherry-pick changes from containers/common/pull#2185

go.mod, go.sum, vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go, vendor/modules.txt
/kind bug
Manually cherry-pick changes from https://github.com/containers/common/pull/2185 as these changes contain a fix that needs to be backported to CRI-O release 1.26, part of OpenShift 4.13 release.
Related:
None
None
```release-note
None
```
=> [release-1.26] OCPBUGS-42653: Cherry-pick changes from containers/common/pull#2185

go.mod, go.sum, vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go, vendor/modules.txt
/kind bug
Manually cherry-pick changes from https://github.com/containers/common/pull/2185 as these changes contain a fix that needs to be backported to CRI-O release 1.28, part of OpenShift 4.15 release.
Related:
None
None
```release-note
None
```
=> [release-1.28] OCPBUGS-42651: Cherry-pick changes from containers/common/pull#2185

test/restore.bats
/kind ci
crictl displays the exit code, which can also be matched now.
None
None
```release-note
None
```
=> Re-enable exit code matching in restore test

internal/oci/container.go, server/container_create.go, server/sandbox_run_freebsd.go, server/sandbox_run_linux.go, server/utils.go
/kind cleanup
Move the label usage into the `oci` package from where it can be re-used all over the place.
None
None
```release-note
None
```
=> Refactor sandbox label usage

server/container_remove.go, server/sandbox_run_freebsd.go, server/sandbox_run_linux.go, server/sandbox_stop_freebsd.go, server/sandbox_stop_linux.go, server/utils.go, test/common.sh, test/ctr.bats, test/helpers.bash, test/pod.bats
/kind feature
We can use the deadline from the CRI context for stopping containers. This allows a more dynamic behavior compared to the static 10s before. Tools like `crictl` can be used to remove containers given a strict timeout this way.
None
None
```release-note
Use the context timeout / deadline for stopping containers if provided.
```
=> Use context timeout/deadline for container stop

internal/config/seccomp/notifier.go, internal/config/seccomp/seccomp.go, internal/config/seccomp/seccomp_unsupported.go
/kind other
I think #3300 regressed #218 by unconditionally compiling with seccomp enabled. #6488 fixed this for non-linux and non-cgo build platforms, but the issue still exists when one uses a cgo-enabled Linux build host but still wants to build without seccomp. In such case build ends quickly with pkg-config error: `Package 'libseccomp' not found`.
This patch makes `internal/config/seccomp` respect the seccomp buildtag.
Fixes #218 regression
```release-note
Fixed building CRI-O without libseccomp.
```
None?
=> Re-allow building without seccomp installed

internal/factory/container/container.go, internal/factory/container/container_test.go, internal/factory/container/namespaces.go, internal/factory/container/sandbox.go, internal/lib/constants/constants.go, internal/lib/container_server.go, internal/lib/namespace/namespace.go, internal/lib/sandbox/namespaces.go, server/sandbox_run_freebsd.go, server/sandbox_run_linux.go
/kind cleanup
Instead of passing whole sandbox object we will pass parameters that are needed This will remove interdependencies for future refactor. Also ManagedNamespace extracted to its own package inside lib so that it can be referenced for both sandbox and container.
Part of #8289 
No
```release-note
Restructuring of packages.
```
=> Refactoring factory/container to remove references of lib/sandbox

go.mod, go.sum, vendor/github.com/containers/storage/userns.go, vendor/github.com/containers/storage/userns_unsupported.go, vendor/modules.txt
/kind bug
Manually cherry-pick changes from https://github.com/containers/storage/pull#2134 as these changes contain a fix that needs to be backported to CRI-O release 1.31, part of OpenShift 4.18 release.
Related:
- https://github.com/containers/storage/pull/2134
None
None
```release-note
None
```
=> [release-1.31] OCPBUGS-42908: Cherry-pick changes from containers/storage/pull#2134

README.md, completions/fish/crio.fish, docs/crio.8.md, internal/client/client.go, internal/criocli/status.go, server/inspect.go, test/status.bats, utils/utils.go
/kind feature
The subcommand can be used to query the CRI-O goroutines in the same way as writing them to disk using `SIGUSR1`. This also allows to query the goroutines using the HTTP endpoint:
```shell
sudo curl --unix-socket /var/run/crio/crio.sock http://crio/debug/goroutines
```
None
None
```release-note
Added crio status `goroutines` subcommand and `/debug/goroutines` HTTP endpoint.
```
=> crio status: add `goroutines` subcommand

internal/hostport/hostport.go, internal/hostport/hostport_manager.go, internal/hostport/hostport_manager_test.go, internal/hostport/hostport_test.go, internal/hostport/noop_hostport_manager.go, internal/hostport/noop_hostport_manager_test.go, server/sandbox_network.go
/kind cleanup
(Split out from work on #8684)
PodPortMapping had a HostNetwork field, but it was always false, because the HostportManager is only called from code that already knows it's working on a pod-network pod. (Likewise, it is always called with a non-nil podPortMapping.)
HostportManager.Add() had a natInterfaceName argument, inherited from the original upstream code, but it was always "" here, because cri-o doesn't know the architecture of the CNI plugin being used.
The unit tests had an "expectError" field, which was previously used to catch errors when the IPv4 manager was called with IPv6 IPs or vice versa, but that's not possible given the current architecture so it was always false. (The dual-stack test would fail if there was actually a problem with the IPv4-vs-IPv6 code.) …
=> Remove dead code in HostportManager

.typos.toml, cmd/crio/main.go
While it's actually not a typo, the var `sserver` does not really indicate what it's meant to be. We rename it to become a more verbose `streamingServer` to fixup both issues.
None
None
```release-note
None
```
=> Fix `typos` in CI

pkg/config/config.go, pkg/config/config_test.go, server/server.go
/kind cleanup
We now pre-check if the configuration fields are set correctly and add more verbose output to the server start. Unit tests have been added around this use case as well.
None
None
```release-note
Validate stream server TLS config on startup if TLS should be used.
```
=> Validate stream server TLS config on startup

internal/hostport/fake_iptables.go, internal/hostport/hostport_manager_test.go
/kind cleanup
Another spinoff of #8684. This fixes up the hostport unit tests in preparation for adding nftables. (In particular, in my first attempt at #8684, the linter complained about the fact that I had just copied the test cases from the iptables unit tests to the nftables unit tests, so this splits them out so we can share them directly.)
#8684 currently has my complete branch if you want to see how the nftables stuff builds on top of this, but I thought it would be easier to review if I split this part out separately...
None
```release-note
None
```
=> Improve hostport unit tests

docs/crio.conf.5.md, pkg/config/config.go, pkg/config/config_test.go, pkg/config/reload.go, pkg/config/reload_test.go, pkg/config/template.go
/kind feature
This allows custom RuntimeHandlers to always inherit the default configured runtime paths. This helps with adding extra annotations or other "minor" changes while following what rest of the system does.
Fixes #8753
This is a minimal proof of concept so I could test whether the configuration flow would make sense. I actually do not know if it covers all code paths.
```release-note
A runtime handler definition in the configuration file can use a new option `use_default_runtime`. Setting it to true causes the values for runtime path, runtime type and runtime root to be inherited from the currently configured default runtime.
```
=> RuntimeHandler inheritance

pkg/config/config.go, pkg/config/config_test.go, pkg/config/reload.go
/kind bug
The original inheritance PR missed few important bits
- the reload code path was not the only one that loads configs
- an empty RuntimePath has a special meaning and inheriting it does not inherit the parent runtime
- golang does a copy during interation, not a reference and the updated values were forgotten
- the unit test ignores some of the checks during CI when not on a bare metal
This patch fixes all of these and adds better logging and also tests that actually catch the above mistakes.
Fixes https://github.com/cri-o/cri-o/issues/8753
I apologize for missing the issue during the first submission, but it all looked like working. It was just an accident though..
This fix was manually tested including the negative cases both by running unit tests with the code commented out …
=> RuntimeHandler inheritance bug-fix

go.mod, server/container_update_resources.go
/kind cleanup
Rely on the official protobuf package instead of the deprecated gogo extension.
None
None
```release-note
None
```
=> Use google.golang.org/protobuf instead of gogo

server/container_restore.go, server/container_restore_test.go, test/checkpoint.bats
This is a manual cherry-pick of commit 429ef7c36
```mail
commit 429ef7c366406280cfa3daa15812d14b22953a7a
Author: Adrian Reber <areber@redhat.com>
Date:   Mon Sep 30 23:37:13 2024
Only restore container if all bind mounts are defined
To avoid the situation where a container that is restored via a registry
mounts unexpected host paths into the container, this changes the
restore behaviour of CRI-O.
Previously all bind mounted paths in the original container which were
defined for example like this:
volumeMounts:
- mountPath: /data
name: data-volume
volumes:
- name: data-volume
hostPath:
path: /srv/container/data
Were automatically mounted in the restored container without and
definition necessary. This lead to the situation that the user does not
know which path will be mounted if starting …
```
=> [release-1.31] Only restore container if all bind mounts are defined

server/container_restore.go, server/container_restore_test.go, test/checkpoint.bats
This is a manual cherry-pick of commit 429ef7c36
```mail
commit 429ef7c366406280cfa3daa15812d14b22953a7a
Author: Adrian Reber <areber@redhat.com>
Date:   Mon Sep 30 23:37:13 2024
Only restore container if all bind mounts are defined
To avoid the situation where a container that is restored via a registry
mounts unexpected host paths into the container, this changes the
restore behaviour of CRI-O.
Previously all bind mounted paths in the original container which were
defined for example like this:
volumeMounts:
- mountPath: /data
name: data-volume
volumes:
- name: data-volume
hostPath:
path: /srv/container/data
Were automatically mounted in the restored container without and
definition necessary. This lead to the situation that the user does not
know which path will be mounted if starting …
```
=> [release-1.30] Only restore container if all bind mounts are defined

server/container_restore.go, server/container_restore_test.go, test/checkpoint.bats
This is a manual cherry-pick of commit 429ef7c36
```mail
commit 429ef7c366406280cfa3daa15812d14b22953a7a
Author: Adrian Reber <areber@redhat.com>
Date:   Mon Sep 30 23:37:13 2024
Only restore container if all bind mounts are defined
To avoid the situation where a container that is restored via a registry
mounts unexpected host paths into the container, this changes the
restore behaviour of CRI-O.
Previously all bind mounted paths in the original container which were
defined for example like this:
volumeMounts:
- mountPath: /data
name: data-volume
volumes:
- name: data-volume
hostPath:
path: /srv/container/data
Were automatically mounted in the restored container without and
definition necessary. This lead to the situation that the user does not
know which path will be mounted if starting …
```
=> [release-1.29] Only restore container if all bind mounts are defined

.github/workflows/integration.yml, .github/workflows/test.yml, server/container_restore_test.go
/kind ci
To fix a failing test following a merge of the changes from Pull Request #8795, where a unit test that verifies whether a given pod sandbox ID has been set was missing the required `Metadata` property when setting up `types.ContainerConfig` object for use in the test.
Related:
- https://github.com/cri-o/cri-o/pull/8795
- https://github.com/cri-o/cri-o/pull/8722
None
To be merged after:
- https://github.com/cri-o/cri-o/pull/8806
```release-note
None
```
=> [release-1.29] Fix failing test following a backport from cri-o/cri-o/pull#8795

internal/oci/runtime_oci.go
/kind bug
We do not unset the env for calling the runtime directly, but we do when calling conmon(-rs). This behavioral difference should be aligned.
None
None
```release-note
Fixed bug to always inherit `monitor_env` when calling the OCI runtime.
```
=> Use `monitor_env` for calling the OCI runtime

cmd/crio/daemon_linux.go, internal/oci/runtime_oci.go
/kind cleanup
Streamline the behavior to always unset the environment variables even when `monitor_env` is not set. This allows to call `SdNotify(false, "READY=1")` as well without breaking any OCI runtime.
Follow-up on https://github.com/cri-o/cri-o/pull/8808
None
```release-note
None
```
=> Always clear env even when `monitor_env` is unset

server/container_create_linux.go, server/sandbox_run_linux.go, server/server.go
/kind bug
While I re-allowed building cri-o for Linux without seccomp in #8686 I later found some issues with it when actually running it. So this PR fixes some issues I found when running cri-o on a Linux system where both cri-o and runtime were compiled without seccomp support.
None
None
```release-note
None
```
=> Fix issues when running on Linux with seccomp disabled

dependencies.yaml, go.mod, hack/build-rpms.sh
/kind cleanup
Using the latest golang version for building CRI-O `main`.
None
```release-note
Require go 1.23 to build CRI-O.
```
=> Require go 1.23 for build

Makefile
/kind bug
From scratch, it failed `make install` with the error `cannot stat 'docs/crio.conf.5': No such file or directory`.
It is because `MANPAGES` variable is defined later than the `install.man` target, and `crio.conf.5` and `crio.conf.d.5` are not created.
This PR moves the definition of `MANPAGES` to the top so that install.man creates `MANPAGES`.
```
$ make install
go build -trimpath  -ldflags '-s -w -X github.com/cri-o/cri-o/internal/version.buildDate='2024-12-18T17:10:25Z' ' -tags "containers_image_ostree_stub  exclude_graphdriver_btrfs btrfs_noversion containers_image_openpgp seccomp selinux  exclude_graphdriver_devicemapper" -o bin/crio ./cmd/crio
make -C pinns
make[1]: Entering directory '/home/atokubi/cri-o/pinns'
cc -std=c99 -Os -Wall -Werror -Wextra -static -O3 -o …
```
=> Refactor man page variables in Makefile.

contrib/cni/README.md
The docs in https://github.com/cri-o/cri-o/blob/main/contrib/cni/README.md indicate to switch to containernetworking/plugins v1.1.1 tag.
After this PR the docs indicate to pick the latest tag instead. This is essential because:
- Problems were fixed in 1.2.0: https://github.com/cri-o/ocicni/issues/77#issuecomment-1574048987.
- Tag v1.1.1 is old and randomally picked.
NONE
At the time of writing, this is the output of the suggested command:
```
container-networking-plugins]> echo $(git tag -l | sort -V | tail -n 1)
v1.6.1
```
```release-note
NONE
```
=> [Docs] Fetch latest containernetworking/plugins tag instead of v1.1.1

dependencies.yaml, internal/version/version.go
/kind cleanup
Bump the next CRI-O version and add zeitgeist checks to remind everyone that they have to be kept in sync.
None
None
```release-note
None
```
=> Update CRI-O version and add checks

server/container_restore.go, server/container_restore_test.go, test/checkpoint.bats
This is a manual cherry-pick of commit 429ef7c36
```mail
commit 429ef7c366406280cfa3daa15812d14b22953a7a
Author: Adrian Reber <areber@redhat.com>
Date:   Mon Sep 30 23:37:13 2024
Only restore container if all bind mounts are defined
To avoid the situation where a container that is restored via a registry
mounts unexpected host paths into the container, this changes the
restore behaviour of CRI-O.
Previously all bind mounted paths in the original container which were
defined for example like this:
volumeMounts:
- mountPath: /data
name: data-volume
volumes:
- name: data-volume
hostPath:
path: /srv/container/data
Were automatically mounted in the restored container without and
definition necessary. This lead to the situation that the user does not
know which path will be mounted if starting …
```
=> [release-1.28] OCPBUGS-45907: Only restore container if all bind mounts are defined

Makefile
/kind cleanup
/kind other
Introduce `GO_TEST` and make it similar to `GO_BUILD`.
None
Note that with this change, the default behavior changes a little bit, that is, `TRIMPATH`, `GCFLAGS` and `GO_LDFALGS` all have effect on test/nri/nri.test.
```release-note
None
```
=> Makefile: introduce GO_TEST for more flexible configuration

.packit.yaml
- Removes Fedora 39 configuration as Fedora 39 is now end-of-life.
/kind cleanup
Removes Fedora 39 configuration from .packit.yaml.
Fedora 39 is end-of-life.
None
The .packit.yaml file needs review and potential revision as Fedora 41 appears to be skipped.
It would also be worth considering eliminating .packit.yaml from the CRI-O repository and move it to the Fedora repositories for CRI-O. If moved, Packit would use the `pull-from-upstream` model rather than the current `push-to-downstream`. This places Packit configuration in the hands of the Fedora maintainers rather than the CRI-O team. Not sure if that is desirable or not but perhaps worth considering.
None
```release-note
Update Packit configuration to remove reference to Fedora 39.
```
=> Remove Fedora 39 content from .packit.yaml

internal/log/klog.go, internal/log/klog_test.go
/kind bug
This fixes the parenthesis of logs from klog.
Tested with this code.
```go
klog.InfoS("test message", "version", "test", "err", nil)
klog.InfoS("test message", "version", "test", "missing")
```
Before
```
time="2025-01-17T14:48:43Z" level=debug msg="test message (version=\"test\" err=<nil>"
time="2025-01-17T14:48:43Z" level=debug msg="test message (version=\"test\" missing=\"[MISSING]\""
```
After
```
time="2025-01-17T14:52:25Z" level=debug msg="test message (version=\"test\" err=<nil>)"
time="2025-01-17T14:52:25Z" level=debug msg="test message (version=\"test\" missing=\"[MISSING]\")"
```
None
```release-note
Fixed log format from klog.
```
=> Fix klog-shim to close the bracket properly

internal/hostport/hostport_manager.go, internal/iptables/iptables.go, server/server.go
/kind cleanup
Replaced klog with logrus to align with other logging in the codebase.
It isn't a big change for users since there's already the klog shim.
The replacement aligns with the way of the klog shim.
https://github.com/cri-o/cri-o/blob/f552e82b023c8e8034a1ecd85bbbecbaa7d61afc/internal/log/klog.go#L12-L38
The only change in behaviour is that the error logs are no longer shown from `iptables.go` just like other error logs when we run unit tests.
None
```release-note
Change log levels and formats for some iptables logs and klog related logs. 
```
=> Switch to our log module for logging in iptables module

internal/version/version.go
/kind ci
This allows to build prerelease packages for release-1.33.
Refers to https://github.com/cri-o/packaging/pull/214
None
```release-note
None
```
=> Add `release-1.33` to active prerelease version

contrib/test/ci/build/plugins.yml, dependencies.yaml, go.mod, go.sum, scripts/versions, vendor/github.com/containers/storage/layers.go, vendor/github.com/containers/storage/pkg/chunked/compression_linux.go, vendor/github.com/containers/storage/pkg/chunked/storage_linux.go, vendor/github.com/go-task/slim-sprig/v3/.gitattributes, vendor/github.com/tetratelabs/wazero/.gitattributes, vendor/modules.txt
/kind bug
Manually cherry-pick changes from [containers/storage](https://github.com/containers/storage) project.
Related:
- https://github.com/containers/storage/pull/2162
- https://github.com/containers/storage/pull/2185
> [!NOTE] 
> This cherry-pick brings the following changes as a dependency:
>
> ```mail
> commit b57566b9c3a5de2d1a0d8108666b4156b0e3e79e
> Author: Krzysztof Wilczyński <kwilczynski@redhat.com>
> Date:   Tue Jan 7 15:09:56 2025
> 
>     Update containernetworking/plugins Go package release to v1.6.2
>     
>     The upstream project pulled the release v1.6.1, which was allegedly
>     incorectly released. The new version has been released in liu of the one
>     that has been pulled.
> …
```
=> [release-1.32] OCPBUGS-48198: Cherry-pick changes from containers/storage project

internal/watchdog/watchdog.go, server/health.go, server/sandbox_network.go, server/sandbox_run_freebsd.go, server/sandbox_run_linux.go
Fixes https://issues.redhat.com/browse/OCPBUGS-48334
The idea is decouple CRI-O's readiness from the CNI plugin readiness.
/kind bug
```release-note
Decouple CNI plugin initialization from CRI-O health checks.
```
=> [OCPBUGS-48334] watchdog: Decouple CNI plugin initialization from CRI-O health checks

internal/resourcestore/resourcecleaner.go, internal/runtimehandlerhooks/high_performance_hooks_linux.go, server/sandbox_run_linux.go, utils/errdefs/grpc.go
/kind ci
Manual cherry-pick of: 99b02b97b4b46606fb53026079c772485953504e
From https://github.com/cri-o/cri-o/pull/8485
Fixes: https://github.com/cri-o/cri-o/issues/8923
```release-note
Fixed build issue with newer golang versions.
```
=> [release-1.29] Fix build errors on go >= 1.23

go.mod, go.sum, vendor/github.com/containers/storage/layers.go, vendor/github.com/containers/storage/pkg/chunked/cache_linux.go, vendor/github.com/containers/storage/pkg/chunked/compression_linux.go, vendor/github.com/containers/storage/pkg/chunked/storage_linux.go, vendor/github.com/containers/storage/storage.conf, vendor/modules.txt
/kind bug
Manually cherry-pick changes from [containers/storage](https://github.com/containers/storage) project.
Related:
- https://github.com/containers/storage/pull/2133
- https://github.com/containers/storage/pull/2156
- https://github.com/containers/storage/pull/2162
- https://github.com/containers/storage/pull/2185
None
None
```release-note
None
```
=> [release-1.31] OCPBUGS-43968: Cherry-pick changes from containers/storage project

go.mod, go.sum, vendor/github.com/containers/image/v5/storage/storage_dest.go, vendor/modules.txt
/kind bug
Manually cherry-pick changes from [containers/image](https://github.com/containers/image) project.
Related:
- https://github.com/containers/image/pull/2636
- https://github.com/containers/image/pull/2643
None
None
```release-note
None
```
=> [release-1.32] Cherry-pick changes from containers/image project

internal/oci/runtime_oci.go
/kind other
`updateContainerStatusFromExitFile` raises error when it fails to parse exit code from exit file, but it is never logged.
It might help investigation of https://github.com/kubernetes/kubernetes/issues/129760 .
None
```release-note
None
```
=> Log error when failing to update container status from exit file

go.mod, go.sum, vendor/github.com/containers/image/v5/storage/storage_dest.go, vendor/modules.txt
/kind bug
Manually cherry-pick changes from [containers/image](https://github.com/containers/image) project.
Related:
- https://github.com/containers/image/pull/2636
- https://github.com/containers/image/pull/2643
None
None
```release-note
None
```
=> [release-1.31] Cherry-pick changes from containers/image project

contrib/systemd/crio.service
Explicit configuration for `LimitNOFILE` in the reference `crio.service` systemd service file is removed.
CRI-O's rlimits are inherited by containers, so the daemon's `LimitNOFILE` affects `RLIMIT_NOFILE` within containers. It is recommended to use the default systemd `LimitNOFILE` configuration.
Administrators on platforms running versions less than systemd 240 should explicitly configure `LimitNOFILE=1024:524288` or risk falling back to the kernel default of `4096`.
Fixes: https://github.com/cri-o/cri-o/issues/7703
cc @cri-o/cri-o-maintainers 
```release-note
Explicit configuration for `LimitNOFILE` in the reference `crio.service` systemd service file is removed.
Warning: Administrators on platforms running versions less than systemd 240 should explicitly configure …
```
=> Remove `LimitNOFILE` from systemd service file

internal/linklogs/link_logs.go, test/ctr.bats
This fixes the CRI-O path traversal vulnerability in log handling functions that allows arbitrary unmounting.
/kind other
```release-note
None
```
=> CVE: Fix path traversal in CRI-O log handling

go.mod, go.sum, vendor/github.com/containers/storage/pkg/chrootarchive/archive.go, vendor/github.com/vbatts/tar-split/archive/tar/format.go, vendor/github.com/vbatts/tar-split/archive/tar/reader.go, vendor/modules.txt
/kind bug
/assign bitoku
Manually cherry-pick changes from [containers/storage](https://github.com/containers/storage) project.
Related:
- https://github.com/containers/storage/pull/2215
None
None
```release-note
None
```
=> [release-1.32] Bump containers/storage

go.mod, internal/hostport/hostport_manager.go, internal/iptables/iptables_linux.go, server/sandbox_stop_freebsd.go, server/sandbox_stop_linux.go
/kind cleanup
Using the sync/errgroup package is slightly more lean compared to the `k8s.io/apimachinery/pkg/util/errors` package. We can also avoid using the package in other places like the hostport manager and rely on golang native error joining.
None
None
```release-note
None
```
=> Switch to golang native error joining and errgroup

dependencies.yaml, internal/version/version.go
/kind cleanup
Mark 1.29 as EOL in the same way as the corresponding Kubernetes minor version.
None
None
```release-note
None
```
=> Mark v1.29 as EOL

go.mod, go.sum, vendor/github.com/containers/storage/pkg/chrootarchive/archive.go, vendor/modules.txt
/kind bug
Manually cherry-pick changes from [containers/storage](https://github.com/containers/storage) project.
Related:
- https://github.com/containers/storage/pull/2156
- https://github.com/containers/storage/pull/2162
- https://github.com/containers/storage/pull/2185
> [!NOTE] 
> This cherry-pick brings the following Pull Request as a dependency:
> - https://github.com/containers/storage/pull/1833
None
None
```release-note
None
```
=> [release-1.30] OCPBUGS-46026: Cherry-pick changes from containers/storage project

go.mod, go.sum, vendor/github.com/containers/storage/pkg/chrootarchive/archive.go, vendor/modules.txt
This reverts commit ee48ae2db78005b9422792c25d4d70ce85370cac. The required changes from container/storage are already merged in the previous commit.
/kind bug
This PR is to revert the commit that replaced the commit [https://github.com/cri-o/cri-o/pull/8828] before it which had the required changes from containers/storage project.
```release-note
None
```
=> [release-1.30] OCPBUGS-46026: Revert "Cherry-pick changes from containers/storage project"

.packit.yaml
/kind ci
It fixes a configuration error that prevents Packit `propose_downstream` from working in/for Fedora 40.
None
Note the missing `.` (or extra `\`) at the end. I can see that `v1.29.x` is already in `f40` so I used the "extended" regex. But perhaps you'd rather switch from `f40` to `f41` now?
```release-note
None
```
=> Fix typo in `version_update_mask` regex

go.mod, go.sum, vendor/github.com/containers/image/v5/storage/storage_dest.go, vendor/modules.txt
/kind bug
Manually cherry-pick changes from [containers/image](https://github.com/containers/image) project.
Related:
- https://github.com/containers/image/pull/2636
None
None
```release-note
None
```
=> [release-1.30] Cherry-pick changes from containers/image project

pkg/config/config.go, pkg/config/config_test.go
conmon_cgroup is deprecated and is replaced with RuntimeHandler monitor_cgroup and we prepopulate with default 'system.slice'
/kind bug
Fixes #6047 
None
```release-note
Fixes #6047
```
=> Fix: If cgroup manager is cgroupfs then allow conmon_cgroup to be empty

server/image_pull.go
/kind bug
Debugging the test since it seems to flake heavily.
We should never cancel the context when the pull timeout is `0`, means we now add an additional check to prevent this corner case.
Deflakes the integration tests and also fixes possible issues around a disabled pull progress timeout.
Fixes https://github.com/cri-o/cri-o/issues/8872
None
```release-note
Fixed context cancellation when image pull progress timeout is `0` (`--pull-progress-timeout=0` / `pull_progress_timeout=0`)
```
=> Fix context cancellation when image pull progress timeout is `0`

Makefile
/kind bug
When I try build-static, I got this error.
```
podman run --network=host --rm --privileged -ti -v /nix:/nix -v /home/atokubi/cri-o:/home/atokubi/cri-o -w /home/atokubi/cri-o \
nixos/nix:2.25.4 nix --print-build-logs --option cores 8 --option max-jobs 8 build --file nix/
error: experimental Nix feature 'nix-command' is disabled; add '--extra-experimental-features nix-command' to enable it
make: *** [Makefile:218: build-static] Error 1
```
This PR fixes this issue.
None
```release-note
None
```
=> Fix nix build

go.mod, go.sum, vendor/modules.txt, vendor/tags.cncf.io/container-device-interface/pkg/cdi/cache.go
Update CDI dependency to v0.8.1, pulling in a fix for a crash which could be triggered, in principle, if we're out of file descriptors while we're instantiating the CDI cache.
None
```release-note
None
```
=> [release-1.32] Bump CDI deps to v0.8.1.

Makefile
/kind other
Update the debug flag to work with dlv. The older flag was causing the below issue and not able to attach to the CRI-O process.
```
[root@toolbox ~]# dlv attach 24478
Warning: no debug info found, some functionality will be missing such as stack traces and variable evaluation.
could not attach to pid 24478: could not read debug info (decoding dwarf section info at offset 0x0: too short) and could not read go symbol table (could not find rodata struct member)
[root@toolbox ~]#
```
Reference: https://github.com/go-delve/delve/blob/master/Documentation/usage/dlv_exec.md?plain=1#L12
None
```release-note
None
```
=> Update debug flag

dependencies.yaml, go.mod, server/container_create_linux_test.go, server/inspect_test.go
/kind cleanup
Kubernetes v1.33 will require that version to be built and we have to align because of the future vendored sources.
None
None
```release-note
Require go 1.24 for build.
```
=> Require go 1.24 for build

server/container_create_linux.go
/kind cleanup
Use the slices package instead of the additional `noop` variable to ensure the image volume path.
None
None
```release-note
None
```
=> Cleanup: ensure image volume path

go.mod, go.sum, vendor/github.com/containers/image/v5/storage/storage_dest.go, vendor/modules.txt
/kind cleanup
This will fix an issue with pulling certain docker schema 1 images in CRI-O.
None
Requires https://github.com/containers/image/pull/2800
```release-note
Fixed bug when trying to pull certain docker schema 1 images in CRI-O.
```
=> OCPBUGS-53431: [release-1.31] Backport c/image `3161ab1`

server/container_create.go, server/masked_paths.go, test/ctr.bats
/kind cleanup
Adding default masked paths to non privileged containers.
Fixes https://github.com/cri-o/cri-o/issues/9068
None
```release-note
Changed runtime default masked paths for non privileged containers to:
- /proc/acpi
- /proc/asound
- /proc/interrupts
- /proc/kcore
- /proc/keys
- /proc/latency_stats
- /proc/sched_debug
- /proc/scsi
- /proc/timer_list
- /proc/timer_stats
- /sys/devices/system/cpu/cpu<ID>/thermal_throttle
- /sys/devices/virtual/powercap
- /sys/firmware
- /sys/fs/selinux
```
=> Set default masked paths

internal/ociartifact/artifact.go, internal/ociartifact/impl.go, internal/ociartifact/store.go, test/mocks/ociartifact/ociartifact.go, test/oci_artifacts.bats
/kind bug
This PR adds some functionality so that it can handle artifacts with digest and shortname.
This PR enables cri-o to:
* get artifact status with the canonical name
* get artifact status with the short name 
https://github.com/cri-o/cri-o/issues/8953#issuecomment-2748570167
```release-note
Fix artifact handling to retrieve artifact status using both the canonical name and the short name.
```
=> Fix artifact status handling

docs/crio.8.md, docs/crio.conf.5.md, pkg/config/config.go
/kind cleanup
There are use cases where a higher timeout is required because zscaler scans all transfers. To fulfill those we now use a slightly higher default value.
None
Needs to be backported down to 1.29.
```release-note
Increased `pull-progress-timeout` to default to `30s`.
```
=> OCPBUGS-54658: Increase pull-progress-timeout to `30s`

docs/crio.8.md, docs/crio.conf.5.md, pkg/config/config.go
/kind cleanup
Follow-up on https://github.com/cri-o/cri-o/pull/9108 and multiple requests to disable the timeout per default.
Cherry-picked: 44d9073dd1133856ffd0858b5d550ce7427335d6 (https://github.com/cri-o/cri-o/pull/9130)
None
None
```release-note
Disabled `pull-progress-timeout` per default. 
```
=> OCPBUGS-54662: [release-1.32] Disable pull-progress-timeout per default

internal/criocli/wipe.go, test/crio-wipe.bats
Signed-off-by: Pannaga Rao Bhoja Ramamanohara
/kind bug
```release-note
Prevent multiple crio wipes on reboot
```
=> [release-1.30]: OCPBUGS-55241: crio wipe should remove storage only once per reboot

internal/lib/stats/descriptors.go, internal/lib/stats/memory_metrics.go, internal/lib/stats/metrics.go
/kind feature
This PR adds the container_spec_memory_limit_bytes metric to the CRI-O metrics suite, which reports the memory limit for containers in bytes. This metric is valuable for monitoring and alerting on memory configuration versus usage. It allows users to easily calculate memory usage percentages and visualize resource allocation versus consumption in monitoring systems like Prometheus and Grafana.
The implementation follows the existing pattern for metrics in CRI-O. The new metric has been added to the "memory" metrics section and implemented in the generateSandboxMemoryMetrics function to collect memory limit data from cgroup stats.
None
```release-note
Added new metric `container_spec_memory_limit_bytes` to display the memory limit of containers in bytes.
```
=> Add container_spec_memory_limit_bytes metric

server/runtime_status.go, test/runtimeconfig.bats
/kind feature
#9122 
This PR brings the status endpoint implementation to parity with that of containerd. We would like the ability to retrieve the active runtime config through CRI socket invocation. 
The other option is for us to import the cri-o package to reuse the same business logic as `crio status config`. This option is undesirable as importing cri-o brings in a significant dependency overhead
```release-note
Added runtime config block to the `StatusResponse` returned by the CRI Status endpoint.
```
=> emit crio runtime config as part of CRI API's StatusResponse

internal/ociartifact/store.go
/kind bug
If the `artifactType` field is set, then we treat the image as OCI artifact. This allows to specify artifacts which still use `application/vnd.oci.image.manifest.v1+json` as manifest media type and/or `application/vnd.oci.image.config.v1+json` config media type.
Fixes https://github.com/cri-o/cri-o/issues/9152#issuecomment-2827357097
None
```release-note
None
```
=> Support `artifactType` OCI artifacts

dependencies.yaml, internal/version/version.go
/kind ci
The `Version` has to be increased after the release is done, otherwise the tag reconciler will publish the wrong tag.
None
/priority critical-urgent
```release-note
None
```
=> Decrement the `Version`

hack/build-rpms.sh
Hopefully it should fix 
```
[ERROR] hack/build-rpms.sh:15: `OS_RPM_NAME="$(rpmspec -q --qf '%{name}\n' "${OS_RPM_SPECFILE}" | head -1)"` exited with status 141. 
```
https://tldp.org/LDP/lpg/node20.html
https://stackoverflow.com/questions/19120263/why-exit-code-141-with-grep-q
https://github.com/jqlang/jq/issues/1017#issuecomment-845399005
```release-note
None
```
=> Fix build-rpm.sh exited 141

internal/hostport/hostport_iptables.go
/kind cleanup
This fixes the following warning:
> level=warning msg="[runner/nolint_filter] Found unknown linters in //nolint directives: interfacer"
None
```release-note
None
```
=> internal/hostport: fix linter warning

internal/hostport/meta_hostport_manager.go, internal/hostport/meta_hostport_manager_test.go, internal/iptables/iptables.go
The new iptables-and-nftables MetaHostPortManager code was falling victim to a classic golang gotcha. If `newHostportManagerIPTables` returned a `nil` value (of type `*hostportManagerIPTables`), then that value would get assigned to `mh.managers[utilnet.IPv4].iptables`, but that value is a `HostPortManager`, so the value would be typecast, becoming a non-`nil` `HostPortManager` value wrapping the `nil` `*hostportManagerIPTables` value, and then later, this code
https://github.com/cri-o/cri-o/blob/9d143f94054fc5c8338673f35f7c0164490363b3/internal/hostport/meta_hostport_manager.go#L143-L149
would see that it was non-`nil` and attempt to call a method on it, which would then SEGV because the underlying `*hostportManagerIPTables` was `nil`.
There are a few possible ways to fix this... this is …
=> Fix HostPort manager when one backend is unavailable

internal/lib/container_server.go, internal/lib/sandbox/sandbox.go, internal/lib/sandbox/sandbox_test.go, server/container_portforward.go, server/sandbox_list_test.go, server/sandbox_status.go, server/server.go
As we hit cases of deadlock when a sandbox is stuck stopping
/kind bug
```release-note
Fix a potential deadlock when an infra container is taking a long time to exit and the sandbox's readiness is blocked on the infra container's opLock
```
=> OCPBUGS-54938: [1.32] sandbox: use created/stopped instead of infra container for readiness

scripts/release-notes/release_notes.go
/kind cleanup
Since this commit https://github.com/cri-o/packaging/commit/433692447fd34681f341cf50323bf34eadbc09ca , the verify command is no longer valid.
This PR changes the verify command in release note.
**Note**: this change doesn't fix the command in the past release note.
```
❯ printf "cosign verify-blob cri-o.amd64.%s.tar.gz \
--certificate-identity https://github.com/cri-o/packaging/.github/workflows/obs.yml@refs/heads/main \
--certificate-oidc-issuer https://token.actions.githubusercontent.com \
--certificate-github-workflow-repository cri-o/packaging \
--certificate-github-workflow-ref refs/heads/main \
--signature cri-o.amd64.%s.tar.gz.sig \
--certificate cri-o.amd64.%s.tar.gz.cert" v1.33.1 v1.33.1 v1.33.1 | bash
Verified OK
```
```release-note
None
```
=> fix verify command

Makefile
turn on debug symbols temporarily for kubernetes CI.
```release-note
NONE
```
=> temporarily enable debug symbols

dependencies.yaml, internal/version/version.go, roadmap.md
/kind cleanup
Kubernetes v1.30 will be end of life on June 28, which also means that we follow in CRI-O.
None
None
```release-note
None
```
=> Mark v1.30 as EOL

test/ctr.bats
/kind ci
It's a long story (see [1], [2], [3], [4]) but both runc and crun is changing the formula to convert cgroup v1 CPU shares to cgroup v2 CPU weight, and it causes a failure in "ctr update resources" test, because it relies on the old conversion formula.
Let's modify it so it works either the old or the new conversion.
(Ultimately, with cgroup v2 we should switch to setting unified.cpu.weight directly).
[1]: https://github.com/kubernetes/kubernetes/issues/131216
[2]: https://github.com/opencontainers/runc/issues/4772
[3]: https://github.com/opencontainers/cgroups/pull/20
[4]: https://github.com/containers/crun/pull/1767
None
```release-note
NONE
```
=> test/ctr.bats: fix wrt new CPU units to weight conversion

internal/oci/container.go, internal/oci/runtime_oci.go
/kind bug
Because `c.stopTimeoutChan` is consumed only until it starts to SIGKILL, it could be deadlock in this scenario.
1. StopContainer(1)
1. `SetAsStopping`
1. `StopLoopForContainer`
1. `killContainer`
1. StopContainer(2)
1. SetAsStopping => false
1. WaitOnStopTimeout
`c.stopLock.Lock()`
`c.stopTimeoutChan <- timeout` (`len(c.stopTimeoutChan) == 1`)
`c.stopLock.ULock()`
1. StopContainer(n = 3~11)
1. SetAsStopping => false
1. WaitOnStopTimeout
`c.stopLock.Lock()`
`c.stopTimeoutChan <- timeout` (`len(c.stopTimeoutChan) == n`)
`c.stopLock.ULock()`
1. StopContainer(12~)
1. SetAsStopping => false
1. WaitOnStopTimeout
`c.stopLock.Lock()`
`c.stopTimeoutChan <- timeout` (BLOCKED!!)
1. After the process was killed (back to 1)
1. `StopLoopForContainer` done
1. `KillExecPIDs`
1. …
=> OCPBUGS-55485: Fix deadlock when stopping uninterruptible container

internal/factory/container/container.go, internal/factory/container/device_freebsd.go, internal/factory/container/device_linux.go, internal/factory/container/device_test.go, internal/factory/container/device_unsupported.go, server/container_create.go, test/cdi.bats
/kind bug
Currently CDI device injection is performed right after injecting other devices into the container. This is problematic because CDI device injection might alter, among other things, the environment. However setting up the final environment happens only later during container creation and it involves setting environment variables from the image and the Pod Spec. If the same environment variable is injected both from an image or a container, and from a CDI Spec, now the former take precedence of the latter. This is unintentional and wrong.
This patch moves CDI device injection much later during container creation, between OCI Hook injection and *oci.Container creation.
None
```release-note
server: delay CDI device injection, to ensure that CDI Spec edits take precedence over image …
```
=> server,factory/container: delay CDI device injection later.

internal/lib/container_server.go, internal/log/log.go
/kind cleanup
The message is printed periodically to the logs which can be noisy. To reduce the verbosity we now print it only when the log level is set to trace.
None
None
```release-note
None
```
=> Reduce log noise from monitor prober

internal/oci/container.go, internal/oci/runtime_oci.go
(cherry picked from commit 1e751b490b2f8eb48cc39efa9eca2c0ffcd9ac0c)
cherry-pick from #9256 
/assign bitoku
```release-note
Fix the bug that pod can't be terminated when the process is uninterruptible sleep for a while.
```
=> OCPBUGS-57734: [release-1.32] fix deadlock when the container is in uninterruptible sleep

contrib/test/ci/vars.yml, internal/storage/image_test.go, server/sandbox_network.go, server/sandbox_network_freebsd.go, server/sandbox_network_linux.go, server/sandbox_network_unsupported.go, test/image.bats, test/network.bats, test/registries.conf, test/testdata/Dockerfile
After host reboot, network namespaces are destroyed but CRI-O attempts to clean them up during pod sandbox destruction, causing CNI plugin failures and preventing pods from restarting properly. The fix ensures pods can restart normally after host reboots.
/kind bug
[Link to journal logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/logs/periodic-ci-openshift-microshift-release-4.20-periodics-e2e-aws-tests-bootc-nightly/1939504337394864128/artifacts/e2e-aws-tests-bootc-nightly/openshift-microshift-e2e-metal-tests/artifacts/scenario-info/el96-src@ai-model-serving-offline/vms/host1/sos/journal_2025-06-30_03:38:43.log)
```release-note
Handle missing network namespace gracefully during networkStop
```
=> OCPBUGS-58229: server: handle missing network namespace gracefully during networkStop

internal/oci/container.go, internal/oci/runtime_oci.go
(cherry picked from commit 1e751b490b2f8eb48cc39efa9eca2c0ffcd9ac0c)
cherry-pick from #9256 
/assign bitoku
```release-note
Fix the bug that pod can't be terminated when the process is uninterruptible sleep for a while.
```
=> OCPBUGS-57735: [release-1.31] fix deadlock when the container is in uninterruptible sleep

internal/oci/container.go, internal/oci/runtime_oci.go
(cherry picked from commit 1e751b490b2f8eb48cc39efa9eca2c0ffcd9ac0c)
cherry-pick from #9256 
/assign bitoku
```release-note
Fix the bug that pod can't be terminated when the process is uninterruptible sleep for a while.
```
=> OCPBUGS-58508: [release-1.30] fix deadlock when the container is in uninterruptible sleep

test/ctr.bats
From the original PR #9271:
```
It's a long story (see [1], [2], [3], [4]) but both runc and crun is changing the formula to convert cgroup v1 CPU shares to cgroup v2 CPU weight, and it causes a failure in "ctr update resources" test, because it relies on the old conversion formula.
Let's modify it so it works either the old or the new conversion.
(Ultimately, with cgroup v2 we should switch to setting unified.cpu.weight directly).
[1]: https://github.com/kubernetes/kubernetes/issues/131216
[2]: https://github.com/opencontainers/runc/issues/4772
[3]: https://github.com/opencontainers/cgroups/pull/20
[4]: https://github.com/containers/crun/pull/1767
```
None
This is a cherry-pick of #9271 to the 1.33 release branch.
```release-note
None
```
=> [release-1.33] [cherry-pick #9271] test/ctr.bats: fix wrt new CPU units to weight conversion

internal/oci/container.go, internal/oci/runtime_oci.go
(cherry picked from commit 1e751b490b2f8eb48cc39efa9eca2c0ffcd9ac0c)
cherry-pick from #9256 
/assign bitoku
```release-note
Fix the bug that pod can't be terminated when the process is uninterruptible sleep for a while.
```
=> OCPBUGS-58509: [release-1.29] fix deadlock when the container is in uninterruptible sleep

dependencies.yaml, docs/crio.8.md, docs/crio.conf.5.md, internal/storage/image_test.go, pkg/config/config_linux.go, pkg/config/config_unsupported.go, test/common.sh
Update the pause image to the latest version.
Refers to https://github.com/kubernetes/kubernetes/pull/130713
None
```release-note
Updated pause image to 3.10.1.
```
=> Update pause image to 3.10.1

install.md, roadmap.md, test/ctr.bats
/kind ci
Fix GitHub action CI test setup (missing br_netfilter).
Cherry-pick #9271 for failing  container update test in `test/ctr.bats`.
Fix failing test due to a mismatching test pattern altered in 438d5281862801c370ef3bed5994d79d872f1a2c.
Fix markdown to make docs pass the prettier-verification in CI.  
None
```release-note
None
```
=> [release-1.32] fix GitHub action CI test setup, failing tests.

go.mod, go.sum, vendor/github.com/go-chi/chi/v5/README.md, vendor/github.com/go-chi/chi/v5/chi.go, vendor/github.com/go-chi/chi/v5/mux.go, vendor/github.com/go-chi/chi/v5/path_value.go, vendor/github.com/go-chi/chi/v5/path_value_fallback.go, vendor/github.com/go-chi/chi/v5/tree.go, vendor/modules.txt
This fixes [GHSA-vrw8-fxc6-2r93](https://github.com/advisories/GHSA-vrw8-fxc6-2r93).
Discussed on slack here: https://kubernetes.slack.com/archives/CAZH62UR1/p1753170348596769
I get that this is a low priority issue but we would like to get it fixed and included in a release. This is why I am pushing it to release-1.33. It is already fixed on main and release-1.34 but not included in any release.
```release-note
None
```
=> Bump go-chi to v5.2.2

internal/config/cgmgr/cgmgr_linux.go, internal/config/cgmgr/systemd_linux.go, server/container_update_resources.go, server/container_update_resources_linux.go, server/container_update_resources_unsupported.go, test/ctr.bats
This change validates memory limits against current usage from cgroup files instead of stale cAdvisor cache.
/kind bug
```release-note
server: add real-time memory validation for limit updates
```
=> server: add real-time memory validation for limit updates

server/container_create.go
/kind cleanup
The log message is pretty old, but we should keep the information around by stating the user even when it's an empty string.
Refers to https://github.com/cri-o/cri-o/issues/9416
None
```release-note
Changed `CONTAINER USER: …` debug log message to become `Container user: "…"`.
```
=> Cleanup container user log message and trivial code

go.mod, go.sum, internal/oci/runtime_pod.go, pkg/config/template.go, vendor/github.com/containers/conmon-rs/pkg/client/client.go, vendor/github.com/containers/conmon-rs/pkg/client/consts.go, vendor/modules.txt
/kind feature
Reuse `monitor_env` to pass down the options to the pod runtime (conmon-rs).
None
None
```release-note
Added support for conmon-rs log driver and heaptrack config by using the `monitor_env` runtime configuration.
```
=> Add support for conmon-rs log driver and heaptrack config

internal/oci/runtime_vm.go, test/logs.bats
/kind bug
This is a cherry-pick of https://github.com/cri-o/cri-o/pull/9433
This commit implements the ReopenContainerLog function. This fixes an issue where kata container logs could not be rotated.
This required duplicating part of the createContainerIO function, so I am moving this in its own subfunction for reuse.
None
```release-note
Fix log rotation not working for containers running with the kata-containers runtime
```
=> [release-1.32] Backport kata logrotate fix

internal/oci/runtime_vm.go, test/logs.bats
/kind bug
This is a cherry-pick of https://github.com/cri-o/cri-o/pull/9433
This commit implements the ReopenContainerLog function. This fixes an issue where kata container logs could not be rotated.
This required duplicating part of the createContainerIO function, so I am moving this in its own subfunction for reuse.
None
```release-note
Fix log rotation not working for containers running with the kata-containers runtime
```
=> [release-1.33] Backport kata logrotate fix

internal/oci/runtime_vm.go, test/logs.bats
/kind bug
This is a cherry-pick of #9433 
This commit implements the ReopenContainerLog function. This fixes an issue where kata container logs could not be rotated.
This required duplicating part of the createContainerIO function, so I am moving this in its own subfunction for reuse.
None
```release-note
Fix log rotation not working for containers running with the kata-containers runtime
```
=> [release-1.31] Backport kata logrotate fix

cmd/crio/main.go
/kind cleanup
The release note has already been added in https://github.com/cri-o/cri-o/pull/9299
Warn when CONTAINER_INCLUDED_POD_METRCIS (typo) is used.
Fixes #9300 
```release-note
None
```
=> Warn when CONTAINER_INCLUDED_POD_METRCIS (typo) is used.

nix/overlay.nix
/kind bug
We still need to drop that to make gpgme work on various systems.
Should fix https://github.com/cri-o/cri-o/issues/9478
None
```release-note
Fixed static build gpgme issue resulting in an "Invalid crypto engine" error on various platforms.
```
=> Re-add the `--enable-fixed-path` removal for gpgme

scripts/release/release.go
/kind ci
This allows to update the dependencies.yaml file if it contains the 'development version' (from 1.33). This will cause not to break CI for those branches anymore. Previous branches should be unaffected by this change.
None
None
```release-note
None
```
=> Update dependencies.yaml if required on release cut

.github/workflows/integration.yml, dependencies.yaml, go.mod, nix/derivation.nix
/kind ci
Switch to go1.25 because it will be required for the next k8s release.
None
None
```release-note
Require go 1.25 for building CRI-O.
```
=> Switch to go 1.25

internal/log/interceptors/interceptors.go, test/ctr.bats, test/logs.bats
/kind cleanup
The log format has changed since https://github.com/cri-o/cri-o/pull/9334 .
We changed the format from `%+v` to `%#v` because we thought it sometimes failed to print structs, but it was actually because the structs didn't have values.
For example, VersionRequest is sometimes like `&VersionRequest{Version:,}`:
In [1.33](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/cri-o_cri-o/9194/pull-ci-cri-o-cri-o-main-ci-cgroupv2-e2e-features/1923039946097037312/artifacts/cgroupv2-e2e-features/cri-o-gather/artifacts/journal.log), it's printed with `%+v` as
```
May 15 15:51:45 ci-op-fi2q3184-9d9a4-buildhost crio[9683]: time="2025-05-15T15:51:45.812030634Z" level=debug msg="Request: &VersionRequest{Version:,}" …
```
=> Update log formatting in interceptors to use %+v
