cri-o/cri-o

scripts/node_e2e_installer

/kind ci
Custom installation script for crio for node e2e tests
None
```release-note
None
```

Add a script for crio installation for node e2e

---

conmon/conmon.c

/kind bug
```release-note
none
```

1.11 conmon: kill process group if timed out

---

scripts/github-actions-setup

/kind ci
```release-note
none
```

[1.21] scripts: pin cri-tools version

---

docs/crio.conf.5.md

docs: remove outdated field

---

pkg/config/template.go
pkg/config/template_test.go

/kind bug
> /kind ci
> /kind design
> /kind flake
> /kind other
otherwise, changing the runtime path doesn't print a new config
```release-note
none
```

config: use deep equal to compare workloads and runtimes

---

internal/oci/runtime_oci.go

and listen to a comment saying explicitly not to close that channel there :facepalm:
/kind bug
```release-note
Fix potential panic when reopening a container's log
```

[1.20] oci: fix panic on double close

---

internal/oci/runtime_oci.go

and listen to a comment saying explicitly not to close that channel there :facepalm:
/kind bug
```release-note
Fix potential panic when reopening a container's log
```

[1.21] oci: fix panic on double close

---

internal/oci/runtime_oci.go

and listen to a comment saying explicitly not to close that channel there :facepalm:
/kind bug
```release-note
Fix potential panic when reopening a container's log
```

[1.19] oci: fix panic on double close

---

internal/oci/runtime_oci.go

and listen to a comment saying explicitly not to close that channel there :facepalm:
/kind bug
```release-note
Fix potential panic when reopening a container's log
```

oci: fix panic on double close

---

pkg/sandbox/fixtures/expanded_resolv.conf
pkg/sandbox/infra.go
pkg/sandbox/infra_test.go

/kind feature
This PR makes cri-o allow [ExpandedDNSConfig](https://github.com/kubernetes/enhancements/tree/master/keps/sig-network/2595-expanded-dns-config)
Fixes #5198 
```release-note
cri-o now does not limit the DNS search paths.
```

Allow expanded DNS configuration

---

internal/config/node/node.go

/kind bug
```release-note
CRI-O now logs when it is using cgroupv2
```

node: log if we are using cgroupv2

---

internal/dirnotifier/dirnotifier.go

/kind bug
```release-note
none
```

dirnotifier: optimize accesses to Map

---

server/inspect.go
server/inspect_ginkgo_test.go
server/inspect_test.go

/kind bug
```release-note
none
```

server: do not check storage for image name on inspect

---

.github/workflows/verify.yml
hack/openpgp_tag.sh

a handy fix, see https://github.com/cri-o/cri-o/issues/5219

fix checking in openpgp_tag.sh

---

completions/fish/crio.fish
docs/crio.8.md
docs/crio.conf.5.md
internal/criocli/criocli.go
pkg/config/config.go
test/crio-wipe.bats

```release-note
The internal_wipe option is now true by default. Further, it is being deprecated, and will be unconditionally true in the future.
```

config: set internal_wipe to true by default, and deprecate the option

---

contrib/test/integration/golang.yml

The new versions depend on newer golang and we don't
want to update golang for this branch.
/kind ci
Broken CI
```release-note
None
```

[1.19] test: Pin gomega and ginkgo versions

---

internal/oci/runtime_oci.go
internal/storage/image.go

if we fail to move conmon to a cgroup, we still need to call Wait() on the process, or else we will leak a child
/kind bug
```release-note
fix a PID leak in situations where conmon fails to be moved into the pod cgroup
```

oci: call wait on conmon if cgroup move fails

---

internal/version/version.go

version: bump to v1.19.4

---

internal/version/version.go

version: bump to v1.20.5

---

internal/version/version.go

version: bump to v1.21.3

---

contrib/bundle/install
scripts/get

/kind bug
Fixes #5279
Alternatively, we can change the `#!` line to run bash.  But maximising portability seemed like the right choice here.
```release-note
None
```

Remove bashism in sh script

---

internal/lib/container_server.go
server/sandbox_status.go
test/drop_infra.bats

/kind bug
```release-note
fix a bug where `inspectp` verbose output was incomplete for pods with a dropped infra container
```

server: set spec when dropping infra

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/integration.yml
.github/workflows/test.yml
.github/workflows/verify.yml
README.md
cri.md
install.md
internal/hostport/README.md
scripts/node_e2e_installer
test/README.md

Signed-off-by: Francesco Giudici <fgiudici@redhat.com>
/kind other
Update the links referring to the **master** branch to point the **main** one.
Links are redirected from master to main when requested, so many changes in this PR do not fix actual issues.
Few changes are anyway required to fix smaller issues (e.g., update the link to display the CRI-O logo in our github markdown pages).
None
```release-note
None
```

Update 'master' branch links to 'main'

---

scripts/node_e2e_installer

there is a stats test that flakes on cgroupv1 and continuously fails on cgroupv2 that needs to be investgiated
```release-note
none
```

node e2e: keep infra container

---

.github/workflows/test.yml

/kind ci
```release-note
none
```

[1.19] gh actions: fix workflow

---

install.md

Fix typo in install.md

---

scripts/node_e2e_installer

/kind other
Bumps the commit used by node e2e installer to take advantage of https://github.com/cri-o/cri-o/commit/c0020b2b57178bc4e66b95a1bc38c58d62679af5
None
```release-note
None
```

bump crio commit for node e2e installer

---

scripts/node_e2e_installer

/kind ci
```release-note
none
```

fix node e2e

---

server/container_create.go
server/container_create_linux.go

/kind bug
as well as fix an issue where hostNet containers couldn't access cgroup heierarchy 
fixes https://github.com/kubernetes/kubernetes/issues/104034
```release-note
Fix a bug where host network containers couldn't read their cgroup hierarchy 
```

server: fix some hostNet handling in container creation

---

README.md

Use a more appropriate console with a code block.
[renderd](https://github.com/cri-o/cri-o/blob/245a8804002c1e39c4dad4d0f5fa638a1b865b03/README.md)
None
```release-note
none
```

use a more appropriate console with code block

---

install.md

Signed-off-by: Étienne Guesnet <etienne.guesnet@atos.net>
Correct two wrong link in install.md.
Fixes #5357
```release-note
None
```

Fix install.md links

---

install.md
tutorials/install-distro.md

apt-key is deprecated and will be removed after Ubuntu 22.04. Follow this guide and use gpg instead.
https://wiki.debian.org/DebianRepository/UseThirdParty
None
```release-note
None
```

Remove usge of deprecated apt-key in Ubuntu install

---

contrib/test/integration/build/parallel.yml

test: skip certificate check for downloading parallel

---

internal/oci/oci.go
internal/oci/runtime_oci.go
test/ctr.bats

as well as fix an issue with terminals in execs
/kind bug
```release-note
fix an issue when a container with a terminal has an exec probe
```

[1.20] oci: finish reverting exec changes

---

contrib/test/ci/cri-o.spec
internal/version/version.go

[1.20] bump to 1.20.6

---

contrib/test/ci/cri-o.spec
internal/version/version.go

[1.22] bump to 1.22.1

---

internal/oci/container.go
internal/oci/oci.go
internal/oci/runtime_oci.go

/kind cleanup
```release-note
none
```

oci: Fix a couple of deadlocks in container stop code

---

server/container_create_linux.go

/kind bug
```release-note
none
```

server: fix segfault when using cgroupv2

---

scripts/github-actions-packages
scripts/release-notes/release_notes.go

/kind ci
```release-note
none
```

release-notes: update to main

---

contrib/test/ci/cri-o.spec
images/os/Dockerfile
internal/version/version.go

[1.21] bump to 1.21.4

---

pkg/config/config.go

Close:https://github.com/cri-o/cri-o/issues/5394:
Specify runtime table format in  the error message to make it more clearer to understand.
```release-note
Specify runtime table format in  the error message
```

Specify runtime table format in  the error message

---

install.md

Signed-off-by: Skyler Clark <wgahnagl@protonmail.com>
adds updating instructions to the install docs
fixes #4227 
```release-note
None
```

adds updating instructions to install.md

---

pkg/config/config.go
server/utils.go
test/workloads.bats

to allow for a more smooth transition between workloads and runtime class level allowed annotations
/kind bug
```release-note
Allow for both runtime class and workload level allowed annotations. Now, if a container or pod has both specified, the list will be merged.
```

config: merge runtime and workload allowed annotations

---

internal/lib/stats/stats_server.go

/kind bug
It may be possible that the stats servers `Shutdown()` get called twice
during CRI-O stop. To avoid calling `close()` on an already closed
channel, we now internally track if the stats server is still running or
not.
Introduced in https://github.com/cri-o/cri-o/pull/5427
None
```release-note
None
```

Fix runtime panic on stats server shutdown

---

internal/oci/container.go
internal/oci/oci.go
internal/oci/runtime_oci.go

/kind cleanup
cherry-pick of https://github.com/cri-o/cri-o/pull/5433
```release-note
none
```

[1.22] oci: fix a couple of deadlocks in container stop code 

---

contrib/test/integration/build/parallel.yml
contrib/test/integration/golang.yml

/kind ci
```release-note
none
```

[1.18] ci: revert ginkgo version update to support go 1.13

---

internal/oci/runtime_oci.go

Even if we kill the process, we still need to wait for it, or else we'll reap a zombie.
```release-note
Fix a case where conmon children are sometimes leaked
```

oci: always reap conmon zombies

---

internal/config/cgmgr/cgroupfs.go
internal/oci/oci_linux.go
pkg/config/config.go
server/image_pull.go
test/helpers.bash
test/infra_ctr_cpuset.bats
test/workloads.bats
utils/consts.go

/kind feature
```release-note
Now, if infra_ctr_cpuset is configured, conmon is put in the same cpuset
```

oci: set conmon cpuset to infra_ctr_cpuset

---

.golangci.yml
contrib/test/integration/test.yml
scripts/github-actions-setup
test/helpers.bash
test/userns_annotation.bats
test/workloads.bats
tutorial.md
tutorials/userns.md

/kind ci
previously, the documentation and testing around user namespaces was pretty poor. Let's update both in one feld swoop, so we know we're testing the stuff we claim works in our docs
```release-note
none
```

docs and tests: update for user namespace modes

---

internal/version/version.go

Signed-off-by: Johannes 'fish' Ziemke <github@freigeist.org>
/kind other

version: bump to 1.18.5

---

utils/utils.go

We're now using a timeout which is able to unblock gaining
the sandbox mutex in a container creation vs sandbox stop race.
Signed-off-by: Sascha Grunert <sgrunert@redhat.com>
/kind bug
```release-note
none
```

Use timeout for conmon cgroup move

---

internal/version/version.go

/kind cleanup
Fixing the version number for a new tag.
None
None
```release-note
Bump version to v1.18.6
```

Bump to v1.18.6

---

pinns/Makefile

Signed-off-by: Ryan Shea <sheabot03@gmail.com>
/kind cleanup
This allows `LDFLAGS` to be passed into the pinns build. This is useful in a Yocto build environment that may have special linker flags (i.e PIE, stack protector, etc.).
None
```release-note
None
```

pinns: Add LDFLAGS to Makefile

---

scripts/node_e2e_installer

/kind ci
Bump crio commit used by upstream k8s CI
```release-note
None
```

bump crio commit for upstream k8s CI

---

.github/workflows/verify.yml
Makefile
hack/validate-config.sh
pkg/config/config.go
pkg/config/template.go
test/config.bats

changes the default crio config to print default config values as comments instead of ommitting them
Fixes #4770 
```release-note
changes default config output to comment default values instead of omitting them
```

Comments default values instead of omitting them

---

ADOPTERS.md

Adds Nestybox to the list of CRI-O adopters list.
None.
No.
```release-note
None
```
Signed-off-by: Cesar Talledo <ctalledo@nestybox.com>

Add Nestybox to the CRI-O adopters list.

---

tutorials/kubeadm.md

Signed-off-by: jamesread <contact@jread.com>
Simply a clarification documentation, re the kubeadm tutorial for cri-o. I ran into an issue trying to use bridge by accident on a multiple-host cluster. 
Fixes #5549 
This is my first PR on the project :-) I've read the CONTRIBUTING guide, and the notes in this PR. 
```release-note
None
```

Documentation: expand on CNI CIDRs in the kubeadm tutorial (RE: #5549)

---

contrib/test/integration/build/runc.yml
images/os/Dockerfile

/kind ci
```release-note
none
```

openshift e2e: bump ci image

---

contrib/test/integration/build/conmon.yml

/kind ci
```release-note
none
```

ci: use main branch for conmon

---

server/utils.go

previously, CRI-O assumed that the kubelet wouldn't bump the attempt number
if it returned an error after a series of retries.
in reality, the kubelet *is* doing that, which means situations where we have lots of load on a node
means the issue is made worse by this workaround, not better.
Mitigate this by waiting until the timeout is completed before returning the fact that the resource is ready.
This will cause the kubelet to continue to believe the timing out has happened, and retry with the same attempt number.
```release-note
fix a bug where situations of excessive load on nodes causes containers to never actually start
```

server: fix race with kubelet

---

contrib/test/integration/build/runc.yml
scripts/github-actions-setup

/kind ci
```release-note
none
```

[1.22] ci: pin binary versions

---

GOVERNANCE.md

GOVERNANCE: fix links

---

server/container_create_linux.go
test/cgroups.bats

```release-note
Fix a bug where memory swap values were specified even if the memory swap cgroup is not enabled
```

server: don't set memory swap when it's not enabled

---

server/sandbox_run_linux.go
test/pod.bats

/kind bug
fixes https://github.com/cri-o/cri-o/security/advisories/GHSA-w2j5-3rcx-vx7x
```release-note
Fix a bug where a pod given a host IPC or network namespace could configure sysctls on the host
```

server: filter sysctls passed through CRI if host namespace

---

README.md

README: update branches

---

internal/version/version.go

[1.23] bump to v1.23.1

---

scripts/release-notes/release_notes.go

/kind bug
```release-note
none
```

[1.23] release-notes: add args for checksum fields

---

internal/oci/runtime_oci.go

/kind bug
if conmon container creation times out, then we'll leak a go routine because of an unbuffered channel
```release-note
none
```

oci: fix a leaked goroutine

---

contrib/test/integration/build/kubetest.yml
contrib/test/integration/main.yml
internal/oci/oci.go

/kind bug
https://github.com/cri-o/cri-o/pull/5535 https://github.com/cri-o/cri-o/pull/5475
cherry-pick of relevant commits of https://github.com/cri-o/cri-o/pull/5475
```release-note
none
```

[1.19] various deadlock fixes

---

install.md

Signed-off-by: David Popp <david.popp@pm.me>
removes dead link
```release-note
None
```

minor edit: removed dead link from TOC

---

OWNERS

I have reached out to @sameo and he has agreed to be moved to the emertius approvers. Github tells me he's submitted 64 commits (#10 as of the time of writing) and ~9000 code changes).
Thank you for all you've for the CRI-O project!
```release-note
none
```

OWNERS: move @sameo to emeritus_approvers

---

OWNERS

Signed-off-by: Fabiano Fidêncio <fabiano.fidencio@intel.com>
I have reached out to @sboeuf and he has agreed to be moved to the emertius approvers. Github tells me he's submitted 41 commits (https://github.com/cri-o/cri-o/commits?author=sboeuf as of the time of writing) and ~40000 code changes, including changes to the vendored code).
Thank you for all you've done for the CRI-O project!
None
```release-note
None
```

OWNERS: Move @sboeuf to emeritus approver

---

.github/workflows/verify.yml
Makefile
dependencies.yaml
internal/config/cgmgr/stats_test.go
internal/hostport/hostport_manager_test.go
internal/runtimehandlerhooks/utils.go
internal/storage/image.go
internal/storage/suite_test.go
internal/version/version.go
scripts/release-notes/release_notes.go
scripts/release/release.go
server/container_create_linux.go
server/server.go
server/streaming/streaming.go
utils/utils.go

/kind ci
/kind cleanup
This bumps golangci-lint to a recent version, and fixes all the newly found issues
(plus a few old ones).
None
```release-note
NONE
```

Bump golangci to 1.44.0

---

OWNERS

welcome to the club :sunglasses: 
fixes https://github.com/cri-o/cri-o/issues/5642 https://github.com/cri-o/cri-o/issues/5649 https://github.com/cri-o/cri-o/issues/5648 https://github.com/cri-o/cri-o/issues/5640
```release-note
none
```

OWNERS: add first round of reviewers

---

OWNERS

These two have helped create CRI-O to what it is today. @rhatdan has ushered CRI-O from infancy giving guidance on SELinux, storage and running an open source project. He has committed 123 commits and changed around 55,000 lines of code
@runcom remains the second highest contributor by changed lines of code, and fourth by commits (1.5 million and ~400, respectively). CRI-O literally wouldn't be what it is today without his ushering CRI-O through and out of infancy.
Thank you both for all the work you've done, and please feel free to come back and contribute/review when you have more time.
```release-note
none
```

OWNERS: move runcom and rhatdan to emeritus approvers

---

hack/build-rpms.sh

/kind ci
/kind flake
This tries to solve a failure in building rpms, and consists of two fixes.
1. Looking into cri-o CI, this error seems common:
> http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2600:1f16:c1:5e03:a992:8ee1:99d2:6f8: Network is unreachable"
> http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: [Errno 14] curl#7 - "Failed to connect to 2600:1f16:c1:5e03:a992:8ee1:99d2:6f8: Network is unreachable"
> http://vault.centos.org/centos/7/os/Source/repodata/repomd.xml: [Errno 14] HTTPS Error 301 - Moved Permanently
> [ERROR] hack/build-rpms.sh:31: `yum-builddep -y "${OS_RPM_SPECFILE}"` exited with status 1.
Apparently, vault.centos.org resolves to both IPv4 and IPv6 addresses,
and one of the …

hack/build-rpms.sh: fix yum-builddep failures

---

contrib/test/integration/build/kubernetes.yml
contrib/test/integration/e2e.yml
contrib/test/integration/main.yml
dependencies.yaml
scripts/versions

/kind ci
Use latest kubernetes and cri-tools in CI.
None
```release-note
NONE
```

CI: use kubernetes and cri-tools from git tip (aka HEAD, aka master)

---

internal/version/version.go

bump to v1.22.2

---

server/sandbox_run_linux.go

/kind bug
```release-note
none
```

server: stop deleting pod from idIndex if already gone

---

contrib/test/ci/cri-o.spec
internal/version/version.go

bump version to 1.24.0

---

internal/version/version.go

bump to 1.21.5

---

internal/oci/runtime_oci.go

/kind bug 
combines https://github.com/cri-o/cri-o/pull/5283 and https://github.com/cri-o/cri-o/pull/5306
```release-note
fix a PID leak in situations where conmon fails to be moved into the pod cgroup
```

[1.19] server: handle processes better

---

internal/version/version.go

bump to v1.19.5

---

test/drop_infra.bats

of failing if there are no containers on `runc list`
/kind ci
```release-note
none
```

test: update to new runc behavior

---

README.md

Minor doc update
None
N/A
```release-note
NONE
```

README: Update EOL & Version Skew links

---

test/pod.bats

/kind ci
The sysctls test needs some shell formatting fixing to make the CI happy again.
None
None
```release-note
None
```

Fix shell format

---

internal/factory/container/container.go
internal/factory/container/container_test.go
internal/factory/sandbox/infra.go
server/container_create.go
server/container_create_linux.go
server/sandbox_run_linux.go
server/utils.go

/kind design
moves capabilities setup to the factory package and adds unit tests
```release-note
none
```

factory: take capabilities setup

---

test/infra_ctr_cpuset.bats

Signed-off-by: Jim Ramsay <jramsay@redhat.com>
/kind ci
This adds a bats test to check the code change in #5514
None
```release-note
None
```

Add bats test for infra_ctr_cpuset taskset

---

scripts/github-actions-setup

Looks like we hit a permission issue with the ginkgo installation. To
avoid something like this we now `chown` the `$GOPATH` accordingly.
None
None
```release-note
None
```

Fix integration tests

---

docs/crio.8.md
docs/crio.conf.5.md
pkg/config/config.go
test/helpers.bash
tutorials/kubeadm.md

/kind feature
Related:
- https://github.com/kubernetes/k8s.io/issues/3411
The Kubernetes project setup a new endpoint that will used to service
the container images produced by the project.
```release-note
Updated default pause image to point to new location `registry.k8s.io/pause:3.6`
```

Switch to registry.k8s.io for the sandbox Image:

---

contrib/test/integration/main.yml

/kind ci
```release-note
none
```

test: bump to go 1.18.1

---

Makefile

```release-note
Fix 386 builds within CI
```

fix 386 builds by passing -buildvcs=false

---

images/os/Dockerfile
internal/factory/container/container.go
internal/factory/container/container_test.go

/kind bug
```release-note
Fix CVE-2022-27652 by dropping and refusing to add any inheritable capabilities
```

capabilities: drop inheritable

---

contrib/test/integration/build/kubetest.yml

/kind ci
```release-note
none
```

[1.23] test: pin kubetest to prevent build failures with generics

---

completions/fish/crio.fish
docs/crio.8.md
docs/crio.conf.5.md
internal/criocli/criocli.go
internal/oci/oci_linux.go
internal/oci/runtime_oci.go
pkg/config/config.go
pkg/config/config_test.go
pkg/config/template.go

This makes the transition to conmonrs easier, as we can update conmonrs fields inpendently of the conmon ones.
```release-note
Deprecate `conmon`, `conmon-cgroup`, and `conmon-env` config options in favor of runtime handler specific fields `monitor-path`, `monitor-cgroup`, and `monitor-env`
```

config: move conmon specific fields in to runtime handler

---

.github/workflows/integration.yml
scripts/github-actions-setup
test/critest.bats

/kind ci
A first try to integrate conmonrs into the CRI-O CI.
None
None
```release-note
None
```

Run critest with conmonrs

---

contrib/test/integration/build/bats.yml
dependencies.yaml
scripts/versions

We now update the versions used in `scripts/versions` to reference their latest releases.
None
None
```release-note
None
```

Bump third party dependencies

---

server/container_create_linux.go

This is a manual cherry pick of https://github.com/cri-o/cri-o/pull/5846
```release-note
None
```

[release-1.22] Move WillRunSystemd call after iterating the mounts

---

internal/oci/runtime_oci.go
server/sandbox_run_linux.go

CodeQL recommends we use ParseInt and convert so we include a bounds checker
/kind bug
```release-note
none
```

Fix some uses of Atoi

---

internal/version/version.go

version: bump to 1.22.4

---

internal/version/version.go

version: bump to 1.21.7

---

README.md

Signed-off-by: Kang.Zhang <Kang.zhang@intel.com>
Move 1.23 -> 1.24
```release-note
none
```

docs: move 1.23 to 1.24 in README

---

README.md

Signed-off-by: vikash <singh.vikash2310@gmail.com>
Fixed multiple typos in the README file including correcting the spelling of convenience earlier it was convinience.
None
```release-note
```

changes in README

---

install.md

fixes https://github.com/cri-o/cri-o/issues/2885
(or finishes doing so)
```release-note
none
```

docs: update for CNI package change

---

README.md

Signed-off-by: jiang wei <jwcesign@gmail.com>
Update readme about pause/unpause interface
none
none
none
```release-note
none
```

docs: Add pause/unpause description to readme

---

contrib/test/integration/build/kubernetes.yml
contrib/test/integration/main.yml

by changing the socket to a symlinked location
fixes https://github.com/cri-o/cri-o/issues/5923
(though we should figure out why it's failing on fedora in the first place)
```release-note
none
```

test: set cri stats more idiomatically

---

contrib/test/integration/main.yml
dependencies.yaml
scripts/versions
test/ctr.bats
test/helpers.bash

Update cri-tools to the latest release.
None
None
```release-note
Updated cri-tools to v1.24.2.
```

Bump cri-tools to v1.24.2

---

go.mod
go.sum
vendor/github.com/containernetworking/cni/pkg/invoke/exec.go
vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
vendor/github.com/cri-o/ocicni/pkg/ocicni/util_linux.go
vendor/modules.txt

fixes https://github.com/cri-o/cri-o/issues/5889
```release-note
Fix a panic caused by using the improper Result structure version when setting up CNI plugins
```

bump ocicni to v0.4.0

---

internal/oci/container.go
server/container_create_linux.go
server/container_status.go

/kind bug
Fixes https://github.com/cri-o/cri-o/issues/5916
```release-note
None
```

Fix container status for HostToContainer propagation

---

contrib/test/integration/build/runc.yml
dependencies.yaml
internal/config/cgmgr/cgroupfs.go
scripts/versions
vendor/github.com/opencontainers/runc/libcontainer/cgroups/manager/new.go
vendor/modules.txt

Update runc to the latest release.
None
Incorporated changes from @kolyshkin (https://github.com/cri-o/cri-o/pull/5506)
```release-note
None
```

Bump runc to v1.1.3

---

.github/workflows/stale.yml

/kind ci
Right now the limit of 30 is hit really soon since we have around 250 issues and PRs to process. We now bump that to 300 to cover all.
None
None
```release-note
None
```

Run more stale operations

---

pkg/config/template.go

/kind bug
```release-note
update `cni_default_network` to not be commented by default in the output of `crio config`
```

[1.23] config: uncomment cni_default_network

---

install.md

update ubuntu releases

---

.github/workflows/test.yml

/kind ci
The unit test coverage does not work any more since quite some time. We should fix that.
None
None
```release-note
None
```

Fix unit test coverage

---

.github/workflows/test.yml
scripts/upload-artifacts

/kind ci
Now we only have to push the tag and GitHub actions will take care of creating the associated release and uploading the artifacts to it.
None
None
```release-note
None
```

Upload release notes for each tag

---

install.md

This PR just fix a link issue in the `install.md` file and make it more obvious why some repositories are needed for specific packages. I admit I did not see the information before so maybe it will make it more obvious.
Fixes #6015 partially.
```release-note
None
```

Fix a link in install.md building section about dependencies

---

scripts/release-notes/release_notes.go

/kind ci
It may be possible that multiple release notes jobs trying to push to the `gh-pages` branch. We now retry to rebase multiple times and only give-up after a couple of errors.
None
None
```release-note
None
```

Retry release notes push if failed

---

contrib/bundle/build
contrib/bundle/install
scripts/get

/kind ci
```release-note
none
```

scripts: install runc if not found in get script

---

internal/lib/sandbox/sandbox.go
internal/oci/container.go
server/container_list.go
server/sandbox_list.go

by only creating a new sandbox or container object when they change
/kind bug
```release-note
none
```

server: reduce object creation in List{Containers,PodSandboxes}

---

scripts/release-notes/release_notes.go

/kind ci
We did not fetch the remote content of the branch which I assume is
caused by the fetch configuration for the GitHub action. Therefore we
now enforce that by running `git pull --rebase`.
Beside that, we also break if the max retries are reached.
None
None
```release-note
None
```

Fix release notes pull behavior

---

contrib/test/integration/e2e-features.yml
contrib/test/integration/e2e.yml

remove succinct to fix jenkins

remove succinct option to fix jenkins

---

test/selinux.bats

Signed-off-by: Burt Holzman <burt@fnal.gov>
/kind other
Adds test case for PR #5775 
None
```release-note
None
```

Add test for "Canonize selinux label"

---

scripts/dependencies/dependencies.go

/kind ci
We now retry pushing the dependency report in the same way we do it with the release notes since they both push to the same branch.
None
None
```release-note
None
```

Retry dependency report push if failed

---

ADOPTERS.md

Add Lyft to ADOPTERS.md
None
PTAL @haircommander
```release-note
None
```

Add Lyft to adopters

---

dependencies.yaml
scripts/versions

None
None
None
```release-note
Updated crun to v1.5.
```

Bump crun: 1.4.5 -> 1.5

---

contrib/test/ci/build/cri-o.yml
contrib/test/ci/golang.yml

Signed-off-by: Skyler Clark <skylerjaneclark@gmail.com>
/kind cleanup
removes the crio clone that was preventing CI from pulling in the actual PR updates
```release-note
none 
```

changes the cri-o clone step to a copy

---

internal/version/version.go

version: bump to v1.24.2

---

test/image.bats

/kind ci
The image digest is gone from the upstream remote so we now point to the latest version of it.
None
I'm not sure why the image has been re-built. Do you know @rphillips @wgahnagl ?
```release-note
None
```

Fix nginx based integration tests

---

contrib/test/ci/critest_images.yml
contrib/test/ci/sync_images.sh
test/image.bats

Migrates more images to quay.io
```release-note
NONE
```

migrate image_list to quay.io

---

.github/workflows/integration.yml
.github/workflows/test.yml
Makefile
contrib/bundle/test-e2e
go.mod
go.sum
internal/oci/runtime_pod.go
scripts/github-actions-setup
test/cgroups.bats
test/conmonrs.bats
test/ctr.bats
test/helpers.bash
test/infra_ctr_cpuset.bats
test/network.bats
test/workloads.bats
vendor/github.com/containers/conmon-rs/pkg/client/attach.go
vendor/github.com/containers/conmon-rs/pkg/client/client.go
vendor/modules.txt

/kind ci
We now test the e2e upstream Kubernetes tests as well as our bats based integration suite using the latest conmonrs version.
None
None
```release-note
None
```

Add bundle e2e and integration tests using conmonrs

---

contrib/cni/README.md

What type of PR is this?
/kind bug
What this PR does / why we need it:
fixed documentation issue present in contrib/cni/README.md
Which issue(s) this PR fixes:
Fixes https://github.com/cri-o/cri-o/issues/6075
Fixes https://github.com/cri-o/cri-o/issues/6073
Special notes for your reviewer:
None
Does this PR introduce a user-facing change?
None
None
```release-note
None
```

fix documentation issues in contrib/cni/README.md

---

scripts/node_e2e_installer

the get script only installs runc if it can't be found in path, which is
good behavior. Use the one found in path when installing the drop-in
files for node e2e tests
/kind bug
```release-note
none
```

node_e2e_installer: be use runc/crun from PATH

---

contrib/cni/README.md

Signed-off-by: Karthik Kondapally <kondapally9@gmail.com>
/kind bug
fix documentation issue in contrib/cni/README.md: build-output changed.. 
pointed out in https://github.com/cri-o/cri-o/pull/6114#discussion_r935915728
None
None
None
```release-note
None
```

fix documentation issue in contrib/cni/README.md: build-output changed

---

.github/workflows/integration.yml
.github/workflows/test.yml
.github/workflows/verify.yml
.golangci.yml
Makefile
contrib/test/ci/main.yml
contrib/test/ci/setup.yml
contrib/test/integration/main.yml
dependencies.yaml
go.mod
internal/config/cgmgr/systemd.go
internal/log/log_test.go
internal/runtimehandlerhooks/utils_test.go
server/container_create.go

bump golang to 1.19

---

.packit.yaml

/kind ci
This change adds a config file for the Packit-as-a-Service GH app (see: https://packit.dev).
With this config, packit will automatically build an RPM for each new commit and each new release tag.
None
/cc @haircommander 
None

Add packit configuration

---

server/server.go

/kind bug
Otherwise, the file will leak and fill up `/run`. also, while we're here, cleanup the exit monitor function a bit to be less deep
```release-note
Fix a bug where exit files were never cleaned up from `/run/crio/exits`
```

server: remove exit file in exit monitor

---

server/container_create_linux.go
test/cgroups.bats

fixes https://github.com/cri-o/cri-o/issues/6040
```release-note
fix a bug where CRI-O would fail if Kubelet specified `-1` for swap (which is a valid way of specifying unlimited)
```

server: allow for kubelet to specify -1 for swap

---

contrib/bundle/test-e2e

Both jobs are failing because of an unbound variable, which should be fixed now.
None
None
```release-note
None
```

Fix bundle e2e tests

---

server/container_create.go
test/ctr.bats

/kind bug
related to https://github.com/moby/moby/security/advisories/GHSA-rc4r-wh2q-q6c4
```release-note
Fix a bug where the GID of the container is not specified in the AdditionalGids, leading to a low risk security vulnerability. For more information please see https://github.com/moby/moby/security/advisories/GHSA-rc4r-wh2q-q6c4
```

server: add container GID to additional groups

---

.github/workflows/verify.yml
.golangci.yml
Makefile
dependencies.yaml
internal/client/client.go
internal/oci/runtime_oci.go
server/inspect_ginkgo_test.go
server/streaming/request_cache.go

/kind ci
Update golangci lint and increase the timeout to reduce the lint flakes.
None
None
```release-note
None
```

Update golangci-lint, config and timeout

---

contrib/test/ci/build/crun.yml
contrib/test/ci/system-packages.yml

Install go-md2man separately for RHEL9

---

internal/oci/runtime_oci.go
internal/oci/runtime_oci_test.go
utils/utils.go
utils/utils_test.go

/kind bug
fixes https://github.com/cri-o/cri-o/issues/5490
```release-note
Fix an issue with leaked systemd scopes by always sending runc the `--systemd-cgroup` flag when using systemd cgroups
```

oci: specify --systemd-cgroup for all runtime commands

---

dependencies.yaml
scripts/versions

/kind cleanup
None
None
```release-note
Update runc to v1.1.4 in static binary bundle.
```

Update runc to v1.1.4

---

.golangci.yml
internal/oci/runtime_oci.go
internal/oci/runtime_pod.go

The CI was broken because of a more or less parallel merge and now it's fixed again.
None
None
```release-note
None
```

Fix lint CI

---

contrib/test/ci/system-packages.yml

the async here was breaking equinix, and it doesn't really make sense for this to be done asyncronously anyway
```release-note
none
```

removes async

---

contrib/test/ci/build/crun.yml
contrib/test/ci/system-packages.yml

/kind ci 
adds rhel9 variant-specific changes to CI
```release-note
None
```

Adds rhel9 variant-specific changes to CI

---

.github/workflows/integration.yml
scripts/github-actions-setup

An attempt to fix the failing integration GitHub actions.
None
None
```release-note
None
```

Fix integration CI runs

---

install.md

Updated build instructions for RHEL 8 distribution, based on
recent work done using RHEL 8.5 as the build system.
Signed-off-by: Bart Wensley <bwensley@redhat.com>
Updated build instructions for RHEL 8 distribution, based on recent work done using RHEL 8.5 as the build system.
None
None
```release-note
None
```

Update build instructions for RHEL 8 distribution

---

contrib/test/ci/test.yml
contrib/test/integration/test.yml

/kind ci
/kind cleanup
The `userns` implementation is already per-pod, so we can safely drop these tests.
```release-note
None
```

contrib/test: drop userns integration tests

---

test/image.bats

Signed-off-by: Ryan Phillips <rphillips@redhat.com>
/kind ci
```release-note
none
```

[1.24] migrate image_list to quay.io

---

pkg/config/template.go

update the docs as well as whitespace of the runtime and workload tables
```release-note
none
```

template: update runtime and workload tables

---

docs/crio.conf.5.md
pkg/config/config.go
pkg/config/reload.go
pkg/config/reload_test.go
test/reload_config.bats

/kind feature
cherry-pick of https://github.com/cri-o/cri-o/pull/6248 and https://github.com/cri-o/cri-o/pull/6056
```release-note
Allow `crio.runtime.runtimes` configuration to be updated on reload.
```

[1.25] Allow runtimes to be reloaded

---

pkg/config/config_test.go
pkg/config/reload_test.go

The lint CI fails on `main`, which is now fixed: https://github.com/cri-o/cri-o/actions/runs/3188462859/jobs/5201160011
None
None
```release-note
None
```

Fix lint CI on `main`

---

internal/version/version.go

[1.24] version: bump to 1.24.3

---

.github/CODEOWNERS

I've been added to emeritus already but I'm still getting a bazillion notifications from this file afacit :)
Signed-off-by: Antonio Murdaca <runcom@users.noreply.github.com>
```release-note
none
```

.github/CODEOWNERS: drop runcom

---

internal/version/version.go

[1.25] version: bump to 1.25.1

---

internal/resourcestore/resourcestore.go
internal/resourcestore/resourcestore_test.go
server/container_create.go
server/container_create_linux.go
server/sandbox_run_linux.go
server/utils.go

/kind feature
```release-note
```

[release-1.24] resource store: save stage of resource creation and report to callers

---

internal/resourcestore/resourcestore.go
internal/resourcestore/resourcestore_test.go
server/container_create.go
server/container_create_linux.go
server/sandbox_run_linux.go
server/utils.go

/kind feature
```release-note
```

[1.22] resource store: save stage of resource creation and report to callers

---

.github/workflows/test.yml

/kind bug
```release-note
none
```

[1.24] release: drop signatures

---

internal/opentelemetry/tracing_config.go

/kind bug
We now use the `HostNameKey` for the hostname rather than the `ServiceInstanceIDKey`. We also add the process PID in the same way we do for conmonrs and update semconv to the latest version.
None
None
```release-note
- Fixed wrong tracing key for hostname field (`service.instance.id` → `host.name`).
- Added process.id to the traces.
```

Use correct key for tracing hostname field

---

internal/version/version.go

[1.23] version: bump to 1.23.4

---

internal/resourcestore/resourcestore.go
internal/resourcestore/resourcestore_test.go
server/container_create.go
server/container_create_linux.go
server/sandbox_run_linux.go
server/utils.go

/kind feature
cherry-pick of https://github.com/cri-o/cri-o/pull/6319
```release-note
```

[1.21] resource store: save stage of resource creation and report to callers

---

.github/workflows/verify.yml
.golangci.yml
Makefile
dependencies.yaml
internal/factory/container/namespaces.go
internal/oci/runtime_oci.go
internal/storage/utils.go
internal/version/version.go
pkg/config/config.go

/kind cleanup
Update the linter as well as its configuration.
None
None
```release-note
None
```

Update golangci-lint and config

---

.golangci.yml

/kind ci
The linter does not seem to work correctly and reports errors on `main`.
None
None
```release-note
None
```

Disable typecheck linter

---

ADOPTERS.md

Adds Reddit to ADOPTERS.md
None
```release-note
None
```

Add Reddit to ADOPTERS.md

---

.github/workflows/integration.yml
scripts/github-actions-packages

This fixes the failing runs in https://github.com/cri-o/cri-o/actions/runs/3535619607/jobs/5941046965.
None
None
```release-note
None
```

Downgrade cgroupfs test to Ubuntu 20.04

---

contrib/test/ci/system-packages.yml

We're temporarily adding `CentOS Stream-9` as the base OS for `cgroupv2` and `crun`  variants until we figure out the SELinux permission issue for RHEL-9 
/kind ci
This is required to address https://github.com/openshift/release/pull/34425
```release-note
None
```

contrib/test/ci: enable crb repo for CentOS Stream 9

---

contrib/test/ci/system-packages.yml

/kind ci
Follow up to https://github.com/cri-o/cri-o/pull/6410
```release-note
None
```

contrib/test/ci: fix the when condition for CentOS Stream 9

---

README.md
SECURITY.md

Update the security process to match the latest criteria. 
None
None
```release-note
None
```

Update security process

---

contrib/cni/99-loopback.conf

Signed-off-by: STRRL <im@strrl.dev>
/kind bug
- from CNI spec, https://github.com/containernetworking/cni/blob/main/SPEC.md, the field `name` should be required. And there is also a logic for validating it:
https://github.com/containernetworking/cni/blob/8dba3824fbfdf9fe69e72cd2f2330c06303e2a84/pkg/skel/skel.go#L184-L186
None
```release-note
None 
```

fix: give loopback a name

---

OWNERS

Signed-off-by: Valentin Rothberg <vrothberg@redhat.com>
/kind other
Keep the OWNERS file clean.
None
```release-note
None
```

OWNERS: move vrothberg to emeritus approvers

---

contrib/test/ci/system-packages.yml

as well as reorder for readability
/kind ci
```release-note
none
```

ci: update system-packages.yml to install gpgme-devel on fedora

---

contrib/test/ci/system-packages.yml

A few CI tests were failing on RHEL9 due to the SELinux permission issue where the boolean `container_manage_cgroup` variable was not populating the right value. Somehow that boolean variable is getting dropped and the value is always set to true. So avoid setting the value when the distribution is RHEL.
```release-note
None
```

contrib/test/ci: fix SELinux permission issue on RHEL9

---

tutorials/kubernetes.md

General updates to documentation
Fixes #6133 
Consider this a draft, I will read through documentation and issues, and fix more things if anything pops out to me.
```release-note
None
```

docs: general updates

---

internal/lib/restore.go
internal/lib/restore_test.go
internal/oci/oci.go
internal/oci/oci_test.go
internal/oci/runtime_oci.go
internal/oci/runtime_pod.go
internal/oci/runtime_vm.go
internal/oci/suite_test.go
server/container_create.go
server/container_restore.go
server/container_restore_test.go
test/checkpoint.bats
test/mocks/oci/oci.go

/kind feature
Add support to checkpoint and restore containers in pods without infrastructure containers.
None
```release-note
Added support to checkpoint and restore containers in pods without infrastructure containers.
```

Support checkpointing infra less containers

---

contrib/bundle/build
contrib/bundle/install
scripts/get

/kind ci
```release-note
none
```

get script: fix conflist path

---

contrib/cni/11-crio-ipv4-bridge.conflist
internal/version/version.go

bump to v1.26.0

---

scripts/node_e2e_installer

Signed-off-by: Sai Ramesh Vanka <svanka@redhat.com>
Bump
/kind ci
This helps in running the Node E2E tests that are failing to run the `crio-install.service`
Ref: https://testgrid.k8s.io/sig-node-cri-o
```release-note
```

Bump e2e-installer script with the latest commit

---

test/mocks/containerstorage/containerstorage.go

/kind ci
```release-note
none
```

mocks: update with new c/storage mocks

---

internal/version/version.go

version: bump to 1.25.2

---

internal/version/version.go

version: bump to 1.23.5

---

.github/workflows/test.yml
.github/workflows/verify.yml

This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/6505
```release-note
None
```

[release-1.24] Fix GitHub actions CI

---

.github/workflows/test.yml
scripts/release-notes/release_notes.go

/kind ci
We now use the branch directly from GitHub actions, which allows us to set the correct branch on tags.
Fixes https://github.com/cri-o/cri-o/issues/5687
None
```release-note
None
```

Inject release-notes branch from GitHub actions

---

contrib/bundle/build
contrib/cni/11-crio-ipv4-bridge.conflist
contrib/cni/99-loopback.conflist
contrib/test/ci/build/plugins.yml
contrib/test/integration/build/plugins.yml
dependencies.yaml
scripts/versions

Update CNI plugins to their latest release.
None
None
```release-note
Updated CNI plugins to v1.2.0.
```

Update CNI plugins to v1.2.0

---

.github/ISSUE_TEMPLATE/org_member.yml
GOVERNANCE.md
MAINTAINERS.md
README.md
code-of-conduct.md
roadmap.md

more details in each commit
```release-note
none
```

Misc documentation updates

---

.github/workflows/test.yml

This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/6506
```release-note
None
```

[release-1.23] Fix GitHub actions CI

---

contrib/cni/README.md

follow up to https://github.com/cri-o/cri-o/issues/6074#issuecomment-1400921571
```release-note
None
```

contrib/cni: provide more context around file selection

---

internal/storage/runtime.go

/kind bug
There are cases where the container storage unmount has been already (partially) done. This would cause `StopContainer()`  in `server/container_stop.go:76` fail and therefore make containers get stuck in recreation, making their pods stuck in `NotReady`.
We now double check the two c/storage errors `ErrContainerUnknown` and `ErrLayerUnknown`
Somehow related to: https://github.com/containers/podman/issues/11207#issuecomment-920768804
None
Cherry-pick of https://github.com/cri-o/cri-o/pull/6517
Issue: https://issues.redhat.com/browse/OCPBUGS-6582
```release-note
None
```

[1.26] Make storage unmount less strict

---

internal/storage/runtime.go

/kind bug
There are cases where the container storage unmount has been already (partially) done. This would cause `StopContainer()`  in `server/container_stop.go:76` fail and therefore make containers get stuck in recreation, making their pods stuck in `NotReady`.
We now double check the two c/storage errors `ErrContainerUnknown` and `ErrLayerUnknown`
Somehow related to: https://github.com/containers/podman/issues/11207#issuecomment-920768804
None
Cherry-pick of https://github.com/cri-o/cri-o/pull/6517
Issue: https://issues.redhat.com/browse/OCPBUGS-6583
```release-note
None
```

[1.25] Make storage unmount less strict

---

contrib/test/ci/ansible.cfg

This will help us identify the time execution and narrow down the tasks that require caching.
/kind ci
```release-note
None
```

contrib/test/ci: adds time information to tasks

---

go.mod
go.sum
vendor/github.com/containerd/nri/pkg/adaptation/adaptation.go
vendor/github.com/containerd/nri/pkg/adaptation/plugin.go
vendor/github.com/containerd/nri/pkg/adaptation/plugin_linux.go
vendor/github.com/containerd/nri/pkg/adaptation/plugin_other.go
vendor/github.com/containerd/nri/pkg/net/socketpair_unix.go
vendor/github.com/containerd/nri/pkg/net/socketpair_windows.go
vendor/github.com/containerd/nri/pkg/runtime-tools/generate/helpers_linux.go
vendor/github.com/containerd/nri/pkg/runtime-tools/generate/helpers_other.go
vendor/modules.txt

Fix a recently discovered panic/crash.
/kind bug
NRI [commit b3cabdec0657](https://github.com/containerd/nri/commit/b3cabdec06578b193da387b1bee4fd23aea8808e) fixes a recently discovered panic crash. Without that fix and NRI support enabled, a plugin requesting an unsolicited update to one or more containers triggers the bug and causes a crash.
None
```release-note
None
```

go.mod: update github.com/containerd/nri.

---

internal/storage/runtime.go

/kind bug
There are cases where the container storage unmount has been already (partially) done. This would cause `StopContainer()`  in `server/container_stop.go:76` fail and therefore make containers get stuck in recreation, making their pods stuck in `NotReady`.
We now double check the two c/storage errors `ErrContainerUnknown` and `ErrLayerUnknown`
Somehow related to: https://github.com/containers/podman/issues/11207#issuecomment-920768804
None
Cherry-pick of https://github.com/cri-o/cri-o/pull/6517
Issue: https://issues.redhat.com/browse/OCPBUGS-6584
```release-note
None
```

[1.24] Make storage unmount less strict

---

server/container_create_linux.go
test/cgroups.bats

/kind bug
```release-note
fix a bug where CRI-O would fail if Kubelet specified `-1` for swap (which is a valid way of specifying unlimited)
```

[1.24] server: allow for kubelet to specify -1 for swap

---

dependencies.yaml
scripts/versions

bundle: bump to conmon 2.1.6

---

server/container_create_linux.go
server/sandbox_run_linux.go

/kind bug
This was missed from backporting from main
```release-note
none
```

[1.24] server: move StartContainer calls to clarify stage

---

scripts/node_e2e_installer

/kind ci
It will allow to use the OOM killer fixes done in k/k testing, see discussion: https://github.com/kubernetes/kubernetes/pull/113205#issuecomment-1415968592.
This will yet require a bump of the image reference in the test-infra. A commit similar to this one: https://github.com/kubernetes/test-infra/commit/2b30f2e31d90eabcc47f7616e19e3485b09a9f59.
```release-note
NONE
```

Bump the CRI-O commit used for node testing to the tip of main

---

roadmap.md

Updating the roadmap to fix markdown links and do some formatting.
None
None
```release-note
None
```

Fix roadmap links

---

go.mod
go.sum
vendor/github.com/containers/image/v5/docker/body_reader.go
vendor/github.com/containers/image/v5/version/version.go
vendor/modules.txt

Update to c/image 5.24.2 with an updated heuristic to retry on pull failures.
None
```release-note
None
```

Update to c/image 5.24.2

---

completions/fish/crio.fish

/kind ci
Fixes validate-completion CI job
None
None
```release-note
None
```

[CI] Fix validate-completion

---

dependencies.yaml
scripts/versions

/kind cleanup
Update crun to the latest release.
None
None
```release-note
Updated crun to v1.8.1.
```

Bump crun to v1.8.1

---

go.mod
go.sum
vendor/github.com/containerd/nri/pkg/api/mount.go
vendor/github.com/containerd/nri/pkg/runtime-tools/generate/generate.go
vendor/modules.txt

Update NRI dependency to the latest tagged version.
None
```release-note
None
```

go.mod: update github.com/containerd/nri to 0.3.0.

---

contrib/test/integration/system-packages.yml

fixes issues like https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/cri-o_cri-o/6682/pull-ci-cri-o-cri-o-main-ci-cgroupv2-integration/1630978265952817152/artifacts/cgroupv2-integration/cri-o-gather/artifacts/testout.txt
```release-note
none
```

test: add irqbalance dependency

---

go.mod
go.sum
internal/factory/container/device_test.go
test/cdi.bats
vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/annotations.go
vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/cache.go
vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/container-edits.go
vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/container-edits_unix.go
vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/device.go
vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/doc.go
vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/qualified-device.go
vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/spec.go
vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/spec_linux.go
vendor/github.com/container-orchestrated-devices/container-device-interface/pkg/cdi/version.go
vendor/modules.txt

Update github.com/container-orchestrated-devices/container-device-interface to v0.5.4.
None
```release-note
- update github.com/container-orchestrated-devices/container-device-interface to v0.5.4.
```

go.mod: update CDI dependency to 0.5.4.

---

scripts/release-notes/release_notes.go

We also fix the `cosign` tool invocation for cosign >= v2.
None
/cherry-pick release-1.26
```release-note
None
```

Add spdx signature and cert to release notes

---

contrib/test/ci/system-packages.yml
contrib/test/integration/system-packages.yml

fixes issues like https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/cri-o_cri-o/6750/pull-ci-cri-o-cri-o-main-ci-cgroupv2-integration/1638178252549787648/artifacts/cgroupv2-integration/cri-o-gather/artifacts/testout.txt
```release-note
none
```

test: add irqbalance dependency to CI

---

server/metrics/metrics.go

/bug
logrus.Fatalf will cause crio to exit with a non-zero return code. This patch changes the fatal error to an error preventing crio from exiting with a (1) status code. The metrics server is gracefully shutdown on termination.
```release-note
Change metrics endpoint to gracefully shutdown, and move metric server fatal errors to just errors. 
```

log errors on metric server and gracefully terminate metrics endpoint

---

test/irqbalance.bats
test/test_runner.sh

Addresses the integration tests failure for https://github.com/cri-o/cri-o/issues/6751
/kind ci
/kind flake
```release-note
None
```

test: run irqbalance tests serially to avoid race condition

---

internal/version/version.go

[1.24] version: bump to 1.24.5

---

docs/crio.conf.5.md
pkg/annotations/annotations.go
server/container_create_linux.go
test/umask_annotation.bats

/kind bug
Add annotation "io.kubernetes.cri-o.umask" to allowed_annotations under crio.runtime.workloads to set umask for crio container.
Fixes #2701
```release-note
Allow annotation "io.kubernetes.cri-o.umask" to set umask for crio container.
```

Set umask for crio container

---

internal/version/version.go

[1.26] version: bump to 1.26.3

---

internal/oci/container.go
internal/oci/container_test.go
server/container_status.go

/kind other
Return resource status in ContainerStatusResponse
Fixes https://github.com/cri-o/cri-o/issues/5653
Yes
```release-note
Added support to return ContainerResources in ContainerStatusResponse.
```

Update container resources in ContainerStatusResponse

---

contrib/test/ci/setup.yml

/kind ci
```release-note
None
```

contrib/test/ci: cache runc and crun setup unconditionally

---

dependencies.yaml
scripts/versions

Update crun to the latest release.
None
None
```release-note
Updated crun to v1.8.4
```

Bump crun to v1.8.4

---

contrib/test/ci/vars.yml
contrib/test/integration/vars.yml
dependencies.yaml
internal/version/version.go
scripts/versions
server/container_restore_test.go

version: bump version (and cri-tools) to 1.27.0

---

server/container_restore_test.go

Addresses [this](https://github.com/cri-o/cri-o/actions/runs/4730295707/jobs/8394161942?pr=6823) failure 
/kind ci
```release-note
None
```

contrib/test/ci: fix failing tests

---

contrib/test/ci/system-packages.yml
test/crio-wipe.bats
test/ctr.bats
test/helpers.bash
test/image.bats
test/image_remove.bats
test/image_volume.bats
test/inspect.bats
test/inspecti.bats
test/metrics.bats
test/network.bats
test/nri/runtime.go
test/pod.bats
test/seccomp_notifier.bats
test/testdata/Dockerfile
test/testdata/container_config.json
test/testdata/container_config_ping.json
test/testdata/container_redis.json
test/testdata/container_sleep.json
test/testdata/docker-entrypoint.sh

Fixes https://issues.redhat.com/browse/OCPNODE-1535
/kind ci
/kind cleanup
```release-note
None
```

consolidate images used for integration tests

---

.github/workflows/test.yml

/kind other
```release-note
None
```

.github/workflows: auto approve dependabot PRs

---

server/container_restore.go
server/container_restore_test.go
test/checkpoint.bats

/kind bug
This allows that containers can be correctly restored in differently named namespaces, pods and containers.
This changes only updates the metadata from the checkpointed container before passing that information to the restored container.
None
```release-note
None
```

Allow restoring of containers with different names

---

contrib/test/ci/build/cri-tools.yml

This will fix the periodic job for building CI images.
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/37628/rehearse-37628-periodic-ci-cri-o-cri-o-main-periodics-setup-periodic/1651597669568614400
/kind bug
/kind ci
```release-note
None
```

contrib/test/ci/build: use `force:yes` while linking crictl/critest

---

go.mod
go.sum
vendor/github.com/containers/common/pkg/config/containers.conf
vendor/github.com/containers/common/pkg/config/containers.conf-freebsd
vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go
vendor/github.com/containers/common/pkg/sysinfo/numcpu.go
vendor/github.com/containers/common/pkg/sysinfo/numcpu_linux.go
vendor/github.com/containers/common/pkg/sysinfo/numcpu_other.go
vendor/github.com/containers/common/pkg/sysinfo/numcpu_windows.go
vendor/github.com/containers/common/pkg/umask/umask.go
vendor/github.com/containers/common/version/version.go
vendor/modules.txt

/kind bug
None
None
```release-note
```

Update c/common to v0.53.0

---

server/container_create_linux.go

Partially fixes #6833 .
#6833 
```release-note
fix a segfault when a user namespace is requested
```

#6833 user ns: Fix segfault while constructing id mappings

---

.github/workflows/test.yml

This workflow grants a significant amount of authority to the dependabot, which may pose security risks for cri-o down the line.
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token
/kind bug
```release-note
None
```

.github/workflows: remove auto-approve workflow

---

GOVERNANCE.md
OWNERS
OWNERS_ALIASES

/kind other
```release-note
None
```

OWNERS: allow cri-o reviewers to approve dependabot PRs

---

server/container_stop.go
server/sandbox_stop_linux.go

Fixes https://github.com/cri-o/cri-o/issues/6625
Signed-off-by: Sai Ramesh Vanka <svanka@redhat.com>
/kind bug
https://github.com/cri-o/cri-o/issues/6625, https://github.com/cri-o/cri-o/issues/6631
```release-note
None
```

Fix events generated by Evented PLEG

---

OWNERS_ALIASES

I'm nominating myself for the cri-o-reviewers after discussing it with @haircommander 
/kind other
```release-note
None
```

OWNERS: add sohankunkerkar to cri-o-reviewers

---

.github/workflows/test.yml
Makefile
README.md
contrib/bundle/build
install.md
nix/default-ppc64le.nix
scripts/get

/kind ci
This PR has changes to build binaries for the `ppc64le` CPU architecture and the related user documentation changes.
None
```release-note
None
```

Support to build binaries for `ppc64le` architecture.

---

.github/workflows/test.yml
Makefile
dependencies.yaml
hack/govulncheck.sh
server/server.go

/kind ci
```release-note
None
```

.github/worflows: add go vulnerability management check for cri-o

---

docs/crio.8.md
docs/crio.conf.5.md
internal/storage/image.go
internal/storage/image_test.go
pkg/config/config.go
test/helpers.bash

Update CRI-O to include configured pause image in pinned images list. This eliminates the need for users to manually add the pause image to the list when a different image is configured in Kubernetes.
/kind cleanup
```release-note
Add sandbox/pause image to the list of pinned_images if configured by the user.
```

internal/storage: add sandbox/pause image to the list of pinned_images

---

contrib/test/ci/build/plugins.yml
contrib/test/integration/build/plugins.yml
dependencies.yaml
scripts/versions

None
None
```release-note
Updated CNI plugins to v1.3.0.
```

Update CNI plugins to v1.3.0

---

contrib/bundle/build

The file count has to be changed together with the recent CNI plugins update. Now the test passes again to unblock CI.
None
None
```release-note
None
```

Fix GitHub action `bundles` test

---

contrib/test/ci/e2e.yml
contrib/test/integration/e2e.yml

/kind ci
```release-note
None
```

contrib/test: re-enable block volmod tests

---

contrib/test/ci/e2e.yml

/kind ci
```release-note
None
```

contrib/test: reenable Statefulset Basic tests

---

go.mod
go.sum
vendor/github.com/containers/storage/layers.go
vendor/modules.txt

/kind bug
Vendoring https://github.com/containers/storage/pull/1612 for testing.
None
None
```release-note
None
```

[1.23] Vendor c/storage PR #1612

---

docs/crio.8.md
docs/crio.conf.5.md
pkg/config/config.go
test/helpers.bash

Fixes: https://github.com/cri-o/cri-o/issues/6985
```release-note
Updating pause image to 3.9
```

[1.27] *: update sandbox/pause image to 3.9

---

tutorials/kubernetes.md

docs: fix eol test

---

.github/workflows/osff.yml

/kind ci
The scorecard provides more security insights into CRI-O.
None
None
```release-note
None
```

Add OSFF scorecard action

---

test/timeout.bats

fixes https://github.com/cri-o/cri-o/issues/7018
```release-note
none
```

test: fix timeout metric test

---

internal/version/version.go

/kind bug
```release-note
none
```

[1.24] version: bump to v1.24.6

---

internal/oci/oci.go
utils/cmdrunner/cmdrunner.go

fix function name in comment

---

cmd/crio/main.go

Fixes: #6981
```release-note
None
```

main: Added a call to GarbageCollect

---

GOVERNANCE.md

as suggested in https://github.com/cncf/tag-contributor-strategy/issues/436
```release-note
none
```

governance: tweak voting behavior

---

install.md

Update supported version and variable guide for adding repository
None
N/A
```release-note
None
```

Update supported version and variable guide for adding repository

---

server/server.go
test/cpu_load_balancing.bats

/kind bug
previously, some containers were missing the default hooks, as they didn't run on container exit.
```release-note
Fix a bug where the PostStop runtime handler hooks weren't being called when a container exited gracefully
```

OCPBUGS-13980: runtime handler hooks: run default hooks on graceful container exit

---

server/container_create.go

/kind cleanup
Having those fields empty does not make much sense on container creation, so we can error-out early and pre-check them directly at the top of the `CreateContainer` method.
None
None
```release-note
None
```

Pre-check request values on container creation

---

install.md

This just removes Debian Testing and Unstable from the lists of supported OSes because no builds are currently available for them.
See issue #7072
None
None
```release-note
```

Remove non existent Debian builds from install instructions

---

README.md

The CII has been replaced by the OpenSSF, means this is a trivial one.
Fixes https://github.com/cri-o/cri-o/issues/7031
None
```release-note
None
```

Add OpenSSF best practices badge in favor of CII

---

internal/version/version.go

[1.27] version: bump to 1.27.1

---

internal/version/version.go

version: bump to 1.26.4

---

install.md

Add Debian 12 to the list of operating systems for which packages are available.
See #7072
```release-note
None
```

Add Debian 12 as a supported OS to the install doc

---

contrib/test/ci/build/bats.yml
contrib/test/integration/build/bats.yml
dependencies.yaml
scripts/versions

/kind ci
Update bats to the latest release.
None
None
```release-note
None
```

Update bats to v1.10.0

---

ADOPTERS.md

Adds Adobe to `ADOPTERS.md`.
```release-note
None
```

Add Adobe to ADOPTERS.md

---

internal/factory/container/device.go

/kind bug
This is a manual cherry-pick of #7142 
None
```release-note
Fixed an issue preventing the use of block devices with kata containers
```

[1.27] Fix filemode for device

---

contrib/test/ci/system-packages.yml

Include this package for testing the `crun-wasm` workflow in CRI-O
```release-note
None
```

contrib/test/ci: add crun-wasm

---

internal/version/version.go

https://github.com/cri-o/cri-o/issues/6805#issuecomment-1655644811
```release-note
None
```

version: bump to 1.25.4

---

server/container_create_linux.go
server/container_create_linux_test.go

/kind bug
Fixes # https://issues.redhat.com/browse/OCPBUGS-14351
```release-note
Set mount type HostToContainer for mounts that include container storage root
```

 Set mount type HostToContainer for mounts that include container storage root

---

docs/crio.conf.5.md
internal/factory/container/container.go
internal/factory/container/container_test.go
internal/lib/container_server.go
internal/oci/container.go
internal/oci/oci.go
internal/oci/runtime_oci.go
pkg/annotations/annotations.go
pkg/config/config.go
pkg/config/template.go
server/container_create_linux.go
test/common.sh
test/image.bats

This helps to track the runtime paths for different platforms.
/kind feature
```release-note
add platform_runtime_paths option to the runtime handler structure, which allows admins to define specific runtime paths based on different platforms.
```

*: add platform_runtime_paths to RuntimeHandler

---

Makefile
nix/nixpkgs.nix

/kind bug
I had trouble building the binaries--I needed to use host network and change the URL
```release-note
none
```

build-static: misc fixes needed for 1.25.4 generation

---

contrib/test/ci/vars.yml
contrib/test/integration/vars.yml
dependencies.yaml
scripts/github-actions-setup
scripts/versions

/kind cleanup
Update cri-tools to the latest release.
None
None
```release-note
Updated cri-tools to v1.28.0.
```

Update cri-tools to v1.28.0

---

internal/oci/container.go
internal/oci/container_test.go
internal/oci/container_test_inject.go
internal/oci/runtime_oci.go
internal/oci/runtime_oci_test.go
internal/oci/runtime_vm.go
server/container_execsync.go
server/container_remove.go
server/container_remove_test.go
server/container_stop.go
server/container_stop_test.go
server/sandbox_stop_linux.go

This is an manual cherry-pick of #7168
```release-note
Fix a very rare panic from a double closed channel in container stop
```

OCPBUGS-17429: [1.25] oci: simplify stopping code

---

install.md

Correct apt update <package> syntax to apt upgrade <package>
Running `apt update cri-o cri-o-runc` yields the following error message: `E: The update command takes no arguments`
[#7225](https://github.com/cri-o/cri-o/issues/7225)
Fixes #7225 
```release-note
None
```

doc(installation): Update install.md

---

internal/factory/container/container.go

/kind bug
```release-note
none
```

[1.25] factory: use non deprecated LastCap

---

internal/factory/container/device.go
internal/factory/container/device_test.go
test/cdi.bats

/kind other
Take the recently introduced CRI ContainerConfig.CDIDevices field into use as the primary source for CDI device resolution and injection..
None
Note that this commit does not remove CDI device injection using annotations. That will get deprecated and eventually removed in tandem with CDI itself.
```release-note
- add support for CDI device resolution and injection using the dedicated CRI ContainerConfig.CDIDevices field.
```

internal/factory/container: take dedicated CRI ContainerConfig.CDIDevices field into use.

---

contrib/bundle/build
dependencies.yaml
scripts/versions

Adding conmon, we have ppc64le builds for it.
None
None
```release-note
Added `conmon` to `ppc64le` static bundle, updated it to v2.1.7.
```

Add `conmon` to `ppc64le` static bundle

---

tutorials/crictl.md

I was trying to use the tutorial to learn more about CRIO.  I got an error saying the image wasn't found.  It turns out that you should pull the image.  Once you do that, the tutorial works without an issue.  
I added a blurb about pulling the image.
```release-note
NONE
```

add info about pulling image before doing the tutorial

---

go.mod
server/container_create_linux.go

/kind cleanup
```release-note
None
```

server: remove deprecated functionality

---

dependencies.yaml
scripts/versions

Update them to their latest release.
None
None
```release-note
- Updated conmon to v2.1.8.
- Updated crun to v1.8.7.
```

Bump conmon and crun dependencies

---

contrib/bundle/install-paths
scripts/get

Closes: #6666
/kind bug
Handle core-os install path based on the /etc/os-release file
Fixes #6666 
None
```release-note
Update systemd install path for coreos based distribution
(fedora coreos & rhcos)
```

Configure systemd install path based on OS

---

README.md

Mentioning the GitHub project board in the README.md for easier contribution.
None
None
```release-note
None
```

Mention Roadmap GitHub Project in README.md

---

internal/factory/sandbox/infra.go
internal/factory/sandbox/infra_test.go
server/sandbox_run_linux.go

first step towards the PR in compartmentalizing sandbox infra setup  
commit introduces the desired change (work towards #4622)
#4622
~Do not merge yet.~
TODO:
No
```release-note
none
```

move shm setup for sandbox to internal/factory/sandbox

---

README.md

Clarify that we allow backporting features which do not rely on external dependencies.
None
None
```release-note
None
```

Policy: Allow backport of independent features

---

internal/config/cgmgr/cgmgr_linux.go

/kind bug
If we call mgr.Apply() first, libcontainer's cpusetCopyIfNeeded() will copy the parent cpuset and set load balancing to 1 by default. This causes the kernel to set the cpus to not load balanced for a brief moment which causes churn.
instead, create the cgroup and set load balance, then have Apply() copy the values into it.
```release-note
fix a bug in cpuset load balancing where cpusets flip between load balanced and not due to an ordering issue.
```

cgmgr: reorder setting of sched_load_balance for pod cgroup

---

contrib/test/ci/golang.yml
contrib/test/integration/golang.yml

This fixes the periodic image job failure: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-cri-o-cri-o-main-periodics-setup-fedora-periodic/1700660453853630464
/kind ci
```release-note
None
```

contrib/test: fix golang version extraction for CI

---

go.mod
go.sum
internal/oci/oci.go
pkg/config/config.go
server/container_create_linux.go
server/container_create_linux_test.go
vendor/github.com/opencontainers/runtime-spec/specs-go/features/features.go
vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
vendor/modules.txt

if we don't, we risk container creation failures or security holes from the runtime not correctly setting up idmaps
/kind feature
```release-note
Check the runtime supports IDMap support before specifying 
```

config/server: add functions to check IDMap support in runtime

---

internal/version/version.go

version: bump to v1.28.1

---

.github/workflows/test.yml
contrib/bundle/build
contrib/bundle/install
contrib/bundle/test-e2e
dependencies.yaml
scripts/get
scripts/versions

/kind feature
Adding conmon-rs to the static binary bundles.
Fixes https://github.com/cri-o/cri-o/issues/7279
Tests will be still done with conmon-rs `main`.
```release-note
Added conmon-rs to static binary bundle.
```

Add conmon-rs binary to bundle

---

internal/version/version.go

/kind cleanup
The version is old and wrong, so we bump it to the latest development version.
None
None
```release-note
None
```

Bump version to 1.29.0

---

scripts/release-notes/release_notes.go

The version.Version can be unreleased, means that the semver constraint matches no tags any more during the release notes generation.
We now fix that by just listing the last 10 tags per API and using the latest of them.
Fixes the failing release-notes job on `main`.
PTAL @sohankunkerkar 
```release-note
None
```

Fix release notes job

---

internal/storage/runtime.go

/kind cleanup
The parameters to `createContainerOrPodSandbox` pass, individually, all but 2 fields of `RuntimeContainerMetadata`. Using a struct, where the parameters are named, seems much more readable, right now - OTOH that might depend on how the function API vs. metadata JSON format evolves.
Should not change behavior.
None
Just because I was working in this area.
I’m not at all sure the metadata struct and the parameters are going to remain so similar; it’s quite possible this is a bad idea, I’m perfectly fine with this PR being rejected.
```release-note
None
```

RFC: Use RuntimeContainerMetadata for passing container data

---

dependencies.yaml
scripts/versions

/kind feature
Update crun to the latest release.
None
None
```release-note
Updated crun to 1.9.2.
```

Update crun to 1.9.2

---

.github/workflows/nixpkgs.yml
.github/workflows/test.yml
dependencies.yaml

/kind ci
Add a cronjob for updating nixpkgs weekly.
None
None
```release-note
None
```

Add nixpkgs update cron

---

internal/storage/image.go
test/image.bats

Fixes https://github.com/cri-o/cri-o/issues/7335
/kind bug
```release-note
None
```

 internal/storage: compute Pinned field from recently loaded image 

---

cmd/crio/main.go

to ensure on initial installation it is installed.
/kind bug
fixes https://github.com/cri-o/cri-o/issues/6226
```release-note
none
```

main: create parent crio dir before creating clean.shutdown.supported

---

Makefile
dependencies.yaml

/kind ci
Also use the new binary location on the non-rate-limited Google Cloud Bucket.
None
None
```release-note
None
```

Update release-notes to v0.16.1

---

CONTRIBUTING.md

Updates the documentation. There is no `integration` option in the Makefile.
None
None

Update CONTRIBUTING.md document

---

.github/workflows/test.yml

/kind ci
Those binaries can be directly re-used by the packaging repository rather than consuming the whole bundle.
Required for https://github.com/cri-o/cri-o/issues/7380 
None
```release-note
None
```

Upload plain static binaries to GCS bucket

---

install.md

Following https://github.com/containers/storage/issues/1721 we need to have `gcc-go` on the compiling machine, so let's specify it in the documentation.
Related to https://github.com/containers/storage/issues/1721
```release-note
none
```

docs: add `gcc-go` as needed dependency

---

scripts/github-actions-packages

Fixing the gpg release key retrieval for CRIU packages.
None
None
```release-note
None
```

Fix GitHub actions package setup

---

README.md
install.md

We now mention the new packaging effort and link it from the README.md.
None
None
```release-note
None
```

docs: mention new packaging effort

---

internal/config/cgmgr/cgmgr_linux.go
internal/runtimehandlerhooks/default_cpu_load_balance_hooks_linux.go
internal/runtimehandlerhooks/high_performance_hooks_linux.go
test/cgroups.bats
test/cpu_load_balancing.bats

```release-note
fix a bug where the cgroup crun configures is different than that CRI-O sets load balancing/cpu quota on
```

OCPBUGS-20492: highperfhooks: apply cgroup setting to crun cgroup

---

internal/config/cgmgr/cgmgr_linux.go
internal/runtimehandlerhooks/default_cpu_load_balance_hooks.go
internal/runtimehandlerhooks/high_performance_hooks.go
test/cgroups.bats
test/cpu_load_balancing.bats

```release-note
fix a bug where the cgroup crun configures is different than that CRI-O sets load balancing/cpu quota on
```

[1.28] highperfhooks: apply cgroup setting to crun cgroup

---

internal/version/version.go

Bump the version to v1.28.2
Refers to https://github.com/cri-o/cri-o/issues/7411
None
```release-note
None
```

[release-1.28] Bump to v1.28.2

---

internal/version/version.go

version: bump to 1.27.2

---

contrib/test/ci/build/crun.yml
contrib/test/ci/system-packages.yml
contrib/test/integration/build/crun.yml

`libsemanage-devel`  and `yajl-devel` packages are removed from RHEL-9.2, so this PR updates the ansible code and uses the embedded `yajl` for installing crun.
/kind ci
/kind cleanup
```release-note
None
```

contrib/test: update RHEL 9.2 dependencies

---

contrib/test/ci/critest-main.yml
contrib/test/ci/critest.yml
contrib/test/ci/e2e-base.yml
contrib/test/ci/e2e-features.yml
contrib/test/ci/e2e-main.yml
contrib/test/ci/e2e.yml
contrib/test/ci/integration-main.yml
contrib/test/ci/setup-main.yml
contrib/test/ci/setup.yml

Addresses this issue: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_release/45930/rehearse-45930-periodic-ci-cri-o-cri-o-main-periodics-setup-periodic/1727367803297599488
/kind ci
/kind cleanup
```release-note
None
```

contrib/test/ci: update ansible syntax to include_tasks

---

contrib/test/ci/build/crun.yml

/kind ci
/kind cleanup
```release-note
None
```

contrib/test/ci: use embedded yajl for crun installation

---

internal/version/version.go

[1.25] version: bump to 1.25.2

---

contrib/test/ci/e2e-main.yml

https://github.com/ansible/ansible/issues/53626#issuecomment-471556190 has a breaking change in ansible 2.5

tests(ansible): fix tasks environment

---

dependencies.yaml

Follow up to https://github.com/cri-o/cri-o/pull/7463
/kind cleanup
```release-note
None
```

dependencies: fix the CI test path

---

contrib/test/ci/vars.yml

Now https://github.com/opencontainers/runc/pull/4053 has fixed, Let's use the main branch of runc
```release-note
None
```

contrib/test: Use the main branch of runc

---

OWNERS_ALIASES

Adding @kwilczynski to be able to `lgtm` CRI-O PRs. 
Welcome! :partying_face: 
Fixes https://github.com/cri-o/cri-o/issues/7449
None
```release-note
None
```

Add kwilczynski to CRI-O reviewers

---

internal/runtimehandlerhooks/default_cpu_load_balance_hooks_linux.go
internal/runtimehandlerhooks/high_performance_hooks_linux.go
internal/runtimehandlerhooks/runtime_handler_hooks_linux.go

/kind feature
```release-note
add support for cpu load balancing annotation for cgroupv2 
```

runtime handler hooks: add support for cgroupv2 cpu load balancing

---

pinns/src/pinns.c

include the mappings that we tried to write in the error message. Also fix the error type since the uid mapping failure was reported as gid mapping.
/kind cleanup
```release-note
None
```

pinns: improve write_mapping_file errors

---

.github/workflows/nixpkgs.yml
.github/workflows/osff.yml
.github/workflows/test.yml
.github/workflows/verify.yml

/kind ci
Update various CI dependencies prior to a new release. This change also closes several dependency changes that had been open for a while.
Related:
- https://github.com/cri-o/cri-o/pull/7512
- https://github.com/cri-o/cri-o/pull/7519
- https://github.com/cri-o/cri-o/pull/7520
- https://github.com/cri-o/cri-o/pull/7521
- [golangci/golangci-lint: v1.55.2](https://github.com/golangci/golangci-lint/releases/tag/v1.55.2)
None
None
```release-note
None
```

[WIP] Update various CI dependencies prior to a new release

---

test/metrics.bats

The test flakes and hides other issues in the CI. We disable it now and can re-enable when we have a solution for the issue.
Refers to https://github.com/cri-o/cri-o/issues/5601
None
```release-note
None
```

Disable metrics OOM integration test

---

.github/workflows/stale.yml

Feature requests should never become stale
None
None
```release-note
None
```

Do not mark `kind/feature` issues as stale

---

contrib/test/ci/build/plugins.yml
dependencies.yaml
scripts/versions

None
None
```release-note
Updated cni-plugins to v1.4.0.
```

Update cni-plugins to v1.4.0

---

dependencies.yaml
scripts/versions

Buildah is on v1.33.1 as of github.
```release-note
None
```

bump buildah to latest version

---

.github/workflows/integration.yml
.github/workflows/test.yml
scripts/github-actions-setup

/kind ci
Run critest on arm64 hardware.
We're also switching to dedicated cache usage to allow multi-arch caches.
None
None
```release-note
None
```

Run critest on arm64

---

contrib/test/ci/build/conmon.yml
contrib/test/ci/build/cri-tools.yml
contrib/test/ci/build/runc.yml

/kind ci
```release-note
None
```

contrib/test/ci: fix caching while installing packages

---

.github/workflows/integration.yml
.github/workflows/osff.yml
.github/workflows/test.yml

/kind ci
Updating the GitHub actions versions manually since they contain breaking changes.
None
None
```release-note
None
```

Bump actions/upload-artifact and actions/download-artifact actions

---

internal/config/cgmgr/cgmgr_linux.go
internal/config/cgmgr/cgroupfs_linux.go
internal/config/cgmgr/stats_linux.go
internal/config/cgmgr/systemd_linux.go

Use `libcontainer/cgroups` to collect sandbox/container stats instead of `containers/common`. This will be useful once we move on from cAdvisor. 
```release-note
None
```

Use `libctr/cgroups` for stats collection

---

.snyk

/kind other
Add a .snyk file to configure the Snyk security scanner.
Why? At the very least, we want to exclude vendored files and tests from being scanned. As for these paths, many false positives are being reported, most of which we can't and won't be fixing.
None
None
```release-note
None
```

Add a .snyk file to configure the Snyk security scanner

---

go.mod
go.sum
server/sandbox_network.go
test/common.sh
test/helpers.bash
test/pod_annotations_capability.bats
test/testdata/log_cni_plugin.sh
vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
vendor/github.com/cri-o/ocicni/pkg/ocicni/types.go
vendor/github.com/cri-o/ocicni/pkg/ocicni/types_freebsd.go
vendor/github.com/cri-o/ocicni/pkg/ocicni/util_freebsd.go
vendor/github.com/cri-o/ocicni/pkg/ocicni/util_unsupported.go
vendor/modules.txt

Fixes #7122 
Finishing touches of a PR authored by @welsper-young
See #7148 
```release-note
Add pod annotations to RuntimeConfig
```

Add pod annotations to RuntimeConfig

---

completions/fish/crio.fish
docs/crio.8.md
docs/crio.conf.5.md
internal/criocli/criocli.go
pkg/config/template.go

```release-note
mark `selinux` option as deprecated. In the future, CRI-O will use the selinux status of the host to enable SELinux separation in pods 
```

config: mark selinux option as deprecated

---

contrib/test/ci/setup.yml

/kind ci
Force clone cri-tools as we are hitting a cache bug where we are still using 1.28.0
```release-note
NONE
```

force clone critools

---

docs/crio.conf.5.md
pkg/config/template.go

The lists of experimental annotations were out of sync, sync up the lists.
None
```release-note
None
```

Sync the list of allowed_annotations in docs and config template

---

internal/runtimehandlerhooks/high_performance_hooks_linux.go

/kind bug
Turns out the `podManager.GetCgroups()` doesn\'t return any information with regards to its existing resources.
We should put some extra effort in order to find and calculate the actual pod quota.
We need to sum the quota value from each container + the shared cpus and that should be our new pod quota.
None
```release-note
None
```

OCPBUGS-25647: runtimehandler: mixedcpus: fix quota calculation

---

.github/workflows/integration.yml
dependencies.yaml
scripts/github-actions-setup
scripts/versions

/kind ci
Update conmon to the latest release and download the binary directly. 
None
None
```release-note
None
```

Update conmon to v2.1.10

---

.github/workflows/verify.yml
README.md

Adding the badge to highlight the sponsoring.
None
cc @alexellis
```release-note
None
```

Add actuated badge

---

server/container_update_resources.go

/kind bug
After Kubelet restart, the CPU manager (CM) sends UpdateContainerResourcesRequest to all containers, to update their resources.
Since the CM is not aware of the shared CPUs concept, it sends only the guaranteed/isolated cpus. Then we end up with a container without the shared CPUs under its cgroup.
We should append the shared CPUs back upon UpdateContainerResourcesRequest if the container had them initially.
None
```release-note
None
```

OCPBUGS-25926: mixedcpus: append the shared CPUs upon `UpdateContainerResourcesRequest`

---

internal/linklogs/link_logs.go
test/ctr.bats

```release-note
Update linked logs to drop an intermediate directory and append `.log` to the container symlink
```

linked logs: drop intermediate logs directory

---

internal/version/version.go
test/workloads.bats

version: bump to 1.29.1

---

internal/version/version.go
test/workloads.bats

/kind bug
and fix lint
```release-note
none
```

bump to v1.28.3

---

contrib/bundle/test-e2e
internal/version/version.go
test/workloads.bats

/kind bug
and fix lint
```release-note
none
```

version: bump to v1.27.3

---

docs/crio.8.md
internal/criocli/criocli.go

/kind bug
wrong parameter
```release-note
None
```

wrong version-file-persist value

---

.snyk

Signed-off-by: <Kevin Hannon kehannon@redhat.com>
/kind cleanup
Fix synk scans to not pick up vendor dependency
```release-note
NONE
```

update 1.29 with vendor scan fix

---

test/workloads.bats

/kind bug
```release-note
none
```

test: fix lint

---

internal/version/version.go
scripts/release-notes/release_notes.go

as well as carry https://github.com/cri-o/cri-o/pull/7625 so release notes can be generated
```release-note
none
```

Bump to 1.26.5

---

internal/config/node/node_freebsd.go
internal/config/node/node_unsupported.go
internal/config/nsmgr/nsmgr_freebsd.go
internal/config/nsmgr/nsmgr_unsupported.go
internal/config/nsmgr/types_freebsd.go
internal/factory/container/container.go
internal/factory/sandbox/infra.go
internal/factory/sandbox/infra_linux.go
internal/lib/container_server.go
internal/lib/container_server_freebsd.go
internal/lib/container_server_linux.go
internal/lib/sandbox/sandbox.go
internal/lib/sandbox/sandbox_freebsd.go
internal/lib/sandbox/sandbox_linux.go
internal/lib/sandbox/sandbox_unsupported.go
internal/oci/container_freebsd.go
internal/oci/container_freebsd_nocgo.go
internal/oci/container_unsupported.go
pkg/config/config.go
pkg/config/config_freebsd.go
pkg/config/config_linux.go
server/sandbox_run_freebsd.go
server/sandbox_run_unsupported.go
server/sandbox_stop_freebsd.go
server/sandbox_stop_unsupported.go
server/server.go
server/server_freebsd.go
server/server_linux.go

/kind feature
This implements the sandbox lifecycle for FreeBSD, allowing pods to be created and destroyed. I have not included the code for container lifecycle to attempt to reduce the scope of this PR to the minimum. Part of #6492.
None
```release-note
None
```

Implement pod sandbox for FreeBSD

---

scripts/release-notes/release_notes.go

if we're on the 0th patch of a release, we compare against the last minor version
/kind bug
fixes https://github.com/cri-o/cri-o/issues/7755
```release-note
none
```

release-notes: fix startTag calculation

---

internal/runtimehandlerhooks/default_cpu_load_balance_hooks.go
internal/runtimehandlerhooks/high_performance_hooks.go
internal/runtimehandlerhooks/high_performance_hooks_test.go
internal/runtimehandlerhooks/runtime_handler_hooks.go
server/container_create_linux.go

Manual cherry-pick of https://github.com/cri-o/cri-o/pull/7716
```release-note
None
```

[relese-1.28] [manual] OCPBUGS-28589: highperfhooks: add precreate hook for injecting envs

---

.github/workflows/integration.yml

The tests use a huge amount of ram (30GB) and seem to flake heavily. We now use a less parallel approach to try a fix.
None
None
```release-note
None
```

Reduce amount of parallel jobs in integration tests

---

.github/workflows/integration.yml

/kind ci
We still need some slight parallel execution otherwise the integration tests take forever.
None
None
```release-note
None
```

Run integration tests with JOBS=2

---

.github/dependabot.yml

/kind ci
We now use a single large group for the go modules as well as the GitHub actions.
None
None
```release-note
None
```

Group all dependabot updates

---

internal/version/version.go

version: bump to 1.27.4

---

internal/version/version.go

version: bump to 1.28.4

---

internal/version/version.go

version: bump to 1.29.2

---

dependencies.yaml
scripts/versions

/kind ci
It's not used any more because everything is now in the cri-o/packaging repository.
None
None
```release-note
None
```

Remove `crun` from `dependencies.yaml`

---

internal/storage/image.go

/kind cleanup
Just a trivial typo fix 
```release-note
None
```

fix a minor typo in the comment of pullImageImplementation

---

internal/config/seccomp/seccomp_unsupported.go

/kind other
Sync the changes to _unsupported.go file from PR #7719 and other defaults as well. Since the secComp.go file is tag by linux & cgo, vscode isn't happy about adding cgo build tag which throws lot of errors in the podman deps from vendor and its really hard to segregate the error. These changes should make vscode happy & clean.
None
```release-note
None
```

Sync changes of PR#7719

---

test/README.md

This pull-request actualize CNI plugin installation instruction
Fixes #7861
None
None
```release-note
None
```

Update test/README CNI plugins installation instructions

---

server/container_restore.go

/kind cleanup
The utility function can be used directly in CRI-O and there is no need to directly depend on `github.com/containers/podman/v4/pkg/errorhandling`.
Refers to https://github.com/cri-o/cri-o/issues/7866
None
```release-note
None
```

Remove Podman `errorhandling` package dependency

---

server/container_restore.go

/kind cleanup
The logging should be in the scope of the context for maximum traceability.
None
```release-note
None
```

Use contextual logs in `server/container_restore.go`

---

Makefile
dependencies.yaml

/kind ci
Update zeitgeist to the latest release.
None
None
```release-note
None
```

Update zeitgeist to v0.4.4

---

scripts/release-notes/release_notes.go

/kind bug
This should fix using the commit SHA's on: https://cri-o.github.io/cri-o
None
None
```release-note
None
```

Use upcoming version as release notes `endRev`

---

utils/utils.go

/kind cleanup
Removing the dependency to decouple the projects. 
Refers to https://github.com/cri-o/cri-o/issues/7866
None
```release-note
None
```

Remove Podman `lookup` dependency

---

internal/runtimehandlerhooks/high_performance_hooks_test.go

This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/7890
```release-note
None
```

[release-1.27] Change duplicated string values into constants

---

contrib/test/ci/build/plugins.yml
dependencies.yaml
scripts/versions

/kind ci
Bump CNI plugins to the latest release.
None
None
```release-note
None
```

Update cni-plugins to v1.4.1

---

contrib/test/ci/build/bats.yml
dependencies.yaml
scripts/versions

Update bats to the latest release.
None
None
```release-note
None
```

Update bats to v1.11.0

---

install-legacy.md
install.md

We have a few issues where people didn't know that 1.29 kubic is not supported.
Cleaned up our docs to mention this and remove the legacy text and move it to a new file. 
```release-note
NONE
```

add a more clear pointer to what is supported for packaging

---

server/image_pull.go

/kind cleanup
Follow-up on https://github.com/cri-o/cri-o/pull/7887#discussion_r1544648429
None
None
```release-note
None
```

Change `progressGoRoutine` to `consumeImagePullProgress`

---

contrib/test/ci/build/crun.yml
contrib/test/ci/system-packages.yml

/kind cleanup
use wasm-edge and drop crum-wasm from fedora package
```release-note
NONE
```

use wasmedge and drop crun-wasm

---

test/test_runner.sh

/kind cleanup
add -x to bash allows one to trace the commands.
```release-note
NONE
```

add x to set for traceability

---

test/common.sh
test/helpers.bash

as it doesn't exist
/kind cleanup
```release-note
none
```

test: remove references to crioctl

---

scripts/github-actions-setup
test/seccomp_notifier.bats

/kind ci
Enable the tests for arm runners.
None
None
```release-note
None
```

Run seccomp notifier tests on arm

---

contrib/test/ci/build/crun.yml
contrib/test/ci/build/runc.yml
contrib/test/ci/system-packages.yml

/kind ci
Build runc with golang 1.21.
Set up correct path.
```release-note
NONE
```

create go1.21.9 directory

---

test/image.bats

crun-wasm on fedora 36 seems to be out of date.
We want to upgrade to fedora 39 in CI but that may take some time.
We are going to skip this test for now.
```release-note
NONE
```

skip crun-wasm test in image bats

---

.github/workflows/cron.yml

/kind bug
/kind ci
Fixes #7992
```release-note
```

Disable cron jobs forks

---

contrib/test/ci/build/crun.yml
contrib/test/ci/vars.yml

Fixes: https://github.com/cri-o/cri-o/issues/7997
/kind ci
The `HEAD` version was cloning the older codebase of crun leading to a different version of crun (v 1.11.0)
```release-note
None
```

contrib/test/ci: use the main branch for building crun

---

dependencies.yaml
scripts/versions

/kind ci
The version is not used anywhere and we use the latest available in our tests.
None
None
```release-note
None
```

Remove pinned conmon-rs version

---

README.md

We should use a fixed height here instead of width.
None
None
```release-note
None
```

Fix Actuated badge in README.md

---

README.md

Adding basic documentation to outline where the prow images are coming from and where the jobs are defined.
None
None
```release-note
None
```

Add docs about the prow CI images

---

contrib/test/ci/build/cri-tools.yml
contrib/test/ci/build/crun.yml
contrib/test/ci/setup.yml

/kind ci
```release-note
None
```

contrib/test/ci: use force_clone for crun to avoid outdated codebase

---

install.md

I was trying to building cri-o on centos and I found some instructions that didn't work.
Fixes #7996 
```release-note
NONE
```

add powertools repo for gpgme-devel

---

.golangci.yml
cmd/crio/main.go
internal/factory/container/device_linux.go
internal/factory/sandbox/infra_linux.go
internal/iptables/iptables.go
internal/iptables/iptables_linux.go
internal/lib/container.go
internal/lib/sandbox/namespaces.go
internal/nri/nri.go
internal/oci/runtime_oci.go
internal/storage/image.go
pkg/config/config.go
server/container_create.go
server/container_create_linux.go
server/container_remove.go
server/container_restore.go
server/container_start.go
server/container_stop.go
server/image_pull.go
server/inspect.go
server/inspect_test.go
server/sandbox_remove.go
server/sandbox_run_linux.go
server/sandbox_stop.go
server/sandbox_stop_linux.go
server/server.go
server/utils.go
test/nri/nri_test.go
test/nri/runtime.go

/kind cleanup
Enable the linter and fix the reports.
None
None
```release-note
None
```

Enable and fix errorlint

---

scripts/patch-release/patch-release.go
scripts/patch-release/patch-release_test.go

/kind feature
* Add the env arg for the version in patch-release script to manually run the workflow 
Fixes #4003
* add the env for the version to make release from
* remove unused release.go code
None
```release-note
```

add release versions for manual workflow run 

---

go.mod
go.sum
vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
vendor/github.com/opencontainers/runtime-spec/specs-go/features/features.go
vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
vendor/modules.txt

Testing if runtime spec is causing CI failures with crun.
```release-note
NONE
```

update runtime spec to 1.2

---

scripts/patch-release/patch-release.go

/kind ci
We now configure the default user otherwise we'll encounter an error on `git.UserCommit`. The old version will be passed around correctly and we do not rely on the `github.com/cri-o/cri-o/internal/version` package any more.
None
@cri-o/cri-o-maintainers PTAL
cc @olad5 
```release-note
None
```

patch-release: configure the default git user and fix file update

---

internal/version/version.go

Automated version bump to version `1.27.5`
/release-note-none

Bump version to 1.27.5

---

internal/version/version.go

Automated version bump to version `1.28.5`
/release-note-none

Bump version to 1.28.5

---

contrib/test/ci/vars.yml
dependencies.yaml
scripts/versions
test/ctr.bats

/kind ci
Update cri-tools to the latest release.
None
None
```release-note
None
```

Update cri-tools to v1.30.0

---

contrib/test/ci/vars.yml

/kind ci
Disable hooks due to https://github.com/kata-containers/kata-containers/issues/9523
I have this in https://github.com/cri-o/cri-o/pull/7852 but I think it will impact other PRs so I wanted to merge this separately now.
Podman update is on hold until release 1.30 is cut.
```release-note
NONE
```

drop hooks from kata integration tests

---

.github/workflows/release-branch-forward.yml
dependencies.yaml

/kind ci
The workflow should reflect what it actually does rather than how it's scheduled.
None
None
```release-note
None
```

Rename `cron` workflow to `release-branch-forward`

---

pkg/config/template.go

/kind cleanup
It removes the duplicate comment of templateStringCrioRuntimeDefaultRuntime.
None
```release-note
None
```

Remove duplicate comment in crio.conf

---

.github/workflows/nixpkgs.yml
.github/workflows/patch-release.yml

/kind ci
We don't need to run those jobs on forks.
None
None
```release-note
None
```

Run patch release and nixpkgs jobs only on cri-o/cri-o

---

go.mod
go.sum
vendor/github.com/containers/ocicrypt/keywrap/jwe/keywrapper_jwe.go
vendor/github.com/containers/ocicrypt/utils/testing.go
vendor/modules.txt

Update https://github.com/containers/ocicrypt/releases/tag/v1.1.10 to fix a potential DDOS with go-jose.
This will probably need backports.
```release-note
update ocicrypt to v1.1.10.
```

Bump ocicrypt to v1.1.10

---

.golangci.yml
go.mod
go.sum
vendor/github.com/containers/ocicrypt/keywrap/jwe/keywrapper_jwe.go
vendor/github.com/containers/ocicrypt/utils/testing.go
vendor/modules.txt

Bump ocicrypt to v1.1.10 to fix potential issue with go-jose.
```release-note
NONE
```

[release-1.29] Bump ocicrypt to v1.1.10

---

.github/workflows/integration.yml
.github/workflows/nixpkgs.yml
.github/workflows/osff.yml
.github/workflows/patch-release.yml
.github/workflows/release-branch-forward.yml
.github/workflows/stale.yml
.github/workflows/test.yml
.github/workflows/verify.yml

/kind ci
Dependabot is able to update the version comments, means we can pin the actions to certain commits rather than branches.
None
None
```release-note
None
```

Pin GitHub actions commits

---

go.mod
go.sum
vendor/github.com/containers/ocicrypt/Makefile
vendor/github.com/containers/ocicrypt/keywrap/jwe/keywrapper_jwe.go
vendor/github.com/containers/ocicrypt/keywrap/pkcs11/keywrapper_pkcs11.go
vendor/github.com/containers/ocicrypt/spec/spec.go
vendor/github.com/containers/ocicrypt/utils/testing.go
vendor/modules.txt

/kind dependency
Bump ocicrypt to v1.1.10.
```release-note
NONE
```

[release-1.28] Bump ocicrypy to v1.1.10

---

.github/workflows/verify.yml

Fixing the syntax error in the action to make the tests run again.
None
None
```release-note
None
```

Fix verify.yml for GitHub actions

---

go.mod
go.sum
vendor/github.com/containers/ocicrypt/Makefile
vendor/github.com/containers/ocicrypt/keywrap/jwe/keywrapper_jwe.go
vendor/github.com/containers/ocicrypt/keywrap/pkcs11/keywrapper_pkcs11.go
vendor/github.com/containers/ocicrypt/spec/spec.go
vendor/github.com/containers/ocicrypt/utils/testing.go
vendor/modules.txt

Bump ocicrypt to v1.1.10
```release-note
NONE
```

[release-1.27] Bump ocicrypt to v1.1.10

---

.github/workflows/verify.yml

/kind ci
We forgot to pin this action like the others, which is now fixed.
None
None
```release-note
None
```

Pin golangci-lint action

---

internal/version/version.go
pkg/annotations/annotations.go
test/workloads.bats

```release-note
Fix CVE-2024-3154 , a security flaw where CRI-O allowed users to specify annotations that changed specific fields in the runtime. One consequence is a user can change the systemd properties of the container, allowing unsafe properties to be set by the runtime
```

version: bump to 1.29.4

---

dependencies.yaml
scripts/github-actions-setup
scripts/versions

/kind ci
Use their corresponding main branches for testing instead of the pinned version.
None
None
```release-note
None
```

Install `cri-tools` from `master`

---

pkg/annotations/annotations.go
test/workloads.bats

meaning an admin would have to opt-into allowing them to be used
/kind bug
```release-note
Fix a security flaw where CRI-O allowed users to specify annotations that changed specific fields in the runtime. One consequence is a user can change the systemd properties of the container, allowing unsafe properties to be set by the runtime
```

[1.26] annotations: add OCI runtime specific annotations to the AllowedAnnotions

---

pkg/annotations/annotations.go
test/workloads.bats

meaning an admin would have to opt-into allowing them to be used
/kind bug
```release-note
Fix a security flaw where CRI-O allowed users to specify annotations that changed specific fields in the runtime. One consequence is a user can change the systemd properties of the container, allowing unsafe properties to be set by the runtime
```

[1.25] annotations: add OCI runtime specific annotations to the AllowedAnnotions

---

.github/workflows/verify.yml

/kind ci
We forgot to pin that action as well, which is now fixed.
None
None
```release-note
None
```

Pin crate-ci/typos GitHub action

---

contrib/metrics-exporter/dashboard.json

Updates sample Grafana dashboard to changes after #7782.
Sorry that I missed the 1.30 release! I haven't recorded a new GIF, because the panels look mostly the same. Only an axis' scale changed.
I dedicate the changes to the public domain.
```release-note
None
```

dashboard: Update data sources to use new metrics names

---

.github/workflows/tag-reconciler.yml
Makefile
internal/version/version.go
scripts/release/release.go
scripts/release/release_test.go
scripts/tag-reconciler/tag-reconciler.go
scripts/utils/utils.go

/kind ci
This adds a cron workflow and Go script that automatically tags new versions and pushes them to remote.
None
None
```release-note
None
```

Add tag-reconciler for patch releases

---

scripts/tag-reconciler/tag-reconciler.go
scripts/utils/utils.go

/kind cleanup
We now log the actual parsed version as well as if the version already exists on the remote. This provides a bit more information about what is going on.
None
cc @olad5 
```release-note
None
```

Enhance tag reconciler logging

---

.github/workflows/integration.yml

/kind ci
The integration test suite should not run longer.
None
None
```release-note
None
```

Set an integration test timeout

---

go.mod
go.sum
vendor/github.com/containers/ocicrypt/Makefile
vendor/github.com/containers/ocicrypt/keywrap/jwe/keywrapper_jwe.go
vendor/github.com/containers/ocicrypt/keywrap/pkcs11/keywrapper_pkcs11.go
vendor/github.com/containers/ocicrypt/spec/spec.go
vendor/github.com/containers/ocicrypt/utils/testing.go
vendor/modules.txt

Bump ocicrypt to 1.1.10
```release-note
NONE
```

[release-1.26] OCPBUGS-32735: Bump ocicrypt to v1.1.10

---

go.mod
go.sum
vendor/github.com/containers/ocicrypt/Makefile
vendor/github.com/containers/ocicrypt/keywrap/jwe/keywrapper_jwe.go
vendor/github.com/containers/ocicrypt/keywrap/pkcs11/keywrapper_pkcs11.go
vendor/github.com/containers/ocicrypt/spec/spec.go
vendor/github.com/containers/ocicrypt/utils/testing.go
vendor/modules.txt

bump ocicrypt to release 1.25
```release-note
NONE
```

[release-1.25] OCPBUGS-32734: Bump ocicrypt to v1.1.10

---

contrib/test/ci/build/cri-tools.yml
contrib/test/ci/build/crun.yml
contrib/test/ci/system-packages.yml

- Removed python-rhsm-certificates that is no longer present in Fedora 40.
- Cleaned up Ansible code.
/kind ci
/kind cleanup
```release-note
None
```

contrib/test/ci: cleanup archived package for Fedora and ansible code

---

go.mod
scripts/release/release.go

/kind bug
Fixes a patch release workflow issue 
Fixes the "invalid upstream" error that occurs when running the patch release job multiple times
None
```release-note
None
```

Fix rebase branch error on patch release

---

test/image.bats

Fixes https://github.com/cri-o/cri-o/issues/7989
/kind ci
```release-note
None
```

test: reenable crun-wasm test

---

cmd/crio/main.go
pkg/config/config.go
server/server.go

/kind feature
Prints configuration at a runtime.
Fixes #7704.
None
```release-note
Show runtime configuration in the CRI-O logs.
```

Show current runtime configuration

---

scripts/tag-reconciler/tag-reconciler.go

/kind ci
The tag we try to push is not being created beforehand, which is now fixed when applying this patch.
None
None
```release-note
None
```

Create tag on reconciler

---

.github/workflows/integration.yml
.github/workflows/test.yml
.github/workflows/verify.yml

/kind ci
This allows running them manually.
None
None
```release-note
None
```

Allow workflow dispatch for `integration`, `test` and `verify` actions

---

scripts/tag-reconciler/tag-reconciler.go

/kind ci
The tag push alone cannot trigger a GitHub action per: https://github.com/orgs/community/discussions/27028
We have to do it manually directly within the script.
None
None
```release-note
None
```

Run workflow after tag push

---

.github/workflows/tag-reconciler.yml

We need to let the workflow allow running actions.
None
None
```release-note
None
```

Fix tag reconciler permissions

---

server/container_portforward.go

/kind bug
This PR forces cri-o to drain the stream when it finishes port-forward in order to avoid failure to close the connection which causes memory leakage.
The issue details are here.
https://issues.redhat.com/browse/OCPBUGS-30978
> while sending multiple failing port-forwarding requests, crio memory usage increases until the node dies
It had been reported before (https://bugzilla.redhat.com/show_bug.cgi?id=1798193) and fixed in https://github.com/cri-o/cri-o/commit/7016c3e13fe19272d6a680ca2172df02da75a35f.
However at some point, it regressed.
Fixes https://issues.redhat.com/browse/OCPBUGS-30978
```release-note
Fix memory leakage when sending a failing port-forward request
```

Fix memory leakage when port-forwarding

---

Makefile
scripts/github-actions-packages

/kind ci
This fixes the mock CI builds.
Related:
- https://github.com/cri-o/cri-o/pull/8019
None
None
```release-note
None
```

Readd `GOARCH` in `Makefile`

---

.golangci.yml
server/container_create_linux.go

server: use SecureJoin when setting container /etc directory

---

scripts/release/release.go

/kind ci
We have to rebase to the `release-1.x` branch, otherwise we force push to the release branch which auto-merges the proposed version.
None
None
```release-note
None
```

Rebase to correct branch on patch release creation

---

contrib/test/ci/build/plugins.yml
dependencies.yaml
scripts/versions

/kind ci
None
None
```release-note
None
```

Update cni-plugins to v1.5.0

---

scripts/automated-patch-releases.md

This documents the flow for the automated patch releases and the tag-reconciler
None
None
```release-note
None
```

add mermaid flow diagram for patch releases

---

contrib/test/ci/e2e.yml

Skipping the test until https://github.com/cri-o/cri-o/issues/8270 is resolved.
None
None
```release-note
None
```

Skip `[sig-network] KubeProxy should update metric…` test

---

internal/lib/container_server.go
test/restore.bats

/kind bug
A restart of CRI-O will not restore the container volumes before applying this patch. An integration test will now cover that additional scenario.
None
None
```release-note
Fixed container volume restore on CRI-O restart.
```

Fix container volume restore

---

.github/workflows/nixpkgs.yml
.github/workflows/test.yml
dependencies.yaml

/kind ci
Update nix to the latest release.
None
None
```release-note
None
```

Update nix to v2.22.1

---

contrib/test/ci/build/plugins.yml
dependencies.yaml
scripts/versions

/kind ci
Update cni-plugins to the latest release.
None
None
```release-note
None
```

Update cni-plugins to v1.5.1

---

contrib/test/ci/integration.yml
contrib/test/ci/vars.yml
go.mod
pkg/config/reload.go
test/reload_config.bats
vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
vendor/modules.txt

/kind bug
Fixes #8202
```release-note
Reload config should remove pinned images when an empty list is provided
```

Reload config should remove pinned images when an empty list is provided

---

contrib/test/ci/integration.yml
contrib/test/ci/vars.yml
go.mod
go.sum
pkg/config/reload.go
test/reload_config.bats
vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
vendor/modules.txt

This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/8213
```release-note
Reload config should remove pinned images when an empty list is provided
```

[release-1.30] Reload config should remove pinned images when an empty list is provided

---

internal/lib/restore.go

/kind bug
A container checkpoint includes a copy of the logs file. However, this file is currently not used during restore. As a result, the output of `kubectl logs` for a restored container is empty. This pull request extends the current functionality to enable restoring of container logs. This is particularly useful with applications such as Jupyter Notebooks that output an authentication token and access instructions in the container logs.
None
None
```release-note
Enabled restoring container logs from a checkpoint.
```

Restore container logs from checkpoint

---

contrib/test/ci/integration.yml
contrib/test/ci/vars.yml
go.mod
go.sum
pkg/config/reload.go
server/image_status.go
test/reload_config.bats
vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
vendor/github.com/google/go-cmp/cmp/cmpopts/struct_filter.go
vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
vendor/modules.txt

This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/8213
```release-note
Reload config should remove pinned images when an empty list is provided
```

[release-1.29] OCPBUGS-33350: Reload config should remove pinned images when an empty list is provided

---

go.mod
internal/storage/image.go
internal/storage/image_test.go
server/container_create_linux.go
server/container_create_linux_test.go
server/image_remove.go
server/image_remove_test.go
test/oci_volumes.bats

/kind feature
Adding support for the new OCI Volume Source feature.
Refers to https://github.com/kubernetes/enhancements/issues/4639
Requires https://github.com/kubernetes/kubernetes/pull/125659
```release-note
Added support for the Kubernetes OCI / image Volume Source ([KEP-4639](https://github.com/kubernetes/enhancements/issues/4639)).
```

Add OCI/Image Volume Source support

---

contrib/test/ci/vars.yml
dependencies.yaml

/kind ci
We need to use the lateste cri-tools master to make the OCI volume test pass.
Fixes https://github.com/cri-o/cri-o/issues/8404
```release-note
None
```

Use cri-tools `master` for CI tests

---

test/oci_volumes.bats

alongside https://github.com/cri-o/cri-o/pull/8407 
fixes https://github.com/cri-o/cri-o/issues/8404
```release-note
none
```

oci_volumes: require crictl that can request OCI volumes

---

internal/storage/image.go

/kind cleanup
There are several use cases around this, so we do not need to log an error here.
None
None
```release-note
None
```

Remove error log message if mountpoint cannot be found

---

.golangci.yml
cmd/crio/main.go
contrib/metrics-exporter/main.go
internal/client/client.go
internal/criocli/status.go
internal/factory/container/container.go
internal/log/hook_filename.go
internal/oci/container.go

/kind cleanup
Enabling the linters and fixing the reports.
None
None
```release-note
None
```

Enable and fix `gomoddirectives`, `gomodguard`, `noctx` and `wastedassign` linters

---

scripts/github-actions-setup
test/critest.bats

/kind ci
Make the critest suite succeed faster by running them in parallel.
None
None
```release-note
None
```

Run critest in parallel

---

contrib/test/ci/build/runc.yml
scripts/github-actions-setup

/kind ci
Remove the custom golang version used for runc.
None
None
```release-note
None
```

Remove custom golang version for runc

---

contrib/test/ci/vars.yml

can be reverted when https://github.com/containers/crun/issues/1514 is fixed
```release-note
none
```

ci: use crun 1.15 temporarily

---

internal/oci/runtime_oci.go

/kind cleanup
This change aims to reduce unnecessary kill attempts and error logs when terminating containers that have already stopped or don't exist.
```sh
ERRO[2024-07-30 14:13:08.095902227-04:00] Killing container d159549c352df42b630974b3057f09146da18c37e266fe3e3d82f325eb557ebd failed: `/usr/bin/crun --root /run/runc --systemd-cgroup kill d159549c352df42b630974b3057f09146da18c37e266fe3e3d82f325eb557ebd KILL` failed: open pidfd: No such process
: exit status 1 
```
```release-note
None
```

internal/oci: improve container termination process in killContainer

---

.github/workflows/integration.yml
internal/config/seccomp/notifier.go
scripts/github-actions-packages
scripts/github-actions-setup
test/checkpoint.bats
test/ctr.bats
test/helpers.bash

/kind ci
Adding integration tests using the latest crun `main`.
None
Refers to https://github.com/containers/crun/issues/1524 and https://github.com/containers/crun/issues/1207
```release-note
None
```

Add `crun` integration tests

---

.github/workflows/nixpkgs.yml
.github/workflows/patch-release.yml
.github/workflows/release-branch-forward.yml
.github/workflows/tag-reconciler.yml
.github/workflows/test.yml

/kind ci
Fixed token-permission and pinned-dependencies issue which are reported by [scorecard](https://scorecard.dev/viewer/?uri=github.com/cri-o/cri-o).
Part #8476 
```release-note
None
```

Fixed token-permission and pinned-dependencies issue

---

.github/workflows/nixpkgs.yml
.github/workflows/patch-release.yml
.github/workflows/release-branch-forward.yml
.github/workflows/tag-reconciler.yml
.github/workflows/test.yml

/kind ci
Follow-up on https://github.com/cri-o/cri-o/pull/8487, which merged early.
Refers to https://github.com/cri-o/cri-o/pull/8487#pullrequestreview-2244760699
None
```release-note
None
```

Fix space at EOL in actions

---

scripts/github-actions-setup
server/container_remove.go
server/container_remove_test.go
server/container_stop.go
server/container_stop_test.go
server/image_remove.go
server/image_remove_test.go
test/restore.bats

This is the manual cherry-pick of https://github.com/cri-o/cri-o/pull/8431
```release-note
None
```

[release-1.30] Make container and image removal/stop idempotent

---

server/container_remove.go
server/container_remove_test.go
server/container_stop.go
server/container_stop_test.go
server/image_remove.go
server/image_remove_test.go
test/restore.bats

This is the manual cherry-pick of https://github.com/cri-o/cri-o/pull/8431
```release-note
None
```

[release-1.29] Make container and image removal/stop idempotent

---

internal/runtimehandlerhooks/high_performance_hooks_linux.go
server/metrics/metrics.go
server/server.go
server/server_linux.go

/kind cleanup
We can use the existing contexts to avoid using `context.Background()` and `context.TODO()`.
None
None
```release-note
None
```

Pass around more contexts in hooks and metrics

---

server/server.go

/kind cleanup
By so pre-size these to avoid any reallocs to a higher capacity.
```release-note
None
```

Avoid potential reallocs by pre-sizing some slices

---

.github/workflows/nixpkgs.yml
.github/workflows/test.yml
Makefile
dependencies.yaml

/kind ci
Add a matrix to simplify the job.
None
None
```release-note
None
```

Make static build a GitHub action matrix

---

Makefile

/kind ci
This avoids issues when using SELinux enabled systems.
None
None
```release-note
None
```

Make `prettier` target run in a privileged container

---

Makefile

We now add a help for the Makefile:
```
> make help
Usage:
make <target>
help                            Display this help
Build targets:
binaries                        Build all binaries.
test-binaries                   Build all test-binaries
bin/pinns                       Build pinns.
test/copyimg/copyimg            Build the compyimg test binary.
test/checkseccomp/checkseccomp  Build the checkseccomp test binary.
test/checkcriu/checkcriu        Build the checkcriu test binary.
test/nri/nri.test               Build the NRI test binary.
build-static                    Build the static binaries.
crio.conf                       Build the CRI-O configuration.
local-cross                     Build the cross compilation targets.
bin/metrics-exporter            Build the …
```

Add Makefile help

---

contrib/test/ci/e2e-base.yml

CI: install system packages at e2e step

---

.github/workflows/test.yml
dependencies.yaml
internal/lib/checkpoint_test.go
internal/lib/restore_test.go
internal/lib/suite_test.go
pkg/config/config.go
pkg/config/config_freebsd.go
pkg/config/config_linux.go
pkg/config/config_test.go
pkg/config/config_unsupported.go
server/container_checkpoint_test.go
server/container_remove_test.go
server/container_restore_test.go
server/container_update_resources_test.go
server/inspect_ginkgo_test.go
server/suite_test.go

/kind ci
Fixing the CI `test` workflow syntax.
None
None
```release-note
None
```

Fix invalid syntax in test workflow and unit tests

---

contrib/test/ci/vars.yml

/kind ci
This reverts commit 269137ede1379b6ab985d0df3e3a8e3e13f7faa9.
None
None
```release-note
None
```

Revert "contrib: temporarily move to crun 1.15 to fix CI"

---

test/ctr.bats

/kind ci
Enable tests which are now succeeding. 
None
None
```release-note
None
```

Enable more crun integration tests

---

internal/version/version.go

/kind ci
Update the latest release version as well as the supported release branches.
None
None
```release-note
None
```

Update release and branching versions

---

internal/storage/image.go
internal/storage/references/registry_reference.go
test/policy.bats

/kind bug
So we can check a signature of an image that has both a tag and a digest
fixes https://github.com/cri-o/cri-o/issues/8603
```release-note
Fix a bug where signature checking failed if an image specified both a tag and a digest
```

image: serialize RegistryImageReferences when checking signatures

---

pkg/config/config.go
server/utils.go
test/ctr.bats

/kind bug
If an annotation was allowed twice by a workload or runtime it should be allowed in the resulting list. Also fix a comment and add a test
```release-note
fix a bug where an `allowed_annotation` specified twice (in either a workload or runtime) couldn't be used
```

OCPBUGS-42547: config: fix validation of allowed annotations

---

internal/storage/image.go
server/image_pull.go
test/policy.bats

/kind feature
Make the `SignatureValidationFailed` CRI error a bit more prominent when it comes to signature verification. We now use the error also when the `oidcIssuer` or the `subjectEmail` does not match.
None
None
```release-note
Use `SignatureValidationFailed` CRI error for invalid signatures.
```

Use `SignatureValidationFailed` CRI error for invalid signatures

---

contrib/test/ci/integration.yml
contrib/test/ci/vars.yml
test/helpers.bash
test/reload_config.bats

This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/8399
```release-note
None
```

[release-1.30] ci: fix reload config for empty pinned image test 

---

go.mod
go.sum
vendor/modules.txt

Upgrade runc to latest patch.
```release-note
upgrade runc to v1.1.15
```

upgrade runc to v1.1.15

---

go.mod
server/sandbox_stop_freebsd.go
server/sandbox_stop_linux.go

/kind cleanup
Removing the max workers since it's unlikely that we ever hit that value. This also allows to simplify the whole for loop.
We also sync that behavior with the FreeBSD implementation.
None
None
```release-note
None
```

Simplify container stop in sandbox

---

.github/workflows/integration.yml
.github/workflows/test.yml
README.md

/kind ci
We can't use them any more so we now remove it from CI.
None
None
```release-note
None
```

Disable actuated runners

---

internal/factory/container/container.go
internal/factory/container/container_test.go
internal/lib/checkpoint.go
internal/lib/container_server.go
internal/oci/container.go
internal/oci/container_test.go
internal/oci/runtime_vm.go
pkg/annotations/internal.go
server/container_create.go
server/container_create_linux.go
server/container_restore.go
server/container_restore_test.go
server/container_status.go
server/inspect.go
server/sandbox_run_freebsd.go
server/sandbox_run_linux.go

/kind bug
Assorted cleanups identified in reviews of https://github.com/cri-o/cri-o/pull/8212 — parts split from #8590 for a separate discussion.
<s>This is on top of, and includes, #8590 ; eventually I should rebase it after some form of #8590 merges.</s>
None
See individual commit messages for details.
```release-note
None
```

Cleanups on top of #8212, second part

---

server/server.go

/kind cleanup
Especially during reload we do not use the context based logging which can lead into (trivial) information loss. To clean that up we now rely on our internal logging facade instead of using `logrus.…` directly.
None
None
```release-note
None
```

Use context for logging in server

---

internal/criocli/criocli.go
internal/log/interceptors/interceptors.go
internal/log/klog.go
internal/log/log.go
internal/mockutils/mockutils.go
internal/oci/runtime_oci_linux.go
internal/oci/runtime_oci_test.go
pkg/config/template.go
server/container_start.go
server/runtime_status.go
server/sandbox_status.go
test/docs-validation/main.go
utils/errdefs/grpc.go
utils/utils.go

/kind cleanup
Just a style change to follow more modern go practices.
None
None
```release-note
None
```

Convert `interface{}` to `any`

---

pkg/config/config.go
pkg/config/config_test.go

/kind bug
https://github.com/cri-o/cri-o/pull/8744 introduced new validations for TLS options of the stream server, but TLSCA is not a required option and it's allowed to be empty. (sorry I should've noticed it)
https://github.com/cri-o/cri-o/blob/0470ab6ed5d1e0f08565b34feac10bfefc9b8225/server/server.go#L140-L153
None 
```release-note
None
```

Remove validation for TLSCA

---

go.mod
go.sum
test/mocks/ocicni/types.go
vendor/github.com/cri-o/ocicni/pkg/ocicni/ocicni.go
vendor/github.com/cri-o/ocicni/pkg/ocicni/types.go
vendor/modules.txt

vendor cni 0.4.3

---

pkg/config/template.go

/kind cleanup
A small cleanup to use more modern go standards.
None
None
```release-note
None
```

Use `slices.Equal` instead of custom implementation

---

server/container_restore.go
server/container_restore_test.go

/kind ci
Fix the lint report by inverting the logic in the loop.
None
None
```release-note
None
```

Fix container restore lint and unit tests

---

.github/workflows/integration.yml
.github/workflows/test.yml
README.md

This is a manual cherry-pick of https://github.com/cri-o/cri-o/pull/8722
```release-note
None
```

[release-1.31] Disable actuated runners

---

internal/config/nsmgr/types_linux.go
server/sandbox_network.go
test/network.bats

/kind bug
We should not error on sandbox removal if the netns path gets either removed or invalidated. This path allows removing the sandbox and cleans up the stale netns path.
Integration test has been added as well.
None
None
```release-note
Fixed issue when sandbox removal is not possible due to stale or missing network namespace path.
```

Allow to remove pod sandbox on netns removal

---

contrib/test/ci/build/plugins.yml
dependencies.yaml
scripts/versions

/kind ci
None
None
```release-note
None
```

Update cni-plugins to v1.6.1

---

server/container_create.go
server/sandbox_run_linux.go

/kind bug
Fixes #8790 
```release-note
None
```

Only ctx timeout errors detected in the final stage can be ignored in createcontainer or runsandbox operation

---

contrib/test/ci/vars.yml
docs/crio.conf.5.md
internal/oci/oci.go
pkg/config/config.go
pkg/config/template.go
server/sandbox_run_linux.go
test/pod.bats

/kind feature
```release-note
add `default_annotations` to the runtime handler configuration field, allowing admins to specify default annotations to pass to pods
```

config: add default_annotations

---

MAINTAINERS.md
OWNERS_ALIASES
SECURITY_CONTACTS

/kind other
```release-note
none
```

maintainers: promote Sohan and Krzysztof to approvers

---

Makefile

/kind cleanup
This PR removes `.PHONY` from crio.conf, because it actually creates a file.
Also modified `clean` target to include crio.conf. 
```release-note
None
```

Makefile: fixes wrt crio.conf

---

.golangci.yml
internal/config/nsmgr/nsmgr_linux.go
internal/config/nsmgr/types_linux.go
internal/iptables/iptables.go
internal/lib/sandbox/sandbox_linux.go
internal/oci/oci_unix.go
server/utils_test.go
test/checkseccomp/checkseccomp.go

/kind cleanup
Enable new linters which do not report anything. Some linters now support auto-fixing, which got applied as well.
None
None
```release-note
None
```

Enable linters and auto-fix

---

internal/config/seccomp/notifier.go
internal/memorystore/memory_store.go
server/container_events.go

/kind cleanup
Improve `sync.Map` iterators with an implicit call
None
None
```release-note
Improve `sync.Map` iterators with an implicit call
```

Use iterators in a for-range loop

---

.github/workflows/integration.yml
.github/workflows/test.yml
scripts/github-actions-setup

/kind ci
Use the native arm64 runners provided by GitHub.
Fixes https://github.com/cri-o/cri-o/issues/8265
None
```release-note
None
```

Integrate native GitHub arm64 runners

---

internal/oci/runtime_oci.go

/kind other
This PR adds logs for an uninterruptible container.
Currently only the main process is concerned and the child processes are not, but a process having uninterruptible child process also can't be removed.
None
```release-note
None
```

Add warning log for a process having an uninterruptible child.

---

internal/linklogs/link_logs.go
test/ctr.bats

This is a manual cherry-pick of #8968
```release-note
Fix path traversal in CRI-O log handling
```

[release-1.31] CVE: Fix path traversal in CRI-O log handling

---

internal/linklogs/link_logs.go
test/ctr.bats

This is a manual cherry-pick of #8968
```release-note
Fix path traversal in CRI-O log handling
```

[release-1.30] CVE: Fix path traversal in CRI-O log handling

---

internal/linklogs/link_logs.go
test/ctr.bats

This is a manual cherry-pick of #8968
```release-note
Fix path traversal in CRI-O log handling
```

[release-1.32] CVE: Fix path traversal in CRI-O log handling

---

.github/workflows/nixpkgs.yml

/kind ci
Update the cronjob to run monthly, because weekly updates are a bit too fast.
None
None
```release-note
None
```

Change nixpkgs update to monthly

---

internal/oci/container.go
internal/oci/oci.go
internal/oci/runtime_oci.go
internal/oci/runtime_pod.go
internal/oci/runtime_vm.go
server/container_reopen_log.go
test/logs.bats
test/mocks/oci/oci.go

(cherry picked from commit 05296551a060b9c96f0ca9001a0abb37780a5dc3)
cherry picked from https://github.com/cri-o/cri-o/pull/8868
/assign bitoku
/kind bug
Fixes https://github.com/cri-o/cri-o/issues/8815
```release-note
Fix log rotation failure during pod termination
```

[release-1.30] Avoid using UpdateContainerStatus for ReopenContainerLog and add logs tests

---

internal/oci/container.go
internal/oci/oci.go
internal/oci/runtime_oci.go
internal/oci/runtime_pod.go
internal/oci/runtime_vm.go
server/container_reopen_log.go
test/mocks/oci/oci.go

(cherry picked from commit 05296551a060b9c96f0ca9001a0abb37780a5dc3)
cherry picked from https://github.com/cri-o/cri-o/pull/8868
/assign bitoku
/kind bug
Fixes https://github.com/cri-o/cri-o/issues/8815
```release-note
Fix log rotation failure during pod termination
```

[release-1.29] Avoid using UpdateContainerStatus for ReopenContainerLog and add logs tests

---

.github/workflows/test.yml

/kind ci
This PR updates actions/upload-artifacts and actions/download-artifacts and fix the error caused by https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
https://github.com/cri-o/cri-o/actions/runs/13317679781/job/37195572187?pr=8961
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
```release-note
None
```

[release-1.27] Fix build github actions

---

.github/workflows/osff.yml
.github/workflows/test.yml

/kind ci
This PR updates actions/upload-artifacts and actions/download-artifacts and fix the error caused by https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
https://github.com/cri-o/cri-o/actions/runs/13317679781/job/37195572187?pr=8961
```
Error: This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
```
```release-note
None
```

[release-1.28] Fix build github actions

---

install.md

Use crun instead of runc
increment minimum golang version
Update Ubuntu 24.04 requirments
Updating documentation for a first time user.
None
No
```release-note
None
```

Updating install docs

---

server/container_events.go

/kind bug
This patch addresses the race conditions which cause at least one of the crashes in https://github.com/cri-o/cri-o/issues/9004.
The code in GetContainerEvents has two possible race conditions.
1. The deferred broadcastEvents may start and complete in between adding the connection to the store and calling `wg.Add()` which causes an invalid state on the WaitGroup, causing a panic.
2. Multiple messages may be processed by the broadcast before a client goroutine wakes up from the first Done() call and removes itself, leading to multiple Done() calls for a single Add(), which is invalid and causes a panic.
Fixes https://github.com/cri-o/cri-o/issues/9004
```release-note
None
```

server: fix races in GetContainerEvents

---

server/image_status.go

/kind cleanup
We already have debug level interceptors to log the response, so we don't need to do an additional info log.
Fixes https://github.com/cri-o/cri-o/issues/9029
None
```release-note
Removed image status `info` log message for the response, we already provide that information in the `debug` logs.
```

Drop image status log message

---

dependencies.yaml
scripts/versions

/kind ci
Update conmon in CI to the latest release.
None
None
```release-note
None
```

Update conmon to v2.1.13

---

server/image_remove.go
server/image_status.go

/kind cleanup
We should not need to log an error if the error is `nil` or if an artifact got not found.
None
None
```release-note
None
```

Improve artifact error logs

---

Makefile

Fixing the failing test on `main` by fixing the download location to point to GitHub.
None
None
```release-note
None
```

Fix release notes download location

---

Makefile

/kind other
This PR adds make target to fix the lint issues.
```release-note
None
```

Add lint-fix target

---

.github/workflows/integration.yml
.github/workflows/patch-release.yml
.github/workflows/release-branch-forward.yml
.github/workflows/tag-reconciler.yml
.github/workflows/test.yml
.github/workflows/verify.yml
dependencies.yaml

/kind ci
Use the required go version directly from go.mod.
None
None
```release-note
None
```

Use go version requirements from go.mod

---

internal/criocli/wipe.go
test/crio-wipe.bats

Signed-off-by: Pannaga Rao Bhoja Ramamanohara
/kind bug
```release-note
Prevent multiple crio wipes on reboot
```

OCPBUGS-44780: crio wipe should remove storage only once per reboot

---

server/container_create_linux.go
server/safemount_linux.go

/kind cleanup
Small follow-up on https://github.com/cri-o/cri-o/pull/9050
None
None
```release-note
None
```

Fix comment location about error message

---

server/masked_paths.go

/kind cleanup
Optimizing the loop by using a better API.
None
None
```release-note
None
```

Use `strings.SplitSeq` instead of `strings.Split`

---

MAINTAINERS.md
OWNERS_ALIASES
SECURITY_CONTACTS

/kind other
I am removing myself as I no longer work for Red Hat.
None
None
```release-note
None
```

Remove Krzysztof Wilczyński as maintainer

---

go.mod
go.sum
vendor/github.com/containers/storage/drivers/quota/projectquota_supported.go
vendor/modules.txt

/kind bug
update from c/storage crio-1.31 branch to fetch the PR https://github.com/containers/storage/pull/2129.
https://issues.redhat.com/browse/OCPBUGS-53284
```release-note
None
```

[release-1.31] OCPBUGS-53284: Update c/storage

---

go.mod
go.sum
vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go
vendor/modules.txt

/kind bug
This PR bumps c/common so that the change about /etc/crypto-policies/config is included.
- https://github.com/containers/common/pull/1667
Fixes https://issues.redhat.com/browse/OCPBUGS-53457
```release-note
Fixed the issue that /etc/crypto-policies/config in a container isn't updated.
```

OCPBUGS-53457: [release-1.28] Cherry-pick changes from containers/common project

---

test/mocks/containerstorage/containerstorage.go
test/mocks/criostorage/criostorage.go
test/mocks/ociartifact/ociartifact.go

/kind ci
Update the mocks for the unit tests.
None
None
```release-note
None
```

[release-1.32] Update mocks

---

test/mocks/containerstorage/containerstorage.go
test/mocks/criostorage/criostorage.go

/kind cleanup
The unit tests failed because of this.
```release-note
None
```

Run make mockgen

---

go.mod
go.sum
internal/ociartifact/store.go
vendor/github.com/CloudNativeAI/model-spec/LICENSE
vendor/github.com/CloudNativeAI/model-spec/specs-go/v1/annotations.go
vendor/github.com/CloudNativeAI/model-spec/specs-go/v1/config.go
vendor/github.com/CloudNativeAI/model-spec/specs-go/v1/mediatype.go
vendor/modules.txt

/kind feature
Adding support for CNAI models.
None
Fixes https://github.com/cri-o/cri-o/issues/9127
```release-note
Added support for handling CNAI models from OCI artifacts.
```

Add support for CNAI models

---

internal/criocli/wipe.go
test/crio-wipe.bats

Signed-off-by: Pannaga Rao Bhoja Ramamanohara
/kind bug
```release-note
Prevent multiple crio wipes on reboot
```

 [release-1.31]: OCPBUGS-55092: crio wipe should remove storage only once per reboot

---

internal/lib/stats/cpu_metrics.go
internal/lib/stats/descriptors.go
internal/lib/stats/memory_metrics.go
internal/lib/stats/metrics.go
internal/lib/stats/network_metrics.go
internal/lib/stats/stats_server_linux.go
test/mocks/containerstorage/containerstorage.go
test/mocks/criostorage/criostorage.go

/kind cleanup
This PR cleans up the metrics code and removes unavailable metrics (cpuLoad, disk, diskio, misc, and process) which is found in https://kubernetes.slack.com/archives/CAZH62UR1/p1743786431644619?thread_ts=1743403344.323189&cid=CAZH62UR1.
If https://github.com/kubernetes-sigs/cri-tools/pull/1815 is merge, I can write an e2e test for this.
```release-note
None
```

Refactor metrics descriptors

---

internal/storage/image.go

/kind bug
fix schema v1 images not resolve to image ID error
https://issues.redhat.com//browse/OCPBUGS-42844
```release-note
None
```

OCPBUGS-42844: fix schema v1 images not resolve to image ID error

---

contrib/test/README.md
contrib/test/ci/integration-main.yml

/kind cleanup
Reflected the comment https://github.com/cri-o/cri-o/pull/9086#discussion_r2036194643
```release-note
None
```

Add README for CI playbooks and remove cri-tools task

---

internal/criocli/wipe.go
test/crio-wipe.bats

Signed-off-by: Pannaga Rao Bhoja Ramamanohara
/kind bug
```release-note
Prevent multiple crio wipes on reboot
```

[release-1.29]: OCPBUGS-44780: crio wipe should remove storage only

---

go.mod
go.sum
vendor/github.com/containers/common/pkg/subscriptions/subscriptions.go
vendor/modules.txt

Revert https://github.com/cri-o/cri-o/commit/f5008502a9dbda3be478f5c18e1eee23a4b39620 in favor of https://issues.redhat.com/browse/OCPBUGS-53457?focusedId=27087963&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-27087963
```release-note
Reverted `Fixed the issue that /etc/crypto-policies/config in a container isn't updated.` to respect the current behavior
```

[Release-1.28] revert c/common bump

---

server/container_create.go
server/container_create_freebsd.go
server/container_create_linux.go
server/container_create_linux_test.go

/kind cleanup
This PR refactors addOCIBindMounts to reduce the complexity of arguments.
```release-note
None
```

Refactor addOCIBindMounts

---

scripts/github-actions-setup

Fixing the runner setup by enabling the right kernel module.
None
None
```release-note
None
```

Fix GitHub actions CI test setup

---

test/timeout.bats

/kind ci
Fixes https://github.com/cri-o/cri-o/issues/9195
None
```release-note
None
```

Improve timeout integration tests

---

dependencies.yaml
internal/version/version.go

Prepare for the 1.33.0 release.
None
/hold
for further items as part of the milestone.
```release-note
None
```

Add v1.33 to supported versions

---

contrib/test/ci/build/plugins.yml
dependencies.yaml
scripts/versions

/kind ci
None
None
```release-note
None
```

Update CNI plugins to v1.7.1

---

internal/ociartifact/impl.go
internal/ociartifact/store.go
internal/ociartifact/store_test.go
internal/storage/image.go
test/mocks/ociartifact/ociartifact.go
test/oci_artifacts.bats

/kind feature
This PR adds multi-architecture OCI artifact support.
Fixes [OCPNODE-3240](https://issues.redhat.com/browse/OCPNODE-3240)
Fixes #9141 
```release-note
Added multi-architecture artifacts support.
```

Support multi arch artifact

---

dependencies.yaml
internal/version/version.go

/kind cleanup
v1.33.0 is out now, we can switch to v1.34.0 as development version.
None
None
```release-note
None
```

Switch to v1.34.0 as development version of `main`

---

.github/workflows/integration.yml
.github/workflows/test.yml
Makefile
test/test_runner.sh

/kind ci
This PR adds coverage reports from:
integration tests (12)
unit tests (3)
Fixes #9199
```release-note
None
```

Add coverage report from integration tests

---

test/checkpoint.bats

/kind ci
This extends the checkpoint/restore test to ensure that the container log file (crictl logs) is restored correctly.
Trying to reproduce https://issues.redhat.com/browse/OCPBUGS-55963
No
```release-note
None
```

Extend checkpoint/restore test for container logs

---

internal/config/apparmor/apparmor_linux.go

/kind cleanup
This PR changes the error message to include the original errors.
related to:
- https://github.com/cri-o/cri-o/pull/9123
```release-note
None
```

Pass down apparmor errors

---

test/test_runner.sh

Retrying is not always a solution, but considering the number of occurrence of quay 502, I think it's better to have.
```release-note
None
```

Retry failed bats tests

---

internal/oci/runtime_oci.go

This reverts #9246
The actual fix should be in [conmon](https://github.com/containers/conmon/pull/566) and not in CRI-O.
/kind cleanup
```release-note
None
```

[revert] internal/oci: fix terminal resize race condition

---

go.mod
nix/nixpkgs.json
roadmap.md

/kind bug
Fixes #9181 
```release-note
Fixed segmentation fault when trying to create a lot of pods at a time.
```

Bump go version to 1.24.3

---

server/container_create_linux.go

/kind cleanup
This prevents falling back when it failed to mount artifacts with non-retryable error (= errors except for NotFoundError).
Fixes #9165 
```release-note
None
```

Fix error handling of mountArtifact

---

completions/fish/crio.fish
docs/crio.8.md
docs/crio.conf.5.md
internal/criocli/criocli.go
internal/storage/image.go
pkg/config/config.go
pkg/config/template.go

This PR deprecates insecure-registries, which causes unnecessary DNS resolution.
part of #9225 
```release-note
Deprecate `insecure_registries` config.
```

Deprecate insecure_registries config

---

OWNERS_ALIASES

/kind other
Fixes #9314 
```release-note
None
```

Add @bitoku as reviewer

---

internal/lib/container_server.go
internal/lib/sandbox/sandbox.go
internal/lib/sandbox/sandbox_test.go
server/container_portforward.go
server/sandbox_status.go
server/server.go

As we hit cases of deadlock when a sandbox is stuck stopping
/kind bug
```release-note
Fix a potential deadlock when an infra container is taking a long time to exit and the sandbox's readiness is blocked on the infra container's opLock
```

OCPBUGS-58833: [1.29] sandbox: use created/stopped instead of infra container for readiness

---

server/nri-api.go

/kind bug
A missing option prevented us from honoring CDI device injection by NRI plugins during container adjustment.
None
```release-note
Fixed a bug which caused CDI injection by NRI plugins to not being honored. NRI plugins are now able to inject CDI devices into containers.
```

server/nri: allow NRI plugins to inject CDI devices.

---

install.md
roadmap.md

/kind ci
Update markdown in {install,roadmap}.md to make them pass verification by prettier. 
None
```release-note
None
```

[release-1.33] update markdown to make prettier happy.

---

internal/oci/runtime_pod.go
test/conmon_track.bats

/kind feature
Tracks conmon-rs just like as conmon
Close #9336 
```release-note
Added feature to track conmon-rs processes and emit containers_stopped_monitor_count{name="$ctr_name"} metric when it's stopped. 
```

OCPNODE-3423: Track conmon-rs process same as conmon

---

internal/runtimehandlerhooks/high_performance_hooks_linux.go
internal/runtimehandlerhooks/high_performance_hooks_test.go
internal/runtimehandlerhooks/runtime_handler_hooks_linux.go
internal/runtimehandlerhooks/runtime_handler_hooks_unsupported.go
pkg/config/config.go
server/container_create.go
server/container_start.go
server/container_stop.go
server/sandbox_run_linux.go
server/server.go
test/exec_cpu_affinity.bats

/kind feature
This implements https://issues.redhat.com/browse/OCPNODE-2864
Fixes https://issues.redhat.com/browse/OCPNODE-2864
```release-note
Added `exec_cpu_affinity` type which can specify cpu where exec command runs.
```

OCPNODE-2864: Set ExecCPUAffinity

---

server/sandbox_network.go
test/network.bats

This fix leverages CNI cache files to retrieve network attachments and call CNI DEL when network namespace files are missing, preventing IP address leaks.
/kind bug
This will fix the issue mentioned in https://github.com/cri-o/cri-o/pull/9301#discussion_r2244988147
```release-note
server: ensure CNI teardown prevents IP leaks with missing netns
```

server: ensure CNI teardown prevents IP leaks with missing netns

---

server/masked_paths.go

/kind cleanup
thermal_throttle paths in maked paths are already included in c/common default masked paths.
The code is no longer needed.
```release-note
None
```

Remove thermal_throttle masked paths.

---

internal/config/seccomp/seccomp.go
internal/config/seccomp/seccomp_test.go
internal/oci/oci.go
internal/oci/oci_test.go
pkg/config/config.go
pkg/config/reload.go
pkg/config/template.go
server/container_create.go
server/sandbox_run_linux.go
test/helpers.bash
test/reload_config.bats
test/seccomp_runtime_handler.bats

/kind feature
Allow configuration of a default seccomp profile per runtime.
Fixes #5715
```release-note
Allow configuration of a default seccomp profile per runtime.
```

Add runtime handler seccomp profile

---

contrib/test/ci/ansible.cfg
contrib/test/ci/build/parallel.yml

/kind ci
Fix ansible error and use faster mirror server instead of ftp.gnu.org.
This fix was verified in
https://github.com/openshift/release/pull/69219
```release-note
None 
```

Fix periodic setup job

---

.github/workflows/nixpkgs.yml
.github/workflows/test.yml
.github/workflows/verify.yml
.golangci.yml
Makefile
contrib/test/ci/build/bats.yml
contrib/test/ci/build/plugins.yml
dependencies.yaml
hack/govulncheck.sh
internal/criocli/documentation.go
internal/lib/stats/cpu_metrics.go
internal/runtimehandlerhooks/high_performance_hooks_linux.go
internal/runtimehandlerhooks/utils_linux.go
scripts/versions
server/metrics/metrics.go
test/apparmor.bats
test/irqbalance.bats

/kind ci
Update the third party dependencies from dependencies.yaml.
None
None
```release-note
None
```

Update third party dependencies

---

Makefile

/kind cleanup
Removing vars which are not used anymore.
None
None
```release-note
None
```

Remove unused code from Makefile

---

.github/workflows/integration.yml
.github/workflows/test.yml
.github/workflows/verify.yml

/kind ci
Automatically cancel parallel runs for a single PR.
None
None
```release-note
None
```

Actions: cancel parallel runs for a single PR
